### ISSUE TITLE
Set init process

### ISSUE THREAD

**Issue by mhausenblas** [cri-o/cri-o#1242]
Potentially a feature request, for now I'm unsure if it might already be possible: how can one specify a process to be used as the PID 1 in the container, akin to `docker run --init …`?

**Comment by mhausenblas** [comment]
Thanks for the clarification. Maybe we should write a post on our [blog](https://medium.com/cri-o) to demonstrate how that works exactly, in practice? WDYT?

**Comment by wking** [comment]
> Maybe we should write a post on our blog to demonstrate how that works exactly…

In case it helps, you configure the pause container [here][1] or [here][2] and enable shared PID namespaces [here][3] or [here][4].  There doesn't seem to be an option yet for “make the containers new PID namespaces underneath the pod PID namespace”, which would be nice to have (standard containers would be more isolated but the infra container could still reap them).

And there's also [a Kubernetes config that disables PID namespaces][5], in which case you won't be able to set a PID 1 in any container (they'll all share the host's).

[1]: https://github.com/kubernetes-incubator/cri-o/blame/v1.9.0/docs/crio.conf.5.md#L143
[2]: https://github.com/kubernetes-incubator/cri-o/blame/v1.9.0/docs/crio.8.md#L93
[3]: https://github.com/kubernetes-incubator/cri-o/blame/v1.9.0/docs/crio.conf.5.md#L90
[4]: https://github.com/kubernetes-incubator/cri-o/blame/v1.9.0/docs/crio.8.md#L97
[5]: https://github.com/kubernetes-incubator/cri-o/blob/v1.9.0/server/container_create.go#L927-L930

**Comment by rhatdan** [comment]
@mhausenblas @mrunalp @wking @runcom Since we can now share the pidnamespace should we write that blog?

**Comment by mhausenblas** [comment]
I think that would be awesome @rhatdan!

**Comment by vijaykumark** [comment]
@mhausenblas @rhatdan  Did someone write a blog on it already?
Does adding `shareProcessNamespace` flag in pod spec work the same way as `docker run --init` as mentioned in the [k8s docs](https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/)?

**Comment by mhausenblas** [comment]
> Did someone write a blog on it already?

Not sure but I don't think so.

**Comment by rhatdan** [comment]
I don't think this does it now.

**Comment by rhatdan** [comment]
@mhausenblas Is this still something you want?
@mrunalp Is this something we should support?

**Comment by haircommander** [comment]
k8s supports private pid namespaces, and we support mounting the proper directories for systemd to function inside a container. closing this as such. please reopen if you disagree
