### ISSUE TITLE
crictl exec inside untrusted runtime script

### ISSUE THREAD

**Issue by kfox1111** [cri-o/cri-o#1276]
**Description**

I'm attempting to run clear containers in a cri-o trusted container.

I setup a shell script at the configured "runtime_untrusted_workload", that:
calls:
```
crictl ps to find the container id of a given k8s pod uuid.
crictl exec into that container to run the real runtime_untrusted_workload script.

The goal being, the untrusted runtime takes a lot of binaries/libraries/kernel/initrd/etc stuff, and shipping it all with a trusted container would greatly ease the management of the untrusted container runtime.

**Describe the results you received:**

Certain calls (likely status calls) block forever on the crictl ps. I suspect the cri-o process is not reenterent during this case.

**Describe the results you expected:**

crictl calls should not block but return properly.

**Output of `crio --version`:**

```
crio --version
crio version 1.9.1-dev
commit: "5321ae20e4428093cdadb80f550e872f75006c32"
```

**Comment by rhatdan** [comment]
@kfox1111 Are you still having this issue?
@umohnani8 PTAL

**Comment by kfox1111** [comment]
I have not had a chance to test this since. I switched to use nsenter as a workaround and it has been working pretty well.

**Comment by umohnani8** [comment]
@kfox1111 could you try this out with the latest version of cri-o and let us know if you are still having an issue?

**Comment by umohnani8** [comment]
@kfox1111 are you still seeing this issue?

**Comment by kfox1111** [comment]
I have not gotten a chance to ever get back to trying this use case again. I still think it would be useful to get working though.

**Comment by kfox1111** [comment]
For those that want to try, might be able to implement this with nsenter instead.

**Comment by haircommander** [comment]
it's unclear to me whether this problem still exists. We don't have the distinction between trusted and untrusted runtimes. If someone finds a similar issue (hang on `crictl ps`) in kata or similar runtime, please reopen this issue
