### ISSUE TITLE
server: The watcher does not get all containers stopped events

### ISSUE THREAD

**Issue by sboeuf** [cri-o/cri-o#1418]
While I was debugging #1334, I have realized why the k8s e2e testing was not working on my PR. The reason being that I was assuming the watcher to get events for every container being stopped. Unfortunately, this assumption was wrong because after putting some logs in the watcher, I have observed that not  all of them where triggering events. I have simplified my PR in order to workaround this issue, but I think it would worth solving it since I think the expectation for the watcher is that it should not miss any container being stopped. If it's not, then go ahead and close this issue.

I was running `Kubectl client [k8s.io] Kubectl run default should create an rc or deployment from an image  [Conformance]` when I have been able to see this issue.

**Comment by umohnani8** [comment]
@sboeuf @mrunalp is this still an issue?

**Comment by sboeuf** [comment]
@umohnani8 I would say so, but I haven't looked at this code in a long time now...
