### ISSUE TITLE
Make localintegration fails the first time

### ISSUE THREAD

**Issue by umohnani8** [cri-o/cri-o#1462]
**Description**

Make localintegration fails the first time. It works on the second attempt and runs through the tests.

**Steps to reproduce the issue:**
1. As root run, `make localintegration TESTFLAGS=test/ctr.bats`

**Describe the results you received:**

```
➜  cri-o git:(master) ✗ sudo make localintegration TESTFLAGS=test/ctr.bats 
[sudo] password for umohnani: 
rm -f "/home/umohnani/go/src/github.com/kubernetes-incubator/cri-o/_output/.gopathok"
rm -rf _output
rm -f docs/*.5 docs/*.8
rm -fr test/testdata/redis-image
find . -name \*~ -delete
find . -name \#\* -delete
rm -f bin/crio
make -C conmon clean
make[1]: Entering directory '/home/umohnani/go/src/github.com/kubernetes-incubator/cri-o/conmon'
rm -f conmon.o cmsg.o ../bin/conmon
rm -f config.h
make[1]: Leaving directory '/home/umohnani/go/src/github.com/kubernetes-incubator/cri-o/conmon'
make -C pause clean
make[1]: Entering directory '/home/umohnani/go/src/github.com/kubernetes-incubator/cri-o/pause'
rm -f pause.o ../bin/pause
make[1]: Leaving directory '/home/umohnani/go/src/github.com/kubernetes-incubator/cri-o/pause'
rm -f test/bin2img/bin2img
rm -f test/copyimg/copyimg
rm -f test/checkseccomp/checkseccomp
touch "/home/umohnani/go/src/github.com/kubernetes-incubator/cri-o/_output/.gopathok"
touch: cannot touch '/home/umohnani/go/src/github.com/kubernetes-incubator/cri-o/_output/.gopathok': No such file or directory
make: *** [Makefile:62: .gopathok] Error 1
```

**Describe the results you expected:**
Should run the tests in the first attempt.

**Output of `crio --version`:**

```
➜  cri-o git:(master) ✗ crio --version
crio version 1.10.0-dev
commit: "d2dc013c489b93352d69e14112b8e6d7cd49b510"
```

**Comment by wking** [comment]
On Tue, Mar 20, 2018 at 05:07:14PM +0000, Urvashi Mohnani wrote:
> touch: cannot touch '/home/umohnani/go/src/github.com/kubernetes-incubator/cri-o/_output/.gopathok': No such file or directory

I expect we want a $(GOPATH) order-only dependency for rules like [1]
that may create something beneath $GOPATH but are not capable of
creating the $GOPATH directory itself.

[1]: https://github.com/kubernetes-incubator/cri-o/blob/0fb585abb483d8b8798a9ab27f8cb73bb1c0d7ca/Makefile#L57-L62

**Comment by rhatdan** [comment]
@umohnani8 Can we close this one now?

**Comment by umohnani8** [comment]
@rhatdan yeah I still see it failing, but haven't dug into it.

**Comment by haircommander** [comment]
I am not seeing this error anymore. We call the `clean`, `binaries` and `test-binaries` targets now. It seems the `binaries` target is creating the gopathtok now. closing as such, please reopen if you disagree
