### ISSUE TITLE
Default pause container does not work on non-amd64 architectures

### ISSUE THREAD

**Issue by kars7e** [cri-o/cri-o#1512]
**Description**

Default `crio.conf` config file (I've checked Ubuntu `ppa` repo and the one installed via `make install.config`) uses `kubernetes/pause` image which is amd64 only. This breaks pod creation on other architectures, e.g., ARM. The workaround is straight-forward, one needs to replace the image with architecture specific, e.g.:
```
# pause_image is the image which we use to instantiate infra containers.
pause_image = "k8s.gcr.io/pause-arm:3.1"
```
However, I've learned it the hard way. Following [this tutorial](https://github.com/kubernetes-incubator/cri-o/blob/86b61d44cfe7de0f4095877d303c4d1b3aa2ec06/tutorial.md), I received a quite misleading error: 
```
root@tinker-0:/var/go/src/github.com/kubernetes-incubator/cri-o# crictl runp test/testdata/sandbox_config.json
FATA[0001] run pod sandbox failed: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_podsandbox1_redhat.test.crio_redhat-test-crio_1(d8961018f0d124127513859bb34e60f39ceae6ab594ee22cee14ad2d6b1df3a7): failed to Statfs "/proc/0/ns/net": no such file or directory
```
I also checked CRI-O logs (first switching to `--log-level` to `debug`), and they were not very helpful:
```
Apr 07 20:36:19 tinker-0 crio[4853]: time="2018-04-07 20:36:19.656046187-07:00" level=debug msg="Received container pid: 4902"
Apr 07 20:36:19 tinker-0 crio[4853]: time="2018-04-07 20:36:19.700163814-07:00" level=debug msg="event: "/var/run/crio/exits/209d030a898afc1076be5447bee582efe1941306281273009ae2f21918f8036f.3CUVGZ": CREATE"
Apr 07 20:36:19 tinker-0 crio[4853]: time="2018-04-07 20:36:19.700260356-07:00" level=debug msg="container or sandbox exited: 209d030a898afc1076be5447bee582efe1941306281273009ae2f21918f8036f.3CUVGZ"
Apr 07 20:36:19 tinker-0 crio[4853]: time="2018-04-07 20:36:19.700657023-07:00" level=debug msg="event: "/var/run/crio/exits/209d030a898afc1076be5447bee582efe1941306281273009ae2f21918f8036f.3CUVGZ": WRITE"
Apr 07 20:36:19 tinker-0 crio[4853]: time="2018-04-07 20:36:19.702512904-07:00" level=debug msg="event: "/var/run/crio/exits/209d030a898afc1076be5447bee582efe1941306281273009ae2f21918f8036f.3CUVGZ": WRITE"
Apr 07 20:36:19 tinker-0 crio[4853]: time="2018-04-07 20:36:19.702724071-07:00" level=debug msg="event: "/var/run/crio/exits/209d030a898afc1076be5447bee582efe1941306281273009ae2f21918f8036f.3CUVGZ": RENAME"
Apr 07 20:36:19 tinker-0 crio[4853]: time="2018-04-07 20:36:19.703321114-07:00" level=debug msg="event: "/var/run/crio/exits/209d030a898afc1076be5447bee582efe1941306281273009ae2f21918f8036f": CREATE"
Apr 07 20:36:19 tinker-0 crio[4853]: time="2018-04-07 20:36:19.703440406-07:00" level=debug msg="container or sandbox exited: 209d030a898afc1076be5447bee582efe1941306281273009ae2f21918f8036f"
Apr 07 20:36:19 tinker-0 crio[4853]: time="2018-04-07 20:36:19.703493782-07:00" level=debug msg="sandbox exited and found: 209d030a898afc1076be5447bee582efe1941306281273009ae2f21918f8036f"
Apr 07 20:36:19 tinker-0 crio[4853]: time="2018-04-07 20:36:19.773087398-07:00" level=info msg="Got pod network {Name:podsandbox1 Namespace:redhat.test.crio ID:209d030a898afc1076be5447bee582efe1941306281273009ae2f21918f8036f NetNS:/proc/0/ns/net PortMappings:[]}"
Apr 07 20:36:19 tinker-0 crio[4853]: time="2018-04-07 20:36:19.773166440-07:00" level=info msg="About to add CNI network cni-loopback (type=loopback)"
Apr 07 20:36:19 tinker-0 crio[4853]: time="2018-04-07 20:36:19.778985498-07:00" level=error msg="Error adding network: failed to Statfs "/proc/0/ns/net": no such file or directory"
Apr 07 20:36:19 tinker-0 crio[4853]: time="2018-04-07 20:36:19.779056081-07:00" level=error msg="Error while adding to cni lo network: failed to Statfs "/proc/0/ns/net": no such file or directory"
```
The error: `failed to Statfs "/proc/0/ns/net": no such file or directory` threw me off completely. I started checking CNI configuration, I also found some references to SELinux-related issues, which made no sense to me as I'm running on Ubuntu 16.04 with SELinux not installed at all.
Only after a long debugging session, I found out there is a separate log produced by `conmon` with `runc` output, which gave me:
```
root@tinker-0:~# cat /var/log/crio/pods/209d030a898afc1076be5447bee582efe1941306281273009ae2f21918f8036f/209d030a898afc1076be5447bee582efe1941306281273009ae2f21918f8036f.log
2018-04-07T20:36:19.679429171-07:00 stderr F standard_init_linux.go:190: exec user process caused "exec format error"
```
Had this been printed to crio log, I would have found the root cause much faster.

**Some ideas:**
* Print `conmon`/`runc` logs to crio.log - looks like this is a [known issue](https://github.com/kubernetes-incubator/cri-o/blob/86b61d44cfe7de0f4095877d303c4d1b3aa2ec06/conmon/conmon.c#L1478).
* Add a comment to `crio.conf` `pause_image` parameter to mention it's architecture-specifc.
* Change the default pause container based on `GOARCH` when running `make` (also when OS packages are built). A similar change has been [introduced to Kubelet]. (https://github.com/kubernetes/kubernetes/pull/23059/files).
* If #91 is addressed, the issue goes away automatically :-) 

**Steps to reproduce the issue:**
1. Install CRI-O (I've used current master https://github.com/kubernetes-incubator/cri-o/commit/86b61d44cfe7de0f4095877d303c4d1b3aa2ec06) on ARM architecture.
2. Follow [this tutorial](https://github.com/kubernetes-incubator/cri-o/blob/86b61d44cfe7de0f4095877d303c4d1b3aa2ec06/tutorial.md) to create a pod.

**Describe the results you received:**
```
root@tinker-0:/var/go/src/github.com/kubernetes-incubator/cri-o# crictl runp test/testdata/sandbox_config.json
FATA[0001] run pod sandbox failed: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_podsandbox1_redhat.test.crio_redhat-test-crio_1(d8961018f0d124127513859bb34e60f39ceae6ab594ee22cee14ad2d6b1df3a7): failed to Statfs "/proc/0/ns/net": no such file or directory
```

**Describe the results you expected:**
Expected a pod ID to be returned by `crictl`.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
root@tinker-0:/var/go/src/github.com/kubernetes-incubator/cri-o# crio --version
crio version 1.10.0-dev
commit: "86b61d44cfe7de0f4095877d303c4d1b3aa2ec06-dirty"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
ARM architecture
```
root@tinker-0:/# uname -a
Linux tinker-0 4.14.29-rockchip #1 SMP PREEMPT Sat Mar 24 21:55:01 PDT 2018 armv7l armv7l armv7l GNU/Linux
```

**Comment by wking** [comment]
What a thorough report; thanks :).


> * Print `conmon`/`runc` logs to crio.log ...

Having `crio` and `conmon` daemons both writing to the same log file sound difficult.  And we have to drop the stderr connection before calling `create`, etc., so that can't be pushed back much further.

My preferred solution to this sort of thing is to have everything dumping into a system logger (syslog, journalctl, etc.) to make it easy to see all the logs interleaved.  `conmon` already supports that for syslog, and teaching `crio` to would be [pretty easy][1].

> * If #91 is addressed, the issue goes away automatically :-)

+1 to this.  I've had #1265 (a baby step in this direction) in flight for a few months, with more local work to push if/when it lands.

[1]: https://github.com/sirupsen/logrus/tree/v1.0.5/hooks/syslog

**Comment by rhatdan** [comment]
@wking is this still an issue?

**Comment by wking** [comment]
Looks like [the default is still `kubernetes/pause`][1], and that that image (implicitly on docker.io?) [hasn't been updated in three years][2].  So yeah, probably still an issue.  And my preferred solution is still dropping the pause container (#91) and just using the runtime itself idling post-`create` and pre-`start` to hold PID namespaces open.  Looks like #1265 has been getting another look recently, so maybe we'll be able to move a bit in that direction soon.

[1]: https://github.com/kubernetes-sigs/cri-o/blame/v1.13.3/docs/crio.8.md#L125
[2]: https://hub.docker.com/r/kubernetes/pause

**Comment by haircommander** [comment]
we have moved to `k8s.gcr.io/pause:3.2` which has better support for different architectures. as such, I'm closing this. please reopen if you disagree
