### ISSUE TITLE
Session affinity NodePort service tests failing

### ISSUE THREAD

**Issue by umohnani8** [cri-o/cri-o#1529]
**Description**
Kube added 2 new tests that check if Session Affinity work with NodePort service, however the tests are failing when ran as part of our e2e test suite. Looks like an issue with networking, which might be caused by AWS having two different IPs. The test is setting up a NodePort service and trying to ping `node-internal-ip:node-port` but failing with a connection refused error.

**Steps to reproduce the issue:**
1. Once kube master is vendored into cri-o master, run the e2e tests for the following two tests:
- `should have session affinity work for NodePort service`
- `should be able to switch session affinity for NodePort service`

**Describe the results you received:**
The tests will fail with rc 1, i.e connection refused.

The tests should be enabled in the ansible playbook once this issue is figured out.
Tests are being pulled in by https://github.com/kubernetes-incubator/cri-o/pull/1502

**Comment by runcom** [comment]
@rajatchopra PTAL

**Comment by runcom** [comment]
For the record, the tests for session affinity have been added upstream with https://github.com/kubernetes/kubernetes/commit/4655f52329b7102cde72be2986844650d5c5c378 (if that helps)

**Comment by runcom** [comment]
> The tests will fail with rc 1, i.e connection refused.

this comes from the "exec wget ..." happening withing the tests

**Comment by umohnani8** [comment]
Pulled in more tests from upstream kube and the following tests are failing:
- `Services should have session affinity work for service with type clusterIP`
- `Services should create endpoints for unready pods`
- `DNS should provide DNS for ExternalName services`
- `Services should be able to switch session affinity for service with type clusterIP`

The failure comes from "exec wget" in the tests.

These two tests are also failing due to timeout when trying to hit a service endpoint:
- `Guestbook application should create and stop a working application`
- `Simple pod should handle in-cluster config`

**Comment by rhatdan** [comment]
@umohnani8 Is this still an issue?

**Comment by umohnani8** [comment]
@rhatdan yup.

**Comment by umohnani8** [comment]
Tests are passing now https://github.com/cri-o/cri-o/pull/2977, closing.
