### ISSUE TITLE
[RFE] log additional details of options

### ISSUE THREAD

**Issue by vbatts** [cri-o/cri-o#1547]
**Description**

spun off from https://github.com/kubernetes-incubator/cri-o/pull/1439#discussion_r174979067

Rather than having this empty recommendation and branch, actually log details.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
@vbatts Is this still something we need?

**Comment by vbatts** [comment]
Need? More of a nice-to-have

**Comment by haircommander** [comment]
@vbatts can you describe a bit more of what this RFE is asking for?

**Comment by vbatts** [comment]
@haircommander if you click the link to the referenced comment, there is a comment that something _should_ be logged, but is not.
This may not even be needed anymore. (i'm fine closing it)
