### ISSUE TITLE
conmon: Move pseudoterminal master up to crio?

### ISSUE THREAD

**Issue by wking** [cri-o/cri-o#1585]
My preferred approach to terminal handling is to pass the pseudoterminal master as high up the stack as possible.  In CRI-O, the stack looks [like this][1], and you need control translation because [the `kublet` <-> `crio` link uses gRPC][2], which doesn't support passing file descriptors.  The Podman stack has no such restriction, so they can avoid the extra `conmon`-proxy overhead by taking direct control of the pseudoterminal master.  But even within CRI-O, getting the proxy step out of `conmon` and up into `crio` itself would also benefit CRI-O, by reducing the size of the API where `crio` and `conmon` need to agree.  For example we could go straight from gRPC to native terminal operations without the [resize][3] [shim][4] or [bit][5]-[shoveling][6].  Would folks be interested in a PR removing the attach socket and replacing it with a control-socket request/response for getting a copy of the pseudoterminal master?

[1]: https://github.com/kubernetes-incubator/cri-o/pull/1350#issuecomment-366770178
[2]: https://github.com/kubernetes-incubator/cri-o/pull/1350#issuecomment-366811671
[3]: https://github.com/kubernetes-incubator/cri-o/blob/db44a51ac2667245fc23a382136e254a68a18542/server/container_attach.go#L68
[4]: https://github.com/kubernetes-incubator/cri-o/blob/733d791bec7792b25137eaf432ab974c5f2f9bc4/conmon/conmon.c#L928
[5]: https://github.com/kubernetes-incubator/cri-o/blob/db44a51ac2667245fc23a382136e254a68a18542/server/container_attach.go#L76
[6]: https://github.com/kubernetes-incubator/cri-o/blob/733d791bec7792b25137eaf432ab974c5f2f9bc4/conmon/conmon.c#L820-L851

**Comment by mrunalp** [comment]
@wking Won't that break restart though? Right now we can restart cri-o, since conmon holds the pseudoterminal master. We only break existing exec/attach connections on restart which is relatively minor as one could open new attach/exec sessions after cri-o has been restarted.

**Comment by wking** [comment]
> Won't that break restart though? Right now we can restart cri-o, since conmon holds the pseudoterminal master.

I was thinking `conmon` would keep its copy open for future re-attach requests (including after `crio` restarts).  That should cover everything short of multiplexing output between multiple reading consumers, and I'm happy to leave that to `screen`, `tmux`, etc.  You might need an additional "close the master for writes" command from `crio` -> `conmon` to avoid hanging `cat` and similar, but that still sounds simpler than what we have now.  Am I missing anything else (as far as we can see now ;)?

**Comment by mrunalp** [comment]
@wking okay, I can't think of anything else right now :) A PR would be fine to see if we can find something else we missed or go for it :)

**Comment by wking** [comment]
Getting into this a bit, one issue which I hadn't expected was [`write_k8s_log`][1], which is logging every output line as required by CRI (I'm not sure if/how Podman turns that off).  I'll have to shift that up into CRI-O too to avoid multiplexing the container's output streams in `conmon`.  And if it turns out that the daemonless Podman actually needs that logging, it may sink this master-shifting idea.

[1]: https://github.com/kubernetes-incubator/cri-o/blob/7910f248c97c2384546b51b063d4126a4a8ef40e/conmon/conmon.c#L354-L360

**Comment by rhatdan** [comment]
Podman logs?

**Comment by wking** [comment]
> Podman logs?

How do those work?  Does `conmon` write them somewhere in the absence of an attached consumer?

A change with this approach will be that, in the absrnce of a consumer, the container may block on a full stdout or stderr buffer.  I don't see a problem with that (no lost logs :), but I'm probably unaware of all use cases.

**Comment by mheon** [comment]
There is a log file for each container (I'm fairly certain it's created and managed by `conmon`). `podman logs` should be interacting exclusively with that file and should not be attaching to the terminal at all.

**Comment by rhatdan** [comment]
@wking @mheon Is this still an issue, or can I close it.

**Comment by wking** [comment]
The `podman logs` bit means that if we did this, we'd need a flag to be able to preserve `conmon`-written logs for Podman.  But we wouldn't need control translation for that, just log writing.  So there's probably space for cleanup along these lines, but I am probably not going to have time to push it forward myself in the near future.  Maybe leave it open and label it priority/backlog?

**Comment by haircommander** [comment]
I think at this point, it's unlikely we will implement this. We're generally in the process of keeping processing out of cri-o and into subcomponents, and since conmon (and conmon-rs) currently do this, I think we will keep it there
