### ISSUE TITLE
Need a way to send results from the CNI plugin add/get operation to the OCI runtime.

### ISSUE THREAD

**Issue by amshinde** [cri-o/cri-o#1712]
Certain CNI plugins such as those that make use of vhost-user sockets could send additional information to the runtime such as the location of the vhost-user socket, IP configuration etc. This information could be sent out as part of the `Result` structure from the CNI plugin `add/get` call. 
We need a mechanism by which this information could be made available to the runtime. 

We could send this information out making use of annotations, but I am not sure if that is the best way, since this approach would not work in case the network namespace is created after the sandbox has already started.

**Comment by amshinde** [comment]
cc @mrunalp @egernst @sboeuf

**Comment by sboeuf** [comment]
Thanks for opening this issue @amshinde, as Kata Containers has a few use cases like this, being a VM based runtime.

@mrunalp I have a question to clarify about CRI-O interaction with CNI plugins. Is it always the CRI implementation reponsibility to call into the CNI plugin? I am trying to understand if we might have some cases where even CRI-O won't have access to the information returned by the CNI plugins.

**Comment by amshinde** [comment]
@sboeuf From my investigations I see that it is the CRI runtime that always calls the CNI. It is just a matter of the CNI plugin being called before or after the sandbox is created.

@mrunalp I think we could first look at handling the case where the network namespace is created before the sandbox i.e `manage_network_ns_lifecycle = true`, since that is the case that Kata supports as of now.

**Comment by mrunalp** [comment]
@amshinde That sounds good to me :+1:

**Comment by mrunalp** [comment]
We discussed this on the call today and decided to do the following:

- Store a blob that is returned from a CNI plugin in the sandbox struct and config.json for managed network ns case.
- Use the config.json to restore the information in memory on CRI-O restart.

**Comment by rhatdan** [comment]
@amshinde @mrunalp Is this still something that is needed and never completed?

**Comment by haircommander** [comment]
/area vm

while not immediately needed, this was deemed to be good to keep open
