### ISSUE TITLE
Provide a hint about the OCI runtime information to CNI plugin. 

### ISSUE THREAD

**Issue by amshinde** [cri-o/cri-o#1733]
CNI plugins assume that they are dealing with network namespace based containers and create interfaces suited for namespace based containers. We can provide a hint about the runtime type to a CNI plugin to make the plugin aware that it is dealing with a hypervisor based runtime. When this hint is present, the CNI plugin may choose to create an interface that is more VM friendly eg, create a vhost-user or tap interface instead of a veth interface.

**Comment by amshinde** [comment]
cc @mrunalp @egernst @mcastelino

**Comment by mrunalp** [comment]
I have no problems with that. However, it will be up to the CNI plugins to interpret this information if it is passed as some metadata.

**Comment by amshinde** [comment]
@mrunalp  I think this can be done in a couple of ways, treat this purely as metadata and pass it as part of  `Args`  to the CNI plugin. The plugin can then choose to act upon this or ignore it.
The other approach I was thinking of is have the network plugin advertise the ability to handle VM specific interfaces explicitly as `capabilities`. Something like
```
{
  "name" : "ExamplePlugin",
  "capabilities": {"configureVM": true}
}
```

In case of  hypervisor based runtimes, `cri-o` can then fill in the mappings as:
```
{
  "name" : "ExamplePlugin",
   "runtimeConfig": {
    "configureVM": "true"
  }
}
```

What do you think?

**Comment by mcastelino** [comment]
@amshinde do we need the runtime to advertise the capability. The plugin is free to ignore the parameter it does not understand. So if the plugin creates a VM friendly interface we can consume it directly. If it does not we need to transparently connect the same to the VM.

Another gap is the passing back of the CNI plugin results back to the runtime. This information is required in the cases where the network configuration for certain interfaces cannot performed by the plugin (e.g. vhost-user). The runtime will need this information to configure the interface inside the VM.

**Comment by egernst** [comment]
@mcastelino see https://github.com/kubernetes-incubator/cri-o/issues/1712

**Comment by tallclair** [comment]
xref: https://github.com/kubernetes-incubator/cri-o/issues/1751

I think it makes sense to tie this to the runtime handler configuration.

**Comment by amshinde** [comment]
@tallclair To keep track of this discussion, following our discussion on Monday in Kata forum, we agreed upon having a runtime classification string in the runtime configuration that can be passed by CRI runtime to CNI.

**Comment by rhatdan** [comment]
Looks like the PR has stalled?

**Comment by yyang13** [comment]
Anybody is fixing this issue? It seems nobody cares it, is there any other issue or solution exisiting?
