### ISSUE TITLE
Consider using a double buffer method for reading/writing log data

### ISSUE THREAD

**Issue by portante** [cri-o/cri-o#1778]
**Description**

Currently it appears that data read from stdout & stderr pipes of the container are written to the log file sequentially instead of using a double buffering scheme [1].  That one thread will not be able to overlap I/O to disk when writing to the log file with reads issued to the pipes.  This can lead to excessive CPU usage as the number of containers rises on a system.

If instead, for example (not necessarily required to be implemented this way) we read from the stdout & stderr pipes into a large buffer using one thread, then a second thread can take that buffer when it is full to write to disk, independent of the first, which would use a second buffer to continue reading.

This allows us to transfer data at the speed of the slowest disk (log file) or pipe (stdout/stderr of container) instead of at the combined speed of processing them both sequentially.

In combination with https://github.com/kubernetes-incubator/cri-o/pull/1605, we'd have a more efficient method of data handling.

[1] https://github.com/kubernetes-incubator/cri-o/blob/3c30a2f1b2a9521afb6b54c9b1f728060e260a2b/conmon/conmon.c#L720

**Comment by rhatdan** [comment]
@portante, is this still something you believe we should do?
@haircommander could you take a look.
@mrunalp FYI

**Comment by haircommander** [comment]
@rhatdan yes, but I'd like the journald PRs to get in first!

**Comment by haircommander** [comment]
I'm going to close this here, as we are moving conmon development to containers/conmon
