### ISSUE TITLE
After running for a period of time, some images will start failing to pull

### ISSUE THREAD

**Issue by mcronce** [cri-o/cri-o#1784]
**Description**
After running for a period of time, I will start to get issues with a node pulling images.  This doesn't seem to impact any _specific_ node, but once a node starts failing on a given image, it will only ever fail unless I stop crio, blow away all its state, and start it back up.

When pulling the image fails, the message returned is similar to the following:
```
$ sudo crictl pull quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.15.0
FATA[0017] pulling image failed: rpc error: code = Unknown desc = Error committing the finished image: error reading layer "5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef" for blob "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4": error creating overlay mount to /mnt/containers/graphroot/overlay/5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef/merged: no such file or directory
```

**Steps to reproduce the issue:**
Steps to aggravate the issue are unknown :( but when a failure begins, any pull operation on a failing image will reproduce it.

**Describe the results you received:**
Images fail to pull

**Describe the results you expected:**
Images pull successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**
```
crio version 1.11.2
commit: "43b906e883a364b816b73ed6cc312917789c75a6-dirty"
```

This was also an occasional issue, just as inexplicable, on 1.9 and 1.10.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is a bare metal Kubernetes cluster on Fedora 28.  My config is:
```
[crio]
root = "/mnt/containers/graphroot"
runroot = "/mnt/containers/runroot"
storage_driver = "overlay"
storage_option = [
]
[crio.api]
listen = "/var/run/crio/crio.sock"
stream_address = ""
stream_port = "10010"
stream_enable_tls = false
stream_tls_cert = ""
stream_tls_key = ""
stream_tls_ca = ""
file_locking = true
[crio.runtime]
runtime = "/usr/bin/runc"
runtime_untrusted_workload = ""
default_workload_trust = "trusted"
no_pivot = false
conmon = "/usr/libexec/crio/conmon"
conmon_env = [
	"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
]
selinux = true
seccomp_profile = "/etc/crio/seccomp.json"
apparmor_profile = "crio-default"
cgroup_manager = "cgroupfs"
default_capabilities = [
	"CHOWN", 
	"DAC_OVERRIDE", 
	"FSETID", 
	"FOWNER", 
	"NET_RAW", 
	"SETGID", 
	"SETUID", 
	"SETPCAP", 
	"NET_BIND_SERVICE", 
	"SYS_CHROOT", 
	"KILL", 
]
hooks_dir_path = "/usr/share/containers/oci/hooks.d"
default_mounts = [
	"/usr/share/rhel/secrets:/run/secrets", 
]
pids_limit = 1024
enable_shared_pid_namespace = false
log_size_max = -1
read_only = false
log_level = "error"
uid_mappings = ""
gid_mappings = ""
[crio.image]
default_transport = "docker://"
pause_image = "k8s.gcr.io/pause:3.1"
pause_command = "/pause"
signature_policy = ""
image_volumes = "mkdir"
insecure_registries = [
]
registries = [
	"docker.io"
]
[crio.network]
network_dir = "/etc/cni/net.d/"
plugin_dir = "/usr/libexec/cni"
```
Primary changes from defaults are storage location (root/runroot), cgroup manager, and default registry.

**Comment by mrunalp** [comment]
@mtrmac @nalind @runcom PTAL

**Comment by rhatdan** [comment]
@mcronce are you still seeing this behaviour?

**Comment by mcronce** [comment]
@rhatdan I switched back to Docker and am traveling currently, but I'll try CRI-O again and see if it's still an issue when I'm home.  Thanks!

**Comment by everflux** [comment]
Same problem here, running on ARM Linux and using crio 16.1
This seems to only be caused by images build with Jib, at least I could not reproduce it with a docker based build.
Changing the output format of jib between Docker and OCI does not seem to have an effect.

Sometimes the node even crashes when pulling/mounting the image. File system check does not reveal any problems.

**Comment by haircommander** [comment]
@everflux can you describe how to reproduce the issue?

cc @nalind @vrothberg @rhatdan

**Comment by everflux** [comment]
I have no safe way to reproduce it.
But I could fix it, it seems, by not only removing the images locally but by wiping the filesystem where the layers where cached. Afterwards pulling worked again. I doubt that it is related to the way the image was built, but since the number of images using jib exceeded other images in my scenario, jib stood out.
