### ISSUE TITLE
crictl ps hangs on a runc kill that is stuck

### ISSUE THREAD

**Issue by mrunalp** [cri-o/cri-o#1824]
**Description**
We saw an instance of runc kill stuck on a process in D state.
This was holding up the container's lock resulting in crictl ps not getting a response.

**Comment by cyphar** [comment]
What was `/proc/$pid/stack` of the `runc` process?

**Comment by mrunalp** [comment]
@cyphar Unfortunately I didn't gather that and I was just thinking about it right now :/ I think we do hit this in e2e CI so will be able to get it sooner or later.

**Comment by mrunalp** [comment]
We are using runc kill -all SIGKILL and I suspect that putting the proceses in frozen state is causing this issue. The code is getting stuck somewhere after that.

**Comment by rhatdan** [comment]
@mrunalp @cyphar Is this still an issue?

**Comment by haircommander** [comment]
I think this is no longer a problem. please reopen if you disagree
