### ISSUE TITLE
crio creates logs in /tmp

### ISSUE THREAD

**Issue by vrothberg** [cri-o/cri-o#1879]
**Description**

`crio` creates some logs in `/tmp` which seems to be an undesired side-effect of used libraries using [glog](https://godoc.org/github.com/golang/glog). 

**Steps to reproduce the issue:**
1. Start crio.

**Describe the results you received:**

After a clean start, I see the following files in `/tmp`:
```
/tmp/crio.INFO
/tmp/crio.nebuchadnezzar.root.log.INFO.20181030-141503.28879   
/tmp/crio.nebuchadnezzar.root.log.WARNING.20181030-141503.28879
/tmp/crio.WARNING
```

**Describe the results you expected:**
Either move them to `/var/log/cri-o/` or no such files at all.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.12.0
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
openSUSE Tumbleweed

**Comment by mrunalp** [comment]
Thanks for the report! Would you be willing to work on a fix? :)

**Comment by vrothberg** [comment]
@mrunalp, sure. How should we change the current behavior? I suggest to either move the logs to /var/log/cri-o/ or, if possible, suppress them altogether.

**Comment by mrunalp** [comment]
I think we should suppress them since we aren't even looking at these today.

**Comment by vrothberg** [comment]
This seems to be worked on already in https://github.com/kubernetes/kubernetes/issues/70264. I propose to wait for those changes to be propagated into CRI-O and to close this issue. @mrunalp, are you cool with it?

**Comment by vrothberg** [comment]
The problem still applies to the latest master. We can recheck when K8s 1.14 is released (March 25, 19).

**Comment by vrothberg** [comment]
Nothing has changed with the new `k8s.io/klog` package as it's `flag` based and cannot really be controlled via an API. That's pretty ugly since we had to screw with cri-o's CLI to prevent klog from creating those files.
