### ISSUE TITLE
FATA[0010] failed to connect: failed to connect: context deadline exceeded

### ISSUE THREAD

**Issue by alexvirtualbr** [cri-o/cri-o#1922]
**Description**

Hey, I'm a problem here when I'm trying ensure the crio service is running.

**Steps to reproduce the issue:**
1. >> sudo crictl --runtime-endpoint unix:///var/run/crio/crio.sock version

**Describe the results you received:**

/// [alexvirtualbr@localhost ~]$ sudo crictl --runtime-endpoint unix:///var/run/crio/crio.sock version
/// NAME:
///   crictl version - Display runtime version information
/// USAGE:
///   crictl version [arguments...]
/// FATA[0010] failed to connect: failed to connect: context deadline exceeded 

**Describe the results you expected:**

I'm following your tutorial and I hope received this:
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.10.0-dev
RuntimeApiVersion:  v1alpha1

**Comment by mrunalp** [comment]
Most likely explanation for this is either crio is not running or crio socket is configured to be some other path. Can you check that?

**Comment by saschagrunert** [comment]
What can we do about this? I mean we could update the user documentation, but I'm not sure if this helps anyone.

**Comment by haircommander** [comment]
@saschagrunert this seems to be more of a crictl problem: an unclear error message, right? Which would mean the only thing we can do here is document it better

**Comment by saschagrunert** [comment]
> @saschagrunert this seems to be more of a crictl problem: an unclear error message, right? Which would mean the only thing we can do here is document it better

I think so too, but I guess we can close this here since the error message already has been improved https://github.com/kubernetes-sigs/cri-tools/pull/459 by @umohnani8.

**Comment by haircommander** [comment]
yeah, closing per above fix in cri-tools. reopen if you don't find this fix sufficient @alexvirtualbr :)

**Comment by danifr** [comment]
Maybe this might help someone. In my cased I was missing the file:  _/etc/crictl.yaml_

These lines did the trick:

```
# cat /etc/crictl.yaml
runtime-endpoint: unix:///run/containerd/containerd.sock
image-endpoint: unix:///run/containerd/containerd.sock
timeout: 2
debug: true
pull-image-on-create: false
```

**Comment by saschagrunert** [comment]
> These lines did the trick:
> 
> ```
> # cat /etc/crictl.yaml
> runtime-endpoint: unix:///run/containerd/containerd.sock
> image-endpoint: unix:///run/containerd/containerd.sock
> timeout: 2
> debug: true
> pull-image-on-create: false
> ```

For CRI-O the runtime and image endpoints have to be:
```yaml
runtime-endpoint: "unix:///var/run/crio/crio.sock"
```
