### ISSUE TITLE
cri-o 1.11 fails network integration test on RHEL 7.6

### ISSUE THREAD

**Issue by cevich** [cri-o/cri-o#2030]
**Description**

When executing cri-o integration tests using the *CRI-O* `1.11` RPM, the ``network.bats`` test fails:

```
@test "Clean up network if pod sandbox fails after plugin success"
```

**Steps to reproduce the issue:**
1. Subscribe and fully update RHEL 7.6 VM, and enable EPEL repository.
2. Install ``rng-tools`` and enable `rngd` service (allows VM to boot w/ low entropy).
3. Reboot
4. Use ``subscription-manager attach`` to access a subscription with access to OpenShift 3.11 packages
5. Disable all repositories except:
    * `EPEL`
    * `rhel-7-server-rpms`
    * `rhel-7-server-optional-rpms`
    * `rhel-7-server-extras-rpms`
    * `rhel-server-rhscl-7-rpms`
    * `rhel-7-server-ose-3.11-rpms`
6. Install the following RPMs:
    * `PyYAML`
    * `atomic-registries`
    * `buildah`
    * `container-selinux`
    * `containernetworking-plugins`
    * `cri-o`
    * `cri-tools`
    * `curl`
    * `device-mapper-devel`
    * `e2fsprogs-devel`
    * `expect`
    * `findutils`
    * `gcc`
    * `glib2-devel`
    * `glibc-devel`
    * `glibc-static`
    * `golang`
    * `gpgme`
    * `gpgme-devel`
    * `grubby`
    * `hostname`
    * `iproute`
    * `iptables`
    * `krb5-workstation`
    * `kubernetes`
    * `libassuan`
    * `libassuan-devel`
    * `libblkid-devel`
    * `libffi-devel`
    * `libgpg-error-devel`
    * `libguestfs-tools`
    * `libseccomp-devel`
    * `libselinux-devel`
    * `libselinux-python`
    * `libsemanage-python`
    * `libvirt-client`
    * `libvirt-python`
    * `libxml2-devel`
    * `libxslt-devel`
    * `make`
    * `mlocate`
    * `nfs-utils`
    * `nmap-ncat`
    * `oci-register-machine`
    * `oci-systemd-hook`
    * `oci-umount`
    * `openssl`
    * `openssl-devel`
    * `ostree-devel`
    * `pkgconfig`
    * `podman`
    * `policycoreutils`
    * `python`
    * `python-devel`
    * `python-rhsm-certificates`
    * `python-virtualenv`
    * `python2-crypto`
    * `python34`
    * `python34-PyYAML`
    * `redhat-rpm-config`
    * `rpcbind`
    * `rsync`
    * `runc`
    * `sed`
    * `skopeo-containeras`
    * `socat`
    * `tar`
    * `vim`
    * `wget`
    * `zlib-devel`

5. Execute the commands: 
    * `grubby --update-kernel=ALL --args="rootflags=pquota"`
    * `setsebool -P container_manage_cgroup 1`
    * `echo "net.ipv4.conf.all.route_localnet = 1" | sudo tee /etc/sysctl.d/route_localnet.conf`
    * reboot

5. Clone the upstream BATS repository, install under /usr/bin/

5. Clone the upstream CRI-O git repository under `$GOPATH`, check out tag `1.11`.

6. From CRI-O repository root, install `test/cni_plugin_helper.bash` into `/usr/libexec/cni/` (mode `0755`)

5. Create the ``/opt/cni/bin`` directory, then symlink `/usr/libexec/cni/*` into it.

6. Create the `/etc/containers/registries.d/` directory

6. From CRI-O repository root, install `test/redhat_sigstore.yaml` as `/etc/containers/registries.d/registry.access.redhat.com.yaml` (mode `0644`)

6. Flush all rules with `iptables -F`, then add the NAT rule `iptables -t nat -I POSTROUTING -s 127.0.0.1 ! -d 127.0.0.1 -j MASQUERADE`

6. From `$GOPATH` use `go get` tool to install:
        * `tools/godep`
        * `onsi/ginkgo`
        * `onsi/gomega`
        * `cloudflare/cfssl/cmd/...`
        * `jteeuwen/go-bindata/go-bindata`
        * `cpuguy83/go-md2man`

7. From CRI-O repository root run the command `make test-binaries`

8. Set the following environment variables:
```bash
export CRIO_BINARY=/usr/bin/crio
export CONMON_BINARY=/usr/libexec/crio/conmon
export PAUSE_BINARY=/usr/libexec/crio/pause
export CRIO_CNI_PLUGIN=/usr/libexec/cni
```

8. From CRI-O repository root execute the integration test runner: ``./test/test_runner.sh``

**Describe the results you received:**

[crio_intg.log.txt](https://github.com/kubernetes-sigs/cri-o/files/2783697/crio_intg.log.txt)

**Describe the results you expected:**

All integration tests should pass

**Additional Info:**

I instrumented the `test/network.bats` test to show the `/var/lib/cni/networks/crionet_test_args` directory contents before and after every test command.  I found the contents throughout the test to be:
* lock
* last_reserved_ip.0

Chatted with both @giuseppe and @runcom on ``#cri-o`` but we could not determine why these files were there and failing the test.  I can readily provide a VM that reproduces this problem.

**Comment by cevich** [comment]
I never got a response from @dcbw on this problem.  Myself and several others decided to simply skip running it for conmon as it wasn't very relevant to our use-case.  However I believe this test is fundamentally broken with a race condition of some sort, causing it to "accidentally" pass.  Unfortunately I do not posses the knowledge necessary to properly fix it, despite making several failed attempts.

**Comment by haircommander** [comment]
I think we're successfully running this test on rhel
