### ISSUE TITLE
/etc/mtab missing in glibc-based containers

### ISSUE THREAD

**Issue by arthfl** [cri-o/cri-o#2036]
**Description**

In glibc based containers (httpd:latest for example) that are running on a CRI-O node, there is not /etc/mtab to be found.

It exists in musl containers (httpd:alpine e.g.)

**Steps to reproduce the issue:**
1. run httpd:latest on crio

**Describe the results you received:**

No /etc/mtab to be found.

**Describe the results you expected:**

/etc/mtab should be there

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.12.1-dev
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Saw this on k8s 1.12, running on vSphere.

**Comment by runcom** [comment]
We'll need to just symlink /etc/mtab to /proc/mounts as Docker does (at the rw layer level)

**Comment by rhatdan** [comment]
SGTM

**Comment by runcom** [comment]
I'm just not sure if we can just create the symlink in the rootfs on container_create, I guess so though, but Docker does something on the read write layer which I'm not sure, @nalind could you have a super fast look?

**Comment by rhatdan** [comment]
@umohnani8 Any movement on this?

**Comment by umohnani8** [comment]
@rhatdan nope, will start looking into it

**Comment by nalind** [comment]
moby creates an intermediate layer sandwiched between the image's layer and the container's read-write layer, and places the container's `/etc/resolv.conf`, `/etc/hosts`, `/etc/hostname`, `/etc/mtab`, `/dev/console`, `/dev/pts`, `/dev/shm`, `/proc`, `/sys`, and a `/.dockerenv` in that, if need be.

**Comment by arthfl** [comment]
Any news on this?

**Comment by haircommander** [comment]
no news here, though I'd like to see this get done. sorry for the (extreme) delay @arthfl
