### ISSUE TITLE
Latest centos7 rpm

### ISSUE THREAD

**Issue by robertrbruno** [cri-o/cri-o#2072]
Is there a reason the latest release 1.13.0 doesn't have centos7 rpms available anywhere?  We only can fine 1.11.0.

**Comment by rhatdan** [comment]
@lsm5 Do you know where these packages are?

**Comment by rbtr** [comment]
1.13 builds haven't been made for fedora either - i forked the spec and packaged it myself but it would be nice to be able to pull an official rpm from the fedora repos instead of copr 🙂

**Comment by lsm5** [comment]
@fkluknav can you please check with centos infra and setup builds for crio 1.12 and 1.13?

**Comment by lsm5** [comment]
@rbtr RE: fedora, sorry that's on me, been distracted on the RHEL side + I've been travelling as well. Anyway, co-maintainers are welcome :) . iCan you ping me (@lsm5) on freenode and we can look at getting you set up with fedora co-maintenance

**Comment by hardoverflow** [comment]
Hey guys. This is currently a huge problem for us too. We will now try to build the cri-o packages itself. @fkluknav - Can we support u ?

**Comment by SimonHoenscheid** [comment]
Yes, this is an issue for the company I work for zoo. Themanagement is thinking about dropping cri-o in favor of docker because of the lack of package support for centos.

**Comment by lsm5** [comment]
@SimonHoenscheid @hardoverflow sorry about the delay, I've filed https://bugs.centos.org/view.php?id=15869 to get repos created for crio versions. I'll get in touch with centos infra to expedite this. Stay tuned..

**Comment by SimonHoenscheid** [comment]
@lsm5 Thanks a lot! Is there also an option for a repository for all versions?

**Comment by lsm5** [comment]
> @lsm5 Thanks a lot! Is there also an option for a repository for all versions?

you mean you're looking for a single yum repo with all crio versions? I guess yum would only pick the latest build from it.

**Comment by SimonHoenscheid** [comment]
@lsm5 yes, exactly, or the version you specify.

**Comment by lsm5** [comment]
> @lsm5 yes, exactly, or the version you specify.

umm I guess that's doable, but I wouldn't wanna spend too much time supporting it. I'll just dump builds from the other repos into this and leave it to the user to figure things out. Would that be good enough?

**Comment by SimonHoenscheid** [comment]
@lsm5 perfect!

**Comment by lsm5** [comment]
ack, I'll request for such a repo as well. Thanks.

**Comment by SimonHoenscheid** [comment]
Thank you!

**Comment by lsm5** [comment]
quick headsup, I've built crio 1.13 at https://cbs.centos.org/repos/paas7-crio-113-candidate/x86_64/os/Packages/ .. still working on enabling dependencies, should be all set by tomorrow.

**Comment by lsm5** [comment]
alright, here you go:

```
# cri-o 1.13
[paas7-crio-113-candidate]
name=paas7-crio-113-candidate
baseurl=https://cbs.centos.org/repos/paas7-crio-113-candidate/x86_64/os/
enabled=1
gpgcheck=0

# cri-o 1.12
[paas7-crio-112-candidate]
name=paas7-crio-112-candidate
baseurl=https://cbs.centos.org/repos/paas7-crio-112-candidate/x86_64/os/
enabled=0
gpgcheck=0

# should have all cri-o builds but right now only has 1.12
[paas7-crio-common-candidate]
name=paas7-crio-common-candidate
baseurl=https://cbs.centos.org/repos/paas7-crio-common-candidate/x86_64/os/
enabled=0
gpgcheck=0
```

Enable the one you want.

Now, it seems cbs repos will only allow 1 build per package to stay on the repo. I tried tagging crio 1.13 to common it says it's already tagged yet it won't show up in https://cbs.centos.org/repos/paas7-crio-common-candidate/x86_64/os/Packages/ . It seems only the latest tagged build will show up there. I'll check with centos infra if it's possible to have multiple builds in there, but this should hopefully get you going.

**Comment by lsm5** [comment]
Also, if you want mirror.centos.org repos, that might take a little longer, but hope ^ ain't too bad

**Comment by SimonHoenscheid** [comment]
@lsm5 Thanks a lot!!

**Comment by hardoverflow** [comment]
Cool! Many thanks @lsm5

**Comment by gandazgul** [comment]
Thank you for setting this up!

I get this on Fedora 29 any ideas?

`nothing provides skopeo-containers >= 1:0.1.24-3 needed by cri-o-1.13.1-1.rhaos4.1.git2ac1ec7.el7.x86_64`

**Comment by rhatdan** [comment]
Skopeo-containers has been renamed to containers-common, which is all you should need.

**Comment by robertrbruno** [comment]
Thanks so much for all the movement on this!  Next time we upgrade this will save us a lot of time!

**Comment by gandazgul** [comment]
> Skopeo-containers has been renamed to containers-common, which is all you should need.

@rhatdan Trying to install 1.13.1 from here: https://cbs.centos.org/repos/paas7-crio-113-candidate/x86_64/os/Packages/ on Fedora 29

I get this:
```
sudo dnf install --nogpgcheck cri-o-1.13.*
Last metadata expiration check: 0:01:39 ago on Fri 01 Mar 2019 02:06:52 AM EST.
Error:
 Problem: conflicting requests
  - nothing provides skopeo-containers >= 1:0.1.24-3 needed by cri-o-1.13.1-1.rhaos4.1.git2ac1ec7.el7.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

You are right if I try to install cri-o from fedora it wants containers-common and it works, but can I use it with kubernetes 1.13?

**Comment by TomSweeneyRedHat** [comment]
FYI @lsm5, i'm thinking you might be asked to weigh in on this one.

**Comment by lsm5** [comment]
@gandazgul yup, no guarantees of the centos build working on f29. I've built cri-o modules for 1.11, 1.12 and 1.13. The module update for crio 1.13. on fedora29 is at https://bodhi.fedoraproject.org/updates/FEDORA-MODULAR-2019-5934cd8569 but funny enough, I'm unable to install the module myself on my f29 machine, filed https://bugzilla.redhat.com/show_bug.cgi?id=1685985 for that.

@jasonbrooks seems to have had the module work for him so maybe he can help out here. Jason, also PTAL at the bug ^ when you get the chance.

**Comment by lsm5** [comment]
@gandazgul we'll get the docs updated once the module install process is straightened out.

**Comment by lsm5** [comment]
hmm, suddenly seems to work now, seems like my yum repos needed a refresh, make sure your `updates-testing-modular` repo is enabled and then a simple `dnf install cri-o` should work. Let me know if that doesn't work. That build should get pushed to stable soon btw.

**Comment by lsm5** [comment]
@robertrbruno can you please close this issue? centos7 should be resolved by https://github.com/kubernetes-sigs/cri-o/issues/2072#issuecomment-467571277

**Comment by lsm5** [comment]
@umohnani8 this is good to be closed as well.

**Comment by gandazgul** [comment]
Thank you all for the quick responses I really want to start using cri-o. 

Cheers

**Comment by lsm5** [comment]
> Thank you all for the quick responses I really want to start using cri-o.

Yup, you can start already, see https://github.com/kubernetes-sigs/cri-o/issues/2072#issuecomment-470108105 :)

HTH

**Comment by SimonHoenscheid** [comment]
@lsm5 thx a lot for your work on this one. Any news about the combined repo?

**Comment by mrunalp** [comment]
@lsm5 Also, we should add a packages section to the README before closing this issue so it is easy for users to get to this :) Thanks!

**Comment by SimonHoenscheid** [comment]
@lsm5 will you add a paas7-crio-113-candidate soon?

**Comment by lsm5** [comment]
ya, seems like requesting for centos repos is gonna be a regular event.

**Comment by lsm5** [comment]
koji tags have been created for 1.14, I'll try and get the builds in soon. https://bugs.centos.org/view.php?id=15869#c34181

**Comment by Prodian0013** [comment]
When will there be an official cri-o rpm in epel or centos repos?

**Comment by hardoverflow** [comment]
@lsm5 What is the current standing?

**Comment by theonewolf** [comment]
1.15 RPMs don't seem to exist anywhere for CentOS 7.

**Comment by lsm5** [comment]
seems like the previous build failed https://cbs.centos.org/koji/taskinfo?taskID=893807 . I'll check whatsup

**Comment by theonewolf** [comment]
@lsm5 we want to use CRI-O with Kubernetes, but this is driving us back to Docker as it works with latest Kubernetes out of the box on the most platforms.

Anyways, excited to see if you get those builds working.

FYI my builds failed on CentOS 7 due to some packages failing to `git fetch` under `cznic`'s namespace on GitHub.  I tried building `release-1.15` on my own and failed there.

**Comment by lsm5** [comment]
@haircommander mind cutting a new 1.15 please? For fedora and centos I build tags and not the release-x branches. v1.15.0 still has the `undefined: strings.ReplaceAll` issue.

**Comment by haircommander** [comment]
@lsm5 oopsies, I cut it but never tagged it. 1.15.1 is tagged now

**Comment by theonewolf** [comment]
@haircommander does that mean a build is underway now?  Let me know if you'd like me to try CRI-O 1.15.1 RPMs soon.  I can rebuild my k8s cluster (just installed yesterday, with Docker).

**Comment by lsm5** [comment]
@theonewolf the cri-o fedora/centos automation still isn't all the way there yet, cause I'm still kinda struggling with fedora modules in an unattended setup. But, I'll take care of this right away.

**Comment by theonewolf** [comment]
Sounds like @lsm5 _is_ the automation.  Anyways looking forward to testing things out with CRI-O.

Unsure if you'll run into them, but I ran into some build problems with certain (Go) dependencies not being able to properly `git fetch` them.

**Comment by lsm5** [comment]
> Sounds like @lsm5 _is_ the automation. Anyways looking forward to testing things out with CRI-O.

hopefully it'll soon be @lsm5-bot :D 

> 
> Unsure if you'll run into them, but I ran into some build problems with certain (Go) dependencies not being able to properly `git fetch` them.

While building rpms, we just use the vendored dependencies, so we don't have to bother with git fetching anything.

**Comment by theonewolf** [comment]
@lsm5 ah, I was wondering about vendored stuff yesterday and didn't explore.  Now I see that folder.

Is it easy to get `make` to use those?  You have a CLI option?  I guess I can read your CI scripts...

**Comment by lsm5** [comment]
@theonewolf done, https://cbs.centos.org/koji/taskinfo?taskID=940324 

yum repo:
```
[paas7-crio-115-candidate]
name=paas7-crio-115-candidate
baseurl=https://cbs.centos.org/repos/paas7-crio-115-candidate/x86_64/os/
enabled=1
gpgcheck=0
```


see lines 78-88 in https://src.fedoraproject.org/rpms/cri-o/blob/1.15/f/cri-o.spec for build steps. That doesn't use Makefile though. HTH

**Comment by theonewolf** [comment]
@lsm5 thanks!  Going to test these now...after a `sonobuoy` test completes.

Also, that link is still useful to me even though it's not the Makefile.

**Comment by Moumoutaru** [comment]
Was looking to switch from docker to cri-o but the lack of rpm/repo's is concerning.

**Comment by rhatdan** [comment]
CRI-O is being shipped under OpenShift, not as a base package for RHEL.  Not sure where the packages for OpenShift are available on RHEL7.

**Comment by jasonbrooks** [comment]
there are srpms at: http://ftp.redhat.com/pub/redhat/linux/enterprise/7Server/en/RHOSE/SRPMS/

I found binaries using https://access.redhat.com/downloads/content/package-browser

**Comment by Moumoutaru** [comment]
Looks like for CentOS 7 v1.11.13 is what is available

http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin311/

via

https://github.com/CentOS-PaaS-SIG/centos-release-openshift-origin/blob/master/CentOS-OpenShift-Origin.repo

**Comment by matthias50** [comment]
FYI, I've been working with @lsm5 to get a closely related issue fixed with #2833.

**Comment by haircommander** [comment]
we now build for centos 7 on OBS, and as such have capacity to have the latest CRI-O release for upstream supported releases.
https://build.opensuse.org/package/show/devel:kubic:libcontainers:testing/cri-o-1.17
as such, I am closing this issue. If an issue pops up with OBS packaging, please reopen a new one.

**Comment by matthias50** [comment]
@haircommander, on https://build.opensuse.org/package/show/devel:kubic:libcontainers:testing/cri-o-1.17, I see Debian, Rasbian, and Ubuntu, but no CentOS. Am I missing something?

**Comment by haircommander** [comment]
on the panel that shows the options there's a `Show 5 excluded/disabled results` link. Click that, debian is hiding under it :smile:

**Comment by Stroppel** [comment]
@haircommander, but I have to repeat the question from @matthias50. There ist no CentOS package. Even if I open the show excluded. It shows excluded, meaning it wasn't build. So will there be a chance, that this package will be build für centos or redhat soon?

**Comment by matthias50** [comment]
@Stroppel, Start navigating from this point: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/ and you can find CentOS repos. For example, the CentOS 7 crio 1.18 repo is here: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.18:/1.18.1/CentOS_7/ and the .repo file is https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.18:/1.18.1/CentOS_7/devel:kubic:libcontainers:stable:cri-o:1.18:1.18.1.repo. The getting started guide here has details: https://github.com/cri-o/cri-o.
