### ISSUE TITLE
Add support for crio restart for RuntimeVM (v2) implementation

### ISSUE THREAD

**Issue by sboeuf** [cri-o/cri-o#2112]
`crio` daemon is able to restart and restore pod and containers already running. We need to implement proper support for this feature for the `RuntimeVM` implementation.

**Comment by haircommander** [comment]
@fidencio PTAL

**Comment by fidencio** [comment]
Ok, I will take this one!

**Comment by gozssky** [comment]
Is there any progress on this issue?

**Comment by haircommander** [comment]
I don't believe so. @gozssky do you have any interest in to fix?

**Comment by gozssky** [comment]
@haircommander Yes, I will take a look. This bug does affect our service.

**Comment by haircommander** [comment]
excellent to hear! please reach out if you have any questions
/assign @gozssky

**Comment by gozssky** [comment]
@haircommander I have a submitted a PR https://github.com/cri-o/cri-o/pull/5574. PTAL thanks.
