### ISSUE TITLE
Create a new Kata CI job for testing runtime v2

### ISSUE THREAD

**Issue by sboeuf** [cri-o/cri-o#2113]
In order to validate the proper functioning of the `RuntimeVM` implementation, we need to setup a new Jenkins job on the Kata CI, that would be triggered by a new hook from the CRIO repository.

The setup should be very similar to what is done with the current Kata CI, but the CRIO configuration should be slightly different to make use of the kata-runtime v2 implementation, instead of the kata-runtime OCI compliant runtime.

/cc @chavafg

**Comment by fidencio** [comment]
This can be closed as we have such CI as part of kata-containers nowadays.
