### ISSUE TITLE
CRI-O requires podman-like "cni_default_network" support

### ISSUE THREAD

**Issue by sysrich** [cri-o/cri-o#2121]
**Description**

This ticket started it's life in a discussion at https://github.com/containers/libpod/issues/2370

In short

- the CNI ecosystem is imperfect, and the assumption that all configurations in /etc/cni/net.d will be compatible with each other is not true (eg. flannel not working alongside a basic podman bridge)
- any container runtime should therefore have some way of mitigating those issues
- podman achieves this with its `cni_default_network` configuration parameter, allow podman to be 'locked' to a specific CNI configuration, ignoring what might be placed in /etc/cni/net.d by other CNI solutions (assumedly to be used by other parallel container runtimes)
- It would be highly advantageous if CRI-O had similar functionality

**Comment by vrothberg** [comment]
Thanks a lot for moving the issue over here, @sysrich!

We can get some inspiration from https://github.com/containers/libpod/commit/4f699db8dad0 to fix the issue in CRI-O.

**Comment by haircommander** [comment]
Working on it! (I'd assign myself but I don't have write access to the repo)

**Comment by weteamsteve** [comment]
has there been any updates to this? currently having problems with Kubernetes and Podman working together
