### ISSUE TITLE
[v1.11.11] Manifest Lists and hash pulls fail.

### ISSUE THREAD

**Issue by SleepyBrett** [cri-o/cri-o#2157]
**Description**
If the image to pull is a sha256 pull (aka `docker://docker.io/tomcat@sha256:87ad70ceaafd5c71301b081b37ca2795bd6c7c1a5599a8c92c9447bbd225ae47`) and that sha actually points to an image manifest the pull will fail with a `Digest of source image's manifest would not match destination reference` 

(I have been told the fix for this is on the roadmap somewhere, but I don't see the it spelled out in any open issue, so I thought I'd surface it)

**Steps to reproduce the issue:**
1. attempt to pull `docker://docker.io/tomcat@sha256:87ad70ceaafd5c71301b081b37ca2795bd6c7c1a5599a8c92c9447bbd225ae47`
2. observe `Digest of source image's manifest would not match destination reference`

**Describe the results you received:**
We are currently testing CRI-O mixed with docker nodes in our env (essentially A/B testing). One of our users ran into this problem. Essentially since the sha provided is `87ad70..` which corresponds to a manifest list, once cri-o resolves the proper image to pull for the architecture (in our case amd64 and thus `@sha256:cded14cf64697961078aedfdf870e704a52270188c8194b6f70c778a8289d87e`). The sha verification fails with the above error, this image pulls properly on docker nodes. Once he swapped to that image, all is fine.

**Describe the results you expected:**
I expect similar behavior from docker or at least an error message that allows the user to update to the correct sha for the architecture ( forcing them to download `skopeo` to inspect the manifest is a bit much to ask )

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**
```
crio version 1.11.11
commit: "474f73d81b5931fb4a3fa9a7f73b2e903e3837c1-dirty"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mrunalp** [comment]
@nalind @mtrmac @vrothberg ptal

**Comment by mtrmac** [comment]
Thanks for your report.

We can certainly easily enough add the computed digest value to the error message (…hoping that it won’t lead to abuse by users ignoring malicious manifest digest mismatches and just using whatever the registry sends). That’s not really helpful for automated usage of CRI-O I guess.

Other than that, oh, “fun”. We could, in c/image:
- Teach everything about manifest lists, and record the complete original manifest lists in c/storage. That seems inconsistent / actively misleading if we only pull one arch into c/storage (and we do almost always only want to pull one). It would be _somewhat_ reasonable for c/storage to present a manifest list and report a failure only when trying to use one of the locally-unavailable architecture, but for `copy.Image` to “write” a complete manifest list that it knows refers to missing images is just wrong.
- Modify `storageReference.DockerReference()` to return `nil` to opt out of all of this digest checking. That would be surprising behavior for values that clearly do have that format, and in practice it would likely break callers in Buildah, Podman and elsewhere that expect the value to be present for little good reason.
- The same but cleaner, add a boolean to `storageImageSource` (`storageImageDestination` as well?) to opt out of manifest verification completely.

Either way, opting c/storage out of digest verification is not completely nonsensical, but it’s not clearly safe either — by now someone might have started reliying on c/storage making such checks, especially after we went through the trouble of https://github.com/containers/image/pull/585 to make this all work for deduplicated images.

**Comment by markusthoemmes** [comment]
We're hitting this on CRI-O as well. Knative Serving resolves image references and transforms all non-sha256 image references into direct sha256 references. On images like [python](https://hub.docker.com/_/python), that breaks us.

**Comment by fabiand** [comment]
Naive question: So it's currently not possible to launch an image which is referenced by hash? @mrunalp

**Comment by mnaser** [comment]
This is breaking us from moving to cri-o entirely :(

Is there anything we can do to help?

**Comment by haircommander** [comment]
@nalind @mtrmac what's the status of this issue WRT manifest work?

**Comment by nalind** [comment]
We've got the feature work merged into the image library, the [PR](https://github.com/containers/buildah/pull/1902) for buildah is passing its tests, and the [draft PR](https://github.com/containers/libpod/pull/4310) that incorporates them both into libpod and the [PR for the 1.16 branch](https://github.com/cri-o/cri-o/pull/2859) that pulls them all into CRI-O are failing some tests.

**Comment by haircommander** [comment]
we now support manifest lists, and have for a couple of releases. as such, I'm closing this

**Comment by haslersn** [comment]
Since which version do you support it?

**Comment by haircommander** [comment]
I believe support began in 1.15 or 1.16. I know all of our currently supported versions (1.16-1.18) have support for it

**Comment by haslersn** [comment]
Ah. It seems that the ppa.launchpad.net/projectatomic/ppa/ubuntu is still on `1.15.3-dev`.
