### ISSUE TITLE
Pass metadata to CNI plugins

### ISSUE THREAD

**Issue by umohnani8** [cri-o/cri-o#2207]
We want to be able to access certain pod information over the CNI. The pod information should be passed down to the CNI plugins, so users can easily access them without having to call back into CRI-O or the kubelet.

**Comment by umohnani8** [comment]
@amshinde @paulnivin can you please give some more details on this so we can start work on it.
cc @mrunalp

**Comment by paulnivin** [comment]
As long as https://github.com/kubernetes/kubernetes/pull/63194 is supported (added in 1.12), that's sufficient metadata for our current production use case need. We've yet to test this flow to make sure all the data is plumbed through correctly, but if so, we can close this ticket.

**Comment by mrunalp** [comment]
@paulnivin Have you seen https://github.com/cri-o/cri-o/pull/2233 ?

**Comment by paulnivin** [comment]
@mrunalp That's exactly what we need. FWIW, our instances on AWS are 25Gbps.

**Comment by haircommander** [comment]
closing per^ comment. please reopen if you disagree
