### ISSUE TITLE
Respecting isolcpus

### ISSUE THREAD

**Issue by cliffburdick** [cri-o/cri-o#2213]
**Description**

The linux boot parameter isolcpus attempts to isolate kernel and extraneous applications from running on specific cores. A user must specifically bind to those cores either at application launch or through pthread calls to use them. Currently, the way cgroups and cpusets interacts with isolcpus is not too clear. However, the kernel documentation says that:

```
By default, there is one sched domain covering all CPUs, including those
marked isolated using the kernel boot time "isolcpus=" argument. However,
the isolated CPUs will not participate in load balancing, and will not
have tasks running on them unless explicitly assigned.
```
This does not seem to be the case with Kubernetes. When a machine is started with isolcpus disallowing specific cores from extraneous tasks, normal pods will float to those isolated cores inadvertently. It appears that the cpusets created for each scheduling type ignore the isolcpus directive. Ideally, a user would be able to specify whether a pod is allowed to use the isolated core groups or not, and they would not be allowed to by default.

**Steps to reproduce the issue:**
1. Enable isolcpus on the grub command line
2. Observe kubernetes pods running on the isolated cpus

**Describe the results you expected:**

No pods run on the isolated cpus unless specifically told to do so.

**Output of `crio --version`: 

1.12

**Comment by marquiz** [comment]
Are you using the static cpumanager policy (`--cpu-manager-policy=static`) in Kubernetes? I don't think what you described would happen with the default `none` policy as cpusets are not used for per-workload cpu assignment.

I think this should be filed against kubernetes as it (kubelet) is responsible for selecting the cpuset assigned to each pod.

**Comment by cliffburdick** [comment]
Hi @marquiz, sorry for the delay. It is set to none in kubelet, and someone in the cri-o slack channel suggested opening an issue here since they believe it was cri-o controlling that.

**Comment by haircommander** [comment]
I'm not so sure this is the fault of CRI-O. @cliffburdick did you find anything new out in the past year :smile:

**Comment by cliffburdick** [comment]
@haircommander no, but we somewhat worked around it by writing a script to move all the kubelet cpusets onto a "jailed" group, and our processes/pods are the only ones allowed on the non-jail group.

**Comment by haircommander** [comment]
awesome to hear you found a work around. Can I close this issue then @cliffburdick ?

**Comment by cliffburdick** [comment]
yes, thanks!

**Comment by saschagrunert** [comment]
> @haircommander no, but we somewhat worked around it by writing a script to move all the kubelet cpusets onto a "jailed" group, and our processes/pods are the only ones allowed on the non-jail group.

May I ask you to share the script? Now I'm pretty interested how it works :)

**Comment by retr0h** [comment]
@saschagrunert can we get further details on this, and possibly see the script?

**Comment by cliffburdick** [comment]
Hi @retr0h and @saschagrunert  , I've since left that employer and don't have access to it anymore. Sorry.
