### ISSUE TITLE
HPA does not work with metrics server on pods on nodes backed w/ crio.

### ISSUE THREAD

**Issue by SleepyBrett** [cri-o/cri-o#2271]
Crosslinking this with the main kube repo, there is a similar crosslink in the metrics server repo. Hoping to get to the bottom of this. Because man, this is just not a great situation.

kubernetes/kubernetes#76715

Basically the metrics server does not report any cpu metrics for pods on crio nodes. Therefore the HPA can not act.

**Steps to reproduce the issue:**
1. Please see attached issue, i feel like it's pretty through.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
Crio 1.13.4 and 1.14.1
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mrunalp** [comment]
@haircommander is looking into this.

**Comment by SleepyBrett** [comment]
Note. 1.14.1 seems fine now. I must have screwed up my initial test. Sorry!

**Comment by rhatdan** [comment]
Can we close this issue then?

**Comment by SleepyBrett** [comment]
Yes I believe so. There are some picks into kube-1.13 to fix it there.
