### ISSUE TITLE
Error restarting a stopped container

### ISSUE THREAD

**Issue by adk9** [cri-o/cri-o#2273]
**Description**

Not sure if this is a question for the upstream CRI api or cri-o, but I'll ask anyway.

I'm trying to restart a container by stopping it first and then starting it again. The CRI API spec isn't explicit about the desired behavior for a restart but I'd assume that this should work; otherwise `StartContainer` and `StopContainer` would be useless and `CreateContainer` and `RemoveContainer` would have sufficed.

**Steps to reproduce the issue:**
1. Create a new pod sandbox and container using crictl
2. Start the container: `crictl start <container-id>`
3. Stop and restart the container: `crictl stop <container-id> && crictl start <container-id>` 

**Describe the results you received:**

The container fails to restart the second time with the following error:

```console
FATA[0000] Starting the container "d016874a4a4fb35b985e5af48397e8ee07fc4a6e0c7c7771d54e327ced0e1cf5" failed: rpc error: code = Unknown desc = container d016874a4a4fb35b985e5af48397e8ee07fc4a6e0c7c7771d54e327ced0e1cf5 is not in created state: stopped 
```

**Describe the results you expected:**

I'd expect the container to restart successfully. Is this not the intended behavior?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```console
crio version 1.14.1-dev
commit: "553ff6fa37937bc0c21c6a35b4791c606ce243e6"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mrunalp** [comment]
kubelet creates a new container if it needs to. It doesn't restart stopped containers. See attempt field in pod. If you are using CRI-O with k8s it should all work fine, crictl is really a low level debugging tool.

**Comment by adk9** [comment]
@mrunalp Thanks for the clarification.

I am not using CRI-O with k8s; we're building a new orchestrator that uses CRI-O directly and I'm trying to understand the semantics of start/stop container in CRI.

Am I correct in understanding that it is not possible to start a "stopped" container and a new container has to be created every time I want to run the same container again?

**Comment by haircommander** [comment]
@adk9 yeah, CRI-O follows k8s precisely, so if kubelet doesn't need to start stopped containers, we don't permit it :)

**Comment by haircommander** [comment]
closing this as it was determined this is not an issue. please reopen if you disagree
