### ISSUE TITLE
RFC: Consider switching to CircleCI

### ISSUE THREAD

**Issue by saschagrunert** [cri-o/cri-o#2294]
Hello folks,

I took my time to play around with CircleCI because I had a very good experience in the past with it, especially in comparison to travis.

For my experiment I ported the travis pipeline to CircleCI on my local fork. You can find a working example here: https://circleci.com/workflow-run/c9107abc-9666-4d50-86b0-7fddfd07a1d1

Some beneficial highlights:
- The pipeline runs in overall ~10min (instead of ~1h 15min on travis)
- We have a maximum (free) parallelism of four runners (instead of 2 on travis)
- We pre-built the test image (instead of building it live on travis)
- We have out-of-the-box build artifacts: https://circleci.com/gh/saschagrunert/cri-o/354#artifacts/containers/0
- We have real pipelines with fine granular dependency specification
- We can pass artifacts via "workspaces" to different jobs. This means we do not have to built the binaries multiple times, we simply pass them around
- We have the full flexibility when choosing the build executor: https://circleci.com/docs/2.0/executor-types/
- We have fine-granular build caching (currently used for docker images)

A drawback:
The free version is pretty fast but bound to "build time". If we overdraw this time, currently nothing happens at all. But in the future this can change, so I would recommend to go for a [pro variant](https://circleci.com/pricing/). This can be expensive, so maybe the CNCF can support us with that?

More details can be found in the [CircleCI configuration specification](https://circleci.com/docs/2.0/configuration-reference/). WDYT?

**Comment by mrunalp** [comment]
@saschagrunert Maybe we can add circle CI free account jobs and see how it goes in parallel with travis for a couple of weeks?

**Comment by saschagrunert** [comment]
> @saschagrunert Maybe we can add circle CI free account jobs and see how it goes in parallel with travis for a couple of weeks?

Yes this sounds good, let's do that.
