### ISSUE TITLE
crictl pull image fails with "denied: requested access to the resource is denied" from docker.io registry

### ISSUE THREAD

**Issue by RohanKurane** [cri-o/cri-o#2331]
Hi,

I am attempting to pull an nginx image from the docker.io registry using crictl

```
sudo crictl pull docker.io/crio/nginx
FATA[0000] pulling image failed: rpc error: code = Unknown desc = Error reading manifest latest in docker.io/crio/busybox: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```

The same works with ```quay.io```

The ```/etc/containers/registries.conf``` looks like 
```
[registries.search]
registries = ['docker.io' ,'quay.io' ,'registry.access.redhat.com', 'registry.fedoraproject.org']

[registries.insecure]
registries = []

#blocked (docker only)
[registries.block]
registries = []
```

**Comment by mrunalp** [comment]
@RohanKurane Can you try docker.io/library/nginx instead?

**Comment by RohanKurane** [comment]
Thanks @mrunalp

**Comment by sarbajitpattanaik** [comment]
I am trying to pull a test image using crictl pull docker.io/library/nginx:
And getting error below:
pulling image failed: rpc error: code = Unknown desc = error pinging docker registry registry-1.docker.io: Get "https://registry-1.docker.io/v2/": proxyconnect tcp: dial tcp: lookup http: Temporary failure in name resolution

**Comment by haircommander** [comment]
what version of crictl and cri-o? I am pretty sure that's a sufficiently different problem to warrant a new issue. Also, the error message `Temporary failure in name resolution` says to me that waiting a bit may help (registry problem)

**Comment by sarbajitpattanaik** [comment]
Thaks for replying:

crictl version
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.18.0-dev
RuntimeApiVersion:  v1alpha1

In docker we can set proxy via  /etc/systemd/system/docker.service.d/http-proxy.conf . Is there a way to do for CRIO?

**Comment by vivekanandpoojari** [comment]
@sarbajitpattanaik  You need to create a similar file for cri-o as well.

systemctl status crio
● crio.service - Container Runtime Interface for OCI (CRI-O)
   Loaded: loaded (/usr/local/lib/systemd/system/crio.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/crio.service.d
           └─http-proxy.conf

https://medium.com/@vivekanand.poojari/installing-kubernetes-behind-a-corporate-proxy-bc5582e43fb8
