### ISSUE TITLE
kubectl does not seem to use CRI-O as the runtime engine

### ISSUE THREAD

**Issue by RohanKurane** [cri-o/cri-o#2337]
Hi,

First I want to apologize for asking too many questions. I am very new to CRI-O (a week into learning and using). 

Setup - 
I have a K8s cluster with a single worker node running RHEL on AWS EKS.
I installed CRI-O on the worker node. 
Using ```crictl``` from the worker node directly, I could see the PODs and containers use the CRI-O runtime engine. 

I now have another AWS EC2 instance (not a part of the K8s cluster). I created the cluster from this instance and have kube config file here. 
I tried to create pods and start containers from this host in the K8s cluster using ```kubectl```
I was able to create the Pods and start the containers. However when I do a ```kubectl describe pods``` I do think it is still using docker instead  of the CRI-O for the container.
```Container ID:   docker://eb4a17cce0453eb562xxxxxxx9f1d87e87bcfdee4ad0c7a5```
 
How can I make sure that kubectl also uses the CRI-O from outside the cluster to create Pods and containers in the cluster ? 

@saschagrunert @mrunalp 

Thanks so much for your help
Rohan

**Comment by RohanKurane** [comment]
Got it to work. Closing

**Comment by saschagrunert** [comment]
> First I want to apologize for asking too many questions. I am very new to CRI-O (a week into learning and using).

There is absolutely no need to apologize for asking questions. :hugs: 

> Got it to work. Closing

Would you like to share the solution with us here? Other users could come over the same issue and would be thankful if you share the resolution here.

**Comment by RohanKurane** [comment]
@saschagrunert 
Here is a good link to follow to use CRI-O instead of Docker runtime engine
https://medium.com/errnothxbye/centos-7-with-cri-o-on-eks-ae9684aff764

I will be glad to answer any questions.

**Comment by rhatdan** [comment]
@saschagrunert We should add this link to tuturial.md or add another page describing use cases.
