### ISSUE TITLE
kubeadm init fails with "node not found" error in kubelet logs

### ISSUE THREAD

**Issue by sdeoras** [cri-o/cri-o#2357]
**Description**
I am trying to test cri-o v1.14.0 with k8s 1.14.1 on ubuntu 18.04 and having issues with kubelet not coming up after migrating my single node cluster from docker version 18.09.6 to cri-o v1.14.0.

In particular, I see following errors in the kubelet logs
```
May 12 02:44:09 instance-1 kubelet[11808]: E0512 02:44:09.718884   11808 kubelet.go:2244] node "instance-1" not found
May 12 02:44:09 instance-1 kubelet[11808]: E0512 02:44:09.819154   11808 kubelet.go:2244] node "instance-1" not found
May 12 02:44:09 instance-1 kubelet[11808]: E0512 02:44:09.858204   11808 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://10.138.15.207:6443/apis/node.k8s.io/v1beta1/runtimeclasses?limit=500&resourceVersion=0: dial tcp 10.138.15.207:6443: connect: connection refused
May 12 02:44:09 instance-1 kubelet[11808]: E0512 02:44:09.919388   11808 kubelet.go:2244] node "instance-1" not found
May 12 02:44:10 instance-1 kubelet[11808]: E0512 02:44:10.019786   11808 kubelet.go:2244] node "instance-1" not found
May 12 02:44:10 instance-1 kubelet[11808]: E0512 02:44:10.058555   11808 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: Get https://10.138.15.207:6443/apis/storage.k8s.io/v1beta1/csidrivers?limit=500&resourceVersion=0: dial tcp 10.138.15.207:6443: connect: connection refused

```
I do have `calico` networking config in `/etc/cni/net.d` and the associated binary with calico working with docker.

I followed migration instructions from here: https://github.com/cri-o/cri-o/blob/master/tutorials/kubernetes.md

**Steps to reproduce the issue:**
1. Setup k8s v1.14.1 using docker and install calico
2. Build cri-o v1.14.0 from source and migrate cluster to cri-o
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.14.0
commit: "0b8a2dffba86ae8ef3316ff2030ed226c3f652a1"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
GCP VM instances Ubuntu 18.04LTS image

**Comment by sdeoras** [comment]
The issue seems to be related to `runc` version bundled with `cri-o` v1.14.0. I manually updated `runc` to [1.0-rc6](https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc6) and things worked:

```
sdeoras@kube-1:~/gcp$ kubectl get nodes -o wide
NAME     STATUS   ROLES    AGE   VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
kube-1   Ready    master   25s   v1.14.1   10.138.15.216   <none>        Ubuntu 18.04.2 LTS   4.15.0-1030-gcp   cri-o://1.14.0
sdeoras@kube-1:~/gcp$ kubectl get pods --all-namespaces
NAMESPACE     NAME                      READY   STATUS    RESTARTS   AGE
kube-system   coredns-fb8b8dccf-mscf8   0/1     Running   0          21s
kube-system   coredns-fb8b8dccf-t4kgl   0/1     Running   0          21s
kube-system   kube-proxy-kwshw          1/1     Running   0          21s
sdeoras@kube-1:~/gcp$
```

and no docker!
```
sdeoras@kube-1:~/gcp$ sudo docker --version
sudo: docker: command not found
```

**Comment by mrunalp** [comment]
@sdeoras Happy to hear that it worked for you :) Can we close the issue?

**Comment by sdeoras** [comment]
@mrunalp yes, we can close this issue. thanks.

**Comment by ptone** [comment]
@sdeoras can you share what you mean by "manually updated runc"?

I have `cri-o-runc is already the newest version (1.0.0-rc6-1~dev~ubuntu18.04~ppa44).`

crio from source build:
```
crio version 1.14.0-dev
commit: "b1d593f3041dc51b14d0b56e3089bc2507db899e"
```
kubeadm 

```
# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:20:34Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

I get looping in the kubelet logs of:

```
Jun 01 17:17:01 kube-box kubelet[7972]: E0601 17:17:01.111886    7972 kubelet.go:2244] node "kube-box" not found
Jun 01 17:17:01 kube-box kubelet[7972]: E0601 17:17:01.212224    7972 kubelet.go:2244] node "kube-box" not found
Jun 01 17:17:01 kube-box kubelet[7972]: E0601 17:17:01.259640    7972 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: Get https://10.168.15.216:6443/apis/storage.k8s.io/v1beta1/csidrivers?limit=500&resourceVersion=0: dial tcp 10.168.15.216:6443: connect: connection refused
```

I saw you referenced this as an 18.04 GCP VM - which is also where I am trying this.

Docker on this set up runs fine.

**Comment by ptone** [comment]
If I update go.mod to downgrade runc from rc8 to rc6 I get build errors of:

"panic: proto: duplicate enum registered: CriuCgMode"

I also tried replacing the packaged system runc with one from source so I have:

```
# runc --version
runc version 1.0.0-rc8+dev
commit: 5ef781c2e7acc776b1ebee5c25c2791b3a8dc139
spec: 1.0.1-dev
```

But none of this is addressing the node not found issue

**Comment by ptone** [comment]
possibly related: https://github.com/kubernetes/kubernetes/issues/77801

**Comment by sdeoras** [comment]
@ptone: i am simply overwriting runc with an [older version](https://github.com/opencontainers/runc/releases/download/v1.0.0-rc6/runc.amd64) of it.

**Comment by sivakg2000** [comment]
Im also getting the same error while trying to setup kubernet with cri-o

My cluster info ( Cento OS 7 )
```bash
#runc --v
runc version spec: 1.0.0
#crio --v
crio version 1.11.11-1.rhaos3.11.git474f73d.el7
#kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:41Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"} 
```

**Comment by worawutchan** [comment]
Same error too

```
> #runc --version
> runc version spec: 1.0.0
> #crio --version
> crio version 1.11.11-1.rhaos3.11.git474f73d.el7
># kubeadm version  
kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:41Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
```

**Comment by sirsikar-lalit** [comment]
We need to have docker and kublet run with the same cgroup driver. In my case on CentOS 7.6 I could fix the issue by adding <--exec-opt native.cgroupdriver=systemd> to docker systemd process and adding <--cgroup-driver=systemd> to kubelet systemd process. This way both kubelet and docker are consuming the same cgroup-driver and both operate normally.

Most likely these drivers can be set with any other driver types as well but that was not a part of my testing.
