### ISSUE TITLE
How to drive cri-o via CRI without Kubernetes: systemd cgroup error?

### ISSUE THREAD

**Issue by estesp** [cri-o/cri-o#2383]
Sorry for the generic issue, but I can't seem to find the right solution after reading through various issues and PRs that are related, but not exactly my issue.

Background: have received recent issues in [`bucketbench`](https://github.com/estesp/bucketbench) re: cri-o support not working. The CRI driver for bucketbench was contributed quite awhile ago and several k8s imports were stale, which I've now fixed to make the driver viable again.

At this point, however, when pointing at the crio CRI socket endpoint I receive this error when bucketbench starts up:
```
Error: error during bench validate: Driver validation: error creating test container: rpc error: code = Unknown desc = cri-o configured with systemd cgroup manager, but did not receive slice as parent: default
```

This is using the following version from the Ubuntu PPA on a pristine 18.04 VM image: **crio version 1.13.1-dev**

Note that I have no Kubernetes installation here--this is a pure use of the CRI endpoint from a CRI "implementation" that allows any CRI runtime to be driven with basic commands (pod start, stop, rm, etc.).

Endpoint itself responds to CRI, of course, but I assume it is the attempt to start a pod that causes the above error:
```
$ sudo crictl -r unix:///var/run/crio/crio.sock version
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.13.1-dev
RuntimeApiVersion:  v1alpha1
```

**Comment by mrunalp** [comment]
You can configure crio to use the cgroupfs cgroup_manager in crio.conf or set cgroup_parent to be a slice in you sandbox config json.

**Comment by haircommander** [comment]
hey @estesp is there more you need for this issue or is it good to close?

**Comment by estesp** [comment]
Oh! Totally forgot I had this open issue; I think I was up and running, but even if not, I got the info I needed. Will go ahead and close.

**Comment by sdeoras** [comment]
Hi Folks, i am running into this issue and don't have the flexibility to change cgroup manager in cri-o config file. How should I be changing this entry in sandbox_config.json? Thanks.
