### ISSUE TITLE
Container hostname is weird to begin with

### ISSUE THREAD

**Issue by RohanKurane** [cri-o/cri-o#2385]
@saschagrunert @mrunalp 

This is by no means a CRI-O related question but I wanted to see if you guys have run into this and have any opinions. 

When I launch a CRI-O container and go into it and do a export of the env variables, the hostname is not what returned by the `hostname` command. Why is this ? And how can I fix it to be what is in `/etc/hostname` when I first ssh into the container ?

**Comment by saschagrunert** [comment]
Hey @RohanKurane, the hostname is usually set by the sandbox configuration, like here:
https://github.com/cri-o/cri-o/blob/2de918dae6548b743a5bc8f7ea5a47e67af281b0/test/testdata/sandbox_config.json#L8

Every container within this sandbox should get that hostname. If that is not the case, then this could be issued by the container image which could do something unexpected during startup.

Is the issue you mentioned bound to a specific container image? Are you able to share the sandbox and container configuration with us? :) Thanks in advance!

**Comment by RohanKurane** [comment]
@saschagrunert I was able to get around the issue temporarily by reading the contents of `/etc/hostname`. 
Let me check what you pointed out and get back to you. 

In the meantime for an unrelated issue - 
What is the command to deploy a yaml deployment from a running CRI-O container ? 
something like what kubectl does : `kubectl create -f xxx`. If I want to do something from a CRI-O container, is that possible ?

**Comment by RohanKurane** [comment]
never mind above question. Going to close this issue out for now. I installed kubectl as part of the container image and going to try to use it to do deployments from a running CRI-O container
