### ISSUE TITLE
`reload` just kills crio

### ISSUE THREAD

**Issue by cgwalters** [cri-o/cri-o#2391]
https://github.com/openshift/installer/pull/1761#discussion_r285712841

As far as I can tell, no commit to crio has ever done anything with `SIGHUP`, so I suspect the `ExecReload=/bin/kill -s HUP $MAINPID` was cargo culted from some other unit.

**Comment by cgwalters** [comment]
PR at https://github.com/cri-o/cri-o/pull/2349

**Comment by saschagrunert** [comment]
Hey @cgwalters, do we still need this issue here? On the master branch the signal handler exist now as already mentioned by @mrunalp. Do you need a specific set of options which should support the update feature during reload? This would be a great input for further developments. :)

**Comment by cgwalters** [comment]
Nah, we need to refactor the code to configure crio before starting it.

But FWIW what we were (re)configuring is the `pause_image`.

**Comment by saschagrunert** [comment]
> But FWIW what we were (re)configuring is the `pause_image`.

Alright, I guess I will follow up on this.

**Comment by cgwalters** [comment]
> Alright, I guess I will follow up on this.

https://github.com/openshift/installer/pull/1768 changes OpenShift so we don't need this anymore right now FWIW.  So I wouldn't worry about it too much, but it's up to you!
