### ISSUE TITLE
Sign Centos7 packages 

### ISSUE THREAD

**Issue by Atoms** [cri-o/cri-o#2401]
Centos7 packages are not being signed, therefore issues arise when we want to enforce gpg checks.
We at kubespray do not want to disable gpg checks to install package, this can lead to some security issues

https://github.com/kubernetes-sigs/kubespray/pull/4781

**Comment by mrunalp** [comment]
@lsm5 ptal.

**Comment by DanyC97** [comment]
@lsm5 fyi in case you see come across this notification before, i've also sent an email on centos-devel mailer (you can reach me on irc or mailer -whatever works for you). thx

**Comment by lsm5** [comment]
@DanyC97 i'll check with centos infra on syncing to mirror.c.o. I really wish they had setup centpkg and dist-git or something to take care of this than filing bugs everytime.

**Comment by DanyC97** [comment]
> @DanyC97 i'll check with centos infra on syncing to mirror.c.o. I really wish they had setup centpkg and dist-git or something to take care of this than filing bugs everytime.

that is double @lsm5 , reach out to me on centos-devel irc and happy to help out

**Comment by haircommander** [comment]
@dougsland @lsm5 can this be done with OBS?

**Comment by dougsland** [comment]
@Atoms this still an issue? Have you tried the binaries from OBS (build.opensuse.org)?

**Comment by Atoms** [comment]
i think this is sorted, but not sure how, we can close this issue, if we will need help, I will reopen issue.
