### ISSUE TITLE
cri-o w/ Kubernetes v1.14 connects pods to wrong subnets when using Weave or kube-router or Flannel CNI plugin

### ISSUE THREAD

**Issue by ghglza** [cri-o/cri-o#2411]
**Description**
with k8s v1.13 and v1.14, after k8s installation pods are reproduceably connected to wrong subnets:

**Steps to reproduce the issue:**
*** provision Kubernetes via kubeadm
*** use cri-o as runtime together with the Weave or kube-router CNI plugin.

**Describe the results you received:**
*** on VirtualBox based VMs, according to "kubectl get po -w" static pods are connected to the NATted VirtualBox default NIC eth0 although a dedicated "host-only" NIC eth1 is configured for each node VM, and its IP address specified for k8s via kubeadm (see below)
  This does in our experience not impair the cluster's functionality (indicating this is in fact a display/reporting error, i.e.  the pods are only shown on the wrong subnet?).
*** Much worse is that in both environments, non-static pods (i.e. CoreDNS which is deployed by kubeadm as default) are connected to the IP network that is configured as "crio-bridge" in /etc/cni/net.d/100-crio-bridge instead to the pod subnet specfied to kubeadm.
  This of course makes the cluster services (which are generated on the pod or service subnets) fail due to the endpoint IPs not matching the pod IPs.

**Describe the results you expected:**
In the case of the VirtualBox based nodes, static pods managed by the kubelets should be connected to the host-only dediacted NIC.
In both cases, pods managed by k8s should be connected to the pod or service subnets specified to kubeadm.

**Additional information you deem important (e.g. issue happens only occasionally):**
*** Weird is that during startup of a cluster node, some of the static pods (e.g. kube-proxy) are shown temporarily with correct eth1 IP addressses for a short time -- but once k8s has booted completely all of the static pods have the wrong IPs.

*** We have found a workaround for both problems is to directly after cluster installation
+ restart first cri-o and then kubelet via systemd on each cluster node (his fixes the wrong IPs of static pods, and has to be repeated after each reboot of a node)
+ then, delete the CNI plugin pods (i.e. Weave or kube-router) on each cluster node
+ repeat restart of k8s related host services as described above
+ finally, delete the non-static pods that are connected to the CNI bridge subnet (i.e. CoreDNS).
The deleted pods are restarted by their controllers, where the non-static pods are now on the correct pod-subnet, and the cluster works fine (pod deletion needs not to be repeated after cluster node reboots)

*** Our questions are:
**** Is cri-o expected to work in the scenario described above?
     We had a problem report opened against kubeadm (see https://github.com/kubernetes/kubeadm/issues/1363), but the comments there seem to indicate that kubeadm + cri-o should theoretically work, but is a bit of a "fringe combination" from the perspective of the kubeadm community
**** If cri-o should work, which version should be used with k8s v1.14?
     The CentOS yum repositories offer RPMs with configuration and systemd support, but these seem to be quite outdated (v1.11).
**** If we follow the release-1.14 branch of cri-o, is it enough to generate /etc/crio/crio.conf with the cri-o version
     that is installed (see below), or has the CNI plugin configuration under /etc/cni also to be updated?
**** Which of the k8s CNI plugins work out of the box with cri-o?
     E.g. the weave utility script fails to reset the CNI configuration, it seems to be tied tightly to a running Docker daemon.

**Output of `crio --version`:**
We tried several versions of cri-o, and currently use

```
crio version 1.14.2-dev
commit: "238229ea3b49a1add6e14e577e6e9e208ec0cf57"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Our cluster nodes are VMs running CentOS 7 under VMWare and VirtualBox hypervisors.
The problems described above arise whith both Weave 2.5.2, and kube-router 0.3.1 CNI plugins

kubeadm init configuration (for VirtualBox setup with the "host-only" adapter configured to be attached to the 192.168.99 subnet):

```
---
apiVersion: kubeadm.k8s.io/v1beta1
clusterName: k8m.qstage.dpt.suborg.int.com
controlPlaneEndpoint: 192.168.99.10
kind: ClusterConfiguration
kubernetesVersion: v1.14.2
networking:
  dnsDomain: qstage.dpt.suborg.int.com
  podSubnet: 172.18.0.0/16
  serviceSubnet: 172.19.0.0/16
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
clusterCIDR: 172.18.0.0/16
kind: KubeProxyConfiguration
---
apiVersion: kubelet.config.k8s.io/v1beta1
clusterDomain: qstage.dpt.suborg.int.com
cgroupDriver: systemd
clusterDNS:
- 172.19.0.10
evictionHard:
  imagefs.available: 5%
  nodefs.available: 5%
evictionSoft:
  imagefs.available: 5%
  nodefs.available: 5%
evictionSoftGracePeriod:
  imagefs.available: 10h
  nodefs.available: 10h
evictionPressureTransitionPeriod: 10h
hairpinMode: hairpin-veth
kind: KubeletConfiguration
podCIDR: 172.18.0.0/16
runtimeCgroups: /systemd/system.slice
kubeletCgroups: /systemd/system.slice
---
apiVersion: kubeadm.k8s.io/v1beta1
nodeRegistration:
  criSocket: unix:///var/run/crio/crio.sock
  name: k8m
  kubeletExtraArgs:
    runtime-cgroups: /systemd/system.slice
  taints: []
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.99.10
```

cri-o bridge configuration in /etc/cni/net.c/100-crio-bridge (installed by CentOS cri-o RPM):

```
{
    "cniVersion": "0.3.0",
    "name": "crio-bridge",
    "type": "bridge",
    "bridge": "cni0",
    "isGateway": true,
    "ipMasq": true,
    "ipam": {
        "type": "host-local",
        "subnet": "10.88.0.0/16",
        "routes": [
            { "dst": "0.0.0.0/0" }
        ]
    }
}
```

cri-o configuration in /etc/crio/crio.conf is generated by 

```
crio --config /etc/crio/crio.conf
     --cgroup-manager systemd --cni-plugin-dir /opt/cni/bin --conmon /usr/libexec/crio/conmon
     --log-journald --selinux=false config
```

Weave setup is standard, i.e. copied from

```
curl --header "Accept: application/json" "https://cloud.weave.works/k8s/v1.10/net?k8s-version=$(kubectl version | base64 | tr -d '\n')" | jq .
```

except that the pod subnet is specified in the deployment YAML via setting the IPALLOC_RANGE environmment variable.

Log messages:

for the master node, k8s logs an event 

```
CRI error: /sys is read-only: cannot modify conntrack limits, problems may arise later (If running Docker, see docker issue #24000)
```

cri-o logs

```
May 22 10:03:05 k8m crio[2709]: weave-cni: error removing interface "eth0": Link not found
May 22 10:03:05 k8m crio[2709]: weave-cni: unable to release IP address: Delete http://127.0.0.1:6784/ip/8bf721ff3fd6fdaa712339c8f2f53b377f0dfe47e7ea8387ccaac27f47b377c6: dial tcp 127.0.0.1:6784: connect: connection refused
May 22 10:03:05 k8m crio[2709]: time="2019-05-22 10:03:05.122774911+02:00" level=error msg="Error deleting network: Delete http://127.0.0.1:6784/ip/8bf721ff3fd6fdaa712339c8f2f53b377f0dfe47e7ea8387ccaac27f47b377c6: dial tcp 127.0.0.1:6784: connect: connection refused"
May 22 10:03:05 k8m crio[2709]: time="2019-05-22 10:03:05.122791969+02:00" level=error msg="Error while removing pod from CNI network "weave": Delete http://127.0.0.1:6784/ip/8bf721ff3fd6fdaa712339c8f2f53b377f0dfe47e7ea8387ccaac27f47b377c6: dial tcp 127.0.0.1:6784: connect: connection refused"
May 22 10:03:07 k8m crio[2709]: time="2019-05-22 10:03:07.020894336+02:00" level=error msg="Error adding network: unable to allocate IP address: Post http://127.0.0.1:6784/ip/5f543bfb4e21e5d1b467b2475f9b2af937da500c31d04b6baad1c52ec5fb66c6: dial tcp 127.0.0.1:6784: connect: connection refused"
May 22 10:03:07 k8m crio[2709]: time="2019-05-22 10:03:07.020915201+02:00" level=error msg="Error while adding pod to CNI network "weave": unable to allocate IP address: Post http://127.0.0.1:6784/ip/5f543bfb4e21e5d1b467b2475f9b2af937da500c31d04b6baad1c52ec5fb66c6: dial tcp 127.0.0.1:6784: connect: connection refused"
M
```

shows up several times in the journal of the master node.

In the nodes systemd journal, kubelet logs many messages
```
node9.qstage.dpt.suborg.int.com kubelet[61333]: E0528 14:29:44.672017   61333 manager.go:1181] Failed to create existing container:
/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod89439d2e_7d5e_11e9_bb2f_0050569516ef.slice/crio-6e60080685c8718d644d16a5fd36e410c229d1d51852b6c2ea3647bcbd22f999.scope:
invalid character 'c' looking for beginning of value

```

**Comment by saschagrunert** [comment]
Hey @ghglza :wave:, thanks for the detailed bug report and all these information.

> VirtualBox based VMs, according to "kubectl get po -w" static pods are connected to the NATted VirtualBox default NIC eth0 although a dedicated "host-only" NIC eth1 is configured for each node VM, and its IP address specified for k8s via kubeadm

I had similar problems in the past, can you try to swap the adapters that the host-only is the first one?

> Much worse is that in both environments, non-static pods (i.e. CoreDNS which is deployed by kubeadm as default) are connected to the IP network that is configured as "crio-bridge" in /etc/cni/net.d/100-crio-bridge instead to the pod subnet specfied to kubeadm.

I'm not familiar with Weave, but how do you provision the CNI configuration of it? I would expect that after the deployment of Weave the folder `/etc/cni/net.d/` contains a higher priority interface (than the default 100-crio-bridge) which will be picked up by CRI-O, right?

**Comment by ghglza** [comment]
Hi @saschagrunert ,
have tried to set up the VirtualBox VMs with host-only as 1st adapter in the past, but gave up due to  problems with the CentOS installer... is cri-o limited to setups with only one NIC?
I was under the impression that having k8s network traffic on a dedicated NIC is a common usage CNI usage pattern.

Ref. the Weave CNI configuration, this is done by the weave shell script in the weave container image -- this creates /etc/cni/net.d/10-weave.conflist

{
    "cniVersion": "0.3.0",
    "name": "weave",
    "plugins": [
        {
            "name": "weave",
            "type": "weave-net",
            "hairpinMode": true
        },
        {
            "type": "portmap",
            "capabilities": {"portMappings": true},
            "snat": true
        }
    ]
}

Should we rename this file so that it has lower priority than 100-crio-bridge.conf, or do you think the configuration's content is wrong?

**Comment by saschagrunert** [comment]
> is cri-o limited to setups with only one NIC?

No, that is a think related to the configuration of Kubernetes and the CNI plugin.

> I was under the impression that having k8s network traffic on a dedicated NIC is a common usage CNI usage pattern.

Yes it is, but it may cause problems with auto-discovery of CIDRs. But I saw that you hard-code the podCIDR in the kubeadm configuration yaml, and if that one is correct the Kubernetes configuration should be correct too.

> Ref. the Weave CNI configuration, this is done by the weave shell script in the weave container image -- this creates /etc/cni/net.d/10-weave.conflist
> 
> ```
> {
>     "cniVersion": "0.3.0",
>     "name": "weave",
>     "plugins": [
>         {
>             "name": "weave",
>             "type": "weave-net",
>             "hairpinMode": true
>         },
>         {
>             "type": "portmap",
>             "capabilities": {"portMappings": true},
>             "snat": true
>         }
>     ]
> }
> ```

This looks good to me. I think I have to see If I can reproduce a similar setup somehow to actually help here any further.

**Comment by ghglza** [comment]
Updating cri-o to v1.14.2 doesn't have any effects on the problems described above.

**Comment by ghglza** [comment]
We have set up the VirtualBox based cluster with Flannel v0.11.0-amd64, and the following results:

* the problem with the static pods shown with the wrong eth0-based IPs remains (but also w/o observable ill effects up to now)
* but the problem with the pods on the k8s subnet is gone, i.e. the CoreDNS pods are connected to the correct Flannel subnet 10.244.0.0

So could it be that cri-o has might currently make some assumptions on CNI plugin behavior that are fulfilled by Flannel, but not Weave and kube-router?

**Comment by saschagrunert** [comment]
> So could it be that cri-o might currently make some assumptions on CNI plugin behavior that are fulfilled by Flannel, but not Weave and kube-router?

I'm not sure if this answers your question, but generally it behaves like this:

- CRI-O looks in `/etc/cni/net.d` for possible network configuration and pick the first one (by filename) on startup. Changing the file order during CRI-O runtime does currently not affect the currently selected network configuration (this might be an issue).

This means we first have to ensure that (in your case) `10-weave.conflist` is the highest priority network configuration.

- I played around with the weave CNI plugin and finally got it working on my local machine via something like: `sudo CONTAINER_RUNTIME=remote NET_PLUGIN=kubenet CONTAINER_RUNTIME_ENDPOINT='unix:///var/run/crio/crio.sock' ALLOW_PRIVILEGED=true ./hack/local-up-cluster.sh`. Weave seems to automatically pick a CIDR of `10.32.0.0/12`, whereas your mentioned pod CIDR is `172.18.0.0/16`.

So I guess this default configuration does not work in your case. I think you have to change the weave DaemonSet to fix the `IPALLOC_RANGE` range of the pods like this:

```
      containers:
        - name: weave
          env:
            - name: IPALLOC_RANGE
              value: 172.18.0.0/16
```

Please be aware that weave maintains some internal state database so I guess you have to wipe `/var/lib/weave` if you try to change it during runtime. On my local machine I changed the CIDR to `173.0.0.0/16` and now every pod gets an address from this subnet, whereas weave shows this within the logs:

```
> kubectl -n kube-system logs -f weave-net-jghzn weave
INFO: 2019/06/04 11:03:16.211737 Command line options: map[docker-api: http-addr:127.0.0.1:6784 ipalloc-init:consensus=1 ipalloc-range:173.0.0.0/16 expect-npc:true host-root:/host nickname:127.0.0.1 no-dns:true datapath:datapath port:6783 conn-limit:100 db-prefix:/weavedb/weave-net metrics-addr:0.0.0.0:6782 name:66:80:e2:43:c0:47]
INFO: 2019/06/04 11:03:16.211791 weave  2.5.2
INFO: 2019/06/04 11:03:16.464101 Re-exposing 10.32.0.1/12 on bridge "weave"
INFO: 2019/06/04 11:03:16.521752 Re-exposing 10.32.0.2/12 on bridge "weave"
INFO: 2019/06/04 11:03:16.561736 Bridge type is bridged_fastdp
INFO: 2019/06/04 11:03:16.561802 Communication between peers is unencrypted.
INFO: 2019/06/04 11:03:16.663064 Our name is 66:80:e2:43:c0:47(127.0.0.1)
INFO: 2019/06/04 11:03:16.663418 Launch detected - using supplied peer list: [127.0.0.1]
INFO: 2019/06/04 11:03:16.702308 Checking for pre-existing addresses on weave bridge
INFO: 2019/06/04 11:03:16.702824 weave bridge has address 10.32.0.1/12
INFO: 2019/06/04 11:03:16.702876 weave bridge has address 10.32.0.2/12
INFO: 2019/06/04 11:03:16.743003 Found address 10.32.0.5/12 for ID _
INFO: 2019/06/04 11:03:16.743210 Found address 10.32.0.5/12 for ID _
INFO: 2019/06/04 11:03:16.745563 [allocator 66:80:e2:43:c0:47] No valid persisted data
INFO: 2019/06/04 11:03:16.760682 [allocator 66:80:e2:43:c0:47] Initialising via deferred consensus
INFO: 2019/06/04 11:03:16.760738 Sniffing traffic on datapath (via ODP)
INFO: 2019/06/04 11:03:16.760926 ->[127.0.0.1:6783] attempting connection
INFO: 2019/06/04 11:03:16.761103 ->[127.0.0.1:45867] connection accepted
INFO: 2019/06/04 11:03:16.761463 ->[127.0.0.1:6783|66:80:e2:43:c0:47(127.0.0.1)]: connection shutting down due to error: cannot connect to ourself
INFO: 2019/06/04 11:03:16.761486 ->[127.0.0.1:45867|66:80:e2:43:c0:47(127.0.0.1)]: connection shutting down due to error: cannot connect to ourself
INFO: 2019/06/04 11:03:16.765640 Listening for HTTP control messages on 127.0.0.1:6784
INFO: 2019/06/04 11:03:16.765990 Listening for metrics requests on 0.0.0.0:6782
INFO: 2019/06/04 11:03:17.281712 [kube-peers] Added myself to peer list &{[{66:80:e2:43:c0:47 127.0.0.1}]}
DEBU: 2019/06/04 11:03:17.290296 [kube-peers] Nodes that have disappeared: map[]
INFO: 2019/06/04 11:03:17.317619 [allocator 66:80:e2:43:c0:47] Address 10.32.0.1/12 claimed by weave:expose - not in our range
INFO: 2019/06/04 11:03:17.321434 [allocator 66:80:e2:43:c0:47] Address 10.32.0.2/12 claimed by weave:expose - not in our range
INFO: 2019/06/04 11:03:17.325194 [allocator 66:80:e2:43:c0:47] Address 10.32.0.5/12 claimed by _ - not in our range
INFO: 2019/06/04 11:03:17.329414 [allocator 66:80:e2:43:c0:47] Address 10.32.0.5/12 claimed by _ - not in our range
173.0.0.1
127.0.0.1
DEBU: 2019/06/04 11:03:17.377445 registering for updates for node delete events
```

I guess there are further configuration tweaks possible like [described here](https://github.com/weaveworks/weave/blob/master/site/kubernetes/kube-addon.md#manually-editing-the-yaml-file).

Does this bring you any further?

**Comment by ghglza** [comment]
Thanks!
But no, sorry -- we already had set IPALLOC_RANGE in the Weave k8s deployment YAML set to the pod CIDR as specified to kubeadm (please see sect. "Additional environment details" in the problem description above).

Ref. the other parameters in the command line you use, the k8s deployment starts the Weave containers w/ 

```
securityContext:
  privileged: true
```
so privilege elevation seems to be covered.

And I guess if we had one of the other parameters wrong, k8s would not come up at all.

As the problem also "survives" a complete teardown of the VirtualBox VMs, I don't think that some configuration remnants under /var/lib/weave are the root cause.

**Comment by ghglza** [comment]
Ref. other possible configuration parameters for the Weave plugin, we experimented with setting KUBE_PEERS to the list of cluster node IPs on the VirtualBox host-only network -- but this only resulted in the Weave containers going into a crash loop.

Do you think setting WEAVE_EXPOSE_IP (resp. to which value -- the crio bridge subnet?) would fix the problem?

We gave up playing with Weave configuration parameters after discovering that using kube-router as CNI plugin resulted in the very same problems... this gave us the impression that this could be a generic cri-o bug.

**Comment by saschagrunert** [comment]
I think the issue might me more related to the combination of the interfaces in the VirtualBox environment and weave net. Are you able to share the VMs here? I might have a look into the adapter configuration as well if you want.

**Comment by ghglza** [comment]
The VirtualBox VMs are generated with Packer, here the builder JSON

```
{
  "_comment": "VirtualBox base image specificaation for k8s nodes, build by running `packer build k8sbase.json`",

  "builders": [
  {
    "boot_command": [
      "<up><wait><tab> text ks=http://{{.HTTPIP}}:{{.HTTPPort}}/centos7-ks.cfg"
    ],
    "disk_size": "14540",
    "guest_additions_mode": "disable",
    "guest_additions_path": "VBoxGuestAdditions_{{.Version}}.iso",
    "guest_os_type": "RedHat_64",
    "hard_drive_interface": "sata",
    "headless": "true",
    "http_directory": "data",
    "iso_checksum": "6d44331cc4f6c506c7bbe9feb8468fad6c51a88ca1393ca6b8b486ea04bec3c1",
    "iso_checksum_type": "sha256",
    "iso_urls": [
      "file:///{{env `HOMEDRIVE`}}/{{env `HOMEPATH`}}/VirtualBox\u0020VMs/CentOS-7-x86_64-DVD-1810.iso",
      "{{user `iso_path`}}/CentOS-7-x86_64-DVD-1810.iso",
      "http://mirrors.kernel.org/centos/7.6.1810/isos/x86_64/CentOS-7-x86_64-DVD-1810.iso"
    ],
    "keep_registered": "true",
    "name": "centos7",
    "output_directory": "VMImages/centos7",
    "shutdown_command": "sudo shutdown -P now",
    "ssh_password": "XXXXXXXXX",
    "ssh_username": "dev",
    "ssh_wait_timeout": "600s",
    "type": "virtualbox-iso",
    "vboxmanage": [
      ["modifyvm", "{{.Name}}", "--memory", "4096"],
      ["modifyvm", "{{.Name}}", "--cpus", "1"],
      ["modifyvm", "{{.Name}}", "--paravirtprovider", "default"],
      ["modifyvm", "{{.Name}}", "--nictype1", "virtio"],
      ["modifyvm", "{{.Name}}", "--nic2", "hostonly", "--hostonlyadapter2", "VirtualBox Host-Only Ethernet Adapter #2"],
      ["modifyvm", "{{.Name}}", "--nictype2", "virtio"]
    ],
    "virtualbox_version_file": ".vbox_version",
    "vm_name": "centos7"
  }
}
```

Please consider that the worse part of the problem (i.e. CoreDNS pods connected to the cri-o bridge NIC instead to the k8s pod subnet) also occurs on VMWare VMs with only 1 host NIC eth0.
And that both problems are also present when using kube-router as CNI plugin, and gone with Flannel.

**Comment by ghglza** [comment]
Upgrading our clusters to k8s v1.14.3 / cri-o 1.14.3-dev commit 615c561 doesn't have any effect on the problems described above.

Additional information: on the master node of each of our the VMWare based clusters, cri-o logs

crio[110878]: weave-cni: Delete: no addresses for 306217d17b340916534a1b6d991e524d9bf68938475317aa846674e42c67e662

several times.
Up to now, these error messages do not appear in the master node journal of VirtualBox based clusters.

**Comment by saschagrunert** [comment]
Hey @ghglza , I still found no time to create such a test setup for myself but I will schedule it for the next week if that is okay for you.

**Comment by ghglza** [comment]
Thanks @saschagrunert !
Next week is completely ok for us... our main interest is to have a production grade cri-o with Weave or kube-router available in the medium turn.
We don't want to use Docker for security reasons, and are currently a bit nervous on whether we can really replace it by cri-o, resp. which of the more advanced CNI plugins we should use for that.

**Comment by saschagrunert** [comment]
Hi @ghglza I took my time to do a setup in VirtualBox and found no big issues related to CRI-O. I still assume that there is some network routing issue between the configured VMs. Can you provide me a logfile of CRI-O which I can check out?

**Comment by ghglza** [comment]
Hi @saschagrunert ,
thanks for trying to reproduce this!
Do I read you correctly in that the pods in your k8s installation were connected to the correct (i.e. VirtualBox "host-only") subnet?

We have rebuilt a VirtualBox cluster, and executed the workaround described in the initial PR above.
Please find a  typescript and the CRI-O journal entries attached.
[criolog.txt](https://github.com/cri-o/cri-o/files/3286238/criolog.txt)

**Comment by ghglza** [comment]
Unfortunately, when upgrading to k8s v1.15.0 / crio 1.14.5-dev commit 1ac991b the situation gets worse: the workaround described above fails.

* With the VirtualBox based VMs, the static pods stay connected to the NATted NIC.
  But after applying the workaround, at least the dynamic pods are switched to the subnet specified to kubeadm during cluster installation, and the cluster seems to work.

* BUT on the VMWare VMs, no amount of restarting crio / kubelet host system services or CNI service and CoreDNS pods cures the bogus IP addresses of the CoreDNS pods -- they just stay connected to the CNI brigde network.
  And though the endpoints for the CoreDNS pods are configured correctly (i.e. also on the CNI bridge network), cluster-internal DNS via the k8s service fails as the latter has assigned an IP on the pod subnet specified to kubeadm.
  Even switching to Flannel as CNI plugin (which worked fine out of the box under k8s v1.14 w/o any workaround applied) doesn't help: the combination of CNI plugin / cri-o / k8s ignores the specified pod subnet, and places dynamically created pods on the CNI bridge subnet.

Would it be helpful to upload cri-o logs with increased verbosity?

**Comment by saschagrunert** [comment]
> Would it be helpful to upload cri-o logs with increased verbosity?

Yeah we could have a look into them as well. :)

**Comment by ghglza** [comment]
On closer inspection, it turned out that we had failed to install the /etc/crio/crio.conf generated by CRI-O 1.14.
After correcting this, upgrading to CRI-O version 1.14.6-dev (commit 3b79e1a), rebooting the VMWare VMs, and making sure all k8s and CRI-O related SDN NICs are deleted prior to each installation of k8s, the restart workaround works again on the VMWare boxes.
However, with k8s v1.15.0, we have to apply the workaround also with Flannel -- this was not the case with older versions of k8s (where the workaround was only needed with Weave or kube-router CNI plugins).
I have appended CRI-O verbose logs and kubelet logs for both VM types.

**Comment by ghglza** [comment]
[logs.tar.gz](https://github.com/cri-o/cri-o/files/3346359/logs.tar.gz)

**Comment by ghglza** [comment]
Upgrading to CRI-O release-1.15.1dev commit f61719a didn't have any effect on the IP address problem.

However, when restarting the CoreDNS pods they got stuck in state "ContainerCreating"

kube-system   coredns-5c98db65d4-5tx24              0/1     ContainerCreating   0          84s   <none>        node27            <none>           <none>
kube-system   coredns-5c98db65d4-95vv2              0/1     ContainerCreating   0          83s   <none>        node26             <none>           <none>

with a CNI related error state (output of "kubectl -n kube-system describe pod coredns-5c98db65d4-5tx24" ):

Warning  FailedCreatePodSandBox  6s    kubelet, node27  Failed create pod sandbox: rpc error: code = Unknown desc = failed to create pod netw
ork sandbox k8s_coredns-5c98db65d4-5tx24_kube-system_89a7072b-c806-4755-8b82-4774b3730025_0(5f696ea2ab4ff8e50ad6bb4444e80b34fe4aa450a632b310145061a79
05f2544): failed to set bridge addr: "cni0" already has an IP address different from 172.18.2.1/24

where the CRI-O bridge interface cni0 is configured to the default IP 10.88.0.0/16

**Comment by ghglza** [comment]
Upgrading k8s to v1.15.1 and CRI-O to commit 635c008a did not have any effect on the problems described above.

**Comment by saschagrunert** [comment]
Hm, did you already try to start with a blank CNI config (without the bridge config) and setup weave afterwards?

**Comment by ghglza** [comment]
The CRI-O bridge config in /etc/cni/net.d is installed by the CRI-O RPM, currently cri-o-1.11.13-1.rhaos3.11.gitfb88a9c.el7.x86_64 (from https://cbs.centos.org/repos/paas7-crio-111-candidate/x86_64/os/), in order to get CentOS systemd integration.
We then overwrite the CRI-O binaries and config with versions built from source, and afterwards adapt the bridge subnet CIDR in the bridge spec (i.e. switch from 10.88 to 10.99 as the default subnet is already in use here).
The Weave (or Flannel) CNI plugins add a config once the resp. containers are started after kubeadm initialization.

I'm not quite sure I understand you correctly  -- do you mean we should delete the CRI-O bridge config prior to crio systemd service start / kubeadm init, so that there is no CRI-O bridge configured when the CNI plugin service containers start?

**Comment by ghglza** [comment]
Ok so we started a cluster w/o a CRI-O CNI bridge configured -- this resulted in kubelet error messages

 kubelet[2544]: E0724 15:06:29.459685    2544 pod_workers.go:190] Error syncing pod e9647c08-9ac4-4fdd-8056-4852b57f7658 ("coredns-5c98db65d4-bpw6m_kube-system(e9647c08-9ac4-4fdd-8056-4852b57f7658)"), skipping: failed to "CreatePodSandbox" for "coredns-5c98db65d4-bpw6m_kube-system(e9647c08-9ac4-4fdd-8056-4852b57f7658)" with CreatePodSandboxError: "CreatePodSandbox for pod \"coredns-5c98db65d4-bpw6m_kube-system(e9647c08-9ac4-4fdd-8056-4852b57f7658)\" failed: rpc error: code = Unknown desc = failed to get network status for pod sandbox k8s_coredns-5c98db65d4-bpw6m_kube-system_e9647c08-9ac4-4fdd-8056-4852b57f7658_0(d3df2229acee6e98c1b9e11a4ebcdca3ba8b530ee6cf6b8b745503a00440f10f): Unexpected command output Device \"eth0\" does not exist.\n with error: exit status 1

and all k8s non-static pods (CoreDNS, Helm tiller) hanging in status 'ContainerCreating' (w/ 'kubectl describe..' reporting the same error as the kubelet)

**Comment by ghglza** [comment]
And another observation:
After reinstalling the VMWare-based cluster w/ CRI-O bridge enabled again, on one of the nodes k8s is unable to get non-static pods started: all of them are connected to the bridge interface 10.99.0.0, and if they are deleted, they are also hanging in state ContainerCreating while kubelet reports 

 E0724 16:17:39.179692   13698 pod_workers.go:190] Error syncing pod f4302d3d-3918-4d25-954d-5ed4e7ea9456 ("coredns-5c98db65d4-kggdw_kube-system(f4302d3d-3918-4d25-954d-5ed4e7ea9456)"), skipping: failed to "CreatePodSandbox" for "coredns-5c98db65d4-kggdw_kube-system(f4302d3d-3918-4d25-954d-5ed4e7ea9456)" with CreatePodSandboxError: "CreatePodSandbox for pod \"coredns-5c98db65d4-kggdw_kube-system(f4302d3d-3918-4d25-954d-5ed4e7ea9456)\" failed: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_coredns-5c98db65d4-kggdw_kube-system_f4302d3d-3918-4d25-954d-5ed4e7ea9456_0(a7bdffefc0d9ade135d5f7051ab700db2a2e315673e8df7df10a4cb61de3dd64): failed to allocate for range 0: no IP addresses available in range set: 172.24.1.1-172.24.1.254"

and CRI-O reports

crio[13591]: time="2019-07-24 16:18:23.971633376+02:00" level=error msg="Error deleting network: invalid version \"\": the version is empty"
crio[13591]: time="2019-07-24 16:18:23.971662200+02:00" level=error msg="Error while removing pod from CNI network \"cbr0\": invalid version \"\": the version is empty"

This failure state even survives rebooting the node.
Is it possible that the root cause for all those problems is kernel-related, e.g. that the kernel version delivered with CentOS 7 is too old for running k8s w/ CRI-O as runtime?

**Comment by ghglza** [comment]
Ok forget the last comment -- this turned out to be a case of https://github.com/cri-o/cri-o/issues/2410, caused by us not removing /var/cni/network prior to reinstalling the cluster.

**Comment by ghglza** [comment]
Now upgrading CRI-O to a version containing the latest libpod (i.e. something above commit 53c3b4d) changes the game -- but not in a good direction:
Dynamically created pods are still connected to the CRI-O bridge interface instead to the specified k8s pod subnet.
But recreation of pods by k8s after deletion (i.e. our workaround described above) fails -- kubectl / the kubelet report

Failed create pod sandbox: rpc error: code = Unknown desc = failed to create pod netwo
rk sandbox k8s_coredns-5c98db65d4-pwgbr_kube-system_880a1559-5cb9-4598-934c-784ef73be6ba_0(458f7733698d4089c264bfd7bff33bf9fdbe81d99de85034abbb93bdcbf
4affb): failed to set bridge addr: "cni0" already has an IP address different from 172.24.1.1/24
cni0 (the CRI-O bridge interface) is configured as (content of /etc/cni/net.d/100-crio-bridge.conf)

{
  "cniVersion": "0.3.0",
  "name": "crio-bridge",
  "type": "bridge",
  "bridge": "cni0",
  "isGateway": true,
  "ipMasq": true,
  "ipam": {
    "type": "host-local",
    "subnet": "10.99.0.0/16",
    "routes": [
      {
        "dst": "0.0.0.0/0"
      }
    ]
  }
}

Is it necessary to reference the k8s pod subnet CIDR also in the CRI-O bridge configuration?
Or the other way round, reference the CRI-O subnet in the CNI plugin configuration?

**Comment by saschagrunert** [comment]
Okay, I think to debug any further here we have to try a different approach. Are you able to export the complete VirtualBox applicance (master and node) that I can import it on my local machine? Can you upload them somewhere? :)

**Comment by matthias50** [comment]
So I was having a similar issue with the Calico CNI. I *think* I have resolved this issue by simply removing /etc/cni/net.d/100-crio-bridge.conf and /etc/cni/net.d/200-loopback.conf right after installing the cri-o RPM.

Then, when the Calico CNI gets installed as a daemonset, it writes the correct CNI config to /etc/cni/net.d and things seem to work. Can someone comment on why these files are there in the first place?

**Comment by ghglza** [comment]
Wow, thanks -- that did the trick, at least for the dynamic pods that were bound to the CRI-O bridge subnet!
We had also to remove a CNI configuration 87-podman-bridge.conflist that was installed by the Podman RPM, but with /etc/cni/net.d being empty when kubeadm ran resulted in a working cluster w/o any workarounds under VMWare.
In the case of the VirtualBox VMs w/ 2 network interfaces, the static pods are still reported to be attached to the wrong adapter, but the cluster also works fine.

As e.g. kube-router installs its CNI configuration as 10-kuberouter, could it be that CRI-O evaluates the files under /etc/cni/net.d in the wrong (=reversed) order?
I.e. not lowest number in the file's name as highest, but as lowest priority?

[We are using k8s v1.16.1, kube-router v0.3.2, and CRI-O 1.16.0-dev commit a191d727 meanwhile]

**Comment by YanzheL** [comment]
I solved this by changing the `plugin_dirs` field in `/etc/crio/crio.conf`

before change
```
plugin_dirs = [
        "/usr/libexec/cni",
]
```

after change
```
plugin_dirs = [
        "/usr/libexec/cni",
        "/opt/cni/bin/"
]
```

then reboot

Now the node connected to the correct pod network, which is `10.32.0.0/12` by default in weave-net.

#### Notes

- I tried to restart the crio and kubelet service to avoid reboot, but it seems not working. So I just reboot to get everything clean.

- I suggest deleting the `87-podman-bridge.conflist` and something other than `10-weave.conflist`.

#### System environment
OS: CentOS 7.7
crio version: 1.15.2-1.el7
kubelet/kubeadm version: 1.16.3

**Comment by haircommander** [comment]
There are now two available work arounds for this issue. As such, I'm closing. please reopen if these mitigations don't work for you.
