### ISSUE TITLE
is there a way to detect cgroup driver for crio

### ISSUE THREAD

**Issue by chenzhiwei** [cri-o/cri-o#2414]
**Description**

For Docker, the `docker info` command can output the cgroup driver.

Is there a command can get the cgroup info from crio?

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vrothberg** [comment]
You can inspect the configuration crio has been started with and look for the `cgroup_manager` option. The default path is `/etc/crio/crio.conf`. The default cgroup manager is cgroupfs. But there is no docker-info like command.

**Comment by chenzhiwei** [comment]
I know this method, but it is not a perfect method.

it is a static detect method, it is not runtime detection.

think about this case, users modified this file, but did not restart crio,
so the detection will not accurate.

**Comment by vrothberg** [comment]
That's a good point. CRI-O does not support inspecting that yet, but I have an idea using `crictl info` and adding some optional information to what CRI-O returns. I'll spin up a PR in a bit.

**Comment by vrothberg** [comment]
Feel free to try out https://github.com/cri-o/cri-o/pull/2416. This is not at all carved into stone and I expect the PR to turn into something more generic to return other potentially useful configuration values as well. But it'll do the trick for your use case:
```bash
$ sudo crictl info{
  "status": {
    "conditions": [
      {
        "type": "RuntimeReady",
        "status": true,
        "reason": "",
        "message": ""
      },
      {
        "type": "NetworkReady",
        "status": true,
        "reason": "",
        "message": ""
      },
      {
        "type": "CgroupManager",
        "status": true,
        "reason": "",
        "message": "cgroupfs"
      }
    ]
  }
}
```

**Comment by vrothberg** [comment]
Actually, there's a much simpler solution pointed out by @saschagrunert: https://github.com/cri-o/cri-o/pull/2416#issuecomment-496841562

**Comment by mrunalp** [comment]
See #2403 We are adding /config endpoint that will return the settings.

**Comment by chenzhiwei** [comment]
Thank you guys, the method mentioned here looks good to me: https://github.com/cri-o/cri-o/pull/2416#issuecomment-496841562

```
> sudo curl -s --unix-socket /var/run/crio/crio.sock http://localhost/info | jq
{
  "storage_driver": "btrfs",
  "storage_root": "/var/lib/containers/storage",
  "cgroup_driver": "cgroupfs",
  "default_id_mappings": {
    "uids": [
      {
        "container_id": 0,
        "host_id": 0,
        "size": 4294967295
      }
    ],
    "gids": [
      {
        "container_id": 0,
        "host_id": 0,
        "size": 4294967295
      }
    ]
  }
}
```
