### ISSUE TITLE
Update Unit File Description

### ISSUE THREAD

**Issue by mrguitar** [cri-o/cri-o#2415]
**Description**

<minor nit pick>
The description in the unit file should be updated to reflect the current project name. 

I never noticed this until I had to troubleshoot a system where the daemon failed to start:
[FAILED] Failed to start Open Container Initiative Daemon.
See 'systemctl status crio.service' for details.

"Open Container initiative Daemon", or OCID, was the original name for this project. I'm surprised this is still around as an artifact. 

I propose we change this line to something like:
Description=cri-o
or 
Description=Container Runtime Interface for OCI
or even
Description=Container Runtime Interface for kubernetes

**Output of `crio --version`:**

```
$ crio -version
crio version 1.13.9-1.rhaos4.1.gitd70609a.el8
```

**Comment by saschagrunert** [comment]
Thanks for the report, a fix is incoming.
