### ISSUE TITLE
[1.14.x .. and previous] Kubelet runaway memory/goroutines

### ISSUE THREAD

**Issue by SleepyBrett** [cri-o/cri-o#2445]
**Description**

We run a mixed cluster of CRI-O and Docker nodes for testing and we've been seeing Kubelets go into runaway memory and goroutine usage on crio nodes only.

![image](https://user-images.githubusercontent.com/279521/58884238-d9de0a00-8694-11e9-9748-69a3019b5f33.png)
![image](https://user-images.githubusercontent.com/279521/58884386-288ba400-8695-11e9-8d86-68b2dcaa0624.png)

The increases are correlated with bunches of logs in this form coming off the kubelet in big blocks:
```
E0520 18:13:34.244009    1457 cri_stats_provider.go:576] Unable to fetch container log stats for path /var/log/pods/fomo_product-consumer-int-8d977bc86-vhgt4_5c8f0efe-7959-11e9-bc76-0639d7c4e89e/product-consumer-int: failed command 'du' ($ nice -n 19 du -s -B 1) on path /var/log/pods/fomo_product-consumer-int-8d977bc86-vhgt4_5c8f0efe-7959-11e9-bc76-0639d7c4e89e/product-consumer-int with error exit status 1
```
I see nothing unusual in the cri-o logs at all (default log-level).

We've recently added a memory cap to the kubelet slice (as before the memory would ballon until it oomed the machine causing general havock that seeming could result in the bug that is perhaps fixed in 1.14.2 around crio/system restarts causing problems  with crio state on disk). Even with the memory cap when the kubelet restarts the memory usage often keeps at a rate similar to the rate from the last iteration until it is again killed. 

![image](https://user-images.githubusercontent.com/279521/58885135-840a6180-8696-11e9-81ef-5bea3aea68e2.png)

This may not be 100% a cri-o issue, there may be a bug in the kubelet but I haven't yet dug in much further to see. All I know is that in a mixed env it happens on cri-o nodes. 

I will create a mirror issue against kubernetes.

**Steps to reproduce the issue:**
I have not yet determined steps to reproduce this issue. Only that in my cluster it happens eventually to every crio node.

**Describe the results you received:**
kubelet stacks memory and goroutines until it is killed.

**Describe the results you expected:**
kubelet behaves.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**
I've seen this for awhile in 1.11.x but wanted to confirm it in 1.14.x before creating this issue. Have seen it in 1.14.1 and 1.14.2.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS, coreos

**Comment by SleepyBrett** [comment]
Crossposted to kubernetes/kubernetes:
https://github.com/kubernetes/kubernetes/issues/78694

**Comment by haircommander** [comment]
@SleepyBrett @mariusgrigoriu are you still seeing this?

**Comment by mariusgrigoriu** [comment]
I believe this was related to a cgroups leak. Should be safe to close.

**Comment by haircommander** [comment]
excellent thank you!
