### ISSUE TITLE
Setting manage_network_ns_lifecycle to true by default.

### ISSUE THREAD

**Issue by ganeshmaharaj** [cri-o/cri-o#2464]
**Description**
This issue is used as a tracker of setting `manage_network_ns_lifecycle` to true by default on cri-o. The latest is, there were issues when this was enabled in RHEL-7. With RHEL-8, if testing proves this is no longer an issue this value will be enabled by default.

**Comment by brtknr** [comment]
Is this the reason why kata-nemu works with containerd and not cri-o?

**Comment by ganeshmaharaj** [comment]
@brtknr kata-deploy when used will set this value in the config. The issue that you are noticing is probably https://github.com/cri-o/cri-o/issues/2479

**Comment by haircommander** [comment]
manage_ns_lifecycle is the successor of manage_network_lifecycle, and it's now true by default :slightly_smiling_face:
