### ISSUE TITLE
Enable cri-o on ppc64le arch & make release binaries available 

### ISSUE THREAD

**Issue by nitkon** [cri-o/cri-o#2467]
Hey!

Thanks for the awesome readme/tutorials on cri-o. I could build cri-o from source & use it in a kubeadm 1.14.2 setup to deploy regular & kata pods. I was wondering what it would take to have the crio CI running on ppc64le and have  release binaries as well. FYI we have ppc64le instances in Travis.

**Comment by saschagrunert** [comment]
Hey @nitkon, thanks for opening up the issue. I generally like the idea in extending testing for different target platforms. Travis is a bit slow these days so we thought about switching to CircleCI. Do you think a cross-compilation toolchain would work here too?

References #2468

**Comment by nitkon** [comment]
Hi @saschagrunert, CircleCI does not have Power ppc64le nodes. However we can have a remote Jenkins ppc64le VM slave instance connected to the current Jenkins infra.

**Comment by haircommander** [comment]
Further, if we really couldn't avoid travis, having only the ppc64le tests there and migrating everything else to circle would probably still be faster

**Comment by nitkon** [comment]
@haircommander: So IIUC, cri-o is planning to move away from Jenkins soon and thus we have only Circle CI and Travis as options left. And since ppc64le instances are not available in Circle CI and Travis CI is slow, thus we can run a part of the tests(ppc64le) on Travis and rest on Circle CI.

**Comment by saschagrunert** [comment]
> @haircommander: So IIUC, cri-o is planning to move away from Jenkins soon and thus we have only Circle CI and Travis as options left.

The only proposal from my side was to keep the current infrastructure and replace travis with CircleCI. It's easy, you currently can enable CircleCI for your fork and use it. Within that repository, we only use it for the master branch right now.

Which tests do you want to run on PPC? I would asume:

- integration
- critest
- unit-tests

So I guess a jenkins runner executed by prow would be a good fit here, right?

**Comment by haircommander** [comment]
oh jeez I really should fully wake up before responding to emails...
sgtm we could use prow for it
