### ISSUE TITLE
Add a request ID log field

### ISSUE THREAD

**Issue by jpeach** [cri-o/cri-o#2555]
In general, the CRI-O server accepts GRPC requests, does some work and then responds, and there may be multiple RPC requests in flight at once.

When debugging pod creation behavior, it is tricky to associate debug messages with the correct pod creation request, particularly if there is more than one in flight. Adding a unique request ID to each structured log message would help log analysis a lot. It would also make it reasonably straight-forward to write tools that summarize CRI-O logs.

**Comment by vrothberg** [comment]
Thanks for opening the issue, @jpeach! The proposal sounds like a valuable extension to me. Would you be interested in contributing?

Certainly, we can't log everything but logging the hot code paths would be great. There are also some limits to what we can do as some logs come from the libraries CRI-O uses.

**Comment by saschagrunert** [comment]
@jpeach can we close this now, since we now have the request ID?

**Comment by jpeach** [comment]
> On Jul 22, 2019, at 8:46 PM, Sascha Grunert <notifications@github.com> wrote:
> 
> @jpeach can we close this now, since we now have the request ID?
> 
Yes, I think the request ID PR addresses this

**Comment by saschagrunert** [comment]
Closing :)
