### ISSUE TITLE
Make image volumes writeable by the container user

### ISSUE THREAD

**Issue by jpeach** [cri-o/cri-o#2562]
In `server/container_create.go:addImageVolumes()`, the `config.ImageVolumesMkdir` volume is create with mode `0755` and UID `0`. Unless the container process also runs as UID `0`, it won't be able to write to the volume. Maybe the ownership or permissions should be adjusted to ensure that image volumes are always writeable from inside the container.

**Comment by rhatdan** [comment]
@samc24 PTAL
