### ISSUE TITLE
Hard to cross-compile cri-o, due to config generation

### ISSUE THREAD

**Issue by afbjorklund** [cri-o/cri-o#2575]
**Description**

It is hard to build cri-o for another target (e.g. Buildroot), due to running tools on host.

This may fail for any number of reasons, including architecture and shared libraries.

**Steps to reproduce the issue:**
1. make minikube.iso
2.
3.

**Describe the results you received:**

`bin/crio-config: error while loading shared libraries: libdevmapper.so.1.02: cannot open shared object file: No such file or directory`

`./bin/crio: error while loading shared libraries: libdevmapper.so.1.02: cannot open shared object file: No such file or directory`

**Describe the results you expected:**

conmon/config.h

crio.conf

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens every time, even if I provide my own configuration files.

Probably due to the usage of `git-vars` target, invalidating everything ?

**Output of `crio --version`:**

```
crio version 1.15.0
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Buildroot 2018.05.3

**Comment by saschagrunert** [comment]
Hey @afbjorklund :wave:, if I understand the issue correctly, then the `crio` binary builds correctly but it is not executable because the shared library for device mapper is not found? If so, then you may have to adapt the `LD_LIBRARY_PATH` in your build environment or exclude the device mapper support during build.

The `git-vars` target should be related to this issue in my point of view.

**Comment by saschagrunert** [comment]
I opened-up a PR which should enhance the `git-vars` target to cover non-existing `git` executables as well: https://github.com/cri-o/cri-o/pull/2581

Can you verify that it works with that patch? If so, we can backport it to `release-1.15` as well.

**Comment by afbjorklund** [comment]
The library does exist in the _target_ environment, it just does not exist in the _build_ environment.

It seems like I also need to do this make as root user, or it will generate crio.conf for rootless ?

**Comment by afbjorklund** [comment]
My problem is not really `git-vars`, even though I don't really need that phony target (provide vars)

The problem is that _because_ of git-vars, it tries to generate the configuration using a target binary.

``` console
$ LANG=C make -dr conmon/config.h
```

Describe the results you received:
```
Considering target file 'conmon/config.h'.
  Considering target file 'git-vars'.
   File 'git-vars' does not exist.
   Finished prerequisites of target file 'git-vars'.
  Must remake target 'git-vars'.
  Successfully remade target file 'git-vars'.
  Considering target file 'cmd/crio-config/config.go'.
   Looking for an implicit rule for 'cmd/crio-config/config.go'.
   No implicit rule found for 'cmd/crio-config/config.go'.
   Finished prerequisites of target file 'cmd/crio-config/config.go'.
  No need to remake target 'cmd/crio-config/config.go'.
  Considering target file 'oci/oci.go'.
   Looking for an implicit rule for 'oci/oci.go'.
   No implicit rule found for 'oci/oci.go'.
   Finished prerequisites of target file 'oci/oci.go'.
  No need to remake target 'oci/oci.go'.
 Finished prerequisites of target file 'conmon/config.h'.
 Prerequisite 'git-vars' of target 'conmon/config.h' does not exist.
 Prerequisite 'cmd/crio-config/config.go' is older than target 'conmon/config.h'.
 Prerequisite 'oci/oci.go' is older than target 'conmon/config.h'.
Must remake target 'conmon/config.h'.
```

Describe the results you expected:
```
Considering target file 'conmon/config.h'.
  Considering target file 'cmd/crio-config/config.go'.
   Looking for an implicit rule for 'cmd/crio-config/config.go'.
   No implicit rule found for 'cmd/crio-config/config.go'.
   Finished prerequisites of target file 'cmd/crio-config/config.go'.
  No need to remake target 'cmd/crio-config/config.go'.
  Considering target file 'oci/oci.go'.
   Looking for an implicit rule for 'oci/oci.go'.
   No implicit rule found for 'oci/oci.go'.
   Finished prerequisites of target file 'oci/oci.go'.
  No need to remake target 'oci/oci.go'.
 Finished prerequisites of target file 'conmon/config.h'.
 Prerequisite 'cmd/crio-config/config.go' is older than target 'conmon/config.h'.
 Prerequisite 'oci/oci.go' is older than target 'conmon/config.h'.
No need to remake target 'conmon/config.h'.
make: 'conmon/config.h' is up to date.
```

This wouldn't be so horrible, if it wasn't for the fact that running crio-config or crio doesn't work.

---

My workaround is to build crio-config with simpler flags, and to avoid building crio.conf at all...

`make BUILDTAGS="containers_image_ostree_stub exclude_graphdriver_btrfs exclude_graphdriver_devicemapper containers_image_openpgp" conmon/config.h`

`make binaries # avoid crio.conf`

This way I avoid trying to running the target (Buildroot) binaries on the host platform (Ubuntu).

https://landley.net/writing/docs/cross-compiling.html

For a **real** cross, things would have been even worse ?

**Comment by saschagrunert** [comment]
That the `git-vars` target forces a rebuild should be fixed with #2583. But in the end we want to move away from the conmon implementation within this repo and switch to [containers/conmon](https://github.com/containers/conmon), where the problem should not exist because of a different Make target structure.

I'm unsure if we have open issues regarding cross-compilation after these changes.

**Comment by afbjorklund** [comment]
It should be OK, with those git-vars changes.

Already building containers/conmon for podman, so that should be fine.

**Comment by saschagrunert** [comment]
Okay cool thanks for all the Input. Feel free to close this if there are no further changes needed. :)
