### ISSUE TITLE
Configuration migration support

### ISSUE THREAD

**Issue by saschagrunert** [cri-o/cri-o#2579]
I'm thinking about providing a better configuration migration to end-users via something like:

```
> crio config migrate /etc/crio/crio.conf --from v1.14.0 --to v1.15.0
```

This way we would have to keep track of changing configuration from a source code and documentation perspective. We could also implement some sort of automatism in correlation to `crio-wipe`.

WDYT?

**Comment by rhatdan** [comment]
crio config migrate /etc/crio/crio.conf --from v1.14.0 --to v1.15.0

1  No need for parameter /etc/crio/crio.conf, this is default and can be overridden with --config.
2 I don't think we need --to v1.15.0, this should default to current version.  Do you think we would need to migrate to different older versions?
3 --from v1.14.0, should be optional, since this is what is assumed  (Current version -1)

**Comment by rhatdan** [comment]
@haircommander @umohnani8 @vrothberg @mrunalp WDYT?

**Comment by vrothberg** [comment]
> This way we would have to keep track of changing configuration from a source code and documentation perspective.

In theory, we should already be doing that :^)

> crio config migrate /etc/crio/crio.conf --from v1.14.0 --to v1.15.0

What is the problem we're trying to solve and who's the target audience? Would it fill potentially new options? Would it fill the default values for missing ones?

**Comment by saschagrunert** [comment]
> What is the problem we're trying to solve and who's the target audience?

I think the target audience are mostly administrators and package maintainers. The idea is inspired by migration tools provided by large web frameworks to migrate the application from one version to another (like [Angular](https://update.angular.io/)). I mean the technical implementation is not trivial since we would have to versionize the structures somehow to be able to do a conversion. But in the end we could provide the user a CLI tool which provides information like:

```
> Migrating CRI-O config from 1.14 to 1.15
> Renaming 'plugin_dir' to 'plugin_dirs'
...
```

> Would it fill potentially new options?

Yeah, the new config should be fully functional :) We could either ask the user interactively or inform about a new default value has been added.

> Would it fill the default values for missing ones?

Yes it should I guess.

**Comment by vrothberg** [comment]
>  I mean the technical implementation is not trivial since we would have to versionize the structures somehow to be able to do a conversion.

Ideally, no change should break backwards compat in the config and this is something we should follow dogmatically. Adding a complex config management system on top of CRI-O seems way too much for my taste. It must be implemented, tested, documented, reviewed, maintained, etc., and all for something that should not happen in the first place (i.e., backwards incompats in the config).

**Comment by saschagrunert** [comment]
> > I mean the technical implementation is not trivial since we would have to versionize the structures somehow to be able to do a conversion.
> 
> Ideally, no change should break backwards compat in the config and this is something we should follow dogmatically.

Deprecations where admins have to take action will always happen, I don't think that we can avoid this.

> Adding a complex config management system on top of CRI-O seems way too much for my taste. It must be implemented, tested, documented, reviewed, maintained, etc., and all for something that should not happen in the first place (i.e., backwards incompats in the config).

It does not necessary have to be really complex, It would be more or less only versionizing the config structures and diffing them by logic. But yeah, I see the point that it might be too much overhead.

**Comment by saschagrunert** [comment]
I think I  will close this for now, might not be the right time for such a feature. :)
