### ISSUE TITLE
container_network_receive_bytes_total metric support

### ISSUE THREAD

**Issue by chrono2002** [cri-o/cri-o#2619]
When migrated from docker to cri-o containers container_network_* metrics suddenly stopped working in Prometheus. Could it be because they haven't implemented yet?

**Comment by mrunalp** [comment]
Can you give more details on what version of kubernetes and CRI-O are you using?

**Comment by chrono2002** [comment]
kubernetes version: "1.15.0-00"
crio version: v1.14.5
runc version: v1.0.0-rc8

**Comment by chrono2002** [comment]
> Can you give more details on what version of kubernetes and CRI-O are you using?

kubernetes version: "1.15.0-00"
crio version: v1.14.5
runc version: v1.0.0-rc8

**Comment by chrono2002** [comment]
hi,
any news with this?

**Comment by chrono2002** [comment]
I have investigated metrics by querying kubelet:

```
curl -k -H "Authorization: Bearer $TOKEN" https://127.0.0.1:10250/metrics/cadvisor

container_network_receive_bytes_total{container="",container_name="",id="/",image="",interface="cali57a1a2e85e8",name="",namespace="",pod="",pod_name=""} 1.21697883984e+11 1564576348800
container_network_receive_bytes_total{container="",container_name="",id="/",image="",interface="cali847e933c8ca",name="",namespace="",pod="",pod_name=""} 1.10633940638e+11 1564576348800
```

and found out that there is no container_name associated with container interface, but why?

**Comment by chrono2002** [comment]
looks like it's not related to cri-o, fixed by this:
https://github.com/kubernetes/kubernetes/issues/79406

**Comment by haircommander** [comment]
closing because of the comment above

**Comment by yichengliu58** [comment]
Hi @chrono2002 

I just met the similar issue here, I migrated from docker to cri-o, and found that a lot of metrics have lost label values:
```
container_network_receive_packets_total{container="",id="/",image="",interface="0f148413c098_h",name="",namespace="",pod=""} 3 1593591826235
container_network_receive_packets_total{container="",id="/",image="",interface="1c11c69e68a7_h",name="",namespace="",pod=""} 56431 1593591826235
container_network_receive_packets_total{container="",id="/",image="",interface="2c71ab18a27c_h",name="",namespace="",pod=""} 165 1593591826235
container_network_receive_packets_total{container="",id="/",image="",interface="2df2fe3b3a6d_h",name="",namespace="",pod=""} 11 1593591826235
container_network_receive_packets_total{container="",id="/",image="",interface="38aa7db95f4c_h",name="",namespace="",pod=""} 1.0091228e+07 1593591826235
container_network_receive_packets_total{container="",id="/",image="",interface="42292d706e9c_h",name="",namespace="",pod=""} 25137 1593591826235
container_network_receive_packets_total{container="",id="/",image="",interface="5af7fd36dc67_h",name="",namespace="",pod=""} 222513 1593591826235
```

It didn't help to restart kubelet or cri-o

I have set the cri-o sockt path to default which results in cri-o using cadvisor to get metrics. I'm not if there are some other configuration issues ?

**Comment by haircommander** [comment]
what version of kube and cri-o?

**Comment by yichengliu58** [comment]
kubernetes: 1.17.6
cri-o: 1.18.2

It appears that some metrics have label values all set, some metrics only have several label values (not all set), and some metrics don't have any label values at all. 

I configured both `runc` and `kata` runtime to cri-o, and started pods using both of them. But both `runc` and `kata` pods have some metrics with labels missed.

I still haven't found any configuration related to this issue, any ideas on this ? @haircommander

**Comment by haircommander** [comment]
what's the path of your `crio.sock`
