### ISSUE TITLE
integration tests flakes

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#2665]
**Description**
When running the bats integration test suite, we often fail a test where `/tmp/tmp.*/crio/overlay` is busy when attempting to remove the temp directory. As a temporary fix, we can remove the directory best effort as in here: https://github.com/cri-o/cri-o/pull/2582, but that is not a permanent solution. 

**Steps to reproduce the issue:**
1. run `sudo bats test/*.bats`on master or release-1.15
2. note tests that fail with `rm: cannot remove '/tmp/tmp.*/crio/overlay': Device or resource busy`

**Comment by saschagrunert** [comment]
Just a pointer, the current workaround to be fixed can be found here: https://github.com/cri-o/cri-o/pull/2667#discussion_r312976058

**Comment by haircommander** [comment]
also a pointer: https://github.com/cri-o/cri-o/pull/2667#discussion_r313051037 because I don't want to forget

**Comment by haircommander** [comment]
`# time="2019-08-13T14:30:22Z" level=fatal msg="run pod sandbox failed: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_podsandbox1_redhat.test.crio_redhat-test-crio_1(e9f14f3892bcc8ae06001759eb29b6d415b225d661d4838b08b64fb9d874d5b9): failed to set bridge addr: could not add IP address to \"cni0\": file exists"`
should be an easy one to fix and happens every so often

**Comment by saschagrunert** [comment]
> `# time="2019-08-13T14:30:22Z" level=fatal msg="run pod sandbox failed: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_podsandbox1_redhat.test.crio_redhat-test-crio_1(e9f14f3892bcc8ae06001759eb29b6d415b225d661d4838b08b64fb9d874d5b9): failed to set bridge addr: could not add IP address to \"cni0\": file exists"`
> should be an easy one to fix and happens every so often

Do you see a way to reproduce this? The log message comes directly from the bridge plugin, so a locking might be needed more there instead of within CRI-O... :thinking:

**Comment by haircommander** [comment]
maybe, but I was thinking the problem is there are multiple crio's running at once, using the same interface (because of parallel bats). If we used cni$RAND instead of every one using cni0 that should alleviate it.

**Comment by haircommander** [comment]
PR to test here https://github.com/cri-o/cri-o/pull/2722

**Comment by haircommander** [comment]
well our integration tests *are* still flaky, but for new and exciting reasons, not because of these. closing as such
