### ISSUE TITLE
Create a default hooks.d directory with release packages

### ISSUE THREAD

**Issue by lrgar** [cri-o/cri-o#2683]
Hello CRI-O team,

When [installing CRI-O by using the Project Atomic PPA]( https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cri-o), the default `crio.conf` file doesn’t have any directories for hooks configured.

```
$ grep -A 1 hooks_dir /etc/crio/crio.conf
hooks_dir = [
]
 ```

The implicit (and deprecated) directories aren't used since `hooks_dir` is set. But then no hooks directories are being looked at.

We try to add a hook if possible when installing our product. But in this case, the customer then needs to create the directory, update `crio.conf` and then restart CRI-O, so that we have place where to put the hook to and have it recognized.

Would it be possible to have a directory configured by default with the official packages so that users can avoid having to do these steps manually?

Best regards,
Luis

**Comment by mrunalp** [comment]
@lsm5 ptal

**Comment by haircommander** [comment]
@lrgar we now use OBS to ship to ubuntu. I believe this is fixed there. As such, I am closing. please reopen if you disagree
