### ISSUE TITLE
Maybe add python-client to the integration tests?

### ISSUE THREAD

**Issue by sebastian-philipp** [cri-o/cri-o#2685]
**Description**

Python's [`list_nodes` was broken](https://github.com/kubernetes-client/python/issues/895) in 1.14.2 

Would it make sense to add some kind of test to make sure, future cri-o versions don't break client libraries?

**Steps to reproduce the issue:**
1. downgrade to 1.14.2
2. call `list_nodes()` in the python client

**Comment by mrunalp** [comment]
If there is some suite we can run from that repo, we can enable it in CI.

**Comment by haircommander** [comment]
is this issue resolved @sebastian-philipp ?

**Comment by sebastian-philipp** [comment]
sorry. never looked again into this.

**Comment by haircommander** [comment]
I don't think the cri-o devs have the cycles to add a set of tests for every kube client out there. If anyone in the community wants to take this on, please do. Otherwise, I will close
