### ISSUE TITLE
Broken builds for 1.15 in ppa

### ISSUE THREAD

**Issue by stamm** [cri-o/cri-o#2692]
https://launchpad.net/~projectatomic/+archive/ubuntu/ppa/+build/17331455

```
# github.com/cri-o/cri-o/oci
src/github.com/cri-o/cri-o/oci/runtime_vm.go:175:20: undefined: strings.ReplaceAll
```
https://github.com/cri-o/cri-o/blob/v1.15.0/oci/runtime_vm.go#L175

But as I can see, it have been fixed in master

**Comment by saschagrunert** [comment]
Hey @stamm, :wave: thanks for hinting to the issue. I've backported the fix to the 1.15 release branch. The issue should be fixed with the 1.15.1 release.
