### ISSUE TITLE
cri-o 1.1.5 failed build latest PPA

### ISSUE THREAD

**Issue by Slach** [cri-o/cri-o#2695]
https://launchpadlibrarian.net/434901960/buildlog_ubuntu-bionic-amd64.cri-o-1.15_1.15.1-1~dev~ubuntu18.04~ppa1_BUILDING.txt.gz
latest build failed with error
```
go: disabling cache (/sbuild-nonexistent/.cache/go-build) due to initialization failure: mkdir /sbuild-nonexistent: permission denied
# github.com/cri-o/cri-o/oci
src/github.com/cri-o/cri-o/oci/runtime_vm.go:175:20: undefined: strings.ReplaceAll
Makefile:119: recipe for target 'bin/crio' failed
make[2]: *** [bin/crio] Error 2
```
dear @lsm5 could you try rebuild ?

**Comment by haircommander** [comment]
This should have been fixed https://github.com/cri-o/cri-o/pull/2693, and i think the PPA is autobuilding, so you may have more luck today?

**Comment by haircommander** [comment]
I'll leave it open and wait for @lsm5 to confirm

**Comment by haircommander** [comment]
@Slach are you still seeing this?

**Comment by Slach** [comment]
yes
https://launchpad.net/~projectatomic/+archive/ubuntu/ppa/+packages
packages doesn't build since 2019-07-28

**Comment by haircommander** [comment]
I pinged @lsm5  to look at it, sorry for the delay!

**Comment by storpipfugl** [comment]
Hi,

There's no cri-o-1.15 package available for ubuntu 18.04 in the PPA:
$ curl -s http://ppa.launchpad.net/projectatomic/ppa/ubuntu/dists/bionic/main/binary-amd64/Packages.gz | gunzip | grep "Package: cri-o-1"
Package: cri-o-1.12
Package: cri-o-1.13
Package: cri-o-1.14

Is this due to this problem or should I open a separate issue?

**Comment by haircommander** [comment]
@Slach sorry for the delay, ubuntu 1.15 PPA should be auto-updated in the next hour or so with a fix :)

**Comment by lsm5** [comment]
@Slach please try using the latest cri-o-1.15 from ppa

**Comment by Slach** [comment]
cri-o-1.15 installed OK, thanks a lot
