### ISSUE TITLE
Set umask in container

### ISSUE THREAD

**Issue by liqlin2015** [cri-o/cri-o#2701]
**Description**

Similar to docker issue https://github.com/moby/moby/issues/19189. Is there anyway to set umask for cri-o container?

**Describe the results you expected:**
Container can choose to have their own umask setting instead of default 0022.

**Additional environment details (AWS, VirtualBox, physical, etc.): OCP 3.11

**Comment by rhatdan** [comment]
I don't think this is a bad idea, but it is not part of the OCI spec and runc does not support it.  In order to get this to work, you would need to work it's way through that tooling.

@giuseppe @nalind @vbatts WDYT?

**Comment by giuseppe** [comment]
change it globally for all containers seems like a bad idea.

Nothing prevents programs to change it separately, you could even have it change as part of an ENTRYPOINT.

**Comment by rhatdan** [comment]
It seems like a reasonable ask, though, podman run --umask ...

But this fell on deaf ears in Docker and eventually under OCI.

**Comment by giuseppe** [comment]
It is even more difficult for CRI-O containers as the change should go through Kubernetes as well.

It seems there is already an open request for runc: https://github.com/opencontainers/runc/issues/1650 and a change to the OCI runtime specs: https://github.com/opencontainers/runtime-spec/pull/941

**Comment by cyphar** [comment]
> But this fell on deaf ears in Docker and eventually under OCI.

I opened PRs, they just weren't merged. The runc change would be very minimal, we just need the spec change first.

**Comment by cyphar** [comment]
> But this fell on deaf ears in Docker and eventually under OCI.

I opened PRs (as @giuseppe mentioned), they just weren't merged. The runc change would be very minimal, we just need the spec change first. I didn't realise this was a high-priority issue -- I assumed it was just a "nice-to-have" and so spent my time on other things rather than chasing it up.

**Comment by rhatdan** [comment]
I would not say it is a high priority. we just got this request and I would think podman could support it also, and it seemed to make sense to me.

**Comment by haircommander** [comment]
the umask runtime-spec PR was merged. Now we just need runtime maintainers to add it. @giuseppe does crun support setting umask?

**Comment by giuseppe** [comment]
Yes, crun supports it

**Comment by haircommander** [comment]
we *could* change the default umask sent to all containers via CLI flag, or we could use annotations (similar to how seccomp does it). though, the most idiomatic change would involve upstream kube changes

**Comment by haircommander** [comment]
we also could use allowed_annotations and a specific cri-o annotation to set the umask

**Comment by sdavids** [comment]
Should be fixed

**Comment by haircommander** [comment]
we have not fixed this AFAIU

**Comment by sdavids** [comment]
Make the bot happy …

**Comment by sdavids** [comment]
Bot needs to be cuddled.

**Comment by sdavids** [comment]
Revive
