### ISSUE TITLE
crio-wipe fails if /var/lib/containers is a mountpoint

### ISSUE THREAD

**Issue by paradon** [cri-o/cri-o#2725]
**Description**

crio-wipe attempts to "rm -rf /var/lib/containers", however if that path is a mountpoint it fails with "Device or resource busy".

**Steps to reproduce the issue:**
1. Mount a filesystem at /var/lib/containers
2. Cause crio-wipe to attempt an update (e.g. remove /var/lib/crio/version)

**Describe the results you received:**
crio-wipe errors with "Device or resource busy", and blocks crio startup due to systemd unit dependency.

**Describe the results you expected:**
crio-wipe should handle this situation, probably by removing the contents instead of the entire directory.

**Output of `crio --version`:**

```
crio version 1.15.1-dev
commit: "68070024cf96caaf252fa9b87265f8f20664bb06"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Archlinux VM.

**Comment by haircommander** [comment]
@paradon thanks for opening the issue. I didn't even think of that! I have a fix here: https://github.com/cri-o/cri-o/pull/2726 which once approved, I will cherry-pick to 1.15 for you
