### ISSUE TITLE
CRIO install fails on Ubuntu due to files in wrong location.

### ISSUE THREAD

**Issue by abhijitherekar** [cri-o/cri-o#2736]
**Description**

**Steps to reproduce the issue:**
1.apt-get install cri-o-1.15
2.systemctl start crio

**Describe the results you received:**
 systemctl status crio-wipe.service 
● crio-wipe.service - CRI-O Auto Update Script
   Loaded: loaded (/usr/lib/systemd/system/crio-wipe.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2019-08-16 22:28:54 UTC; 11min ago
  Process: 10314 ExecStart=/bin/bash /usr/bin/libexec/crio/crio-wipe/crio-wipe.bash (code=exited, status=127)
 Main PID: 10314 (code=exited, status=127)
Aug 16 22:28:54 abhi-sandbox-crio systemd[1]: Starting CRI-O Auto Update Script...
Aug 16 22:28:54 abhi-sandbox-crio bash[10314]: /bin/bash: /usr/bin/libexec/crio/crio-wipe/crio-wipe.bash: No such file or directory
Aug 16 22:28:54 abhi-sandbox-crio systemd[1]: crio-wipe.service: Main process exited, code=exited, status=127/n/a
Aug 16 22:28:54 abhi-sandbox-crio systemd[1]: Failed to start CRI-O Auto Update Script.
Aug 16 22:28:54 abhi-sandbox-crio systemd[1]: crio-wipe.service: Unit entered failed state.
Aug 16 22:28:54 abhi-sandbox-crio systemd[1]: crio-wipe.service: Failed with result 'exit-code'.

**Describe the results you expected:**
The crio to start.

**Additional information you deem important (e.g. issue happens only occasionally):**
Found a work around with the help @haircommander to change the location of the crio-wipe.bash. 
1. mkdir -p /usr/bin/libexec/crio/crio-wipe/
2. cp /usr/libexec/crio/crio-wipe/* /usr/bin/libexec/crio/crio-wipe/.
**Output of `crio --version`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by lsm5** [comment]
that has been fixed in source, but launchpad doesn't seem to be really building anything. I'll resubmit builds in a while.

**Comment by lsm5** [comment]
should be fixed now. Check it out..

**Comment by haircommander** [comment]
@abhijitherekar can this be closed now?

**Comment by haircommander** [comment]
closing this, as it should be fixed

**Comment by jayaddison** [comment]
This issue re-occurred under package `cri-o-1.17:1.17.4~1` on Ubuntu 20.04 following a non-graceful machine reboot.

The following steps enabled recovery:

1. Temporarily removed `After=crio-wipe.service` and `Requires=crio-wipe.service` from `/usr/lib/systemd/system/crio.service` (i.e. removed `crio-wipe` dependency from `crio` service)
2. Restarted `crio` service (`systemctl restart crio.service`)
3. Restore `crio-wipe` dependency

**Comment by haircommander** [comment]
@jayaddison I

**Comment by haircommander** [comment]
oops, clicked too soon.
@jayaddison what was the failing output from crio-wipe that caused this?

**Comment by haircommander** [comment]
I think it may be a separate issue, as the problem that caused this issue should have been fixed

**Comment by jayaddison** [comment]
@haircommander Thanks for taking a look - the log line `/bin/bash: /usr/bin/libexec/crio/crio-wipe/crio-wipe.bash: No such file or directory` was showing up in `journalctl` output, and that's what led me here; here's an example snippet from the syslog:

```
Jun 16 10:33:35 kubehost systemd[1]: crio-wipe.service: Main process exited, code=exited, status=127/n/a
Jun 16 10:33:35 kubehost systemd[1]: crio-wipe.service: Failed with result 'exit-code'.
Jun 16 10:33:35 kubehost systemd[1]: Failed to start CRI-O Auto Update Script.
Jun 16 10:33:35 kubehost systemd[1]: Dependency failed for Container Runtime Interface for OCI (CRI-O).
Jun 16 10:33:35 kubehost systemd[1]: crio.service: Job crio.service/start failed with result 'dependency'.
```
