### ISSUE TITLE
Network plugin returns error: Missing CNI default network

### ISSUE THREAD

**Issue by k-tipp** [cri-o/cri-o#2741]
**Description**

kubelet doesn't start up properly and the calico cni could not startup. Maybe related to #2739

**Steps to reproduce the issue:**
1. Install kubernetes v. 1.15.3 following the [kubernetes guide](https://kubernetes.io/docs/setup/production-environment/) 
2. Follow the [cri-o kubeadm-guide](https://github.com/cri-o/cri-o/blob/master/tutorials/kubeadm.md)
3. set crio.network.network_dir to `/etc/cni/crio/net.d/`

**Describe the results you received:**
Calico containers didn't start up, kube-system containers showed various error in logs.

kubelet writes a whole lot of these lines into syslog

`Aug 21 08:06:22 [$IP] kubelet[1942]: E0821 08:06:22.143972    1942 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: Missing CNI default network`

**Describe the results you expected:**
Kubernetes spins up properly

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**
```
crio version 1.15.2-dev
```
OS: Ubuntu 18.04.3 LTS
Calico: v. 3.8.2

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Single host deployment on a VMware virtual machine.

**Workaround**
Not changing crio.network.network_dir to `/etc/cni/crio/net.d/` and keep the default location  `/etc/cni/net.d/` solved the problem

**Comment by haircommander** [comment]
yeah this is the same issue as #2739 :) closing as such!
