### ISSUE TITLE
Suggestion: Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [cri-o/cri-o#2744]
Hi, I'm Yevgeny Pats Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- [go-fuzz](https://github.com/dvyukov/go-fuzz) fuzzers (This is generic step not-connected to fuzzit)
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [fuzzitdev/example-go](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [prometheus/prometheus](https://github.com/prometheus/prometheus), [coredns/coredns](https://github.com/coredns/coredns), [google/syzkaller](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Cheers,
Yevgeny

**Comment by saschagrunert** [comment]
Hey @yevgenypats, I already did some experiments with fuzzing the gRPC API of CRI-O so I generally like the idea. The main reason I stopped with the topic is that the corpus generation for gRPC based protocols seems not trivial, do you have any experiences with that?

**Comment by yevgenypats** [comment]
Hi @saschagrunert, do you have maybe a link to an old commit so I can take a look? essentially I'm not sure you want to fuzz the gRPC protocol/library but essentially you want to fuzz some of your internal functions that really do the heavy lifting/parsing. But I need to see the specific function or use-case you had mind.

**Comment by saschagrunert** [comment]
> Hi @saschagrunert, do you have maybe a link to an old commit so I can take a look? 

Unfortunately the code does not exist any more. I basically setup a new CRI-O instance and ran go-fuzz against it. I started with a corpus generated by [critest](https://github.com/kubernetes-sigs/cri-tools) but gave up after a while because I did not achieve an appropriate fuzzing speed. 

> essentially I'm not sure you want to fuzz the gRPC protocol/library but essentially you want to fuzz some of your internal functions that really do the heavy lifting/parsing. But I need to see the specific function or use-case you had mind.

I agree, unfortunately CRI-O does no computing intense parsing or raw data that I see that fuzzing would bring us any further. I think the lower level libraries like containers/{image,storage} could benefit more from that testing approach, but I'm interested what the other maintainers think about this topic.

**Comment by rhatdan** [comment]
I agree that I think fuzzing the low level libraries would be helpful, but I would get the maintainers opions
@nalind @mtrmac @vrothberg WDYT?

**Comment by vrothberg** [comment]
I don't have experience in fuzzing but I guess the problem regarding raw-data processing applies to c/image and c/storage as well. But I am supportive if that's possible.

Thanks a lot for reaching out, @yevgenypats!

**Comment by haircommander** [comment]
@yevgenypats do you still have plans to work on this?

**Comment by yevgenypats** [comment]
@haircommander Hi! Fuzzit is now part of GitLab so it won't be available in the near future outside GitLab. So I don't think it makes sense to work on this now.
