### ISSUE TITLE
Add documentation regarding crio restart expectations

### ISSUE THREAD

**Issue by sboeuf** [cri-o/cri-o#2745]
The CRI-O daemon can be restarted while containers are running, this should have no impact on the container lifecycle. This assumption is true when CRI-O relies on systemd to manage the cgroups. But when CRI-O is configured to be used with cgroupfs, when the daemon terminates, all other processes are terminated too (which means the containers are stopped). This is due to some technical details on how cgroups are managed between systemd and cgroupfs.
CRI-O should have some documentation reporting those behaviors as users might not be aware about this subtle difference.

**Comment by dbgoytia** [comment]
Hi! Is this issue still open? I'd like to contribute to the repo and in the way I believe that I'd learn a lot from documenting this :)

**Comment by saschagrunert** [comment]
> Hi! Is this issue still open? I'd like to contribute to the repo and in the way I believe that I'd learn a lot from documenting this :)

This sounds wonderful, feel free to take this issue if you want to. :slightly_smiling_face:

**Comment by haircommander** [comment]
thanks @dbgoytia feel free to reach out with any questions!

**Comment by dbgoytia** [comment]
Thanks a lot @saschagrunert , @haircommander. If you guys have some links, or important pieces of code that I should take a look at as well it would be awesome so documentation can be rich
