### ISSUE TITLE
Fatal error when starting crio package in Ubuntu 16.04

### ISSUE THREAD

**Issue by alijahnas** [cri-o/cri-o#2774]
**Description**
Error: opening seccomp profile (/etc/crio/seccomp.json) failed: open /etc/crio/seccomp.json: no such file or directory

When installing cri-o via latest ppa package (done via kubespray), crio service doesn't start and throws the above error.

**crio-o package:**

```
cri-o-1.15/xenial,now 1.15.2-1~dev~ubuntu16.04~ppa5 amd64 [installed]
```

I thought the seccomp file should be included with the package because it is mandatory for the service to start?

/packaging
/ubuntu
/kind bug

**Comment by rhatdan** [comment]
@lsm5 PTAL

**Comment by haircommander** [comment]
1.15.x is out of support now, and we've changed where we package from. as such, I believe this issue is stale, and I'm closing as such. Please reopen if you disagree
