### ISSUE TITLE
crio-wipe.service error with crio-1.15 on CentOs 7

### ISSUE THREAD

**Issue by alijahnas** [cri-o/cri-o#2779]
**Description**
crio-wipe.service doesn't start using https://cbs.centos.org/repos/paas7-crio-115-candidate/x86_64/os on CentOS 7.
Package: `cri-o-1.15.1-1.el7.x86_64.rpm`

The unit to start the crio-wipe service references crio-wipe.bash:

```
ExecStart=/bin/bash /usr/local/libexec/crio/crio-wipe/crio-wipe.bash
```

but the file is found in `/usr/libexec/crio/crio-wipe/crio-wipe.bash`

Even if I rewrite the crio-wipe.service file to point to the right service, crio service doesn't start because it doesn't find /etc/crio/seccomp.json which I also got on Ubuntu: #2774

/kind bug

**Comment by haircommander** [comment]
PTAL @lsm5

**Comment by lsm5** [comment]
fixed at https://cbs.centos.org/koji/taskinfo?taskID=945926

**Comment by alijahnas** [comment]
Thanks, the crio-wipe service works.
Still the crio service doesn't start because it doesn't find /etc/crio/seccomp.json
I am not an expert on CRI-O so I am not sure how to solve it. Maybe the file should be part of the package no?

**Comment by lsm5** [comment]
err ... sorry about that, let me look that up.

**Comment by alijahnas** [comment]
Hi @lsm5 anything new on the issue with `/etc/crio/seccomp.json` in the RPM and DEB packages?
I have a PR in Kubespray that use these packages: https://github.com/kubernetes-sigs/kubespray/pull/5145
And the crio service doesn't start on either CentOS or Ubuntu because the above file is missing. Thanks :+1

**Comment by rhatdan** [comment]
I would prefer to move to /usr/share/containers/seccomp.json so that it can be share between all of the different container engines.  Let's not make this only specific to CRI-O.

**Comment by alijahnas** [comment]
@rhatdan as long as it can be accessed by crio service it's ok. The crio config should then be modified to have it point to the new location.

**Comment by rhatdan** [comment]
I agree.

**Comment by dougsland** [comment]
@haircommander @mrunalp @rhatdan @alijahnas I believe it is all set in this report. Please take a look and close this one.
