### ISSUE TITLE
cri-o rpm 1.15.2

### ISSUE THREAD

**Issue by Prodian0013** [cri-o/cri-o#2826]
**Description**

**Steps to reproduce the issue:**

https://cbs.centos.org/repos/paas7-crio-115-candidate/x86_64/os/Packages/ is missing cri-o 1.15.2

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.15.1-2.el7
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by haircommander** [comment]
@lsm5 PTAL

**Comment by ibotty** [comment]
https://cbs.centos.org/repos/paas7-crio-115-candidate/x86_64/os/Packages/cri-o-1.15.1-2.el7.x86_64.rpm apparently exists now.

**Comment by matthias50** [comment]
> https://cbs.centos.org/repos/paas7-crio-115-candidate/x86_64/os/Packages/cri-o-1.15.1-2.el7.x86_64.rpm apparently exists now.

That's not the same thing. That is 1.15.1. The -2 is because there were multiple RPMs built which contain 1.15.1 (1.15.1-1 and 1.15.1-2).

**Comment by lsm5** [comment]
1.15.2 available at https://cbs.centos.org/koji/taskinfo?taskID=976430 . HTH.
