### ISSUE TITLE
Many tags exist which don't have releases

### ISSUE THREAD

**Issue by matthias50** [cri-o/cri-o#2832]
**Description**

Many tags in https://github.com/cri-o/cri-o/releases do not have releases associated with them.
**Steps to reproduce the issue:**
1. Visit https://github.com/cri-o/cri-o/releases

**Describe the results you received:**

There are many tags which don't have an associated release. For example 1.15.2, 1.15.1, 1.11.15, 1.14.9, 1.14.8, 1.14.7. 

**Describe the results you expected:**
Every tag has a release.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**
N/A

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by haircommander** [comment]
Thanks for the issue! I'll take a look
/assign

**Comment by haircommander** [comment]
/close
They all should have official releases now, sorry for the delay. thanks for opening the issue @matthias50
