### ISSUE TITLE
High memory usage during image pull

### ISSUE THREAD

**Issue by rkojedzinszky** [cri-o/cri-o#2847]
**Description**

Since release-1.15 image pulls needs huge amount of memory for crio daemon.

**Steps to reproduce the issue:**
1. Start release-1.15 crio daemon with empty /var/lib/containers as
```bash
/usr/bin/time -f "%M" ./crio
```
2. In another terminal:
```bash
crictl pull k8s.gcr.io/kube-apiserver:v1.16.0
```
3. Then, stop crio. You will see the max amount of memory used for the pull process.

**Describe the results you received:**

I received ~600Mbytes of max memory.

**Describe the results you expected:**

I expected to have it <100Mbytes, as was with 1.14.

**Additional information you deem important (e.g. issue happens only occasionally):**

Can be reproduced.

**Output of `crio --version`**

```
# ./crio --version
crio version 1.15.3-dev
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Qemu test environment & small board computers with low ram.

**Comment by rkojedzinszky** [comment]
It seems that https://github.com/containers/storage/commit/d85da313ef195ca827e3a17db9824971fbb6ec6e#diff-a281f22627802db5c62d316f5eac7a96 intoduced this behaviour.

**Comment by rhatdan** [comment]
@vbatts @nalind PTAL

**Comment by mrunalp** [comment]
@vrothberg ptal.

**Comment by vrothberg** [comment]
> @vrothberg ptal.

https://github.com/containers/storage/pull/435 fixes it. Thanks for the report and especially for bisecting, @rkojedzinszky!
