### ISSUE TITLE
CRI-O Nix Image Error

### ISSUE THREAD

**Issue by Prodian0013** [cri-o/cri-o#2848]
**Description**

**Steps to reproduce the issue:**
1. Following the instructions for static builds https://github.com/cri-o/cri-o/blob/master/tutorials/setup.md#static-builds
2. Run `make nix-image`

**Describe the results you received:**
`make[4]: *** [Makefile:12762: tests/test-suite.log] Error 1
make[4]: Leaving directory '/tmp/nix-build-coreutils-8.31.drv-0/coreutils-8.31'
make[3]: *** [Makefile:12870: check-TESTS] Error 2
make[3]: Leaving directory '/tmp/nix-build-coreutils-8.31.drv-0/coreutils-8.31'
make[2]: *** [Makefile:13125: check-am] Error 2
make[2]: Leaving directory '/tmp/nix-build-coreutils-8.31.drv-0/coreutils-8.31'
make[1]: *** [Makefile:12647: check-recursive] Error 1
make[1]: Leaving directory '/tmp/nix-build-coreutils-8.31.drv-0/coreutils-8.31'
make: *** [Makefile:13127: check] Error 2
builder for '/nix/store/ginpvcz8rvwim0g2di4bi11bmj7zz7li-coreutils-8.31.drv' failed with exit code 2
cannot build derivation '/nix/store/lgnq9jmfdfdy3x3llxv2vypdmxi6mbzz-compat-netbsd-8.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/3x4idn3pl3d8aa0vsx57v7s1d0mm95cn-findutils-4.6.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ikhyynhsny7f476jrv84467yxisrhc1k-gcc-wrapper-7.4.0.drv': 1 dependencies couldn't be built
building '/nix/store/n5w87cjanrqcnqplb4p1x3vx6qsqahhb-patch-2.7.6.drv'...
cannot build derivation '/nix/store/a3h10z2i163rfjsk3aa09sqgxjdbnbyl-stdenv-linux.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/xzdxrlc5sp39x8d2635vqib4wwhzs3vw-stdenv-linux.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ila2bqmphd54lv680nyv13d9mdgiz2fw-cri-o-x86_64-static-musl-e70f16792161ac69b9f0a895bbfe46c6106ed9a0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/ila2bqmphd54lv680nyv13d9mdgiz2fw-cri-o-x86_64-static-musl-e70f16792161ac69b9f0a895bbfe46c6106ed9a0.drv' failed
Error: error building at STEP "RUN nix-build --argstr revision ${COMMIT}": error while running runtime: exit status 100
12920.51user 3748.75system 1:06:13elapsed 419%CPU (0avgtext+0avgdata 1049496maxresident)k
296inputs+39621457outputs (0major+669460310minor)pagefaults 0swaps
make: *** [nix-image] Error 125`

**Describe the results you expected:**
For it not to throw an error?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CentOS Linux release 7.7.1908 (Core)

**Comment by saschagrunert** [comment]
Hey @Prodian0013, thanks for reporting that issue. I saw this as well on different systems and container runtimes, I'll work on a fix for 1.16.0.

**Comment by saschagrunert** [comment]
Hey @Prodian0013 can you give it a try again, we updated the nix dependencies for the image recently?

**Comment by Prodian0013** [comment]
@saschagrunert `make nix-image` appears to ran without errors but now when running `make build-static` it returns a permission denied.

```
make build-static
podman run --rm -it -v /home/jenkins/cri-o:/cri-o quay.io/crio/nix:1.1.0 sh -c \
        "nix build -f cri-o/nix --argstr revision f0d379cd80a5b7a3be8bcd1b120c32c415e37413 && \
        mkdir -p cri-o/bin && \
        cp result-*bin/bin/crio-* cri-o/bin"
error: opening file '/cri-o/nix/default.nix': Permission denied
make: *** [build-static] Error 1
```

**Comment by saschagrunert** [comment]
Hm, strange how is that possible. Are you sure that you want to use the image `quay.io/crio/nix:1.1.0` for building it or do you want to use the local one? For using the local one you would have to overwrite `TESTIMAGE_NIX`:

```
> make build-static TESTIMAGE_NIX=my-local-image:latest
```

**Comment by Prodian0013** [comment]
> Hm, strange how is that possible. Are you sure that you want to use the image `quay.io/crio/nix:1.1.0` for building it or do you want to use the local one? For using the local one you would have to overwrite `TESTIMAGE_NIX`:
> 
> ```
> > make build-static TESTIMAGE_NIX=localhost/my-local-image:latest
> ```

Im actually just trying to follow the documentation provided at https://github.com/cri-o/cri-o/blob/master/tutorials/setup.md which arent put together very well.

Why arent the binaries just provided on github with each release similar to containerd?  Crio needs to get its act together in terms of distribution compared to other container run times.  Theres multiple open issues asking for consistent build and package distributions but nothing has happened.

**Comment by Prodian0013** [comment]
@saschagrunert Same error as before when trying to use a local image
```
make test-image-nix  CONTAINER_RUNTIME=podman  TESTIMAGE_NIX=crionix
make build-static TESTIMAGE_NIX=localhost/crionix
```
```
podman run --rm -it -v /home/jenkins/cri-o:/cri-o localhost/crionix sh -c \
        "nix build -f cri-o/nix --argstr revision f0d379cd80a5b7a3be8bcd1b120c32c415e37413 && \
        mkdir -p cri-o/bin && \
        cp result-*bin/bin/crio-* cri-o/bin"
error: opening file '/cri-o/nix/default.nix': Permission denied
make: *** [build-static] Error 1
```

**Comment by Prodian0013** [comment]
@saschagrunert figure it out selinux was blocking it

**Comment by saschagrunert** [comment]
Oh cool, how did you solve it? Let me know how to improve the docs to avoid such issues in the future. I’m always happy to help somehow. :)

**Comment by Prodian0013** [comment]
> Oh cool, how did you solve it? Let me know how to improve the docs to avoid such issues in the future. I’m always happy to help somehow. :)

`setenforce 0` to test my theory

Another issue I found is with bundle/build not being backwards compatible with older version of coreutils
```
cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.7 (Maipo)
```

**Comment by Prodian0013** [comment]
@saschagrunert I was finally able to create a bundle tar for 1.16.2 tag! I did notice the crio-status binary was missing from the tar, do you see that as an issue?

**Comment by saschagrunert** [comment]
> @saschagrunert I was finally able to create a bundle tar for 1.16.2 tag! I did notice the crio-status binary was missing from the tar, do you see that as an issue?

Thanks for the feedback, we added it to the release bundle and static build. Closing this now feel free to reopen if you encounter another bug.
