### ISSUE TITLE
cri-o passes (possibly) reused namespaces on network teardown

### ISSUE THREAD

**Issue by squeed** [cri-o/cri-o#2849]
**Description**
CRI-O tears down networking after a reboot, risking pid reuse.

**Steps to reproduce the issue:**
Sadly, reproducing this is probabilistic. It should still be easy to fix, though

1. Reboot the node. Create some containers, so they have a low pid number
2. Reboot the node again
3. Kubelet starts tearing down sandboxes that were killed because of the reboot
4. cri-o issues a CNI delete with /proc/$pid/ns/net, even though `$pid` is meaningless since the reboot.

Even if you don't get a pid collision, I was able to see pretty clearly getting a CNI DEL for a stale pid. For example, from crio logs at level Info:

```
About to add CNI network lo (type=loopback)
Got pod network &{Name:alertmanager-main-1 Namespace:openshift-monitoring ID:... NetNS:/proc/8036/ns/net Networks:[] RuntimeConfig:map[]}

-- reboot --

About to del CNI network lo (type=loopback)
Error deleting network: failed to Statfs "/proc/8036/ns/net": no such file or directory
```

This clearly shows that it is *looking* for `/proc/8036...`, and it happens to not be a process. However, reboot enough times and you will eventually lose and it will point to a running pid (but not the one started by cri-o). We typically see this in about 1-in-10 reboots.

**Describe the results you received:**
We got a CNI Delete with the netns of `/proc/<pid>/ns/net`, which is correct, except that the node was rebooted in the mean time, and `/proc/<pid>/ns/net` pointed to the root netns.

**Describe the results you expected:**
The CNI delete should be with an empty netns parameter, which signifies to the plugins that the namespace is gone and only bookkeeping operations (e.g IPAM cleanup) are to be done. CRI-O should only pass the netns parameter if it points to a known-good crio-created process that is still running.

**Output of `crio --version`:**

```
crio version 1.14.10-0.19.dev.rhaos4.2.gita86dae7.el8
```

**Comment by squeed** [comment]
Another solution would be to bind-mount the network namespace to `/var/run/netns/<containerid>`, and only pass that. Then, if there's a reboot, it will be invalidated automatically. This is what rkt does.

**Comment by umohnani8** [comment]
@squeed I am currently working on fixing this up in CRI-O. I am returning an empty string as the netns path but I keep getting this error when tryng to stop the network and clean up
```
level=error msg="Error deleting network: failed to Statfs "": no such file or directory"
34.709227408-04:00" level=error msg="Error while removing pod from CNI lo network: failed to Statfs "": no such file or directory"
```

This probably needs to be fixed in ocicni before we can patch this up in CRI-O

**Comment by squeed** [comment]
Very good point. Filed https://github.com/cri-o/ocicni/issues/64

**Comment by mccv1r0** [comment]
Using ```ocicnitool``` supplying "" for netns seems to behave.  What call is returning the ```failed to Statfs``` error?

**Comment by haircommander** [comment]
I think the stat is coming from `internal/lib/sandbox/sandbox.go:372` `NetNsPath()` which returns the path given the pause pid. I am guessing the pause pid is no longer valid, and so the stat fails? If the pause container is down, the net namespace is probably not valid anymore. what is the proper course of action there?

**Comment by haircommander** [comment]
I actually think it comes from 
`vendor/github.com/opencontainers/runc/libcontainer/container_linux.go`
because we try to grab the NetNsPath in `server/container_create_linux.go:618` and immediately pass it to the runtime.

**Comment by haircommander** [comment]
We have mitigated this with the option `manage_ns_lifecycle` in cri-o, which does not allow for races with kernel namespace tearing down. as such, I am closing this. please reopen if you disagree

**Comment by squeed** [comment]
@haircommander cool, thanks for following up. That's a decently large enough change to grok, so one question for you: we don't pass namespaces with pids to CNI anymore, right?

**Comment by haircommander** [comment]
nope! they're bind mounted in a similar way that rkt did it
