### ISSUE TITLE
Error: Image not known after upgrade cri-o upgrade

### ISSUE THREAD

**Issue by bartelsb** [cri-o/cri-o#2853]
**Description**

I am updating cri-o across the nodes in my Kubernetes cluster. Prior to upgrade, everything seems to be working fine. After upgrade, some (but not all) workloads will no longer run. They get stuck in a `CreateContainerError` state. When I describe the pods for these workloads, I see the following:
```
      Successfully assigned wazuh/wazuh-7bb996795-2zjfb to ip-10-240-5-229.eu-central-1.compute.internal
      Normal   Pulled     5m33s (x8 over 7m4s)  kubelet, ip-10-240-5-229.eu-central-1.compute.internal  Successfully pulled image "datica/wazuh:3.6.1"
      Warning  Failed     5m33s (x8 over 7m4s)  kubelet, ip-10-240-5-229.eu-central-1.compute.internal  Error: image not known
```
Also, when I attempt to delete the pods, they seem to get stuck in a `Terminating` state.

**Steps to reproduce the issue:**
1. Upgrade coreos on hosts from v1967.6.0 to v2191.5.0 (to get glibc 2.29)
2. Upgrade cri-o from v1.13.3 to v1.15.1-dev
3. Upgrade Kubernetes control plane components from 1.13.10 to 1.15.3 (I'm testing now to see if this issue occurs without upgrading k8s components, will update after)

**Describe the results you received:**
Workloads are no longer running correctly. Some can't start, and have the error above in their events. Deleting pods results in them being stuck indefinitely in a `Terminating` state.

**Describe the results you expected:**
All workloads would continue running.

**Additional information you deem important (e.g. issue happens only occasionally):**
I found [one Redhat thread](https://bugzilla.redhat.com/show_bug.cgi?id=1708605) that discussed a similar issue and indicated upgrading cri-o from certain versions could cause problems. Not sure if it's relevant though, and the thread did not really explain why their issue was occurring.

**Output of `crio --version`:**
Prior to upgrade:
```
crio version 1.13.3
commit: "5a3c24900797986fd3f1f39094aeea8c4a4354ef"
```

After upgrade:
```
crio version 1.15.1-dev
commit: "7eb0fb039a8e379bcda319826a34caec983e8519-dirty"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CoreOS nodes running in AWS.

**Comment by haircommander** [comment]
can you first try to upgrade to the latest on the 1.13 branch before going to 1.15? There were known issues in container/image storage that were fixed after 1.13.9

**Comment by bartelsb** [comment]
I will try this next and get back to you.

**Comment by bartelsb** [comment]
I'm seeing the issue just after upgrading crio from `1.13.3` to `1.13.11-dev` (image built from branch `v1.13.10`). Any other thoughts?

Prior to upgrade:
```
crio version 1.13.3
commit: "5a3c24900797986fd3f1f39094aeea8c4a4354ef"
```

After upgrade:
```
crio version 1.13.11-dev
commit: "852c30c33b748a3b2a9865f29f662638f65a63d2"
```

**Comment by bartelsb** [comment]
It seems that deleting the image from the host and pulling down a new one fixes the issue. However, that's not a great solution for us because the images can't be deleted while in use, and we can only delete one pod at a time from our deployments without risking downtime. Any idea as to why all local images stop working post-upgrade?

**Comment by haircommander** [comment]
ah dang. Okay, what do you do for an upgrade? replace the binaries? or by package manager?

**Comment by bartelsb** [comment]
Yes, we replace the binaries and restart the systemd service that runs crio.

**Comment by haircommander** [comment]
Also, does upgrading to 1.14 work?

**Comment by bartelsb** [comment]
We haven't tried that yet, but we can. From 1.13.3 or from 1.13.10?

**Comment by haircommander** [comment]
1.13.10 please!
thank you! I am low on bandwidth this week but if I can't figure it out I'll get to it next week

**Comment by haircommander** [comment]
also 1.14.10 would probably be best too

**Comment by bartelsb** [comment]
Unfortunately, I'm having issues getting a clean image build from any of the `v1.14.*` branches. I think it's related to the name change of the protobuf-c dependency.

**Comment by mrunalp** [comment]
cc: @nalind @mtrmac

**Comment by bartelsb** [comment]
Our current workaround looks like this (in pseudo-code):
```
drain the node
for each remaining pod (daemonsets):
    delete the pod
backup kubelet manifests
confirm that all pods have stopped and been removed
retrieve a list of images
for each image:
    delete the image
uncordon the node
```

It's not ideal, but it should work.

**Comment by haircommander** [comment]
@bartelsb sorry for the *super* late response. Have you found any success with upgrades? is there any more information you'd like to provide me to help me debug your situation?

**Comment by bartelsb** [comment]
No worries. Yes, we went through this upgrade a while back and it was successful. I believe we went with the method mentioned above of deleting all of the images before uncordoning each node, which allowed cri-o to pull a fresh image for every pod assigned to the node. I'll close this issue now, as the workaround seems to work as described.

**Comment by haircommander** [comment]
well then here's a shameless plug to use `crio wipe` to do this. We have `crio wipe` running as a requirement for the `crio.service` systemd unit. It checks if there has been a minor version upgrade (1.16->1.17), and removes the images if so. If there was a reboot, it now also removes containers, which is good state to clear out between reboots. Glad you found a work around :smile:
