### ISSUE TITLE
Running cri-o as unprivileged user (rootless) fails with FATAL chown "operation not permitted"

### ISSUE THREAD

**Issue by TristanCacqueray** [cri-o/cri-o#2858]
**Description**

Running cri-o as unprivileged user doesn't seem to be working. Is this supported?

**Steps to reproduce the issue:**

1. Generate config with:
```
crio config | sed -e "s#/var/run/crio#${HOME}/.cache/crio#" -e "s#/run/runc#${XDG_RUNTIME_DIR}/crio#" -e "s#/var/log/crio#${HOME}/.cache/crio-logs#" -e "s#^conmon .*#conmon = '/usr/libexec/podman/conmon'#" -e "s#/opt/cni/bin#/usr/libexec/cni#" > ~/.config/crio.conf 
```
2. Start crio
```
crio --config ~/.config/crio.conf
``` 

**Describe the results you received:**

Crio fails with:

```
DEBU[2019-09-24 18:08:11.132719066-04:00] using runtime executable from $PATH "/usr/bin/runc"  file="config/config.go:793"
DEBU[2019-09-24 18:08:11.132852963-04:00] found valid runtime "runc" for runtime_path "/usr/bin/runc"  file="config/config.go:799"
INFO[2019-09-24 18:08:11.133529341-04:00] using conmon executable "/usr/libexec/podman/conmon"  file="config/config.go:730"
DEBU[2019-09-24 18:08:11.134225418-04:00] [graphdriver] trying provided driver "overlay"  file="drivers/driver.go:244"
DEBU[2019-09-24 18:08:11.134320250-04:00] overlay: mount_program=/usr/bin/fuse-overlayfs  file="overlay/overlay.go:313"
FATA[2019-09-24 18:28:18.470962012-04:00] chown /var/home/tristanc/.local/share/containers/storage/overlay/l: operation not permitted 
```

After fixing the chown call uids in the code, crio fails later with:
 
```
FATA[2019-09-24 18:31:53.462771398-04:00] operation not permitted                      

[pid 15603] mount("/var/home/tristanc/.local/share/containers/storage/overlay", "/var/home/tristanc/.local/share/containers/storage/overlay", 0xc0003713c9, MS_BIND, NULL) = -1 EPERM (Operation not permitted)
```

**Describe the results you expected:**

Crio starts.

**Additional information you deem important (e.g. issue happens only occasionally):**

Using _CRIO_ROOTLESS=1 or setting different uidmaps didn't help.

**Output of `crio --version`:**

```
crio version 1.15.1-dev
commit: "f8d13a9055fa836b9f624142de4a5e2f01d6fb26-dirty"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Silverblue 30 host.

**Comment by mrunalp** [comment]
@giuseppe ptal

**Comment by giuseppe** [comment]
CRI-O doesn't automatically create the user namespace.  This is not really a limitation, since when running as rootless all the Kubernetes components must be in the same user namespace.  I'd suggest you don't use the rootless support directly but through Usernetes.

**Comment by AkihiroSuda** [comment]
Here is the link to Usernetes (contains CRI-O as well)
https://github.com/rootless-containers/usernetes

**Comment by TristanCacqueray** [comment]
Thank you for the pointer, using rootlesskit I was able to start crio with the vfs storage driver.

**Comment by TristanCacqueray** [comment]
Well for some reason when using usernetes, CRI-O fails to setup SELinux context. It seems like rootlesskit remount /sys for slirp which hides /sys/fs/selinux. And even when remounting the selinuxfs, then CRI-O fails with `selinux label is specified in config, but selinux is disabled or not supported`

**Comment by smijolovic** [comment]
can you describe what you mean by:

"After fixing the chown call uids in the code"

Rootlesskit or usernetes are not real solutions - crio should have the ability to run as a deprivileged user via systemd. Chown is a root only command and should be removed as part of the CRIO process. Curious to what you did to help move this forward - even if a SIG for cri-o.

**Comment by TristanCacqueray** [comment]
@smijolovic iirc I changed the chown argument so that it doesn't results in a permission failure.

**Comment by hanneshoettinger** [comment]
@TristanCacqueray did you manage to run crio as unprivileged user? if yes, how?

**Comment by giuseppe** [comment]
> Rootlesskit or usernetes are not real solutions - crio should have the ability to run as a deprivileged user via systemd. Chown is a root only command and should be removed as part of the CRIO process. Curious to what you did to help move this forward - even if a SIG for cri-o.

it must be in the same namespaces as the Kubelet and the rest of Kubernetes, so that is not possible, unless we add extra logic for joining namespaces.

**Comment by AkihiroSuda** [comment]
@hanneshoettinger See https://github.com/rootless-containers/usernetes#install (`./install.sh --cri=crio`)

**Comment by hanneshoettinger** [comment]
_CRIO_ROOTLESS=1 worked for me.

**Comment by TristanCacqueray** [comment]
@hanneshoettinger yes, using `usernetes`. Though I am having some issues with SELinux : https://github.com/rootless-containers/rootlesskit/issues/94 .
