### ISSUE TITLE
Audit

### ISSUE THREAD

**Issue by runcom** [cri-o/cri-o#288]
Similar to what the kernel does, it would be nice for cri-o to support some sort of audit logging. That allows administrators to have a clear vision on what cri-o is doing and enhance security. 
This is a placeholder issue to discuss audit. I'll create a design document if people are happy having this. 

Thoughts? Questions?

**Comment by resouer** [comment]
👍 for this, please.

**Comment by jawnsy** [comment]
It makes sense to have some logging facility, though isn't it less useful at the CRI-O level, since we don't have contextual information like the reason a pod was started or by whom? Maybe if we support a standard like [OpenTracing](http://opentracing.io/)? We'd have to be careful not to rely on any external services being available, though.

**Comment by runcom** [comment]
> It makes sense to have some logging facility, though isn't it less useful at the CRI-O level, since we don't have contextual information like the reason a pod was started or by whom? Maybe if we support a standard like OpenTracing? We'd have to be careful not to rely on any external services being available, though.

I was thinking at just using the kernel/system audit subsystem, what about that?

**Comment by jawnsy** [comment]
@runcom Are there other systems we want to correlate with, like kubernetes, and do they log to the kernel audit subsystem as well? I'm not too familiar with it, the extent of my familiarity with it is looking in `/var/log/audit/audit.log` for SELinux errors :smile:

Maybe we can punt on the decision by making it pluggable, and defaulting to the audit subsystem?  Then if some better idea comes along we can provide that as a plugin and make it selectable with `ocid.conf`.

**Comment by fntlnz** [comment]
What kind of events would you like to track?

Talking about the audit subsystem, I think that a pointer could be interesting to track all the endpoints in `server/` with request/response information, wdyt?

**Comment by rhatdan** [comment]
I pinged Steve Grubb to see if he is interested in auditing added to CRI-O.  Might be a better question for podman and buildah.

**Comment by stevegrubb** [comment]
I'd be happy to help flesh out the requirements. There's 2 kinds of requirements...the ones for common criteria, and the extra information you might want not required by CC. CC wants the full lifecycle events such as start, stop, suspend, migrate, etc. It wants resource assignments. And a couple other things. The requirements are more or less spelled out in this document:

https://github.com/linux-audit/audit-documentation/wiki/SPEC-Virtualization-Manager-Guest-Lifecycle-Events

But I imagine you'd want this boiled down to something a little more specific. This is also needing to be coordinated with the patches currently being discussed on the linux-audit mail list for container IDs.

**Comment by rhatdan** [comment]
Another year goes by and no one has worked on this.  Is this important for RHEL8?
