### ISSUE TITLE
dnf installation fails on f30

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#2897]
cross-posting https://github.com/cri-o/cri-o.io/pull/36#issuecomment-543104822 to track
seemingly related https://bugzilla.redhat.com/show_bug.cgi?id=1754170

**Comment by lsm5** [comment]
fedora bugzilla at https://bugzilla.redhat.com/show_bug.cgi?id=1754170

**Comment by adelton** [comment]
It seems that due to https://bugzilla.redhat.com/show_bug.cgi?id=1751765, the steps on Fedora 30 need to be
```
VERSION=1.14
dnf module enable cri-o:$VERSION
dnf install cri-o
```

**Comment by afbjorklund** [comment]
Later versions are available from Koji directly, there's something wrong with the 1.15 and 1.16 modules.

https://koji.fedoraproject.org/koji/packageinfo?packageID=24240

**Comment by spaced** [comment]
for `f31` available in `updates-testing-modular-f31` repo, see
https://bodhi.fedoraproject.org/updates/FEDORA-MODULAR-2019-24636b4ff9

**Comment by dougsland** [comment]
@haircommander @mrunalp  it seems ready to close this one.

**Comment by adelton** [comment]
On Fedora 32 (to be), the steps fail:
```
# dnf module enable cri-o:$VERSION
Last metadata expiration check: 0:01:26 ago on Mon Mar 30 08:12:50 2020.
Error: Problems in request:
missing groups or modules: cri-o:1.14
```
I don't think the generic "Fedora 30 and later" with 1.14 instructions will work long term.

**Comment by afbjorklund** [comment]
> I don't think the generic "Fedora 30 and later" with 1.14 instructions will work long term.

Like with Kubernetes 1.18 already out and released, you mean ? No, that seems a bit late.

**Comment by adelton** [comment]
I mean, https://cri-o.io/ says that 1.14 works on Fedora 30 and later (higher), but that does not seem to be true on Fedora 32.

**Comment by haircommander** [comment]
@lsm5 what versions of cri-o are being built for f32 right now?

@adelton I can imagine we don't support 1.14 on f32 anymore, probably only 1.17-1.15 (and probably will soon drop support for 1.15 once we cut 1.18 which should be happening soon)

**Comment by lsm5** [comment]
@haircommander can you release a 1.18.0 or something? I'll build 1.18 then. Also, remind me how many prior 1.X releases we're required to support.

**Comment by haircommander** [comment]
we're required to support three kubernetes releases, so kubernetes/CRI-O 1.15 has just had support dropped. That means you could get away with building 1.16 and 1.17. Hopefully we can get 1.18 out this week.

**Comment by lsm5** [comment]
> I mean, https://cri-o.io/ says that 1.14 works on Fedora 30 and later (higher), but that does not seem to be true on Fedora 32.

@haircommander ack, I guess the `three latest releases` part should be clear on the site. Once you have 1.18 released, I'll build for fedora and add another PR for the install doc.

**Comment by haircommander** [comment]
1.16-1.18 is on OBS and I think the install doc is updated. closing as such, please reopen if you disagree
