### ISSUE TITLE
Add metric for time spent in oci hooks

### ISSUE THREAD

**Issue by smarterclayton** [cri-o/cri-o#2902]
OCI hooks can potentially be a significant portion of container start time.  From an operational perspective as part of understanding where time is going during hooks it would be useful to track a latency summary metric for the individual hooks when they are invoked.  I.e. a prometheus summary vector with a single label for `hook` (or whatever the appropriate name is) so that an administrator can estimate how much time a hook adds to the various start calls.

This would be part of the large effort to improve pod start times across Kubernetes (a number of key components are already tracked, but this would close a CRI-O specific component to start container times).

**Comment by smarterclayton** [comment]
@mrunalp

**Comment by rhatdan** [comment]
This is handled in the OCI Runtime, I believe so it would need to be added to them.
@giuseppe WDYT of doing this in crun?

**Comment by giuseppe** [comment]
@rhatdan adding the feature to crun would be easy.  We will need to agree where this information is stored and how CRI-O can access it.

I think a wrapper program will be more portable and easier to manage and CRI-O can inject it in every configured OCI hook.

It can be as simple as using `/usr/bin/time`, e.g.:

```
        "prestart": [
            {
                "path": "/usr/bin/echo",
                "args": ["/usr/bin/sleep", "1"]
            }
        ]
```

becomes:

```
        "prestart": [
            {
                "path": "/usr/bin/time",
                "args": ["/usr/bin/time", "--output=/tmp/hook-1-time", "/usr/bin/sleep", "1"]
            }
        ]
```

**Comment by rhatdan** [comment]
@smarterclayton @mrunalp WDYT?  (Although need to be smart about the path to the output.

**Comment by mrunalp** [comment]
Wrapper will be easiest to implement without having to modify runc in the short term. I think we can open an issue/discussion upstream regardless. If there is wider interest, then we can make it first class in runc.

**Comment by mrunalp** [comment]
@smarterclayton One more thing that will be useful to track is CNI network setup time including calling the CNI hook. I will create another issue for that.

**Comment by rhatdan** [comment]
Do we know which OCI Plugins we are actually using in OpenShift. I would think we should be running none by default.  oci-systemd-hook and oci-umount are not needed for CRI-O and Overlayfs storage driver.

**Comment by mrunalp** [comment]
We have oci-systemd-hook installed and I think we have some users trying to use that and copying out logs based on a report I got today.

**Comment by rhatdan** [comment]
Well we should get rid of it, and if we want to allow containers to run as systemd, we could vendor in the code from podman that does this the correct way without requiring a hook.
