### ISSUE TITLE
all CRI-O versions after commit fdc2cc372 fail to pull OCI formatted images while pulling Docker formatted images works fine

### ISSUE THREAD

**Issue by ghglza** [cri-o/cri-o#2905]
**Description**

**Steps to reproduce the issue:**
1. Build CRI-O from sources after commit fdc2cc372
2. Deploy to CentOS 7 machine
3. Try to pull container image in OCI format (i.e. built with "buildah --format oci ...)" via "crictl pull ..."

**Describe the results you received:**
Pull operation fails w/ RPC error about "unsupported docker v2s2 media type"

**Describe the results you expected:**
Image pull operation succeeds, as with the same image and CRI-O versions up to / including commit fdc2cc372

**Additional information you deem important (e.g. issue happens only occasionally):**
CRI-O was built w/ golang version 1.13 on CentOS 7 -- trying to pull an image built from the very same buildah configuration, but commited by "buildah --format docker..."  works fine

**Output of `crio --version`:**
[this is for the last version working w/ OCI formatted images]
```
crio version 1.16.0-dev
commit: "fdc2cc372a49413bb89abaa9494beb24ab9e0ce3"

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CentOS 7.7.1908 provisioned in VMWare (test environment) / VirtualBox (CRI-O build environment)

Output from "grep -v -e '^#' -e '^$' /etc/crio/crio.conf":
```
[crio]
log_dir = "/var/log/crio/pods"
version_file = "/var/lib/crio/version"
[crio.api]
listen = "/var/run/crio/crio.sock"
host_ip = ""
stream_address = "127.0.0.1"
stream_port = "0"
stream_enable_tls = false
stream_tls_cert = ""
stream_tls_key = ""
stream_tls_ca = ""
grpc_max_send_msg_size = 16777216
grpc_max_recv_msg_size = 16777216
[crio.runtime]
default_runtime = "runc"
no_pivot = false
conmon = "/usr/libexec/crio/conmon"
conmon_cgroup = "pod"
conmon_env = [
	"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
]
selinux = true
seccomp_profile = ""
apparmor_profile = "crio-default-1.16.0-dev"
cgroup_manager = "systemd"
default_capabilities = [
	"CHOWN", 
	"DAC_OVERRIDE", 
	"FSETID", 
	"FOWNER", 
	"NET_RAW", 
	"SETGID", 
	"SETUID", 
	"SETPCAP", 
	"NET_BIND_SERVICE", 
	"SYS_CHROOT", 
	"KILL", 
]
default_sysctls = [
]
additional_devices = [
]
hooks_dir = [
]
default_mounts = [
]
pids_limit = 1024
log_size_max = -1
log_to_journald = false
container_exits_dir = "/var/run/crio/exits"
container_attach_socket_dir = "/var/run/crio"
bind_mount_prefix = ""
read_only = false
log_level = "error"
uid_mappings = ""
gid_mappings = ""
ctr_stop_timeout = 0
manage_network_ns_lifecycle = false
[crio.runtime.runtimes.runc]
runtime_path = ""
runtime_type = "oci"
runtime_root = "/run/runc"
[crio.image]
default_transport = "docker://"
global_auth_file = ""
pause_image = "k8s.gcr.io/pause:3.1"
pause_image_auth_file = ""
pause_command = "/pause"
signature_policy = ""
image_volumes = "mkdir"
[crio.network]
network_dir = "/etc/cni/net.d/"
plugin_dirs = [
	"/opt/cni/bin/",
]
[crio.metrics]
enable_metrics = false
metrics_port = 9090
```

**Comment by saschagrunert** [comment]
Hey @ghglza, may I ask you to provide us more information about the image and the registry where you'd pull the image from? I'm currently not able to reproduce it locally. Which tool and version did you use to push the image into the registry?

**Comment by ghglza** [comment]
The registry is a locally operated Nexus Repository Manager OSS 3.9.0-01, the image built w/ buildah 1.11.3, (both formats), and copied to the registry w/ skopeo 0.1.37, while being based on a CentOS 7 standard layer.

**Comment by ghglza** [comment]
And the container storage of the image build environment (i.e. the source from where the image is copied to the Nexus registry) is CRI-O  1.11.11-1.rhaos3.11.git474f73d.el7

**Comment by rhatdan** [comment]
Are you able to pull it using podman and/or skopeo?

**Comment by ghglza** [comment]
"skopeo copy docker://... containers-storage:..." and "podman pull..." on the machine where "crictl pull..." fails works fine -- skopeo is 0.1.37, podman 1.4.4

**Comment by ghglza** [comment]
Once copied via skopeo or podman, CRI-O version 08cf02124 can remove the OCI formatted image from local container strorage w/o problems via crictl

**Comment by rhatdan** [comment]
And can it pull it again then?

**Comment by ghglza** [comment]
With podman -- yes, with crictl -- no.

**Comment by ghglza** [comment]
The error stays the same when upgrading to CRI-O v1.16.0 (commit fa99ff4ae).

Now while we could re-build all our images in Docker format as a workaround, we would prefer to be able to pull OCI formatted images (as this format is the default when building w/ buildah).

Has anybody an idea why this media format error occurs?

**Comment by haircommander** [comment]
@mtrmac @vrothberg @nalind PTAL

**Comment by vrothberg** [comment]
@ghglza can you paste the entire error? Also, I'd love to see the output of `skopeo inspect --raw` on the image you attempt to pull.

The mentioned versions of Podman and Skopeo use an older version of containers/image than CRI-O v1.16.0 does which explains why `podman pull` works.

**Comment by ghglza** [comment]
@vrothberg you're right ref. the image library version -- trying to copy the OCI formatted image with skopeo 0.1.40 (commit be6146b0a) fails with the very same error message

'''
# crictl --debug pull docker.corp.int:5001/proj/autoreg/artifact-loader:oci-image-test113
DEBU[0000] PullImageRequest: &PullImageRequest{Image:&ImageSpec{Image:docker.corp.int:5001/proj/autoreg/artifact-loader:oci-image-test113,},Auth:nil,SandboxConfig:nil,}
DEBU[0000] PullImageResponse: nil
FATA[0000] pulling image failed: rpc error: code = Unknown desc = unsupported docker v2s2 media type: ""

# ../skopeo inspect --raw docker://docker.corp.int:5001/proj/autoreg/artifact-loader:oci-image-test113 | jq .
{
  "schemaVersion": 2,
  "config": {
    "mediaType": "application/vnd.oci.image.config.v1+json",
    "digest": "sha256:ef680c1a9fda67ded184daea17071cdd5b3c69db061c5a4c0815d4ce09df74ea",
    "size": 3719
  },
  "layers": [
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar",
      "digest": "sha256:52b8c05288da8d6fb365b6cfc325a4f817522e87723e00f71b08f9d77daa3c84",
      "size": 78975355
    },
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar",
      "digest": "sha256:be80b3af4d7b320bc0a68f66102744b33c2b69a536f369c216054bb4397ebaf6",
      "size": 1694
    },
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar",
      "digest": "sha256:fcfb41a7e6be120cd2bbe97ca35d974a033767cc55e20692e020dfce57185766",
      "size": 45520657
    },
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar",
      "digest": "sha256:7f1cce15b1dd45adf43e91a4ac0d93b3335147bef677e22a8352071539c003f8",
      "size": 179
    },
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar",
      "digest": "sha256:067a01097f13ace840196085b172fbd61059238728495c8d0af179055bdff32f",
      "size": 302
    },
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar",
      "digest": "sha256:ce34a576a5d16a31b472ddba9353e22067a1758027747cf09ab3fa9cae1130b8",
      "size": 6471
    },
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar",
      "digest": "sha256:fb70e84af5bbcaa9ebce865ebc2655a061f0a30ecad459f8b7748809109417e0",
      "size": 488466
    },
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar",
      "digest": "sha256:c839227b82e3ca826c25ac1c233a27a04a00b166f49e7c66c9e60ca1a43ddcc8",
      "size": 26249968
    },
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar",
      "digest": "sha256:ce2bfd3ded729dfef126a6ed5b997cbca7a14868fc91a212906f5fb0e325805b",
      "size": 43300193
    }
  ]
}
'''

**Comment by mtrmac** [comment]
Can you re-check the CRI-O commit reference, please?

An update of containers/image (to something that includes https://github.com/containers/image/commit/69aa1e85460f4bbc9d4762b0c01efda6c0759979 ) would clearly be relevant, except that I can’t see the linked CRI-O commit (https://github.com/cri-o/cri-o/commit/fdc2cc372a49413bb89abaa9494beb24ab9e0ce3 ) changing the c/image version at all; v3.0.2 is used both before and after AFAICS; in fact the error message `unsupported docker v2s2 media type` does not exist _at all_ in the source code as of that commit (but it does exist on `master`)

---

As far as the cause, I would guess `manifest.GuessMIMEType` mis-detecting the image as v2s2 at _some_ point (during push?), but I can’t immediately see how. Or maybe the registry itself might be returning a v2s2 MIME type in the `Content-Type` header.

**Comment by vrothberg** [comment]
@mtrac, it starts breaking _after_ this commit (i.e., commit a04c91657341).

**Comment by vrothberg** [comment]
I have troubles wrapping my head around it. We're pulling an OCI images fail with `unsupported docker v2s2 media type: ""` relating to a docker v2s2 image. The `skopeo inspect` output from https://github.com/cri-o/cri-o/issues/2905#issuecomment-550344336 looks okay to me.

**Comment by mtrmac** [comment]
> @mtrmac , it starts breaking _after_ this commit (i.e., commit [a04c916](https://github.com/cri-o/cri-o/commit/a04c91657341655d5ed8c7a3faf1f7c8514e9b9e)).

Duh. Thanks.

> We're pulling an OCI images fail with unsupported docker v2s2 media type: "" relating to a docker v2s2 image.

The easiest way this could happen is if `GetManifest` returned the listed manifest with a v2s2 MIME type (for some unknown reason), `manifest.Schema2FromManifest` would then clearly reject the OCI data now that MIME types are enforced (whereas before it would have silently worked well enough).

**Comment by mtrmac** [comment]
@ghglza Can you paste the output of
```
skopeo copy --debug docker://docker.corp.int:5001/proj/autoreg/artifact-loader:oci-image-test113 docker://$some_other_location
```
, please? Primarily looking for a line matching `Manifest has MIME type`, but collecting the full output might be useful anyway. Preferably using one of the new failing skopeo versions.

**Comment by nalind** [comment]
@mtrmac that does seem to be what's happening with nexus3 (3.19.1-01) when I push an image to it using OCI format:  the manifest that I get back looks like an OCI manifest, but in `dockerImageSource.fetchManifest()`, we're being told it's a `application/vnd.docker.distribution.manifest.v2+json`.

**Comment by ghglza** [comment]
Destination is temporary Docker v2 registry (therefore the authentication errors) -- but I think you can see the same error as with copying to local container storage

```
# ../u002305/skopeo --debug copy docker://docker.corp.int:5001/proj/autoreg/artifact-loader:oci-image-test113 docker://172.25.77.203:5000/proj/autoreg/artifact-loader:oci-image-test113
DEBU[0000] Credentials not found
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration
DEBU[0000]  Using "default-docker" configuration
DEBU[0000]   Using file:///var/lib/atomic/sigstore
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/172.25.77.203:5000
DEBU[0000] reference rewritten from 'docker.corp.int:5001/proj/autoreg/artifact-loader:oci-image-test113' to 'docker.corp.int:5001/proj/autoreg/artifact-loader:oci-image-test113'
DEBU[0000] Trying to pull "docker.corp.int:5001/proj/autoreg/artifact-loader:oci-image-test113"
DEBU[0000] Credentials not found
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration
DEBU[0000]  Using "default-docker" configuration
DEBU[0000]  No signature storage configuration found for docker.corp.int:5001/proj/autoreg/artifact-loader:oci-image-test113
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/docker.corp.int:5001
DEBU[0000] GET https://docker.corp.int:5001/v2/
DEBU[0000] Ping https://docker.corp.int:5001/v2/ status 401
DEBU[0000] GET https://docker.corp.int:5001/v2/token?scope=repository%3Aproj%2Fautoreg%2Fartifact-loader%3Apull&service=https%3A%2F%2Fdocker.corp.int%3A5001%2Fv2%2Ftoken
DEBU[0000] Increasing token expiration to: 60 seconds
DEBU[0000] GET https://docker.corp.int:5001/v2/proj/autoreg/artifact-loader/manifests/oci-image-test113
DEBU[0000] Using blob info cache at /var/lib/containers/cache/blob-info-cache-v1.boltdb
DEBU[0000] IsRunningImageAllowed for image docker:docker.corp.int:5001/proj/autoreg/artifact-loader:oci-image-test113
DEBU[0000]  Using default policy section
DEBU[0000]  Requirement 0: allowed
DEBU[0000] Overall: allowed
FATA[0000] Error initializing image from source docker://docker.corp.int:5001/proj/autoreg/artifact-loader:oci-image-test113: unsupported docker v2s2 media type: ""
```

**Comment by mtrmac** [comment]
@nalind Thanks. Ouch, that’s broken.

It’s rather tempting to just declare the registry as not supporting OCI correctly.

(This was actually  previously reported in https://github.com/containers/buildah/issues/575  , and closed as such in there.)

The corresponding Nexus bug seems to be https://issues.sonatype.org/browse/NEXUS-16947 , closed with “We can't see any reference about docker registries needing to be OCI compliant in the Docker spec. ”. That’s a bit demotivating.

---

Is there a HTTP header, or some other convenient mechanism to detect the registry implementation that we could use to work around this (by using `GuessMIMEType`), without ignoring valid `Content-Type` values for other registries? Preferably including a version number, so that we could turn the work-around off after Nexus is fixed?

**Comment by mtrmac** [comment]
> Destination is temporary Docker v2 registry (therefore the authentication errors) -- but I think you can see the same error as with copying to local container storage

Oops, it turns out the image is rejected before the code I was expected to log the MIME types is executed. Nalin has confirmed the behavior in the meantime.

**Comment by mtrmac** [comment]
> Is there a HTTP header, or some other convenient mechanism to detect the registry implementation that we could use to work around this (by using `GuessMIMEType`)

Actually, considering the Nexus response, this would ideally be worked around on the push side, by not trying to upload OCI and forcing conversion to v2s2.

**Comment by mtrmac** [comment]
… or, I guess, both. I’ll stop writing now.

**Comment by nalind** [comment]
As far as headers go, this may be of use:
```
# curl -v http://localhost:8080/v2/test/manifests/latest
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /v2/test/manifests/latest HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.65.3
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Wed, 06 Nov 2019 17:30:57 GMT
< Server: Nexus/3.19.1-01 (OSS)
< X-Content-Type-Options: nosniff
< Content-Security-Policy: sandbox allow-forms allow-modals allow-popups allow-presentation allow-scripts allow-top-navigation
< X-XSS-Protection: 1; mode=block
< Last-Modified: Wed, 06 Nov 2019 16:19:40 GMT
< Docker-Distribution-Api-Version: registry/2.0
< Content-Type: application/vnd.docker.distribution.manifest.v1+json
< Content-Length: 1509
< 
{
  "schemaVersion" : 1,
  "name" : "test",
  "tag" : "latest",
  "architecture" : "amd64",
  "fsLayers" : [ {
    "blobSum" : "sha256:1dbcab28ce46b65c0174e5e82658492107396fead31e9144c343e6bc96e471c7"
  }, {
    "blobSum" : "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
  }, {
    "blobSum" : "sha256:eb7c47c7f0fd0054242f35366d166e6b041dfb0b89e5f93a82ad3a3206222502"
  } ],
  "history" : [ {
    "v1Compatibility" : "{\"created\":\"2019-11-06T16:19:39.97193512Z\",\"docker_version\":null,\"architecture\":\"amd64\",\"config\":{\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"/bin/sh\"]},\"container\":null,\"os\":\"linux\",\"container_config\":null,\"id\":\"89da313c4c89da7857a30529b3f625deeea94225d49336a4404635ed02c9195b\",\"parent\":\"41405ad186cb9909596c393717c39233656342f9a04f3370435e9bb2e9ed015d\"}"
  }, {
    "v1Compatibility" : "{\"id\":\"41405ad186cb9909596c393717c39233656342f9a04f3370435e9bb2e9ed015d\",\"created\":\"2019-10-21T17:21:42.387111039Z\",\"Cmd\":{\"container_config\":\"/bin/sh -c #(nop)  CMD [\\\"/bin/sh\\\"]\"},\"parent\":\"7c17543de7107af2dde702b49c8cfd4980680207e669fccf589958c6b7b8edb9\",\"throwaway\":true}"
  }, {
    "v1Compatibility" : "{\"id\":\"7c17543de7107af2dde702b49c8cfd4980680207e669fccf589958c6b7b8edb9\",\"created\":\"2019-10-21T17:21:42.078618181Z\",\"Cmd\":{\"container_config\":\"/bin/sh -c #(nop) ADD file:fe1f09249227e2da2089afb4d07e16cbf832eeb804120074acd2b8192876cd28 in / \"}}"
  } ]
* Connection #0 to host localhost left intact

# curl -v -H Accept:application/vnd.oci.image.manifest.v1+json http://localhost:8080/v2/test/manifests/latest
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /v2/test/manifests/latest HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.65.3
> Accept:application/vnd.oci.image.manifest.v1+json
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Wed, 06 Nov 2019 17:33:11 GMT
< Server: Nexus/3.19.1-01 (OSS)
< X-Content-Type-Options: nosniff
< Content-Security-Policy: sandbox allow-forms allow-modals allow-popups allow-presentation allow-scripts allow-top-navigation
< X-XSS-Protection: 1; mode=block
< Last-Modified: Wed, 06 Nov 2019 16:19:40 GMT
< Docker-Distribution-Api-Version: registry/2.0
< Content-Type: application/vnd.docker.distribution.manifest.v1+json
< Content-Length: 1509
< 
{
  "schemaVersion" : 1,
  "name" : "test",
  "tag" : "latest",
  "architecture" : "amd64",
  "fsLayers" : [ {
    "blobSum" : "sha256:1dbcab28ce46b65c0174e5e82658492107396fead31e9144c343e6bc96e471c7"
  }, {
    "blobSum" : "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
  }, {
    "blobSum" : "sha256:eb7c47c7f0fd0054242f35366d166e6b041dfb0b89e5f93a82ad3a3206222502"
  } ],
  "history" : [ {
    "v1Compatibility" : "{\"created\":\"2019-11-06T16:19:39.97193512Z\",\"docker_version\":null,\"architecture\":\"amd64\",\"config\":{\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"/bin/sh\"]},\"container\":null,\"os\":\"linux\",\"container_config\":null,\"id\":\"89da313c4c89da7857a30529b3f625deeea94225d49336a4404635ed02c9195b\",\"parent\":\"41405ad186cb9909596c393717c39233656342f9a04f3370435e9bb2e9ed015d\"}"
  }, {
    "v1Compatibility" : "{\"id\":\"41405ad186cb9909596c393717c39233656342f9a04f3370435e9bb2e9ed015d\",\"created\":\"2019-10-21T17:21:42.387111039Z\",\"Cmd\":{\"container_config\":\"/bin/sh -c #(nop)  CMD [\\\"/bin/sh\\\"]\"},\"parent\":\"7c17543de7107af2dde702b49c8cfd4980680207e669fccf589958c6b7b8edb9\",\"throwaway\":true}"
  }, {
    "v1Compatibility" : "{\"id\":\"7c17543de7107af2dde702b49c8cfd4980680207e669fccf589958c6b7b8edb9\",\"created\":\"2019-10-21T17:21:42.078618181Z\",\"Cmd\":{\"container_config\":\"/bin/sh -c #(nop) ADD file:fe1f09249227e2da2089afb4d07e16cbf832eeb804120074acd2b8192876cd28 in / \"}}"
  } ]
* Connection #0 to host localhost left intact
}

# curl -v -H Accept:application/vnd.docker.distribution.manifest.v2+json http://localhost:8080/v2/test/manifests/latest
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /v2/test/manifests/latest HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.65.3
> Accept:application/vnd.docker.distribution.manifest.v2+json
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Wed, 06 Nov 2019 17:33:32 GMT
< Server: Nexus/3.19.1-01 (OSS)
< X-Content-Type-Options: nosniff
< Content-Security-Policy: sandbox allow-forms allow-modals allow-popups allow-presentation allow-scripts allow-top-navigation
< X-XSS-Protection: 1; mode=block
< Last-Modified: Wed, 06 Nov 2019 16:19:40 GMT
< Docker-Content-Digest: sha256:8b07856beee99763434701c1f785c1975b9211915902cc34781c7f1c6ef4972f
< Docker-Distribution-Api-Version: registry/2.0
< Content-Type: application/vnd.docker.distribution.manifest.v2+json
< Content-Length: 491
< 
* Connection #0 to host localhost left intact
{"schemaVersion":2,"config":{"mediaType":"application/vnd.oci.image.config.v1+json","digest":"sha256:24714781b4f3764fb9332eaa19c84a34af854e3eaf85ffacb87e4a8b422f3125","size":725},"layers":[{"mediaType":"application/vnd.oci.image.layer.v1.tar","digest":"sha256:eb7c47c7f0fd0054242f35366d166e6b041dfb0b89e5f93a82ad3a3206222502","size":2857626},{"mediaType":"application/vnd.oci.image.layer.v1.tar","digest":"sha256:1dbcab28ce46b65c0174e5e82658492107396fead31e9144c343e6bc96e471c7","size":48}]}
```

**Comment by mtrmac** [comment]
@vrothberg BTW it does not seem _completely_ unreasonable to me that we should not be that strict about MIME types. At the very least, it should be possible to copy images with recognized manifest MIME types and unknown (future) layer MIME types.  (The case for ignoring unknown manifest / config MIME types is admittedly much weaker.)

**Comment by vrothberg** [comment]
@mtrmac, I am completely open to relax the checks (and backport to v4). Would you open a PR with what you have in mind?

**Comment by ghglza** [comment]
From our perspective, a configuration option for relaxed MIME checks (where maybe strict is the default) would also be fine.

And a hint which registry implementations are OCI-compliant (resp. which are not!) in the docs might also be helpful... IMHO setting up a private registry is a very common use pattern during containerization in most organizations, and knowing about limitations of widespread components might save a lot of hassle.

**Comment by iinuwa** [comment]
> The corresponding Nexus bug seems to be https://issues.sonatype.org/browse/NEXUS-16947 , closed with “We can't see any reference about docker registries needing to be OCI compliant in the Docker spec. ”. That’s a bit demotivating.

FWIW, another issue ([NEXUS-21087](https://issues.sonatype.org/browse/NEXUS-21087)) has been opened to support OCI compliance in Nexus.

**Comment by fragfutter** [comment]
[NEXUS-21087](https://issues.sonatype.org/browse/NEXUS-21087) will be fixed in 3.23.0

**Comment by haircommander** [comment]
additionally, I believe @mtrmac is currently working on the relaxed checks in containers/image. is that correct?

**Comment by mtrmac** [comment]
OCI checks have been relaxed significantly; schema2 not currently — and I’m not at all sure that ignoring unrecognized MIME types of the manifest, but depending on contents of the manifest, makes sense. Auto-detecting the missing support during push would be cleaner.

Anyway, I am currently working on neither.
