### ISSUE TITLE
Add metric for CNI network setup time

### ISSUE THREAD

**Issue by mrunalp** [cri-o/cri-o#2906]
We want to be able to accurately measure and improve pod startup time. We should track the time it takes for CNI to set up the network namespace for a pod so we can improve the performance and help debug issues in running clusters.

cc: @smarterclayton

**Comment by baude** [comment]
@mrunalp i would love for us to coordinate performance of CNI as well.

**Comment by smarterclayton** [comment]
Excellent - this will help nail down why our p90 on pod sandbox create is over 10s
