### ISSUE TITLE
crio does not work correctly on fedora 31

### ISSUE THREAD

**Issue by Samet-MohamedAmin** [cri-o/cri-o#2923]
**Description**
I have recently installed crio on fedora silverblue 31 via dnf module, but crio does not work correctly.
``` bash
[ ~ ]$ crio --log-level debug
DEBU[2019-10-26 20:18:02.401489195+01:00] found valid runtime 'runc' for runtime_path '/usr/bin/runc'

FATA[2019-10-26 20:18:02.401859100+01:00] remove /var/run/crio/crio.sock: permission denied
```
``` bash
[ ~ ]$ sudo crio --log-level debug
DEBU[2019-10-26 20:18:09.053567296+01:00] found valid runtime 'runc' for runtime_path '/usr/bin/runc'
 
DEBU[2019-10-26 20:18:09.053954331+01:00] [graphdriver] trying provided driver "overlay" 
DEBU[2019-10-26 20:18:09.195912594+01:00] overlay test mount with multiple lowers succeeded 
DEBU[2019-10-26 20:18:11.171493228+01:00] overlay test mount indicated that metacopy is being used 
WARN[2019-10-26 20:18:11.417775753+01:00] Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled 
DEBU[2019-10-26 20:18:11.417856747+01:00] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=true 
INFO[2019-10-26 20:18:11.419261805+01:00] Found CNI network crio-bridge (type=bridge) at /etc/cni/net.d/100-crio-bridge.conf 
INFO[2019-10-26 20:18:11.419369295+01:00] Found CNI network 200-loopback.conf (type=loopback) at /etc/cni/net.d/200-loopback.conf 
INFO[2019-10-26 20:18:11.419529755+01:00] Found CNI network podman (type=bridge) at /etc/cni/net.d/87-podman-bridge.conflist 
DEBU[2019-10-26 20:18:11.429458201+01:00] seccomp status: true                         
DEBU[2019-10-26 20:18:11.432012047+01:00] Golang's threads limit set to 55980          
DEBU[2019-10-26 20:18:11.433560636+01:00] sandboxes: []                                
FATA[2019-10-26 20:18:11.433637376+01:00] Invalid character(s) found in prerelease "module_f31"
```

**Output of `crio --version`:**

```
[ ~ ]$ crio --version
crio version 1.14.9-1.module_f31+5133+e8343ec4
```
 **Addtional information**
```
[ ~ ]$ uname -a
Linux samet 5.3.6-300.fc31.x86_64 #1 SMP Mon Oct 14 12:26:42 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Samet-MohamedAmin** [comment]
similar problem:
https://bugzilla.redhat.com/show_bug.cgi?id=1754170

**Comment by rhatdan** [comment]
crio does not run rootless, You need to run it as root.

**Comment by rhatdan** [comment]
Were you intending to use podman?

**Comment by afbjorklund** [comment]
This is a packaging bug, it is inserting invalid characters into the semantic version:

https://src.fedoraproject.org/rpms/cri-o/blob/1.16/f/cri-o.spec#_75

```sh
sed -i 's/%{version}/%{version}-%{release}/' internal/version/version.go
```

It works OK if you remove the trailing `-1.module_f31+5133+e8343ec4` suffix...

**Comment by Samet-MohamedAmin** [comment]
> Were you intending to use podman?

I installed `cri-o` to run it as `minikube` runtime.

**Comment by Samet-MohamedAmin** [comment]
> This is a packaging bug, it is inserting invalid characters into the [semantic version](https://semver.org/):
> 
> https://src.fedoraproject.org/rpms/cri-o/blob/1.14/f/cri-o.spec#_76
> 
> ```shell
> sed -i 's/%{version}/%{version}-%{release}/' internal/version/version.go
> ```
> 
> It works OK if you remove the trailing `-1.module_f31+5133+e8343ec4` suffix...
> 
> As per the bug report(s) listed above, it's been this way since fedora 30 (Aug).
> 
> https://bugzilla.redhat.com/show_bug.cgi?id=1743017

Can it be fixed somehow?

**Comment by Samet-MohamedAmin** [comment]
As @afbjorklund reply, the problem does not seem to be related to the `cri-o` project but to fedora packaging.
There are already opened issues on the rpm package repository.

**Comment by afbjorklund** [comment]
The ugly workaround that I ended up with was patching the binary.

Couldn't get `sed` to cooperate, so ended up using `perl` instead:

```
# dnf install https://kojipkgs.fedoraproject.org//packages/cri-o/1.15.2/1.module_f30+6830+9be88745/aarch64/cri-o-1.15.2-1.module_f30+6830+9be88745.aarch64.rpm
# perl -p0e "s/\.module_f30/.alpha.0.30/g;s/\+6830/.6830/g;s/\+9be88745/.90088745/g" -i /usr/bin/crio
```

You might want to use a different package, but principally the same.

Basically changing the fedora release into something that parses...

https://koji.fedoraproject.org/koji/packageinfo?packageID=24240

**Comment by afbjorklund** [comment]
> There are already opened issues on the rpm package repository.

I think that @lsm5 is aware of this, lots of problems with "modules"

https://docs.fedoraproject.org/en-US/modularity/

**Comment by Samet-MohamedAmin** [comment]
> > There are already opened issues on the rpm package repository.
> 
> I think that @lsm5 is aware of this, lots of problems with "modules"
> 
> https://docs.fedoraproject.org/en-US/modularity/

Sadly I can't install `cri-o` on fedora from default repositories only via modules.
I'll try with the local rpm.

**Comment by afbjorklund** [comment]
> Sadly I can't install `cri-o` on fedora from default repositories only via modules.

Modules _are_ the new default repositories. Unfortunately they don't work (yet).

But once the module and the package _works_, it should be straightforward:

```
# dnf module enable cri-o:1.15
# dnf install cri-o
```

See https://github.com/cri-o/cri-o.io/pull/36

**Comment by afbjorklund** [comment]
Looks like the fedora package also forgets to pass the git commit to the build system:

```sh
export GIT_COMMIT=%{commit0}
```

Instead it is using an internal commit from the build system, showing _that_ in crio version:

```
+ cd cri-o-6a4b481e35f2b11e5b3ae9b930991cfcac3d687d
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ /usr/bin/git init -q
+ /usr/bin/git config user.name rpm-build
+ /usr/bin/git config user.email '<rpm-build>'
+ /usr/bin/git add .
+ /usr/bin/git commit -q --allow-empty -a --author 'rpm-build <rpm-build>' -m 'cri-o-1.16.0 base'
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
```

```sh
GO111MODULE=on go build -mod=vendor -ldflags '-s -w -X main.gitCommit="84af0bc842f8a18c7a12cf7043a32a965f5dcae7-dirty" -X main.buildInfo=1571616000' -tags "    seccomp selinux" -o bin/crio github.com/cri-o/cri-o/cmd/crio
GO111MODULE=on go build -mod=vendor -ldflags '-s -w -X main.gitCommit="84af0bc842f8a18c7a12cf7043a32a965f5dcae7-dirty" -X main.buildInfo=1571616000' -tags "    seccomp selinux" -o bin/crio-status github.com/cri-o/cri-o/cmd/crio-status
```

```
crio version 1.16.0-0.1.rc1.git6a4b481.module_f31+6837+7e34758d-rc1
commit: "84af0bc842f8a18c7a12cf7043a32a965f5dcae7-dirty"
```

Will try to add to bugzilla.

@lsm5: need patches ?
