### ISSUE TITLE
v1.16.0 Toml key host_ip=[] causes bad validation of crio.conf

### ISSUE THREAD

**Issue by ashayshub** [cri-o/cri-o#2952]
**Description**

Using OS: centos 7 on a KVM vm

**Steps to reproduce the issue:**
1. yum install oci-umount ; yum install podman
2. Download cri-o tar.gz version 1.16.0 from github release download page
3. untar cri-o tar.gz
4. export DESTDIR="" and export PREFIX="/usr"
5. make install
6. Set conmon binary path in conman="" key in /etc/crio/crio.conf
7. systemctl daemon-reload && systemctl start crio

**Describe the results you received:**

Error message:
Nov  6 22:26:18 k8s-m crio: unable to decode configuration /etc/crio/crio.conf: toml: cannot load TOML value of type []interface {} into a Go string

**Describe the results you expected:**

● crio.service - Container Runtime Interface for OCI (CRI-O)
   Loaded: loaded (/usr/lib/systemd/system/crio.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-11-06 22:30:01 EST; 2s ago
     Docs: https://github.com/cri-o/cri-o
 Main PID: 20159 (crio)
   CGroup: /system.slice/crio.service
           └─20159 /usr/bin/crio

Nov 06 22:30:01 k8s-m systemd[1]: Starting Container Runtime Interface for OCI (CRI-O)...
Nov 06 22:30:01 k8s-m systemd[1]: Started Container Runtime Interface for OCI (CRI-O).

**Additional information you deem important (e.g. issue happens only occasionally):**

Error dissappears if `host_ip` key in the `/etc/crio/crio.conf` is commented/hashed

**Output of `crio --version`:**
crio --version
crio version 1.16.0

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by ashayshub** [comment]
** More Information **
1. I compiled `bin/crio` from the source code v1.16.0. It worked with the `host_ip=[]` parameter
2. I downloaded the v1.16.0, it gave error parsing the toml configuration for `host_ip=[]` parameter

Thus, the `bin/crio-x86_64-static-musl` binary (which links to `bin/crio`) is probably not compiled from the source code tagged v1.16.0.

**Comment by saschagrunert** [comment]
Hey @ashayshub, the `host_ip=[…]` configuration should be not available for 1.16.x, so it should be a simple string. Your first comment indicates that you've been using the source code and not the bundle tarball, right? Are you sure that you downloaded the sources of the 1.16.0 tag?

**Comment by ashayshub** [comment]
@saschagrunert I just reverified the setup. The error I received in the first place is because the [prepackaged](https://github.com/cri-o/cri-o/releases/download/v1.16.0/crio-v1.16.0.tar.gz) `etc/crio.conf` has `host_ip=[]` which gets copied as `/etc/crio/crio.conf` on `make install`  (export DESTDIR="" and export PREFIX="/usr") and gives out error. 

I just verfieied by freshly compiling the v1.16.0 source code and there the binary expects `host_ip=""` as your have rightly said.

**Comment by saschagrunert** [comment]
Ah thanks for the hint, I'll updated the release tarball which should now contain the correct configuration. :+1:
