### ISSUE TITLE
1.16.0 release not available in PPA

### ISSUE THREAD

**Issue by marshallford** [cri-o/cri-o#2963]
This is not a bug report or feature request but rather just an observation. The `1.16.0` release was cut a week ago and the package for Debian/Ubuntu is not present in the Project Atomic archive.

Thanks.

**Comment by Ehekatl** [comment]
still waiting for the release...
I'm running 1.15 release with k8s 1.16 now
is it recommended? 
hope it's more stable than the latest, not sure it's fully compatible with k8s 1.16 or not

**Comment by haircommander** [comment]
the CRI guarentees n-1 compatibility, so you should be alright. That said, @lsm5 should be getting to packaging 1.16 soon, so stay tuned. Thanks for the patience folks!

**Comment by Prodian0013** [comment]
k8s 1.17 RC1 is already out while crio packages for 1.16.x havent been updated.  Does crio intend to stay in step with k8s releases or continue to fall further behind?

**Comment by haircommander** [comment]
@Prodian0013 We are releasing in lock step, but have trouble keeping up with packaging for each platform users expect it from. We always welcome volunteers for packaging, and will work on a solution that builds CRI-O everywhere as soon as possible. Sorry for the delay. @lsm5 in the meantime, do you have an update for the PPA?

**Comment by lsm5** [comment]
I'm transitioning to opensuse's OBS for shipping deb and ubuntu packages, and I'll ship cri-o in there too. Still wip and I'm out this week, so should have more progress next week.

See: https://github.com/containers/libpod/issues/1742#issuecomment-555061785

**Comment by matthias50** [comment]
> the CRI guarentees n-1 compatibility, so you should be alright. That said, @lsm5 should be getting to packaging 1.16 soon, so stay tuned. Thanks for the patience folks!

I saw this and I did try out the crio 1.15.2 on k8s 1.16 and the results were not great.  From what I can tell, service account token mounting completely broke which messed up all kinds of stuff. I switched to docker as a test and the issue went away. So from where I sit, using CRI-O 1.15 with k8s 1.16 seems like a non-starter.

**Comment by lsm5** [comment]
I've switched to [OBS](https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable) for shipping deb packages. To get cri-o 1.16 on ubuntu, see below.

For xUbuntu 19.10 run the following:
Keep in mind that the owner of the key may distribute updates, packages and repositories that your system will trust (more information).

```sudo sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_19.10/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_19.10/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt-get update
sudo apt-get install cri-o-1.16
```

For xUbuntu 19.04 run the following:
Keep in mind that the owner of the key may distribute updates, packages and repositories that your system will trust (more information).

```sudo sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_19.04/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_19.04/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt-get update
sudo apt-get install cri-o-1.16
```

For xUbuntu 18.04 run the following:
Keep in mind that the owner of the key may distribute updates, packages and repositories that your system will trust (more information).

```sudo sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_18.04/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt-get update
sudo apt-get install cri-o-1.16
```

**Comment by lsm5** [comment]
https://github.com/cri-o/cri-o/pull/3114

**Comment by haircommander** [comment]
https://github.com/cri-o/cri-o/pull/3114 has merged, closing this as such. If there are issues with the new installation method, please open a new issue :smile: thanks for the patience everyone, and huge thanks to @lsm5 for getting this done :tada:
