### ISSUE TITLE
make install rebuilds go binaries

### ISSUE THREAD

**Issue by mythi** [cri-o/cri-o#2978]
**Description**

The Go binaries (`bin/crio` and `bin/crio-status`) are rebuilt when running `make install`.

**Steps to reproduce the issue:**
1. `make GIT_COMMIT=brokenbuild`
2. `bin/crio -v`
3. `mkdir /tmp/crio-bins`
4. `make install PREFIX=/tmp/crio-bins`
5. `/tmp/crio-bins/bin/crio -v`

**Describe the results you received:**

1. make rebuilds Go binaries
2. `GIT_COMMIT` setting is lost after `make install`

**Describe the results you expected:**

1. `make install` runs `install` commands only
2. `GIT_COMMIT`  (or any other setting specified during build time is preserved)

**Additional information you deem important (e.g. issue happens only occasionally):**

The workaround is to specify the same build time `make` overrides for `make install` too but the build is still sub-optimal.

**Comment by saschagrunert** [comment]
Thanks for the report, @mythi I see your point. I'm taking care of this in https://github.com/cri-o/cri-o/compare/master...openSUSE:install-fix
