### ISSUE TITLE
Static Linking Not Supported in RHEL 8

### ISSUE THREAD

**Issue by ccravens** [cri-o/cri-o#2993]
When building cri-o from source, it enforces static linking for example in the pause/Makefile:

```
src = $(wildcard *.c)
obj = $(src:.c=.o)
override LIBS +=
CFLAGS ?= -std=c99 -Os -Wall -Wextra
override CFLAGS += -static
../bin/pause: $(obj) | ../bin
        $(CC) -o $@ $^ $(CFLAGS) $(LIBS)
../bin:
        mkdir -p $@
.PHONY: clean
clean:
        rm -f $(obj) ../bin/pause
```

However, static linking is not supported in RHEL 8: https://access.redhat.com/articles/rhel8-abi-compatibility

```
Static Linking with the C/C++ Runtime
Static linking with the C/C++ runtime is not supported. This includes linking with any files that are part of the glibc-static or libstdc++-static packages. You may choose to link statically, but the resulting application binaries may fail to operate if any package in the installation is changed.
```

This means that glibc-static is not available for install in RHEL 8. We can build on RHEL 8 by commenting out the lines that force a static build:

```
- override CFLAGS += -static
+ #override CFLAGS += -static
```

**Steps to reproduce the issue:**
1. Run make to build cri-o on RHEL 8

**Describe the results you received:**
```
[ec2-user@a cri-o]$ make
mkdir -p "/home/ec2-user/cri-o/_output/src/github.com/cri-o"
ln -s "/home/ec2-user/cri-o" "/home/ec2-user/cri-o/_output/src/github.com/cri-o/cri-o"
touch "/home/ec2-user/cri-o/_output/.gopathok"
GO111MODULE=on go build -mod=vendor -ldflags '-s -w -X main.gitCommit="0c5540dabeba426e514e870754b395e8569a805b-dirty" -X main.buildInfo=1574741461' -tags "containers_image_ostree_stub  exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper libdm_no_deferred_remove containers_image_openpgp  " -o bin/crio github.com/cri-o/cri-o/cmd/crio
make -C pause
make[1]: Entering directory '/home/ec2-user/cri-o/pause'
cc -std=c99 -Os -Wall -Wextra -static   -c -o pause.o pause.c
cc -o ../bin/pause pause.o -std=c99 -Os -Wall -Wextra -static 
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:9: ../bin/pause] Error 1
make[1]: Leaving directory '/home/ec2-user/cri-o/pause'
make: *** [Makefile:117: bin/pause] Error 2
```

**Describe the results you expected:**
I expect cri-o to build successfully without having to manually edit the Makefiles. Perhaps option we can pass to the make command that enables static vs dynamic linking?

**Additional information you deem important (e.g. issue happens only occasionally):**
Static linking does not seem to be supported in RHEL 8

**Output of `crio --version`:**

```
N/A - trying to build from source
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS EC2 RHEL 8.0

**Comment by saschagrunert** [comment]
Hey @ccravens, I see your point. I'm not sure if you need the pause binary at all in your use case, and we're currently thinking about removing it completely.

Do need the bause binary for anything? We usually use a pause image like `k8s.gcr.io/pause:3.1`.

Relates to: https://github.com/cri-o/cri-o/issues/2444

**Comment by ccravens** [comment]
Hello @saschagrunert and thank you for looking into this and the PR! Yes, the pause binary is the one that I referenced, however it seems that there are a lot of references to static linking throughout the crio build as well.

For example, in the ./bundle/Makefile all builds (including the crio binary) are called *-static-glibc. The glibc-static dependency is referenced in many places such as the Vagrantfile, ./contrib/test/integration/system-packages.yml and even specified as a dependency in the ./tutorials/setup.md markdown file.

I'm thinking that this issue might be deeper and there may be more dependencies on static linking than just the pause binary. However, I can  get it to build successfully if I comment out the "override CFLAGS += -static" in both the pinns/Makefile and pause/Makefile, so it may be just that easy!

Thanks!

**Comment by saschagrunert** [comment]
You're welcome :) The contents of the `bundle/` directory are only used for building a static binary bundle via the nix package, which we provide for every release. So there is no need to build the bundle when you don't need it.
