### ISSUE TITLE
cgroups mounted differently for privileged containers

### ISSUE THREAD

**Issue by nalind** [cri-o/cri-o#2996]
It looks like we've changed how we're running privileged containers and pods.  In 1.14, runc would be given these in its configuration for a privileged container:
```
        {
            "destination": "/sys",
            "type": "sysfs",
            "source": "sysfs",
            "options": [
                "nosuid",
                "noexec",
                "nodev",
                "rw"
            ]
        },
	{
            "destination": "/sys/fs/cgroup",
            "type": "cgroup",
            "source": "cgroup",
            "options": [
                "nosuid",
                "noexec",
                "nodev",
                "relatime",
                "rw"
            ]
        },
```
An unprivileged container would get the same mounts, but marked read-only.

In 1.16, a privileged container instead gets
```
        {
            "destination": "/sys",
            "type": "bind",
            "source": "/sys",
            "options": [
                "nosuid",
                "noexec",
                "nodev",
                "rw",
                "rbind"
            ]
        }
```
This appears to have been changed as a bug fix in https://github.com/cri-o/cri-o/pull/2627, but it breaks applications which are accustomed to reading control group settings that affect them from the root of cgroup hierarchies (e.g. `/sys/fs/cgroup/memory/memory.max_usage_in_bytes`).

In OpenShift we currently run builds with privileges, so checks executed by RUN instructions are getting tripped up by this (test disabled in https://github.com/openshift/origin/pull/24001, investigation in https://github.com/openshift/origin/pull/24157 and https://github.com/openshift/origin/pull/24174).

**Comment by haircommander** [comment]
this should be fixed with #2997. please reopen if you disagree
