### ISSUE TITLE
[Discussion] packet.net infrastructure

### ISSUE THREAD

**Issue by saschagrunert** [cri-o/cri-o#3008]
I played around with the packet.net access we've got from the CNCF, looks very promising from an infrastructure perspective. We have now basically any kind of flexibility since we're able to spawn bare-metal machines.

The big question is now, how to integrate / migrate to it?

I would assume that we still want to use the currently used prow instance, but integrate some packet.net machines for faster integration/e2e testing, right? This seems not that trivial to me, since the current ansible based test setup deployment is targeting AWS instances, right?

We could built-up a parallel system, which would be easier to maintain for us. But this means that we would have to maintain the whole stack.

WDYT?

**Comment by haircommander** [comment]
So the jenkins server we use to spawn all of the aws vms is being (very slowly) deprecated. I would personally be in favor of mirroring all tests we have on packet net, getting them stable, then moving there entirely (kind of like what we did travis->circleci). 

In terms of implementing our own solution, I agree it's a drag, but it's also very difficult making changes as is, as there are 4 different repositories all over the place that need changes, and in lots of those places no one here has permission to merge.

**Comment by haircommander** [comment]
An advantage of having our own solution would be tailoring it to CRI-O's needs (the biggest that comes to mind is pinning the needs of the release branches so dependencies don't slide when we update stuff for master)

**Comment by rhatdan** [comment]
SGTM
@mrunalp @umohnani8 WDYT?

**Comment by saschagrunert** [comment]
Okay, I'd be happy to support you with the decision for going our own way with packet.net. Since packet.net provides only the infrastructure (which is pretty awesome), I'd suggest to:

- Host our own Prow instance on top of a small Kubernetes cluster (1 node for now)
- Setup a Jenkins server inside this cluster
- Setup Jenkins nodes for all target platforms: RHEL, Fedora, SLES, ...
- Setup a CI repo inside this organization where we can develop the prow jobs

WDYT?

Since packet only supports RHEL7 out of the box:
We're able to boot via a custom iPXE script in packet, which needs to be publicly available. Do you have something like this for RHEL?

**Comment by mrunalp** [comment]
Sounds good to me.

**Comment by mrunalp** [comment]
I do think that we shouldn't underestimate the effort to run CI though. We have a team that keeps our CI functioning 24/7 :) So this could probably be a parallel thing that we run for a while before we have confidence that we can keep it up and running.

**Comment by saschagrunert** [comment]
> I do think that we shouldn't underestimate the effort to run CI though. We have a team that keeps our CI functioning 24/7 :) So this could probably be a parallel thing that we run for a while before we have confidence that we can keep it up and running.

Yes I agree. :+1: 

I created a single node cluster on top of Ubuntu 18.04 (via kubeadm) and installed prow. If we now move forward, we would have to invite the [cri-o-ci](https://github.com/cri-o-ci) user (created by me) into the organization.

Necessary cluster bootstrap information are available on the node itself, but I propose that we create a private repo where I can put some credentials and notes about the setup in. Beside that we would need another public repo for the prowjob definitions.

Another question is regarding TLS: Since we have no domain associated with the [node](https://app.packet.net/devices/b5cca120-17bf-4203-b660-fbcd58a7f6e5) it would only be possible to use a self-signed certificate which might be rejected by GitHub. Do we want to use TLS? Do we have a chance to point something like `ci.cri-o.io` to that node?

**Comment by saschagrunert** [comment]
Basic prow seems to work already, I setup a test org to play around with the setup: 
https://github.com/cri-o-ci-tests/repository/pull/5

**Comment by saschagrunert** [comment]
I think we need a GCS bucket to run jobs in kubernetes: https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#configure-cloud-storage

**Comment by saschagrunert** [comment]
> I think we need a GCS bucket to run jobs in kubernetes: https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#configure-cloud-storage

I requested a bucket in https://github.com/kubernetes/test-infra/issues/15569

**Comment by saschagrunert** [comment]
I guess this can be closed now.
