### ISSUE TITLE
Containers are stuck creating waiting on image pull that already completed

### ISSUE THREAD

**Issue by benceszikora** [cri-o/cri-o#3013]
**Description**
We have some pods getting stuck in ContainerCreating. When I describe the pod I can see that it says it's still pulling the image (but didn't fail). This can be stuck forever, minutes, hours after trying to create the pod.

When I login to the node the pod is creating on and try to do a `crictl pull $image`, it says the image is already up to date.

I don't see any relevant log messages in the cri-o logs or anywhere else.

Is this a known issue, if not what's the best way to debug this?

**Steps to reproduce the issue:**
I don't have a reliable way to reproduce the issue, but it seems to happen multiple times on a single node.

**Describe the results you received:**
The pod is created.

**Describe the results you expected:**
The pod is stuck in `ContainerCreating`

**Output of `crio --version`:**
```
crio version 1.16.0
commit: "fa99ff4ae2aa45115bf3c6bb33db07191db2518e-dirty"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Vanilla kubernetes 1.16.2

**Comment by haircommander** [comment]
@vrothberg @nalind @mtrmac PTAL

**Comment by vrothberg** [comment]
Haven't seen this particular symptom yet. @benceszikora, if possible, could you share these logs?

**Comment by vrothberg** [comment]
Is it something you've seen multiple times already or was it the first encounter?

**Comment by benceszikora** [comment]
I have attached the logs from around that time. We have seen this multiple times already, I believe even on 1.15

[crio-stuck.txt](https://github.com/cri-o/cri-o/files/3917039/crio-stuck.txt)

**Comment by benceszikora** [comment]
Actually, looking at this now, there were no logs for 4 hours prior to this at all, which is suspicious.

**Comment by vrothberg** [comment]
Thanks, @benceszikora! I am currently fighting other fires but will come back to this asap.

**Comment by vrothberg** [comment]
> [crio-stuck.txt](https://github.com/cri-o/cri-o/files/3917039/crio-stuck.txt)

Back from the holidays. I had a look at these logs but they don't provide any insight to me (they're very short).

@benceszikora what's the host environment and which binaries are you using? `fa99ff4ae2aa45115bf3c6bb33db07191db2518e-dirty` seems suspicious and indicates that the git repositories was dirty at build time.

**Comment by benceszikora** [comment]
@vrothberg We're running on RHEL 7.5. Since there are no rpms released for it we built our own from source at the 1.16.0 release tag (https://github.com/cri-o/cri-o/commit/fa99ff4ae2aa45115bf3c6bb33db07191db2518e)

**Comment by vrothberg** [comment]
@benceszikora, could you update CRI-O to v1.16.2 and check if you're still seeing the issue? The `-dirty` suffix indicates that the git repository was dirty at the time of compilation. Just to be sure, could you check via `git status` and `git diff` if any files have been changed?

**Comment by haircommander** [comment]
hey @benceszikora are you still seeing this issue? @vrothberg do you think https://github.com/cri-o/cri-o/pull/3409 would help?

**Comment by vrothberg** [comment]
> @vrothberg do you think #3409 would help?

The symptoms look different to me. The symptoms of this issue indicate that the image has been pulled successfully but, for some reason, the pod doesn't fire.

But it's hard to make conclusions without logs or ideally a reproducer.
