### ISSUE TITLE
Question: restrict credentials in global auth for a given namespace or even image

### ISSUE THREAD

**Issue by Martin-Weiss** [cri-o/cri-o#3056]
We have to use global_auth for our kubernetes deployment as the images can only be retrieved from the on-premise registry with a given authentication. So we use the global_auth to add these.

Unfortunately these credentials are also used "automatically" for all other image pulls that are done through kubernetes later on (or via crictl pull) in case no other registry credentials are given.

Would it be possible to restrict the usage of registry credentials given via global_auth to a specific registry namespace or even some images so that all other pull requests for other images in the same or other namespace do not use these credentials?

Maybe it would be possible to enhance the global_auth in a way that we can add a namespace or even image name to the registry sting or add an other variable to the given credentials?

Just as a quick idea:

A default global_auth json looks like this:
```
{
        "auths": {
                "registry.domain.com:5000": {
                        "auth": "username:password"
                }
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/19.03.1 (linux)"
        }
```

But probably we can enhance crio to allow this to be restricted i.e. by specifying the namespace and image with additional variables or by adding it to the registry i.e.:

```
{
        "auths": {
                "registry.domain.com:5000/namespace/*": {
                        "auth": "username:password"
                }
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/19.03.1 (linux)"
        }
```

or

```
{
        "auths": {
                "registry.domain.com:5000": {
                        "auth": "username:password"
                }
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/19.03.1 (linux)"
        },
        "namespace": {
                "/namespace/*"
        }
```

Thoughts?

**Comment by haircommander** [comment]
Unfortunately, this is more of an issue with the kubelet. CRI-O has no idea about container namespaces, and couldn't decide whether an image should be pulled with creds based on namespace.

global_auth is really best used for mirrored registries (which bypasses the kubelet). If you need the mirroring functionality, then you're not able to only send the credentials sometimes. If you don't need the mirroring functionality, I would pass those credentials through the kubelet instead (i.e. have the pull spec of the pod specify your on-prem registry directly, and link the credentials with a service account)

**Comment by haircommander** [comment]
I suppose it could be possible to only pass creds when searching for a given image. that's more of an issue for `github.com/containers/image` though, CRI-O's image handling library :smile:

**Comment by haircommander** [comment]
can this issue be closed @Martin-Weiss

**Comment by Martin-Weiss** [comment]
Yes - I believe we are fine.. Thanks!
