### ISSUE TITLE
CRI-O fails to start container due to missing log directory

### ISSUE THREAD

**Issue by rancid-racer** [cri-o/cri-o#3062]
---------------------------------------------------
GENERAL SUPPORT INFORMATION
---------------------------------------------------

The GitHub issue tracker is for bug reports and feature requests.
General support for **CRI-O** can be found at the following locations:

- IRC - #cri-o channel on irc.freenode.org
- Slack - kubernetes.slack.com #sig-node channel
- Post a question on StackOverflow, using the CRI-O tag

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

**Description**

Creating a container following the sandbox example for crictl from https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/crictl.md fails to start the container.  Checking logs I found that journalctl was reporting a no such file or directory.  If I update the pod and container to not specify the log directory the containers start in the pods successfully.   This has been impacting the ability to start kubernetes with CRI-O runtime

**Steps to reproduce the issue:**
1. Bare minimum install of CENTOS 7.7.1908
2. Add repo for CRI-O from cbs.centos.org/repos/paas7-crio-115-release
3. yum install cri-o
4. add repo for kubernetes from packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
5. yum install cri-tools
6. disable swap
7. start cri-o service
8. create pod : crictl runp pod-config.json
9. create container : crictl create $POD_ID container-config.json pod-config.json

**Describe the results you received:**
container does not start with following error
FATA[0000] Creating container failed: rpc error: code = Unknown desc = exit status 1: write child: broken pipe

**Describe the results you expected:**
Have a running container

**Additional information you deem important (e.g. issue happens only occasionally):**
Edited pod config to not specify /tmp as log_directory
Edited container config to use log_path as busybox-0.log instead of busybox/0.log

**Output of `crio --version`:**

```
crio version 1.15.1-2.el7
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

running on bare metal install of INTEL NUC5CPYH

**Comment by rancid-racer** [comment]
Exact error from journalctl -u crio:
crio[1307]: [common:e]: Failed to open log file No such file or directory

**Comment by haircommander** [comment]
can I see the pod config and container config?

**Comment by haircommander** [comment]
(I lied about the labels, I don't think this is packaging)

**Comment by rancid-racer** [comment]
working configs:
pod-config.json
`
{
	"metadata": {
		"name" : "nginx-sandbox",
		"namespace" : "default",
		"attempt" : 1,
		"uid" : "hdishd83djaidwnduwk28bcsb"
	},
	"linux": {
	}
}
`

working conainer-config.json

`
{
	"metadata": {
		"name": "busybox"
	},
	"image": {
		"image" : "busybox"
	},
	"command" : [ "top" ],
	"log_path": "busybox-0.log",
	"linux": {
	}
}
`

**Comment by rancid-racer** [comment]
Tested with pod config 
```
{
	"metadata": {
		"name" : "nginx-sandbox",
		"namespace" : "default",
		"attempt" : 1,
		"uid" : "hdishd83djaidwnduwk28bcsb"
	},
	"log_directory": "/tmp",
	"linux": {
	}
}
```
This also seems to work fine using the above container config.  Not sure if this is a bug or an issue with the container config documentation where log_path cannot contain a subdirectory

**Comment by rancid-racer** [comment]
Based on examples in https://github.com/kubernetes-sigs/cri-tools/tree/master/docs/examples it looks like it is a documentation error for crictl as they use busybox.0.log in the actual example file.

**Comment by haircommander** [comment]
> working configs:
> pod-config.json
> 
> ```
> {
> 	"metadata": {
> 		"name" : "nginx-sandbox",
> 		"namespace" : "default",
> 		"attempt" : 1,
> 		"uid" : "hdishd83djaidwnduwk28bcsb"
> 	},
> 	"linux": {
> 	}
> }
> ```
> 

sorry, is this the failing config or one that works? If it's the failing one, what's the log_path? I don't see it specified

**Comment by rancid-racer** [comment]
For clarification, the pod config wasn't the issue.  I isolated it to being a / character in the container config for log_path indicating a subfolder.  I cannot be sure if it was intended to use folders in the container log_path parameter in crictl and who's responsibility it is to handle that.

**Comment by mrunalp** [comment]
@rancid-racer Thanks!
