### ISSUE TITLE
compilation fails on redhat8 

### ISSUE THREAD

**Issue by milind69** [cri-o/cri-o#3087]
**Description**

**Steps to reproduce the issue:**
1. git clone https://github.com/cri-o/cri-o
2.cd crio-o
3.make 

**Describe the results you received:**
make fails  with error 
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status

**Describe the results you expected:**
clean build with no errors 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `cc --version`:**
 cc --version
cc (GCC) 8.3.1 20190507 (Red Hat 8.3.1-4)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMware - VM

**Comment by milind69** [comment]
log message when it fails 
[root@icplxvm23 cri-o]# make
touch "/kube/go/.gopathok"
GO111MODULE=on go build --mod=vendor -ldflags '-s -w -X main.gitCommit="b98778d524f37737ad1385f8cddcfebbcf4bf4c7" -X main.buildInfo=1578515050' -tags "containers_image_ostree_stub  exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper libdm_no_deferred_remove containers_image_openpgp seccomp selinux" -o bin/crio github.com/cri-o/cri-o/cmd/crio
GO111MODULE=on go build --mod=vendor -ldflags '-s -w -X main.gitCommit="b98778d524f37737ad1385f8cddcfebbcf4bf4c7" -X main.buildInfo=1578515098' -tags "containers_image_ostree_stub  exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper libdm_no_deferred_remove containers_image_openpgp seccomp selinux" -o bin/crio-status github.com/cri-o/cri-o/cmd/crio-status
make -C pinns
make[1]: Entering directory '/kube/m/cri-o/pinns'
cc -std=c99 -Os -Wall -Wextra -static   -c -o pinns.o pinns.c
cc -o ../bin/pinns pinns.o -std=c99 -Os -Wall -Wextra -static
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status

**Comment by milind69** [comment]
[root@icplxvm23 cri-o]# uname -r
4.18.0-147.0.3.el8_1.x86_64

[root@icplxvm23 cri-o]# rpm -qa gcc

gcc-8.3.1-4.5.el8.x86_64
[root@icplxvm23 cri-o]#

cat /etc/redhat-release
Red Hat Enterprise Linux release 8.1 (Ootpa)

**Comment by dougsland** [comment]
Hi @milind69, I cannot reproduce the report but my guess is that you are missing glibc-static.

At moment, our official guide doesn't mention about codeready-builder-for-rhel-8-x86_64-rpms repo. So I would suggest to try:
 
# subscription-manager repos --enable=codeready-builder-for-rhel-8-x86_64-rpms
# dnf install glibc-static 
<try to do a make again>

You can see the full list of packages for rhel8 here:
https://github.com/cri-o/cri-o/blob/master/tutorials/setup.md

**Comment by milind69** [comment]
Greetings

Is it necessary to statically compile it? I had opened case with Redhat ,
they gave me same rpm. Redhat saying avoid building statically.
Also is there any know issue cri-o working with calico? My calico kub
controller not going in running state.

**Comment by dougsland** [comment]
Hi @milind69, in such case, having a subscription with Red Hat and installing/updating via rpm (yum/dnf) helps you to avoid building cri-o every single release, probably that's the main reason the support shared to avoid building statically. I am not aware of calico issue so far. We would need more information about your env to try a reproducer. The error logs might help us to identify what's going on as well.

**Comment by milind69** [comment]
I will open a case with details, thanks for help
We can close this one for staitc building

**Comment by dougsland** [comment]
Unfortunately, I can't close the ticket. Please next time in github, close for us. Thanks!

**Comment by milind69** [comment]
Will do, sorry for asking , new to kubernetes world
