### ISSUE TITLE
MemoryUsage.WorkingSetBytes should take total_inactive_file into consideration

### ISSUE THREAD

**Issue by AkihiroSuda** [cri-o/cri-o#3106]
containerd/CRI defines workingset as `usage - total_inactive_file`:

https://github.com/containerd/cri/blob/982e767745a9b0c8ea5f82d9795ab3c37f21c0f5/pkg/server/container_stats_list_unix.go#L84-L96

OTOH, CRI-O doesn't seem taking `total_inactive_file` into consideration:
https://github.com/cri-o/cri-o/blob/3314d8abfd80132bf89e408384ff6683b9799e5e/server/container_stats.go#L42

**Comment by saschagrunert** [comment]
Hey @AkihiroSuda, thanks for the hint. I'll check how to improve that and align with containerd.
