### ISSUE TITLE
crictl images shows --all images by default

### ISSUE THREAD

**Issue by afbjorklund** [cri-o/cri-o#3149]
Including any intermediate build images. Unlike the dockershim, which hides them by default...

That is, "crictl images" shows "docker images" on Docker but "podman images --all" with CRI-O.

When building images on the kubernetes master node, like minikube, this looks kinda messy.

See https://github.com/kubernetes/minikube/issues/6350 for details

**Comment by haircommander** [comment]
@vrothberg @mtrmac PTAL, should we be filtering images that don't have fully qualified names in the output?

**Comment by vrothberg** [comment]
Here's the relevant code in libpod:

```golang
// If all is false and the image doesn't have a name, check to see if the top layer of the image is a parent
// to another image's top layer. If it is, then it is an intermediate image so don't print out if the --all flag
// is not set.                 
isParent, err := img.IsParent(ctx)                          
if err != nil {                                             
        logrus.Errorf("error checking if image is a parent %q: %v", img.ID(), err)
}                                     
if !opts.all && len(img.Names()) == 0 && isParent {                          
        continue                                              
}                        
```

**Comment by saschagrunert** [comment]
I'm wondering what the better strategy is in terms of the kubelet. I would expect that the image GC removes unused images/layers from time to time. Beside that the scheduler takes the images into account when it comes to scoring the nodes. 

Generally I don't think that we should add more logic on top of that within CRI-O.

**Comment by mtrmac** [comment]
To the extent `crictl` is used to debug node/Kubelet issues/state, it must be _possible_ to see the full image list that Kubelet receives. As to whether it should be the _default_ output, I don’t have a strong opinion.

**Comment by haircommander** [comment]
as mentioned in https://github.com/cri-o/cri-o/pull/3892#issuecomment-648150305

I don't think the intermediate layers should be exposed by CRI-O. I'm fairly certain it can't be the kubelet that got them there (probably a build happened on the node) and I don't think it should be the responsibility of the kubelet to GC them (nor will it know what do do with layers that don't match a digest/name:tag)

If a user wants to debug images on the node, with the full scope of layers, they should use podman or buildah to show the intermediate layers IMO (they put them there in the first place)

WDYT @saschagrunert @mtrmac @vrothberg

**Comment by saschagrunert** [comment]
> as mentioned in [#3892 (comment)](https://github.com/cri-o/cri-o/pull/3892#issuecomment-648150305)
> 
> I don't think the intermediate layers should be exposed by CRI-O. I'm fairly certain it can't be the kubelet that got them there (probably a build happened on the node) and I don't think it should be the responsibility of the kubelet to GC them (nor will it know what do do with layers that don't match a digest/name:tag)

Yes, I totally agree to that point. 👍

**Comment by afbjorklund** [comment]
I think that explanation sounds much better, than trying to stay bug-compatible with the historic daemon (WWDD)

Building on the master node is one of those features unique to minikube, most others use registries or tarballs...

**Comment by haircommander** [comment]
closing this as it doesn't seem we want it
