### ISSUE TITLE
shouldn't CRI-O works well without /usr/share/containers/oci/hooks.d?

### ISSUE THREAD

**Issue by skycastlelily2** [cri-o/cri-o#3179]
make install v1.17.0-rc1 ,/bin/crio failed with
 FATA[2020-01-31 22:00:40.228343398-05:00] runtime config: invalid hooks_dir: stat /usr/share/containers/oci/hooks.d: no such file or directory: stat /usr/share/containers/oci/hooks.d: no such file or directory 

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**
crio should work without /usr/share/containers/oci/hooks.d

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by skycastlelily2** [comment]
sorry,I was wrong,the hook dir will be there after run" make install.config",
I first tried dnf install  cri-o-1.17.0-0.1.gitb89a5fc.module_f31+7363+0a59a30e
in fedora server,systemctl start crio failed as the subject,so seems like a fedora issue.
But shouldn't crio works well without the hooks dir?

**Comment by saschagrunert** [comment]
Alright I think it would make sense to specify an empty hooks dir option which is considered as _no hooks directories specified_. For that we have to change CRI-O and libpod as well. The first PR is available here: https://github.com/containers/libpod/pull/5078/files. The second one comes afterwards.

**Comment by skycastlelily2** [comment]
Hi, really sorry for the so delay response,but commit 3203 seems doesn't work.
make and make install in cri-o directory, then run /bin/crio,still failed with the same error

[root@dell-pe-fm120-2b cri-o]# /bin/crio
FATA[2020-03-17 21:11:10.250037360-04:00] runtime config: invalid hooks_dir: stat /usr/share/containers/oci/hooks.d: no such file or directory: stat /usr/share/containers/oci/hooks.d: no such file or directory

**Comment by skycastlelily2** [comment]
I should run /usr/local/bin/crio,sorry for the noise, and thanks for your fix.

**Comment by haircommander** [comment]
> I should run /usr/local/bin/crio,sorry for the noise, and thanks for your fix.

thanks for testing!
