### ISSUE TITLE
cri-o http apis doesnt work though crictl works

### ISSUE THREAD

**Issue by ganga1980** [cri-o/cri-o#3180]
**Description**
I am looking for CRI-O HTTP APIs to get the  inventory of the containers and images for the monitoring purpose.  Based on investigation, support of HTTP APIs is very limited and doesnt have support for APIs to get the list of containers and images. 
1.  /containers API failing with 404
{"storage_driver":"overlay","storage_root":"/var/lib/containers/storage","cgroup_driver":"systemd","default_id_mappings":{"uids":[{"container_id":0,"host_id":0,"size":4294967295}],"gids":[{"container_id":0,"host_id":0,"size":4294967295}]}}[root@myocp42-pdqlw-worker-eastus2-thg2w /]# curl -v --unix-socket /var/run/crio/crio.sock http://localhost/containers
*   Trying /var/run/crio/crio.sock...
* Connected to localhost (/var/run/crio/crio.sock) port 80 (#0)
> GET /containers HTTP/1.1
> Host: localhost
> User-Agent: curl/7.61.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Sun, 02 Feb 2020 04:58:09 GMT
< Content-Length: 19
<
404 page not found
* Connection #0 to host localhost left intact

2. /images API call failing with 404
[root@myocp42-pdqlw-worker-eastus2-thg2w /]# curl -v --unix-socket /var/run/crio/crio.sock http://localhost/images
*   Trying /var/run/crio/crio.sock...
* Connected to localhost (/var/run/crio/crio.sock) port 80 (#0)
> GET /images HTTP/1.1
> Host: localhost
> User-Agent: curl/7.61.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Sun, 02 Feb 2020 05:01:40 GMT
< Content-Length: 19
<
404 page not found
* Connection #0 to host localhost left intact

3. /info API works
[root@myocp42-pdqlw-worker-eastus2-thg2w /]# curl -v --unix-socket /var/run/crio/crio.sock http://localhost/info
*   Trying /var/run/crio/crio.sock...
* Connected to localhost (/var/run/crio/crio.sock) port 80 (#0)
> GET /info HTTP/1.1
> Host: localhost
> User-Agent: curl/7.61.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Sun, 02 Feb 2020 05:02:26 GMT
< Content-Length: 239
<
* Connection #0 to host localhost left intact
{"storage_driver":"overlay","storage_root":"/var/lib/containers/storage","cgroup_driver":"systemd","default_id_mappings":{"uids":[{"container_id":0,"host_id":0,"size":4294967295}],"gids":[{"container_id":0,"host_id":0,"size":4294967295}]

**Steps to reproduce the issue:**
1.  Run /containers API and observe API failing with 404
sudo curl -v --unix-socket /var/run/crio/crio.sock http://localhost/containers
2.Run /images API and observe API failing with 404
sudo curl -v --unix-socket /var/run/crio/crio.sock http://localhost/images

**Describe the results you received:**
/containers and /images APIs are failing with 404 though crictl ps and crictl images works.

**Describe the results you expected:**
Expecting /containers and /images to work.  Having the support of these APIs will be great value for the monitoring purpose to get the inventory of CRI-O containers similarly to Docker.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
[root@myocp42-pdqlw-worker-eastus2-thg2w /]# crictl version
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.14.11-6.dev.rhaos4.2.git627b85c.el8
RuntimeApiVersion:  v1alpha1
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by haircommander** [comment]
Info is actually the only http connection that cri-o serves. The rest are gRPC. The reasoning is CRI-O is only designed to fulfill the needs of the CRI, and the CRI uses gRPC to ask for containers and images. I I think you can use grpc over http, though I haven't personally tried that

**Comment by rhatdan** [comment]
With the new Podman APIV2, if we every get CRI-O and Libpod merged, it would be able to give good API Endpoints,  Sadly this seems far away.

**Comment by ehashman** [comment]
Is it possible to get this information via gRPC rather than HTTP?

**Comment by saschagrunert** [comment]
> Is it possible to get this information via gRPC rather than HTTP?

Yes I think via [crictl](https://github.com/kubernetes-sigs/cri-tools).

**Comment by ganga1980** [comment]
> > Is it possible to get this information via gRPC rather than HTTP?
> 
> Yes I think via [crictl](https://github.com/kubernetes-sigs/cri-tools).

> @rhatdan , @saschagrunert , can you guys point me to gRPC APIs which I can use to get the inventory of the containers and images etc?

**Comment by nalind** [comment]
@ganga1980 https://github.com/kubernetes/cri-api/blob/master/pkg/apis/runtime/v1alpha2/api.proto, I think.

**Comment by harche** [comment]
@ganga1980 if you are using golang, you can use the following links for reference to learn to how initialize the client, 

[list containers](https://github.com/kubernetes-sigs/cri-tools/blob/master/cmd/crictl/container.go#L282)

[list images](https://github.com/kubernetes-sigs/cri-tools/blob/master/cmd/crictl/image.go#L140)

**Comment by haircommander** [comment]
@ganga1980 have the links posted helped your problem? can this be closed?

**Comment by ganga1980** [comment]
Hi, @haircommander , thanks for the links. please go-ahead and close this issue.

**Comment by coolninja1504** [comment]
Hi @harche ,
 Is there any way to find out the terminated(crashed) container id using cri-o api or crictl command output. How can we co relate the pid before and after crash. We could see that after crash the pid is becomes 0 but do we have any hidden apis to get this pid for crashed container ?

**Comment by haircommander** [comment]
it's kind of complicated, but CRI-O keeps track of an `initPid` which is the initial pid of the container. It can be found in the container's persistent storage directory, which is at `/var/lib/containers/storage/overlay-containers/$ctr_id/state.json`, like:
jq .initPid <  /var/lib/containers/storage/overlay-containers/9ba7a438541ca304b90fcc46caa9e047f0d52272cefc30c959f05ba04ae7f7dd/userdata/state.json
