### ISSUE TITLE
cri-o must set home ton $HOME if specified in image

### ISSUE THREAD

**Issue by akram** [cri-o/cri-o#3186]
When cri-o is used  in OpenShift, it automatically creates the arbitrary user that OpenShift requires to run a specific image. as an example:
```
sh-4.2$ tail -1 /etc/passwd
1000580000:x:1000580000:0:1000580000 user:/:/sbin/nologin
sh-4.2$
```
However, the home directory is set to "/"  .
```
sh-4.2$ getent passwd $(id -u) | cut -f6 -d:
/
```

When the $HOME environment variable is set in the built container image, it is preferable that the user home matches the same value.

**Comment by mrunalp** [comment]
@akram Thanks for the report. We can fix that code to respect $HOME.

**Comment by mrunalp** [comment]
@akram I have opened https://github.com/cri-o/cri-o/pull/3193 as a fix.

**Comment by akram** [comment]
thanks team for fixing this so fast.
I am just wondering based on this: https://github.com/cri-o/cri-o/pull/3193/files#diff-aab4c88107335f18845d9e317503a02dR770

Will cri-o use the last WORKDIR of the container or the HOME ? 
cc @mrunalp

**Comment by nalind** [comment]
Going by https://github.com/cri-o/cri-o/blob/6fa039b4da9f4138605dacf6aace150ef97eb043/server/container_create.go#L284, if there is a `HOME` value in the environment list that is passed to the `setupContainerUser()` function, its value is used in preference to the image's working directory when creating the `/etc/passwd` entry for the user.  The PR makes sure that values from the images are in that list.

**Comment by akram** [comment]
awesome, thanks, that would be perfect
