### ISSUE TITLE
Question: hostNetwork and uts namespace

### ISSUE THREAD

**Issue by yboaron** [cri-o/cri-o#3197]
**Description**
I create (Kubernetes + cri-o) pod with host networking (i.e: 'hostNetwork: true' in pod's spec), and it seems that a new uts namespace being allocated for this pod.
Doesn't pod's with host networking should use host's uts namespace?
Thanks
Yossi

**Comment by haircommander** [comment]
in the above PR I checked whether setting hostUts when hostNetwork was true, but it broke the cri tests. Pods are apparently always given a private hostname. as such, I'm closing
