### ISSUE TITLE
Refactor server sources under new interfaces

### ISSUE THREAD

**Issue by saschagrunert** [cri-o/cri-o#3247]
As discussed recently via Slack, the general idea would be to introduce new Interfaces to be able to reduce code complexity and be prepared for a possible migration to libpod. We can see the new interface as middle-layer between the gRPC API and the usage of underlying libraries.

Target is to discuss here if we want to go that way and roughly design the interface to be able to start with the implementation.

Right now, the interface needs methods for the following features:
```go
type Sandboxes interface {
	List() []Sandbox
	Restore()
}

type Sandbox interface {
	Create()
	Start()
	Stop()
	Remove()

	State()
	Network()

	Containers() Containers
	AddContainer(Container)
	RemoveContainer(Container)
}

type Network interface {
	Start()
	Stop()
}

type Containers interface {
	List() []Container
}

type Container interface {
	Start()
	Stop()
	Remove()

	Attach()
	Exec()
	PortForward()
	ReopenLog()

	State()
}
```

**Comment by mrunalp** [comment]
I think we should also add a `Create` for `Sandbox`. `Create` is where we setup everything and `Start` could be where we start a container or a vm or a no-op for pinned namespaces.

**Comment by mrunalp** [comment]
Also, the current runtime interface `RuntimeImpl` interface could be renamed to Container.

**Comment by saschagrunert** [comment]
Alright, I added `Create()` to the Sandbox as well.

**Comment by saschagrunert** [comment]
I tried to nail down the Sandbox/Creator interface in a first PR: https://github.com/cri-o/cri-o/pull/3261

**Comment by saschagrunert** [comment]
Closing this since I guess we're on a good track.
