### ISSUE TITLE
Repeating kubelet errors with crio: Failed to create existing container

### ISSUE THREAD

**Issue by clee** [cri-o/cri-o#3259]
**Description**

I have a baremetal Kubernetes 1.17.2 cluster, using crio with the ZFS graph driver for storage. I have one host using `crun` as the default runtime, and one using `runc` as the default. I have both crio and kubelet configured to use `systemd` as the cgroup driver.

**Steps to reproduce the issue:**

1. Use CRI-O on ZFS with Kubernetes
2. Watch kubelet logs

**Describe the results you received:**

On both machines, I see errors and warnings like these in my logs every minute (or more, for the crio warnings):

```log
crio[59456]: time="2020-02-15 13:44:32.065927387-07:00" level=warning msg="unable to get stats for container fc7efb695cfb307b48421225a47d19f172f6555d5a09a7a90821c9edc06a98f2: unable to load cgroup at kubepods-besteffort-pod0fb386ed7a9f3e4462d5182de8ccaa2b.slice: cgroup deleted" id=b01c9014-5969-4452-81b5-3d5a3f43230b
kubelet[59015]: E0215 13:44:37.944357   59015 manager.go:1086] Failed to create existing container: /kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod0fb386ed7a9f3e4462d5182de8ccaa2b.slice/crio-31b710e9b2340e9f18fbd3a14b19a44e76a4192e668239e5cfd9597681eed9bc.scope: Error finding container 31b710e9b2340e9f18fbd3a14b19a44e76a4192e668239e5cfd9597681eed9bc: Status 404 returned error &{%!s(*http.body=&{0xc0017ae640 <nil> <nil> false false {0 0} false false false <nil>}) {%!s(int32=0) %!s(uint32=0)} %!s(bool=false) <nil> %!s(func(error) error=0x74f5f0) %!s(func() error=0x74f580)}
```

**Describe the results you expected:**

I expect to see no errors or warnings in my kubelet logs with crio, the same way I don't see any warnings with docker or containerd.

**Additional information you deem important (e.g. issue happens only occasionally):**

I see these logs every 60 seconds.

**Output of `crio --version`:**

```
crio version 1.17.0
commit: "3afd3331a57e85bc56358f4e13802e7c25cd6c2d"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
- baremetal
- debian bullseye
- crun `4a9b272b98768549da1277ec073c66c3ef51fd5b`
- runc `1.0.0~rc6+dfsg1`

**Comment by mrunalp** [comment]
@nalind ptal.

**Comment by nalind** [comment]
It looks the error is that we expect the container's control groups to have a path that doesn't match what's actually happening on the system - CRI-O's looking for `/sys/fs/cgroup/cpu/kubepods-burstable-podc83c5351_54dc_4615_bc17_f356749db365.slice` for a container with ID bdb2c5262c638322449f0ca38ba8c9ec36f6aa96089a1c285843605ae7391ad6`, for example, when the path for the cpu controller for the processes in the container is `/sys/fs/cgroup/cpu/kubepods.slice/kubepods-pode26e3c3e_8ff8_4539_931d_49b1ca4c52ae.slice/crio-bdb2c5262c638322449f0ca38ba8c9ec36f6aa96089a1c285843605ae7391ad6.scope`.  I'm not sure where the disagreement comes from.

The error's logged as a warning, so they don't show up if we're only logging error-level messages, but the log messages we're seeing here are from the kubelet.

**Comment by mrunalp** [comment]
@clee Are crio and kubelet both configured to use the same cgroup driver. We prefer `systemd` as the cgroup driver. Also, I would first test with runc as a sanity test.

**Comment by clee** [comment]
> @clee Are crio and kubelet both configured to use the same cgroup driver? We prefer `systemd` as the cgroup driver. Also, I would first test with runc as a sanity test.

From my description:

> I have one host using crun as the default runtime, and one using runc as the default. I have both crio and kubelet configured to use systemd as the cgroup driver.

**Comment by nalind** [comment]
@haircommander this looks a lot like #3295 to me.

**Comment by moreqpi** [comment]
I had the same issue on crio & kubernetes v1.16
Changing **conmon_cgroup** value to "**kubepods.slice**" in **_crio.conf_** fixed that issue.
```
[crio.runtime]
...
conmon_cgroup = "kubepods.slice"
...
```

**Comment by haircommander** [comment]
ah @clee I've got a fix in the works [here](https://github.com/cri-o/cri-o/pull/3482). Lucikly, that's just a warning, and a result of the timing between stopping a pod and removing a pod. It only happens with systemd cgroup driver because systemd cleans up cgroups after they're dead. Once I come to a solution, I'll backport to 1.17. Thanks for your patience :smile:

**Comment by haircommander** [comment]
> I had the same issue on crio & kubernetes v1.16
> Changing **conmon_cgroup** value to "**kubepods.slice**" in **_crio.conf_** fixed that issue.
> 
> ```
> [crio.runtime]
> ...
> conmon_cgroup = "kubepods.slice"
> ...
> ```

I find this interesting. You didn't see any messages of `unable to load cgroup at kubepods-besteffort-pod0fb386ed7a9f3e4462d5182de8ccaa2b.slice: cgroup deleted` after switching the conmon_cgroup? where was it before? `system.slice`?

**Comment by haircommander** [comment]
> I expect to see no errors or warnings in my kubelet logs with crio, the same way I don't see any warnings with docker or containerd.


following up on this expectation, out of curiosity. When using containerd/docker are you using systemd cgroup driver @clee ?

**Comment by clee** [comment]
> I had the same issue on crio & kubernetes v1.16
> Changing **conmon_cgroup** value to "**kubepods.slice**" in **_crio.conf_** fixed that issue.

Unfortunately, this didn't work for me. I now see:

```
kubelet[27715]: E0326 14:37:11.930304   27715 manager.go:1086] Failed to create existing container: /kubepods.slice/kubepods-podb0877b91_acee_4a63_b114_84a3ff2e9441.slice/crio-fe2a3416f2121e5cb0f87deeccf7d1f6695b9272bf8a6bfc28aee7f963b89da6.scope: Error finding container fe2a3416f2121e5cb0f87deeccf7d1f6695b9272bf8a6bfc28aee7f963b89da6: Status 404 returned error &{%!s(*http.body=&{0xc0009021a0 <nil> <nil> false false {0 0} false false false <nil>}) {%!s(int32=0) %!s(uint32=0)} %!s(bool=false) <nil> %!s(func(error) error=0x74f5f0) %!s(func() error=0x74f580)}
```

**Comment by clee** [comment]
> > I expect to see no errors or warnings in my kubelet logs with crio, the same way I don't see any warnings with docker or containerd.
> 
> following up on this expectation, out of curiosity. When using containerd/docker are you using systemd cgroup driver @clee ?

I have both crio and kubelet configured to use systemd as the cgroup driver.

**Comment by haircommander** [comment]
> > > I expect to see no errors or warnings in my kubelet logs with crio, the same way I don't see any warnings with docker or containerd.
> > 
> > 
> > following up on this expectation, out of curiosity. When using containerd/docker are you using systemd cgroup driver @clee ?
> 
> I'm actually not sure. I was using the default configuration with the docker.io packages. So maybe not?

yeah they use cgroupfs by default. I think this is from systemd cleaning up the cgroups from underneath the runtime. Gotta find the best way to not error in this case

**Comment by clee** [comment]
> I think this is from systemd cleaning up the cgroups from underneath the runtime. Gotta find the best way to not error in this case

I'm pretty sure @nalind narrowed it down to the new cgroup code - crio switched from containerd's `cgroups` implementation to the libpod one, and the libpod one doesn't seem to work properly.

> &lt;nalind&gt; ah, in 1.14, oci/container.go used `github.com/containerd/cgroups`'s `cgroups.Load()` to read things, and 1.17 uses a function with the same name from `github.com/containers/libpod/pkg/cgroups`

**Comment by moreqpi** [comment]
> > I had the same issue on crio & kubernetes v1.16
> > Changing **conmon_cgroup** value to "**kubepods.slice**" in **_crio.conf_** fixed that issue.
> > ```
> > [crio.runtime]
> > ...
> > conmon_cgroup = "kubepods.slice"
> > ...
> > ```
> 
> I find this interesting. You didn't see any messages of `unable to load cgroup at kubepods-besteffort-pod0fb386ed7a9f3e4462d5182de8ccaa2b.slice: cgroup deleted` after switching the conmon_cgroup? where was it before? `system.slice`?

I saw something like this before, but for now I haven't any errors in logs.
If it is important - I can try to reproduce my actions, before this, and attach logs here.

@clee, it seems like something exist with that cgroup name.
A simple solution in my mind - reboot and check again. May be it helps.
Of course its possible to kill PIDs in that cgroup.

**Comment by lbogdan** [comment]
Workaround and explanation [here](https://github.com/cri-o/cri-o/issues/5490#issuecomment-1107812321).

**Comment by lbogdan** [comment]
Workaround and explanation [here](https://github.com/cri-o/cri-o/issues/5490#issuecomment-1107812321).
