### ISSUE TITLE
No DNS resolution with K8s 1.17/1.18 (alpha)

### ISSUE THREAD

**Issue by thschue** [cri-o/cri-o#3260]
**Description**
On K8s 1.17/1.18(alpha) pods on nodes with CRI-O 1.15(ppa) and 1.16(obs) are not able to resolve names.  The same setup works with e.g. K8s 1.16 and CRI-O 1.15. The networking plugin is flannel and works on the same cluster with docker/containerd.

**Steps to reproduce the issue:**
1. Install kubernetes 1.17 (apt-repo) or 1.18 (github)
2. Install CRI-O (1.15 or 1.16)
3. Schedule Pod
4. Ping a pod per name

**Describe the results you received:**
Pod can not resolve the name, target can be pinged using the IP

**Describe the results you expected:**
- IP address should be printed and echo replies should be shown

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**
```
crio version 1.15.3-dev
commit: unknown
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
* Ubuntu 18.04
* AWS

**Comment by thschue** [comment]
Seems that this is an issue in combination with flannel. After switching to calico, DNS resolution works. Both (calico/flannel) were installed with default settings as described in the documentation.

**Comment by haircommander** [comment]
are you able to use cri-o 1.17 from obs? @thschue

**Comment by thschue** [comment]
Yes, I’ve installed cri-o from obs and it works fine with calico.

**Comment by haircommander** [comment]
alrighty, as such I'm closing :smile:
