### ISSUE TITLE
crio unable to create container for k8s pod

### ISSUE THREAD

**Issue by skycastlelily2** [cri-o/cri-o#3293]
**Description**
I set up k18s on fedora30, then join the node on a  f31 system with cgroupv1(and docker)
then I change the runtime to crio,and try to create a pod to the f31 node,but failed
here is the yaml I used to create the k18s pod
apiVersion: v1
kind: Pod
metadata:
  name: memory-demot4
  namespace: mem-example
spec:
  nodeSelector:
    type: testEndNode1
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
systemctl kubectl status shows:
Feb 16 04:39:29 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[250802]: E0216 04:39:29.473981  250802 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get network JSON for pod sandbox k8s_memory-demot3_mem-example_fed9a3c5-07f7-4e96-881b c1cb3d15a32b_0(a252ca0cf4c2cc9709c6e09aa3b02ec3dbbedfbfdcbef355f5dcc78e2ac6f61c): cannot convert version ["" "0.1.0" "0.2.0"] to 0.4.0

[root@dell-pem905-01 lnie]# kubectl get pods --namespace=mem-example
NAME            READY   STATUS              RESTARTS   AGE
memory-demot5   0/1     ContainerCreating   0          2m53s

docker works fine on this node very well 

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by skycastlelily2** [comment]
forget to put the information,both the master and the f31 node are:
crio version 1.17.0

**Comment by haircommander** [comment]
What cgroup manager are you using for kubelet, and does it match CRI-O's?

**Comment by skycastlelily2** [comment]
hi, I set kubelet's cgroup manager(driver) to systemd, which matchs CRI-O's

**Comment by saschagrunert** [comment]
Hey @skycastlelily2, which kind of CNI plugin do you use and what is the content of `/etc/cni/net.d/*` before creating the workload?

**Comment by skycastlelily2** [comment]
HI, 
flannel,
[root@dell-per6415-04 ~]# cat /etc/cni/net.d/10-flannel.conflist 
{
  "cniVersion": "0.2.0",
  "name": "cbr0",
  "plugins": [
    {
      "type": "flannel",
      "delegate": {
        "hairpinMode": true,
        "isDefaultGateway": true
      }
    },
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      }
    }
  ]
}
[root@dell-per6415-04 ~]# cat /etc/cni/net.d/100-crio-bridge.conf
{
    "cniVersion": "0.3.1",
    "name": "crio-bridge",
    "type": "bridge",
    "bridge": "cni0",
    "isGateway": true,
    "ipMasq": true,
    "hairpinMode": true,
    "ipam": {
        "type": "host-local",
        "routes": [
            { "dst": "0.0.0.0/0" },
            { "dst": "1100:200::1/24" }
        ],
        "ranges": [
            [{ "subnet": "10.88.0.0/16" }],
            [{ "subnet": "1100:200::/24" }]
        ]
    }
}

**Comment by saschagrunert** [comment]
Can you please try to set the `"cniVersion": "0.2.0",` to `"cniVersion": "0.3.1",`, restart CRI-O and test again if the workload creation succeeds?

**Comment by skycastlelily2** [comment]
Hi,
doesn't work,still the same error.
FYI,there are two pods on that node,one is memory-demoty I create when
docker is the runtime,
then I stop docker and use crio instead,crio create the pod successfully,
but when I try to kubeadm apply -f yaml to create pod with crio runtime,the
status is always
ContainerCreating.
root@dell-pem905-01 lnie]# kubectl get pods --namespace=mem-example
NAME             READY   STATUS              RESTARTS   AGE
memory-demoty    0/1     Error               0          177m
memory-demoty6   0/1     ContainerCreating   0          21m

here is the output before I follow your suggest and stop crio to set the
config
[root@dell-pem905-01 lnie]# kubectl get pods --namespace=mem-example
NAME             READY   STATUS              RESTARTS   AGE
memory-demoty    1/1     Running             0          176m
memory-demoty6   0/1     ContainerCreating   0          20m

**Comment by skycastlelily2** [comment]
Closing this,as it seems work now,I was trying with crun as the runtime to see if it will make any difference,as in another case,crun support cgroupv2 but runc doesn't,then I found crun works,and then I changed it back to runc,works now,sorry for the noise. #3295 still there.
