### ISSUE TITLE
cri-o v1.17.0 refuses to remove images though associated container is gone (leads to kubelet Disk Pressure failure condition)

### ISSUE THREAD

**Issue by ghglza** [cri-o/cri-o#3302]
**cri-o refuses to remove an image due to it being in use though there is no container process running using it**

**Steps to reproduce the issue:**
1. Run k8s w/ cri-o as runtime for some time
2. Try to remove unused images, either by kubelet housekeeping or manually:
```
# journalctl -xeu kubelet
...
Feb 19 09:44:43 node26.corp.int kubelet[56921]: I0219 09:44:43.568179   56921 image_gc_manager.go:300] [imageGCManager]: Disk usage on image filesystem is at 87% which is over the high threshold (85%). Trying to free 12543375769 bytes down to the low threshold (80%).
Feb 19 09:44:43 node26.corp.int kubelet[56921]: I0219 09:44:43.572308   56921 image_gc_manager.go:371] [imageGCManager]: Removing image
"6d5fcfe5ff170471fcc3c8b47631d6d71202a1fd44cf3c147e50c8de21cf0648" to free 1439735 bytes
Feb 19 09:44:43 node26.corp.int kubelet[56921]: E0219 09:44:43.573177   56921 remote_image.go:135] RemoveImage "6d5fcfe5ff170471fcc3c8b4
7631d6d71202a1fd44cf3c147e50c8de21cf0648" from image service failed: rpc error: code = Unknown desc = Image used by 4b8c2fe88586b69141b7597b03c90499e1
72ac9bb906824e08118859109b95bd: image is in use by a container
...
# crictl rmi 6d5fcfe
FATA[0000] error of removing image "6d5fcfe": rpc error: code = Unknown desc = Image used by 4b8c2fe88586b69141b7597b03c90499e172ac9bb906824e08118859109b95bd: image is in use by a container
```
3.  But, the container processes reported by cri-o to use the image doesn't exist!
```
# crictl ps -q --id 4b8c2fe88586b69141b7597b03c90499e172ac9bb906824e08118859109b95bd
#
```

**Describe the results you received:**
Images no longer in use by running containers cannot be purged from local image repository.
This renders k8s cluster nodes unusable for starting new pods, as the kubelet marks them tainted due to ephemeral disk pressure.

**Describe the results you expected:**
Images in local repository not used by any running container process should have been deleted.

**Additional information you deem important (e.g. issue happens only occasionally):**
Unfortunately, we cannot reliably reproduce the broken state of the cri-o record of images in use / containers running.
But it is sufficient to run a k8s cluster with cri-o v1.17.0 for a few days in order to trigger the problem

**Output of `crio --version`:**
```
crio version 1.17.0
commit: "6d0ffae63b9b7d8f07e7f9cf50736a67fb31faf3"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
cri-o is installed from sources on CentOS 7 on VMWare based VMs, and used as container runtime by k8s v1.17.3

**Comment by mrunalp** [comment]
@ghglza Can you try listing containers using `crictl ps -a` to make sure if it is gone or not?

**Comment by ghglza** [comment]
@mrunalp Yes we tried that, too -- the container reported by "crictl rmi" as using the image was definitively gone.
We had also cases where we had removed the k8s installation ("kubeadm reset") completely, so there was absolutely no container running -- and yet crictl refused to remove some of the images (e.g. for the kube-router CNI plugin) in the local store

**Comment by haircommander** [comment]
hey @ghglza do you have any update here? Sorry for the super late reply. it's also possible the containers are still running but cri-o has lost track of them. does `runc list` print any containers?

**Comment by ghglza** [comment]
No update -- the problem is still there with k8s v1.18.3 / cri-o v1.18:

* Installed, and then deleted the cluster with "kubeadm reset"
* Output of "runc list" is empty (same for "crictl ps")
* "crictl rmi kube-proxy:v1.18.3" on the master node fails, crictl complains about the image being in use
* Interesting is that the kube-proxy container had been deleted directly after cluster instantiation, (as we use kube-router's IPVS proxy functionality instead), by running
```
podman run --privileged -v /lib/modules:/lib/modules --net=host k8s.gcr.io/kube-proxy:v1.18.3 kube-proxy --cleanup'
```

**Comment by haircommander** [comment]
what's the output of `mount | grep containers`?

**Comment by ghglza** [comment]
```
$ mount | grep containers
/dev/mapper/vg01-var on /var/lib/containers/storage/overlay type ext4 (rw,relatime,data=ordered)
```

**Comment by haircommander** [comment]
what the heck...
does a `podman rmi 6d5fcfe` do the job? also what's `podman ps -a`

**Comment by ghglza** [comment]
Now this is funny:

```
# podman rmi k8s.gcr.io/kube-proxy:v1.18.3
Error: could not remove image 3439b7546f29bec22edd737bc0a5770ead18b5ee5ce0aea5af9047a554715f9f as it is being used by 4 
# podman ps -a
CONTAINER ID  IMAGE                          COMMAND               CREATED            STATUS                        PORTS  NAMES
e4a4e96e0a0a  k8s.gcr.io/kube-proxy:v1.18.3  kube-proxy --clea...  About an hour ago  Exited (0) About an hour ago         beautiful_bose
9f7e943892b9  k8s.gcr.io/kube-proxy:v1.18.3  kube-proxy --clea...  2 hours ago        Exited (0) 2 hours ago               flamboyant_wilson
b8b3485d6e4a  k8s.gcr.io/kube-proxy:v1.18.3  kube-proxy --clea...  3 hours ago        Exited (0) 3 hours ago               nostalgic_einstein
e82733c7912b  k8s.gcr.io/kube-proxy:v1.18.3  kube-proxy --clea...  10 days ago        Exited (0) 10 days ago               hardcore_moore
e230bd4cb831  k8s.gcr.io/kube-proxy:v1.18.2  kube-proxy --clea...  5 weeks ago        Exited (0) 5 weeks ago               elated_moore
125a6e1ff393  k8s.gcr.io/kube-proxy:v1.18.2  kube-proxy --clea...  5 weeks ago        Exited (0) 5 weeks ago               affectionate_merkle
be63de7808a6  k8s.gcr.io/kube-proxy:v1.18.2  kube-proxy --clea...  6 weeks ago        Exited (0) 6 weeks ago               admiring_mcclintock
ee712c0c725e  k8s.gcr.io/kube-proxy:v1.18.2  kube-proxy --clea...  6 weeks ago        Exited (0) 6 weeks ago               peaceful_leakey
1dce06240e46  k8s.gcr.io/kube-proxy:v1.18.2  kube-proxy --clea...  6 weeks ago        Exited (0) 6 weeks ago               cool_hopper
eb85a6563f7f  k8s.gcr.io/kube-proxy:v1.18.1  kube-proxy --clea...  7 weeks ago        Exited (0) 7 weeks ago               xenodochial_poincare
35fb177a2b60  k8s.gcr.io/kube-proxy:v1.18.1  kube-proxy --clea...  7 weeks ago        Exited (0) 7 weeks ago               charming_lamarr
d7c0857887d2  k8s.gcr.io/kube-proxy:v1.18.1  kube-proxy --clea...  7 weeks ago        Exited (0) 7 weeks ago               eloquent_ellis
e2bf95e2fab5  k8s.gcr.io/kube-proxy:v1.18.1  kube-proxy --clea...  7 weeks ago        Exited (0) 7 weeks ago               silly_chaplygin
a2ff84e9f1eb  k8s.gcr.io/kube-proxy:v1.18.1  kube-proxy --clea...  7 weeks ago        Exited (0) 7 weeks ago               romantic_visvesvaraya
7a5bf0e2e75b  k8s.gcr.io/kube-proxy:v1.18.1  kube-proxy --clea...  7 weeks ago        Exited (0) 7 weeks ago               friendly_mayer
005ff8b38884  k8s.gcr.io/kube-proxy:v1.18.1  kube-proxy --clea...  7 weeks ago        Exited (0) 7 weeks ago               dreamy_morse
6e00630141f8  k8s.gcr.io/kube-proxy:v1.17.4  kube-proxy --clea...  7 weeks ago        Exited (0) 7 weeks ago               amazing_mirzakhani

```
podman seems to think that all 4 container instances that were using kube-proxy:v1.18.3 in the last weeks are still running?!?
I.e. each time the cluster had been deleted and  reinstalled with, a sort of "container zombie" seems to be left behind

**Comment by haircommander** [comment]
ah! you need to specify on the command line `--rm` or the container will still be mounted and tracked in the database.
if you do a `podman rm -a`, then a `podman rmi 6d5fcfe`  that should do it

**Comment by ghglza** [comment]
And of course, after "podman rm ..." the container zombies, "crictl rmi..." works fine

**Comment by haircommander** [comment]
huzzah! any further needs before we close this ticket?

**Comment by ghglza** [comment]
Ok, thanks a lot for clarifying this!
As we currently cannot reproduce the problem when the cluster is running (i.e. cri-o fails to remove an image if triggered by the kubelet) I think you can close this ticket.

**Comment by haircommander** [comment]
thanks for the report!
