### ISSUE TITLE
arm64 builds for the current ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by chrstnwhlrt** [cri-o/cri-o#3304]
It might be a feature request but is it possible to add **arm64/armv7l** targets to the build service https://build.opensuse.org/project/repository_state/devel:kubic:libcontainers:stable/xUbuntu_18.04 for Ubuntu 18.04? Ubuntu 18.04 still ships with **GLIBC 2.27-3** which makes other debian compatible build for arm incompatible to it.

**Comment by haircommander** [comment]
PTAL @lsm5

**Comment by lsm5** [comment]
@chrstnwhlrt the build envs for ubuntu 18.04 and 19.04 on OBS aren't correctly setup to fetch the required dependencies and fixing that isn't high enough priority for the OBS folks. But 19.10 has arm64 builds available and I'm guessing once 20.04 is out, it'll have those too. So, I'm hoping you can wait a month or so for the new LTS (assuming OBS enables it around the same time).

**Comment by chrstnwhlrt** [comment]
@lsm5 I managed to build cri-o myself natively using your build instructions and it seems to run as expected using cri-o 1.17 with kubernetes 1.17. Is there any intended way to create a DEB package using the Makefile?

**Comment by lsm5** [comment]
@chrstnwhlrt don't have a Makefile target (patches welcome), but you can fetch the deb sources from the `debian-` branches at https://gitlab.com/rhcontainerbot/cri-o/ and then `dpkg-buildpackage -us -uc`

**Comment by chrstnwhlrt** [comment]
@lsm5 Are there any differences between the release-1.17 branch in github and the gitlab debian-stable-1.17 branch? I copied the debian directory from the gitlab branch into the release-1.17 branch of github (which I managed to build natively on arm64) and the packaging failed. Using the gitlab debian-stable-1.17 branch for building and packaging failed as well. Both methods seem to expect the go binary in "/usr/bin/go" - I installed go manually to "/usr/local/go/bin/go". After symlinking the go binary the github branch failed to build, the gitlab branch succeeded and created the package as expected. Will the /debian packaging directory be merged to github? Or should I stay with the gitlab branches?

**Comment by lsm5** [comment]
@chrstnwhlrt yes, the `debian/` dir is the only addition in the debian- branches. I tried upstreaming the debian packaging for other tools sometime back, but I wasn't sure how to deal with changelogs, and the other reason being upstreaming could cause conflicts with the packaging sources maintained by official debian maintainers (if any).

**Comment by lsm5** [comment]
@chrstnwhlrt I'd rather not handle upstreaming at this point myself, but in case you're willing to get that done, go right ahead :)

I'm aware people are looking to get the Fedora spec files upstreamed too, so this could be a good addition on the debian side.

/cc @mrunalp @dougsland

**Comment by chrstnwhlrt** [comment]
@lsm5 Okay if I get this right the /debian directory is the only addition to the release branch from github? Which branch is used for the OBS?

**Comment by lsm5** [comment]
In the debian forks, I also added a `crio.conf.prebuilt` in the main cri-o dir as it was much easier to just use it than generate one at package build time. But everything else is in the `debian` dir.

The `debian-stable-` branches are used for the OBS stable repo https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable while `debian-testing-` branches are for the OBS testing repo https://build.opensuse.org/project/show/devel:kubic:libcontainers:testing . 

So for example, `debian-stable-1.16` is the source for `cri-o-1.16` on OBS stable, `debian-testing-1.17` is for `cri-o-1.17` on OBS testing.

Difference between stable and testing is that stable will only get release tags built, while testing will also get the rc tags.

**Comment by chrstnwhlrt** [comment]
Thank you for clearing that up, maybe we should add packaging instructions to the build instructions? It's quite straight forward to package as deb with the prebuilt file, fixing the OBS configuration should be easy - or am I missing something?

**Comment by lsm5** [comment]
> Thank you for clearing that up, maybe we should add packaging instructions to the build instructions? It's quite straight forward to package as deb with the prebuilt file, fixing the OBS configuration should be easy - or am I missing something?

Umm, so `crio.conf.prebuilt` ends up being `crio.conf` and doesn't really affect debian packaging or OBS config.

RE: adding packaging instructions, sure that could be useful for people looking to build on distro/arches that OBS can't support ATM. Could you please submit a PR?

**Comment by chrstnwhlrt** [comment]
To close this: With the release of Ubuntu 20.04 I will reinstall our evaluation clusters on arm64 and amd64 using the provided packages. Compiling cri-o and all dependencies is not that hard using the documented way but not maintainable for a production case.
