### ISSUE TITLE
rm: cannot remove '/tmp/tmp.syQYUNncNo/crio-run/vfs-containers/xxxx/userdata/shm': Device or resource busy

### ISSUE THREAD

**Issue by skycastlelily2** [cri-o/cri-o#3311]
**Description**
make integration TESTFLAGS="image.bats" on fedora  ,most of the test failed with:
rm: cannot remove '/tmp/tmp.syQYUNncNo/crio-run/vfs-containers/xxxx/userdata/shm': Device or resource busy

with make localintegration ,most of the test will fail due to #3301 

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by haircommander** [comment]
hmm we should really be using overlayfs for the tests.

you may need to run the tests as sudo

**Comment by saschagrunert** [comment]
> hmm we should really be using overlayfs for the tests.
> 
> you may need to run the tests as sudo

We can use overlay, the tests run on a native Ubuntu machine in CircleCI. :)

**Comment by skycastlelily2** [comment]
Hi,I ran the integration test with root.
I have modified the makefile : -e STORAGE_OPTIONS="-s=overlay" and retested just now,
got the following error:
time="2020-02-27T02:44:56Z" level=error msg="error opening storage: 'overlay' is not supported over overlayfs, a mount_program is required: backing file system is unsupported for this graph driver"^M
# time="2020-02-27T02:44:58Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"^M

**Comment by saschagrunert** [comment]
> hmm we should really be using overlayfs for the tests.
> 
> you may need to run the tests as sudo

The tests are already running on overlay in our CI :thinking:

**Comment by skycastlelily2** [comment]
> The tests are already running on overlay in our CI 
And you didn't see this error?If so,maybe the CI is running on Ubuntu,while I'm running the test on Fedora,is the reason?
BTW, the current makefile has STORAGE_OPTIONS="-s=vfs" not  STORAGE_OPTIONS="-s=overlay",would you please tell me how the CI run the integration test on overlay?

**Comment by skycastlelily2** [comment]
> The tests are already running on overlay in our CI

And you didn't see this error?If so,maybe the CI is running on Ubuntu,while I'm running the test on Fedora,is the reason?
BTW, the current makefile has STORAGE_OPTIONS="-s=vfs" not STORAGE_OPTIONS="-s=overlay",would you please tell me how the CI run the integration test on overlay?

**Comment by haircommander** [comment]
hey @skycastlelily2 I don't see any update here, were the issues figured out or was the attempt dropped? either way, is there any further help that is needed?
