### ISSUE TITLE
cri-o v 1.14.11-0 CRI log race condition

### ISSUE THREAD

**Issue by wiwats2019** [cri-o/cri-o#3339]
**Description**
cri-o v 1.14.11-0 CRI log race condition

**Steps to reproduce the issue:**
1.  Run 1 pods 1 container in 2 theard
2.  2 theard write log at concurrent

**Describe the results you received:**
The cri-o write log in /var/log/containers/pod_name.log in race condition
when cri-o  write "P" in partial flag for split log into multiple lines

**sample log**
2020-02-27T08:01:22.949039232+07:00 stderr P {"level":"info","version":"","@suffix":"smssmpp","envName":"PROD","appName":"smssmpp","logName":"TransactionLog","from":"AAA","to":"xxxxxx","filename":"SMS_SENTOUT_20200226_0.csv","message_text":"message"
2020-02-27T08:01:22.949102484+07:00 stdout F day process  true

**Describe the results you expected:**
The cri-o should handle (race condition) writing logs correctly when  a log entry is split into multiple lines

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.14.11-0.24.dev.rhaos4.2.gitc41de67.el7
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CentOS Linux release 7.7.1908
cri-o://1.14.11-0.24.dev.rhaos4.2.gitc41de67.el7
k8s v1.14.6

**Comment by haircommander** [comment]
unfortunately, containers don't really handle logging all that intelligently. We're just forwarding what the container's pid 1 sends to stdout/stderr. We don't have any mechanism to control how the data gets to stdout/stderr, including keeping threads inside of the first process in order. You will need to implement the locking in your container to keep your threads from stepping on each other.

**Comment by haircommander** [comment]
@wiwats2019 sorry I can't be of much help. Given that, are you okay with me closing this ticket?
