### ISSUE TITLE
New Community Meeting Time

### ISSUE THREAD

**Issue by saschagrunert** [cri-o/cri-o#3454]
I think it would be good if we could agree on a new community meeting time slot. This way we could sync our work and streamline our efforts in the project.

From my (CET) perspective, I’m open to choose any time from Monday-Thursday 8am-6pm.

What do you think? What would be your expectations from such a meeting (agenda)?

**Comment by haircommander** [comment]
[Here's](https://www.when2meet.com/?8916284-E3Jpt) a when2meet (based in eastern time). I choose between 4pm and 6pm central time Monday-Friday as the first list of options

**Comment by vrothberg** [comment]
Something more EU friendly would be great. I'd love to hangout in the meetings :+1:
