### ISSUE TITLE
cri-o staticcheck issues with Go 1.14

### ISSUE THREAD

**Issue by smijolovic** [cri-o/cri-o#3481]
cri-o 1.17.1
staticcheck 2020.1.3
Go 1.14.1

staticcheck ./...

-: could not analyze dependency github.com/containers/image/v5/storage of github.com/cri-o/cri-o/internal/pkg/storage: 
	could not analyze dependency github.com/containers/storage of github.com/containers/image/v5/storage: 
	could not analyze dependency github.com/containers/storage/drivers/register of github.com/containers/storage: 
	could not analyze dependency github.com/containers/storage/drivers/btrfs of github.com/containers/storage/drivers/register: 
	/home/rpmbuild/nimbus8/crio-build/pkg/mod/github.com/containers/storage@v1.15.8/drivers/btrfs/btrfs.go:15:8: could not import C (cgo preprocessing failed) (compile)
-: could not analyze dependency github.com/containers/image/v5/transports/alltransports of github.com/cri-o/cri-o/test/copyimg: 
	could not analyze dependency github.com/containers/image/v5/storage of github.com/containers/image/v5/transports/alltransports: 
	could not analyze dependency github.com/containers/storage of github.com/containers/image/v5/storage: 
	could not analyze dependency github.com/containers/storage/drivers/register of github.com/containers/storage: 
	could not analyze dependency github.com/containers/storage/drivers/btrfs of github.com/containers/storage/drivers/register: 
	/home/rpmbuild/nimbus8/crio-build/pkg/mod/github.com/containers/storage@v1.15.8/drivers/btrfs/btrfs.go:15:8: could not import C (cgo preprocessing failed) (compile)
-: could not analyze dependency github.com/containers/libpod/pkg/cgroups of github.com/cri-o/cri-o/internal/oci: 
	could not analyze dependency github.com/containers/libpod/pkg/rootless of github.com/containers/libpod/pkg/cgroups: 
	could not analyze dependency github.com/containers/storage of github.com/containers/libpod/pkg/rootless: 
	could not analyze dependency github.com/containers/storage/drivers/register of github.com/containers/storage: 
	could not analyze dependency github.com/containers/storage/drivers/btrfs of github.com/containers/storage/drivers/register: 
	/home/rpmbuild/nimbus8/crio-build/pkg/mod/github.com/containers/storage@v1.15.8/drivers/btrfs/btrfs.go:15:8: could not import C (cgo preprocessing failed) (compile)
-: could not analyze dependency github.com/containers/libpod/pkg/cgroups of github.com/cri-o/cri-o/server: 
	could not analyze dependency github.com/containers/libpod/pkg/rootless of github.com/containers/libpod/pkg/cgroups: 
	could not analyze dependency github.com/containers/storage of github.com/containers/libpod/pkg/rootless: 
	could not analyze dependency github.com/containers/storage/drivers/register of github.com/containers/storage: 
	could not analyze dependency github.com/containers/storage/drivers/btrfs of github.com/containers/storage/drivers/register: 
	/home/rpmbuild/nimbus8/crio-build/pkg/mod/github.com/containers/storage@v1.15.8/drivers/btrfs/btrfs.go:15:8: could not import C (cgo preprocessing failed) (compile)
-: could not analyze dependency github.com/containers/libpod/pkg/spec of github.com/cri-o/cri-o/pkg/config: 
	could not analyze dependency github.com/containers/libpod/pkg/util of github.com/containers/libpod/pkg/spec: 
	could not analyze dependency github.com/containers/libpod/cmd/podman/cliconfig of github.com/containers/libpod/pkg/util: 
	could not analyze dependency github.com/containers/buildah/pkg/cli of github.com/containers/libpod/cmd/podman/cliconfig: 
	could not analyze dependency github.com/containers/buildah/util of github.com/containers/buildah/pkg/cli: 
	could not analyze dependency github.com/containers/image/v5/storage of github.com/containers/buildah/util: 
	could not analyze dependency github.com/containers/storage of github.com/containers/image/v5/storage: 
	could not analyze dependency github.com/containers/storage/drivers/register of github.com/containers/storage: 
	could not analyze dependency github.com/containers/storage/drivers/btrfs of github.com/containers/storage/drivers/register: 
	/home/rpmbuild/nimbus8/crio-build/pkg/mod/github.com/containers/storage@v1.15.8/drivers/btrfs/btrfs.go:15:8: could not import C (cgo preprocessing failed) (compile)
-: could not analyze dependency github.com/containers/storage of github.com/cri-o/cri-o/internal/pkg/storage_test [github.com/cri-o/cri-o/internal/pkg/storage.test]: 
	could not analyze dependency github.com/containers/storage/drivers/register of github.com/containers/storage: 
	could not analyze dependency github.com/containers/storage/drivers/btrfs of github.com/containers/storage/drivers/register: 
	/home/rpmbuild/nimbus8/crio-build/pkg/mod/github.com/containers/storage@v1.15.8/drivers/btrfs/btrfs.go:15:8: could not import C (cgo preprocessing failed) (compile)
-: could not analyze dependency github.com/containers/storage of github.com/cri-o/cri-o/test/mocks/containerstorage: 
	could not analyze dependency github.com/containers/storage/drivers/register of github.com/containers/storage: 
	could not analyze dependency github.com/containers/storage/drivers/btrfs of github.com/containers/storage/drivers/register: 
	/home/rpmbuild/nimbus8/crio-build/pkg/mod/github.com/containers/storage@v1.15.8/drivers/btrfs/btrfs.go:15:8: could not import C (cgo preprocessing failed) (compile)
-: could not analyze dependency github.com/containers/storage of github.com/cri-o/cri-o/test/mocks/criostorage: 
	could not analyze dependency github.com/containers/storage/drivers/register of github.com/containers/storage: 
	could not analyze dependency github.com/containers/storage/drivers/btrfs of github.com/containers/storage/drivers/register: 
	/home/rpmbuild/nimbus8/crio-build/pkg/mod/github.com/containers/storage@v1.15.8/drivers/btrfs/btrfs.go:15:8: could not import C (cgo preprocessing failed) (compile)
-: could not analyze dependency github.com/containers/storage of github.com/cri-o/cri-o/test/mocks/lib: 
	could not analyze dependency github.com/containers/storage/drivers/register of github.com/containers/storage: 
	could not analyze dependency github.com/containers/storage/drivers/btrfs of github.com/containers/storage/drivers/register: 
	/home/rpmbuild/nimbus8/crio-build/pkg/mod/github.com/containers/storage@v1.15.8/drivers/btrfs/btrfs.go:15:8: could not import C (cgo preprocessing failed) (compile)
-: could not analyze dependency github.com/cri-o/cri-o/internal/client of github.com/cri-o/cri-o/cmd/crio-status (compile)
-: could not analyze dependency github.com/cri-o/cri-o/internal/lib/sandbox of github.com/cri-o/cri-o/internal/lib/sandbox.test (compile)
-: could not analyze dependency github.com/cri-o/cri-o/internal/lib/sandbox of github.com/cri-o/cri-o/server [github.com/cri-o/cri-o/server.test] (compile)
-: could not analyze dependency github.com/cri-o/cri-o/internal/lib/sandbox of github.com/cri-o/cri-o/test/mocks/sandbox (compile)
-: could not analyze dependency github.com/cri-o/cri-o/internal/lib_test [github.com/cri-o/cri-o/internal/lib.test] of github.com/cri-o/cri-o/internal/lib.test (compile)
-: could not analyze dependency github.com/cri-o/cri-o/internal/oci of github.com/cri-o/cri-o/internal/lib/sandbox_test [github.com/cri-o/cri-o/internal/lib/sandbox.test] (compile)
-: could not analyze dependency github.com/cri-o/cri-o/internal/oci of github.com/cri-o/cri-o/internal/lib_test [github.com/cri-o/cri-o/internal/lib.test] (compile)
-: could not analyze dependency github.com/cri-o/cri-o/internal/oci of github.com/cri-o/cri-o/test/mocks/oci (compile)
-: could not analyze dependency github.com/cri-o/cri-o/internal/oci_test [github.com/cri-o/cri-o/internal/oci.test] of github.com/cri-o/cri-o/internal/oci.test (compile)
-: could not analyze dependency github.com/cri-o/cri-o/internal/pkg/criocli of github.com/cri-o/cri-o/cmd/crio (compile)
-: could not analyze dependency github.com/cri-o/cri-o/internal/pkg/storage of github.com/cri-o/cri-o/internal/lib (compile)
-: could not analyze dependency github.com/cri-o/cri-o/internal/pkg/storage_test [github.com/cri-o/cri-o/internal/pkg/storage.test] of github.com/cri-o/cri-o/internal/pkg/storage.test (compile)
-: could not analyze dependency github.com/cri-o/cri-o/pkg/config of github.com/cri-o/cri-o/internal/lib/sandbox (compile)
-: could not analyze dependency github.com/cri-o/cri-o/pkg/config of github.com/cri-o/cri-o/internal/oci_test [github.com/cri-o/cri-o/internal/oci.test] (compile)
-: could not analyze dependency github.com/cri-o/cri-o/pkg/config of github.com/cri-o/cri-o/internal/pkg/criocli (compile)
-: could not analyze dependency github.com/cri-o/cri-o/pkg/config of github.com/cri-o/cri-o/pkg/config.test (compile)
-: could not analyze dependency github.com/cri-o/cri-o/pkg/config of github.com/cri-o/cri-o/pkg/config_test [github.com/cri-o/cri-o/pkg/config.test] (compile)
-: could not analyze dependency github.com/cri-o/cri-o/pkg/config of github.com/cri-o/cri-o/test/docs-validation (compile)
-: could not analyze dependency github.com/cri-o/cri-o/server of github.com/cri-o/cri-o/internal/client (compile)
-: could not analyze dependency github.com/cri-o/cri-o/server_test [github.com/cri-o/cri-o/server.test] of github.com/cri-o/cri-o/server.test (compile)
-: could not analyze dependency github.com/cri-o/cri-o/test/mocks/lib of github.com/cri-o/cri-o/server_test [github.com/cri-o/cri-o/server.test] (compile)

**Comment by saschagrunert** [comment]
Hey @smijolovic can you explain how you run this?

We lint out code with golangci lint (contains staticcheck) and have currently not reported issues.

**Comment by smijolovic** [comment]
Thank you for pointing me in the right direction WRT to the build tags!

I build cri-o with:
make BUILDTAGS="containers_image_ostree_stub exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper libdm_no_deferred_remove seccomp selinux"

When adding the tags for staticcheck in the crio cmd directory, it works:

staticcheck -tags "containers_image_ostree_stub exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper libdm_no_deferred_remove seccomp selinux" ./cmd/crio

**Comment by saschagrunert** [comment]
Awesome, it was a pleasure to help you out. :)
