### ISSUE TITLE
crio package not available in CentOS 7 repository

### ISSUE THREAD

**Issue by geragio** [cri-o/cri-o#3495]
**Description**
It seems that crio package is not available on standard CentOS 7 repository.
I'm following the instruction provided on the README.md file, probably you just need to add an additional repository but I think the step should be added in the documentation 

**Steps to reproduce the issue:**
1. # yum install crio -y

**Describe the results you received:**
No package **crio** available.
Error: Nothing to do

**Describe the results you expected:**
crio package installed

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I'm using CentOS 7 7.7.1908 with minimal install

**Comment by haircommander** [comment]
@lsm5 has WIP builds on opensuse's OBS, once that's done he's going to update the docs

**Comment by 13rentgen** [comment]
But why current centos repos are deleted? For example:
https://cbs.centos.org/repos/paas7-crio-114-candidate/

I think you have to keep current packages and repos. And never delete it for backward compatibility.
I try to install k8s with cri-o and can't do it because of it.

**Comment by lsm5** [comment]
@13rentgen I guess cbs repos weren't meant to be used directly. https://lists.centos.org/pipermail/centos-devel/2020-March/036693.html . The CentOS IRC channels or mailing lists might provide more support.

**Comment by 13rentgen** [comment]
> @13rentgen I guess cbs repos weren't meant to be used directly. 

But, kubespray using cbs repos directly: https://github.com/kubernetes-sigs/kubespray/blob/master/roles/container-engine/cri-o/defaults/main.yml#L2

**Comment by lsm5** [comment]
> > @13rentgen I guess cbs repos weren't meant to be used directly.
> 
> But, kubespray using cbs repos directly: https://github.com/kubernetes-sigs/kubespray/blob/master/roles/container-engine/cri-o/defaults/main.yml#L2

CentOS people would suggest switching to buildlogs.centos.org repos.

**Comment by lsm5** [comment]
@13rentgen I can add 1.14 to the OBS repo if that helps.

**Comment by 13rentgen** [comment]
@lsm5 I think that if all versions are available, it will be cool. I think it's could be helpfull for many users

**Comment by lsm5** [comment]
@13rentgen RE: `all versions`, I hope 1.14 and later would suffice :)

**Comment by 13rentgen** [comment]
@lsm5 yeap :) I meant exactly the same

**Comment by lsm5** [comment]
@13rentgen `cri-o-1.14` will be published soon on OBS https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/cri-o-1.14 . Use `yum -y install cri-o-1.14` . I'll do 1.15 now.

**Comment by lsm5** [comment]
`cri-o-1.15` https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/cri-o-1.15

**Comment by 13rentgen** [comment]
@lsm5 Why you're rename `cri-o` package to `cri-o-{{version}}`?
Now I have to delete `cri-o` and install `cri-o-1.17` instead of to update package.

**Comment by sysadm1989** [comment]
Do you think the update should not be provided?
I think,
True:
```
#yum install cri-o
#yum update cri-o
```
Wrong:
```
#yum install cri-o-1.14
#yum remove cri-o-1.14
#yum install cri-o-1.15
```

**Comment by lsm5** [comment]
@13rentgen @sysadm1989 that's because I need to provide all versions on the same OBS repo.

**Comment by 13rentgen** [comment]
> @13rentgen @sysadm1989 that's because I need to provide all versions on the same OBS repo.

In cbs repo multiple versions was into single package name `cri-o`: https://cbs.centos.org/koji/packageinfo?packageID=5695

Because of package name was like `cri-o-1.14.10-1.el7.x86_64.rpm`: https://cbs.centos.org/koji/buildinfo?buildID=26913.

Now, you are create package like `cri-o-1.14-1.14.12-5.1.el7.x86_64.rpm`:
https://build.opensuse.org/package/live_build_log/devel:kubic:libcontainers:stable/cri-o-1.14/CentOS_7/x86_64

Because of that, I can't install cri-o with `yum install cri-o`.

**Comment by lsm5** [comment]
@13rentgen What I meant was cri-o 1.14 was on paas7-crio-114 repo, cri-o 1.15 was on paas7-crio-115 repo and so on. Over here everything has to be on the same repo.

You can change the install step to `yum install cri-o-1.14`. That's how it's already set up for cri-o-1.16 and cri-o-1.17 in there. Same for the debian and ubuntu versions.

**Comment by 13rentgen** [comment]
@lsm5 It also mean, that if I want to upgrade k8s cluster to the next version(for example), I have to current delete cri-o package and install new, instead of `yum update cri-o`. Do you really think it's ok?

**Comment by YuriyBufeev** [comment]
`[  492s] RPMS/x86_64/cri-o-1.14-1.14.12-5.1.el7.x86_64.rpm`

The package tagging is wrong now, @lsm5 please ensure that you have done the versioning in the right way.

**Comment by YuriyBufeev** [comment]
@haircommander kindly ask you to review the situation again.

**Comment by haircommander** [comment]
I'd like to thank @lsm5 for supporting so many different versions on so many different platforms. Note we technically only support 1.17-1.15 right now (once 1.18 is released, it'll be 1.16-1.18), as we follow kubernetes support cycles. 

@lsm5's packaging model matches the intention of cri-o. We support release branches of cri-o for a year and a half after they're released. if a simple `yum update cri-o` updated cri-o between minor versions (1.17-1.18), that would mess with users sticking to that minor version in kubernetes.

@13rentgen is this experience all that much different for updating kube? I'm not familiar with k8s packaging strategy, but I would be surprised if doing `yum update kubernetes` or similar would bump between minor versions. I would more expect upgrading between minor versions to be a bit of a chore (are we using this new feature, yadda yadda).

@YuriyBufeev that does look like it's a bit malformatted. @lsm5 can you PTAL

**Comment by haircommander** [comment]
I'd also like to note the upgrade strategy has not really changed in difficulty between OBS and CBS. before, you had to delete a repo, and add a new one, keeping the package name the same. Now you have to delete a package, and add a new one, keeping the repo the same.

**Comment by sysadm1989** [comment]
@haircommander Really? Do you work for Red that has a produc Ansiblet? Explain to me how to update cri-o through Ansible? 
P.S. Idempotency is gone.

**Comment by 13rentgen** [comment]
@haircommander for example, kubeadm updates with `yum update kubeadm`.  Of course, I could specify version on install command like `yum install kubeadm-1.17` and it's **updates** kubeadm to specific version. 

Now, you propose to update packages through deletion.

**Comment by lsm5** [comment]
@13rentgen I think I can add an `Obsoletes` to the newer packages which should replace the older package, I gotta check if it works like you expect though.

**Comment by 13rentgen** [comment]
@lsm5 seems like solution. But I do not understand, for what this difficulties? :) Standard versioning and updates looks quite ok.

**Comment by geragio** [comment]
@13rentgen got the point in my opinion
Basically this is the behavior we should expect, for example:

1) **yum install cri-o** --> Install the latest version available on repo
2) **yum install cri-o-1.18** --> Install that specific version on the OS(if available on repo of course)
3) **yum update cri-o** --> Update the package to the latest version available on the repo

**Comment by lsm5** [comment]
I pushed changes to the OBS testing repo for this https://build.opensuse.org/project/show/devel:kubic:libcontainers:testing . Let's see how that works out

**Comment by lsm5** [comment]
still building, not ready yet..

**Comment by lsm5** [comment]
After looking at the kube repos, I realized what you all are looking for was version pinning, which isn't available on OBS. OBS gets rid of the older builds soon as a new build is available. So, it's not possible to have a single cri-o package which will have older builds. That's why I had to include the major.minor string in the package name.

I'll try to setup a copr which I guess could keep the older builds too. If that doesn't work either, I guess I'll just setup separate repos / projects on OBS, like you had earlier with the CentOS CBS repos.

Wish you all a Very Happy Easter!

**Comment by lsm5** [comment]
Alright, so I changed the package organization for cri-o on OBS (centos repos only for now) to be more like what used to exist on CentOS CBS.

So, to get any dependencies for cri-o, first ensure you have the `devel:kubic:libcontainers:stable` repo enabled:
```
$ sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/devel:kubic:libcontainers:stable.repo
```

Next, add the repo for each cri-o subproject. The sub-projects for each cri-o major.minor are at  https://build.opensuse.org/project/subprojects/devel:kubic:libcontainers:stable:cri-o

For example
```
# cri-o 1.14
$ sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.14.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.14/CentOS_7/devel:kubic:libcontainers:stable:cri-o:1.14.repo

# cri-o 1.15
$ sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.15.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.15/CentOS_7/devel:kubic:libcontainers:stable:cri-o:1.15.repo

# cri-o 1.16
$ sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.16.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.16/CentOS_7/devel:kubic:libcontainers:stable:cri-o:1.16.repo

# cri-o 1.17
$ sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.17.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.17/CentOS_7/devel:kubic:libcontainers:stable:cri-o:1.17.repo
```

Now, try any of:
```
$ yum -y install cri-o-1.14.2
$ yum -y install cri-o-1.16.4
$ yum -y install cri-o
$ yum -y update cri-o
```

Once newer versions are published upstream, there will be additional sub-projects and you'll be able to add similar repos. This did work for my centos7 env. Once you guys test and approve, I'll PR to update the install docs.

HTH and Happy Easter again :)

**Comment by 13rentgen** [comment]
@lsm5 thank you!

I start to test the new repos. I test it on a fresh VM without previously installed `cri-o`.

First of all, I install all of them:
```shell
[root@test-vm2 ztsv]# cat /etc/yum.repos.d/devel\:kubic\:libcontainers\:stable*
[devel_kubic_libcontainers_stable_cri-o_1.14]
name=1.14 (CentOS_7)
type=rpm-md
baseurl=http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.14/CentOS_7/
gpgcheck=1
gpgkey=http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.14/CentOS_7/repodata/repomd.xml.key
enabled=1
[devel_kubic_libcontainers_stable_cri-o_1.15]
name=devel:kubic:libcontainers:stable:cri-o:1.15 (CentOS_7)
type=rpm-md
baseurl=http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.15/CentOS_7/
gpgcheck=1
gpgkey=http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.15/CentOS_7/repodata/repomd.xml.key
enabled=1
[devel_kubic_libcontainers_stable_cri-o_1.16]
name=1.16 (CentOS_7)
type=rpm-md
baseurl=http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.16/CentOS_7/
gpgcheck=1
gpgkey=http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.16/CentOS_7/repodata/repomd.xml.key
enabled=1
[devel_kubic_libcontainers_stable_cri-o_1.17]
name=1.17 (CentOS_7)
type=rpm-md
baseurl=http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.17/CentOS_7/
gpgcheck=1
gpgkey=http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.17/CentOS_7/repodata/repomd.xml.key
enabled=1
[devel_kubic_libcontainers_stable]
name=Stable Releases of Upstream github.com/containers packages (CentOS_7)
type=rpm-md
baseurl=http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/
gpgcheck=1
gpgkey=http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/repodata/repomd.xml.key
enabled=1
```

After that, I install `cri-o-1.14.12` - it's installed successfully:
```shell
[root@test-vm2 ztsv]# yum info cri-o
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.alpix.eu
 * epel: ftp.acc.umu.se
 * extras: mirror1.hs-esslingen.de
 * updates: mirror.alpha-labs.net
Installed Packages
Name        : cri-o
Arch        : x86_64
Version     : 1.14.12
Release     : 2.1.el7
Size        : 74 M
Repo        : installed
From repo   : devel_kubic_libcontainers_stable_cri-o_1.14
Summary     : Kubernetes Container Runtime Interface for OCI-based containers
URL         : https://github.com/cri-o/cri-o
License     : ASL 2.0
Description : Kubernetes Container Runtime Interface for OCI-based containers
```

Now, I try to update cri-o to 1.15.3 - but it causes conflicts:
```shell
[root@test-vm2 ztsv]# yum install -y cri-o-1.15.3
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.halifax.rwth-aachen.de
 * epel: ftp.acc.umu.se
 * extras: mirror1.hs-esslingen.de
 * updates: mirror.alpha-labs.net
Resolving Dependencies
--> Running transaction check
---> Package cri-o.x86_64 0:1.14.12-2.1.el7 will be updated
---> Package cri-o.x86_64 2:1.15.3-5.1.el7 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

==============================================================================================================================================================================================================================================
 Package                                      Arch                                          Version                                                  Repository                                                                          Size
==============================================================================================================================================================================================================================================
Updating:
 cri-o                                        x86_64                                        2:1.15.3-5.1.el7                                         devel_kubic_libcontainers_stable_cri-o_1.15                                         22 M

Transaction Summary
==============================================================================================================================================================================================================================================
Upgrade  1 Package

Total size: 22 M
Downloading packages:
Running transaction check
Running transaction test


Transaction check error:
  file /usr/libexec/crio/conmon from install of cri-o-2:1.15.3-5.1.el7.x86_64 conflicts with file from package conmon-2:2.0.15-1.1.el7.x86_64

Error Summary
-------------
```

**Comment by lsm5** [comment]
hmm, I guess I didn't separate conmon in 1.15, I'll fix that.

**Comment by lsm5** [comment]
@13rentgen could you try 1.16 and 1.17? I think those should work as expected.

**Comment by 13rentgen** [comment]
@lsm5 install 1.16 and upgrade to 1.17 works as expected.

**Comment by lsm5** [comment]
1.15 should be fixed now, check it out

**Comment by 13rentgen** [comment]
Yes, it works. Thank you @lsm5

**Comment by lsm5** [comment]
@13rentgen thanks, I'll PR to update the docs then. This should probably be done for ubuntu and debian packages as well.

**Comment by lsm5** [comment]
Fixed in https://github.com/cri-o/cri-o/pull/3514/files . Will open PRs for other branches as well.
