### ISSUE TITLE
AppArmor Profile not loaded on k8s 1.17 / cri-o 1.17

### ISSUE THREAD

**Issue by thschue** [cri-o/cri-o#3504]
**Description**
Start cri-o 1.17 on k8s 1.17 fails with folllowing error message:
`
-- Unit crio.service has begun starting up.
Apr 01 09:14:48 <HOSTNAME> crio[7882]: time="2020-04-01 09:14:48.773919363Z" level=fatal msg="config provided AppArmor profile \"crio-default\" not loaded"
Apr 01 09:14:48 <HOSTNAME> systemd[1]: crio.service: Main process exited, code=exited, status=1/FAILURE
Apr 01 09:14:48 <HOSTNAME> systemd[1]: crio.service: Failed with result 'exit-code'.
Apr 01 09:14:48 <HOSTNAME> systemd[1]: Failed to start Container Runtime Interface for OCI (CRI-O).
`
If i comment out the line `apparmor_profile = "crio-default"` in crio.conf, the service starts

**Steps to reproduce the issue:**
1. Install K8s 1.17
2. Install cri-o 1.17 from obs
3. Try to start crio

**Describe the results you received:**
`
-- Unit crio.service has begun starting up.
Apr 01 09:14:48 <HOSTNAME> crio[7882]: time="2020-04-01 09:14:48.773919363Z" level=fatal msg="config provided AppArmor profile \"crio-default\" not loaded"
Apr 01 09:14:48 <HOSTNAME> systemd[1]: crio.service: Main process exited, code=exited, status=1/FAILURE
Apr 01 09:14:48 <HOSTNAME> systemd[1]: crio.service: Failed with result 'exit-code'.
Apr 01 09:14:48 <HOSTNAME> systemd[1]: Failed to start Container Runtime Interface for OCI (CRI-O).
`

**Describe the results you expected:**
crio service starts

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**
```
crio version 1.17.2
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 18.04.4 LTS on AWS

**Comment by saschagrunert** [comment]
Hey @thschue thank you for the report. I think we can comment out the profile in the config per default.

@lsm5 can we change the config to comment out the AppArmor profile?

**Comment by lbogdan** [comment]
Also ran into this, and figured out it happens because the default profile is actually named `crio-default-1.17.2`, so you can either comment out the profile, or update its name.

**Comment by cortopy** [comment]
In the conf file this is explained:

```
# Used to change the name of the default AppArmor profile of CRI-O. The default
# profile name is "crio-default-" followed by the version string of CRI-O.
```

But it's misleading because the package in Ubuntu is `cri-o-1.17` and the apparmor profile is `crio-default-1.17.2`

**Comment by lsm5** [comment]
`1.17.2~2` has been built for the OBS testing repo. https://build.opensuse.org/package/show/devel:kubic:libcontainers:testing/cri-o-1.17 . If people could test and approve the build, I'll do the same build for the stable repo as well.

**Comment by jayaddison** [comment]
@lsm5 This affects me too, and I'm available to help with testing.

There's one requirement before getting started - I'd like to view the changes so that we can verify the fix.

When testing updates between CRI-O `v1.17.1` and `v1.17.2` it's useful to compare the [changes between those releases](https://github.com/cri-o/cri-o/compare/v1.17.1..v1.17.2) and test based on that.

Could you provide a similar link (in the [OBS package](https://build.opensuse.org/package/show/devel:kubic:libcontainers:testing/cri-o-1.17) or the [Fedora package source](https://src.fedoraproject.org/rpms/cri-o/)) to show what changed between binary package `1.17.2~1` and `1.17.2~2`?

**Comment by joshuafc** [comment]
I am a newer, trying install k8s follow https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
Now I ran into the plobrem, is there any workaround like edit `/usr/lib/systemd/system/crio.service`, so I can continue my k8s install study.

**Comment by joshuafc** [comment]
edit `/etc/crio/crio.conf`, 
change `apparmor_profile = "crio-default"` to `apparmor_profile = "crio-default-1.17.2"`
service start success now. 
Thanks @lbogdan .

**Comment by arthfl** [comment]
Is there some rough ETA for this?

**Comment by lsm5** [comment]
today

**Comment by lsm5** [comment]
I'm waiting on the tarball upload to OBS, following which OBS can build and ship new package. So, please wait some more...

**Comment by lsm5** [comment]
should be available now. I'm gonna close this. Please re-open in case the issue persists. Sorry about the lag.

**Comment by lbogdan** [comment]
@lsm5 Any particular reason `1.17.2~1` was removed? Is there a policy in place that specifies how long older packages are kept around / when they are removed?

**Comment by lsm5** [comment]
@lbogdan OBS doesn't preserve older debs when new packages are built. Keeping older packaging files in there at the same time would mean _nothing_ gets built and the older debs get wiped out too. Also, earlier I used to keep older files with a `.old` appended to it. But then it would quickly fill up.

You can fetch the older packaging files by checking out an older revision. For example: https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/cri-o-1.17?rev=26 . Hope that works for you.
