### ISSUE TITLE
Ansible Role for CRI-O

### ISSUE THREAD

**Issue by hswong3i** [cri-o/cri-o#3552]
I am now maintenance an Ansible Role for CRI-O installation (https://github.com/alvistack/ansible-role-cri_o), by downloading the static binary release archive and extract it for following OS:
- Ubuntu 16.04/18.04/19.10
- CentOS/RHEL 7/8
- openSUSE 15.1

Could we also introduce this as an alternative installation method, e.g. under https://github.com/cri-o/cri-o#installing-cri-o?

**Comment by saschagrunert** [comment]
Hey @hswong3i :wave:, sure do you mind opening a PR for that?

**Comment by hswong3i** [comment]
> Hey @hswong3i wave, sure do you mind opening a PR for that?

@saschagrunert  thank you for your interest and PR created (#3628) please kindly comment ;-)

**Comment by hswong3i** [comment]
As report from https://github.com/alvistack/ansible-role-cri_o/issues/1

> Need to cd into the newly created directory and then clone the repo
> 
> ```
> sudo su -
> mkdir -p ~/.ansible/roles
> cd  ~/.ansible/roles <-------------------------
> git clone https://github.com/alvistack/ansible-role-cri_o.git cri_o
> cd ~/.ansible/roles/cri_o
> pip3 install --upgrade --ignore-installed --requirement requirements.txt
> molecule converge
> molecule verify
> ```
