### ISSUE TITLE
Use proper variable for error return in Server#createSandboxContainer

### ISSUE THREAD

**Issue by tedyu** [cri-o/cri-o#3558]
**Description**
In Server#createSandboxContainer, the deferred func calls DeleteContainer if there is error.
Subsequently, some error is not assigned to the error variable which is checked by the deferred func.

Here is suggested change:
```
diff --git a/server/container_create_linux.go b/server/container_create_linux.go
index 13f0e0db9..02428dda3 100644
--- a/server/container_create_linux.go
+++ b/server/container_create_linux.go
@@ -440,13 +440,13 @@ func (s *Server) createSandboxContainer(ctx context.Context, containerID, contai
                return nil, err
        }

-       if err := addDevices(ctx, sb, containerConfig, privilegedWithoutHostDevices, &specgen); err != nil {
+       if err = addDevices(ctx, sb, containerConfig, privilegedWithoutHostDevices, &specgen); err != nil {
                return nil, err
        }

        labels := containerConfig.GetLabels()

-       if err := validateLabels(labels); err != nil {
+       if err = validateLabels(labels); err != nil {
                return nil, err
        }
```

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**
Container is properly deleted if there is error.

**Comment by tedyu** [comment]
There are several places in Server#createSandboxContainer (after line 440) where new error variable is used to store / check error.
Please confirm whether those places warrant deletion of the container upon return.

**Comment by haircommander** [comment]
oof, thanks for bringing this to light. I'm taking a look
