### ISSUE TITLE
Unable to retrieve the image spec using crictl inspecti 

### ISSUE THREAD

**Issue by vivekanandpoojari** [cri-o/cri-o#3567]
**Description**
crictl inspecti does not return the OCI imagespec.

**Steps to reproduce the issue:**
1. Install cri-o on a ubuntu machine
2. Pull busybox image
3. crictl inspecti ##busyBoxImageID##

**Describe the results you received:**
The inspect data does not include the OCI Image spec in the info 

```
crictl inspecti 83aa35aa1c79e
{
  "status": {
    "id": "83aa35aa1c79e4b6957e018da6e322bfca92bf3b4696a211b42502543c242d6f",
    "repoTags": [
      "docker.io/library/busybox:latest"
    ],
    "repoDigests": [
      "docker.io/library/busybox@sha256:afe605d272837ce1732f390966166c2afff5391208ddd57de10942748694049d",
      "docker.io/library/busybox@sha256:b26cd013274a657b86e706210ddd5cc1f82f50155791199d29b9e86e935ce135"
    ],
    "size": "1441595",
    "uid": null,
    "username": ""
  }
}
```

**Describe the results you expected:**
When I execute the same command on containerd runtime.
I get the complete OCI image spec.

```
crictl inspecti 83aa35aa1c79e
{
  "status": {
    "id": "sha256:83aa35aa1c79e4b6957e018da6e322bfca92bf3b4696a211b42502543c242d6f",
    "repoTags": [
      "docker.io/library/busybox:latest"
    ],
    "repoDigests": [
      "docker.io/library/busybox@sha256:b26cd013274a657b86e706210ddd5cc1f82f50155791199d29b9e86e935ce135"
    ],
    "size": "764687",
    "uid": null,
    "username": ""
  },
  "info": {
    "chainID": "sha256:a6d503001157aedc826853f9b67f26d35966221b158bff03849868ae4a821116",
    "imageSpec": {
      "created": "2020-03-10T00:19:33.019716493Z",
      "architecture": "amd64",
      "os": "linux",
      "config": {
        "Env": [
          "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
        "Cmd": [
          "sh"
        ]
      },
      "rootfs": {
        "type": "layers",
        "diff_ids": [
          "sha256:a6d503001157aedc826853f9b67f26d35966221b158bff03849868ae4a821116"
        ]
      },
      "history": [
        {
          "created": "2020-03-10T00:19:32.83969331Z",
          "created_by": "/bin/sh -c #(nop) ADD file:450bea8cddb743ed282cb1ade3d1614033172b93ef531c69a4e49fda3016cef0 in / "
        },
        {
          "created": "2020-03-10T00:19:33.019716493Z",
          "created_by": "/bin/sh -c #(nop)  CMD [\"sh\"]",
          "empty_layer": true
        }
      ]
    }
  }
}
```

Is this an expected behvaiour from cri-o ?
What would be another way for a C++ application to fetch the image layers, OCI image spec ?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.17.2
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu ECS Instance (AWS)
Ubuntu version : 
```
cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by saschagrunert** [comment]
Hey @vivekanandpoojari, the `info` field in the `ImageStatusReponse` is currently not used for the OCI image spec in CRI-O:
https://github.com/cri-o/cri-o/blob/e94c67fbeefaa33117805466d346af58b05909a1/vendor/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.pb.go#L5196-L5200

In the upcoming release we add the image labels to this field so we might have some overlap here. 

We probably want to switch to include the full OCI spec into the info field, @mrunalp @haircommander ?

**Comment by vivekanandpoojari** [comment]
There is currently no way for a C++ application to retrieve the image layers in cri-o runtime.
I dont want to ship additional dependencies like podman or buildah into my container.

**Comment by saschagrunert** [comment]
I see, fix is incoming in https://github.com/cri-o/cri-o/pull/3570

**Comment by vivekanandpoojari** [comment]
Hi,
Thank you for the quick turn around on this.
Can we expect this fix to be back ported to 1.16 or 1.17 ?
We have customers using this version of cri-o.
--Vivekanand

**Comment by saschagrunert** [comment]
Hey, from my perspective this is clearly a feature and we should not backport such changes with patch releases. In any case I'd like to leave room for discussion and would like to hear @mrunalp and @haircommander 's opinions as well :)

**Comment by vivekanandpoojari** [comment]
Assuming this is not going to be backported, 
how can a c++ containerised app fetch this information ?

@saschagrunert , @mrunalp @haircommander

**Comment by haircommander** [comment]
what information are you looking for? Is podman an option here?

**Comment by vivekanandpoojari** [comment]
@haircommander : I think I can use the podman api InspectImage via the varlink C binding.
podman inspect image returns the OCI config for an image.
However there is no workaround for #3568. Podman does not recognise the cri-o containers.
Is there any way in which a containerised application can view the runtime spec of other containers , assuming we have enough privileges ? In containerd its a simple inspect call via cri gRPC api.

**Comment by saschagrunert** [comment]
Hm, you could lookup them on disk based on your storage configuration:
```
root # jq . /var/lib/containers/storage/overlay-containers/$CONTAINER_ID/userdata/config.json
```

**Comment by vivekanandpoojari** [comment]
Hmm ok. Thanks @saschagrunert .
