### ISSUE TITLE
Add SECURITY.md (security disclosure policy)

### ISSUE THREAD

**Issue by caniszczyk** [cri-o/cri-o#3573]
Please add a security disclosure policy.

I see a SECURITY_CONTACTS file in there that's a start.

**Comment by saschagrunert** [comment]
@haircommander @mrunalp do we have something from other `containers/*` projects which we can use here? :thinking:

**Comment by haircommander** [comment]
libpod only has https://github.com/containers/libpod/#communications

Maybe we could create a similar list on crio.io (security@crio.io

@caniszczyk do any other CNCF projects have a security.md? I looked at etcd, prometheus, containerd and kubernetes, none of which have one. I am mostly asking to know what typically is in a security disclosure policy that isn't covered in SECURITY_CONTACTS

**Comment by TomSweeneyRedHat** [comment]
The only one I found is https://github.com/containers/crun/blob/master/SECURITY.md which is similar to the libpod entry that @haircommander pointed out.

I'd be happy to basically steal the one in crun and add it to all of the containers/* projects and also crio if that works for everyone.  I'd vote for using the security@podman.io list, but could be dissuaded to use something else. 

I'd suggest doing like we did for the Code of Conduct.  Make one file in containers/common and then add a security.md file to each project pointing at it.

**Comment by caniszczyk** [comment]
Kubernetes doesn't have one in a SECURITY.md file yet but it will, it's here: https://kubernetes.io/docs/reference/issues-security/security/

See Envoy as a complex example: https://github.com/envoyproxy/envoy/blob/master/SECURITY.md

**Comment by TomSweeneyRedHat** [comment]
I've started one for the Containers project here:  https://github.com/containers/common/pull/117
We can add/manipulate that into CRI-O if desired.

**Comment by haircommander** [comment]
done here https://github.com/cri-o/cri-o/blob/main/SECURITY.md
