### ISSUE TITLE
crictl stats return pod memory usage not per container

### ISSUE THREAD

**Issue by Nefelim4ag** [cri-o/cri-o#3580]
CRI-O: 1.17.2
K8s: 1.16.8
Cgroup driver: systemd

We found what `kubectl top pods --containers` return same cpu/memory usage for all containers in POD, after i check that by running crictl stats for 2 containers in same pod

```
root@K8S-N1:~# crictl ps | grep f432ef16bf3ca
538fbb2396de1       013718a8b3d932355c501429b8e58d0e27597070371ca5a0308ca1af24af0f01                                                         About an hour ago   Running             nginx                      0                   f432ef16bf3ca
168141c76d71c       9f1e244751343bbb999ac715eea9c7cd946f532b19e45097c4a86951f4757cff                                                         About an hour ago   Running             kube-proxy                 0                   f432ef16bf3ca

root@K8S-N1:~# crictl stats 538fbb2396de1
CONTAINER           CPU %               MEM                 DISK                INODES
538fbb2396de1       5.49                30.65MB             8.194kB             3

root@K8S-N1:~# crictl stats 168141c76d71c
CONTAINER           CPU %               MEM                 DISK                INODES
168141c76d71c       0.15                30.58MB             32.77kB             10

root@K8S-N1:~# crictl stats --pod f432ef16bf3ca
CONTAINER           CPU %               MEM                 DISK                INODES
```

So that's looks like CRI-O internal error with collecting/store metrics

Thanks

**Comment by mrunalp** [comment]
@Nefelim4ag What is the path to your `crio.sock` ?

**Comment by Nefelim4ag** [comment]
@mrunalp, `unix:///run/crio/crio.sock`

Does that matter?

**Comment by mrunalp** [comment]
Yes, if it is `/var/run/crio/crio.sock` then it will use cadvisor vs. any other path will make it use cri stats. Can you try with `/var/run/crio/crio.sock`? We may have a bug in cri stats that you are hitting.

**Comment by haircommander** [comment]
@dougsland PTAL

**Comment by Nefelim4ag** [comment]
@mrunalp, are you sure?
That's just ubuntu machine with debian packages

```
root@K8S-N1:~# ls -al /var/run
lrwxrwxrwx 1 root root 4 Apr  7 14:15 /var/run -> /run
```

**Comment by haircommander** [comment]
I don't think it's smart enough to resolve symlinks. It's doing a string comparison. it's an age old hack done in cadvisor:
https://github.com/kubernetes/kubernetes/blob/87eb688ec921fe20a93a25803f08f223fba3d4ee/pkg/kubelet/cadvisor/util.go#L78
So I would expect this is CRI stats behavior, not cadvisor. You could verify by changing the path to `unix:///var/run/crio/crio.sock`

**Comment by Nefelim4ag** [comment]
@haircommander, i test crictl for both path, no difference

Will test kubelet, sec

**Comment by haircommander** [comment]
yes `crictl stats` should always use cri stats, as cadvisor is baked into the kubelet

**Comment by Nefelim4ag** [comment]
You are right, change path to `/var/run` in kubelet fix metrics issue

**Comment by haircommander** [comment]
okay cool, we still have a cri-o bug, but glad to know you can get something working :+1:

**Comment by DevasiaThomas** [comment]
I'm not sure if should raise another one, but can the stats also show the memory limit on the container? OR the total host memory if there is no limit.

**Comment by haircommander** [comment]
seems like separate issue @DevasiaThomas

**Comment by karthikg1978** [comment]
HI,

is there update on this. Still crictl stats provides POD usage not the container usage. Can you suggest any other method to find out container level usage. 

Regards
Karthik

**Comment by haircommander** [comment]
what version are you using @karthikg1978 ? https://github.com/cri-o/cri-o/pull/3933 should be in 1.19.0

**Comment by karthikg1978** [comment]
Thank you for the update. We are running with 1.17.4-17. Let me check with 1.19.0 and update
