### ISSUE TITLE
[1.17/1.18] Only musl Static Binary Works with Ubuntu

### ISSUE THREAD

**Issue by hswong3i** [cri-o/cri-o#3614]
**Description**

Starting with CRI-O 1.17.x release we could download the statically build binary from release page, with musl/glibc (1.17.x) or glibc only (1.18.0-rc1).

BTW, glibc version not always functioning as expected; only musl version always works, e.g.

**Steps to reproduce the issue:**
1. OK: CentOS 7/8 + CRI-O 1.17.x musl static binary
2. OK: CentOS 7/8 + CRI-O 1.17.x/1.18.x glibc static binary
3. OK: Ubuntu 18.04/19.10/20.04 + CRI-O 1.17.x musl static binary
4. FAILED: Ubuntu 18.04/19.10/20.04 + CRI-O 1.17.x/1.18.x glibc static binary

P.S. On the other hand, compile and install from source code ALWAYS works with both CentOS/RHEL/openSUSE/Ubuntu.

**Describe the results you received:**

Ubuntu with glibc static binary + `systemctl start crio` return with no error; BTW, `kubeadm init` not functioning since not able to pull image (seems related with #3612?)

**Describe the results you expected:**

Both musl or glibc should able to start as systemd service + `kubeadm init` functioning.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Test running as Ansible Role with KVM + libvirt at Travis CI: https://travis-ci.com/github/alvistack/ansible-role-kube_master/builds/160485753

Once rolling back as source code based build and installation all OS functioning correctly: https://travis-ci.com/github/alvistack/ansible-role-kube_master/builds/160827011

**Comment by saschagrunert** [comment]
Hey @hswong3i, have you tried the workaround mentioned there:
https://github.com/cri-o/cri-o/issues/3612#issuecomment-615843431

**Comment by hswong3i** [comment]
> Hey @hswong3i, have you tried the workaround mentioned in [#3612 (comment)](https://github.com/cri-o/cri-o/issues/3612#issuecomment-615843431)?

@saschagrunert I read that but not try that yet, because from my point of view native source build is functioning and release provided package should be also functioning out-of-the-box ;-)

**Comment by saschagrunert** [comment]
This issue should be fixed with v1.18.0 (or rc2). Closing this now and feel free to reopen if there is anything else I can do.
