### ISSUE TITLE
[1.18] unable to run pod - "cannot generate pod name without uid in metadata"

### ISSUE THREAD

**Issue by miabbott** [cri-o/cri-o#3618]
The RHEL CoreOS team has sanity tests for `cri-o` that started failing when we moved to `cri-o` 1.18

Our previous configuration (pod template/container template) no longer works with 1.18.  We are getting failures like:

```
            cluster.go:141: time="2020-04-20T18:01:00Z" level=fatal msg="run pod sandbox failed: rpc error: code = Unknown desc = setting pod sandbox name and id: cannot generate pod name without uid in metadata"
```

The error seems to match 2d5cedabe81ee94f4eef4c1656177faa542f9d1b

I suspect we'll be told to update our templates, but filing an issue to track the issue going from 1.17 to 1.18 for us.

**Comment by haircommander** [comment]
@miabbott did you hit this on an upgrade? what's the template?

**Comment by hswong3i** [comment]
I had upgrade my Ubuntu 18.04 + Kubernetes 1.17.5 + CRI-O 1.17.3, into Kubernetes 1.18.2 + CRI-O 1.18.0-RC1 successfully.

P.S. once upgraded all pod failed with “some” reason that I didn’t dig into it; as usual I reboot all nodes one by one, then kill all running pods once; after that everything resume as normal, even follow with another few rounds of reboot or pod restart.

**Comment by miabbott** [comment]
@haircommander Yeah, hit this when RHCOS went from `cri-o` 1.17 to 1.18

Template:

```json
{
	"metadata": {
		"name": "rhcos-crio-pod-%s",
		"namespace": "redhat.test.crio"
	},
	"image": {
			"image": "localhost/%s:latest"
	},
	"args": [],
	"readonly_rootfs": false,
	"log_path": "",
	"stdin": false,
	"stdin_once": false,
	"tty": false,
	"linux": {
			"resources": {
					"memory_limit_in_bytes": 209715200,
					"cpu_period": 10000,
					"cpu_quota": 20000,
					"cpu_shares": 512,
					"oom_score_adj": 30,
					"cpuset_cpus": "0",
					"cpuset_mems": "0"
			},
			"cgroup_parent": "Burstable-pod-123.slice",
			"security_context": {
					"namespace_options": {
							"pid": 1
					},
					"capabilities": {
							"add_capabilities": [
								"sys_admin"
							]
					}
			}
	}
}
```

**Comment by haircommander** [comment]
master PR [here](https://github.com/cri-o/cri-o/pull/3774) I'll backport to 1.18 when it merges
