### ISSUE TITLE
Ubuntu 20.04 packages

### ISSUE THREAD

**Issue by marshallford** [cri-o/cri-o#3629]
FYI: Ubuntu 20.04 LTS is expected to be [released tomorrow](https://wiki.ubuntu.com/FocalFossa/ReleaseSchedule). Perhaps 20.04 could be added to the build/publish process?

Currently the repo URL is returning a 404: `http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/`.

Thank you!

**Comment by haircommander** [comment]
thanks for the heads up @marshallford 

PTAL @lsm5

**Comment by lsm5** [comment]
> FYI: Ubuntu 20.04 LTS is expected to be [released tomorrow](https://wiki.ubuntu.com/FocalFossa/ReleaseSchedule). Perhaps 20.04 could be added to the build/publish process?
> 
> Currently the repo URL is returning a 404: `http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/`.
> 
> Thank you!

@marshallford yup, that's because OBS admins will first need to setup 20.04 repos. We can enable builds for it soon as that's done. 

btw, @dougsland will be the go-to for OBS cri-o builds going forward and I'll back him up wherever possible.

**Comment by gattytto** [comment]
I use this in my Ubuntu 20.04 LXC images:
````
deb http://ppa.launchpad.net/projectatomic/ppa/ubuntu disco main 
deb http://ftp.lysator.liu.se/pub/opensuse/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_19.10/ / 
````

**Comment by marshallford** [comment]
Looks like Ubuntu 20.04 builds are up: `http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/`
