### ISSUE TITLE
.tar.gz artifacts (on GitHub) are gzipped twice

### ISSUE THREAD

**Issue by nealey** [cri-o/cri-o#3634]
**Description**

Releases (appear to be called "artifacts" in the source tree) are gzipped twice. They should either only be gzipped once, or named `.tar.gz.gz`.

**Steps to reproduce the issue:**
1. Locate a .tar.gz file at https://github.com/cri-o/cri-o/releases
2. Download it someplace
3. `zcat $file | zcat | tar tv`

For instance:

    curl -sL https://github.com/cri-o/cri-o/releases/download/v1.17.4/crio-fe61deb85.tar.gz | zcat | zcat | tar xv

**Describe the results you received:**

I had to zcat the release twice, even though it was named `.tar.gz` (and not `.tar.gz.gz`)

**Describe the results you expected:**

I thought `tar xvzf file.tar.gz` would uncompress and unpack, like it usually does far `.tar.gz` files :)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

Appears to be the case for everything on the first releases page of Github (1.17.0 through 1.17.4). I didn't check any further back.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by haircommander** [comment]
extra compression!

thanks for the issue;
@saschagrunert I've been using the artifacts bundle, do you know why it would be double zipped?

**Comment by saschagrunert** [comment]
> @saschagrunert I've been using the artifacts bundle, do you know why it would be double zipped?

Do you use Firefox for the download? There is a difference content-type behavior which caused do double-compress on download: https://bugzilla.mozilla.org/show_bug.cgi?id=1470011

Did you download them from CircleCI?

**Comment by haircommander** [comment]
ah yes, I did download them from firefox, and download them directly from circle

**Comment by nealey** [comment]
I can not reproduce this bug based on my initial report. The most current release is only gzipped once.
