### ISSUE TITLE
fix check for rw mounts test

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#3662]
sometime today, the test `privileged ctr -- check for rw mounts` started failing in integration_{fedora,rhel} because `/sys/fs/cgroup` was not mounted `ro` by runc. Oddly, the test is named "check for rw mounts", but switching the grep line to `rw` makes it fail with crun.

instead of tracking down the source of the issue, I've made the test nearly no-op, by just catting /proc/mounts [here](https://github.com/cri-o/cri-o/pull/3661)

We should determine what is expected by that test, and figure out which runtime is wrong.

**Comment by kolyshkin** [comment]
Alas, the test itself is wrong. It is supposed to run a privileged container, and commit d3a50d86 (PR #2627) even adds the `test/testdata/container_config_privileged.json` file, but it is not used by the test.

I am looking into it.
