### ISSUE TITLE
CentOS 8: undefined: errors.Is

### ISSUE THREAD

**Issue by sysopsdev** [cri-o/cri-o#3664]
**Description**
Cannot build from source on CentOS 8

**Steps to reproduce the issue:**
1. sudo dnf config-manager --set-enabled PowerTools && sudo dnf install epel-release
2. Install required packages for CentOS 
3. Clone cri-o repo
4. cd into repo and run make

**Describe the results you received:**
`vendor/k8s.io/apimachinery/pkg/util/errors/errors.go:99:10: undefined: errors.Is`
`make: *** [Makefile:168: bin/crio] Error 2`

**Describe the results you expected:**
CRI-O to build

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
# Not able to build or install 
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by saschagrunert** [comment]
Hey @sysopsdev, I think you have to update golang to be at least 1.13.

**Comment by sysopsdev** [comment]
@saschagrunert Well that's embarrassing lol. Please close, unlist, and delete my shame :) 

Thank you! That seems to have worked.

**Comment by saschagrunert** [comment]
> @saschagrunert Well that's embarrassing lol. Please close, unlist, and delete my shame :)
> 
> Thank you! That seems to have worked.

No worries, every question is very welcome :)
