### ISSUE TITLE
CRI-O 1.18 packaging

### ISSUE THREAD

**Issue by chrstnwhlrt** [cri-o/cri-o#3685]
Is there any ETA for the version 1.18 hitting the OBS / prebuilt availability?

**Comment by dougsland** [comment]
@chrstnwhlrt which distro are you looking? CentOS ?

**Comment by dougsland** [comment]
Just to share, CentOS8 needs to ship golang1.13. It's required for CRI-O 1.18. We are waiting for that.

**Comment by chrstnwhlrt** [comment]
I am using CRI-O with a Ubuntu Server Cluster, currently redeploying on the latest 20.04 LTS.

**Comment by dougsland** [comment]
> I am using CRI-O with a Ubuntu Server Cluster, currently redeploying on the latest 20.04 LTS.

Yeah, I am working on the Ubuntu stay tuned.

**Comment by mazzystr** [comment]
I was just about to create a similar issue.  Over in KubeVirt land we have a need to test CentOS 8 & minikube --driver=none --container-runtime=cri-o

**Comment by chrstnwhlrt** [comment]
Compiling CRI-O is not that hard but I would really prefer using the packaged version for production usage

**Comment by haircommander** [comment]
we also have static binaries available, but yes 1.18 packaging through OBS coming soon

**Comment by dougsland** [comment]
@chrstnwhlrt @mazzystr just uploaded the testing branch, sorry the delay. Getting all bits about OBS from @lsm5 .

Could you please give a try in the testing branch:

```
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/testing:/cri-o:/1.18/xUbuntu_20.04/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:testing:cri-o:1.18.list"
wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:testing:cri-o:1.18/xUbuntu_20.04/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt-get update
sudo apt-get install cri-o
```

**Comment by Sh4d1** [comment]
@dougsland do you also manage cri-o-1.17 and cri-o-1.16 patch release on Ubuntu?

**Comment by chrstnwhlrt** [comment]
Thank you for the amd64 builds, do you know when the arm64 builds will be available? Is it safe to use the testing builds for now and upgrade later to the stable builds?

**Comment by hswong3i** [comment]
In case if you can't wait for prebuild packages + willing to compile from CRI-O's release source code + some basic knowledge with Ansible, my Ansible Role and Collection may be your cup of tea:
- https://github.com/cri-o/cri-o/blob/master/tutorials/setup.md#install-with-ansible
- https://github.com/alvistack/ansible-role-cri_o
- https://github.com/alvistack/ansible-collection-kubernetes

**Comment by dougsland** [comment]
> Thank you for the amd64 builds, do you know when the arm64 builds will be available? Is it safe
>  to use the testing builds for now and upgrade later to the stable builds?

Should be landed in stable too (with arm64 support) please let us how it goes.
```
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.18/xUbuntu_20.04/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:1.18.list"
wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.18/xUbuntu_20.04/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt-get update
sudo apt-get install cri-o
```

**Comment by dougsland** [comment]
> @dougsland do you also manage cri-o-1.17 and cri-o-1.16 patch release on Ubuntu? (On ubuntu
> 18.04)

I should be able to help. What's your question?

**Comment by Sh4d1** [comment]
@dougsland the latest patch versions are not available (I think its 1.17.2 and 1.16.2 right now only)

**Comment by dougsland** [comment]
> @dougsland the latest patch versions are not available (I think its 1.17.2 and 1.16.2 right now only)

Okay, please open a different issue. This one is about 1.18 for Ubuntu. I am going to start working on that.

**Comment by dougsland** [comment]
> > Thank you for the amd64 builds, do you know when the arm64 builds will be available? Is it safe
> > to use the testing builds for now and upgrade later to the stable builds?
> 
> Should be landed in stable too (with arm64 support) please let us how it goes.
> 
> ```
> sudo sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.18/xUbuntu_20.04/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:1.18.list"
> wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.18/xUbuntu_20.04/Release.key -O Release.key
> sudo apt-key add - < Release.key
> sudo apt-get update
> sudo apt-get install cri-o
> ```

@chrstnwhlrt please consider closing the ticket if your issue was addressed. Thanks!

**Comment by chrstnwhlrt** [comment]
@dougsland Thanks for the packaging! Just to clarify: The new repository holds just a few packages, am I supposed to use both repositories? Are all dependencies resolved using just this repo?

**Comment by dougsland** [comment]
> @dougsland Thanks for the packaging! Just to clarify: The new repository holds just a few
> packages, am I supposed to use both repositories? Are all dependencies resolved using just this > repo?
> 
> _EDIT_
> **Repo A:**
> http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/
> **Repo B:**
> http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-
> o:/1.18/xUbuntu_20.04/

@chrstnwhlrt  Yes, just confirmed, for dependencies.

**Comment by Sh4d1** [comment]
@dougsland is Ubuntu 18.04 planned too?

**Comment by dougsland** [comment]
> @dougsland is Ubuntu 18.04 planned too?

CRI-O 1.18 requires golang 1.13 at least which it seems not shipped to Ubuntu != 20.04. Please correct me if I am wrong.

**Comment by Sh4d1** [comment]
It's correct, but there is no workaround? (Not familiar with the internals of Ubuntu package)

**Comment by dougsland** [comment]
> It's correct, but there is no workaround? (Not familiar with the internals of Ubuntu package)

Probably manually build golang and CRI-O.

**Comment by chrstnwhlrt** [comment]
@dougsland Thanks for  the work, I will test the Ubuntu 20.04 build with the next deployment in the coming days for arm64 and amd64.
