### ISSUE TITLE
Error in make on RHEL7

### ISSUE THREAD

**Issue by vbmade2000** [cri-o/cri-o#369]
I am facing below error while executing "make" on my RHEL7 system. I am following tutorial given in README.md file.

[mvora@macsystem cri-o]$ make
go build -o ocid \
	-tags "selinux seccomp  libdm_no_deferred_remove" \
	github.com/kubernetes-incubator/cri-o/cmd/ocid
 github.com/kubernetes-incubator/cri-o/vendor/github.com/containers/storage/pkg/devicemapper
/usr/bin/ld: cannot find -ldevmapper
collect2: error: ld returned 1 exit status
# github.com/kubernetes-incubator/cri-o/vendor/github.com/mtrmac/gpgme
vendor/github.com/mtrmac/gpgme/data.go:4:20: fatal error: gpgme.h: No such file or directory
 // #include <gpgme.h>
                    ^
compilation terminated.
# pkg-config --cflags libseccomp libseccomp
Package libseccomp was not found in the pkg-config search path.
Perhaps you should add the directory containing `libseccomp.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libseccomp' found
Package libseccomp was not found in the pkg-config search path.
Perhaps you should add the directory containing `libseccomp.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libseccomp' found
pkg-config: exit status 1
make: *** [ocid] Error 2

When I try to install libseccomp it returns following.

Package libseccomp-2.3.1-2.el7.x86_64 already installed and latest version
Nothing to do

**Comment by runcom** [comment]
did you installed all packages listed here? https://github.com/kubernetes-incubator/cri-o#build

**Comment by vbmade2000** [comment]
Yes I did. Most of the packages I found from some other sites as they were not available in repo.
Regarding libseccomp it is raising error about, following is an output of "yum list installed" command.

[mvora@macsystem cri-o]$ yum list installed | grep "libseccomp"
libseccomp.x86_64                    2.3.1-2.el7             @rhel-7-server-rpms
libseccomp-devel.i686                2.3.1-2.el7             installed

**Following is list of sources for various dependencies.**
#install ex2fs if not installed
sudo yum install e2fsprogs-devel

#install blkid package if not installed
sudo yum install libblkid-devel

#install zlib if not installed
sudo yum install zlib-devel

#install lzo if not installed
sudo yum install lzo

#install llzo2 library if not installed
ftp://bo.mirror.garr.it/1/slc/centos/7.1.1503/os/x86_64/Packages/lzo-devel-2.06-6.el7_0.2.x86_64.rpm

#install btrfs dependecies
https://btrfs.wiki.kernel.org/index.php/Btrfs_source_repositories#Fedora

#install asciidoc package if not installed
https://www.rpmfind.net/linux/rpm2html/search.php?query=asciidoc
 
#install/buildbtrfs
https://www.cyberciti.biz/faq/how-to-build-and-install-the-latest-version-of-btrfs-tools-on-linux/

#install device-mapper-devel
https://rpmfind.net/linux/rpm2html/search.php?query=device-mapper-devel

#install glib2-devel
sudo yum install glib2-devel

#install glibc-devel
Raises already installed due to glib2-devel

#install glibc-static
https://www.rpmfind.net/linux/rpm2html/search.php?query=glibc-static

#install gpgme-devel
ftp://195.220.108.108/linux/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/g/gpgme-devel-1.8.0-12.fc26.i686.rpm

#install libassuan-devel
ftp://mirror.switch.ch/pool/4/mirror/centos/7.3.1611/os/x86_64/Packages/libassuan-devel-2.1.0-3.el7.x86_64.rpm

#install libgpg-error-devel
libgpg-error-devel

#install pkgconfig
http://rpm.pbone.net/index.php3/stat/4/idpl/26646110/dir/centos_7/com/pkgconfig-0.27.1-4.el7.x86_64.rpm.html

#install libseccomp-devel
https://centos.pkgs.org/7/centos-x86_64/libseccomp-devel-2.3.1-2.el7.i686.rpm.html

**Comment by rhatdan** [comment]
libseccomp-devel?

**Comment by vbmade2000** [comment]
In order to enable seccomp support as per README.md

**Comment by jawnsy** [comment]
@vbmade2000 I wouldn't recommend installing CentOS packages on RHEL (or vice versa), as packages are only built/tested with other packages from the same distro. What version of RHEL are you running? I tested with 7.4 Beta (Maipo) and the only problem I ran into was an old runc version, which has been fixed recently.

**Comment by jawnsy** [comment]
Try running: `pkg-config libseccomp --libs`, you should see `-lseccomp` (if you see "No package found" then the .pc file hasn't been installed correctly)

**Comment by gouyang** [comment]
@vbmade2000 I could make ocid binaries on RHEL7 after installing the dependencies, so it should not be the ocid problem.

**Comment by vbmade2000** [comment]
I am setting up on Fedora now instead of RHEL. We can close this issue.

**Comment by mjudeikis** [comment]
2020 and this still an issue on rhel :/

**Comment by haircommander** [comment]
which issue? the gpgme or the seccomp dependency?

**Comment by mjudeikis** [comment]
I moved to rhel7 as I was not able to compile anything on rhel7 due to missing deps. seccomp was the issue

**Comment by haircommander** [comment]
can you post more of your output? also, what happens if you run `BUILDTAGS='selinux' make` (i.e, omitting the seccomp build tag)

**Comment by mjudeikis** [comment]
Sadly I cant. Passed this phase and removed the setup. If I get back to rhel7, for sure will try again and post here.

**Comment by haircommander** [comment]
I'm closing this (age old) issue for now then. Please open a new issue with more details if you see it again!

**Comment by mjudeikis** [comment]
@haircommander:
```
[root@ci-000000 ARO-RP]# BUILDTAGS='selinux' make aro
go generate ./...
../pkg/deploy/bindata.go
writing ../../pkg/install/assets_vfsdata.go
deploy/bindata.go
bindata.go
go build -ldflags "-X github.com/Azure/ARO-RP/pkg/util/version.GitCommit=bb28e90" ./cmd/aro
# github.com/Azure/ARO-RP/vendor/github.com/mtrmac/gpgme
vendor/github.com/mtrmac/gpgme/data.go:4:20: fatal error: gpgme.h: No such file or directory
 // #include <gpgme.h>
                    ^
compilation terminated.
make: *** [aro] Error 2
```
Linux ci-000000 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 11 19:12:04 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

Libarary we use: `"github.com/containers/image/types"`

```
[root@ci-000000 ARO-RP]# yum search libseccomp
Loaded plugins: langpacks, product-id, search-disabled-repos
============================================================== N/S matched: libseccomp ==============================================================
libseccomp.i686 : Enhanced seccomp library
libseccomp.x86_64 : Enhanced seccomp library

  Name and summary matches only, use "search all" for everything.
```
libseccomp-devel is not available in RHUI

**Comment by haircommander** [comment]
do you have `gpgme-devel`? it's not failing on seccomp but gpgme.h not being installed

**Comment by mjudeikis** [comment]
we ended solving it with `CGO_CFLAGS="-Dgpgme_off_t=off_t"` and `gpgme-devel libassuan-devel` packages
