### ISSUE TITLE
RFC:  container image pull speed metric

### ISSUE THREAD

**Issue by jeremyeder** [cri-o/cri-o#3697]
**Description**

For rollouts, particularly of new daemonsets (since they are roughly simultaneous pulls to every node), we are lacking visibility into what our pull performance looks like.

Do folks think it would be possible to add this metric?

**Comment by haircommander** [comment]
seems simple enough wdyt @saschagrunert

**Comment by saschagrunert** [comment]
Yes this can be added on top of the existing image pull metric. Should I take care of that?

**Comment by jeremyeder** [comment]
I'm only a user here.  If you can, please do take care of it?

**Comment by saschagrunert** [comment]
Sounds good to me! :)

**Comment by saschagrunert** [comment]
@jeremyeder if you need the metric per container image, then the byte counter `crio_image_pulls_by_name` could be used to get the download rate:
```
rate(container_runtime_crio_image_pulls_by_name{job="cri-o"}[1m])
```
Does this already fit for you or do you need anything else?

**Comment by haircommander** [comment]
I believe we have this
