### ISSUE TITLE
Cgroup Manage default change in 1.18.0

### ISSUE THREAD

**Issue by Sh4d1** [cri-o/cri-o#3719]
**Description**
The default cgroup manager change from 1.17 to 1.18 (and nothing in the changelog? :thinking: ) Is it wanted?

**Describe the results you received:**
```
# crio --version
crio version 
Version:       1.18.0
GitCommit:     7d79f42b28ad00cf2e7d86604a5a4007303ac328
GitTreeState:  clean
BuildDate:     2020-05-04T11:59:30Z
GoVersion:     go1.14.2
Compiler:      gc
Platform:      linux/amd64
Linkmode:      unknown: `ldd /root/crio` failed: ldd: /root/crio: No such file or directory
  (exit status 1)

# crio --help | grep "cgroup-manager"
   --cgroup-manager value        cgroup manager (cgroupfs or systemd) (default: "systemd") [$CONTAINER_CGROUP_MANAGER]
```

```
# crio --version
crio version 1.17.4
commit: "16a05aafdf5d8fb84942ca60497818949b711cbc"

# crio --help | grep "cgroup-manager"
   --cgroup-manager value        cgroup manager (cgroupfs or systemd) (default: "cgroupfs") [$CONTAINER_CGROUP_MANAGER]
```

**Describe the results you expected:**
The default not to chane

**Comment by haircommander** [comment]
ah! thanks for the report @Sh4d1 and sorry for the poor communication. In the last release, we switched our release-notes generation tool, but the commit making the default change (https://github.com/cri-o/cri-o/pull/3137) came in before making that switch, and was thus missed in the release notes. 

this change was expected and desired, we believe systemd is a better cgroup manager. Now that we've fully switched to the new release-notes generator, we shouldn't have this communication problem again.

**Comment by haircommander** [comment]
@Sh4d1 is there any action you'd like us to take, or are you alright with me closing this ticket?

**Comment by Sh4d1** [comment]
I'll close :)

**Comment by haircommander** [comment]
thank you for the report!

**Comment by oldthreefeng** [comment]
Is there any General method to check `contianerd` or `cri-o `or `docker` cgroupDriver ? 

for docker.
```
cgroupDriver=$(docker info|grep Cg)
driver=${cgroupDriver##*: }
echo "driver is ${driver}"
```

**Comment by haircommander** [comment]
not generic, but you can do
`crio config | grep cgroup`
for crio
