### ISSUE TITLE
Cni network namespace is not removed after deleting a pod in cri-o 1.14.11-1.16.6

### ISSUE THREAD

**Issue by korivka** [cri-o/cri-o#3736]
**Description**
Cni network namespace is not being removed after deleting a pod. This results in pods getting new IP addresses each time they are added and old IP addresses not being recycled

**Steps to reproduce the issue:**
1. Add a pod that doesn't use host ip
2. Run ip netns to check that cni namespace was created for the pod
3. Delete the pod
2. /var/run/netns/ contains namespaces of deleted pods

**Describe the results you received:**
Every time a new pod is created, new namespace is added but it doesn't get removed on pod delete

**Describe the results you expected:**
Pod namespace should be removed on pod deletion

Testing with cri-o v 1.14.10
Cni plugin: https://github.com/lyft/cni-ipvlan-vpc-k8s v 0.6.3

**Additional information you deem important (e.g. issue happens only occasionally):**
In 1.14.11 containernerworking was updated to v0.8.2. 
One of the changes that was made was a change in namespace management https://github.com/containernetworking/plugins/commit/a0eac8d7d990adc7621e6ac0adf8b351e6e6c34b
NS creation code was moved to crio as part of this https://github.com/cri-o/cri-o/commit/8cd1763a504c8dcf09909d2ced77285fabd4c972
UnmountNS was not moved https://github.com/containernetworking/plugins/commit/a0eac8d7d990adc7621e6ac0adf8b351e6e6c34b#diff-4d866d7b5450b9c19b2c89c7e90ec8e0R135

**Output of `crio --version`:**
Tried with different crio versions 1.14.10 works fine. 1.14.11-1.16.6 have this issue

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by tedyu** [comment]
Do you see the following in the log ?
```
		if err := unix.Unmount(nsPath, unix.MNT_DETACH); err != nil {
			return fmt.Errorf("failed to unmount NS: at %s: %v", nsPath, err)
```

**Comment by mrunalp** [comment]
@haircommander ptal

**Comment by haircommander** [comment]
@korivka are you running with `manage_network_ns_lifecycle` set in your crio.conf?

**Comment by korivka** [comment]
manage_network_ns_lifecycle is set to true

not seeing 'failed to unmount NS' errors in the logs 

Deleting `if n.restored ` check in Remove method so that unmount gets called every time fixes the issue
https://github.com/korivka/cri-o/commit/e1eed0e708d136948d31b6d653b2b020e8f84a7b fixes the issue

**Comment by haircommander** [comment]
did you mean to close this?

**Comment by haircommander** [comment]
Would you like to submit a PR with the fix?
