### ISSUE TITLE
Centos 7 repos gone

### ISSUE THREAD

**Issue by mclarkson** [cri-o/cri-o#3740]
Centos 7 repos have gone from 'download.opensuse.org/repositories', as referenced by the main page on this repo.

**Steps to reproduce the issue:**
1. Try to use the curl commands mentioned in https://github.com/cri-o/cri-o#installing-cri-o

**Describe the results you received:**

404 - repo not found

**Describe the results you expected:**

downloaded repo files so cri-o can be installed

**Additional information you deem important (e.g. issue happens only occasionally):**

This is for building kubernetes locally in a container (for https://github.com/mclarkson/my-own-kind) so these commands are added to a Dockerfile. Will there be a more permanent download location?

**Comment by haircommander** [comment]
what's the precise curl command you've tried?

**Comment by mclarkson** [comment]
```
sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/CentOS_7/devel:kubic:libcontainers:stable.repo
sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:[REQUIRED VERSION].repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:[REQUIRED VERSION]/CentOS_7/devel:kubic:libcontainers:stable:cri-o:[REQUIRED VERSION].repo
sudo yum -y install cri-o
```
From: https://github.com/cri-o/cri-o#installing-cri-o

**Comment by haircommander** [comment]
sorry for the confusion, https://github.com/cri-o/cri-o/pull/3733 will resolve them
you need to set `[REQUIRED VERSION]` to the version of cri-o you're looking for. For instance, if you're using kube 1.18, you'd want
```
sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/CentOS_7/devel:kubic:libcontainers:stable.repo
sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.18.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.18/CentOS_7/devel:kubic:libcontainers:stable:cri-o:1.18.repo
sudo yum -y install cri-o
```

**Comment by mclarkson** [comment]
I did change the `[REQUIRED VERSION]`. The devel: directories had disappeared earlier and now they're back. Now I'm puzzled. Thanks for checking!

**Comment by mclarkson** [comment]
Actually it was this URL that's gone:
https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.17/CentOS_7/devel:kubic:libcontainers:stable:cri-o:1.17.repo

The 1.18 one you posted is there. Do you know where the 1.17 version is.

**Comment by dougsland** [comment]
> Actually it was this URL that has vanished:
> https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.17/CentOS_7/devel:kubic:libcontainers:stable:cri-o:1.17.repo
> 
> The 1.18 one you posted is there. Do you know where the 1.17 version is?

Indeed, just checked. All bits are available but OBS is not showing the packages or repos for download. I am looking for this specific case.

**Comment by dougsland** [comment]
@mclarkson just re-created the repo for 1.17 and it seems working now. Thanks for the report. Please consider closing the ticket if everything is working.

**Comment by mclarkson** [comment]
Looks good, thanks very much!
