### ISSUE TITLE
CentOS 8 installation instructions in README.md not working

### ISSUE THREAD

**Issue by ecky-l** [cri-o/cri-o#3744]
**Description**

**Steps to reproduce the issue:**
1. Try the command sequence statet in the "Getting started" section for CentOS 8

**Describe the results you received:**

`dnf install cri-o` reports "no package available"

**Describe the results you expected:**

cri-o should be installed with a simple "getting started" configuration and it should be possible to bring it up with `systemctl start cri-o`. Advanced configuration is possible with commented config files in some location in /etc/, i.e. /etc/cri-o/. Useful documentation is available in /usr/share/doc/ and in a man page.

**Comment by dougsland** [comment]
@ecky-l Hi, could you please point the URL ? Right now I am working in a patch to share all releases repo for users. (See: https://github.com/cri-o/cri-o/pull/3733)

**Comment by ecky-l** [comment]
Hi, @dougsland 

I am refering to the CentOS 8 section in the README.md of this project. The copy-paste statements are

```
sudo dnf -y install 'dnf-command(copr)'
sudo dnf -y copr enable rhcontainerbot/container-selinux
sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/CentOS_8/devel:kubic:libcontainers:stable.repo
sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:[REQUIRED VERSION].repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:[REQUIRED VERSION]/CentOS_8/devel:kubic:libcontainers:stable:cri-o:[REQUIRED VERSION].repo
sudo dnf -y install cri-o
```

**Comment by hswong3i** [comment]
@ecky-l should replace the `[REQUIRED VERSION]` into, e.g. `1.18`: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.18/CentOS_8/devel:kubic:libcontainers:stable:cri-o:1.18.repo

I always double check the URL with browser, e.g. https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.18/CentOS_8/

**Comment by dougsland** [comment]
@ecky-l if the answer from @hswong3i  works for you please consider closing this issue. Thanks!

**Comment by ecky-l** [comment]
> @ecky-l should replace the `[REQUIRED VERSION]` into, e.g. `1.18`: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.18/CentOS_8/devel:kubic:libcontainers:stable:cri-o:1.18.repo

Of course I have done this ;-). Still it doesn't work.
I also checked the URL in the browser, apparently there is a repository and there are packages inside. But still dnf couldn't find any.

What worrys me are the funny colons : in between the path names. Is that really something that has to be that way?

**Comment by dougsland** [comment]
Hi @ecky-l ,

> > @ecky-l should replace the `[REQUIRED VERSION]` into, e.g. `1.18`:
> https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri
>-o:/1.18/CentOS_8/devel:kubic:libcontainers:stable:cri-o:1.18.repo
> 
> Of course I have done this ;-). Still it doesn't work.
> I also checked the URL in the browser, apparently there is a repository and there are packages 
> inside. But still dnf couldn't find any.

Could you please re-try? Everything seems to be working.

> 
> What worrys me are the funny colons : in between the path names. Is that really something that 
> has to be that way?

Yes. It's the way OBS works.

**Comment by spaced** [comment]
for a `stable` repo the urls should be stable. for example

https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.16/
-> CentOS_7 gone
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.17/
-> CentOS_7 gone
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.18/
-> CentOS_8 gone, but there is CentOS_8_Stream

We will try to keep track on your changes but every change will break kubespray  `CI` 
https://github.com/kubernetes-sigs/kubespray/blob/master/roles/container-engine/cri-o/tasks/crio_repo.yml#L34

**Comment by spaced** [comment]
after browser refresh all repos looks fine now, but
yum install failed because
```
https://download.opensuse.org/repositories/devel%3A/kubic%3A/libcontainers%3A/stable/CentOS_7/x86_64/conmon-2.0.17-1.el7.x86_64.rpm: [Errno 14] HTTPS Error 302 - Found
```
because
```
curl -v https://download.opensuse.org/repositories/devel%3A/kubic%3A/libcontainers%3A/stable/CentOS_7/x86_64/conmon-2.0.17-1.el7.x86_64.rpm                             SIGINT(2) ↵
*   Trying 195.135.221.134:443...
* Connected to download.opensuse.org (195.135.221.134) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=opensuse.org
*  start date: Apr  8 11:31:07 2020 GMT
*  expire date: Jul  7 11:31:07 2020 GMT
*  subjectAltName: host "download.opensuse.org" matched cert's "*.opensuse.org"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55561949ad90)
> GET /repositories/devel%3A/kubic%3A/libcontainers%3A/stable/CentOS_7/x86_64/conmon-2.0.17-1.el7.x86_64.rpm HTTP/2
> Host: download.opensuse.org
> user-agent: curl/7.70.0
> accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 302 
< date: Wed, 03 Jun 2020 14:48:18 GMT
< server: Apache/2.4.33 (Linux/SUSE)
< x-mirrorbrain-mirror: widehat.opensuse.org
< x-mirrorbrain-realm: region
< link: <https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/x86_64/conmon-2.0.17-1.el7.x86_64.rpm.meta4>; rel=describedby; type="application/metalink4+xml"
< link: <http://widehat.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/x86_64/conmon-2.0.17-1.el7.x86_64.rpm>; rel=duplicate; pri=1; geo=de
< link: <https://ftp.gwdg.de/pub/opensuse/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/x86_64/conmon-2.0.17-1.el7.x86_64.rpm>; rel=duplicate; pri=2; geo=de
< link: <http://ftp.lysator.liu.se/pub/opensuse/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/x86_64/conmon-2.0.17-1.el7.x86_64.rpm>; rel=duplicate; pri=3; geo=se
< link: <https://provo-mirror.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/x86_64/conmon-2.0.17-1.el7.x86_64.rpm>; rel=duplicate; pri=4; geo=us
< location: http://widehat.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/x86_64/conmon-2.0.17-1.el7.x86_64.rpm
< content-length: 399
< content-type: text/html; charset=iso-8859-1
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http://widehat.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/x86_64/conmon-2.0.17-1.el7.x86_64.rpm">here</a>.</p>
<hr>
<address>Apache/2.4.33 (Linux/SUSE) Server at download.opensuse.org Port 443</address>
</body></html>
* Connection #0 to host download.opensuse.org left intact
```
what yum does not like.

**Comment by dougsland** [comment]
@spaced conmon is 2.0.18-1 the 2.0.17-1 is not there. https://download.opensuse.org/repositories/devel%3A/kubic%3A/libcontainers%3A/stable/CentOS_7/x86_64/conmon-2.0.18-1.el7.x86_64.rpm

**Comment by haircommander** [comment]
@ecky-l is there anything left here, or is this resolved?
