### ISSUE TITLE
auto delete images is a normal?

### ISSUE THREAD

**Issue by wushuyi** [cri-o/cri-o#3748]
**Description**

default install crio
the crio-wipe.service
auto delete my images is a normal?

/usr/lib/systemd/system/crio.service
[Unit]
Description=Container Runtime Interface for OCI (CRI-O)
Documentation=https://github.com/cri-o/cri-o
Wants=network-online.target
After=network-online.target
After=crio-wipe.service
Requires=crio-wipe.service

**Steps to reproduce the issue:**
1. reboot or shutdown

**Describe the results you received:**
my image auto delete =.=

$ journalctl -u crio-wipe:
>-- Reboot --
5月 09 05:55:13 nx2-f32 systemd[1]: Starting CRI-O Auto Update Script...
5月 09 05:55:16 nx2-f32 crio[845]: version file /var/run/crio/version not found: open /var/run/crio/version: no such file or directory. Triggering wipetime="2020-05-09 05:55:16.768387> 5月 09 05:55:16 nx2-f32 crio[845]: time="2020-05-09 05:55:16.802493236+08:00" level=info msg="deleted container e563efabdf7b31ce0b54d2c549ad3d62218da30a2b086fa03149a0be5277c863"
5月 09 05:55:16 nx2-f32 crio[845]: time="2020-05-09 05:55:16.834118929+08:00" level=info msg="deleted container f5ecddc46ee2c03805b8767df5c85503f243461863d82ba0710104c6b14eba00"
5月 09 05:55:16 nx2-f32 crio[845]: time="2020-05-09 05:55:16.856359850+08:00" level=info msg="deleted container 3f644f55c7f741f939710da89855a8f53f248ddcb6348d8051716239d7268172"
5月 09 05:55:16 nx2-f32 crio[845]: time="2020-05-09 05:55:16.878311827+08:00" level=info msg="deleted container 944ac859227cd053423e92d0f2ddda1b6272a01392aa70eb6e860ea73bd77fa8"
5月 09 05:55:16 nx2-f32 crio[845]: time="2020-05-09 05:55:16.891102557+08:00" level=info msg="deleted container 6117dfcc33b88e1e021e96fce0dc1f729a8cdbc147a9286fff7594c86d5172fe"
5月 09 05:55:16 nx2-f32 crio[845]: time="2020-05-09 05:55:16.920271685+08:00" level=info msg="deleted container 89850fd0a9db5790ff10277158a84b50b7bf814f7c2dd4a4f5eb3a5aa7345e38"
5月 09 05:55:16 nx2-f32 crio[845]: time="2020-05-09 05:55:16.935971773+08:00" level=info msg="deleted container d6c74d0223bd29be52e6f51dc2e1265c8da59ceacec479304706a309ddd92751"
5月 09 05:55:17 nx2-f32 crio[845]: time="2020-05-09 05:55:16.990410302+08:00" level=info msg="deleted container 5181e6c6c0bda32bbe32af9a3e28ba54f68e7afd8e0.....

**Describe the results you expected:**
It makes me feel like I lost the hard disk file

**Output of `crio --version`:**

```
crio version 1.17.4
```

**Additional environment details physical:**
fedora32 module cri-o:1.17

**Comment by haircommander** [comment]
@wushuyi yes, that is expected. crio-wipe wipes all images of containers it cleans. It is meant for upgrades between minor versions, where kube components will likely have updated their images.

Though, we have since dropped the requirement of the crio-wipe service, as it isn't something everyone wants (https://github.com/cri-o/cri-o/pull/3633/commits/95b65e07f33cfa6c7b682d858cf6744c035c79c1), but this hasn't made it into a 1.17 release yet. sorry for the inconvenience.

**Comment by wushuyi** [comment]
@haircommander thank you for your answer
