### ISSUE TITLE
creating read-write layer with ID No such file or directory - crio reading from overlay instead of overlay2?

### ISSUE THREAD

**Issue by rgembalik** [cri-o/cri-o#3768]
**Description**

We have a kubernetes cluster (1.16.9) in which one of the nodes is based on cri-o. (cri-o://1.16.6). From time to time there is a weird error blocking pods from getting up:

```
Warning  FailedCreatePodSandBox  2s (x4 over 43s)  kubelet, kube6     (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = error creating pod sandbox with name "some-sandbox-name": error creating read-write layer with ID "a5021e65186da551b712f7dd743d712833e5f75fc727c6f937d421897d2eb9d6": Stat /var/lib/containers/storage/overlay/e17133b79956ad6f69ae7f775badd1c11bad2fc64f0529cab863b9d12fbaa5c4: no such file or directory
```

When I check that path, it doesn't exist indeed, but:
1. crio is set to use overlay2, so I'm not sure why it tries to load the layer from `/var/lib/containers/storage/overlay`
2. When I check that path, but in overlay2 - `/var/lib/containers/storage/overlay2/e17133b79956ad6f69ae7f775badd1c11bad2fc64f0529cab863b9d12fbaa5c4` - it **does** exist. 

Is this some stale layer ref issue? if so, where should I look to clean it? Can crictl perform validation of layer tree and remove stale data? What are other reasons for such behaviour?

**Steps to reproduce the issue:**
1. Create some pod?

**Describe the results you received:**
Pod never starts

**Describe the results you expected:**
Pod should run

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**
```
crio version 1.16.6
commit: "af8faf448858335f9645b896120167d08caf7156-dirty"
```

Our cluster runs on bare metal. The node with crio on it is:
```
NAME    STATUS                     ROLES    AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
...
kube6   Ready                      node     512d    v1.16.9   10.200.0.15   <none>        Ubuntu 18.04.4 LTS   5.3.0-51-generic    cri-o://1.16.6
...
```

**Comment by haircommander** [comment]
what's the output of 
`sudo grep -r 'driver =' /etc/{containers/storage.conf,crio}`

**Comment by haircommander** [comment]
@nalind @vrothberg @rhatdan PTAL

**Comment by rgembalik** [comment]
@haircommander Full results below. From what I understand in `/etc/crio/crio.conf` the driver in use is overlay2. That's the main reason I was confused.

```
/etc/containers/storage.conf:driver = ""
/etc/crio/crio.conf.dpkg-dist:#storage_driver = "vfs"
/etc/crio/crio.conf:storage_driver = "overlay2"
```

**Comment by haircommander** [comment]
yup you are correct, have/can you try using `storage_driver = "overlay"` instead? I don't personally know or remember the distinction, but I believe our storage library chooses the right one. (one of the folks tagged will have better insights)

**Comment by nalind** [comment]
There's no functional difference between `overlay2` and `overlay` - at the lower levels, they're aliases for the same logic for compatibility reasons, but some of the bits that ensure that things don't get confused when the `overlay2` name is used could be making mistakes here.

**Comment by rgembalik** [comment]
@nalind @haircommander 

One thing I forgot to mention is that there are pods and containers running on that node. It's not all broken. Some images are able to start without a problem. When I `ls` `storage/overlay` and `storage/overlay2` catalogues, both of them contain some layers. 

The problem seems to come and go as some containers are failing to start, just to be able to start a few hours later. For example, I have a set of 5 image building containers running at the same time. All of them are GitLab runners. All of them have the same base images: GitLab runner helper and `quay.io/buildah/stable`. 

But some of them will fail to start nonetheless. Even now when I retry one of the jobs from yesterday, it won't start, with the error I provided at the beginning of issue description.

**Comment by rgembalik** [comment]
I just started the same job again and it ran without problems. This kind of random behaviour starts to look to me like some sort of race condition. Now that the container started I checked quickly for that layer on fs and it still exists only in `overlay2`, not in `overlay`. 

Could it be that there is an issue when two pods are trying to download the same image at the same time? And one of them would see a broken (incomplete) layer in `overlay2`, so it tries `overlay` for backward compatibility?

**Comment by rgembalik** [comment]
When I check `tail -f /var/log/systlog | grep cri` here's what comes up during failed startup, but I can't understand most of it:

```
May 15 09:27:18 kube6 kubelet[52221]: E0515 09:27:18.561128   52221 manager.go:1084] Failed to create existing container: /kubepods/burstable/pod4b2129be-42a4-4ac9-86dc-cafc01a790f1/crio-9e1ed50bf89b85c0d24e896a6afedd595fb53f2b4a4740b7705008655c1867d6: Error finding container 9e1ed50bf89b85c0d24e896a6afedd595fb53f2b4a4740b7705008655c1867d6: Status 404 returned error &{%!s(*http.body=&{0xc0019fe500 <nil> <nil> false false {0 0} false false false <nil>}) {%!s(int32=0) %!s(uint32=0)} %!s(bool=false) <nil> %!s(func(error) error=0x74f810) %!s(func() error=0x74f7a0)}
May 15 09:27:18 kube6 kubelet[52221]: E0515 09:27:18.583714   52221 manager.go:1084] Failed to create existing container: /kubepods/burstable/pod4aa82cbc-8af9-48ca-ad63-b8c18688d559/crio-a8d52a62352e88793236de1ceff2cf5af817c7a7a55c1f403d5117a0e193afd0: Error finding container a8d52a62352e88793236de1ceff2cf5af817c7a7a55c1f403d5117a0e193afd0: Status 404 returned error &{%!s(*http.body=&{0xc001b33480 <nil> <nil> false false {0 0} false false false <nil>}) {%!s(int32=0) %!s(uint32=0)} %!s(bool=false) <nil> %!s(func(error) error=0x74f810) %!s(func() error=0x74f7a0)}
May 15 09:27:18 kube6 kubelet[52221]: E0515 09:27:18.696273   52221 manager.go:1084] Failed to create existing container: /kubepods/burstable/pod17e193c6626a8c420c26cc5032ef0401/crio-9cf9177692255d426819bdcf485dc0afbd2c64fa3f8bd59b8af6febcc1d2b587: Error finding container 9cf9177692255d426819bdcf485dc0afbd2c64fa3f8bd59b8af6febcc1d2b587: Status 404 returned error &{%!s(*http.body=&{0xc001ee0740 <nil> <nil> false false {0 0} false false false <nil>}) {%!s(int32=0) %!s(uint32=0)} %!s(bool=false) <nil> %!s(func(error) error=0x74f810) %!s(func() error=0x74f7a0)}
May 15 09:27:18 kube6 kubelet[52221]: E0515 09:27:18.742191   52221 manager.go:1084] Failed to create existing container: /kubepods/besteffort/pod44cdeca3-f0c9-11e9-8076-525400451066/crio-ee82e14e028b53f573dd78008eab77da2ea6cd9d62f5aa88e5b4afe3ec23359c: Error finding container ee82e14e028b53f573dd78008eab77da2ea6cd9d62f5aa88e5b4afe3ec23359c: Status 404 returned error &{%!s(*http.body=&{0xc001ee1280 <nil> <nil> false false {0 0} false false false <nil>}) {%!s(int32=0) %!s(uint32=0)} %!s(bool=false) <nil> %!s(func(error) error=0x74f810) %!s(func() error=0x74f7a0)}
May 15 09:27:19 kube6 kubelet[52221]: I0515 09:27:19.258499   52221 kubelet_getters.go:172] status for pod nginx-proxy-kube6 updated to {Running [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2020-05-13 09:59:17 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2020-05-13 10:20:25 +0000 UTC  } {ContainersReady True 0001-01-01 00:00:00 +0000 UTC 2020-05-13 10:20:25 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2020-05-13 09:59:17 +0000 UTC  }]    10.200.0.15 10.200.0.15 [{10.200.0.15}] 2020-05-13 09:59:17 +0000 UTC [] [{nginx-proxy {nil &ContainerStateRunning{StartedAt:2020-05-13 09:59:28 +0000 UTC,} nil} {nil nil nil} true 0 docker.io/library/nginx:1.17 docker.io/library/nginx@sha256:86ae264c3f4acb99b2dee4d0098c40cb8c46dcf9e1148f05d3a51c4df6758c12 cri-o://2c2aebcd8de277755ca17e9eae40380de911d19a06ab48611c65c1f7e9ddeae9 0xc0018aac78}] Burstable []}
```

**Comment by haircommander** [comment]
are you running crio as a systemd unit? if so, what's the output of `journalctl -u crio`. It may also be helpful to make the log level debug or info in `/etc/crio/crio.conf`

**Comment by rgembalik** [comment]
Normally I would, but it turns out that unit logs cut off about two days ago. `systemctl status crio` has the same logs - that is missing last two days. 

The issue I am reporting here is much longer, but I don't know why all of a sudden it's not logging into the journal. 

Here are the last 100 lines of whatever is available:

[crio-100lines.txt](https://github.com/cri-o/cri-o/files/4634816/crio-100lines.txt)

**Comment by haircommander** [comment]
dang that's all ipam, nothing from cri-o...

**Comment by haircommander** [comment]
if you see it again can you nab the logs?

**Comment by rgembalik** [comment]
The error occurs all the time. Today it blocked in our team about 10 pipelines throughout the day, so if it was logging anything it would be visible in that `journalctl` I uploaded. The same goes for yesterday.

**Comment by haircommander** [comment]
can you try setting the log level to `warning` instead

**Comment by rgembalik** [comment]
Ok, I set `log_level = "warn"` and reloaded the service. the information about changing log level appeared in `journalctl`, so let's hope the actual error will log there too. I'll let you know when something happens, but that would be probably in the next week.

**Comment by haircommander** [comment]
sounds good, thanks @rgembalik

**Comment by rhatdan** [comment]
What application is setting up overlay2?  Can we just fix the machine to just use overlay?  We should ix storage to always use overlay even if the user specifies overlay2, since they are the same thing?

**Comment by rgembalik** [comment]
@rhatdan Our setup is kinda a mix of kubespray and self-developed kubespray config, so I assume that came from my bosses configuration of the node deployment. While that might be a valid solution for selection between ov and ov2 I kinda think this might not be the core issue here. 

The main reason I think that is that those containers are getting up every now and then and working correctly. However, when I launch them in our pipeline, there will be 5 pods spawning with the same underlying image to do different jobs. Some of them will work fine, some of them will never start due to the error above (well, I say never - it's more like "not withing gitlab runner timeout"). 

For that reason, I think that there can be something that decides, that the layer (which is stored on ov2) is not valid for use and tries to look for it in `overlay`. 

I will try switching to overlay when nobody is looking next week and see what blows up. I'll let you know. I hope my gut-feeling is not correct as that would be the easiest scenario.

**Comment by rgembalik** [comment]
I just switched the storage system and checked `journalctl`: Since Friday I see there are hundreds of messages like this one:
```
May 17 01:20:30 kube6 crio[9468]: time="2020-05-17 01:20:30.658182673Z" level=warning msg="imageStatus: can't find gcr.io/google_containers/pause-amd64:3.1" id=a9b1e437-70b4-4baa-a960-7b0438ce120b
```
Not sure what it means.

**Comment by rgembalik** [comment]
I changed the `storage_driver` option to `overlay` and reloaded with `systemctl reload crio`. Unfortunately, the issue persists. Just fired another build pipeline and it got stuck immediately on creating all `quay.io/buildah/stable` containers. `kubectl describe pod` produces the same message as in the first post:
```
Warning  FailedCreatePodSandBox  3s (x12 over 2m28s)  kubelet, kube6     (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = error creating pod sandbox with name "k8s_runner-kz8jrada-project-466-concurrent-2hcr4l_gitlab_401c8c2e-26e1-4696-bf17-8318224ee311_0": error creating read-write layer with ID "2effca51c3c13e303f9330e22aa1c5bd9dcbfa8593dd878575d9dd4755cad550": Stat /var/lib/containers/storage/overlay/e17133b79956ad6f69ae7f775badd1c11bad2fc64f0529cab863b9d12fbaa5c4: no such file or directory
```

Anything else I could safely try?

**Comment by rgembalik** [comment]
I also tried `systemctl restart crio`, Unfortunately with no luck either. I checked GitLab runner settings and it uses pull policy `IfNotPresent`, so since buildah image is already there, crio should be able to use it as is.

**Comment by haircommander** [comment]
what do you have for a pause_image in crio.conf? it's failing on pulling the pause image for some reason. our default is: `k8s.gcr.io/pause:3.1` and you seem to be pulling `gcr.io/google_containers/pause-amd64:3.1`

**Comment by haircommander** [comment]
(btw: a reload probably won't work for storage driver, we have to manually support reloaded config values. A restart is more reliable)

**Comment by rgembalik** [comment]
@haircommander The crio.conf has indeed the default `k8s.gcr.io/pause:3.1`, while our kubelet.env passes `--pod-infra-container-image=gcr.io/google_containers/pause-amd64:3.1`. That warning is a bit  weird as I do have that image locally:
```
crictl image | grep pause
gcr.io/google_containers/pause-amd64     3.1        da86e6ba6ca19       749kB
k8s.gcr.io/pause                         3.1        da86e6ba6ca19       749kB
gcr.io/google_containers/pause           3.0        99e59f495ffaa       760kB
```

> (btw: a reload probably won't work for storage driver, we have to manually support reloaded config values. A restart is more reliable)
Yeah, I thought as much, and that's why I tried a restart as well. Alas, still no improvement.

**Comment by haircommander** [comment]
can you set the --pod-infra-container-image and pause_image to be the same? (whichever you want) and see what happens?

**Comment by haircommander** [comment]
how disturbing would a system reset be for you? If you stop cri-o, run `rm /var/run/crio/version`, then run `crio wipe` and then restart it, i would be interested in seeing what happens when cri-o is re-bootstrapped

**Comment by rgembalik** [comment]
I tried both pause images, neither of them worked. What's more, when I set both to `gcr.io/google_containers/pause-amd64:3.1`, then not only the issue persisted but also kubernetes started getting errors on creating pod sandbox (namely, that it couldn't download that image, despite the fact that it already was there).

Yeah, I think I can try that wipe as most of the work has already stopped in our company.

**Comment by haircommander** [comment]
thanks for your patience and for working with us :smiley:

**Comment by rgembalik** [comment]
Hmm... I think some paths might be different:
```
# rm /var/run/crio/version
rm: cannot remove '/var/run/crio/version': No such file or directory
# crio wipe
major and minor version unchanged; no wipe needed
```
Any idea where to look? In `/var/run/crio/` I have a bunch of symlinks to `/var/run/containers/storage/overlay-containers/` and one directory named `exits`.

**Comment by rgembalik** [comment]
Or did you mean `/var/lib/crio/version`?

**Comment by haircommander** [comment]
ah yeah sorry I meant that

**Comment by haircommander** [comment]
we changed the paths in later versions of cri-o

**Comment by rgembalik** [comment]
Hmm... I did that, but I had to manualy umount many leftovers from the containers. After wipe there are still layers in `/var/lib/containers/storage/overlay` and `/var/lib/containers/storage/overlay2`. Should I do anything else?

**Comment by rgembalik** [comment]
I also have `/var/run/containers/storage` with similar paths inside, which confuses me even more... Are those some leftovers from previous versions?

**Comment by haircommander** [comment]
OK: full system reset then. I would stop cri-o, reboot the node, `rm -rf /var/{run,lib}/containers`, then start kubelet and cri-o.

**Comment by haircommander** [comment]
I would think crio wipe would wipe it all, but if there are running containers using the mount points, it will fail. Only way to fully wipe is reboot

**Comment by rgembalik** [comment]
Yeah, sorry, didn't think about it. I'm way too much used to docker and it's ways ;) It's a bit shame that crio allowed me to do wipe once containers were running because after that try I can't restart it to clean it up properly.

**Comment by haircommander** [comment]
I forgot about it too, no worries.

Did crio not restart after you called crio wipe?

**Comment by rgembalik** [comment]
No, it kept crashing complaining about dependencies, although I didn't turn off any other services than crio and kubelet.

**Comment by haircommander** [comment]
:upside_down_face: welp, sorry, hopefully the node reboot does the job

**Comment by rgembalik** [comment]
Everything went up, some containers are getting up. The one I am interested in the most (i.e. those based on `quay.io/buildah/stable`) can't get up as it looks like quay has some bad day today and keeps throwing 504 on that image. 

Anyway, I'll run some test builds, push that 64 threads to some serious work and let you know what happens. I think we'll see the best results once the team starts working tomorrow. So far those builds that were able to get up did run, but I'd like to see them working on parallel.

**Comment by haircommander** [comment]
Okay, glad to hear! Keep me posted, thanks :smiley:

**Comment by rgembalik** [comment]
Good news/bad news:

**Good** 
I am observing the node and so far everything is building as it should. No problems so far.

**Bad** 
I talked with my boss (who tried previously fix that issue) and he told me, that he tried to do `crio wipe` a few weeks ago to address mentioned issue and it didn't help back then. From what I gather, the wipe my boss did was of a similar fashion as he renamed `containers` directory once done (it wasn't empty either as I am looking at it now). But back then that wipe wasn't enough (hence this issue).

Considering that I additionally set pause image to be unified and changed storage driver to overlay I'd say, that storage driver doesn't affect existing images and therefore requires full wipe (as there is no way to remove dangling layers). It's somewhat logical, but once there are some problems with layers, it's hard to get them fixed. 

From my perspective, wiping the entire node to "fix" layers and images metadata it's a bit much. There should be some way to remove unused layers once I manually `crictl rmi` the faulty image(s).

**Comment by haircommander** [comment]
yeah I understand the difficulty @rgembalik. It's hard for us to prune orphaned layers because other tools (buildah) may legitimately want them, so cri-o can't unconditionally remove them, nor can it really find them because it accesses images on an image digest level, not layer level. I am not sure there is much cri-o specifically can do here, other than hope that the `overlay` change fixes the problem at the root . Do you have any updates/are you satisfied and feel alright closing the ticket?

**Comment by rgembalik** [comment]
@haircommander Yeah, our team didn't report any issues, so the issue is solved. 

I am sure there are discussions about pruning images in crio, so I am not going to argue your point here. In my case `crictl image prune` would just allow me to fix the issue without having to wipe the entire overlay and that's why I would welcome such feature. But I recognize that's a subjective opinion, so I'll leave it at that. 

Once again, thank you for your help.

**Comment by haircommander** [comment]
happy to help, thanks for the report :smiley:

**Comment by rathinikunj** [comment]
I had an Openshift 4.5 cluster with 3 masters and 2 worker nodes. Pods were not coming up on one of the worker nodes with the same error when i describe the pod. After following the above steps and rebooting the node, pods come up like a charm.
**Summarizing the Steps followed**
-   Stop crio `systemctl stop crio`
-  Remove crio version file `rm /var/lib/crio/version`
-  `crio wipe`
-  Remove lib/containers and run/containers `rm -rf /var/{run,lib}/containers`
-  Reboot the node
-  `systemctl restart kubelet`

One of these steps may not be necessary, nonetheless i did all these while going through this thread.

Thanks for this thread @haircommander and @rgembalik

**Comment by haircommander** [comment]
glad that worked for you!

**Comment by caruccio** [comment]
In addition to @rathinikunj I also did `umount` bellow prior to reboot the node:

```
umount /var/lib/containers/storage/overlay/*/merged /var/run/containers/storage/overlay-containers/*/userdata/shm
```

**Comment by caruccio** [comment]
Just found that a simple `systemctl restart kubelet` does the job.

**Comment by volkovro** [comment]
I encountered a similar issue. It only occurs on a node running kubelet staticPods.

All I could find was a warning, which can be found like this:

journalctl -xefu crio | grep "Switching default driver from overlay2 to equivalent overlay driver"

Clearing the overlay2 and overlay directories and then changing the overlay directory to point to overlay2 helped.

```
lrwxrwxrwx  1 root root   28 Nov 13 02:44 overlay -> ./overlay2
drwxr-xr-x 52 root root 4096 Nov 13 02:51 overlay2
drwxr-xr-x 21 root root 4096 Nov 13 02:51 overlay-containers
drwx------  9 root root 4096 Nov 13 02:50 overlay-images
drwx------  2 root root 4096 Nov 13 02:51 overlay-layers
drwx------  2 root root 4096 Nov 13 02:44 overlay-locks
-rw-r--r--  1 root root   64 Nov 13 02:44 storage.lock
-rwxr-xr-x  1 root root    0 Nov 13 02:41 userns.lock
```
