### ISSUE TITLE
docker exec -u 0 equivalent for crictl exec

### ISSUE THREAD

**Issue by DevasiaThomas** [cri-o/cri-o#3770]
**Description**
docker exec allows me to get a root shell to a target container via -u 0. How can I achieve the same in cri-o?

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
1.14.11-0.24.dev.rhaos4.2.gitc41de67.el8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
https://www.openshift.com/learn/courses/playground/

**Comment by saschagrunert** [comment]
Hey @DevasiaThomas, the Container Runtime Interface (CRI) specification does not allow us to implement such feature right now. There is a similar issue (https://github.com/kubernetes-sigs/cri-tools/issues/507) open in cri-tools (crictl), which also came to the conclusion that we cannot support this without changing the CRI. Is there any reason that you cannot switch users when already exec'ed into the container?

**Comment by DevasiaThomas** [comment]
Hi @saschagrunert! Well I use it to get a root shell into any container and then switch to the user I need. The way you suggest is the opposite of what I need and also requires authentication - something I don't have in containers I don't own (ie images I built). If you need more details around the use case, I can provide them privately.

**Comment by DevasiaThomas** [comment]
@saschagrunert Is what I provided enough?

**Comment by saschagrunert** [comment]
> @saschagrunert Is what I provided enough?

Yes, unfortunately I don't think that we can much do for you here right now. The CRI needs support for such a use case. I know that there was a request in kubectl as well but I'm not sure if anybody is already working on that topic.

**Comment by DevasiaThomas** [comment]
Hmm, thats disheartening. especially since the container runtime supports it

**Comment by haircommander** [comment]
This can be solved by running `su -` and then continuing with the exec session. The larger-scoped CRI change would need to happen for us to do anything else. @DevasiaThomas would you be alright if we closed this ticket?

**Comment by DevasiaThomas** [comment]
@haircommander :) and we know that su can have issues #3803. Yes I'll close the ticket. Solving this using runc is a viable option as well.

**Comment by sharkymcdongles** [comment]
> This can be solved by running `su -` and then continuing with the exec session. The larger-scoped CRI change would need to happen for us to do anything else. @DevasiaThomas would you be alright if we closed this ticket?

How do you mean? If you do su - then the container will prompt for authentication to change to root which is the entire reason this functionality is necessary.

**Comment by haircommander** [comment]
you have to edit the user or the group to not need a password. This can be done when building the container:
[here](https://unix.stackexchange.com/questions/113754/allow-user1-to-su-user2-without-password) are some tips to do so

**Comment by sharkymcdongles** [comment]
I am aware how to build a container. If you use any upstream deployments
from a CNCF project or similar with a properly vetted security footprint in
the container, then you will likely be running containers not built by you
e.g. prometheus operator or similar. This alteration would necessitate
building every single container for every single deployment and every
single upgrade of said deployment. This is a tremendous undertaking just to
have a root user to use in case of some emergency or something.

**Comment by haircommander** [comment]
understood. in this disaster recovery scenario, is there anything preventing you from using `runc exec` directly instead of crictl?

**Comment by DevasiaThomas** [comment]
@sharkymcdongles I understand your pain point, and I thought about trying to get the spec changed etc. But since the product I work on needs to work with crio today, I just shifted to the runc layer. You can supply the user id using runc instead. As it is, dealing with crio means you are in the node dealing with containers directly, just use runc instead. 
If you are using some other runtime, I’m sure they too have a user switch.

**Comment by sharkymcdongles** [comment]
I was unaware you could use runc directly. This seems like an acceptable
solution. I will experiment with this then. No need to repeat functionality
already given via runc. Thanks for the thorough explanation and
enlightening correspondence!
