### ISSUE TITLE
logs and attach lost when restart crio

### ISSUE THREAD

**Issue by shsjshentao** [cri-o/cri-o#3771]
**Description**

we know crio read io from fifo in vm. (/tmp/crio/fifo/io...)
If runtime write logs in fifo file during the crio restart or stopped, the runtime fifo writer will exit and not recovery.

**Describe the results you received:**
no logs can be received
attach cannot use

**Comment by haircommander** [comment]
yeah right now kata shim v2 does not work in a restart case. this is the largest tech debt left in closing https://github.com/cri-o/cri-o/issues/1945. I'd deem this as a duplicated ticket to that. Would you mind we closed this and tracked your issues there?

**Comment by haircommander** [comment]
Since I've gotten no response, I am going to close this in favor of tracking the problem in #1945
thanks for opening the report

**Comment by shsjshentao** [comment]
ok, i have finished crio restart used by vm and move log behavior to shim in case lost io
