### ISSUE TITLE
su throws system error in crio started containers

### ISSUE THREAD

**Issue by DevasiaThomas** [cri-o/cri-o#3803]
**Description**
I have the same image being started in the same cluster by k8s. One node runs docker and the other runs cri-o.
The container started by docker has no issues running su, but the one started by cri-o just says ``su: system errror``
This is consistent across the following
``runc exec <containerID> su``
``docker exec/crictl exec <containerID> su``
``kubectl exec -it <pod> sh`` and then ``su``

**Steps to reproduce the issue:**
1. Deploy this yaml using kubectl on a docker node and a cri-o node
```
apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  labels:
    name: tomcat
spec:
  containers:
    - image: tomcat:jre8
      name: tomcat-pod
      ports:
        - containerPort: 8080
```
2. Try execute su in the respective containers
3.

**Describe the results you received:**
docker deployed container did not cause an error and worked fine. cri-o one caused an error
``su: system error``

**Describe the results you expected:**
crio deployed container should have had the same behavior since both are runc in the end

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.16.6
```
**Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
**Output of `docker version`:**
```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:52:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:50:54 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
All nodes in my cluster are identical (they are virtual machines)

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Comment by haircommander** [comment]
I don't know if this will actually help, but I found [this](https://unix.stackexchange.com/questions/193499/cant-switch-to-a-specific-system-account-with-su) article and wonder if specifying a different shell yields any success?

**Comment by haircommander** [comment]
it is possible we're not correctly setting up /etc/passwd inside the container. I'd be interested in what `cat /etc/passwd` yields in both docker and cri-o

**Comment by haircommander** [comment]
also what's the output of `cat /etc/crio/crio.conf.d/00-default.conf  | grep capa -A 12`

**Comment by DevasiaThomas** [comment]
> I don't know if this will actually help, but I found [this](https://unix.stackexchange.com/questions/193499/cant-switch-to-a-specific-system-account-with-su) article and wonder if specifying a different shell yields any success?

Well I can't get su to work within the container the binary itself fails with that error and hence further arguments are ignored.

**Comment by DevasiaThomas** [comment]
> cat /etc/crio/crio.conf | grep capa -A 12

```
# List of default capabilities for containers. If it is empty or commented out,
# only the capabilities defined in the containers json file by the user/kube
# will be added.
default_capabilities = [
	"CHOWN", 
	"DAC_OVERRIDE", 
	"FSETID", 
	"FOWNER", 
	"NET_RAW", 
	"SETGID", 
	"SETUID", 
	"SETPCAP", 
	"NET_BIND_SERVICE", 
	"SYS_CHROOT", 
	"KILL", 
]
```

**Comment by DevasiaThomas** [comment]
> it is possible we're not correctly setting up /etc/passwd inside the container. I'd be interested in what `cat /etc/passwd` yields in both docker and cri-o

Docker
```
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
_apt:x:100:65534::/nonexistent:/bin/false
```
cri-o
```
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
_apt:x:100:65534::/nonexistent:/bin/false

```

**Comment by haircommander** [comment]
and what's the output if you do `kubectl exec -ti <pod> whoami`

**Comment by DevasiaThomas** [comment]
> and what's the output if you do `kubectl exec -ti <pod> whoami`

Both are ``root``

**Comment by haircommander** [comment]
I will work on reproducing

**Comment by DevasiaThomas** [comment]
@haircommander This is how I set up a crio-node for my existing k8s 1.16 cluster.
https://github.com/DevasiaThomas/Kubernetes-Cluster-Installer-NonHA-CentOS7/wiki/Crio-node

**Comment by haircommander** [comment]
update: i was able to reproduce, and podman doesn't have the same issue. I am investigating

**Comment by DevasiaThomas** [comment]
> update: i was able to reproduce, and podman doesn't have the same issue. I am investigating

Are you saying you got the system error with crio but not with podman? Sorry, I haven't used podman yet but will soon start working on it in the future.

**Comment by haircommander** [comment]
found it! It had to do with capabilities. CRI-O ships with fewer capabilities by default than podman does. One such capability is CAP_AUDIT_WRITE. I bet docker also gives containers CAP_AUDIT_WRITE by default. More capabilities==less secure :smile: 

if you change the pod spec to 
```
apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  labels:
    name: tomcat
spec:
  containers:
    - image: tomcat:jre8
      name: tomcat-pod
      ports:
        - containerPort: 8080
      securityContext:
        capabilities:
          add:
            - AUDIT_WRITE
```
it works as expected

**Comment by haircommander** [comment]
(podman or docker are less secure by default because they're used for debugging containers and playing around with them. Without those capabilities, weird issues like this pop up. CRI-O is only meant for running containers in production, so we drop as many capabilities as we can)

**Comment by DevasiaThomas** [comment]
hmm but is this required if I'm doing an run exec -u 0, I am after all entering as root into that container. Why should root have lesser privileges?

**Comment by haircommander** [comment]
container processes are run inside of a user namespace (among other namespaces). Namespaces are a key linux isolation mechanism, and most of how containers can act like light weight VMs. Where the container process sees itself as root, from the outside, the container is actually a different user in the host's user namespace. This means it is less powerful than root on the host. This is good, as we want containers to act as isolated hosts. It would be like a VM breaking out of virtual space and mucking around on the host.

along with namespaces, the container processes are also confined by linux capabilities. Processes are typically given a subset of capabilities because they don't need them. However, some binaries try to do things that require capabilities, and the mechanism to report an "I'm not allowed to do that" error is notoriously poor. `su` tries to write to the audit logs to say "hey, someone tried to switch users", but if it isn't given the capability CAP_AUDIT_WRITE, that attempt is denied. This is what the (horribly cryptic) error `su: system error` is showing

**Comment by rhatdan** [comment]
Why is su writing to the audit file?  Seems like a PAM Module that could be modified to not attempt to send the audit message.  There is no reason that audit messages should be written from within a container. There is potential that these messages could be used to cause problems on the system.

**Comment by rhatdan** [comment]
I am not sure how you can get this failure. Trying this with Podman it works.

```
$ podman run --cap-drop audit_write -ti fedora sh
sh-5.0# su bin
This account is currently not available.
sh-5.0# useradd dwalsh
sh-5.0# su dwalsh
[dwalsh@dfe8f01fa259 /]$ exit
```

**Comment by haircommander** [comment]
try the container used here (or debian:stretch, as that seems to be the base):
```
podman run --cap-drop audit_write -ti debian:stretch su
su: System error
```

**Comment by haircommander** [comment]
actually, I needed root to get that. with rootless I have other troubles:
```
$ podman run --cap-drop audit_write -ti debian:stretch su
Error: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:378: setting rlimits for ready process caused \\\"error setting rlimit type 7: invalid argument\\\"\"": OCI runtime error
```

**Comment by DevasiaThomas** [comment]
@haircommander and I agree this seems like a problem with the debian image as this doesn't happen in the latest image. Adding that CAP seems to be the best bet.
Closing this issue. Thanks guys :)

**Comment by haircommander** [comment]
note: once we get https://github.com/seccomp/containers-golang/pull/27 in, we may prevent the need to give this container audit_write
