### ISSUE TITLE
Add metrics for image pull failures

### ISSUE THREAD

**Issue by mrunalp** [cri-o/cri-o#3807]
We should add metrics for image pull failures, so we can add alerts for situations like quay.io going down.

Off the top, we could start with:
1. A registry is unreachable.
2. Authentication error.

@mtrmac @vrothberg @saschagrunert Thoughts?

**Comment by saschagrunert** [comment]
Sounds good to me, we could also count the successful downloads. This way the user doesn’t have to calculate: pull operations - failures

**Comment by vrothberg** [comment]
All proposals sounds like a reasonable addition :+1:

**Comment by saschagrunert** [comment]
Proposed a solutoin in #3809
