### ISSUE TITLE
crictl pull not working - invalid status code from registry 502 (Bad Gateway)

### ISSUE THREAD

**Issue by poladiaraj** [cri-o/cri-o#3863]
On server running Oracle Linux 7.5, with crio version 1.17.0 facing issues while pulling image from private docker registry (insecure) .

FATA[0001] pulling image failed: rpc error: code = Unknown desc = error pinging docker registry <registry IP>:<registry PORT>: invalid status code from registry 502 (Bad Gateway)

although if I use podman to pull image then image gets pulled successfully. Is it specific to CRI-O 1.17.0? Because, we didn't face such issue with crio 1.14

**Comment by mtrmac** [comment]
Why doesn’t “502 bad gateway” mean exactly what it says?

Nothing in the docker/distribution repository, at least, uses that error code to report specific error situations, so I would suggest starting at the server side to figure out which component is reporting that and why.

(That doesn’t necessarily mean that c/image is not being the difference between the two versions, but I’m not going to just _guess_ what difference.)

**Comment by poladiaraj** [comment]
Is there any difference between the request sent to registry between crictl pull and podman pull or docker pull for insecure registries? Because crictl pull is working for docker hub it's not working for private insecure registry setup locally.

**Comment by poladiaraj** [comment]
Had to remove proxy configured in /etc/sysconfig/crio file to make it work.
