### ISSUE TITLE
cri-o runtime gets into a loop while trying to get a shell from from hello world image

### ISSUE THREAD

**Issue by vivekanandpoojari** [cri-o/cri-o#3869]
[kubeletLogsContainerd.txt](https://github.com/cri-o/cri-o/files/4800269/kubeletLogsContainerd.txt)
**Steps to reproduce the issue:**
1. kubectl run -i myscan --image=hello-world --restart=Never --rm=true --command -- sh

**Describe the results you received:**
This command never returns.
For containerd runtime we immediately get an error that shell does not exist in the path.
For cri-o kubelet repeatedly tries to create a pod in a loop.

**Describe the results you expected:**
The command should have failed immediately as in case of containerd.
I have attached logs from containerd as well

My main use case is that I want to get a shell handle into an image.
So I need to launch a pod from an image and override the entrypoint with bash or sh.
If the image doesnt have shell it should terminate immediately 

**Additional information you deem important (e.g. issue happens only occasionally):**
**Output of `crio --version`:**

```
=======================================================================

crictl version

Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.18.1
RuntimeApiVersion:  v1alpha1

=======================================================================

kubectl version

Client Version: version.Info
{Major:"1",
Minor:"18",
GitVersion:"v1.18.3",
GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40",
GitTreeState:"clean",
BuildDate:"2020-05-20T12:52:00Z",
GoVersion:"go1.13.9",
Compiler:"gc",
Platform:"linux/amd64"}

Server Version: version.Info
{Major:"1",
Minor:"18",
GitVersion:"v1.18.3",
GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40",
GitTreeState:"clean",
BuildDate:"2020-05-20T12:43:34Z",
GoVersion:"go1.13.9",
Compiler:"gc",
Platform:"linux/amd64"}

=======================================================================
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtual Machine , CentOS7 , Single  node k8s cluster 

Attached the errors from kubelet , crio, containerd

crio logs ==> crioOutput.txt
kubelet for crio ==> kubelet.txt
containerd logs ==> containerdOutput.txt

[containerdOutput.txt](https://github.com/cri-o/cri-o/files/4769623/containerdOutput.txt)
[crioVersion.txt](https://github.com/cri-o/cri-o/files/4769624/crioVersion.txt)
[crioOutput.txt](https://github.com/cri-o/cri-o/files/4769625/crioOutput.txt)
[kubelet.txt](https://github.com/cri-o/cri-o/files/4769626/kubelet.txt)
[containerdLogs2.txt](https://github.com/cri-o/cri-o/files/4800353/containerdLogs2.txt)

**Comment by mrunalp** [comment]
@tedyu can you look at this one?

**Comment by tedyu** [comment]
Ack:
I will analyze the logs tomorrow.

**Comment by vivekanandpoojari** [comment]
@tedyu uploaded the kubelet containerd logs.
Search for the text 'myscan'

**Comment by tedyu** [comment]
For kubelet running on containerd, 'pod_workers.go:191' occurred once.

For kubelet running on cri-o, 'pod_workers.go:191' occurred several times.

**Comment by haircommander** [comment]
@mrunalp looked at this one a bit, and found a disagreement between what CRI-O does on CreateContainer and what containerd/docker do. Basically, we go all the way to call the `$runtime create` call, where docker just generates an ID and creates a rootfs. It would require a significant rework fix it, though it has been added to the list of things we want to address in the coming weeks

**Comment by haircommander** [comment]
this is still an issue
