### ISSUE TITLE
Missing MKNOD capability makes rancher setup fail

### ISSUE THREAD

**Issue by kubealex** [cri-o/cri-o#3872]
**Description**

Some tools require creation of files/paths with MKNOD, like Rancher, and it fails hard when trying to install on k8s with cri-o.

**Steps to reproduce the issue:**
1. Install k8s
2. Install rancher
3. Enjoy failure on startup

**Describe the results you received:**

2020/05/20 08:38:26 [INFO] Rancher version v2.4.3 (684884c) is starting
2020/05/20 08:38:26 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:auto Embedded:false HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features:}
2020/05/20 08:38:26 [INFO] Listening on /tmp/log.sock
2020/05/20 08:38:26 [INFO] Starting API controllers
2020/05/20 08:38:26 [INFO] Running in clustered mode with ID 10.85.0.52, monitoring endpoint cattle-system/rancher
2020/05/20 08:38:27 [INFO] Starting API controllers
2020/05/20 08:38:27 [INFO] Starting rbac.authorization.k8s.io/v1, Kind=Role controller
2020/05/20 08:38:27 [INFO] Starting rbac.authorization.k8s.io/v1, Kind=ClusterRole controller
2020/05/20 08:38:28 [FATAL] error running the jail command: exit status 2

From a debug pod:

tar: ./urandom: Cannot mknod: Operation not permitted
tar: ./zero: Cannot mknod: Operation not permitted
tar: ./tty: Cannot mknod: Operation not permitted
tar: ./full: Cannot mknod: Operation not permitted
tar: ./random: Cannot mknod: Operation not permitted
tar: ./null: Cannot mknod: Operation not permitted
tar: Exiting with failure status due to previous errors

**Describe the results you expected:**

Setup completes

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens everytime, doesn't happen on docker or containerd.

**Output of `crio --version`:**

```
[kube@k8s-master-0 ~]$ crio --version
crio version 
Version:       1.18.1
GitCommit:     5cbf694c34f8d1af19eb873e39057663a4830635
GitTreeState:  clean
BuildDate:     2020-06-08T13:01:11Z
GoVersion:     go1.13.11
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

All

**Comment by haircommander** [comment]
Hey @kubealex !
We prefer to keep CRI-O as secure as possible by default. However, you can add capabilities by adding a drop-in file to your config dir (by default `/etc/crio/crio.conf.d/`)
```
[crio.runtime]
default_capabilities = [
...
MKNOD,
...
]
```
Is that a sufficient fix for you?

**Comment by kubealex** [comment]
sure, it works, but some missing capabilities break even compatibility with coredns, since it requires the NET_RAW capability to correctly serve dns requests on kube-dns service.

I don't know if it is a strict security requirements, but you should work together with rancher and coredns team to find a match and make it work, maybe adding capabilities in the deployment.

**Comment by rhatdan** [comment]
Mknod and NET_RAW are two very powerful capabiltiies, that 99% of containers around the world do not need.  We should NOT turn them on by default.  Please open issues with them, to have them specify their needs in the yaml files.

**Comment by rhatdan** [comment]
Also you can simply add MKNOD and NET_RAW to your crio.conf if you don't like the defaults chosen by the upstream.

**Comment by haircommander** [comment]
@kubealex are you saying rancher and coredns create pods in cri-o that require these caps? If so, I agree with @rhatdan that it's an issue of the pod not asking to add the capability (and assuming every container manager has it)

**Comment by haircommander** [comment]
I opened https://github.com/rancher/rancher/issues/27587

**Comment by haircommander** [comment]
and also opened https://github.com/coredns/coredns/issues/3951
