### ISSUE TITLE
Is there a way to setup runtime type in CRI-O tests?

### ISSUE THREAD

**Issue by GabyCT** [cri-o/cri-o#3877]
We are trying to run the tests from CRI-O like https://github.com/cri-o/cri-o/blob/master/test/ctr.bats, however, for kata containers 2.0, we can performed the export of the RUNTIME to `containerd-shim-kata-v2` without a problem but how can we performed a export for `runtime_type = "vm"`? 
/cc @chavafg

**Comment by haircommander** [comment]
we actually don't have this capability right now. the only cli flag we support is `--runtimes` (or the equivalent env variable `CONTAINER_RUNTIMES`
However, the help string for the runtimes string says
`OCI runtimes, format is runtime_name:runtime_path:runtime_root`
which means we don't support overriding the type

**Comment by haircommander** [comment]
a way you could do this is set
`OVERRIDE_OPTIONS="-d /tmp/crio.conf.d" CONTAINER_DEFAULT_RUNTIME=kata`
and then put 
```
[crio.runtime.runtimes.kata]
runtime_path = ""
runtime_type = "vm"
```
in /tmp/crio.conf.d

**Comment by haircommander** [comment]
I also think `--runtimes` should support a fourth field for runtime_type

**Comment by GabyCT** [comment]
@haircommander thanks for your answer, I tried to applied the solution of `OVERRIDE_OPTIONS`, however, I am seeing errors like this (when I ran the tests)
```
14:26:13 # time="2020-06-15 19:20:56.751723072Z" level=debug msg="Running conmon under custom slice system.slice and unitName crio-conmon-643308c7bc53fa75ed2444cbf82cf2f6e0be082c0abd2509fd5869361d74bc61.scope" file="oci/oci_linux.go:66"
14:26:13 # time="2020-06-15 19:20:56.822256080Z" level=debug msg="Received container pid: -1" file="oci/runtime_oci.go:207"
14:26:13 # time="2020-06-15 19:20:56.822355586Z" level=error msg="Container creation error: flag provided but not defined: -root\nUsage of /usr/local/bin/containerd-shim-kata-v2:\n  -address string\n    \tgrpc address back to main containerd\n  -bundle string\n    \tpath to the bundle if not workdir\n  -debug\n    \tenable debug output in logs\n  -id string\n    \tid of the task\n  -namespace string\n    \tnamespace that owns the shim\n  -publish-binary string\n    \tpath to publish binary (used for publishing events) (default \"containerd\")\n  -socket string\n    \tabstract socket path to serve\n" file="oci/runtime_oci.go:210"
14:26:13 # time="2020-06-15 19:20:56.873628436Z" level=warning msg="unable to delete container 
```
Is this error related with the `runtime_type`? I am asking this because I specify to use the `crio.conf` where my runtime type is `vm`...is this still using `oci`? thanks

**Comment by chavafg** [comment]
@GabyCT, following @haircommander advice, could you try adding the `runtime_type` to the `--runtimes` option at: https://github.com/cri-o/cri-o/blob/master/test/helpers.bash#L306

**Comment by haircommander** [comment]
ah @chavafg that was not quite advice, but rather a statement that it's something we *should* support. it would fail now AFAICT

**Comment by chavafg** [comment]
Ohh ok, I misunderstood it, thanks for the explanation
