### ISSUE TITLE
[Ubuntu 20.04] [cri-o-1.17~1] Broken symlink: /usr/lib/systemd/system/cri-o.service

### ISSUE THREAD

**Issue by jayaddison** [cri-o/cri-o#3879]
**Description**
This looks like a minor packaging issue and it does not appear to be causing direct problems.

**Steps to reproduce the issue:**
1. Set up an Ubuntu 20.04 environment
2. Within the environment, run `apt install cri-o-1.17=1.17.4~1`
3. Inspect the symlink:

```sh
$ ls -l /usr/lib/systemd/system/cri-o.service
lrwxrwxrwx 1 root root 81 Apr  8 17:07 /usr/lib/systemd/system/cri-o.service -> ../../../src/packages/BUILD/debian/cri-o-1.17/usr/lib/systemd/system/crio.service
```

4. Confirm that the target symlink does not exist:

```sh
$ stat -L /usr/lib/systemd/system/cri-o.service
stat: cannot stat '/usr/lib/systemd/system/cri-o.service': No such file or directory
```

**Describe the results you received:**
`/usr/lib/systemd/system/cri-o.service` looks like a package build-time symlink

**Describe the results you expected:**
`/usr/lib/systemd/system/cri-o.service` should point to a valid systemd service definition file, or should be removed from the `cri-o-1.17` package if it is not required

**Output of `crio --version`:**

```
crio version 1.17.4
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
# /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
```

**Comment by haircommander** [comment]
@lsm5 @dougsland PTAL

**Comment by haircommander** [comment]
https://github.com/cri-o/cri-o/pull/3890 will fix this on master, I will backport to appropriate branches when it's approved. thanks for opening @jayaddison

**Comment by jayaddison** [comment]
Brilliant, thanks @haircommander!

**Comment by haircommander** [comment]
this should now be fixed in the latest revision [here](https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable:cri-o:1.17)

**Comment by jayaddison** [comment]
Thanks @haircommander!
