### ISSUE TITLE
No default registry in crio.conf

### ISSUE THREAD

**Issue by kubealex** [cri-o/cri-o#3884]
This happens since yesterday evening

**Steps to reproduce the issue:**
1. Install cri-o
2. try to pull an image from unqualified registry
3. enjoy the error

**Describe the results you received:**
[kube@k8s-master-0 ~]$ sudo crictl pull alpine:latest
FATA[0000] pulling image failed: rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image, add at least one in either /etc/crio/crio.conf or /etc/containers/registries.conf

**Describe the results you expected:**
Image pulls from docker.io (reported as default, but missing in the configuration)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
[kube@k8s-master-0 ~]$ crio --version
crio version 
Version:       1.18.1
GitCommit:     5cbf694c34f8d1af19eb873e39057663a4830635
GitTreeState:  clean
BuildDate:     2020-06-08T13:01:11Z
GoVersion:     go1.13.11
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VM/Physical Centos 7 installation

**Comment by haircommander** [comment]
what's the output of `rpm -q containers-common`?

**Comment by kubealex** [comment]
Sorry for the delay:

[kube@k8s-master-0 ~]$ rpm -q containers-common
containers-common-1.0.0-1.el7.x86_64

**Comment by haircommander** [comment]
I would expect registries.conf to be populated by containers-common. do you have a registries.conf on the node? (or registries.conf.d?)

**Comment by kubealex** [comment]
Yep, but unqualified registry section Is empty, I will post the output as soon as I get home! :)

**Comment by haircommander** [comment]
ah!

we unqualified search registries are inherently insecure (there have been cases where a bad actor can MitM because of the way a search works).

as such, we recommend users strictly use (ideally) digests, or fully qualified images. If that's not possible, you're free to fill the unqualified registries, but I do not think we should add entries by default

**Comment by kubealex** [comment]
> ah!
> 
> unqualified search registries are inherently insecure (there have been cases where a bad actor can MitM because of the way a search works).
> 
> as such, we recommend users strictly use (ideally) digests, or fully qualified images. If that's not possible, you're free to fill the unqualified registries, but I do not think we should add entries by default

Great then, I Will notify this to nginx team, ingress controller used to have unqualified images for admission pods, so It stopped working and I was thinking that something changed :)

I close this, thank you!!
