### ISSUE TITLE
NOT POSSIBLE TO INSTALL CRIO RHEL8

### ISSUE THREAD

**Issue by liticia-hub** [cri-o/cri-o#3888]
sudo yum install crio 
ansible  - 8                                            253 Kb/s | 2.6 Kb 
puppet-6 - 8                                         243 Kb/s | 2.6 Kb
No match for argument: crio
Error: Unable to find a match: crio

**Comment by haircommander** [comment]
we only package cri-o for rhel8 through openshift. You may have some luck with the centos 8 packaging in [obs](https://build.opensuse.org/project/monitor/devel:kubic:libcontainers:testing:cri-o:1.18?arch_x86_64=1&blocked=1&broken=1&building=1&defaults=0&deleting=1&dispatching=1&failed=1&finished=1&locked=1&repo_CentOS_8=1&scheduled=1&signing=1&succeeded=1&unresolvable=1)

**Comment by liticia-hub** [comment]
Ok ! Thanks
