### ISSUE TITLE
how to limit container rootfs size?

### ISSUE THREAD

**Issue by yichengliu58** [cri-o/cri-o#3904]
**Description**
I'm looking for the way to limit the size of containers' rootfs (writeable layer). There is an option in docker
`--storage-opt dm.basesize=10G` to set it, but I didn't find a method in cri-o.

I'm not sure if this option is defined in CRI, but since this is an important option for containers, there should be a way to limit it.

**Comment by haircommander** [comment]
I can't find documentation that it's exposd at the CRI

if you're using devicemapper storage driver (which we do not recommend), then you can set `basesize = "x"` in your /etc/containers/storage.conf, which will be applied to every container.
I think we have an option to set quotas on overlay (recommended driver) on XFS, but I can't remember the specifics

cc @nalind @rhatdan @giuseppe

**Comment by nalind** [comment]
For overlay that'd be done by setting a value for the `size` setting in the `[storage.options.overlay]` section of storage.conf.  The underlying XFS filesystem will also need to be mounted using the `prjquota` option.  The driver will assign a project ID to the directory tree used to store the container's read-write layer and will set a quota for the project.  I don't believe that this is exposed via CRI, nor by the storage library at the time when the container's read-write layer is being created.

**Comment by rhatdan** [comment]
The images should be run read-only in Kubernetes, and then the problem is solved.  :^)  Otherwise you need to use @nalind solution.

**Comment by yichengliu58** [comment]
Thanks guys ！ @nalind solution works fine
