### ISSUE TITLE
How to pass ldconfig to crio 

### ISSUE THREAD

**Issue by raz-bn** [cri-o/cri-o#3906]
Hey I'm trying to pass to crio a different ldconfig from the one in @/sbin/ldconfig.real
Is there anyway to do so?
Didn't find any reference to it in the crio.config file

**Comment by haircommander** [comment]
are you trying to pass ldconfig to each container cri-o launches, or are you trying to compile crio with a specific ldconfg?

**Comment by raz-bn** [comment]
> are you trying to pass ldconfig to each container cri-o launches, or are you trying to compile crio with a specific ldconfg?

@haircommander thanks for the fast response!
I'm trying to pass ldconfig to each container crio launches

**Comment by haircommander** [comment]
you could add an entry to your `default_mounts_file` (in your crio config) that mounts /sbin/ldconfig.real for every container (that assumes that each container uses the same ldconfig location)

**Comment by raz-bn** [comment]
@haircommander, thanks for the response again! 

I tried to do as you suggested and it did not solve my problem.
I will explain my problem with more details. Hopefully, you can give me some insight :)

I am using Openshift 4.4 with cri-o as my default container runtime, and my nodes are running CoreOS.
I'm trying to access Nvidia drivers for inside a container cri-o launches. However, I'm installing those drivers using a container that installs them directly into the host OS. This container sees the path /run/nvidia as its root volume. Therefore, the drivers are located in a different path inside the file system rather than the default one.

This is the log for the container I'm trying to run:
![image](https://user-images.githubusercontent.com/52315689/85691415-2b609900-b6dd-11ea-90c4-22eed8486887.png)
this error means the container doesn't detect the GPU card on my machine.

Trying to debug this issue, I installed the Nvidia-docker container run time to see if something is wrong with my driver's installation.

using this runtime hook:

```
{
    "version": "1.0.0",
    "hook": {
        "path": "/usr/local/nvidia/toolkit/nvidia-container-toolkit",
        "args": ["nvidia-container-toolkit", "prestart"],
        "env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/nvidia/toolkit"
        ]
    },
    "when": {
        "always": true,
        "commands": [".*"]
    },
    "stages": ["prestart"]
}
```

and this nvidia-docker config:

```
disable-require = false
#swarm-resource = "DOCKER_RESOURCE_GPU"

[nvidia-container-cli]
root = "/run/nvidia/driver"
#path = "/usr/bin/nvidia-container-cli"
environment = []
#debug = "/var/log/nvidia-container-toolkit.log"
#ldcache = "/etc/ld.so.cache"
load-kmods = true
#no-cgroups = false
#user = "root:video"
ldconfig = "@/run/nvidia/driver/sbin/ldconfig.real"

[nvidia-container-runtime]
#debug = "/var/log/nvidia-container-runtime.log"
```

And this is why I thought about passing the same ldconfig to the container cri-o launches, but I got the same error.

I am kind of lost now. I hope you can help me even if a bit :)

**Comment by raz-bn** [comment]
@haircommander Hey! I fixed the issue and it was not related to cri-o at all.
However, after fixing it I stumbled with another issue which is related to cri-o.
cri-o is looking for the file /dev/nvidia0, but this file is located in /run/nvidia/driver/dev/nvidia0
I fixed it by creating a soft link to this file, but is there any way to make cri-o look for it in /run/nvidia/driver/dev/ ?

**Comment by zvonkok** [comment]
@raz-bn Why are you not using the NVIDIA GPU operator, it is enabling everything you need for using GPUs in a cluster? 

The GPU operator will deploy a DriverContainer, Container enablement (prestart hook), metrics. 

You are trying to solve problems that are already solved by the NV GPU operator.

**Comment by raz-bn** [comment]
> @raz-bn Why are you not using the NVIDIA GPU operator, it is enabling everything you need for using GPUs in a cluster?
> 
> The GPU operator will deploy a DriverContainer, Container enablement (prestart hook), metrics.
> 
> You are trying to solve problems that are already solved by the NV GPU operator.

@zvonkok Thank you for replay again.
I am using the GPU-Operator by Nvidia, but the driver container is installing the drivers under the /run/nvidia/driver/ path.
Also using this project: https://github.com/tkestack/gpu-manager
and in there, they are using a different device plugin.
If I'm trying to deploy a pod that requires nvidia.com/gpu, everything works just fine.
but when trying to deploy a pod with their tencent.com/vcuda-core I get the following error:
```
Error: lstat /dev/nvidia0: no such file or directory
```
since the right path is:
```
/run/nvidia/driver/dev/nvidia0
```

**Comment by zvonkok** [comment]
@raz-bn This is by design, the DriverContainer lays down the dev files there so that the prestart hook can mount them from a well known location. 

The project you referring to is just reimplementing what we already have and is certified and tested by RH. 

What is your use-case? Why do you want to use the gpu-manager? 


Just create a Pod allocating `nvidia.com/gpu: 1` and you're done.

**Comment by zvonkok** [comment]
@raz-bn The device-plugin is nothing magical it will just expose the healthy hardware via extended resources to the cluster. What is so special about the gpu-manager device-plugin?
