### ISSUE TITLE
Openshift 4.4 nvidia-runtime hook

### ISSUE THREAD

**Issue by raz-bn** [cri-o/cri-o#3907]
Hey!
is there any way to use the nvidia-runtime hook only on certain containers and not on all of them?

**Comment by zvonkok** [comment]
@raz-bn The NVIDIA prestart hook will check for specific environment variables in the container to enable GPUs in the container.  If a container does not have this env variable the hook will just exit. 

What are you trying to achieve? Do you want to run the hook only for a specific set of GPU containers? 

Being a prestart runtime hook it will be executed every time you start up a container before the command or entrypoint is executed by the runtime. 

The file `/etc/containers/oci/hooks.d/oci-nvidia-hook.json` is the activation file that states in which state to run the hook.

**Comment by raz-bn** [comment]
> Do you want to run the hook only for a specific set of GPU containers

@zvonkok thanks for your response!

I have one pod which exports metrics from the GPU (but do not consume GPU), according to Nvidia this pod requires to set the default runtime to nvidia.
All the other pods in this node will consume GPUs but I don't want them to run with the Nvidia runtime. (they don't even use the Nvidia device plugin). 
is there any way to achieve this?

**Comment by ArangoGutierrez** [comment]
Hi @raz-bn , when you say `set the default runtime to nvidia.` you are referring to using a different container runtime?

**Comment by raz-bn** [comment]
> Hi @raz-bn , when you say `set the default runtime to nvidia.` you are referring to using a different container runtime?

@ArangoGutierrez 
Yes, sorry if it was not clear.

**Comment by zvonkok** [comment]
The NVIDIA runtime is not used in the cri-o use-case. We need only the prestart hook. 
The monitoring pod should not allocate the GPU extended resources (nvidia.com: x) and just export the `NVIDIA_VISIBLE_DEVICES=all` env variable which will trigger the prestart hook.

**Comment by ArangoGutierrez** [comment]
Yes, and to be clear, you are always running with the CRI-O runtime, what is happens with the OCI hook is that it informs the runtime the needed paths to bind mount at pre-start. but the Runtime is not modified.

**Comment by raz-bn** [comment]
@zvonkok 
@ArangoGutierrez 
Oh, that sounds good for me.
I will try to do as you suggested and reopen the issues is something went wrong.
Thanks a lot!

**Comment by raz-bn** [comment]
@zvonkok 
@ArangoGutierrez 
I don't want to bother you too much but since you were so kind.
Can you please take a look at my other issue?
https://github.com/cri-o/cri-o/issues/3906
