### ISSUE TITLE
how to set the size of /dev/shm ?

### ISSUE THREAD

**Issue by yichengliu58** [cri-o/cri-o#3916]
**Description**

I'm trying to find the config that can set the size of /dev/shm file in container, but didn't find anything. In docker, option `--shm-size="64M"` can be used when running a container, is there any similar config in cri-o that can be used to set this value?

**Comment by haircommander** [comment]
it's not a supported configuration in the cri: https://github.com/kubernetes/kubernetes/issues/28272

so I'm afraid there's no way to pass this value down to cri-o

**Comment by haircommander** [comment]
@yichengliu58 if `ShmSize` was set globally for all containers, would that satisfy your needs?

**Comment by yichengliu58** [comment]
@haircommander of course, it'd be great to be able to set `ShmSize` globally. But I think it might be a better way to support this config per pod instead of globally. 
Would it be an easy way if we add an annotation in `PodSpec` to specify this value, `cri-o` finds this annotation and checks if it needs to set this value? This doesn't involve changing CRI, it's totally a cri-o feature.

**Comment by haircommander** [comment]
the main concern I'd have is making sure there is sufficient control from an admin's perspective to protect against malicious users, as any user can add an annotation to their pod.

There could be a two tiered approach, where one defined a max_shm_size in crio.conf, and then allows users to specify (with annotations) a custom shm size.

though, I suppose that'd also be a vector for DOSing the node...

**Comment by yichengliu58** [comment]
it's true this could be a risk point if there are malicious users setting unexpected values... 
But I think this could be handled by outside systems. For example you can simply have an admission system for untrusted users to deploy their workloads, where the system can check all the values before deploying into K8S. And administrators are able to configure those values easily.
My key point is: it's not always easy to support both new features and security in one system at the same time, there could be other system to help. So we should support this feature (set `ShmSize`), and provide a config to toggle on/off this feature, users can use it at their own risk.

**Comment by haircommander** [comment]
would you have any interest in attempting a PR @yichengliu58 ?

**Comment by yichengliu58** [comment]
Yes of course, I'll try to work on this in my spare time. I'll make a PR after it's done.

**Comment by haircommander** [comment]
awesome, thanks!
