### ISSUE TITLE
big container  image pulling failed /var/tmp no space left on device

### ISSUE THREAD

**Issue by punkprzemo** [cri-o/cri-o#3917]
Hello,
I'm using cri-o runtime (1.18.1) in our kubernetes (1.18.3) cluster. 
Everything was OK until I started pulling big container images from private repo. 
```
# crictl pull myprivate.registry/big-image:latest
FATA[0009] pulling image failed: rpc error: code = Unknown desc = Error writing blob: error storing blob to file "/var/tmp/storage333619107/1": write /var/tmp/storage333619107/1: no space left on device
```
Same issue when images are pulled inside kubernetes cluster.

On my  RHEL 7 server I have small /var/tmp dir which has 1G. 

Do you know how to switch tmp directory for image pull? I would like to store them e.g. in /var/lib/containers/tmp.

my crio version:
```
# /usr/local/bin/crio version
Version:       1.18.1
GitCommit:     5cbf694c34f8d1af19eb873e39057663a4830635
GitTreeState:  clean
BuildDate:     2020-05-14T14:16:02Z
GoVersion:     go1.14
Compiler:      gc
Platform:      linux/amd64
Linkmode:      static
```

cri-o was installed from the cri-o static build

I have only added some custom values in `/etc/crio.conf.d/99-custom.conf`. 
```
[crio]

log_dir = "/var/log/crio/pods"

[crio.runtime]

selinux = true

[crio.image]

pause_image = "myprivate.registry/pause:3.2"
```

`crio.conf` file wasn't changed as i set my overrides in above custom  `/etc/crio.conf.d/99-custom.conf`.

Regards

**Comment by haircommander** [comment]
related: https://github.com/containers/image/pull/747

we currently do not support overriding the BigFilesTemporaryDir.

Extending CRI-O wouldn't be too difficult. it could be wired up by setting the SystemContext in `pkg/config/config.go`: https://github.com/cri-o/cri-o/blob/d0dc0d3076367f6a26c46fb6e72d1e582b552599/pkg/config/config.go#L528

Would you have any interest in submitting a PR @punkprzemo

**Comment by adawolfs** [comment]
@haircommander I would like to help, if there is no problem with @punkprzemo of course! 

I've already taken a look to the code and I have a solution in progress but I would like to know if **BigFilesTemporaryDir** should be placed in a new toml table or like `crio.system` or should be part of `crio.image` ?

**Comment by haircommander** [comment]
Thank you @adawolfs , i think `crio.image` makes most sense 😃

**Comment by punkprzemo** [comment]
Thanks for answers @haircommander and @adawolfs 
As a temporary solution for us  we have rebuilt cri-o 1.18.2 and set below in  [config.go](https://github.com/cri-o/cri-o/blob/v1.18.2/pkg/config/config.go) to override default `/var/tmp`
```
return &Config{
   SystemContext: &types.SystemContext{
      DockerRegistryUserAgent: useragent.Get(),
      BigFilesTemporaryDir: "/var/lib/containers/tmp",
   },
```
 But would be great to have it configurable in `crio.conf`.
