### ISSUE TITLE
Consider changing runc dependency from Required to Recommended in package builds

### ISSUE THREAD

**Issue by rbtr** [cri-o/cri-o#3923]
**Description**

When installing `cri-o` on F32 according to the docs, it tries to install `runc` as a Required dependency. Likewise, due to this relation, _uninstalling_ `runc` tries to also uninstall the dependent `cri-o`. 

I don't want `runc` - I have `crun` installed already, but I can only either install `cri-o` with NO dependencies (:-1:), or with them all (including `runc`, because `runc` is a "Required" dependency - also :-1:).

Since `runc` is not actually a hard dependency - as far as I understand it, any OCI runtime should work - I think it should be changed in to a "Recommended" dependency. Then, if I naively install `cri-o` with dnf, I still get `runc`, but if I know I have `crun` and don't want `runc`, I can `--setopt=install_weak_deps=False` and skip that weak dep.

**Steps to reproduce the issue:**
1. Install cri-o per docs on Fedora >= 30:
    - ```
      dnf module enable cri-o:1.18
      dnf install cri-o
      ```
    - note `runc` is also installed as a required dependency
2. Uninstall `runc` via dnf: 
    - `dnf remove runc`
    - note `cri-o` is also uninstalled

**Comment by mrunalp** [comment]
@lsm5 @dougsland ptal

**Comment by rbtr** [comment]
any movement on this?

**Comment by haircommander** [comment]
thanks for the ping @rbtr I am updating the spec now

**Comment by rbtr** [comment]
@haircommander awesome to hear, thank you!

**Comment by haircommander** [comment]
I have updated 1.18 module. we have an autobuilder that picks up changes and pushes every hour. Please let me know if you can't see it changed soon!

**Comment by rbtr** [comment]
hey @haircommander, I can see that you've updated the spec on src.fedoraproject.org but that doesn't seem to have made it to the packages that I see on my end (at least through DNF on F32). Any hiccups with that autobuilder?

**Comment by lsm5** [comment]
@rbtr 1.17 and 1.18 are in pending state:
```
 cri-o-1.17-3220200804180155.43bbeeef     module     pending   2020-08-06 (0)
 cri-o-1.17-3120200804180155.f636be4b     module     pending   2020-08-06 (0)
 cri-o-1.18-3120200804180129.f636be4b     module     pending   2020-08-06 (0)
 cri-o-1.18-3220200804180129.43bbeeef     module     pending   2020-08-06 (0)
 cri-o-1.16-3220200804175424.43bbeeef     module     testing   2020-08-05 (1)
 cri-o-1.16-3120200804175424.f636be4b     module     testing   2020-08-05 (1)
```

These should land in testing soon.

It's my bad that the auto-builder ain't quite working as expected atm. A few things to iron out and we hope to have it enabled next week.

**Comment by rbtr** [comment]
copy that, thanks for the update. I'll keep an eye out!

**Comment by rbtr** [comment]
@haircommander @lsm5 Just got the chance to check this again; looks good on my end!
```
$ sudo dnf install cri-o
...
...
Installing weak dependencies:
 runc
```
:tada: 

Thanks for this!

**Comment by haircommander** [comment]
excellent to hear!

As such, I'm closing this
