### ISSUE TITLE
Streamline how done channel is closed in Runtime#WaitContainerStateStopped

### ISSUE THREAD

**Issue by tedyu** [cri-o/cri-o#3925]
**Description**

Currently the done channel may be closed in the goroutine or by the select statement starting on line 139.
We need to consider the following scenario:
* detection of ContainerStateStopped exhausts the timeout, with done channel closed by the select statement starting on line 139
* around the same time, ContainerStateStopped is returned from UpdateContainerStatus call, resulting in the close of done channel on line 132.

Thanks to @haircommander for noticing such scenario.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
Potential panic closing done channel twice.

**Describe the results you expected:**
I am thinking about the following change:
```
diff --git a/internal/oci/oci.go b/internal/oci/oci.go
index 459a99667..3008c6162 100644
--- a/internal/oci/oci.go
+++ b/internal/oci/oci.go
@@ -126,11 +126,10 @@ func (r *Runtime) WaitContainerStateStopped(ctx context.Context, c *Container) (
                                // Check if the container is stopped
                                if err := impl.UpdateContainerStatus(c); err != nil {
                                        done <- err
-                                       close(done)
                                        return
                                }
                                if c.State().Status == ContainerStateStopped {
-                                       close(done)
+                                       done <- nil
                                        return
                                }
                                time.Sleep(100 * time.Millisecond)
@@ -139,6 +138,7 @@ func (r *Runtime) WaitContainerStateStopped(ctx context.Context, c *Container) (
        }()
        select {
        case err = <-done:
+               close(done)
                break
        case <-ctx.Done():
                close(chControl)
```
This way, responsibility of closing done channel is up to the select statement starting line 139.
If the goroutine returns due to err updating container status or ContainerStateStopped being reached, the read from done channel on line 140 would return and we can close the done channel.

There wouldn't be any race between the select statement on line 139 and the goroutine.

**Output of `crio --version`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by haircommander** [comment]
This sounds good to me
