### ISSUE TITLE
container with securityContext: priviledge: true by pass file permissions

### ISSUE THREAD

**Issue by hxquangnhat** [cri-o/cri-o#3937]
**Description**
A container deployed on Kubernetes cluster using Crio can by pass file permission when securityContext: priviledge: true, meanwhile on another Kubernetes cluster using Docker, it doesn't happen.

**Steps to reproduce the issue:**
1. Deploying filebeat on Kubernetes cluster using this official chart from Elastic: https://github.com/elastic/helm-charts/blob/master/filebeat
2. Filebeat image was rebuilt to set the user to a non-root user (`aapuser`, with id `20000` here)
3. Change the value in `podSecurityContext` section:
``podSecurityContext:
  runAsUser: 20000
  privileged: true
``

**Describe the results you received:**
Executed into a filebeat pod, run the following command and got the result:
```
bash-4.2$ stat /var/log/messages
  File: '/var/log/messages'
  Size: 862504680       Blocks: 1684592    IO Block: 4096   regular file
Device: fd03h/64771d    Inode: 44          Links: 1
Access: (0600/-rw-------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-07-06 13:24:35.786599943 +0000
Modify: 2020-07-08 13:59:05.998718566 +0000
Change: 2020-07-08 13:59:05.998718566 +0000
 Birth: -
bash-4.2$ getfacl /var/log/messages
getfacl: Removing leading '/' from absolute path names
# file: var/log/messages
# owner: root
# group: root
user::rw-
group::---
other::---

bash-4.2$ id
uid=20000(aapuser) gid=20000(aapuser) groups=20000(aapuser)
bash-4.2$ head -n 2 /var/log/messages
Mar 15 03:12:01 XXXX rsyslogd: [origin software="rsyslogd" swVersion="8.24.0-34.el7" x-pid="7155" x-info="http://www.rsyslog.com"] rsyslogd was HUPed
Mar 15 03:12:42 XXXX rhsmd: In order for Subscription Manager to provide your system with updates, your system must be registered with the Customer Portal. Please enter your Red Hat login to ensure your system is up-to-date.
```
We can read and even write to the `/var/log/messages` file which is owned by only `root`

**Describe the results you expected:**
We shouldn't be able to read the `/var/log/messages` file

**Additional information you deem important (e.g. issue happens only occasionally):**
Within another kubernetes cluster running with docker, we got the permission denied when trying to read `/var/log/messages` inside a filebeat pod with the same setup
```
bash-4.2$ stat /var/log/messages
  File: '/var/log/messages'
  Size: 191829213       Blocks: 374680     IO Block: 4096   regular file
Device: fd04h/64772d    Inode: 28          Links: 1
Access: (0600/-rw-------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-05-10 01:47:02.000000000 +0000
Modify: 2020-07-08 13:57:01.317499816 +0000
Change: 2020-07-08 13:57:01.317499816 +0000
 Birth: -
bash-4.2$ getfacl /var/log/messages
getfacl: Removing leading '/' from absolute path names
# file: var/log/messages
# owner: root
# group: root
user::rw-
group::---
other::---

bash-4.2$ id
uid=20000(aapuser) gid=20000(aapuser) groups=20000(aapuser)
bash-4.2$ head -n 2 /var/log/messages
head: cannot open '/var/log/messages' for reading: Permission denied
```

**Output of `crio --version`:**

```
crio version
Version:       1.18.1
GitCommit:     5cbf694c34f8d1af19eb873e39057663a4830635
GitTreeState:  clean
BuildDate:     2020-06-16T08:06:12Z
GoVersion:     go1.13.11
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Kubernetes version: 
```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by haircommander** [comment]
I'd be curious if using cri-containerd does the same thing docker does or CRI-O

**Comment by haircommander** [comment]
also, what version of runc are you using?

**Comment by hxquangnhat** [comment]
here's our runc version:
```runc version spec: 1.0.1-dev```

**Comment by haircommander** [comment]
oh! what operating system and are you running with SELinux?

**Comment by hxquangnhat** [comment]
the OS is RHEL 7.8 (maipo) and yes, we enabled SELinux

**Comment by haircommander** [comment]
can you try by disabling SELinux? that'll show us if it's that or not
