### ISSUE TITLE
crictl inspect does not show any information about the container cpuset.cpus

### ISSUE THREAD

**Issue by cynepco3hahue** [cri-o/cri-o#3963]
**Description**

`crictl inspect` does not show any information about the `cpuset.cpus`, only fields that I can see is:
```
"cpu": {
      "shares": 1024,
      "quota": 100000,
      "period": 100000
},

```

**Steps to reproduce the issue:**
1. Run any container and check the container via `crictl inspect`
2.
3.

**Describe the results you received:**
No information about the container `cpuset.cpus`

**Describe the results you expected:**
I expect to get the updated information regarding the `cpuset.cpus`, if the CPU manager updated the container `cpuset.cpus` via `UpdateContainerResources` I expected to the updated value under the container status.

**Additional information you deem important (e.g. issue happens only occasionally):**
It some additional fields that I can not see, for example, field with the value of `cpuset.mems`
**Output of `crio --version`:**

```
# crio version
Version:       1.19.0-dev
GitCommit:     3e17a74a8f7bf708b2e0250028ed118d65686c22
GitTreeState:  dirty
BuildDate:     2020-07-16T18:48:34Z
GoVersion:     go1.14.4
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I tested it in dev build of k8s, but the same behavior I can see under the OpenShift.

**Comment by cynepco3hahue** [comment]
I would try to fix it if someone ready to be my mentor :)

**Comment by haircommander** [comment]
you may be able to get this with `crictl inspect -v ...`. If not, I'd be happy to mentor you

**Comment by cynepco3hahue** [comment]
I can see it returns an error:
```
# crictl inspect -v 664e51762ca50
Incorrect Usage: flag provided but not defined: -v

NAME:
   crictl inspect - Display the status of one or more containers

USAGE:
   crictl inspect [command options] CONTAINER-ID [CONTAINER-ID...]

OPTIONS:
   --output value, -o value  Output format, One of: json|yaml|go-template|table
   --quiet, -q               Do not show verbose information (default: false)
   --template value          The template string is only used when output is go-template; The Template format is golang template
   --help, -h                show help (default: false)
   
FATA[0000] flag provided but not defined: -v
```

**Comment by cynepco3hahue** [comment]
It affects the PR https://github.com/cri-o/cri-o/pull/3936, because I also do not have anything under the
`c.Spec().Linux.Resources.CPU.Cpus` :(

**Comment by cynepco3hahue** [comment]
@haircommander Can you please explain who is responsible to update this field and store it under the container `config.json` file? Because I can see that the `crictl inspect` shows CPU quota, but I did not find any place where do we update it for the container, except the update for the sandbox.

My current understanding:
- k8s calls to the `UpdateContainerResources`
- cri-o should call runc command to update the container resources
- cri-o should update the container spec with update resources
- cri-o should store the data under the config.json file

**Comment by haircommander** [comment]
cri-o shouldn't be rewriting the config.json. that's immutable and only used for container creation. What UpdateContainerResources does is ask runc to update the cgroup information for the container.

You may have more luck getting the information from `crictl stats...` instead of inspect

**Comment by haircommander** [comment]
cri-o shouldn't be rewriting the config.json. that's immutable and only used for container creation. What UpdateContainerResources does is ask runc to update the cgroup information for the container.

You may have more luck getting the information from `crictl stats...` instead of inspect

**Comment by cynepco3hahue** [comment]
The problem not only that `crictl` does not show it, the problem that container spec does not have this information at all.
So who responsible to update the container spec after the resources update?

**Comment by fromanirh** [comment]
Hey, interested in this issue. worth noting that AFAIR if you try the same thing mentioned in https://github.com/cri-o/cri-o/issues/3963#issue-658490630 with containerd (easy example: kind), you do get the `cpuset.cpus` reporting. I'll fetch an example ASAP.

**Comment by fromanirh** [comment]
> Hey, interested in this issue. worth noting that AFAIR if you try the same thing mentioned in [#3963 (comment)](https://github.com/cri-o/cri-o/issues/3963#issue-658490630) with containerd (easy example: kind), you do get the `cpuset.cpus` reporting. I'll fetch an example ASAP.

```bash
$ alias K=kubectl
$ kind version
kind v0.8.1 go1.14.2 linux/amd64
$ cat multi-node1.18.yaml 
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
- |
  kind: KubeletConfiguration
  cpuManagerPolicy: "static"
  topologyManagerPolicy: "single-numa-node"
  reservedSystemCPUs: "1,3"
nodes:
- role: control-plane
  image: kindest/node:v1.18.0@sha256:0e20578828edd939d25eb98496a685c76c98d54084932f76069f886ec315d694
- role: control-plane
  image: kindest/node:v1.18.0@sha256:0e20578828edd939d25eb98496a685c76c98d54084932f76069f886ec315d694
- role: control-plane
  image: kindest/node:v1.18.0@sha256:0e20578828edd939d25eb98496a685c76c98d54084932f76069f886ec315d694
- role: worker
  image: kindest/node:v1.18.0@sha256:0e20578828edd939d25eb98496a685c76c98d54084932f76069f886ec315d694
- role: worker
  image: kindest/node:v1.18.0@sha256:0e20578828edd939d25eb98496a685c76c98d54084932f76069f886ec315d694
- role: worker
  image: kindest/node:v1.18.0@sha256:0e20578828edd939d25eb98496a685c76c98d54084932f76069f886ec315d694
$ docker container exec -it kind-worker /bin/ps -ax
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 /sbin/init
   99 ?        S<s    0:00 /lib/systemd/systemd-journald
  119 ?        Ssl    0:08 /usr/local/bin/containerd
 1796 ?        Ssl    0:05 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernet
 1872 ?        Sl     0:00 /usr/local/bin/containerd-shim-runc-v2 -namespace k8s
 1892 ?        Sl     0:00 /usr/local/bin/containerd-shim-runc-v2 -namespace k8s
 1921 ?        Ss     0:00 /pause
 1928 ?        Ss     0:00 /pause
 1973 ?        Ssl    0:00 /bin/kindnetd
 1999 ?        Ssl    0:00 /usr/local/bin/kube-proxy --config=/var/lib/kube-prox
 2179 ?        Sl     0:00 /usr/local/bin/containerd-shim-runc-v2 -namespace k8s
 2203 ?        Ss     0:00 /pause
 2254 ?        Ssl    0:00 redis-server *:6379
 2954 pts/1    Rs+    0:00 /bin/ps -ax
$ K get pods -o json | jq '.items[0].spec.containers[0].resources'
{
  "limits": {
    "cpu": "2",
    "memory": "200Mi"
  },
  "requests": {
    "cpu": "2",
    "memory": "200Mi"
  }
}
$ K get pods -o json | jq '.items[0].status.qosClass'
"Guaranteed"
$ docker container exec -it kind-worker /usr/local/bin/crictl ps
CONTAINER           IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID
dca1a0ce78d28       2355926154447       4 minutes ago       Running             redis-qos-ctr-0     0                   7e294a4fb060b
313b0a5f18efb       8aff47b2a8d8d       4 minutes ago       Running             kube-proxy          0                   6c22130bc4cc6
37cb5bf874892       2186a1a396deb       4 minutes ago       Running             kindnet-cni         0                   fe5cef111a4f8
$ docker container exec -it kind-worker /usr/local/bin/crictl inspect dca1a0ce78d28 | jq '.info["runtimeSpec"]["linux"]["resources"]'
{
  "devices": [
    {
      "allow": false,
      "access": "rwm"
    }
  ],
  "memory": {
    "limit": 209715200
  },
  "cpu": {
    "shares": 2048,
    "quota": 200000,
    "period": 100000,
    "cpus": "0,6"
  }
}

```

**Comment by haircommander** [comment]
ah! We will happily accept a PR from either of you to fix this discrepancy :smiley:

**Comment by cynepco3hahue** [comment]
I created the PR to fix the issue with the `UpdateContainerResources`, but we still will have this value empty, before `UpdateContainerResources` will run at least once. I do not think we should set any default values, because it an API consumer responsibility to send proper values for the container creation(in our case k8s - see https://github.com/kubernetes/kubernetes/blob/363c3b89f570142da5c43b1ccbd99629f03e0ee0/pkg/kubelet/kuberuntime/kuberuntime_container_linux.go#L42).

@fromanirh @haircommander WDYT?

**Comment by fromanirh** [comment]
> I created the PR to fix the issue with the `UpdateContainerResources`, but we still will have this value empty, before `UpdateContainerResources` will run at least once. I do not think we should set any default values, because it an API consumer responsibility to send proper values for the container creation(in our case k8s - see https://github.com/kubernetes/kubernetes/blob/363c3b89f570142da5c43b1ccbd99629f03e0ee0/pkg/kubelet/kuberuntime/kuberuntime_container_linux.go#L42).
> 
> @fromanirh @haircommander WDYT?

This seems reasonnable to me - as consumer of the API. I didn't check what containerd does in this case, but again, the proposed behaviour seems ok.
