### ISSUE TITLE
refactor to remove naming conflicts

### ISSUE THREAD

**Issue by wgahnagl** [cri-o/cri-o#3965]
in the code, we reuse a lot of terms like container, image and sandbox. It would be really nice if we could figure out exactly what those interfaces do, and then rename them accordingly. (if it's the factory for a container or a sandbox, we should put factory somewhere in the name, so uses can be unambiguous)

**Comment by haircommander** [comment]
agreed! I think a good first step would be renaming `pkg/sandbox` and `pkg/container` to `pkg/factory/container` and `pkg/factory/container` with each of the interfaces being named {Sandbox,Container}Factory. WDYT @saschagrunert 

I am also interested in feedback about other confusing cases from newer contributors.

**Comment by saschagrunert** [comment]
> agreed! I think a good first step would be renaming `pkg/sandbox` and `pkg/container` to `pkg/factory/container` and `pkg/factory/container` with each of the interfaces being named {Sandbox,Container}Factory. WDYT @saschagrunert

Probably a good first step. I know it seems confusing that we have multiple levels of containers which express something different, so I guess we could need any help we can get to fight this kind of technical depth.

**Comment by haircommander** [comment]
I went for `internal/ctrfactory` and `internal/sboxfactory` though I am not married to that

**Comment by haircommander** [comment]
this was done in https://github.com/cri-o/cri-o/pull/5623
