### ISSUE TITLE
Remove resolvPath when Relabel fails

### ISSUE THREAD

**Issue by tedyu** [cri-o/cri-o#3976]
**Description**

In Server#runPodSandbox, when Relabel fails, it seems we should remove resolvPath before returning the error.

This would be consistent with the handling in case parseDNSOptions() returns error.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you expected:**
resolvPath shouldn't linger when relabeling fails.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
(paste your output here)
```

**Comment by tedyu** [comment]
Here is proposed fix:
```
diff --git a/server/sandbox_run_linux.go b/server/sandbox_run_linux.go
index acdc7d5f1..1fc4324d4 100644
--- a/server/sandbox_run_linux.go
+++ b/server/sandbox_run_linux.go
@@ -163,6 +163,11 @@ func (s *Server) runPodSandbox(ctx context.Context, req *pb.RunPodSandboxRequest
                        return nil, err
                }
                if err := label.Relabel(resolvPath, mountLabel, false); err != nil && errors.Cause(err) != unix.ENOTSUP {
+                       err1 := removeFile(resolvPath)
+                       if err1 != nil {
+                               err = err1
+                               return nil, fmt.Errorf("%v; failed to remove %s: %v", err, resolvPath, err1)
+                       }
                        return nil, err
                }
                mnt := spec.Mount{
```
/cc @haircommander

**Comment by haircommander** [comment]
good catch, makes sense to me! (one nit, setting err = err1 will make the error double print err1)
