### ISSUE TITLE
rhel 7 and managed ns are not playing together well

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#3996]
**Description**
[we](https://github.com/cri-o/cri-o/pull/3979#issuecomment-661236332) [have](https://github.com/cri-o/cri-o/pull/3973#issuecomment-660257176) [had](https://github.com/cri-o/cri-o/pull/3987#issuecomment-661858243) [many](https://github.com/cri-o/cri-o/pull/3987#issuecomment-662043024) [of these failures](https://github.com/cri-o/cri-o/pull/3868#issuecomment-661941694)

suspiciously after https://github.com/cri-o/cri-o/pull/3929

It's hard to tell which specific change is causing it, but I am suspicious it's https://github.com/cri-o/cri-o/commit/d8615ec4693bece6b2d537463fde02263e7444cc

unfortunately, I tried reproducing locally, and on an amazon instance, and have gotten no where yet. Instead of adding comments to the issues, I'm going to compile instances here.

**Steps to reproduce the issue:**
1. run the integration tests on rhel

**Describe the results you received:**
sometimes, the managed namespaces are still busy

**Describe the results you expected:**
they should not be busy

**Additional information you deem important (e.g. issue happens only occasionally):**
so far, only on latest cri-o
**Additional environment details (AWS, VirtualBox, physical, etc.):**
so far, only aws

**Comment by haircommander** [comment]
https://storage.googleapis.com/origin-federated-results/pr-logs/pull/cri-o_cri-o/3960/test_pull_request_crio_integration_rhel/14278/artifacts/testout.txt

**Comment by haircommander** [comment]
https://storage.googleapis.com/origin-federated-results/pr-logs/pull/cri-o_cri-o/3482/test_pull_request_crio_integration_rhel/14388/artifacts/testout.txt

**Comment by haircommander** [comment]
https://storage.googleapis.com/origin-federated-results/pr-logs/pull/cri-o_cri-o/4034/test_pull_request_crio_integration_rhel/15195/artifacts/testout.txt

**Comment by haircommander** [comment]
got one on integration_crun, which is no bueno
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_crio_integration_crun_fedora/7317/s3/

**Comment by haircommander** [comment]
got one on fedora
https://storage.googleapis.com/origin-federated-results/pr-logs/pull/cri-o_cri-o/4080/test_pull_request_crio_integration_rhel/16593/artifacts/testout.txt

**Comment by kolyshkin** [comment]
OK, this is happening on RHEL7 kernel because no one cared to set `fs.may_detach_mounts=1` (see more details at #4210).

Fix is coming
