### ISSUE TITLE
LFX 2024: Fully automated releases

### ISSUE THREAD

**Issue by saschagrunert** [cri-o/cri-o#4003]
<details>
<summary>Original issue description</summary>

Right now we have to do the following steps to cut a release:
1. Bump CRI-O's version in `internal/version/version.go`
2. Create a PR for that change and merge it
3. Create a release via the GitHub UI
4. Manually trigger CircleCI on the release branch
5. Update the release notes via the GitHub UI

To fully automate this process we could:
1. Add a new (golang based) script which:
    - Bumps the version automatically
    - Creates the PR automatically (via go-github and a set GITHUB_TOKEN env var)
2. Let GitHub actions *automatically* do the rest:
    - Tag the specified version
    - (Maybe bump the version again to *-dev?)
    - Create the GitHub release and push the changelog and artifacts

WDYT? I'm not sure if tagging the PR commit will cause issues in the future.

Refs: https://github.com/cri-o/cri-o/pull/4017

</details>

### Update

This topic is now part of the LFX mentoring program, where @olad5 will work on it

We had an onboarding call on March 12 (2024) which can be summarized as follows:

- Focus on the current state of the CI pipeline to automate the patch releases for now (the minor versions will be considered later)
- Use a GitHub action cron to propose a version bump [like this](https://github.com/cri-o/cri-o/pull/7810) once a month
- The PR needs to get manually approved by maintainers and merged by prow
- The merge will trigger the automatic release creation including the tag
- The tag will trigger the rest of the pipeline, [which is already in place](https://github.com/cri-o/cri-o/blob/ccc3e5b21399cab1e08ecc7482e772c997c745e6/.github/workflows/test.yml#L222-L239)

We probably can recycle code parts from (if not, then we may remove them):
- https://github.com/cri-o/cri-o/pull/7173
- https://github.com/cri-o/cri-o/tree/main/scripts/release

**Comment by haircommander** [comment]
Another step further would be to build for respective distributions once the release is cut

I am certainly in favor of automating :smile:

**Comment by haircommander** [comment]
we still want this!

**Comment by anshgoyalevil** [comment]
@haircommander Can I start working on some part of this issue by creating child issues to it? I really want to work upon it under LFX Fall'23

**Comment by haircommander** [comment]
good initiative! yeah please feel free to open child issues and begin breaking down the issue

**Comment by anshgoyalevil** [comment]
@saschagrunert Can we put this project to GSoC 2024?

**Comment by saschagrunert** [comment]
@anshgoyalevil we have not decided if we want to participate to the program in 2024, yet. What do @cri-o/cri-o-maintainers think?

**Comment by AkashKumar7902** [comment]
@saschagrunert I am interested in working on this project for lfx term 1 2024. I have hands-on experience in go and writing github actions. I am currently interning at CNCF landscape and GSOC organisation, Keploy. 
if there is pretask, I would love to take it!

**Comment by saschagrunert** [comment]
@AkashKumar7902 @anshgoyalevil we submitted the topic to the LFX Mentorship program: https://github.com/cncf/mentoring/pull/1146

Feel free to apply: https://github.com/cncf/mentoring/discussions/1150

**Comment by anshgoyalevil** [comment]
@saschagrunert Thanks for putting it in. I was a previous LFX Mentee, so I cannot apply again.

To all the folks applying for this idea, go for it. Feel free to ping me if you need any help related to this.

**Comment by MiirzaBaig** [comment]
@saschagrunert @haircommander I see this project perfectly suits with my tech stack and though i have also started learning about CNCF landscape etc!

**Comment by HarshvMahawar** [comment]
@saschagrunert Are there any specific needs for the LFX application, such as a proposal or anything else? Thank you.

**Comment by amitamrutiya2210** [comment]
Hello everyone 👋,

I have a basic understanding of Linux, Docker, Helm, Kubernetes, Go, version control, and GitHub Actions. I participated in GSoC 2023 with CCExtractor, working on the open-source [flood-mobile](https://github.com/CCExtractor/Flood_Mobile) project. Now, I plan to join the cri-o project through the LFX Mentorship Program.

https://github.com/cri-o/cri-o/issues/4003 caught my attention as it aligns with my skills and offers a great opportunity to gain hands-on experience with real-world open-source codebases. I've started exploring the provided resources and reviewing the issue. I'm excited about the chance to make meaningful contributions.

Looking forward to learning from the cri-o community and contributing to this valuable project.

**Comment by SD-13** [comment]
@saschagrunert @kwilczynski 
> Update the release notes via the GitHub UI
Why we need this step?

**Comment by kwilczynski** [comment]
> @saschagrunert @kwilczynski
> 
> > Update the release notes via the GitHub UI
> 
> Why we are doing this step?

@SD-13, to add release notes. Have a look at [releases](https://github.com/cri-o/cri-o/releases).

**Comment by SD-13** [comment]
@kwilczynski I tried to mean in step 3(in issues description) while publishing the release we populate the release notes then in step 5 what content need to be updated/added?

**Comment by saschagrunert** [comment]
Usually the CI rons on a tag, which is available after the GitHub release has been created. This means we have to update the existing release to contain the release notes.

**Comment by saschagrunert** [comment]
It works:

* https://github.com/cri-o/cri-o/pull/8047
* https://github.com/cri-o/cri-o/pull/8046
* https://github.com/cri-o/cri-o/pull/8045
