### ISSUE TITLE
v1.17.4+ & kubelet restart: failed to initialize top level QOS containers: root container [kubepods] doesn't exist

### ISSUE THREAD

**Issue by tstromberg** [cri-o/cri-o#4035]
**Description**

With crio v1.17.4 and above, there appears to be some kind of race condition which may cause kubelet (v1.18.3) crash-looping with the following error:

```
Jul 30 23:56:11 minikube crio[440]: time="2020-07-30 23:56:11.034428100Z" level=debug msg="request: &ListPodSandboxRequest{Filter:nil,}" file="go-grpc-middleware/chain.go:25" id=6a0d12a9-80e0-4f14-a7c3-6766ed07d8ca
Jul 30 23:56:11 minikube crio[440]: time="2020-07-30 23:56:11.034554800Z" level=debug msg="response: &ListPodSandboxResponse{Items:[]*PodSandbox{},}" file="go-grpc-middleware/chain.go:25" id=6a0d12a9-80e0-4f14-a7c3-6766ed07d8ca
Jul 30 23:56:11 minikube kubelet[1358]: E0730 23:56:11.045210    1358 kubelet.go:1845] skipping pod synchronization - container runtime status check may not have completed yet
Jul 30 23:56:11 minikube kubelet[1358]: F0730 23:56:11.051263    1358 kubelet.go:1383] Failed to start ContainerManager failed to initialize top level QOS containers: root container [kubepods] doesn't exist
Jul 30 23:56:11 minikube kubelet[1528]: E0730 23:56:11.904122    1528 reflector.go:178] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://control-plane.minikube.internal:8443/api/v1/pods?fieldSelector=spec.nodeName%3Dminikube&limit=500&resourceVersion=0: dial tcp 172.17.0.3:8443: connect: connection refused
Jul 30 23:56:11 minikube kubelet[1528]: I0730 23:56:11.891561    1528 container_manager_linux.go:271] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:remote CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:systemd KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: ReservedSystemCPUs: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerReconcilePeriod:10s ExperimentalPodPidsLimit:-1 EnforceCPULimits:true CPUCFSQuotaPeriod:100ms ExperimentalTopologyManagerPolicy:none}
Jul 30 23:56:11 minikube kubelet[1528]: I0730 23:56:11.894979    1528 kubelet.go:292] Adding pod path: /etc/kubernetes/manifests
```

**Steps to reproduce the issue:**
1. `git clone git@github.com:kubernetes/minikube.git`
2. replace `deploy/kicbase/Dockerfile` with https://gist.github.com/tstromberg/9bb9c3ebdd8893f4677a313130d5e481
3. run `docker build -t kicbase:experiment deploy/kicbase`
4. run `make`
5. run `./out/minikube delete; ./out/minikube start --vm-driver=docker --base-image=kicbase:experiment --container-runtime=crio; ./out/minikube stop; sleep 60; ./out/minikube start --vm-driver=docker --base-image=kicbase:experiment --container-runtime=crio`

**Describe the results you received:**

Roughly 50% of the time, kubelet will fail to startup on the node restart, causing no pods to come up. I find that at worst, I have to repeat that command 3 times. Unfortunately, this is one of our integration tests. :| 

If the `sleep` statement is omitted, it happens far less.

**Describe the results you expected:**

Kubernetes will come up successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

This problem does not appear in crio v1.17.3. 

To help narrow things down, I've got crio debug logs as well as kubelet logs to share, collected using:

`minikube ssh "sudo env TERM=dumb journalctl -u kubelet"`
`minikube ssh "sudo env TERM=dumb journalctl -u crio"`

Unhealthy:

[1174_unhealthy2.crio.log](https://github.com/cri-o/cri-o/files/5004356/1174_unhealthy2.crio.log)
[1174_unhealthy2.kubelet.log](https://github.com/cri-o/cri-o/files/5004357/1174_unhealthy2.kubelet.log)

Healthy:

[1174_healthy2.crio.log](https://github.com/cri-o/cri-o/files/5004358/1174_healthy2.crio.log)
[1174_healthy2.kubelet.log](https://github.com/cri-o/cri-o/files/5004359/1174_healthy2.kubelet.log)

**Output of `crio --version`:**

```
`crio version 1.17.4`
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

`minikube v1.12.1+ with the docker driver`

**Comment by haircommander** [comment]
thanks for reporting @tstromberg . I am curious if we see the same with a 1.18.x cri-o

**Comment by tstromberg** [comment]
I believe this also occurs with 1.18. @sharifelgamal may have some logs.

**Comment by afbjorklund** [comment]
> I am curious if we see the same with a 1.18.x cri-o

Testing 1.18 was complicated by #3844 (missing .deb)

**Comment by afbjorklund** [comment]
There is a 1.17.5 now

**Comment by afbjorklund** [comment]
Also seen with CRI-O 1.18.3, as per linked bug report

**Comment by afbjorklund** [comment]
It was suggested elsewhere (https://bugzilla.redhat.com/show_bug.cgi?id=1508040#c15) that this bug is related to running with a different `runc`, and the installation was using runc 1.0.0-rc10 from either the system or the vendor.

Have upgraded to the suggested cri-o-runc now, see if that fixes the problem. For some reason the version was missing from it (?), but I verified in the sources that it is using runc 1.0.0-rc92 (had a lame "1.0.0-6" package version)
