### ISSUE TITLE
CloseIO is called before exec start

### ISSUE THREAD

**Issue by liubin** [cri-o/cri-o#4046]
**Description**

When using `kubectl exec` with the `-i` option and don't provide any input, the RPC call sequence may be dis-order.

**Steps to reproduce the issue:**
1. kubectl exec -i POD_NAME date

**Describe the results you received:**

In log:

```
Aug 05 04:17:28 fedoradocker32-975ac0 crio[97226]: time="2020-08-05 04:17:28.186091648Z" level=error
msg="Failed to close stdin for container exec \"3ebcf38f49f5ecfc97fd16689ac54e8524ff56b6610d6da99eba736dbd02cd8f\""
error="exec does not exist fde479da83d3d15513e2446650b84187bcb007fc5de67dd1690e0b4f75b7eb54: not found" file="io/exec_io.go:78"
```
The RPC call sequence may be either of these:

- CloseIO -> Exec -> Start
- Exec -> CloseIO -> Start

`CloseIO` is called in https://github.com/cri-o/cri-o/blob/master/utils/io/exec_io.go#L69, a separated goroutine from main RPC call goroutine.

**Describe the results you expected:**

The RPC call sequence should be `Exec -> Start -> CloseIO`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
master branch
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by haircommander** [comment]
@liubin thanks for opening the issue. you're using kata containers here right?

**Comment by liubin** [comment]
Hi @haircommander , I'm using Kata containers, it's working now, but breaks https://github.com/kata-containers/kata-containers/pull/440 
It may be depend on implementation of shim v2.

**Comment by haircommander** [comment]
yeah we only use the `utils/io` package when we're using kata shim v2 :)

**Comment by haircommander** [comment]
do you have any interest in trying to put together a fix @liubin ?

**Comment by liubin** [comment]
> do you have any interest in trying to put together a fix @liubin ?

Ok, let me try it.

**Comment by haircommander** [comment]
thanks @liubin !
