### ISSUE TITLE
cri-o 1.17 doesn't install on RHEL 7.7 - Package does not match intended download

### ISSUE THREAD

**Issue by realnikhilkumar** [cri-o/cri-o#4050]
RHEL 7.7
Followed instructions from kubernetes https://kubernetes.io/docs/setup/production-environment/container-runtimes/

Using kubernetes 1.17.9

cri-o install fails

Downloading packages:
warning: /var/cache/yum/x86_64/7Server/devel_kubic_libcontainers_stable/packages/conmon-2.0.20-1.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 75060aa4: NOKEY--:--:-- ETA
Public key for conmon-2.0.20-1.el7.x86_64.rpm is not installed
(1/4): conmon-2.0.20-1.el7.x86_64.rpm                                                                                                                        |  38 kB  00:00:01
(2/4): containers-common-1.1.1-1.el7.x86_64.rpm                                                                                                              |  71 kB  00:00:00
cri-o-1.17.4-1.1.el7.x86_64.rp FAILED                                           [=======================================================-         ]  16 MB/s |  67 MB  00:00:00 ETA
https://download.opensuse.org/repositories/devel%3A/kubic%3A/libcontainers%3A/stable%3A/cri-o%3A/1.17/CentOS_7/x86_64/cri-o-1.17.4-1.1.el7.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=devel_kubic_libcontainers_stable_cri-o_1.17 clean metadata
Trying other mirror.
(3/4): containernetworking-plugins-0.8.6-1.el7.x86_64.rpm                                                                                                    |  35 MB  00:00:04

Error downloading packages:
  2:cri-o-1.17.4-1.1.el7.x86_64: [Errno 256] No more mirrors to try.

**Comment by haircommander** [comment]
I am going to guess running 
```
yum --enablerepo=devel_kubic_libcontainers_stable_cri-o_1.17 clean metadata
```
didn't help, right?

**Comment by realnikhilkumar** [comment]
Yes it didn't help.

**Comment by haircommander** [comment]
we are actively updating the instructions for installation. can you refer to `install.md` in this repo, or at the update PR https://github.com/kubernetes/website/pull/23000 and see if those instructions help at all?

**Comment by realnikhilkumar** [comment]
I am checking on it

**Comment by realnikhilkumar** [comment]
Do you want me to run below commands and check if installer went through

curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/CentOS_7/devel:kubic:libcontainers:stable.repo
curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.17.repo 

https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.18/CentOS_7/devel:kubic:libcontainers:stable:cri-o:1.17.repo

yum install -y cri-o

**Comment by haircommander** [comment]
yeah!

**Comment by realnikhilkumar** [comment]
Install worked now!

It still gives a warning about signature key. Is this benign or can this be ignored. Would it lead to any security/integrity risk. See attached.

Nikhil
![Key Not Present](https://user-images.githubusercontent.com/69275062/90052361-06cd7a00-dca7-11ea-8e47-13f43d88bb6e.PNG)

**Comment by realnikhilkumar** [comment]
I am closing this now. I think GPG key requires update. Install and remove both worked fine.
