### ISSUE TITLE
Version '1.18.3~2' for 'cri-o' was not found 

### ISSUE THREAD

**Issue by medyagh** [cri-o/cri-o#4074]
Similar to our previous problem with Cri-o packaging we are again blocked by cri-o package vanishing

https://github.com/kubernetes/minikube/issues/8982

we might need to drop support for cri-o in minikube in case we can not have a stable build process for crio.

**Comment by haircommander** [comment]
hey @medyagh sorry for the late reply, I was out on vacation

does installation work if you drop the `~2`? We'll need to bump the version to make patches to the build, so I do not think we can avoid going from `1.18.3~2` to `1.18.3~3`

**Comment by haircommander** [comment]
cc @lsm5

**Comment by afbjorklund** [comment]
Current workaround is `1.18.3~3`

It will probably break in the _next_ update, so maybe better off as just "cri-o" (or "cri-o-1.18" from the main repository, not sure).

https://github.com/kubernetes/minikube/blob/v1.13.0/deploy/kicbase/Dockerfile#L27_L31

> `apt-get install -y --no-install-recommends cri-o=1.18.3~3`

**Comment by haircommander** [comment]
I have personally been installing by adding the repository `VERSION=1.18:1.18.3` and running `apt install -y cri-o` is there a reason you need `cri-o=1.18.3~3`? 1.18.3 is the only version that will be in the 1.18.3 repository

**Comment by haircommander** [comment]
this is unfortunately a limitation of OBS. We're already jumping through hoops to pin specific cri-o versions (1.18.3) in addition to have a rolling release within a version (1.18). Unfortunately, when we change something in the way things are packaged (if we need to add/update one particular distro), the version needs to bump. 

If you set `VERSION=1.18:1.18.3` and run `apt install -y cri-o`, there will be no cri-o code changes. The "version pinning" that's happening here is for cri-o code (specifically, 1.18.3 version will always point to https://github.com/cri-o/cri-o/commit/61de18161fb4ccda720768c001713592b5a04e46), and not necessarily the packaging code around it. I cannot guarantee 1.18.3~3 will not change to 1.18.3~4 in the future, so I really recommend you drop the `~3`

**Comment by medyagh** [comment]
we can close this issue since we moved on from that version
