### ISSUE TITLE
cri-o compiled with Golang 1.15 errors on execing into a container

### ISSUE THREAD

**Issue by rkojedzinszky** [cri-o/cri-o#4110]
Cannot exec into a container using pty.

**Steps to reproduce the issue:**
1. Start a container
2. Try to exec into the container:
```
$ kubectl exec -it test
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
error: Internal error occurred: error executing command in container: fork/exec /usr/sbin/runc: Setctty set but Ctty not valid in child
```

**Describe the results you received:**

Could not execute command using pty in container.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens when compiled with Golang 1.15

**Output of `crio --version`:**

```
# crio --version
crio version 1.17.5
commit: "2b41afa54acf0a2cdb85ba48d905c54836a32445"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Baremetal.

Seems that upgrading dependency github.com/creack/pty to v1.1.10 would solve the issue.

https://github.com/creack/pty/pull/97
https://github.com/creack/pty/releases/tag/v1.1.10

**Comment by saschagrunert** [comment]
@rkojedzinszky I proposed a fix in #4111, can you confirm that this works for you?

**Comment by rkojedzinszky** [comment]
@saschagrunert Seems to be working as expected. Thanks for the quick response.

**Comment by saschagrunert** [comment]
> @saschagrunert Seems to be working as expected. Thanks for the quick response.

Awesome, thank you for the verification.

**Comment by haircommander** [comment]
pr merged upstream, are we good to close this?

**Comment by saschagrunert** [comment]
I think so
/close
