### ISSUE TITLE
[1.18] crio reports image up to date while still downloading

### ISSUE THREAD

**Issue by gattytto** [cri-o/cri-o#4156]
Version:       1.18.0
GitCommit:     7d79f42b28ad00cf2e7d86604a5a4007303ac328
GitTreeState:  dirty
BuildDate:     2020-08-04T01:21:36Z
GoVersion:     go1.13.8
Compiler:      gc
Platform:      linux/amd64
Linkmode:      unknown: `ldd /root/crio` failed: ldd: /root/crio: No such file or directory
  (exit status 1)

![image](https://user-images.githubusercontent.com/407397/92024932-3535f680-ed35-11ea-8e37-0737ecd8d262.png)

image is big around 4GB before unpacking

**Comment by haircommander** [comment]
@gattytto I have just been reminded of this, and I decided to check for myself (with date to confirm)

can you run `crio --log-level debug` in one window, and `date && sudo crictl pull fedora && date` in the other and post that?
I am getting first window:
```
DEBU[2020-12-02 16:18:44.158761902-05:00] Response: &PullImageResponse{ImageRef:docker.io/library/fedora@sha256:aa889c59fc048b597dcfab40898ee3fcaad9ed61caf12bcfef44493ee670e9df,}  file="go-grpc-middleware/chain.go:25" id=4db077e8-07b0-4b37-bfa0-c32c9ec53eb4 name=/runtime.v1alpha2.ImageService/PullImage
```
and second window:
```
Image is up to date for docker.io/library/fedora@sha256:aa889c59fc048b597dcfab40898ee3fcaad9ed61caf12bcfef44493ee670e9df
Wed Dec  2 04:18:44 PM EST 2020
```
which shows to me that crictl isn't returning until crio send the response (and finishes pulling)

**Comment by gattytto** [comment]
I think this got fixed in recent builds of cri-o, at least for me. zfs presents a delay in unpacking which sometimes can lead to very long non-responsive crictl command, but at least it works as expected now.
