### ISSUE TITLE
containers not started after host reboot, storage_driver overlay2

### ISSUE THREAD

**Issue by hafe** [cri-o/cri-o#4175]
**Description**

Kubespray configures storage_driver=overlay2 in crio.conf whereas  /etc/containers/storage.conf contains overlay
Containers can be deployed but after host reboot nothing is started

I been told that crio interprets overlay2 the same as overlay but it does not fully work. 

The docs are not clear if the value overlay2 is supported and it actually seems to work! A lot of old docs and threads refer to that overlay2 is superior and should be used.

**Steps to reproduce the issue:**
1. Configure crio.conf with storage_driver=overlay2 and /etc/containers/storage.conf with overlay
2. Deploy some containers, e.g. a kubernetes worker
3. Reboot host
4. => No started containers
5. Configure storage_driver=overlay in crio.conf (or commented the line out)
6. Restart crio
7. => Containers are started!

**Describe the results you received:**

Containers not started after host reboot. kubelet and crio in an endless loop trying to start containers.

**Describe the results you expected:**

Containers started

**Additional information you deem important (e.g. issue happens only occasionally):**

Easily reproduced

**Output of `crio --version`:**

Tested with 1.18.3 but also latest master as of today:

```
[root@worker-1 ~]# crio version
Version:       1.19.0-dev
GitCommit:     f136427273ea7ffa91584f54de86ee21250a3922
GitTreeState:  clean
BuildDate:     2020-09-08T17:24:33Z
GoVersion:     go1.14.7
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Vitualbox, CentOS 7

**Comment by haircommander** [comment]
I am suspicious (though not sure) that https://github.com/cri-o/cri-o/commit/36e33eb7ddc0a16c9fa6a038fee1b4348987f623 will help with this
