### ISSUE TITLE
Executing commands in containers with --tty option results in error.

### ISSUE THREAD

**Issue by kubealex** [cri-o/cri-o#4189]
**Description**

Using cricitl exec -it *anycommand* in any container fails with error:

set 13 11:04:38 k8s-worker-2.k8s.lab crio[10506]: E0913 11:04:38.180305   10506 exec.go:71] error executing command in container: fork/exec /usr/bin/runc: Setctty set but Ctty not valid in child

**Steps to reproduce the issue:**

1. run crictl exec -it anycommand in anycontainer
 

**Describe the results you received:**

This happens in Kubernetes 1.19 with kubectl exec: 
set 13 11:04:38 k8s-worker-2.k8s.lab crio[10506]: E0913 11:04:38.180305   10506 exec.go:71] error executing command in container: fork/exec /usr/bin/runc: Setctty set but Ctty not valid in child

This is the same on the host:

[kube@k8s-worker-2 ~]$ sudo crictl exec -it 968e74ed4204f sh
FATA[0000] execing command in container failed: Internal error occurred: error executing command in container: fork/exec /usr/bin/runc: Setctty set but Ctty not valid in child

**Describe the results you expected:**
The command running in the container

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
[kube@k8s-worker-2 ~]$ crio version
Version:       1.18.3
GitCommit:     61de18161fb4ccda720768c001713592b5a04e46
GitTreeState:  clean
BuildDate:     2020-09-11T03:11:20Z
GoVersion:     go1.15
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Vms

**Comment by saschagrunert** [comment]
@kubealex can you check if the issue still exists with v1.19.0?

**Comment by kubealex** [comment]
Unfortunately I can't at the moment, the SUSE repo doesn't support centos7 anymore that is the supported version for k8s. I will try to compile it and test it.

**Comment by kubealex** [comment]
> @kubealex can you check if the issue still exists with v1.19.0?

Sorry for the delay, got a bit busy these days, I confirm everything is fine now! 
Thank you!
