### ISSUE TITLE
pod status is ready, logs report error

### ISSUE THREAD

**Issue by lovebaby979** [cri-o/cri-o#4194]
ubuntu: 18.04
crio: 1.18.3
runtime: kata-runtime 1.11.3
K8S： 1.14.3
------------------------------------------------
root@mgt03:~# crictl pods coredns
POD ID              CREATED             STATE               NAME                                      NAMESPACE           ATT
558ac990df54e       20 minutes ago      Ready               coredns-d5rz8                             kube-system         1
------------------------------------------------
root@mgt03:~# crictl logs 558ac990df54e 
E0915 09:18:06.277998   62846 remote_runtime.go:295] ContainerStatus "558ac990df54e" from runtime service failed: rpc error: code = NotFound desc = could not find container "558ac990df54e": specified container not found: 558ac990df54e26dba04ccb2ce7cbd091a739878a8075ebbed12cfedb033dac0
FATA[0000] rpc error: code = NotFound desc = could not find container "558ac990df54e": specified container not found: 558ac990df54e26dba04ccb2ce7cbd091a739878a8075ebbed12cfedb033dac0 
------------------------------------------------
root@mgt03:~# crictl logs 558ac990df54e 
E0915 09:18:06.277998   62846 remote_runtime.go:295] ContainerStatus "558ac990df54e" from runtime service failed: rpc error: code = NotFound desc = could not find container "558ac990df54e": specified container not found: 558ac990df54e26dba04ccb2ce7cbd091a739878a8075ebbed12cfedb033dac0
FATA[0000] rpc error: code = NotFound desc = could not find container "558ac990df54e": specified container not found: 558ac990df54e26dba04ccb2ce7cbd091a739878a8075ebbed12cfedb033dac0 

------------------------------------------------
how to resolve the problem?

**Comment by haircommander** [comment]
a pod is different than a container in cri-o world. If you want the logs from the containers in pod 558, run `crictl ps -a | grep $pod_id` and run `crictl logs` on the resulting containers

**Comment by lovebaby979** [comment]
@haircommander thank you. Problem not resolve.

**Comment by haircommander** [comment]
you should run the CoreDNS pods (and any other pods that need the host network) without kata:
https://github.com/kata-containers/documentation/blob/master/design/architecture.md#networking

**Comment by lovebaby979** [comment]
@haircommander thank you!

**Comment by haircommander** [comment]
I believe this is resolved. please reopen if you disagree!
