### ISSUE TITLE
Wrong static release URL for 1.19.0 ?

### ISSUE THREAD

**Issue by Sh4d1** [cri-o/cri-o#4196]
Hello!

Is it normal that the URL for the 1.19.0 static release bundle is https://storage.googleapis.com/k8s-conform-cri-o/artifacts/crio-99c925beb.tar.gz and not https://storage.googleapis.com/k8s-conform-cri-o/artifacts/crio-v1.19.0.tar.gz ? 

If not could it be added?

**Comment by saschagrunert** [comment]
@Sh4d1 thank you for the hint. I fixed the link and download location. :+1:
