### ISSUE TITLE
Orphaning native fedora package

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#4200]
@lsm5 and I are considering orphaning the native fedora packages (built using fedora modules) in favor of packaging in OBS (same as every other distribution other than openSUSE).

I am opening this issue to find out of there is anyone who has any problem with that. It will no longer be in the native packaging system, but it will unify the packaging solutions and reduce maintenance burden.

**Comment by haircommander** [comment]
we will also be discussing in the [weekly community meeting](https://github.com/cri-o/cri-o/wiki/CRI-O-Weekly-Meeting) on Thursday and will have a decision by then.

**Comment by lsm5** [comment]
+1 . I am not the biggest fan of modularity myself, and I support whatever makes @haircommander's life easier :) .

@adelton IIRC you're a very active user of the fedora cri-o module. Do you see any issues with switching to a fedora package hosted on opensuse's OBS repos?

**Comment by lsm5** [comment]
btw, just to be clear, orphaning != retiring. Community members are welcome to assume ownership.

**Comment by adelton** [comment]
The main issue that I see with that change is the signal that it sends -- that CRI-O is so hard to maintain in Fedora's koji that it cannot be done, and the Kubernetes package will eventually follow suit.

**Comment by lsm5** [comment]
well it's not really cri-o but rather fedora modularity that makes things painful. Also, OBS makes it easy to manage multiple distros in one place itself.

**Comment by lsm5** [comment]
hmm, I see kubernetes is not a module atm, but rather a vanilla package, only 1 version installable from the base fedora repo. If cri-o is open to being just a package (I guess that means only 1 version at a time), then maybe we could continue to keep cri-o in fedora.

**Comment by adelton** [comment]
Why is it important for cri-o to be a modular package in Fedora, instead of ursine?

**Comment by lsm5** [comment]
I don't quite remember details but afaict, given that upstream supports mulitple release branches for all active kubernetes branches, and that modularity would allow us to support this on fedora, we went ahead with modularity.

**Comment by lsm5** [comment]
if we decide to support only one branch for fedora, guess we could do the same for centos, debian and  as well.

**Comment by adelton** [comment]
My understanding is that the primary reason for CRI-O is Kubernetes. If Kubernetes package in Fedora did not jump on the possibility of maintaining multiple versions (using modules), there's really no point for CRI-O to keep doing so.

**Comment by dustymabe** [comment]
I think there is a lot of value with modularity in being able to install various "streams" of kubernetes (i.e. choose which one to install), but it's totally up to the maintainer(s) of kubernetes in Fedora to determine if they can handle that extra load.

Assuming you get CRI-O and Kubernetes from the same place, having them either both be modules or both be non-modules make sense.

There may be some cases where people are installing a specific CRI-O version from Fedora repos and then pulling kube binaries from the public somewhere, so that would break the assumption I made above.

So... Maybe we should talk to the kube maintainers in Fedora. Do they want to do modules and just don't have the bandwidth? Do they not want to do modules and just keep a traditional package workflow?

Either way, for CRI-O I certainly thinking having at least a single package (even if it's not a module with various streams) would be better than none.

**Comment by mrunalp** [comment]
A use case for different versions is folks working with different versions of kubernetes and needing a matching cri-o version. You could be working on k8s master testing new features with latest cri-o while also working with previous versions of kubernetes to fix bugs reported by your customers.

**Comment by haircommander** [comment]
I personally see a single package as antithetical to CRI-O's support claims. We claim to support all supported k8s releases upstream, so that's n to n-2 versions. If we only package version n, that claim isn't true. I would either prefer to keep building with fedora modules or (my real preference) switch entirely to OBS

**Comment by adelton** [comment]
When you switch entirely to OSB, won't you effectively force removal of Kubernetes from Fedora as well?

**Comment by lsm5** [comment]
> When you switch entirely to OSB, won't you effectively force removal of Kubernetes from Fedora as well?

Going simply by `dnf install kubernetes` on Fedora, it depends on containerd and moby-engine in Fedora. And AFAICT, given that it's a single rpm and not a module, it won't depend on modular content. So kubernetes needs to be included as a module if it's to depend on cri-o module.

**Comment by adelton** [comment]
Ah, you are right, kubernetes in Fedora uses moby-engine. Well, based on https://pagure.io/fesco/issue/2231 and https://bugzilla.redhat.com/show_bug.cgi?id=1817022#c15 I'm not sure how stable that setup is long term.

So I guess if the CRI-O team does not plan to work with the Fedora kubernetes maintainer(s) to switch to cri-o as the default, the fact that cri-o won't be maintained in Fedora would not be a big problem. It would still be a pity though.

**Comment by lsm5** [comment]
> So I guess if the CRI-O team does not plan to work with the Fedora kubernetes maintainer(s) to switch to cri-o as the default, the fact that cri-o won't be maintained in Fedora would not be a big problem. It would still be a pity though.

I privately pinged the most recent fedora maintainer of kubernetes just now. Couldn't find their github. I'll update this issue once I hear from them.

**Comment by ingvagabund** [comment]
I don't think anyone is interesting in k8s in Fedora. Its outdated, only CVE repoted, no user issues. It's more preferable to use kind or kubeadm to spin the cluster. Unless there's a real interesting in running k8s in Fedora, I suggest to orphan kubernetes package as well.

**Comment by dustymabe** [comment]
ping @LorbusChris @vrutkovs - how does OKD get CRIO-O ? does it come from the Fedora builds or somewhere else?

**Comment by vrutkovs** [comment]
We're using CRI-O modules from Fedora

**Comment by dustymabe** [comment]
@vrutkovs maybe we could scale it back and just have one version of cri-o in Fedora (not a module) and have it be the one OKD needs.

**Comment by vrutkovs** [comment]
OKD needs at least two now (1.18 for 4.5 and 1.19 for 4.6). It would be nice to start testing cri-o from master in 4.7 too. That leads to 3 CRI-o version on F32 and at some point on F33. All of the modules also need to be added in bodhi. I think that's too much extra work and the only beneficiary in OKD really

**Comment by afbjorklund** [comment]
> It's more preferable to use kind

Which uses ubuntu, with containerd...

For minikube we have _tried_ to keep things working with fedora/centos and with cri-o, but it has always been difficult it seems.
Normally it is just the lack of user interest, but recently cgroups v2 has been something of a blocker for Kubernetes on Fedora.

But a maintained version from openSUSE is better than an unmaintained version from Fedora, so moving to OBS sounds good.
Once we are over all the current podman v2 problems, we will probably look again at upgrading cri-o. We are using `kubeadm`.

**Comment by vrutkovs** [comment]
>Which uses ubuntu, with containerd...

Not necessarily - default is ubuntu+containerd, but its fairly easy to replace it with crio - https://github.com/vrutkovs/kindest-node-crio

**Comment by Conan-Kudo** [comment]
Pretty much the reason kubernetes hasn't been given any love lately in Fedora is that it's been broken for two Fedora releases due to cgroupv2. With kubernetes 1.19 supporting cgroupv2 with cri-o and the recent launch of the kubedev SIG in Fedora, I think it makes sense to fix the kubernetes package and update crio as a regular package.

**Comment by Conan-Kudo** [comment]
If we wanted to have modular streams of k8s with crio, it would make sense to do so with a specific k8s module rather than a crio one, and have matching k8s and crio versions in the same module for supporting different streams. That said, I do not know if there's any appetite for that model right now for kubernetes users on Fedora (assuming they haven't all been driven away by the breakage...).

**Comment by afbjorklund** [comment]
> Pretty much the reason kubernetes hasn't been given any love lately in Fedora is that it's been broken for two Fedora releases due to cgroupv2.

Ehrm, the cri-o package was broken in Fedora for _months_ even without the decision made to go cgroups v2 ahead of docker (moby-engine) and kubernetes supporting it ? I'm sure you remember the "Invalid character(s) found in prerelease "module_f30"' and the `sed` workarounds for it, so blaming modularity here seems to me to be rather fair in this discussion...

But the most important thing would be that there are simple instructions for users to follow, in order to install a CRI _anywhere_. Maybe it will never be get.docker.com but at least half a dozen lines with some opensuse repository is "portable" enough. It would be nice if `yum install cri-o` worked right-out-of-the-box on fedora/centos, but it seems unlikely to happen ?

https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cri-o

That is from the (kubernetes) user's perspective. I could see why the _distro_ would not want it.

**Comment by Conan-Kudo** [comment]
> Ehrm, the cri-o package was broken in Fedora for months even without the decision made to go cgroups v2 ahead of docker (moby-engine) and kubernetes supporting it ? I'm sure you remember the "Invalid character(s) found in prerelease "module_f30"' and the sed workarounds for it, so blaming modularity here seems to me to be rather fair in this discussion...

The whole _point_ of the modular streams is that you should not need to do pinning beyond the version series. If CRI-O requires pinning beyond that, then something is broken. Admittedly, I would even argue that CRI-O requiring pinning between Kubernetes and CRI-O runtime version numbers is broken, but that ship has sailed.

> But the most important thing would be that there are simple instructions for users to follow, in order to install a CRI anywhere. Maybe it will never be get.docker.com but at least half a dozen lines with some opensuse repository is "portable" enough. It would be nice if `yum install cri-o` worked right-out-of-the-box on fedora/centos, but it seems unlikely to happen ?

There is literally no reason that this couldn't happen.

**Comment by afbjorklund** [comment]
I still think that most Fedora (and RHEL) users are more interested in OpenShift, so I guess serving OKD first makes sense...

As long as it works with reasonable effort, I think that we will continue support cri-o (with podman as the build/load support)

Whether the users chooses the "system" (distribution) or the "vendor" (upstream) packages, is not so important to me.

I know that some distributions, like Debian, take great pride in building reproducible packages from source for everything.

**Comment by LorbusChris** [comment]
Maybe for Fedora, the [Packit Service](https://github.com/packit-service/packit-service) could be set up. It could be configured to auto-build release tags from one release branch to Koji (which branch depending on what's needed for the current OKD release). @haircommander do you think that could work?

**Comment by adelton** [comment]
Is the problem really triggering the builds, or the fact that even if the builds pass and get shipped to updates, they may not be not usable (like https://bugzilla.redhat.com/show_bug.cgi?id=1740730 a.k.a. https://bugzilla.redhat.com/show_bug.cgi?id=1754170) and require fix by the maintainers?

**Comment by lsm5** [comment]
On Sun, Oct 04, 2020 at 05:24:56PM -0700, Christian Glombek wrote:
> Maybe for Fedora, the [Packit Service](https://github.com/packit-service/packit-service) could be set up. It could be configured to auto-build release tags from one release branch to Koji (which branch depending on what's needed for the current OKD release). @haircommander do you think that could work?
> 

Does packit work for fedora modules?

-- 
Lokesh
IRC, GitHub: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by haircommander** [comment]
BTW, I forgot to mention, but on a CRI-O weekly sync call, we decided to not orphan the package.

Given that, I am definitely open to suggestions on how to build it. Packit seems like a great option @LorbusChris, do you have any experience with it (i.e. can I bother you with questions if that's the route we go :smile: )

**Comment by haircommander** [comment]
I reached out to the devs, packit does not support modules right now, and while it's a feature they want, they also have no timeline for adding it

**Comment by LorbusChris** [comment]
Oh yea, my assumption was that cri-o wouldn't be a module, but a simple RPM.
Looks like using packit isn't a viable option just yet then.

**Comment by Conan-Kudo** [comment]
Couldn't you use `tito` to release into dist-git branches?

**Comment by haircommander** [comment]
I have continued packaging fedora manually with modules. I think we can close this for now
