### ISSUE TITLE
Update cri-o.io website Ubuntu/Debian install documentation

### ISSUE THREAD

**Issue by JamesLaverack** [cri-o/cri-o#4214]
The documentation on the [CRI-O website](https://cri-o.io) provides incorrect install instructions for Ubuntu and Debian, prompting users to install the following APT repository:

```
deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x${NAME}_${VERSION_ID}
```

Whereas the latest [repository documentation](https://github.com/cri-o/cri-o/blob/master/install.md#apt-based-operating-systems) instructs the user to install this repository instead:

```
deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/
```

**Comment by saschagrunert** [comment]
cc @lsm5 @dougsland

**Comment by afbjorklund** [comment]
There were some changes to the cri-o packaging, so you might want to check the latest/greatest documentation as well:

https://github.com/cri-o/cri-o/blob/master/install.md#install-packaged-versions-of-cri-o

https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cri-o

**Comment by JamesLaverack** [comment]
Ah, I was following the documentation on https://cri-o.io. I'll update my packages list.

Should I close this as a wontfix? Or convert it into an issue to update the https://cri-o.io website docs?

**Comment by saschagrunert** [comment]
> Ah, I was following the documentation on https://cri-o.io. I'll update my packages list.
> 
> Should I close this as a wontfix? Or convert it into an issue to update the https://cri-o.io website docs?

Yes I think we have to update the website docs. :+1: Feel free to update the issue to match the new requirement. Thank you! :pray:

**Comment by JamesLaverack** [comment]
@saschagrunert I've updated the issue title and description. 👍

**Comment by JamesLaverack** [comment]
Some further investigation shows there is already a pull request against the CRI-O website from August https://github.com/cri-o/cri-o.io/pull/45 It's just not been approved yet.

**Comment by haircommander** [comment]
this should be fixed now!

**Comment by JamesLaverack** [comment]
Looks good to me. I see the updated instructions on https://cri-o.io, so I'd say this is fixed by https://github.com/cri-o/cri-o.io/pull/45.

Thanks all!
