### ISSUE TITLE
Document crio update using package managers

### ISSUE THREAD

**Issue by hafe** [cri-o/cri-o#4227]
**Description**

(As requested in the slack channel) - create documentation how crio should be updated using package managers like yum and apt. Other projects like kubespray would need it.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by haircommander** [comment]
@wgahnagl can you take a stab at this?
