### ISSUE TITLE
fatal error: runtime·unlock: lock count

### ISSUE THREAD

**Issue by nyxi** [cri-o/cri-o#4278]
**Description**
A few days after migrating to cri-o it crashed on one of our nodes. All nodes are logging a lot of these two warnings:

```
unable to retrieve network namespace link eth0: Link not found
unable to get stats for container b6d170426c4803dd8f8478c45821f9f27840e24c4911269a152b1af4033d3a5a: unable to load cgroup at /kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod4b5fcfe7_a146_4006_870a_2ba4c633694f.slice: cgroup deleted" id=b3a64d8d-3287-4222-942c-6d8019f1449c
```

**Steps to reproduce the issue:**
Can't really say, we were running our normal workload with Rook Ceph, multiple Prometheus instances and a few java applications.

**Describe the results you received:**
crio daemon crashed with:

```
fatal error: runtime·unlock: lock count
panic during panic
runtime stack:
goroutine 0 [runtime.throwidle(]:
0x560457766761fatal error: runtime·unlock: lock count
runtime.throwstack trace unavailable
(fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
```

**Describe the results you expected:**
For crio to not crash

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.17.5
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- Virtual machines on Openstack
- OS is Fedora CoreOS 32.20200809.3.0
- Kernel 5.8.10-200.fc32.x86_64
- Kubernetes v1.17.6

**Comment by haircommander** [comment]
can you post the logs leading up to the crash as well?

**Comment by nyxi** [comment]
Sure;
[crio service log](https://github.com/cri-o/cri-o/files/5402878/logs.txt)

**Comment by haircommander** [comment]
can you post the output of `crio config` as well as the contents of `/etc/cni/net.d`? it seems like you're using CRI stats, and not cadvisor stats, and that some configuration of your networking plugins are confusing our CRI stats path

**Comment by haircommander** [comment]
what happens if you restart crio? could you restart crio and attach the full logs if it happens again? specifically, I want to see if it chooses the plugin correctly, and how long it takes for the node to hit this issue again.

this is further confusing because you should be using cadvisor stats, and I've never seen this error before...

**Comment by nyxi** [comment]
I'm hopeful this is something that can be resolved with configuration changes, just need to figure out what is off.

As for your cadvisor stats comment, is this something I should configure somewhere?

[Here is the startup log from crio](https://github.com/cri-o/cri-o/files/5404107/crio-start.txt)

**Comment by haircommander** [comment]
cadvisor stats should be default. The way it's configured is roundabout though. if you `--runtime-endpoint` arg for kubelet is not `/var/run/crio/crio.sock` or `unix:///var/run/crio/crio.sock` then it chooses CRI stats. If it's either of those values, it uses cadvisor stats.

What are the kubelet args you're using?

**Comment by nyxi** [comment]
If you are being literal, ie. you are matching for the full path of the crio socket, then that is probably why it's not using cadvisor stats:

```
/opt/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --eviction-hard=imagefs.available<30% --container-runtime=remote --container-runtime-endpoint=unix:///run/crio/crio.sock --dynamic-config-dir=/var/lib/kubelet/dynamic-config
```

On my OS `/var/run` is a symbolic link to `/run`:

```
$ stat /var/run
  File: /var/run -> ../run
(..)
```

So it would be trivial for me to change this. But is that issue related to the crash at all?

**Comment by haircommander** [comment]
Yeah it's a literal string comparison...

The crash is happening on the CRI stats path. If you switch to cadvisor stats (which we currently recommend because we have some small performance issues), then this won't be an issue.

Though, this is definitely a bug that needs resolving in CRI stats. For now, you can stop it by changing the dir to have /var

**Comment by nyxi** [comment]
Thank you for the prompt help with this issue. I have applied the configuration change to kubelet and it drastically reduced the logspam from crio. Hopefully we won't see this crash again.

> Though, this is definitely a bug that needs resolving in CRI stats

Should I report this issue somewhere else for CRI stats or is it already in the right place?

**Comment by haircommander** [comment]
this is the right place, thanks for the report!
