### ISSUE TITLE
Unable to install or update packages from OpenSUSE Build Service due to expired GPG key

### ISSUE THREAD

**Issue by DanHam** [cri-o/cri-o#4279]
**Description**

A while back I followed the instructions at the [cri-o](https://cri-o.io/) website to add the required APT repositories and associated GPG package signing keys for cri-o (podman, skopeo, etc).

Things had been working fine until recently. 

I now get an error running `apt-get update` due to an expired GPG key.

The expired key affects every package in the OpenSUSE Build Service repository - not just cri-o.

This prevents installation of any packages and/or upgrades.

**Describe the results you received:**

```
$ sudo apt-get update
Hit:1 http://deb.debian.org/debian buster InRelease
...
Get:7 http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10  InRelease [1,623 B]                                                                                                                                
...
Err:7 http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10  InRelease
  The following signatures were invalid: EXPKEYSIG 4D64390375060AA4 devel:kubic OBS Project <devel:kubic@build.opensuse.org>
Fetched 13.1 kB in 2s (6,739 B/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10  InRelease: The following signatures were invalid: EXPKEYSIG 4D64390375060AA4 devel:kubic OBS Project <devel:kubic@build.opensuse.org>
W: Failed to fetch http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/InRelease  The following signatures were invalid: EXPKEYSIG 4D64390375060AA4 devel:kubic OBS Project <devel:kubic@build.opensuse.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by haircommander** [comment]
I would re-do the installation steps here: https://github.com/cri-o/cri-o/blob/master/install.md#apt-based-operating-systems
I believe the second step (adding the gnupg key) will fix your problem

**Comment by afbjorklund** [comment]
You will need to use VERSION=1.19, otherwise you will get the stale keys.

**Comment by DanHam** [comment]
Thanks. That's fixed things.

For anyone else experiencing this issue, the old (expired) key can be deleted with:

```bash
sudo apt-key del '2472 D6D0 D2F6 6AF8 7ABA  8DA3 4D64 3903 7506 0AA4'
```
