### ISSUE TITLE
Setctty set but Ctty not valid in child

### ISSUE THREAD

**Issue by kallisti5** [cri-o/cri-o#4280]
**Description**

Trying to open a TTY to a container...

**Steps to reproduce the issue:**
1. ```kubectl exec -it pod/haproxy-ingress-55544d676-k2pxs -- /bin/sh -l```

**Describe the results you received:**
```error: Internal error occurred: error executing command in container: fork/exec /usr/bin/runc: Setctty set but Ctty not valid in child```

**Output of `crio --version`:**

```
# crio --version
crio version 1.18.3
Version:       1.18.3
GitCommit:     61de18161fb4ccda720768c001713592b5a04e46
GitTreeState:  clean
BuildDate:     2020-10-08T01:53:51Z
GoVersion:     go1.15.0
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical
CentOS 8
Selinux permissive

```
# rpm -qa | egrep "kube|cri"
kubectl-1.19.3-0.x86_64
kubelet-1.19.3-0.x86_64
cri-o-1.18.3-6.6.el8.x86_64
criu-3.12-9.module_el8.2.0+305+5e198a41.x86_64
cri-tools-1.13.0-0.x86_64
kubernetes-cni-0.8.7-0.x86_64
kubeadm-1.19.3-0.x86_64
```

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by kallisti5** [comment]
https://github.com/creack/pty/issues/96 might be related?

**Comment by haircommander** [comment]
@kolyshkin can you PTAL

**Comment by kallisti5** [comment]
Just noticed I was running the 1.18 cri-o repo when 1.19 exists for CentOS 8.  I'm updating and will report back shortly.

**Comment by kallisti5** [comment]
Yup.   Upgrading cri-o from 1.18 to 1.19 fixes it.

```
# kubectl exec -it pod/haproxy-ingress-55544d676-k2pxs -- /bin/sh

/ # uname -a
Linux haproxy-ingress-55544d676-k2pxs 4.18.0-193.19.1.el8_2.x86_64 #1 SMP Mon Sep 14 14:37:00 UTC 2020 x86_64 Linux
/ # exit
```

I'm assuming cri-o used creack/pty < v1.1.9 per the issue above.  cri-o 1.19 moved to v1.1.10+

**Comment by haircommander** [comment]
ah and we merged https://github.com/cri-o/cri-o/pull/4192 in 1.18 but haven't cut a new release yet. 

Glad to hear it's working. We should cut a new 1.18 release soon. Are you comfortable with closing this issue?

**Comment by haircommander** [comment]
Happy to :smile: 

shameless plug while you're here, are you interested in filling out our [user survey](https://www.surveymonkey.com/r/crio-user-poll-2020). We'd love to hear feedback @kallisti5
