### ISSUE TITLE
"layer not known" after powering off VM with CRI-O

### ISSUE THREAD

**Issue by jomeier** [cri-o/cri-o#4285]
Hi,

CRI-O seems to have  a problem if a Host VM is powered off.

On OKD 4.5 (and also on OKD 4.6 nightlies) we get this error very often, if we power off worker VMs:

```
Failed to create pod sandbox: rpc error: code = Unknown desc = error creating pod sandbox with name "k8s_virt-operator-74745fbc9c-xknls_openshift-cnv_6c53d52d-af4b-4bca-800d-4eccc0b0ee64_0": layer not known
```

If we ssh into the worker VM and do a 

```
sudo podman images
```

we get lots of "layer not known" error messages.

```
sudo crictl ps -a
```

does not show any running containers.

The workaround to get that running again is to remove the overlay-images storage directory:

```
rm -rf /var/lib/containers/storage/overlay-images
```

Thanks and greetings,

Josef

**Comment by haircommander** [comment]
curious, does `sudo crictl images` also print the same errors?

**Comment by Dorye123** [comment]
after removing the images. did you restart the server ?

(the same happened to me on a master server)

to answer @haircommander - no, using crictl does not show the error we can see when using "podman images"

**Comment by haircommander** [comment]
also is this an upgrade (specifically a minor version upgrade: 4.5->4.6), or just a normal power cycle

**Comment by Dorye123** [comment]
to me it happened during a normal power cycle.

**Comment by jomeier** [comment]
Same here.

I rebooted my VM with vSphere. Then I ran into this problem again.

**Comment by Dorye123** [comment]
@jomeier , I remove the directory and its content. 

"The workaround to get that running again is to remove the overlay-images storage directory:

rm -rf /var/lib/containers/storage/overlay-images"

after that I stopped kubelet and crio then started crio and kubelet. 

what else did you do to workaround this ? 

for me that did not worked :(

**Comment by jomeier** [comment]
Remove all overlay directories. As a last resort you could also try to delete the storage folder.

Kubernetes should pull all images on this node again after a few minutes.

**Comment by haircommander** [comment]
what happens if you run `crio wipe -f`?

**Comment by haircommander** [comment]
actually, I see the problem

CRI-O is at version 1.18.2. We attempted to make it more performant by not syncing after storage writes. Unfortunately that caused dangling image/metadata problems. We've since reverted that change: https://github.com/cri-o/cri-o/commit/6a7417b47e94c72042e3bcc9f3ee585cb1a4a945 but don't yet have a released version.

I am cutting a 1.18.4, and will work to get it in okd 4.5. okd 4.6 should have cri-o 1.19 soon as well, which will also fix the problem.

thanks for reporting, I didn't realize okd was on such an old version

**Comment by jomeier** [comment]
This are great news! 

If it gets released I‘ll stress test it and if the problem does not occur again, I‘ll close this issue.

**Comment by haircommander** [comment]
sounds good :smile: it may take a bit to get it into 4.5, as they are waiting on kernel fixes to update to 1.18.3, so I don't have a timeline, but I will try to get it all through ASAP

**Comment by jomeier** [comment]
Ah. At least there seems to exist a solution for the problem 😉

**Comment by haircommander** [comment]
this should be fixed now!
