### ISSUE TITLE
cni-loopback getting pilled up in /var/lib/cni/results

### ISSUE THREAD

**Issue by sudheshpn** [cri-o/cri-o#4296]
We are seeing cni-loopback files getting pilled up in /var/lib/cni/results resulting in /var filesystem getting full. Ideally this files should have been deleted once the container is delete from the VM. I tried upgrading the cri version to cri-o-1.17.0-1.0.5.el7.x86_64 and i still see the issue. We ran a sample k8s job which spins up 10 pod on the specified host. Count of the cni file increased to 67 to 77. Job got complete and status of pod now shows as NotReady as expected.  Count of cni-lookback still shows as 77. Now i am deleting the job which should delete the pod from the vm. Pod got deleted the count still shows as 77.

[root@umemsxx results]# crictl version
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.17.0
RuntimeApiVersion:  v1alpha1
[root@umemsxx results]# rpm -qa | grep cri-o
cri-o-1.17.0-1.0.5.el7.x86_64

Kubernetes version: v1.17.6+1.0.2.el7

uname -a
Linux umems805 4.14.35-2018.el7uek.x86_64 #2 SMP Fri May 1 14:35:54 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
 cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.8 (Maipo)

[root@umemsxxx results]# crictl ps -a | wc -l
46
[root@umemsxxx results]# crictl ps  | wc -l
29
[root@umemsxxresults]# ls -ltr | wc -l
8112

df -kh | grep /var/lib/containers | wc -l
63

**Comment by haircommander** [comment]
hey @sudheshpn what CNI plugin/config are you using? I would expect the cleanup to be their responsibility

**Comment by sudheshpn** [comment]
We are using Canal as CNI. Its seems to be similar issue as mentioned in https://github.com/cri-o/cri-o/issues/3581

**Comment by haircommander** [comment]
can you update to at least 1.17.4 to see if it fixes your issue? I see now it is definitely cri-o's responsibility, thanks for the link :smile:

**Comment by kaitaklam** [comment]
is there a way to find out which /var/lib/cni/results/* files are in use and which of them I can manually remove them?

**Comment by haircommander** [comment]
it depends on the plugin, but for the bridge plugin I think the filename is the pod ID, so you may be able to correlate running pods with active files

**Comment by haircommander** [comment]
I think this can be closed
