### ISSUE TITLE
Recent changes causing go modules to be downloaded in CI

### ISSUE THREAD

**Issue by saschagrunert** [cri-o/cri-o#4298]
With the merge of https://github.com/cri-o/cri-o/pull/4208 we're now downloading go modules in CircleCI, which should not happen. For example:
https://app.circleci.com/pipelines/github/cri-o/cri-o/6356/workflows/6223bde7-3cc2-4f16-a201-7ff5923d5ec3/jobs/102326/parallel-runs/0/steps/0-105

Either we remove the vendoring completely or we stick to the vendored sources. The issue seems to be introduced by the removal of the `--mod=vendor` flag.

**Comment by mrunalp** [comment]
@kolyshkin ptal

**Comment by kolyshkin** [comment]
This happens as CI is using golang 1.13 (not supported since August). I mistakenly thought everyone has switched to go 1.14+. With 1.13, `-mod=vendor` is still required.

**Comment by kolyshkin** [comment]
Let me try to fix circleci scripts to have golang. The problem is we use Ubuntu Xenial which is pretty old, and the backports ppa we use (https://launchpad.net/~longsleep/+archive/ubuntu/golang-backports) only has go-1.13 for Xenial.

**Comment by kolyshkin** [comment]
Let's see if this works... https://github.com/cri-o/cri-o/pull/4305

**Comment by saschagrunert** [comment]
> Let me try to fix circleci scripts to have golang. The problem is we use Ubuntu Xenial which is pretty old, and the backports ppa we use (https://launchpad.net/~longsleep/+archive/ubuntu/golang-backports) only has go-1.13 for Xenial.

Ah yeah I see… I think CircleCI also provides some 20.04 images. Let's see if this fixes magically the issue. 
Xref #4306
