### ISSUE TITLE
log version at startup

### ISSUE THREAD

**Issue by hafe** [cri-o/cri-o#4332]
**Description**

It would be nice if crio could output its version at startup for troubleshooting/diagnosis purposes.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
1.19.0
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by saschagrunert** [comment]
Hey @hafe, yes I think it would be good to have the complete `crio version` output logged. Do you want to contribute a PR to achieve that? :)

**Comment by hafe** [comment]
@saschagrunert I could give it a try!

**Comment by saschagrunert** [comment]
> @saschagrunert I could give it a try!

Awesome, feel free to reach out to me if there is anything unclear.

**Comment by hafe** [comment]
Why did not this issue auto close at merge?

**Comment by haircommander** [comment]
it wasn't linked properly it seems!
