### ISSUE TITLE
The package subproject for 1.18.4 is missing on OBS

### ISSUE THREAD

**Issue by afbjorklund** [cri-o/cri-o#4357]
https://github.com/cri-o/cri-o/tree/release-1.18

https://github.com/cri-o/cri-o/releases

* v1.18.4
* v1.18.3
* v1.18.2

https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable

https://build.opensuse.org/project/subprojects/devel:kubic:libcontainers

devel:kubic:libcontainers:stable:cri-o:1.18 | Last release available in 1.18 branch
-- | --
devel:kubic:libcontainers:stable:cri-o:1.18:1.18.0 | Release 1.18.0
devel:kubic:libcontainers:stable:cri-o:1.18:1.18.1 | Release v1.18.1
devel:kubic:libcontainers:stable:cri-o:1.18:1.18.1-2 | Release 1.18.1-2
devel:kubic:libcontainers:stable:cri-o:1.18:1.18.3 | Release 1.18.3
 

So the subproject for 1.18.4 is missing, in case you wanted to pin to a release.

There are packages available for 1.18.4, but only in the main 1.18 channel ?

**Comment by rmohr** [comment]
Does this manifest itself as the following error which we seee now since a feww days?

```
+ export CRIO_OS=CentOS_8_Stream
+ CRIO_OS=CentOS_8_Stream
+ export CRIO_VERSION=1.18
+ CRIO_VERSION=1.18
+ curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8_Stream/devel:kubic:libcontainers:stable.repo
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   380  100   380    0     0    676      0 --:--:-- --:--:-- --:--:--   674
+ curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.18.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.18/CentOS_8_Stream/devel:kubic:libcontainers:stable:cri-o:1.18.repo
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   452  100   452    0     0   1083      0 --:--:-- --:--:-- --:--:--  1083

100   453  100   453    0     0    831      0 --:--:-- --:--:-- --:--:--   831

100   454  100   454    0     0    674      0 --:--:-- --:--:-- --:--:--   674

100   455  100   455    0     0    568      0 --:--:-- --:--:-- --:--:--   568

100   456  100   456    0     0    490      0 --:--:-- --:--:-- --:--:--   490
100   456  100   456    0     0    490      0 --:--:-- --:--:-- --:--:--     0

100   396  100   396    0     0    373      0  0:00:01  0:00:01 --:--:--   373
+ dnf install -y cri-o
Stable Releases of Upstream github.com/containe 0.0  B/s |   0  B     01:01    
Failed to download metadata for repo 'devel_kubic_libcontainers_stable'
Error: Failed to download metadata for repo 'devel_kubic_libcontainers_stable'
```

**Comment by afbjorklund** [comment]
@rmohr : no, you seem to be using the "1.18" channel rather than the "1.18.4" channel ?

Probably more related to build failures: https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable:cri-o:1.18/cri-o

**Comment by haircommander** [comment]
the 1.18 branch is currently building, once i verify the fix for @rmohr's problem works, then I'll branch with 1.18.4.

**Comment by rmohr** [comment]
> the 1.18 branch is currently building, once i verify the fix for @rmohr's problem works, then I'll branch with 1.18.4.

My problem is gone. Thanks.

**Comment by haircommander** [comment]
execellent to hear! @afbjorklund is your problem fixed as well?

**Comment by afbjorklund** [comment]
@haircommander : looks good, I will change the URL back
