### ISSUE TITLE
Yum metadata for CentOS7 seems broken, affects Kubespray CI

### ISSUE THREAD

**Issue by hafe** [cri-o/cri-o#4381]
**Description**

Kubespray CI cannot not install cri-o (1.19) for CentOS7

See e.g. https://gitlab.com/kargo-ci/kubernetes-sigs-kubespray/-/jobs/858600578#L2603

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

yum install errs with "Package does not match intended download"

**Describe the results you expected:**

packages install properly

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Kubespray CI (gitlab)

**Comment by hafe** [comment]
Installing cri-o 1.19 has worked for Kubespray since 26th of October but no longer does. Metadata for cri-o Centos7 was updated 12th of November (still the same version of package)

**Comment by haircommander** [comment]
something seems to be failing. I am taking a look
/assign

**Comment by haircommander** [comment]
should be fixed now! ptal @hafe

**Comment by hafe** [comment]
> should be fixed now! ptal @hafe 

Looks like it did not help

**Comment by haircommander** [comment]
are you able to run `yum clean all` [ref](https://access.redhat.com/discussions/1266213)

**Comment by hafe** [comment]
> are you able to run `yum clean all` [ref](https://access.redhat.com/discussions/1266213)

No, not yet. Looks the CI job will be disabled instead

**Comment by hafe** [comment]
We got around by disabling the yum cache for crio. Something is weird

**Comment by hafe** [comment]
It now happens again despite the disabled yum cache for this repo.

**Comment by haircommander** [comment]
:'( I gotta be honest, I have no idea why that may happen. the build hasn't updated for 1.19 since two weeks ago

**Comment by hafe** [comment]
This time the problem is/was containers-common. It was changed 2 dec at the same time as other rpms.

**Comment by haircommander** [comment]
ah thanks for looking into that. @lsm5 PTAL

**Comment by lsm5** [comment]
I'll bump skopeo on OBS right away.

**Comment by lsm5** [comment]
> I'll bump skopeo on OBS right away.

1.2.0-12 building right now: https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/skopeo

**Comment by lsm5** [comment]
containers-common should be fixed now. Let me know..

**Comment by abhivaidya07** [comment]
Facing issue with installing cri-o on centos 7. There is some issue with 2 rpm files 
1. Container-networking-plugin 
2. Container-common 

Plz look into it i am facing the issue since couple of days !!

**Comment by hafe** [comment]
Fails again
https://gitlab.com/kargo-ci/kubernetes-sigs-kubespray/-/jobs/903748966

**Comment by oomichi** [comment]
Even if operating the official installation of cri-o on CentOS7 as https://cri-o.io by hands, we are facing the same issue like the following:
```
$ export OS=CentOS_7
$ export VERSION=1.19
$ sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/devel:kubic:libcontainers:stable.repo
$ sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/$OS/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo
$
$ sudo yum install cri-o
Loaded plugins: product-id, search-disabled-repos, subscription-manager

This system is not registered with an entitlement server. You can use subscription-manager to register.

devel_kubic_libcontainers_stable                                                                                                                    | 1.3 kB  00:00:00     
devel_kubic_libcontainers_stable_cri-o_1.19                                                                                                         | 1.3 kB  00:00:00     
Resolving Dependencies
--> Running transaction check
---> Package cri-o.x86_64 2:1.19.0-13.2.el7 will be installed
--> Processing Dependency: containernetworking-plugins >= 0.7.5-1 for package: 2:cri-o-1.19.0-13.2.el7.x86_64
--> Processing Dependency: conmon >= 2.0.2-1 for package: 2:cri-o-1.19.0-13.2.el7.x86_64
--> Running transaction check
---> Package conmon.x86_64 2:2.0.21-1.el7 will be installed
---> Package containernetworking-plugins.x86_64 0:0.8.7-1.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===========================================================================================================================================================================
 Package                                     Arch                   Version                              Repository                                                   Size
===========================================================================================================================================================================
Installing:
 cri-o                                       x86_64                 2:1.19.0-13.2.el7                    devel_kubic_libcontainers_stable_cri-o_1.19                  43 M
Installing for dependencies:
 conmon                                      x86_64                 2:2.0.21-1.el7                       devel_kubic_libcontainers_stable                             37 k
 containernetworking-plugins                 x86_64                 0.8.7-1.el7                          devel_kubic_libcontainers_stable                             36 M

Transaction Summary
===========================================================================================================================================================================
Install  1 Package (+2 Dependent packages)

Total size: 78 M
Total download size: 36 M
Installed size: 220 M
Is this ok [y/d/N]: y
Downloading packages:
containernetworking-plugins-0. FAILED                                          =========================================================-] 675 kB/s |  36 MB  00:00:00 ETA 
https://download.opensuse.org/repositories/devel%3A/kubic%3A/libcontainers%3A/stable/CentOS_7/x86_64/containernetworking-plugins-0.8.7-1.el7.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=devel_kubic_libcontainers_stable clean metadata
Trying other mirror.


Error downloading packages:
  containernetworking-plugins-0.8.7-1.el7.x86_64: [Errno 256] No more mirrors to try.
$
```

**Comment by haircommander** [comment]
I have reproduced this, and I have asked my colleague @lsm5 to take a look. he's in charge of the containernetworking-plugins and containers-common repos. I'll have him fix it or give me permission to edit the repos. thanks for the patience folks, sorry for the inconvenience.

**Comment by hafe** [comment]
> I have reproduced this, and I have asked my colleague @lsm5 to take a look. he's in charge of the containernetworking-plugins and containers-common repos. I'll have him fix it or give me permission to edit the repos. thanks for the patience folks, sorry for the inconvenience.

Any idea why this keeps happening?

**Comment by haircommander** [comment]
the repos that cri-o depends on have had flaky build issues. I am not sure why in particular that's happening, unfortunately.

**Comment by haircommander** [comment]
should be fixed now

**Comment by hafe** [comment]
Happens now again...

**Comment by haircommander** [comment]
I think this is fixed now, please reopen if you disagree
