### ISSUE TITLE
"test/ctr: ctr oom" fails sometimes

### ISSUE THREAD

**Issue by kolyshkin** [cri-o/cri-o#4382]
Observed the failure of "ctr oom" int test, which fails like:

```
not ok 54 ctr oom
# (in test file ./ctr.bats, line 662)
#   `[[ "$output" == *"OOMKilled"* ]]' failed
```

(the last such failure happened in integration/rhel CI during userns testing).

Apparently, ContainerStatus returns `Reason:Error` (and exit code of 137 which indicates SIGKILL which is most probably because of OOM) instead of expected `Reason:OOMKilled`.

There are two issues:
1. OOMKilled for whatever reason is not set.
2. the test keeps checking for `OOMKilled` even if it won't get it (as another reason was already set).

Looking into whatever conmon is doing to create "oom" file which cri-o relies upon to set `OOMKilled=true`.

**Comment by kolyshkin** [comment]
from the same logs
> time="2020-11-18 20:54:06.900794213Z" level=info msg="Conmon does not support the --sync option" file="conmonmgr/conmonmgr.go:63"

This indicates conmon version < 2.0.19 (released Jul 15 2020), while current one is 2.0.21 (released Sep 8 2020).

**Comment by kolyshkin** [comment]
`contrib/test/integration/build/conmon.yml` says conmon v2.0.15 is used.

conmon version used for circle-ci was bumped twice since (to 2.0.17 in commit 65fe2c5fb76c06d542eaeeeea845bd76ca365dce, and to 2.0.20 in commit d9ea3921d23ab51b6d4cda41eda6571dce3990e1), but not in Ansible files.

Looking into recent changes in conmon (`v2.0.15..`), nothing seems to fix oom file creation.

**Comment by haircommander** [comment]
actualy, I'm confusing this with https://github.com/cri-o/cri-o/issues/5601, I think we're good here
