### ISSUE TITLE
`manifest unknown` when pulling image from secure registry

### ISSUE THREAD

**Issue by Aykelith** [cri-o/cri-o#4388]
**Description**

I want to use my private secured docker v2 registry, but I get the following error:

> FATA[0000] pulling image failed: rpc error: code = Unknown desc = Error reading manifest latest in registry.mydomain/image: manifest unknown: manifest unknown

( where `registry.mydomain/image` would be the actual image )

I first tried with `podman` and it worked (after I logged in). Then I copied the `auth.json` content created by `podman` to a file and set it as the `--global-auth-file` argument.

**Additional information you deem important (e.g. issue happens only occasionally):**

From a CentOS 7 machine.

**Output of `crio --version`:**

```
crio version 1.18.4
Version:       1.18.4
GitCommit:     aba91e59ec78e3299e443a7364e2cf8909af4606
GitTreeState:  clean
BuildDate:     2020-11-19T18:26:08Z
GoVersion:     go1.15.2
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Comment by umohnani8** [comment]
Hi @Aykelith , are you pulling the image via `crictl` or are you doing so with a pod spec and local cluster?

If via crictl, login to your registry via podman (make sure to do the login command as root). Then unset the `--global-auth-file` flag and it should pick up the credentials from the file that podman saves it to.

If via a pod spec, set the `global_auth_file` value in the `crio.conf` file to the path of the auth.json file that podman saves the credentials to.

Please let me know if these suggestions still fail for you.
