### ISSUE TITLE
Testing kubeadm init with cri-o

### ISSUE THREAD

**Issue by leiw324** [cri-o/cri-o#4393]
Hello,

I am testinf cri-o with kubeadm, but node not found, please help!

CentOS 7

cat /etc/hosts

crio-o01    10.0.10.191
crio-o02    10.0.10.192
crio-o03    10.0.10.193
crio-o04    10.0.10.194
crio-o05    10.0.10.195
crio-o06    10.0.10.196

-------------------------------------

crictl version
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.17.5
RuntimeApiVersion:  v1alpha1

--------------------------------------

kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:15:05Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

--------------------------------------

[root@cri-o01 kubernetes]# cat /etc/default/kubelet
KUBELET_EXTRA_ARGS=--feature-gates="AllAlpha=false,RunAsGroup=true" --container-runtime=remote --cgroup-driver=systemd --container-runtime-endpoint='unix:///var/run/crio/crio.sock' --runtime-request-timeout=5m

--------------------------------------

[root@cri-o01 kubernetes]# kubeadm init --pod-network-cidr=$CIDR
W1128 18:26:50.834401    5811 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
[init] Using Kubernetes version: v1.19.4
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Generating "ca" certificate and key
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [cri-o01 kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 10.0.10.191]
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "front-proxy-ca" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] Generating "etcd/ca" certificate and key
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [cri-o01 localhost] and IPs [10.0.10.191 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [cri-o01 localhost] and IPs [10.0.10.191 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

        Unfortunately, an error has occurred:
                timed out waiting for the condition

        This error is likely caused by:
                - The kubelet is not running
                - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

        If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
                - 'systemctl status kubelet'
                - 'journalctl -xeu kubelet'

        Additionally, a control plane component may have crashed or exited when started by the container runtime.
        To troubleshoot, list all containers using your preferred container runtimes CLI.

        Here is one example how you may list all Kubernetes containers running in cri-o/containerd using crictl:
                - 'crictl --runtime-endpoint /var/run/crio/crio.sock ps -a | grep kube | grep -v pause'
                Once you have found the failing container, you can inspect its logs with:
                - 'crictl --runtime-endpoint /var/run/crio/crio.sock logs CONTAINERID'

error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher

--------------------------------------

[root@cri-o01 kubernetes]# journalctl -xeu kubelet
Nov 28 18:31:01 cri-o01 kubelet[5895]: E1128 18:31:01.883155    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:01 cri-o01 kubelet[5895]: E1128 18:31:01.983408    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:02 cri-o01 kubelet[5895]: E1128 18:31:02.084641    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:02 cri-o01 kubelet[5895]: E1128 18:31:02.109966    5895 remote_runtime.go:113] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = cri-o configured with systemd cgroup manager, but did not receive sli
Nov 28 18:31:02 cri-o01 kubelet[5895]: E1128 18:31:02.110056    5895 kuberuntime_sandbox.go:69] CreatePodSandbox for pod "kube-apiserver-cri-o01_kube-system(722f82a93d48eba65d5416a3cf2dbf47)" failed: rpc error: code = Unknown desc = cri-
Nov 28 18:31:02 cri-o01 kubelet[5895]: E1128 18:31:02.110099    5895 kuberuntime_manager.go:741] createPodSandbox for pod "kube-apiserver-cri-o01_kube-system(722f82a93d48eba65d5416a3cf2dbf47)" failed: rpc error: code = Unknown desc = cri
Nov 28 18:31:02 cri-o01 kubelet[5895]: E1128 18:31:02.110187    5895 pod_workers.go:191] Error syncing pod 722f82a93d48eba65d5416a3cf2dbf47 ("kube-apiserver-cri-o01_kube-system(722f82a93d48eba65d5416a3cf2dbf47)"), skipping: failed to "Cr
Nov 28 18:31:02 cri-o01 kubelet[5895]: E1128 18:31:02.185078    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:02 cri-o01 kubelet[5895]: E1128 18:31:02.285388    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:02 cri-o01 kubelet[5895]: E1128 18:31:02.385779    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:02 cri-o01 kubelet[5895]: E1128 18:31:02.485969    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:02 cri-o01 kubelet[5895]: E1128 18:31:02.586229    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:02 cri-o01 kubelet[5895]: E1128 18:31:02.686494    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:02 cri-o01 kubelet[5895]: E1128 18:31:02.786756    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:02 cri-o01 kubelet[5895]: E1128 18:31:02.887005    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:02 cri-o01 kubelet[5895]: E1128 18:31:02.987316    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:03 cri-o01 kubelet[5895]: E1128 18:31:03.087552    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:03 cri-o01 kubelet[5895]: E1128 18:31:03.187801    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:03 cri-o01 kubelet[5895]: E1128 18:31:03.288006    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:03 cri-o01 kubelet[5895]: E1128 18:31:03.388318    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:03 cri-o01 kubelet[5895]: E1128 18:31:03.488657    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:03 cri-o01 kubelet[5895]: E1128 18:31:03.588955    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:03 cri-o01 kubelet[5895]: E1128 18:31:03.689263    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:03 cri-o01 kubelet[5895]: E1128 18:31:03.789496    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:03 cri-o01 kubelet[5895]: E1128 18:31:03.889733    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:03 cri-o01 kubelet[5895]: E1128 18:31:03.990010    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:04 cri-o01 kubelet[5895]: E1128 18:31:04.090273    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:04 cri-o01 kubelet[5895]: E1128 18:31:04.190426    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:04 cri-o01 kubelet[5895]: E1128 18:31:04.231664    5895 event.go:273] Unable to write event: 'Post "https://10.0.10.191:6443/api/v1/namespaces/default/events": dial tcp 10.0.10.191:6443: connect: connection refused' (may ret
Nov 28 18:31:04 cri-o01 kubelet[5895]: E1128 18:31:04.290784    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:04 cri-o01 kubelet[5895]: E1128 18:31:04.391151    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:04 cri-o01 kubelet[5895]: E1128 18:31:04.491510    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:04 cri-o01 kubelet[5895]: E1128 18:31:04.591780    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:04 cri-o01 kubelet[5895]: E1128 18:31:04.692104    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:04 cri-o01 kubelet[5895]: E1128 18:31:04.792404    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:04 cri-o01 kubelet[5895]: E1128 18:31:04.892663    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:04 cri-o01 kubelet[5895]: E1128 18:31:04.992974    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:05 cri-o01 kubelet[5895]: E1128 18:31:05.053685    5895 reflector.go:127] k8s.io/kubernetes/pkg/kubelet/kubelet.go:438: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://10.0.10.191:6443/api/v1/nodes?fieldSelec
Nov 28 18:31:05 cri-o01 kubelet[5895]: E1128 18:31:05.093375    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:05 cri-o01 kubelet[5895]: E1128 18:31:05.193643    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:05 cri-o01 kubelet[5895]: E1128 18:31:05.293959    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:05 cri-o01 kubelet[5895]: E1128 18:31:05.394242    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:05 cri-o01 kubelet[5895]: E1128 18:31:05.494462    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:05 cri-o01 kubelet[5895]: E1128 18:31:05.594657    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:05 cri-o01 kubelet[5895]: E1128 18:31:05.694935    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:05 cri-o01 kubelet[5895]: E1128 18:31:05.795524    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:05 cri-o01 kubelet[5895]: E1128 18:31:05.895929    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:05 cri-o01 kubelet[5895]: E1128 18:31:05.996225    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:06 cri-o01 kubelet[5895]: E1128 18:31:06.096407    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:06 cri-o01 kubelet[5895]: E1128 18:31:06.126507    5895 remote_runtime.go:113] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = cri-o configured with systemd cgroup manager, but did not receive sli
Nov 28 18:31:06 cri-o01 kubelet[5895]: E1128 18:31:06.126659    5895 kuberuntime_sandbox.go:69] CreatePodSandbox for pod "kube-controller-manager-cri-o01_kube-system(1dc3dd91ec9aacaa7cb533065e67cc99)" failed: rpc error: code = Unknown de
Nov 28 18:31:06 cri-o01 kubelet[5895]: E1128 18:31:06.126717    5895 kuberuntime_manager.go:741] createPodSandbox for pod "kube-controller-manager-cri-o01_kube-system(1dc3dd91ec9aacaa7cb533065e67cc99)" failed: rpc error: code = Unknown d
Nov 28 18:31:06 cri-o01 kubelet[5895]: E1128 18:31:06.126891    5895 pod_workers.go:191] Error syncing pod 1dc3dd91ec9aacaa7cb533065e67cc99 ("kube-controller-manager-cri-o01_kube-system(1dc3dd91ec9aacaa7cb533065e67cc99)"), skipping: fail
Nov 28 18:31:06 cri-o01 kubelet[5895]: E1128 18:31:06.196630    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:06 cri-o01 kubelet[5895]: E1128 18:31:06.296778    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:06 cri-o01 kubelet[5895]: E1128 18:31:06.396988    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:06 cri-o01 kubelet[5895]: E1128 18:31:06.497262    5895 kubelet.go:2183] node "cri-o01" not found
Nov 28 18:31:06 cri-o01 kubelet[5895]: E1128 18:31:06.597413    5895 kubelet.go:2183] node "cri-o01" not found

**Comment by leiw324** [comment]
Now I cant start the kubelet:

![image](https://user-images.githubusercontent.com/33790160/100621074-2671d680-335a-11eb-9ba3-4fe79ef28fca.png)

**Comment by haircommander** [comment]
it looks like kubeadm doesn't correctly set systemd cgroup driver. Did you follow instructions [here](https://github.com/cri-o/cri-o/blob/master/tutorials/kubeadm.md#configuring-kubelet) to set the cgroup driver and other kubelet flags?

**Comment by leiw324** [comment]
Hello,

I followed your guideline to add below content to /etc/default/kubelet
KUBELET_EXTRA_ARGS=--feature-gates="AllAlpha=false,RunAsGroup=true" --container-runtime=remote --cgroup-driver=systemd --container-runtime-endpoint='unix:///var/run/crio/crio.sock' --runtime-request-timeout=5m

I have 100-crio-bridge.conf already in /etc/cni/net.d/
![image](https://user-images.githubusercontent.com/33790160/100758928-05c58180-342b-11eb-8121-ee34002be2fd.png)

I created /var/lib/kubelet/config.yaml and added the following content
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd

When I run kubeadm config images list --image-repository user.private.repo --kubernetes-version=v1.19.4
![image](https://user-images.githubusercontent.com/33790160/100759176-491ff000-342b-11eb-83c9-e86facfcc7ad.png)

Please help.

**Comment by haircommander** [comment]
it looks like the kubelet isn't picking up the extra configuration (still trying to use docker). It seems the documentation for kubeadm has updated slightly, and now rpm based systems put the file in /etc/sysconfig/kubelet instead of /etc/default/kubelet
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/

maybe that will help?

**Comment by leiw324** [comment]
Hello,

I used Yum to install, do you mean I copy the following content to /etc/systemd/system/kubelet.service.d/10-kubeadm.conf ?

[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf
--kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml"
# This is a file that "kubeadm init" and "kubeadm join" generate at runtime, populating
the KUBELET_KUBEADM_ARGS variable dynamically
EnvironmentFile=-/var/lib/kubelet/kubeadm-flags.env
# This is a file that the user can use for overrides of the kubelet args as a last resort. Preferably,
# the user should use the .NodeRegistration.KubeletExtraArgs object in the configuration files instead.
# KUBELET_EXTRA_ARGS should be sourced from this file.
EnvironmentFile=-/etc/default/kubelet
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS

**Comment by leiw324** [comment]
Can someone help?

**Comment by haircommander** [comment]
what happens when you set the KUBELET_CONFIG_ARGS maually in the service file to the contents of the link I posted above

**Comment by leiw324** [comment]
Hello,

I don't know how to add, can you guide me?

Thanks

**Comment by haircommander** [comment]
what are the contents of the generated `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf`

**Comment by leiw324** [comment]
Hello,

I did the following, but no luck..

[root@cri-o01 kubelet.service.d]# cat /etc/default/kubelet
KUBELET_EXTRA_ARGS=--feature-gates="AllAlpha=false,RunAsGroup=true" --container-runtime=remote --cgroup-driver=systemd --container-runtime-endpoint='unix:///var/run/crio/crio.sock' --runtime-request-timeout=5m

mkdir /etc/systemd/system/kubelet.service.d

[root@cri-o01 kubelet.service.d]# cat 10-kubeadm.conf
[Unit]
Description=kubelet: The Kubernetes Node Agent
Documentation=https://kubernetes.io/docs/
Wants=network-online.target
After=network-online.target

#[Service]
#ExecStart=/usr/bin/kubelet
#Restart=always
#StartLimitInterval=0
#RestartSec=10

[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf
--kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml"
# This is a file that "kubeadm init" and "kubeadm join" generate at runtime, populating
the KUBELET_KUBEADM_ARGS variable dynamically
EnvironmentFile=-/var/lib/kubelet/kubeadm-flags.env
# This is a file that the user can use for overrides of the kubelet args as a last resort. Preferably,
# the user should use the .NodeRegistration.KubeletExtraArgs object in the configuration files instead.
# KUBELET_EXTRA_ARGS should be sourced from this file.
EnvironmentFile=-/etc/default/kubelet
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS

[Install]
WantedBy=multi-user.target

-----------------------------------------

cir-o working:
![image](https://user-images.githubusercontent.com/33790160/101026056-6252a900-35b1-11eb-9cb2-52d5ba3d031d.png)

**Comment by haircommander** [comment]
can you put 
```
KUBELET_EXTRA_ARGS=--feature-gates="AllAlpha=false,RunAsGroup=true" --container-runtime=remote --cgroup-driver=systemd --container-runtime-endpoint='unix:///var/run/crio/crio.sock' --runtime-request-timeout=5m
```

in /var/lib/kubelet/kubeadm-flags.env
and restart the kubelet service

**Comment by haircommander** [comment]
oh wait that may not make sense. though it's worth a shot...

**Comment by haircommander** [comment]
can you try running this script:
```
#!/bin/bash                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                              
set -euo pipefail                                                                                                                                                                                                                             
                                                                                                                                                                                                                                              
outfile="${1-/tmp/kubeadm.yaml}"                                                                                                                                                                                                              
echo "Printing to $outfile"                                                                                                                                                                                                                   
                                                                                                                                                                                                                                              
if [ -d "$outfile" ]; then                                                                                                                                                                                                                    
    echo "$outfile is a directory!"                                                                                                                                                                                                           
    exit 1                                                                                                                                                                                                                                    
fi                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                              
if [ ! -d $(dirname "$outfile") ]; then                                                                                                                                                                                                       
    echo "please create directory $(dirname $outfile)"                                                                                                                                                                                        
    exit 1                                                                                                                                                                                                                                    
fi                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                              
if [ ! $(which yq) ]; then                                                                                                                                                                                                                    
    echo "please install yq"                                                                                                                                                                                                                  
    exit 1                                                                                                                                                                                                                                    
fi                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                              
if [ ! $(which kubeadm) ]; then                                                                                                                                                                                                               
    echo "please install kubeadm"                                                                                                                                                                                                             
    exit 1                                                                                                                                                                                                                                    
fi                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                              
kubeadm config print init-defaults --component-configs=KubeletConfiguration > "$outfile"                                                                                                                                                      
yq w -i "$outfile" nodeRegistration.criSocket unix:///var/run/crio/crio.sock                                                                                                                                                                  
yq w -i --doc 2 "$outfile" cgroupDriver systemd
```
and then running `kubeadm init --config /tmp/kubeadm.yaml`

(you'll need [yq](https://github.com/mikefarah/yq) installed too)

**Comment by haircommander** [comment]
I also needed `yq w -i "$outfile" localAPIEndpoint.advertiseAddress 0.0.0.0`

**Comment by leiw324** [comment]
Hello,

I followed this guideline: https://medium.com/@raghwendrasingh1819/diy-kubernetes-cluster-with-cri-o-container-runtime-ubuntu-xenial-53e967c33dd9

Just changed 👍 ![image](https://user-images.githubusercontent.com/33790160/101061299-4fe56900-35cb-11eb-9808-9eba475b5c42.png)

And then run Step 4 and Step 5 to install flannel:

Now I can run cri-o:
![image](https://user-images.githubusercontent.com/33790160/101061437-773c3600-35cb-11eb-95a6-0a1fab6de00d.png)
![image](https://user-images.githubusercontent.com/33790160/101061457-7c00ea00-35cb-11eb-99dc-3062207f621b.png)
![image](https://user-images.githubusercontent.com/33790160/101061471-7f947100-35cb-11eb-8092-66ca222149f8.png)
![image](https://user-images.githubusercontent.com/33790160/101061480-84592500-35cb-11eb-9844-5f273f7bb17d.png)

But when I join --control-plane I have following error:
kubeadm join 10.0.10.191:443 --token ypb5ay.g4tluzrqp87vd8wh --discovery-token-ca-cert-hash sha256:dca27e696e17b7be9329dd442eaf506b166585d200333d7d4b26ff0738574663 --control-plane --certificate-key 40cb25c108b86bee7fb3ee00d70c4feaa53ab8d6b794881883f48e41ea603dc5
![image](https://user-images.githubusercontent.com/33790160/101061783-d732dc80-35cb-11eb-91a2-4f72b2ad108a.png)

Please help

**Comment by haircommander** [comment]
looks like this: https://stackoverflow.com/questions/55867216/adding-master-to-kubernetes-cluster-cluster-doesnt-have-a-stable-controlplanee
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/#steps-for-the-first-control-plane-node

**Comment by leiw324** [comment]
I just join worker with no problem:

kubeadm join 10.0.10.191:443 --token ypb5ay.g4tluzrqp87vd8wh \
    --discovery-token-ca-cert-hash sha256:dca27e696e17b7be9329dd442eaf506b166585d200333d7d4b26ff0738574663

![image](https://user-images.githubusercontent.com/33790160/101065024-9d63d500-35cf-11eb-870b-2d71169501ff.png)

I will try to join master node and read you suggestioin link tmr, good night

**Comment by leiw324** [comment]
This commnad not working when init Master 01

kubeadm init --pod-network-cidr 10.244.0.0/16 --apiserver-advertise-address 10.0.10.191 --cri-socket=unix:///var/run/crio/crio.sock --apiserver-bind-port=443 --control-plane-endpoint '10.0.10.191:6443' --upload-certs

**Comment by leiw324** [comment]
I used the following command can init Master 01:

kubeadm init --pod-network-cidr 10.244.0.0/16 --cri-socket=unix:///var/run/crio/crio.sock --control-plane-endpoint '10.0.10.191:6443' --upload-certs 

But when I kubectl get node with the following error:

The connection to the server 10.0.10.191:443 was refused - did you specify the right host or port?

**Comment by haircommander** [comment]
is this a local installation or on some cloud?

**Comment by leiw324** [comment]
I am using KVM for testing.

**Comment by leiw324** [comment]
I successfully create cluster !

**Comment by haircommander** [comment]
that's awesome to hear! what did you change?

**Comment by haircommander** [comment]
Since you found the issue, I'm going to close this. please reopen if you disagree @leiw324
