### ISSUE TITLE
completions job is failing

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#4415]
https://github.com/cri-o/cri-o/pull/4409 changed the function names of the completions, but didn't update the script that generated the completions. I should have reviewed more thoroughly, and we should have checked the pipeline results. oops :smile: 

We need to update `internal/criocli/completions.go` to be able to handle two different set of names (and the other small nits in that PR)

success criteria is a clean tree when `make completions` is run

**Comment by haircommander** [comment]
@grammy-jiang any interest in taking this?

**Comment by kolyshkin** [comment]
I have opened a PR to move completions validation to github actions, so it will be failing instantly (rather than after the PR is merged). https://github.com/cri-o/cri-o/pull/4423

**Comment by grammy-jiang** [comment]
Hi, @haircommander,

It seems my last commit is covered by this commit:

* [drop support for ManageNSLifecycle · cri-o/cri-o@1633196](https://github.com/cri-o/cri-o/commit/1633196c14b2cc8160c588ea64ee3d718bfe9399)

Although I am not a Golang programmer, I would like to have a try. Also, the link [cri-o/completion.go at master · cri-o/cri-o](https://github.com/cri-o/cri-o/blob/master/internal/criocli/completion.go) seems only for the command `crio`, which one is for `crio-status`?

**Comment by haircommander** [comment]
hey @grammy-jiang ! yeah we had to overwrite the changes. We'd love for you to help out!

the tricky part is that code section is for both crio and crio-status.

you can see [here](https://github.com/cri-o/cri-o/blob/6ee8d68771c24a045aef1f5372eae377928a3530/cmd/crio-status/main.go#L42) that  crio-status inherets the DefaultCommands [here](https://github.com/cri-o/cri-o/blob/6ee8d68771c24a045aef1f5372eae377928a3530/internal/criocli/criocli.go#L19), which includes completion().

I think the change would simply involve changing the static slice to a function: `DefaultCommands(binaryName string)` and pass the binary name to the completions function like `completions(binaryName string)` and then use that binaryName when setting up the completions.

I am going to assign this issue to you, please feel free to reach out with any questions, and thanks for the help :smile:

**Comment by haircommander** [comment]
I think this is fixed
