### ISSUE TITLE
Log Message Max Size

### ISSUE THREAD

**Issue by jvincze84** [cri-o/cri-o#4432]
**Description**

We have OKD4.6 cluster installed, and seems cri-o has a limitation on log message size.
Message larger than 8192 bytes (8k) are spitted, and stored separately in a new line. 
These messages are flagged with P(artial) and (F)ull tag. However no logs are lost, but for example it is not possible to parse a long json message. 
Related Fluentd issue: [https://github.com/fluent/fluent-bit/issues/821](https://github.com/fluent/fluent-bit/issues/821)
Documentation we found: [https://stupefied-goodall-e282f7.netlify.app/contributors/design-proposals/node/kubelet-cri-logging/](https://stupefied-goodall-e282f7.netlify.app/contributors/design-proposals/node/kubelet-cri-logging/)

Is there any option to increase this limit? Or any solution to join theses messages?
We are sending the logs with fluentd to Graylog via Gelf, but because of this limitation we cannot parse json logs larger than 8192 bytes.

**Steps to reproduce the issue:**
I think all cri-o installations have this limit.

**Describe the results you received:**
We experience the same as described in the mentioned documentation:
```
2016-10-06T00:17:09.669794202Z stdout F The content of the log entry 1
2016-10-06T00:17:09.669794202Z stdout P First line of log entry 2
2016-10-06T00:17:09.669794202Z stdout P Second line of the log entry 2
2016-10-06T00:17:10.113242941Z stderr F Last line of the log entry 2
```

**Describe the results you expected:**
We would like to increase the size of the log message.

**Output of `crio --version`:**
```
crio version 1.19.0
Version:       1.19.0
GitCommit:     99c925bebdd9e392f2d575e25f2e6a1082e6c232
GitTreeState:  clean
BuildDate:     2020-11-10T19:23:50Z
GoVersion:     go1.14.10
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
The OKD cluster is running on VSphere. 
Cluster version: `Cluster version is 4.6.0-0.okd-2020-11-27-200126`

**Comment by haircommander** [comment]
hm weird, it's configured with the `log_size_max` field in the crio configuration, but we default to unlimited log size (-1). what is the value of that field when you run `crio config` on a node

**Comment by jvincze84** [comment]
@haircommander 
Thank you for your answer. 
As I understand the `log_size_max` is for configuring the container log file size, not for the message size.
```
# Maximum sized allowed for the container log file. Negative numbers indicate
# that no size limit is imposed. If it is positive, it must be >= 8192 to
# match/exceed conmon's read buffer. The file is truncated and re-opened so the
# limit is never exceeded.
```
Our case is not about file size, but the individual log entry size.
Br,
Janos Vincze

**Comment by haircommander** [comment]
ah, oops, I didn't read precisely enough :laughing: 

so the short answer is: we don't have a knob to change this behavior at runtime

we do, however have a way to change it, though it's not going to be trivial on OKD.

what needs to happen is you need to change

**Comment by dbluxo** [comment]
@haircommander does the buffersize limit of 8192 bytes per logline apply? Or does it also apply to all loglines with the same timestamp? We see the following behavior on our systems:

```
2022-05-17T15:36:16.021568025+00:00 stdout F log line with 1382 bytes
2022-05-17T15:36:16.021568025+00:00 stdout F log line with 2381 bytes
2022-05-17T15:36:16.021568025+00:00 stdout F log line with 2655 bytes 
2022-05-17T15:36:16.021568025+00:00 stdout F log line with 1633 bytes
2022-05-17T15:36:16.021568025+00:00 stdout P log line with 141 bytes
2022-05-17T15:36:16.021645139+00:00 stdout F log line with 2012 bytes
```

The second last log line was splitted, although it would have a total of only 2153 bytes (141+2012).
However, the sum of the first five log lines reaches the limit of 8192 bytes, so it is split.

**Comment by haircommander** [comment]
Interesting, I would expect the buffer to be reset after each newline, so it should only be calculated per buffer, not the total timestamp

**Comment by dbluxo** [comment]
Do you have a hint where in the code the buffer is reset?

**Comment by haircommander** [comment]
I was wrong actually, this is expected behavior. Basically, conmon reads the container's logs in 8192 byte sized buffers. AT the end of that buffer, if there's no EOF or newline, whatever remains is logged and deemed "partial"

**Comment by mrunalp** [comment]
I don't think we need any changes to the buffer size right now. The log parsers can implement joining the logs using the P and F annotations.
