### ISSUE TITLE
CANNOT INSTALL PER DOCS on Ubuntu 20.04

### ISSUE THREAD

**Issue by icpenguins** [cri-o/cri-o#4436]
I followed the mess around this issue.

https://github.com/cri-o/cri-o/issues/3844

https://github.com/kubernetes/website/pull/23000

Then the directions.

https://github.com/cri-o/cri-o/blame/master/install.md#L103

The installation does not work when following the directions as specified.

```shell
...@...:~$ sudo apt update
Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]

Get:3 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
Get:4 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  InRelease [1634 B]
Get:5 http://us.archive.ubuntu.com/ubuntu focal-security InRelease [109 kB]
Get:6 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [699 kB]
Get:7 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  Packages [13.0 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 c-n-f Metadata [11.3 kB]
Get:9 http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [705 kB]
Get:10 http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 c-n-f Metadata [13.7 kB]
Get:11 http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.20/xUbuntu_20.04  InRelease [1623 B]
Get:12 http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.20/xUbuntu_20.04  Packages [2986 B]
Fetched 1772 kB in 2s (763 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
...@...:~$ sudo apt install cri-o cri-o-runc
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package cri-o
```

Now that there has been an announcement from Kubernetes that Docker is gone, it would be nice to have this process simplified.

**Comment by Exagone313** [comment]
I can confirm the repository doesn't contains CRI-O 1.20.

However, it contains CRI-O 1.19.

**Comment by haircommander** [comment]
I'm in the midst of packaging 1.20, sorry for the delay!

**Comment by haircommander** [comment]
ubuntu 20.04 should be working, PTAL @icpenguins @Exagone313

**Comment by icpenguins** [comment]
@haircommander I appreciate the update and it appears to be working. I'll be working with it some more today.

```shell
...@...:~$ apt-cache search cri-
ruby-cri-doc - library for building easy-to-use commandline tools - documentation
cri-o-1.15 - OCI-based implementation of Kubernetes Container Runtime Interface.
cri-o-1.16 - OCI-based implementation of Kubernetes Container Runtime Interface.
cri-o-1.17 - OCI-based implementation of Kubernetes Container Runtime Interface.
cri-o-runc - Open Container Project - runtime
cri-tools - A command line tool used for creating OCI images.
cri-o - OCI-based implementation of Kubernetes Container Runtime Interface.
```

Is there a reason it can't be delivered through the normal methods so that we don't have to change the version every time but rather can specify the version we need when updating the systems?

My overall confusion came because I was able to see the release posted to the SUSE site but that the `install` would not work.

**Comment by haircommander** [comment]
It's a developer time problem. I have been volunteering to package for distros, but it's only part of the responsibilities I hold for the project. OBS is easiest because it's relatively simple to package for all required distros for all required CRI-O versions (we support three versions concurrently, so that's like 20-30 version/distro combos).

Sorry for the confusion, I had started to package it and then got distracted. You can see if the builds are succeeding by checking the sidebar on https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable:cri-o:1.20/cri-o

If your distro has the `succeeded` string underneath, then it *should* work to install

**Comment by icpenguins** [comment]
@haircommander yup, time is a killer. I bring up the point because the downstream impact to the thousands of admins that will likely be coming this way will be something to think about.

Thanks for these details! They are helpful.

**Comment by haircommander** [comment]
Thanks for trying out CRI-O, I'm happy to help with anything you need when using it :)

**Comment by Exagone313** [comment]
@haircommander Thanks for your fast support.

Is there a way this task could be automated in the future? This would prevent having new users complaining for a missing package on each new major release :smile:

**Comment by haircommander** [comment]
I would consider that task tech debt. it's been a plan of ours, but there are enough steps that it's proven easier to do it manually every couple of months rather than spend a couple of weeks working on properly automating it.

Every time I do it, I attempt to automate another part of it, though. It is a dream of mine to have it all just happen

**Comment by icpenguins** [comment]
@haircommander one last thing, could you point me in the direction to resolve this issue? I did a full image reinstall and followed the K8S instructions for installing CRI-O, but `kubelet` is not happy.

```shell
...@...:~$ sudo kubelet
I1216 12:33:39.737228   18430 server.go:416] Version: v1.20.0
W1216 12:33:39.737498   18430 server.go:558] standalone mode, no API client
W1216 12:33:39.737582   18430 server.go:614] failed to get the kubelet's cgroup: cpu and memory cgroup hierarchy not unified.  cpu: /, memory: /user.slice/user-1000.slice/session-1.scope.  Kubelet system container metrics may be missing.
W1216 12:33:44.759050   18430 server.go:473] No api server defined - no events will be sent to API server.
I1216 12:33:44.759106   18430 server.go:645] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
I1216 12:33:44.759920   18430 container_manager_linux.go:274] container manager verified user specified cgroup-root exists: []
I1216 12:33:44.759954   18430 container_manager_linux.go:279] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:docker CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:cgroupfs KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: ReservedSystemCPUs: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[{Signal:memory.available Operator:LessThan Value:{Quantity:100Mi Percentage:0} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.1} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.inodesFree Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>} {Signal:imagefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.15} GracePeriod:0s MinReclaim:<nil>}]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalTopologyManagerScope:container ExperimentalCPUManagerReconcilePeriod:10s ExperimentalPodPidsLimit:-1 EnforceCPULimits:true CPUCFSQuotaPeriod:100ms ExperimentalTopologyManagerPolicy:none}
I1216 12:33:44.760129   18430 topology_manager.go:120] [topologymanager] Creating topology manager with none policy per container scope
I1216 12:33:44.760153   18430 container_manager_linux.go:310] [topologymanager] Initializing Topology Manager with none policy and container-level scope
I1216 12:33:44.760171   18430 container_manager_linux.go:315] Creating device plugin manager: true
W1216 12:33:44.760300   18430 kubelet.go:297] Using dockershim is deprecated, please consider using a full-fledged CRI implementation
I1216 12:33:44.760345   18430 client.go:77] Connecting to docker on unix:///var/run/docker.sock
I1216 12:33:44.760380   18430 client.go:94] Start docker client with request timeout=2m0s
F1216 12:33:44.760817   18430 server.go:269] failed to run Kubelet: failed to get docker version: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by haircommander** [comment]
what flags have you passed to the kubelet? it should have `--container-runtime=remote --cgroup-driver=systemd --container-runtime-endpoint='unix:///var/run/crio/crio.sock'`

**Comment by icpenguins** [comment]
@haircommander according to Kubernetes, setting anything in these arguments is deprecated and should be done in the `config.yaml` file. That said, I made the changes and it seems to be working.

Here is the output I had.

```shell
...@...:~$ sudo cat /var/lib/kubelet/kubeadm-flags.env
KUBELET_KUBEADM_ARGS="--container-runtime=remote --container-runtime-endpoint=/var/run/crio/crio.sock"
```

Here is what I changed it to from above.

```shell
...@...:~$ sudo cat /var/lib/kubelet/kubeadm-flags.env
KUBELET_KUBEADM_ARGS="--container-runtime=remote --container-runtime-endpoint='unix:///var/run/crio/crio.sock' --cgroup-driver=systemd"
```

**Comment by haircommander** [comment]
interesting I'd have expected it to work with what you had before.

as a side note, I am updating the docs to use the kubelet config file (for kubeadm deployments at least) https://github.com/cri-o/cri-o/pull/4440

**Comment by icpenguins** [comment]
@haircommander thank you so much! I really do appreciate your timely responses and support. Apologies if I came off harsh, it had been a couple of hours wrestling with this issue.

A couple of things you might want to update in your documentation.

https://github.com/cri-o/cri-o/blame/master/install.md#L105 states `http` instead of `https` so someone might do a copy paste and leave it that way

After doing the `apt install ...` Kubernetes recommends putting a hold on their packages. The following does that.

```shell
sudo apt-mark hold cri-o cri-o-runc kubeadm kubelet kubectl
```

And the other thing that is a good thing to do, unless I'm missing something?

```shell
# Enable CRI-O
sudo systemctl enable cri-o

sudo systemctl daemon-reload
sudo systemctl restart cri-o
sudo systemctl status cri-o
```

**Comment by Exagone313** [comment]
I'd rather do:
```
sudo systemctl daemon-reload
sudo systemctl enable --now crio
```
(`enable --now` equals to `enable` + `start`)

**Comment by haircommander** [comment]
We welcome any PRs for additions to the documentation :smiley:
