### ISSUE TITLE
Found multiple CRI sockets, please use --cri-socket to select one: /var/run/dockershim.sock, /var/run/crio/crio.sock

### ISSUE THREAD

**Issue by ps9802** [cri-o/cri-o#4445]
Hi Team,
While add nodes to master , when i enter token to join on worker node , i am getting below error.

Found multiple CRI sockets, please use --cri-socket to select one: /var/run/dockershim.sock, /var/run/crio/crio.sock

suggest me on this.

**Comment by haircommander** [comment]
my first suggestion would be to stop docker while running cri-o. if you need docker running, you can pass `--cri-socket=/var/run/crio/crio.sock` to the kubelet args (or set criSocket in the kubelet configuration yaml)

**Comment by haircommander** [comment]
I think this can be closed. please reopen if you disagree
