### ISSUE TITLE
Static release bundle for v1.20.0 is missing

### ISSUE THREAD

**Issue by amcinnes** [cri-o/cri-o#4452]
At https://github.com/cri-o/cri-o/releases/tag/v1.20.0 it says
```
Download the static release bundle via our Google Cloud Bucket:
crio-d388528db.tar.gz
```

It links to https://storage.googleapis.com/k8s-conform-cri-o/artifacts/crio-d388528db.tar.gz which returns a 404.

**Comment by amcinnes** [comment]
I found http://storage.googleapis.com/k8s-conform-cri-o/artifacts/crio-v1.20.0.tar.gz ; perhaps that was the intended URL?

**Comment by haircommander** [comment]
you are correct, I slightly messed up the release procedure. I have updated the release page!

**Comment by haircommander** [comment]
thanks for catching this @amcinnes
