### ISSUE TITLE
Failed to create existing container

### ISSUE THREAD

**Issue by nyxi** [cri-o/cri-o#4465]
**Description**

I had a look at the similar issue in https://github.com/cri-o/cri-o/issues/3259 but there didn't seem to be any clear conclusion there?

Kubelet is consistently logging a lot of errors like:

```
E0111 08:32:10.713214 1965321 manager.go:1123] Failed to create existing container: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod6212df55_f00e_4c6a_ae35_c7f202889f55.slice/crio-500d6719132d2a1397acacaf2e1192dd543a0d6c6316315020e7f569143202fe.scope: Error finding container 500d6719132d2a1397acacaf2e1192dd543a0d6c6316315020e7f569143202fe: Status 404 returned error &{%!s(*http.body=&{0xc0012878c0 <nil> <nil> false false {0 0} false false false <nil>}) {%!s(int32=0) %!s(uint32=0)} %!s(bool=false) <nil> %!s(func(error) error=0x772000) %!s(func() error=0x771f80)}
```

The error messages seems to go away after reboot (not sure if forever or if these errors start cropping up over time). I would like to understand what is the cause so I don't repeat any mistakes when setting up new servers in the future.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.19.0
Version:       1.19.0
GitCommit:     99c925bebdd9e392f2d575e25f2e6a1082e6c232
GitTreeState:  clean
BuildDate:     2020-11-19T15:24:08Z
GoVersion:     go1.15.2
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora CoreOS on VMs in private OpenStack. cri-o binaries from the package for CentOS 8 Stream.

Kubernetes v1.19.3

Kubelet configuration and cri-o configuration here: https://github.com/cri-o/cri-o/issues/4437#issuecomment-746390906

**Comment by haircommander** [comment]
I'm not seeing the `--cgroup-driver=systemd` flag in the kubelet config. Are crio and kubelet using the same cgroup driver? if they are, what happens when you switch to cgroupfs for both (as in, is this a systemd specific bug as the situation in the other bug suggests)

**Comment by nyxi** [comment]
I have the systemd cgroup driver configured in the configuration file for kubelet `--config=/var/lib/kubelet/config.yaml`:

```
(...)
cgroupDriver: systemd
(...)
```

I assume the systemd cgroup driver is default for cri-o?

**Comment by haircommander** [comment]
yes it is! Can you try switching the cgroup driver and see if the issue happens?

**Comment by nyxi** [comment]
I think I may have had a custom value for `conmon_cgroup` in cri-o at some point and then ended up in this situation when I reverted my configuration, not sure though - sorry :)

With default value `conmon_cgroup = "system.slice"` and reboots of the servers where kubelet was throwing the errors I have not seen it again.

**Comment by haircommander** [comment]
no need to apologize, glad you found the issue! is this good to be closed, then?

**Comment by nyxi** [comment]
Sure, thanks! 👍

**Comment by lbogdan** [comment]
Workaround and explanation [here](https://github.com/cri-o/cri-o/issues/5490#issuecomment-1107812321).
