### ISSUE TITLE
Calico not worked on CRI-O

### ISSUE THREAD

**Issue by fuzhibo** [cri-o/cri-o#4474]
**Description**
I try to deploy a kubernetes cluster of version v1.20.1. The environment config as following:
|Node|OS|Kubernetes Version|CRI Engine|
| :---: | :---: | :---: | :---: |
|Master|Ubuntu 18.04 (4.15.0-130-generic x86_64)|v1.20.1|Docker 20.10.2|
|Minion01|Centos 8 (4.18.0-240.1.1.el8_3.x86_64)|v1.20.1|CRI-O 1.20.1|
|Minion02|Centos 7 (5.9.1-1.el7.elrepo.x86_64)|v1.20.1|Docker 20.10.2|

**Steps to reproduce the issue:**
1. Deploy a node with centos 8.
2. Install CRI-O
3. Install Kubeadm and use kubeadm join to join the cluster
4. Deploy a POD on the node.
5. Use kubectl exec to enter the pod and run some net command to connect other pod of other node or access internet.
6. Use other pod of other node to connect the pod on the node of CRI-O.

**Describe the results you received:**
In step 5, the pod seems can not connect other pod of other node or access internet.
In step 6, the pod of other node can not connect the pod on the node of CRI-O. but can be pinged.

**Describe the results you expected:**
The pod's network work good on the CRI-O node. It seems it can not work on it.

**Additional information you deem important (e.g. issue happens only occasionally):**
Calico Node Version: v3.14.1
**Output of `crio --version`:**

```
crio version 1.20.0
Version:       1.20.0
GitCommit:     d388528dbed26b93c5bc1c89623607a1e597aa57
GitTreeState:  clean
BuildDate:     2021-01-11T20:46:36Z
GoVersion:     go1.14.12
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

[pcap.zip (Capture the network package for the issue)](https://github.com/cri-o/cri-o/files/5814548/pcap.zip)

**Comment by haircommander** [comment]
what's the kubeadm config you're using?

**Comment by fuzhibo** [comment]
The kubeadm config is default, only `localAPIEndpoint.advertiseAddress`, `nodeRegistration.name` was modified for the environment. The cluster is beginning with only Docker first, the CRI-O is deployed as a minion node and join the cluster recently. All config is default, the join operation only use `kubeadm join` command. @haircommander

**Comment by fuzhibo** [comment]
I have replace the CNI plugin from Calico to Weave-net, and reconfig `/etc/crio/crio.conf` to add `linux capabilities` as docker default to `default_capabilities`:
```
# List of default capabilities for containers. If it is empty or commented out,
# only the capabilities defined in the containers json file by the user/kube
# will be added.
default_capabilities = [
        "SETPCAP",
        "MKNOD",
        "AUDIT_WRITE",
        "CHOWN",
        "NET_RAW",
        "DAC_OVERRIDE",
        "FSETID",
        "FOWNER",
        "SETGID",
        "SETUID",
        "SETPCAP",
        "NET_BIND_SERVICE",
        "KILL",
        "SYS_CHROOT",
        "SETFCAP",
]
```
Then, I deploy two POD on two node, `Minion01` deploy a `busybox`, it will use `echo "test" | nc <remote ip> 10086` to connect POD on `Minion02`. I deploy a `nc` with command `nc -l 10086` to listen the port on the POD. However, the message can not send from `busybox` to `nc`.

[minion01_to_02pcap.zip](https://github.com/cri-o/cri-o/files/5819762/minion01_to_02pcap.zip)
This package record the network package from `Minion01` to `Minion02`. It seems that there are many `TCP Retransmission`, It seems too strange.

**Comment by haircommander** [comment]
is the container actually starting? did you set the cgroupDriver to systemd in kubelet config? Can I have the crio logs `journalctl -u crio` from the node?

**Comment by fuzhibo** [comment]
@haircommander here is the log: 
[k8sm01-journallog.txt](https://github.com/cri-o/cri-o/files/5827259/k8sm01-journallog.txt)

**Comment by fuzhibo** [comment]
By the way, I have replaced CRI of this node from CRI-O to containerd, everything is ok...  
The net access work fine on the node. I think this issue cased by CRI-O.

**Comment by haircommander** [comment]
did you originally start crio with weave then start using calico?
```
Error while adding pod to CNI network \"weave\": unable to allocate IP address: Post \"http://127.0.0.1:6784/ip/e2338ec773aa3e0266943ba2b64b976b904d2fbe0f4c7d462f167bfb242b0824\": dial tcp 127.0.0.1:6784: connect: connection refused
```
it seems crio was started with weave, then the pods were stopped/crio was restarted before weave was able to clean up the CNI files, and cri-o is still attempting to talk to weave, even though you're using calico. 

What's in 
`/etc/cni/net.d` and `/opt/cni/bin`

**Comment by fuzhibo** [comment]
> did you originally start crio with weave then start using calico?
> 
> ```
> Error while adding pod to CNI network \"weave\": unable to allocate IP address: Post \"http://127.0.0.1:6784/ip/e2338ec773aa3e0266943ba2b64b976b904d2fbe0f4c7d462f167bfb242b0824\": dial tcp 127.0.0.1:6784: connect: connection refused
> ```
> 
> it seems crio was started with weave, then the pods were stopped/crio was restarted before weave was able to clean up the CNI files, and cri-o is still attempting to talk to weave, even though you're using calico.
> 
> What's in
> `/etc/cni/net.d` and `/opt/cni/bin`

For more investigation, I found it may caused by CentOS 8, I tried `cri-o + calico`, `cri-o + weave`, `containerd + calico`, `containerd + weave`, `docker + calico`. All of them can't work (I also tried to configure or remove firewalld and nftables). All I think of the possibilty to cause the problem maybe the sysctl.conf.
```
vm.max_map_count=655350
vm.swappiness=0
vm.min_free_kbytes=65535
fs.file-max=655360
net.core.somaxconn=65500
net.core.netdev_max_backlog=262144
net.ipv4.tcp_max_orphans=262144
net.ipv4.tcp_timestamps=0
net.ipv4.tcp_max_syn_backlog=262144
net.ipv4.tcp_syncookies=0
net.ipv4.tcp_tw_reuse=0
net.ipv4.ip_forward=1
net.ipv4.conf.default.rp_filter=0
net.ipv4.conf.all.rp_filter=0
net.bridge.bridge-nf-call-ip6tables=1
net.bridge.bridge-nf-call-iptables=1
```
The issue should be closed, maybe not a issue.
