### ISSUE TITLE
CRI-O 'net.ipv4.ping_group_range' set failure

### ISSUE THREAD

**Issue by fuzhibo** [cri-o/cri-o#4476]
**Description**
I try to deploy a kubernetes cluster of version v1.20.1. The environment config as following:
|Node|OS|Kubernetes Version|CRI Engine|
| :---: | :---: | :---: | :---: |
|Master|Ubuntu 18.04 (4.15.0-130-generic x86_64)|v1.20.1|Docker 20.10.2|
|Minion01|Centos 8 (4.18.0-240.1.1.el8_3.x86_64)|v1.20.1|CRI-O 1.20.1|
|Minion02|Centos 7 (5.9.1-1.el7.elrepo.x86_64)|v1.20.1|Docker 20.10.2|

Then, I reconfig `/etc/crio/crio.conf` to add `net.ipv4.ping_group_range = 0 2147483647` in `default_sysctls`:
```
# List of default sysctls. If it is empty or commented out, only the sysctls
# defined in the container json file by the user/kube will be added.
default_sysctls = [
        "net.ipv4.ping_group_range = 0 2147483647",
]
```
> by the way, the config format error in [crio.conf.5.md on the github](https://github.com/cri-o/cri-o/blob/master/docs/crio.conf.5.md)
![doc_bug](https://user-images.githubusercontent.com/54472027/104699092-2f253d00-574d-11eb-8b34-f6b62d8749e6.png)

Finally, 

**Steps to reproduce the issue:**
1. Deploy a node with centos 8.
2. Install CRI-O.
3. Modify /etc/crio/crio.conf, add `net.ipv4.ping_group_range` in `default_sysctls`.
4. Restart CRI-O service.
5. Install kubeadm, kubectl and kubelet, then use `kubeadm join` to join the cluster.
6. Deploy a POD on the node of the cluster.

**Describe the results you received:**
Got the pod deploy error:
```
Events:
  Type     Reason                  Age               From               Message
  ----     ------                  ----              ----               -------
  Normal   Scheduled               46s               default-scheduler  Successfully assigned default/busybox to k8s-minion-01
  Warning  FailedCreatePodSandBox  8s (x4 over 45s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to pin namespaces [net ipc uts]: [pinns:e]: failed to open /proc/sys/net/ipv4/ping_group_range : No such file or directory
[pinns:e]: Failed to configure sysctls after unshare: No such file or directory
```

**Describe the results you expected:**
Deploy a pod worked on the node.

**Additional information you deem important (e.g. issue happens only occasionally):**
CNI is weave-kube 2.7.0

**Output of `crio --version`:**
```
crio version 1.20.0
Version:       1.20.0
GitCommit:     d388528dbed26b93c5bc1c89623607a1e597aa57
GitTreeState:  clean
BuildDate:     2021-01-11T20:46:36Z
GoVersion:     go1.14.12
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
No.  I don't believe IPv6 supports this.

**Comment by fuzhibo** [comment]
@haircommander It is a IPv4 environment.

**Comment by haircommander** [comment]
I honestly don't know why ping_group_range is not available on your system. @mrunalp @rhatdan @giuseppe any ideas here?

**Comment by rhatdan** [comment]
What kernel are you using?

**Comment by fuzhibo** [comment]
@rhatdan @haircommander I use CentOS 8
```
$ uname -a
Linux k8s-minion-01 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/redhat-release 
CentOS Linux release 8.3.2011
```

**Comment by haircommander** [comment]
and doing `cat /proc/sys/net/ipv4/ping_group_range` succeeds, but cri-o doing it fails... How are you running cri-o? just as a service? is there anything special in your systemd unit file?

**Comment by fuzhibo** [comment]
I follow the [install.md](https://github.com/cri-o/cri-o/blob/master/install.md) to install the cri-o, just as a service, all is default. @haircommander

**Comment by rhatdan** [comment]
Could this be something that systemd is doing.  If you run cri-o outside of the service, does it throw an error?

**Comment by maxaudron** [comment]
I'm running into the same problem on a NixOS host, kernel 5.10.93.

File is accessible on the host, running as systemd service or directly doesn't make a difference.

```
WARN[2022-02-19 23:33:36.703898149+01:00] Allowed annotations are specified for workload [io.containers.trace-syscall]
WARN[2022-02-19 23:33:36.882898831+01:00] Pinns [-d /var/run -f 844aa3c8-2c60-4245-a7df-9e26768ff303 -s 'net.ipv4.ping_group_range = 0   2147483647' --ipc --net --uts] failed: [pinns:w]: failed to open /proc/sys/net/ipv4/ping_group_range : No such file or directory
[pinns:e]: Failed to configure sysctls after unshare: No such file or directory
 (exit status 1)
WARN[2022-02-19 23:33:36.882924319+01:00] Failed to unmount /var/run/ipcns/844aa3c8-2c60-4245-a7df-9e26768ff303: no such file or directory
WARN[2022-02-19 23:33:36.882932424+01:00] Failed to unmount /var/run/netns/844aa3c8-2c60-4245-a7df-9e26768ff303: no such file or directory
WARN[2022-02-19 23:33:36.882940048+01:00] Failed to unmount /var/run/utsns/844aa3c8-2c60-4245-a7df-9e26768ff303: no such file or directory
```

When I don't have `default_sysctls` set, the `/proc/sys/net/ipv4/ping_group_range` entry in a running container is also accessible, and showing `1	0` as expected. Could this be an issue in timing? The pinns command running too early in the container creation cycle?

**Comment by haircommander** [comment]
@maxaudron or anyone, what is the output of `sudo unshare -n cat /proc/sys/net/ipv4/ping_group_range`?

**Comment by andrasbabos** [comment]
I have the same issue with a bit different os version:

```
$ uname -a
Linux kubecompute1 5.4.0-99-generic #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
```

```
$ crio --version
crio version 1.21.4
Version:       1.21.4
GitCommit:     61748dc51bdf1af367b8a68938dbbc81c593b95d
GitTreeState:  clean
BuildDate:     2021-12-03T20:58:29Z
GoVersion:     go1.15.2
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

unshare on host:

```
$ sudo unshare -n cat /proc/sys/net/ipv4/ping_group_range
1       0
```

**Comment by haircommander** [comment]
ah! the default_sysctls seem to be invalid. they're specified as
```
# List of default sysctls. If it is empty or commented out, only the sysctls
# defined in the container json file by the user/kube will be added.
default_sysctls = [
        "net.ipv4.ping_group_range = 0 2147483647",
]

```
but It needs to not have the extra spaces:
```
# List of default sysctls. If it is empty or commented out, only the sysctls
# defined in the container json file by the user/kube will be added.
default_sysctls = [
        "net.ipv4.ping_group_range=0 2147483647",
]
```

**Comment by andrasbabos** [comment]
> ah! the default_sysctls seem to be invalid. they're specified as
> 
> ```
> # List of default sysctls. If it is empty or commented out, only the sysctls
> # defined in the container json file by the user/kube will be added.
> default_sysctls = [
>         "net.ipv4.ping_group_range = 0 2147483647",
> ]
> ```
> 
> but It needs to not have the extra spaces:
> 
> ```
> # List of default sysctls. If it is empty or commented out, only the sysctls
> # defined in the container json file by the user/kube will be added.
> default_sysctls = [
>         "net.ipv4.ping_group_range=0 2147483647",
> ]
> ```

Thank you, tested and it working fine without the extra spaces.

**Comment by haircommander** [comment]
I've opened a PR to make the error clearer in the future

**Comment by willzhang** [comment]
> 啊！default_sysctls 似乎无效。他们被指定为
> 
> ```
> # List of default sysctls. If it is empty or commented out, only the sysctls
> # defined in the container json file by the user/kube will be added.
> default_sysctls = [
>         "net.ipv4.ping_group_range = 0 2147483647",
> ]
> ```
> 
> 但它不需要有额外的空间：
> 
> ```
> # List of default sysctls. If it is empty or commented out, only the sysctls
> # defined in the container json file by the user/kube will be added.
> default_sysctls = [
>         "net.ipv4.ping_group_range=0 2147483647",
> ]
> ```

greate
