### ISSUE TITLE
Move to GitHub actions

### ISSUE THREAD

**Issue by saschagrunert** [cri-o/cri-o#4489]
CircleCI seemed to slow-down recently and now we're in a state where some jobs have been transferred to GitHub, whereas others are still running in CircleCI.

The integration tests have a fair amount of dependencies which have to be setup before we could run them in GitHub actions. ~~Beside that, it looks like that we cannot model a pipeline in the same way we do it in CircleCI right now.~~ Edit: We can.

Anyways, I'd prefer moving completely over to GitHub actions.

We also have access to packet.net (now Equinix Metal) resources where we could maintain our own GitHub actions runners (one per machine). This has the drawback that we actually have to maintain the machines on our own.

Any thoughts on that?

Ref https://github.com/cri-o/cri-o/issues/3008
cc @haircommander @kolyshkin

**Comment by haircommander** [comment]
I would be interestd in moving to github actions. runc uses vagrant to set up VMs, so we could do something similar I'd think
