### ISSUE TITLE
`crio config` fixes

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#4506]
Currently, calling `crio config` spits out an entire config file. However, it would be prudent for us to move away from the monolithic config file, in favor of smart defaults, and drop-in files.

However, to do this, there needs to be a way for users to quickly create drop-in files, and have them not override the defaults where they don't need to.

The main advantage to this approach is it allows us to change defaults without as much churn in config files.

This proposal is to change `crio config` to render the configuration/flags it's passed, and only print the toml for the fields that are different than the default.

Sample could be:
`crio --log-level debug config`
would only output
```
[crio]
[crio.runtime]
log_level = "debug"
```

/kind feature

**Comment by saschagrunert** [comment]
Yep, I think this makes sense and would be a good addition :+1:

**Comment by ityuhui** [comment]
May I take this ticket ?

**Comment by ityuhui** [comment]
Hi @haircommander 

I have 4 design behaviors for you to confirm : 

1. What should be the output of ``crio config`` ?

2. What should be the output of ``crio config --default`` ?

3. What should be the output of ``crio --config="" config`` ?

4. What should be the output of ``crio --config="a_valid_config_file" config`` ?

**Comment by haircommander** [comment]
hey @ityuhui ! here's what I think:

1: `crio config` should output the diff of the current configuration (/etc/crio/crio.conf + /etc/crio/crio.conf.d/*) and the default
2: I forgot we had this flag. I suppose if it's manually asked for, `crio config --default` should specify the whole config (all with defaults filled in)
3: note there's `--config=""` and `--config-dir`. I assume you meant `--config="" --config-dir=""`, which I think should print nothing out
4: this should only print the diff of that valid configuration file and the default configuration

**Comment by haircommander** [comment]
wdyt?

**Comment by ityuhui** [comment]
I agree and will implement the above behaviors.
