### ISSUE TITLE
When using crictl to create pod, the rpc error : get https://k8s.gcr.io/v2/: dial tcp i/o time out  occurred.

### ISSUE THREAD

**Issue by ccnankai** [cri-o/cri-o#4518]
According to CRI-O crictl tutorial,I type the following command in the shell,

*POD_ID=$(sudo crictl runp test/testdata/sandbox_config.json)*

Then the following error is reported：

![image](https://user-images.githubusercontent.com/33537489/105987053-b1601a80-60d8-11eb-823c-8a1022c5fa81.png)

If I cannot connect to k8s.gcr.io/v2/, is there any proxy setting to solve this problem?

**Comment by saschagrunert** [comment]
Hey @ccnankai, is this a reproducible issue? From my location (Germany) I have no issues accessing the k8s.gcr.io images. May It be possible that you're blocked by some firewall?

**Comment by ccnankai** [comment]
Thank you very much, I am indeed restricted from accessing k8s.gcr.io here.
