### ISSUE TITLE
How to get the name of the cri-o image I need, such as ubuntu16.04

### ISSUE THREAD

**Issue by ccnankai** [cri-o/cri-o#4522]
I just started learning to use crio, I am a novice
No one answered me on the stackoverflow website, so I am sorry to ask questions here.
I have the following three  questions, and I found no tutorials anywhere,  I was very confused.

(1)I can search for the image I need from docker hub and download it. If I use cri-o, where can I find the basic image I need, such as ubuntu:16.04 .  use  docker.io/library ? 

(2) Can I make my own image from scratch?Just like using dockerfile to build docker image  .

(3)Is there a tutorial on  the json format configuration file of   pod and container

**Comment by haircommander** [comment]
no need to apologize for asking questions :)
1: we recommend [podman](github.com/containers/podman) or [skopeo](github.com/containers/skopeo) for inspecting images. You can use podman in the same way as you would the docker CLI.
2: we recommend [buildah](github.com/containers/buildah) for building images from a Dockerfile
3: Are you talking about the files given to crictl? Those are the JSONified version of the [cri-api](https://github.com/kubernetes/cri-api/blob/master/pkg/apis/runtime/v1/api.proto). There's no specific documentation on how to map between the values, but you basically translate the `PascalCase` variable name in the protobuf definition to `snake_case` in JSON (see https://www.chaseadams.io/posts/most-common-programming-case-types/)

**Comment by ccnankai** [comment]
@haircommander 
Thank you very much for your patience and advice. These are very helpful to me and my problems have been solved. Thanks.
