### ISSUE TITLE
Is there a function or structure in go that can get detailed information about the container?

### ISSUE THREAD

**Issue by ccnankai** [cri-o/cri-o#4527]
I want to get the detailed information of the container in the Go language, such as container ID, continaer name, etc.
 Is there a good way?

**Comment by haircommander** [comment]
we don't expose any library that would give one access to the internals like that. what are you using it for? 

no need to apologize, this is a good forum for asking questions :)

**Comment by ccnankai** [comment]
@haircommander   
I want to make a prestart-hooks, just like nvidia-container-toolkit (toolkit of nvidia-gpu), mount the device that nvidia-gpu needs to use in the /dev  into the container, and then get permission. These devices can be used inside the container.
Thank you very much.
