### ISSUE TITLE
Make `ctx.SystemRegistriesConfDirPath` configurable via CLI

### ISSUE THREAD

**Issue by maybe-sybr** [cri-o/cri-o#4593]
**Description**

It is currently possible to use a specific `containers-registries.conf(5)` file via the hidden `--registries-conf` CLI option but there is no similar option to set the directory path used for `containers-registries.conf.d(5)`. Instead, the usual user path (if extant) or system path will be used.

**Steps to reproduce the issue:**
N/A

**Describe the results you received:**
N/A

**Describe the results you expected:**
N/A

**Additional information you deem important (e.g. issue happens only occasionally):**
None

**Output of `crio --version`:**

```
crio version 1.20.0
Version:       1.20.0
GitCommit:     d388528dbed26b93c5bc1c89623607a1e597aa57
GitTreeState:  clean
BuildDate:     2020-12-11T17:42:02Z
GoVersion:     go1.15.5
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by maybe-sybr** [comment]
This is actually slightly surprising behaviour to me. I wouldn't necessarily expect the system or user conf.d directories to be respected at all when I provide my own .conf file, but that's probably a debatable point. That said, I'd be happy if the existing behaviour was left unchanged as long as I could override it with my own conf.d path via the CLI and/or env vars

**Comment by haircommander** [comment]
are you interested in opening a PR @maybe-sybr ?

**Comment by maybe-sybr** [comment]
I certainly can, @haircommander . The way the CLI options get put into the system context seems simple enough so I'll see what I can do today.
