### ISSUE TITLE
Image endpoint configuration can (should?) be omitted from crictl.yaml

### ISSUE THREAD

**Issue by maybe-sybr** [cri-o/cri-o#4607]
**Description**

The `crictl.yaml` bundled in this repo contains configuration for both the runtime and image endpoints with the same path: `unix:///var/run/crio/crio.sock`. This makes some sense since omitting these to use the default endpoint searching behaviour is marked as deprecated. However, `image-endpoint` is documented as defaulting to the value of `runtime-endpoint` if it is not otherwise set. By setting both configuration parameters to the same value, we're actually causing `image-endpoint` to not be able to mirror `runtime-endpoint` when only that value is set, e.g. `crictl --runtime-endpoint=unix://foo/bar/baz`, since `image-endpoint` has been explicitly set to `unix:///var/run/crio/crio.sock` in the config file.

I raised this at kubernetes-sigs/cri-tools#722 first and @povsister pointed out that it was likely the `crictl.yaml` getting in the way.

**Steps to reproduce the issue:**
1. Stop any system/user cri-o to ensure the configured sockets no longer exist
2. Run a cri-o with some other RPC endpoint path (I use usernetes, but manually running a crio would also probably work)
3. `crictl --runtime-endpoint=unix:///some/alternative/endpoint/path images` and various alternatives show below

**Describe the results you received:**

```
[maybe@karma cri-o]$ crictl images
FATA[0002] connect: connect endpoint 'unix:///var/run/crio/crio.sock', make sure you are running as root and the endpoint has been started: context deadline exceeded
[maybe@karma cri-o]$ crictl --runtime-endpoint unix:///run/user/1337/usernetes/crio/crio.sock images
FATA[0002] connect: connect endpoint 'unix:///var/run/crio/crio.sock', make sure you are running as root and the endpoint has been started: context deadline exceeded
[maybe@karma cri-o]$ CONTAINER_RUNTIME_ENDPOINT=unix:///run/user/1337/usernetes/crio/crio.sock crictl images
FATA[0002] connect: connect endpoint 'unix:///var/run/crio/crio.sock', make sure you are running as root and the endpoint has been started: context deadline exceeded
[maybe@karma cri-o]$ crictl --image-endpoint unix:///run/user/1337/usernetes/crio/crio.sock images
IMAGE                       TAG                 IMAGE ID            SIZE
docker.io/library/busybox   1.31.0              19485c79a9bbd       1.44MB
k8s.gcr.io/pause            3.2                 80d28bedfe5de       688kB
[maybe@karma cri-o]$ IMAGE_SERVICE_ENDPOINT=unix:///run/user/1337/usernetes/crio/crio.sock crictl images
IMAGE                       TAG                 IMAGE ID            SIZE
docker.io/library/busybox   1.31.0              19485c79a9bbd       1.44MB
k8s.gcr.io/pause            3.2                 80d28bedfe5de       688kB
```

**Describe the results you expected:**

Setting just the `CONTAINER_RUNTIME_ENDPOINT` env var or `--runtime-endpoint` argument should be enough to access the image endpoint as well since they are the same path.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
1.20 modular
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by haircommander** [comment]
thanks for opening the issue, but this seems to be an issue with crictl more than CRI-O, as that's where the endpoint is being specified and where the inconsistent behaviour is happening. Are there any things you expect CRI-O to be doing differently?

**Comment by maybe-sybr** [comment]
It's an issue with the crictl.yaml config bundled by CRI-O being (IMHO) too specific. There's no need for the config file bundled in the RPM to specify that both the runtime and image endpoints are at the same path, and it causes a slight headache when attempting to use an alternate (non-system) CRI-O like the one started by usernetes. Of course, that's only valid while CRI-O does in fact provide the runtime and image endpoints on the same unix socket.

It'd be entirely valid to close this as WONTFIX since I can do any of the following:
 * `CRI_CONFIG_FILE=/some/other/crictl.yaml crictl ...`
 * `crictl --config /some/other/crictl.yaml ...`
 * or set both the runtime and image endpoints to my preferred CRI-O RPC socket path as shown in the top post

Removing `image-endpoint:` from the CRI-O bundled `crictl.yaml` would be a nice way to avoid those and have it Just Work (TM) when I specify `--runtime-endpoint=...` naively.

**Comment by povsister** [comment]
> It's an issue with the crictl.yaml config bundled by CRI-O being (IMHO) too specific.

That's the key point.
I think the behavior `crictl` is reasonable, and there is no need to explicitly specify `image-endpoint` if both of them are served on the same socket. (and it's always so for most of cases.)

As far as I know, the `crictl.yaml` bundled in containerd distribution only has `runtime-endpoint` defined.

**Comment by haircommander** [comment]
that's fine with me. how are you installing cri-o? would you be interested in opening a PR to fix in this repo?
