### ISSUE TITLE
infra container creation should live entirely in internal/factory/sandbox

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#4622]
Right now, we create the infra container entirely in server/sandbox_run_linux.go

Long term, we should move sandbox to pkg/sandbox, and the infra container creation is around 70% of sandbox creation

This is a tracking issue for this work

**Comment by arcolife** [comment]
just agreed with @haircommander to take a shot at this one!

**Comment by arcolife** [comment]
I got this
