### ISSUE TITLE
Why does CRI-O impose the restriction of only loading binaries from the PATH?

### ISSUE THREAD

**Issue by fidencio** [cri-o/cri-o#4632]
While browsing CRI-O code I've faced the following test:
https://github.com/cri-o/cri-o/blob/c61c691b9c6d00ab18268d1a5d53d2b9c2dd2702/pkg/config/config_test.go#L462-L471

Why do we need to ensure that the runtime binary is part of the `PATH`? Security implications? Something else?

I'm asking as it directly impacts https://github.com/cri-o/cri-o/issues/4541 and the issue I've opened for containerd https://github.com/containerd/containerd/issues/5006.

Also, if we want to ensure the `PATH` is used, we should actually check that the full binary passed as the `runtime_path` is part of the `PATH` and fail otherwise, and this should be done as part of the config validation.

/cc @mrunalp, @haircommander, @saschagrunert

**Comment by saschagrunert** [comment]
> Why do we need to ensure that the runtime binary is part of the `PATH`? Security implications? Something else?

Do we? If I create a pseudo runtime:
```
> cat /etc/crio/crio.conf.d/03-runtime.conf
[crio.runtime]
default_runtime = "my-runtime"

[crio.runtime.runtimes.my-runtime]
runtime_path = "/tmp/my-runtime"
```

And then start CRI-O:
```
> touch /tmp/my-runtime
> sudo crio --log-level=debug
…
DEBU[2021-03-08 13:50:21.224366027+01:00] Found valid runtime "my-runtime" for runtime_path "/tmp/my-runtime"  file="config/config.go:1058"
…
```

**Comment by fidencio** [comment]
> > Why do we need to ensure that the runtime binary is part of the `PATH`? Security implications? Something else?
> 
> Do we? If I create a pseudo runtime:
> 
> ```
> > cat /etc/crio/crio.conf.d/03-runtime.conf
> [crio.runtime]
> default_runtime = "my-runtime"
> 
> [crio.runtime.runtimes.my-runtime]
> runtime_path = "/tmp/my-runtime"
> ```
> 
> And then start CRI-O:
> 
> ```
> > touch /tmp/my-runtime
> > sudo crio --log-level=debug
> …
> DEBU[2021-03-08 13:50:21.224366027+01:00] Found valid runtime "my-runtime" for runtime_path "/tmp/my-runtime"  file="config/config.go:1058"
> …
> ```

Yep, same here with `containerd-shim-kata-v2` binaries from different locations.  However, that test made me think that:
1. We enforced that in the past, **consciously** dropped the restriction, and we should also update the tests;
2. We enforced that in the past, **unconsciously** dropped the restriction, and we should update the code;
3. We never enforced that, and we should update the tests;

I've decided to have the issue opened in order to be able to find the discussion later on. :-)

**Comment by haircommander** [comment]
I think this was a concious decision that doesn't have a test... yet :wink:

**Comment by fidencio** [comment]
> I think this was a concious decision that doesn't have a test... yet wink

If that's the case, I'll update the tests as part of https://github.com/cri-o/cri-o/issues/4541, when I get to work on that.
Meanwhile, I'll leave it to y'all to decide whether we can should leave this one open or if we should close it.

**Comment by fidencio** [comment]
We adapted the test as part of f04cdc51de99b3c66964a7c2b04ce56c5480e8e4 and, IMHO, we could just close it.

If someone thinks differently, please, just re-open the issue and @ me here. :-)
