### ISSUE TITLE
cri-o 1.20.0 package replaced by 1.20.1

### ISSUE THREAD

**Issue by lazystone** [cri-o/cri-o#4657]
**Description**

cri-o 1.20.0 package replaced by 1.20.1

See https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.20:/1.20.0/xUbuntu_20.04/amd64/

So there is no way to install 1.20.0

**Comment by lazystone** [comment]
Might be related to #4484

**Comment by haircommander** [comment]
oh darn.

note to self: branching a package makes a shallow copy :upside_down_face:

**Comment by haircommander** [comment]
updated, sorry for the difficulty

**Comment by lazystone** [comment]
@haircommander it's back to repo now, thanks!

Also small side-question: on Ubuntu when I do `apt-get install cri-o cri-o-runc` it also always install `runc` package, which is a bit confusing, since it's much older version of runc. Is it intended or is there some misconfiguration in the package dependencies?

**Comment by haircommander** [comment]
@lazystone that seems unintended, thanks for the heads up I'll take a look

**Comment by haircommander** [comment]
I updated it for 1.20.1, I'll do so for 1.20.2 when I release it
