### ISSUE TITLE
cri-o 1.20.1 fails to run privileged pods: unknown capability "CAP_PERFMON"

### ISSUE THREAD

**Issue by lazystone** [cri-o/cri-o#4658]
```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  15s                default-scheduler  Successfully assigned kube-system/kube-proxy-7j8zj to nas
  Warning  Failed     14s (x2 over 14s)  kubelet            Error: container create failed: time="2021-03-15T07:39:31+01:00" level=error msg="container_linux.go:370: starting container process caused: unknown capability \"CAP_PERFMON\""
  Normal   Pulled     1s (x3 over 14s)   kubelet            Container image "k8s.gcr.io/kube-proxy:v1.20.4" already present on machine
  Warning  Failed     1s                 kubelet            Error: container create failed: time="2021-03-15T07:39:44+01:00" level=error msg="container_linux.go:370: starting container process caused: unknown capability \"CAP_PERFMON\""
 ```

```
crio --version
INFO[0000] Starting CRI-O, version: 1.20.1, git: 0e6266bc8b26e7f8c1b85df3af7af1dcb50ce813(clean) 
crio version 1.20.1
Version:       1.20.1
GitCommit:     0e6266bc8b26e7f8c1b85df3af7af1dcb50ce813
GitTreeState:  clean
BuildDate:     2021-03-12T02:24:13Z
GoVersion:     go1.15.2
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

And 1.20.0 release can't be installed anymore because it was removed from repository: #4657

Problem seems to be related to #4466

1.20.1 release has different gocapability than 1.20.0: https://github.com/cri-o/cri-o/blob/v1.20.1/go.mod#L54

But cri-o-runc package wasn't updated in the repos, still 1.0.0~rc92.3: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/amd64/

**Comment by saschagrunert** [comment]
Thank you for the issue report @lazystone, a fix is in flight in https://github.com/cri-o/cri-o/pull/4659

**Comment by Sh4d1** [comment]
@saschagrunert can we expect a 1.20.2 soon? Or should I rather revert and wait? 😄

**Comment by saschagrunert** [comment]
> @saschagrunert can we expect a 1.20.2 soon? Or should I rather revert and wait?

Let's ask @haircommander about this :upside_down_face:

**Comment by haircommander** [comment]
yeah I can work on a 1.20.2

**Comment by haircommander** [comment]
cri-o 1.20.2 will be packaged up tomorrow I believe also

**Comment by StrikerExtreem** [comment]
I updated on my raspberrypi from 1.20.2 to 1.21.0. And the CAP_PERFMON has returned.
I also found that the /etc/crio/crio.conf file is empty, which it wasn't on 1.20.2.

**Comment by haircommander** [comment]
darn :( we will revert the issue for 1.21.1

the config file being empty is expected, though we intend on changing it

**Comment by moto-timo** [comment]
Also seeing CAP_PERFMON on Debian 10 x86_64 system after upgrade to 1.21.0 (this system is on 5.10 kernel).
cri-o installed from https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.21/

**Comment by ledroide** [comment]
Same issue here, running : 
* Kubernetes 1.21.1
* cri-o 1.21.0
* CentOS Stream + Linux 4.18.0-294.el8.x86_64

Privileged pods in kube-system namespace keep on _CreateContainerError_ status.
Events report that CAP_PERFMON is an unknown capability : 
```
Error: container create failed: time="2021-06-02T12:03:51+02:00" level=error msg="container_linux.go:370: starting container process caused: unknown capability \"CAP_PERFMON\""
```

**Comment by haircommander** [comment]
are people able to upgrade the runc version? There is a newly built one in the OBS repo (cri-o-runc)

**Comment by haircommander** [comment]
independently, I'd like to cook up new releases for like every release branch soon .that should also help. thanks for the patience folks

**Comment by elinesterov** [comment]
Same issue with 1.21.1 on raspberry with `cri-o` from https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.21/ and `crun` from https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Raspbian_10
`runc` at the same time works perfectly fine

**Comment by haircommander** [comment]
> Same issue with 1.21.1 on raspberry with `cri-o` from https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.21/ and `crun` from https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Raspbian_10
> `runc` at the same time works perfectly fine
> 
> ```
> apt info cri-o-runc
> Package: cri-o-runc
> Version: 1.0.0~rc93.1
> ```

cri-o-runc should be upgradable to rc95 now

**Comment by elinesterov** [comment]
Ок. my fault. I just build `crun` out of 0.20.1 release and it works fine.

**Comment by kubealex** [comment]
mmhh, not working from https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.21/CentOS_8_Stream/

**Comment by ledroide** [comment]
However, using cri-o 1.20.3 on a Kubernetes 1.21.1 cluster works fine for me, no CAP_PERFMON issue, and I did not find side effects.
Tried the last cri-o package [cri-o-1.21.0-4.22 for centos:stream](https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.21/CentOS_8_Stream/x86_64/cri-o-1.21.0-4.22.el8.x86_64.rpm) and the CAP_PERFMON issue is still there.

**Comment by kubealex** [comment]
Still broken in https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.21/CentOS_8_Stream/x86_64/cri-o-1.21.0-29.1.el8.x86_64.rpm

**Comment by haircommander** [comment]
sorry for the delay, I've just updated the 1.21 branch to have 1.21.1, which should have the fix

**Comment by ledroide** [comment]
[Cri-o 1.21.1](https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.21/CentOS_8_Stream/x86_64/cri-o-1.21.1-3.1.el8.x86_64.rpm) fixes the CAP_PERFMON issue for me.
Thank you @haircommander

**Comment by kubealex** [comment]
> sorry for the delay, I've just updated the 1.21 branch to have 1.21.1, which should have the fix

Thanks Peter! Successfully tested, you're the best!

**Comment by haircommander** [comment]
thanks for the patience folks! I will close this issue, someone yell at me if this sneaks in again :laughing:

**Comment by haircommander** [comment]
hey all, considering newer runcs now support this capability, we have opted to [undo the workaround](https://github.com/cri-o/cri-o/pull/5241/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L80) that fixes this issue. If anyone runs into the issue again, please let me know and we can figure out how to get you a newer runc

**Comment by ledroide** [comment]
Hello,
The CAP_PERFMON bug is back with cri-o 1.22.1 when using runc-1.0.0-70.rc92 . This version of runc was running fine with cri-o 1.21.4. In Kubernetes, privileged pods (such as calico, dns, metrics-server) fail to start in kube-system.
Upgrading runc to runc-1.0.2-1 solves the issue.
@haircommander : Not sure it is a cri-o or a runc issue ; my comment is there to help anyone who faces the same problem when upgrading cri-o.
i.e. we can use ansible : 
```bash
ansible -i ${ANSIBLE_INVENTORY_PATH} all --become -m package -a "name=runc state=latest"
```

**Comment by haircommander** [comment]
yeah at this point we hope that folks are using an up-to-date runc that has the fixes. I am glad to hear you have found a way to have such a runc :smiley:

**Comment by Chathuru** [comment]
> 

Upgrading runc to runc-1.0.2-1 solves the issue for me as well
