### ISSUE TITLE
refactor config/CLI handling

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#4675]
right now, there are like 5 different places that need updating if we add a new config/cli field:
pkg/config/config.go to add it to the structure
pkg/config/template.go to add it to the man page template
internal/criocli/criocli.go to add the cli flag
docs/* and completions/* to add completions and documentation

Ideally, we could have just one (or maybe two) places we add a structure, and then we automatically generate the config structure, CLI and documentation out of that

This issue is to track that work

**Comment by tushar-dubey** [comment]
Hi! I want to pick this up.

**Comment by haircommander** [comment]
That's awesome to hear :smile:

**Comment by haircommander** [comment]
Please reach out if you have any questions!

**Comment by tushar-dubey** [comment]
Sure will do. currently checking out the code and trying to have a succesfull local build.

**Comment by agbanagba** [comment]
Hi @haircommander , Has this issue been worked on. I will like to take it up.

**Comment by haircommander** [comment]
hey @agbanagba no one has done this yet and we'd love your help. May I assign you?

**Comment by agbanagba** [comment]
Sure @haircommander. You can assign this to me.
