### ISSUE TITLE
add CI job to CRI-O simulating upstream prow job

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#4688]
after https://github.com/cri-o/cri-o/issues/4466 being closed and reopened, it occured to me we should gate changes in cri-o on how it will affect the upstream k8s prow job

this is a tracking issue to see if this makes sense.

@harche @saschagrunert wdyt

**Comment by saschagrunert** [comment]
Yes, this makes sense. See my first approach in #4687
