### ISSUE TITLE
Different container state between kubernetes and crictl

### ISSUE THREAD

**Issue by michalzxc** [cri-o/cri-o#4693]
I am opening this one in replacement of #4676 what wasn't accurate

**Description**
I found container what shows in kubectl describe that it is Running, while crioctl shows "Completed" with exit code 0:
```
  drone-1qljfp58m4cuf0qxndjo:
    Container ID:  cri-o://7f8d467da4d7288d9083887f5539fdac4ba5d6b3967638c8b88b31d2ab1e65f2
    Image:         ecr.ad.dice.fm/base:waitdbs-latest
    Image ID:      ecr.ad.dice.fm/base@sha256:5973219db525061334ccb4ef74f1e3220ad13f01ad0419599cd5be933bc73d2b
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
    Args:
      echo "$DRONE_SCRIPT" | /bin/sh
    State:          Running
      Started:      Tue, 23 Mar 2021 17:15:21 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Tue, 23 Mar 2021 17:14:54 +0000
      Finished:     Tue, 23 Mar 2021 17:15:20 +0000
```

```
crictl inspect 7f8d467da4d72
{
  "status": {
    "id": "7f8d467da4d7288d9083887f5539fdac4ba5d6b3967638c8b88b31d2ab1e65f2",
    "metadata": {
      "attempt": 1,
      "name": "drone-1qljfp58m4cuf0qxndjo"
    },
    "state": "CONTAINER_EXITED",
    "createdAt": "2021-03-23T17:15:21.459089592Z",
    "startedAt": "2021-03-23T17:15:21.479616027Z",
    "finishedAt": "2021-03-23T17:15:24.646643722Z",
    "exitCode": 0,
    "image": {
      "image": "ecr.ad.dice.fm/base:waitdbs-latest"
    },
    "imageRef": "ecr.ad.dice.fm/base@sha256:5973219db525061334ccb4ef74f1e3220ad13f01ad0419599cd5be933bc73d2b",
    "reason": "Completed",
```

In kubectl describe I am not showing pod status, but status of particulat container inside a pod

It doesn't happen all the time, but in 24h I can find couple of them, on our CI/CD kubernetes nodes

Below is full crio debug log:
https://drive.google.com/file/d/1FRP4FBnt92wkMObmSQb2fHZVzjGZW_qA/view

**Steps to reproduce the issue:**
Run hundreds of pods with multiple containers each until it will happen - or run actively used drone-ci, what generates lot of pods during a day

**Describe the results you received:**
kubectl describe shows that container inside pod is Running, while crictl inspect shows it EXITED

**Describe the results you expected:**
I expected that kubectl with show correct state of container

**Additional information you deem important (e.g. issue happens only occasionally):**
I might be wrong, but I suspect that this is something about not passing CONTAINER_EXITED event from crio to kubelet

**Output of `crio --version`:**

```
 crio --version
crio version 1.18.4
Version:       1.18.4
GitCommit:     aba91e59ec78e3299e443a7364e2cf8909af4606
GitTreeState:  clean
BuildDate:     2020-11-10T20:02:11Z
GoVersion:     go1.15.2
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical, "Infra-3" Dedicated host from OVH

**Comment by saschagrunert** [comment]
Hey @michalzxc, thank you for the report. The mentioned difference in the outputs seems to be related to diverging code paths being executed by the kubelet and crictl. One question:

If you run `crictl inspect` on the container first, is then the kubelet able to report the correct state?

Unfortunately I'm not able to reproduce the issue locally right now. Would you be able to deploy a custom build of CRI-O in your cluster to see if the issue still persists if I prepare a fix?

**Comment by michalzxc** [comment]
Hi,
Yes, absolutely I can try custom build :)

I didn't check explicitly, but I suspect it didn't. I noticed the problem while debuging some drone-ci jobs getting stuck. They were stuck. because kubernetes is reporting them as "Running" indefinitely. Every step is in a container, and step what takes usually 8s, suddenly is Running for example for 30minutes. So I firstly checked kubectl describe, and later jumped to node and checked crictl inspect. Nothing I did, unstuck it, and it remained running until drone-ci timeouted for pipeline execution, what is set for 60m

I know that drone is doing one weird-ish thing, it starts pod with every container image as "place holder" and some way it replace it with actual image after first container restart. Possibly this is the operation what turns out to be tricky?
https://github.com/drone-runners/drone-runner-kube/pull/37#issuecomment-665703923 

As said, it all works well 98% of time, but every 1/50 pod is getting stuck

**Comment by saschagrunert** [comment]
> Yes, absolutely I can try custom build :)

Awesome, can you give this PR a try: https://github.com/cri-o/cri-o/pull/4695
If you want, then just download the static binary for  x86-64 directly from the CI run: https://github.com/cri-o/cri-o/suites/2367396161/artifacts/50156093

> I know that drone is doing one weird-ish thing, it starts pod with every container image as "place holder" and some way it replace it with actual image after first container restart. Possibly this is the operation what turns out to be tricky?

I don't think that this is related, but I might be wrong and double check.

**Comment by michalzxc** [comment]
With this one kube-proxy started failing with:
```
  Warning  Failed          12s                kubelet  Error: container create failed: time="2021-03-29T15:44:51+01:00" level=error msg="container_linux.go:370: starting container process caused: unknown capability \"CAP_PERFMON\""
```

I was running crio in version 1.18.4 before, following Readme saying that for kubernetes 1.18 I should run 1.18 version of crio?

The binary you sent is 1.21.0-dev, should I just ignore difference and remove CAP_PERFMON from kube-proxy?

**Comment by saschagrunert** [comment]
Can you please upgrade runc to rc 93? The binary is available in the bundle, too:
https://github.com/cri-o/cri-o/suites/2367396161/artifacts/50156095

**Comment by michalzxc** [comment]
Thank you, yes it started with it. 

I will let you know if I will see status issue again with this fix present

**Comment by saschagrunert** [comment]
> I will let you know if I will see status issue again with this fix present

Awesome, thank you so much! :pray:

**Comment by michalzxc** [comment]
I just saw it to happen again:

kubectl describe
```
  drone-gwnr9euh15qpjikc58yu:
    Container ID:  cri-o://7708bc69de8506faa54ca0a592a6ce205d5f6a313b67865ed8fadc0be3dbe278
    Image:         ecr.ad.dice.fm/base:imagebuilder-latest
    Image ID:      docker.io/drone/placeholder@sha256:1b791b37e0589c7f1470fe0210ec0e7ef1e1de479c8f742d25942d2b4617bc07
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
    Args:
      echo "$DRONE_SCRIPT" | /bin/sh
    State:          Running
      Started:      Mon, 29 Mar 2021 18:24:29 +0100
    Ready:          True
    Restart Count:  0
```

``` 
crictl ps -a|grep drone-gwnr9euh15qpjikc58yu
337c691e99b0e       ecr.ad.dice.fm/base@sha256:cd59042101be6e233b67f550d0b70c5f9c3b8891ebd2ae4d1b9bd6bebf271e34           43 minutes ago      Exited              drone-gwnr9euh15qpjikc58yu   1                   1cdc1460fccb1
```

```
crictl inspect 337c691e99b0e
{
  "status": {
    "id": "337c691e99b0ed479a6e32f117e90224b02da14cd99083063b752ad46082ab95",
    "metadata": {
      "attempt": 1,
      "name": "drone-gwnr9euh15qpjikc58yu"
    },
    "state": "CONTAINER_EXITED",
    "createdAt": "2021-03-29T18:24:53.308212031+01:00",
    "startedAt": "2021-03-29T18:24:53.32933952+01:00",
    "finishedAt": "2021-03-29T18:31:25.93772367+01:00",
    "exitCode": 2,
    "image": {
```

I run kubectl describe again after inspect command, but it did not refresh the state

New journal log:
https://drive.google.com/file/d/1DEtY02IBYsoRwO1oUcP94vIeuqpTDhO3/view (tar.bz2)

**Comment by michalzxc** [comment]
I notice that this time I can see this placeholder image I told you about in Image ID :

```
    Image ID:      docker.io/drone/placeholder@sha256:1b791b37e0589c7f1470fe0210ec0e7ef1e1de479c8f742d25942d2b4617bc07
```

**Comment by saschagrunert** [comment]
> I just saw it again:

This one might be a red herring, because the container ID:

> ```
>     Container ID:  cri-o://7708bc69de8506faa54ca0a592a6ce205d5f6a313b67865ed8fadc0be3dbe278
> ```

from kubectl describe does not match the ID from the crictl output:

> ```
> crictl ps -a|grep drone-gwnr9euh15qpjikc58yu
> 337c691e99b0e       ecr.ad.dice.fm/base@sha256:cd59042101be6e233b67f550d0b70c5f9c3b8891ebd2ae4d1b9bd6bebf271e34           43 minutes ago      Exited              drone-gwnr9euh15qpjikc58yu   1                   1cdc1460fccb1
> ```

Can you ensure that the container `7708bc69de8506faa54ca0a592a6ce205d5f6a313b67865ed8fadc0be3dbe278` is running? I think due to the rescheduling/image name change effect there will be one container exited in any case.

**Comment by michalzxc** [comment]
I see, different ID, will check it if/when I will see it again. Drone-CI pipeline what is producing these pods has internal 60minutes timeout, so these are already gone

**Comment by michalzxc** [comment]
It took some time, but got it again:

```
  drone-gfc5j8k15wr5baokozqp:
    Container ID:  cri-o://5677c0b966ab3f25ec7873732d1033c44b2cd85eca9c39d2c396ec3646c357bc
    Image:         ecr.ad.dice.fm/base:imagebuilder-latest
    Image ID:      docker.io/drone/placeholder@sha256:1b791b37e0589c7f1470fe0210ec0e7ef1e1de479c8f742d25942d2b4617bc07
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
    Args:
      echo "$DRONE_SCRIPT" | /bin/sh
    State:          Running
      Started:      Wed, 31 Mar 2021 13:24:20 +0100
    Ready:          True
    Restart Count:  0
```
```
 crictl ps -a|grep    drone-gfc5j8k15wr5baokozqp
ba87b3150756d       50be76f541ecac94a77fc3b02ee932fe0f81a728981df88740b91879c2ea4af7                                      44 minutes ago       Exited              drone-gfc5j8k15wr5baokozqp   1                   3d76cb615a301
```

Different ID again, looking for ID:

```
crictl ps -a|grep 5677c0b966ab3f25ec7873732d1033c44b2cd85eca9c39d2c396ec3646c357bc
[root@drone1cluster0dc ~]# 
```
not found

```
kubectl --namespace drone-ci-exec logs drone-f599oe6z2kbrthogm4cf drone-gfc5j8k15wr5baokozqp
  unable to retrieve container logs for cri-o://5677c0b966ab3f25ec7873732d1033c44b2cd85eca9c39d2c396ec3646c357bc
```

Pipeline timeouted around 14:22

journald logs:
https://drive.google.com/file/d/1Wj9ATpzLiXnJfUE_KdUNR3sDLzTbFlwo/view?usp=sharing

**Comment by michalzxc** [comment]
I did some extra checks how it usually works:

```
kubectl --namespace drone-ci-exec get pods  drone-xv55stnsvg62pgumdqgz  -o yaml|egrep "image:|imageID:"
    image: docker.io/drone/git:latest
    imageID: docker.io/drone/git@sha256:4a030a46a38951a7ec39fbe0eaf924597218b67f4090ace3cdca9548d0a017a3
    image: docker.io/library/redis:latest
    imageID: docker.io/library/redis@sha256:c82cacd2eee119e912ad61abe2a60b2ee728ef06fbb3c0fa1555728e4188bc69
    image: docker.io/drone/placeholder:1
    imageID: docker.io/drone/placeholder@sha256:1b791b37e0589c7f1470fe0210ec0e7ef1e1de479c8f742d25942d2b4617bc07
    image: docker.io/bitnami/postgresql:11
    imageID: docker.io/bitnami/postgresql@sha256:7384fd80570b3614e7a611a383defaea6af49033501876feb307b68e31757393
    image: docker.io/drone/placeholder:1
    imageID: docker.io/drone/placeholder@sha256:1b791b37e0589c7f1470fe0210ec0e7ef1e1de479c8f742d25942d2b4617bc07
    image: ecr.ad.dice.fm/base:imagebuilder-latest
    imageID: ecr.ad.dice.fm/base@sha256:e3e62e3b2411ab2853fecb99b28d40d50836455b3717bfafef024b292a0c6e43
    image: docker.io/drone/placeholder:1
    imageID: docker.io/drone/placeholder@sha256:1b791b37e0589c7f1470fe0210ec0e7ef1e1de479c8f742d25942d2b4617bc07
    image: docker.io/dicefm/elixir-image:elixir-1.8.2
    imageID: docker.io/dicefm/elixir-image@sha256:fa6947ffba8a2d3b8cfa04d9b13a2fc60279526fd3c28992622a4375e7217dfd
    image: docker.io/drone/placeholder:1
    imageID: docker.io/drone/placeholder@sha256:1b791b37e0589c7f1470fe0210ec0e7ef1e1de479c8f742d25942d2b4617bc07
    image: docker.io/library/mongo:3
    imageID: docker.io/library/mongo@sha256:559ba7ae917a2bc61e5a6f9db0e5cf7fee2d7476e38b0510a5ddf49857dd478d
    image: ecr.ad.dice.fm/base:waitdbs-latest
    imageID: ecr.ad.dice.fm/base@sha256:629a5e1eb8106091443af3fdb0afefd2d5432b3cb49024b89e0c38267d782ebf
    image: docker.io/drillster/drone-volume-cache:latest
    imageID: docker.io/drillster/drone-volume-cache@sha256:b82e143081dfb04ba300ce7854dfcecd31e7858e1998bf89806ec74a80a78e94
    image: docker.io/fiorix/freegeoip:latest
    imageID: docker.io/fiorix/freegeoip@sha256:3882c7f82dec3171ebf4fdb3d6c66db6025fbe8a7bb20fd085d863660a37d00a
    image: docker.io/drone/placeholder:1
    imageID: docker.io/drone/placeholder@sha256:1b791b37e0589c7f1470fe0210ec0e7ef1e1de479c8f742d25942d2b4617bc07
    image: docker.io/stripemock/stripe-mock:v0.84.0
    imageID: docker.io/stripemock/stripe-mock@sha256:fd31b8ab22ea60a7fdb914431cd90172a4ee6f2ff5fa7563a32bf8529edc79b4
```

when step in drone-ci pipeline didn't startet, and it is waiting both image and image ID are set to:|
```
    image: docker.io/drone/placeholder:1
    imageID: docker.io/drone/placeholder@sha256:1b791b37e0589c7f1470fe0210ec0e7ef1e1de479c8f742d25942d2b4617bc07
```

But when image changes, but imageID stays set to placeholder, that means it got stuck

**Comment by saschagrunert** [comment]
Thank you for the input, @michalzxc!

An analysis from the logs about container `5677c0b966ab3f25ec7873732d1033c44b2cd85eca9c39d2c396ec3646c357bc`:
- **Mar 31 13:24:20**: Container creation successful, container is up and running
- **Mar 31 13:34:26**: CRI-O receives a `StopContainerRequest`, container exited with code `2`. From that point on, CRI-O reporits the correct status `CONTAINER_EXITED` to the kubelet
- **Mar 31 13:34:27**: The kubelets topology manager removes the container, CRI-O receives the `RemoveContainer` request and does its job.
- **Mar 31 14:21:04**: CRI-O receives a `ContainerStatusRequest` for the container, which does not make any sense at all.

The kubelet already got the notice around 13:34 that the container has exited and does not exist any more. CRI-O does also not return the container any more in the list responses. The kubelet should not list the container as running between 13:34 and 14:21, but this seems the case here, right?

**Comment by michalzxc** [comment]
"The kubelet should not list the container as running between 13:34 and 14:21, but this seems the case here, right?"
Yes

Do you see anything about 50be76f541ecac94a77fc3b02ee932fe0f81a728981df88740b91879c2ea4af7 in logs?
kubectl and crio were reporting 5677c0b966ab3f25ec7873732d1033c44b2cd85eca9c39d2c396ec3646c357bc for this pod, but somehow 50be76f541ecac94a77fc3b02ee932fe0f81a728981df88740b91879c2ea4af7 started some way

```
 crictl ps -a|grep    drone-gfc5j8k15wr5baokozqp
ba87b3150756d       50be76f541ecac94a77fc3b02ee932fe0f81a728981df88740b91879c2ea4af7                                      44 minutes ago       Exited              drone-gfc5j8k15wr5baokozqp   1                   3d76cb615a301
```

**Comment by Jonnymcc** [comment]
Hi, just wanted to mention that we are seeing this same exact issue. Although not using CRI-O, we are using AWS EKS.
**Summary:** step should take a few seconds, runs indefinitely, `kubectl describe` shows the container restarted and is still running, `kubectl logs` shows normal log output for the step and that it should have finished, `kubectl exec` doesn't work because the container could not be found.

**Comment by michalzxc** [comment]
I think these are 2 separate issues, because the provided fix is definitely making a big difference. Amount of stuck pipelines went down from one every 10 minutes to one per couple of days

**Comment by kasabov** [comment]
I'm also hitting this in production when a mysql replica does a CLONE and exits with 0 waiting to be restarted. That however never happens despite startup and liveness probes. Kubectl logs are unsuspecting of the long-gone container "c5b3c8d0f49e0b4b95a64f3d3465afe529b9dc6f90c2dad4644855096601bab4":

```
$ kubectl describe pod/percona-1
...
Containers:
  percona:
    Container ID:  containerd://c5b3c8d0f49e0b4b95a64f3d3465afe529b9dc6f90c2dad4644855096601bab4
    Image:         [redacted]/percona:8.0.25
    Image ID:      [redacted]/percona@sha256:f324fcbaebd5ecc235aafe3b152f11a7d72bafd0f7a8f1048a92399c6e950a5b
    Ports:         6032/TCP, 33061/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      /etc/mysql/scripts/run.sh
    State:          Running
      Started:      Fri, 03 Feb 2023 19:00:17 +0100
    Ready:          True
    Restart Count:  0
    Requests:
      memory:   8Gi
    Liveness:   exec [mysql --defaults-file=/etc/mysql/generated/monitor.credentials --execute=quit] delay=0s timeout=5s period=30s #success=1 #failure=3
    Readiness:  exec [mysql --defaults-file=/etc/mysql/generated/monitor.credentials --execute=quit] delay=0s timeout=5s period=30s #success=1 #failure=3
    Startup:    tcp-socket :6032 delay=0s timeout=1s period=30s #success=1 #failure=60
```

Unlike the cases above, I can't find this container ID on the node:
```
gke-[redacted] / # ctr -n k8s.io c ls | grep c5b3c8d0f4
gke-[redacted] / # crictl ps -a | grep c5b3c8d0f4
gke-[redacted] / #
```

I'm trying to get to a reproducible setup that I can share. Cluster version:
```
gke-[redacted] / # kubectl --kubeconfig=/var/lib/kubelet/kubeconfig version --short
I0203 22:49:21.089633  879157 cache.go:40] re-using cached key and certificate
Client Version: v1.23.14-gke.401
Server Version: v1.23.14-gke.401
```

**Comment by haircommander** [comment]
@kasabov it looks like you're using containerd, which is a separate project :) If you'd like to try cri-o out, we can see if we can help you, otherwise I recommend opening an issue in github.com/containerd/containerd
