### ISSUE TITLE
cleanupFuncs are not retried on failure, leading to resource leaks

### ISSUE THREAD

**Issue by caseydavenport** [cri-o/cri-o#4719]
**Description**

I believe this is a bug in the resource cleanup logic found here: https://github.com/cri-o/cri-o/blob/0e6266bc8b26e7f8c1b85df3af7af1dcb50ce813/internal/resourcestore/resourcestore.go#L91-L93

I found this while investigating an issue where CNI resources (specifically, IP addresses) were being leaked on a cluster using CRI-O.

In my logs, I can clearly see that the affected sandboxes are being garbage collected in that loop:

```
Cleaning up stale resource k8s_hello-world-7b8969fc6d-4zrq2_default_72e5d565-87b2-4d44-8f5a-4c4d5d7df14c_0
```

However, while executing the `cleanupFuncs`, an error occurs during the CNI DEL call, meaning the CNI plugin doesn't have an opportunity to release any state associated with the resource. Since the cleanupFuncs don't return errors, the garbage collection has no way to know that the resource hasn't been properly cleaned up, and never retries, resulting in leaked state. 

**Steps to reproduce the issue:**

It's a bit tricky to reproduce. In my environment, I believe I am seeing this due to a combination of resource contention and potentially a bug in the CNI layer. I am still investigating the root cause, so might be able to add more here later.

**Describe the results you received:**

Leaked CNI state on failed teardown. 

**Describe the results you expected:**

Retry GC on resources that fail garbage collection, no leaked state. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.18.2-18.rhaos4.5.git754d46b.el8
Version:    1.18.2-18.rhaos4.5.git754d46b.el8
GoVersion:  go1.13.4
Compiler:   gc
Platform:   linux/amd64
Linkmode:   dynamic

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Seen on a OpenShift cluster.

**Comment by caseydavenport** [comment]
@haircommander it looks like you designed this system originally here: https://github.com/cri-o/cri-o/pull/4394

Would appreciate your insight here - I'm not sure if I am missing some other mechanism by which this GC is meant to be retried.

**Comment by haircommander** [comment]
Awesome analysis, you're definitely correct that we're at risk of leaking.

An issue that we need to figure out is: how many times is a failure allowed? for instance, if the cni plugin  call fails once, can we be guaranteed that it will *ever* succeed? I don't think so, so we may want to cap the number of times a function is called, or make this an error condition that can be traced.

I will put some thought into this

**Comment by caseydavenport** [comment]
@haircommander yeah, I agree it probably doesn't make sense to try forever. Although I'm not sure what the right criteria / timeout should be. I'll think some more as well.

I think I might have had another realization for my particular case which exacerbates this issue. Specifically, the error I am seeing in the GC is this:

> level=error msg="Error while removing pod from CNI network \"multus-cni-network\": netplugin failed with no error message: context deadline exceeded"

At first I thought it must be a problem in multus, since no error message was being returned. However, I think the problem is actually the "context deadline exceeded". Specifically, [since CRIO stores the `cleanupFuncs` as part of the `runPodSandbox` call](https://github.com/cri-o/cri-o/blob/0e6266bc8b26e7f8c1b85df3af7af1dcb50ce813/server/sandbox_run_linux.go#L728), the context being passed to `networkStop` is long-since expired by the time the garbage collection happens. So, as a result, the CNI plugin is never actually invoked, and we always get a context expired error.

**Comment by caseydavenport** [comment]
One other thing I spotted.

This code runs the cleanup functions in reverse order: https://github.com/cri-o/cri-o/blob/0e6266bc8b26e7f8c1b85df3af7af1dcb50ce813/server/sandbox_run_linux.go#L317-L319

Which, I think is appropriate.

The GC doesn't seem to do that:

https://github.com/cri-o/cri-o/blob/0e6266bc8b26e7f8c1b85df3af7af1dcb50ce813/internal/resourcestore/resourcestore.go#L91

I don't think it's relevant for my situation, nor am I sure if the cleanup funcs actually are order dependent, but thought I'd raise it as it seems some care was originally made to execute them in reverse order.

**Comment by haircommander** [comment]
:facepalm: and that will be the case literally everytime this function is evoked, because it initially got there because of a cancelled context (and it's been at least four minutes after *that*)

Are you able to build a cri-o binary from scratch? I'm wondering if you can get more insight with something like this patch applied:
```
diff --git a/server/sandbox_run_linux.go b/server/sandbox_run_linux.go
index b519fb2c6..951457841 100644
--- a/server/sandbox_run_linux.go
+++ b/server/sandbox_run_linux.go
@@ -690,6 +690,9 @@ func (s *Server) runPodSandbox(ctx context.Context, req *types.RunPodSandboxRequ
 		log.Infof(ctx, "runSandbox: stopping network for sandbox %s", sb.ID())
 		if err2 := s.networkStop(ctx, sb); err2 != nil {
 			log.Errorf(ctx, "error stopping network on cleanup: %v", err2)
+			if err3 := s.networkStop(context.Background(), sb); err3 != nil {
+				log.Errorf(ctx, "error stopping network on cleanup after creating new context: %v", err3)
+			}
 		}
 	})
 	if result != nil {

```

I've left the original context there for now, but I'm not convinced it actually makes sense to keep it at all...

**Comment by caseydavenport** [comment]
I'm able to build it from scratch, but not yet sure if I can get my build installed on the cluster that I am encountering this on. I'll see what I can do.

**Comment by haircommander** [comment]
> I don't think it's relevant for my situation, nor am I sure if the cleanup funcs actually are order dependent, but thought I'd raise it as it seems some care was originally taken to execute them in reverse order.

I agree I don't think it's relevant, but I definitely think that's a bug in general. the cleanup funcs are generally independent of each other ,but I think keeping the order will help keeping operations atomic (we use name reservation to keep the resources not created simultaneously, removing the name first could cause weird situations)

I really appreciate the feedback, this is awesome!

**Comment by haircommander** [comment]
first piece to address the ordering issue:

https://github.com/cri-o/cri-o/pull/4722

this will also allow us to enhance ResourceCleaner to be smarter if we need to

**Comment by haircommander** [comment]
we have introduced the resource cleaner which solves this
