### ISSUE TITLE
Cannot start pod

### ISSUE THREAD

**Issue by mind-mind** [cri-o/cri-o#4720]
Hi,

After I create K8s using CRI-O, I can join the worker node with the master node.

But when I tried to start the pod, I got this error

Events:
  Type     Reason                  Age   From               Message
  ----     ------                  ----  ----               -------
  Normal   Scheduled               9s    default-scheduler  Successfully assigned default/rnn to w1
  Warning  FailedCreatePodSandBox  7s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = container create failed: container_linux.go:344: starting container process caused "error adding seccomp rule for syscall socket: requested action matches default action of filter"

At first, I used cri-o version 15.01, I think possibly because old version, but now I used version 1.21.0. 

I still got this error, so I don't know how to fix it.

I tried to fix it for several days, but it seems doesn't work.

So, any idea about this. Thank you.

**Comment by mind-mind** [comment]
I think cni0 doesn't create in the master node, but I'm sure how to fix it.

**Comment by haircommander** [comment]
what version of runc are you using? it seems out of date

**Comment by mind-mind** [comment]
runc version 1.0.0~rc6+dfsg1
commit: 1.0.0~rc6+dfsg1-3
spec: 1.0.1

**Comment by haircommander** [comment]
are you able to build/install runc 1.0.0-rc93?

**Comment by haircommander** [comment]
there's, big surprise, something wrong with the cri-o-runc package that I would normally recommend you install (issue with libseccomp)

**Comment by mind-mind** [comment]
I did install libseccomp. How to install runc 1.0.0-rc93?

**Comment by haircommander** [comment]
okay I figured out how to install cri-o-runc:
```
echo 'deb http://deb.debian.org/debian buster-backports main contrib non-free' >> /etc/apt/sources.list
apt update
apt -t buster-backports install libseccomp-dev
echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/Release.key | apt-key add -
apt install cri-o-runc
```

**Comment by haircommander** [comment]
(you need a newer version of libseccomp than are in buster's main repos, so you need to enable buster-backports)

**Comment by mind-mind** [comment]
Okay. For now, I did install cri-o-runc, but when I see the version of runc, it is still the same version.

**Comment by mind-mind** [comment]
Also, I still cannot start the pod.

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/68138683/113595594-6677fb80-9663-11eb-873f-9bde215ca245.png">

Or maybe should I disable IPV6 or something?

**Comment by mind-mind** [comment]
Okay, I think I can fix the version of runc. it is 1.0.0-rc93 now.

**Comment by haircommander** [comment]
are we good to close this @mind-mind ?

**Comment by mind-mind** [comment]
Actually, I didn’t succeed in this yet, but we can close until I have more questions then.
