### ISSUE TITLE
Add tracing and integrate with OpenTelemetry collector

### ISSUE THREAD

**Issue by sallyom** [cri-o/cri-o#4734]
**Description**

This issue will track the work of adding OpenTelemetry tracing to CRI-O as well as the ability to export tracing data to a back-end of choice through a vendor-agnostic OpenTelemetry Collector.  

The goal is to more easily detect and diagnose problems as well as improve performance of CRI-O. Tracing tracks and observes service requests as they flow through a system by collecting data as requests go from one service to another. It's possible, then, to pinpoint bugs and bottlenecks or other issues that can impact overall system performance. Tracing provides the story of an end-to-end request that is difficult to get otherwise.

@husky-parul (Parul) and I (@sallyom) will be implementing this. We will work with others to determine where best to add spans to collect traces. 
 
To begin with, we'll add traces for:
* podSandbox creation 
* ListContainers

 Please add in comments points in code where it would be useful to gain more information through traces.

**Comment by dashpole** [comment]
Ideally, you would just use [GRPC server integrations](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/google.golang.org/grpc/otelgrpc), rather than instrument specific methods.

**Comment by LouisStAmour** [comment]
Any interest in adding Otel Collector support for logging, such as via OTLP Logs or Fluentd? This would absolutely help in collecting logs from short-lived containers and in associating OTLP Resource data to log lines for further processing, such as splitting logs by Kubernetes namespace without needing to make K8S API calls to lookup potentially deleted container IDs?

**Comment by husky-parul** [comment]
> Ideally, you would just use [GRPC server integrations](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/google.golang.org/grpc/otelgrpc), rather than instrument specific methods.

Does it mean all GRPC will be traced w/o `trace.start` in each methods?

**Comment by haircommander** [comment]
@sallyom @husky-parul has this been finished?

**Comment by sallyom** [comment]
@haircommander this is complete, it's an experimental feature. Will the 1.23 release include the tracing option?

**Comment by haircommander** [comment]
yes it will! I think we can close this then
