### ISSUE TITLE
crio.conf file empty

### ISSUE THREAD

**Issue by aniecki** [cri-o/cri-o#4752]
**Description**
Installing the compiled cri-o program sets an empty config file. 

**Steps to reproduce the issue:**
1. git clone https://github.com/cri-o/cri-o
2. cd cri-o
3. make
4. sudo make install
5. sudo make install.config

**Describe the results you received:**
ls -l /etc/crio/crio.conf
-rw-r--r-- 1 root root 0 Apr 13 15:57 /etc/crio/crio.conf

**Describe the results you expected:**
sudo make install.config

will generate default config file
/etc/crio/crio.conf

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.21.0-dev
Version:       1.21.0-dev
GitCommit:     0d2b3e27624124a04ac2572437f6f3d5124bfac2
GitTreeState:  clean
BuildDate:     2021-04-13T10:41:22Z
GoVersion:     go1.13.8
Compiler:      gc
Platform:      linux/arm64
Linkmode:      dynamic
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by haircommander** [comment]
yes this is working as expected. we are deprecating the main crio.conf file, and instead moving towards drop-in files with logical defaults baked into the cri-o binary. You can run `crio config --default` to see all the fields, or use env vars or cli flags to only configure non-default config fields.

I think the install.config make target should probably be deprecated too.

Does all of this work for you? @aniecki

**Comment by aniecki** [comment]
> Does all of this work for you? @aniecki
Well, as I am new to the system, bit difficult to tell. But at least there is a lead... 
Spend really a day trying to figure our what went wrong... and yes, nothing wrong...

**Comment by haircommander** [comment]
sorry about that!
