### ISSUE TITLE
No v1.21.0 apt packages available

### ISSUE THREAD

**Issue by HubbeKing** [cri-o/cri-o#4756]
No packages for the v1.21.0 release are available in the apt repositories.
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/

**Comment by haircommander** [comment]
built now!

**Comment by HubbeKing** [comment]
Still missing the arm64 packages for xUbuntu_20.10... but I imagine the arm64 packages for xUbuntu_20.04 will likely work just fine?

**Comment by haircommander** [comment]
just needed to flip a switch, should be available now

**Comment by haircommander** [comment]
soon*

**Comment by haircommander** [comment]
alright, they're available now :)

**Comment by HubbeKing** [comment]
Thanks! Gonna close this out then, since the packages exist now :)
