### ISSUE TITLE
Package CRI-O in Debian and Ubuntu

### ISSUE THREAD

**Issue by jawnsy** [cri-o/cri-o#476]
[Kubernetes](https://packages.debian.org/source/sid/kubernetes) and [Docker](https://packages.debian.org/sid/docker.io) are available in Debian.

Now that the codebase is beginning to stabilize, we should supply a CRI-O package, possibly in `experimental` until we hit our 1.0 release. The [Debian Go packaging team](https://pkg-go.alioth.debian.org/) (which maintains the kubernetes packages) sounds like the best way forward.

- [ ] Package dependencies if not available (including vendored libraries)
- [ ] Perform legal/license review of codebase
- [ ] Create Debian package
- [ ] Sync package to Ubuntu

**Comment by sameo** [comment]
Sounds very good. @jawnsy Are you willing to work on that issue ?

**Comment by mrunalp** [comment]
@cyphar Do we already have packages for SUSE or should we add it to this list or track with another issue?

**Comment by jawnsy** [comment]
@mrunalp Hehe, you should've known that Aleksa would be ahead of all of us ;) https://software.opensuse.org/package/crio

If adding it upstream is needed, I suggest creating a separate issue to make it easier to track.

@sameo Yep I'll get started on this, but if you are a member of the Debian Go packaging team, you're welcome to help out too!

**Comment by mrunalp** [comment]
Sweet :)
Let us add a link to the releases on different distros in the README.

**Comment by rhatdan** [comment]
We had better move forward with the rename of the package and the daemon before we get to far with packaging.

I suggest 
package name crio.
Daemon criod
Client cri

I can prepare a patch for this change if it is agreed upon.

**Comment by rhatdan** [comment]
@lsm5 has done most of this now.  @mrunalp  I think we can close this

**Comment by lsm5** [comment]
PPA for ubuntu 16.04.2 and 17.04 is available at https://launchpad.net/~projectatomic/+archive/ubuntu/ppa . I'm gonna need help for putting this in debian itself, primarily because I don't have enough motivation to un-vendor dependencies :)

**Comment by lsm5** [comment]
Also, dh-make-golang (including the latest upstream version) simply crashed when I tried to package this up.

**Comment by Bregor** [comment]
@lsm5 do you know anything about the fate of the ppa?
The last build was two weeks ago, and no any releases of 1.8-branch for xenial.

Maybe any help needed in supporting repository?

**Comment by runcom** [comment]
@lsm5 ^^

**Comment by lsm5** [comment]
@Bregor ah sorry, i was working on this last friday, but got distracted, I'll update this. btw, help is always appreciated, so let me know if you're interested :)

**Comment by Bregor** [comment]
@lsm5 great!
I have some experience with PPA support and have read Debian Maintainer Guide many times ;)
So, if I can help, I'm in.

**Comment by lsm5** [comment]
alright, i'll do this 1.8.1 bump and send you the sources for it once ready. Then we can work on setting you up with this.

**Comment by Bregor** [comment]
Awesome, thanks.

**Comment by lsm5** [comment]
v1.8.1 should be available on both xenial and zesty. I also got rid of the ostree dependency for cri-o and skopeo

**Comment by keithdadkins** [comment]
Would love a Debian apt package. I tried to use the Ubuntu PPA, but no joy (debian 9).

**Comment by FranklinYu** [comment]
Since CRI-O hasn’t been packaged in Debian, shall we re-open this bug?

**Comment by haircommander** [comment]
we have support for debian and ubuntu in our OBS builds now thanks to @lsm5 
https://build.opensuse.org/package/show/devel:kubic:libcontainers:testing/cri-o-1.16
while it's not the main Debian packages, I think they are sufficient. Please reopen if you disagree.
