### ISSUE TITLE
1.21.0 installed config is empty

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#4770]
This was intentional, but it is not optimal.

For 1.21.0, we changed the `crio config` command to *only* print fields that are different than the default. This allows config migration to be easier, and config changes as well.

However, now running `make install.config` (which all packaged solutions do, as well as our recommendation for installation from source) installs an empty file--it's all the default!

This is sub-par--often users want to use the default config as a way to see the available options.

I take the blame for this one, I guided the solution to https://github.com/cri-o/cri-o/issues/4506 without checking the reprocussions and making sure all stakeholders were okay with the fix.

The good news is: we have another good first issue! 

Here are three proposed pieces:
- `crio config` should print *all the fields*, with the default ones commented out, instead of omitted. This will be used to populate the default configuration
- `crio config --all` should print *all the fields*, with both default and non-default commented out
- `crio config --verbose` should print only the non-default fields. This will be used for generating drop-in files

**Comment by fidencio** [comment]
kata-containers CI (from our repo) is failing and may pretty much be related to this one.
It happens the really sub-optimal way come configurations are changed on the kata-containers side is by `sed ...` the default value (now, not found anymore).

I'll open an issue on kata-containers side and link it here on Monday.

**Comment by saschagrunert** [comment]
Yep, printing the defaults commented-out should be a good solution around it. The static binary bundles are affected by that change, too.

/help

**Comment by wgahnagl** [comment]
I'm working on this!
