### ISSUE TITLE
overlayfs: unrecognized mount option "volatile" or missing value

### ISSUE THREAD

**Issue by aniecki** [cri-o/cri-o#4773]
**Description**
Every time I restart crio (sudo systemctl restart crio), it logs the error info in dmesg

overlayfs: unrecognized mount option "volatile" or missing value

**Steps to reproduce the issue:**
1.sudo systemctl daemon-reload
2.sudo systemctl restart crio
3.

**Describe the results you received:**
error overlayfs in dmesg

**Describe the results you expected:**
no error in dmesg

**Additional information you deem important (e.g. issue happens only occasionally):**
when restarting crio service
**Output of `crio --version`:**

```
crio --version
crio version 1.21.0
Version:       1.21.0
GitCommit:     bc1ef35a932acc2f6f3b6d3eb19a4f68aa9423f6
GitTreeState:  clean
BuildDate:     2021-04-14T23:19:50Z
GoVersion:     go1.15.2
Compiler:      gc
Platform:      linux/arm64
Linkmode:      dynamic

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
uname -a
Linux metal 5.4.0-1034-raspi #37-Ubuntu SMP PREEMPT Mon Apr 12 23:14:49 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

**Comment by aniecki** [comment]
This seems to be problem, related to crun, Also could be as per design, will test the behaviour bit more....
https://github.com/containers/crun/issues/649

**Comment by giuseppe** [comment]
It is by design as it is a check performed at runtime to verify whether the `volatile` flag is supported by overlay.

More information about "volatile": https://www.kernel.org/doc/html/latest/filesystems/overlayfs.html?highlight=overlayfs#volatile-mount

**Comment by aniecki** [comment]
Closing now, due to the explanation above.
