### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by DavidHaltinner** [cri-o/cri-o#4777]
**Description**
I have had about a half dozen crashes of cri-o in the last few months, on a few different versions.
Crio crashes with a "panic: runtime error: index out of range" and a stack trace which I will paste below.
I am utilizing OKD, 4.7 currently, but issue occured under 4.6 as well, maybe 4.5 but my memory is bad.
Current crio is 1.20.0.
There does not seem to anything that I can see that triggers it, it appears random. In today's issue, directly before, podman removes an image, and hyperkube "Failed to create an existing container".

**Steps to reproduce the issue:**
1. Run OKD using crio
2. Wait? No determinable trigger to me
3.

**Describe the results you received:**
No panics should occur.

**Describe the results you expected:**
Crio to continue to run normally.

**Additional information you deem important (e.g. issue happens only occasionally):**
The crio service logs from the journal are being attached from the crash.
[crio.txt](https://github.com/cri-o/cri-o/files/6336851/crio.txt)

**Output of `crio --version`:**

```
INFO[0000] Starting CRI-O, version: 1.20.0, git: d388528dbed26b93c5bc1c89623607a1e597aa57(clean) 
crio version 1.20.0
Version:       1.20.0
GitCommit:     d388528dbed26b93c5bc1c89623607a1e597aa57
GitTreeState:  clean
BuildDate:     2020-12-11T17:42:02Z
GoVersion:     go1.15.5
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtual machines running on Nutanix AOS.

**Comment by saschagrunert** [comment]
This looks like a race from a first rough guess. The crash happens on the `copyImage` operation:
https://github.com/cri-o/cri-o/blob/d388528dbed26b93c5bc1c89623607a1e597aa57/vendor/github.com/containers/storage/images.go#L191

Since it is an index out of bounds we can think of a changed `r.Images` during the iteration, which should be usually covered by a file lock. :thinking:

**Comment by DavidHaltinner** [comment]
> This looks like a race from a first rough guess. The crash happens on the `copyImage` operation:
> 
> https://github.com/cri-o/cri-o/blob/d388528dbed26b93c5bc1c89623607a1e597aa57/vendor/github.com/containers/storage/images.go#L191
> 
> Since it is an index out of bounds we can think of a changed `r.images` during the iteration, which should be usually covered by a file lock. thinking

Just before, podman removed an image it stated... (In this case a customized graylog image I have). Related? I dont know the internal mechanics enough to know the involvement of crio/podman in something like this:
Apr 19 08:06:34 okd-prod-cmpt04.rgl.com podman[3091098]: 2021-04-19 08:06:34.307610175 -0500 CDT m=+249.235712493 image remove a6d081b7d335d71b74c7084079956b1fadb9e2e3edbe12d686756bc368f952fc image-registry.openshift-image-registry.svc:5000/graylog/graylog-custom@sha256:2b34cb10953329487e00b9cdb20a43f99b2db5decc2268326509714899e39bf8

**Comment by haircommander** [comment]
@vrothberg  @QiWang19 @umohnani8 PTAL

**Comment by vrothberg** [comment]
Please open an issue at c/storage.

**Comment by DavidHaltinner** [comment]
I added the new log in the issue I opened at c/storage, but adding here as well.

Had a crash of crio over the weekend. This one also proceeded by podman removing an image.

[crio2.txt](https://github.com/cri-o/cri-o/files/6451990/crio2.txt)

**Comment by DavidHaltinner** [comment]
They issued a fix on the c/storage side. It looks like the cri-o team has started using dependabot to pull updates from c/storage. Would we expect for the next bugfix release to pull that over from c/storage automatically?

**Comment by haircommander** [comment]
Once there is a release cut for c/storage it would be pulled in to the main branch, which then would end up in 1.22. I think it's realistic to expect this to be backported to an earlier branch too

**Comment by haircommander** [comment]
https://github.com/cri-o/cri-o/pull/4932 for 1.21
https://github.com/cri-o/cri-o/pull/4933 for 1.20

**Comment by haircommander** [comment]
should have done this earlier, but here's a c/storage fix in 1.19, revendor to follow https://github.com/containers/storage/pull/931

**Comment by DavidHaltinner** [comment]
Looks like the commit for 1.20 made it into the 1.20.3 release. OKD also pulled in 1.20.3 in it's release this last weekend. I upgraded my test cluster yesterday morning, and will upgrade the production one in about a week.

However, I hadnt had a panic occur since May, as of yet. Should we consider the issue completed since it made it to release now?

**Comment by haircommander** [comment]
yes I believe so! I'm glad it's working :)
