### ISSUE TITLE
seccomp is not enabled in your kernel, cannot run with a profile

### ISSUE THREAD

**Issue by baoho1106** [cri-o/cri-o#4786]
,
**Description**

I am currently using the latest kubernetes 1.21.

After updating to cri-o v1.21 I I cannot start up any pods.  The output of the describe pod is "Failed to create pod sandbox: rpc error: code = Unknown desc = seccomp is not enabled in your kernel, cannot run with a profile"

I was working previously on  1.18 and it was working fine.  I've then upgraded to v1.19, but there was an update on the seccomp for kubernetes 1.19 PSP so I had to add in the crio.conf seccomp_profile = "/usr/share/containers/seccomp.json" and that remove the above error. 
However in 1.21 the crio.conf was depreciated and I use the cmd crio --seccomp-profile =  "/usr/share/containers/seccomp.json" or crio -c "/home/foo/config/seccomp.conf"  to store the values?  Not sure if I am doing it correctly or not, but it is giving me the same error. If I revert back to 1.20 the pods can be created with the seccomp_profile that I use.

**Steps to reproduce the issue:**
1. git clone https://github.com/cri-o/cri-o
2. cd cri-o
3. make
4. sudo make install
5. crio --seccomp-profile =  "/usr/share/containers/seccomp.json" 

**Describe the results you received:**

Pods having status ContainerCreating with a warning
Failed to create pod sandbox: rpc error: code = Unknown desc = seccomp is not enabled in your kernel, cannot run with a profile

**Describe the results you expected:**

Pods should have status RUNNING

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.21.0
Version:       1.21.0
GitCommit:     bc1ef35a932acc2f6f3b6d3eb19a4f68aa9423f6
GitTreeState:  clean
BuildDate:     2021-04-21T15:28:36Z
GoVersion:     go1.14.7
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox
Oracle Linux Server release 8.3
NAME="Oracle Linux Server"
VERSION="8.3"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.3"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.3"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:3:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.3
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.3
Red Hat Enterprise Linux release 8.3 (Ootpa)
Oracle Linux Server release 8.3

**Comment by fidencio** [comment]
Are you building CRI-O yourself? Please, ensure you have libseccomp-devel installed in your environment and give it another try, as this is quite similar to https://github.com/cri-o/cri-o/issues/4627#issuecomment-795965178

**Comment by baoho1106** [comment]
Yes I am building the CRI-O.

I have that installed already.  Here is the list of stuff I installed

`sudo yum module -y install go-toolset

sudo  yum install -y \
  containers-common \
  device-mapper-devel \
  git \
  make \
  glib2-devel \
  glibc-devel \
  glibc-static \
  runc \
  libassuan \
  libassuan-devel \
  libgpg-error \
  libseccomp \
  libseccomp-devel \
  libselinux \
  pkgconf-pkg-config 
`

**Comment by baoho1106** [comment]
Here is my whole  kubectl describe
```
Name:           hello-node-7567d9fdc9-8bftd
Namespace:      default
Priority:       0
Node:           vmkubernetes01/10.100.92.103
Start Time:     Wed, 21 Apr 2021 17:25:06 -0400
Labels:         app=hello-node
                pod-template-hash=7567d9fdc9
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/hello-node-7567d9fdc9
Containers:
  echoserver:
    Container ID:
    Image:          k8s.gcr.io/echoserver:1.4
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fng5g (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-fng5g:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                     From               Message
  ----     ------                  ----                    ----               -------
  Normal   Scheduled               9m6s                    default-scheduler  Successfully assigned default/hello-node-7567d9fdc9-8bftd to vmkubernetes01
  Warning  FailedCreatePodSandBox  2m52s (x26 over 8m59s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = setup seccomp: from field: seccomp is not enabled, cannot run with a profile
```

**Comment by baoho1106** [comment]
Also will there be a problem if I use crio v 1.20 with kubernetes 1.21 because that seems to work.

**Comment by fidencio** [comment]
@haircommander, mind to chime in? :-)

**Comment by saschagrunert** [comment]
@baoho1106 what's the output of 
```
ldd bin/crio
```

Is it possible for you to share the debug logs of CRI-O (`-l debug`) while creating the container?

**Comment by saschagrunert** [comment]
@baoho1106 can you please try the same again with the PR https://github.com/cri-o/cri-o/pull/4789?

**Comment by baoho1106** [comment]
After applying the changes in PR #4789 the pods were able to start up.  Thank you for the help! I will close this PR now :)
