### ISSUE TITLE
Support Target NamespaceMode 

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#4790]
We have managed to avoid processing Target NamespaceMode because there are no CRI tests nor k8s conformance tests that rely on it. However, we really should be supporting it (ephemeral containers are still alpha and seem to be the major consumer, but it will go beta one day)

This is a tracking issue for this work

**Comment by haircommander** [comment]
it seems beta ephemeral containers [slipped 1.22](https://github.com/kubernetes/website/pull/27988) so I am going to push this to 1.23

**Comment by haircommander** [comment]
also, to do this we'll need to revive https://github.com/cri-o/cri-o/pull/3910

**Comment by haircommander** [comment]
I opened a PR to add support. @paulnivin do y'all have any interest in trying it out and making sure it works for you?

**Comment by paulnivin** [comment]
@haircommander Sorry, I missed the updates here. We can give the code a spin. Thanks for adding
