### ISSUE TITLE
ulimit values are not inherited to runtimeVM

### ISSUE THREAD

**Issue by snir911** [cri-o/cri-o#4807]
**Description**

According to documentation if no ulimit values were set _"settings will be inherited from the CRI-O daemon"_, however, it seems to be wrong for some runtimes such as kata-runtime, where ulimits are not inherited from CRI-O.
This may also cause application failures if nofile value is to large, [see this issue](https://github.com/kata-containers/runtime/issues/2597).

**Steps to reproduce the issue:**
1.[ install kata](https://github.com/kata-containers/documentation/tree/master/install)
2. run some deployment with kata as runtime and without
3. check for differences in ulimit -a

([alternatively see](https://github.com/kata-containers/runtime/issues/2597))

**Describe the results you received:**
native runtime:
```
$ kubectl exec pod/fedora -- ulimit -n
1048576
```

kata runtime:
```
$ kubectl exec pod/fedora-kata -- ulimit -n
1073741816
```

**Describe the results you expected:**
same value

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.21.0
Version:       1.21.0
GitCommit:     40d6ec0f56215417267f5297c99bdab3cc36827c
GitTreeState:  clean
BuildDate:     2021-04-26T13:51:41Z
GoVersion:     go1.14.15
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by haircommander** [comment]
by "from the cri-o daemon" I believe it means our `default_ulimits` field in crio.conf . I am not so sure we want to give every container the limits cri-o has.

**Comment by snir911** [comment]
@haircommander sorry, i trimmed this quote so it might be unclear, it's mentioned also in crio.conf and the full sentence says _"If nothing is set here, settings will be inherited from the CRI-O daemon"_ where "here" refers to default_ulimits
(I think it was introduced with 1a01ca7251e9e91af3fd4e0593a849015363f520 and stayed since)
Do you think it would make more sense to just remove the [ClearProcessRlimits](https://github.com/cri-o/cri-o/blob/d3dbaec060e33870e5cb5c3f7ec4207837804b00/pkg/sandbox/infra.go#L29) so that the default value set by runtime-tools will be used?

**Comment by haircommander** [comment]
ah interesting. I think calling ClearProcessRlimits makes sense. We may also want to update that documentation

**Comment by snir911** [comment]
@haircommander, hi, pushed another version
(BTW, third option might be, explicitly inherit limits only when it's runtimeVM type)

**Comment by fidencio** [comment]
@snir911, rather than explicitly inheriting the limits only when using the runtimeVM type, I'd rather go with your proposal on the kata-containers side (ref: https://github.com/kata-containers/kata-containers/pull/1778).

**Comment by snir911** [comment]
@fidencio i believe some solution should be done also in crio in any case, so at least it will be somewhat consistent between different runtimes
