### ISSUE TITLE
error: creating cgroup directory with version v1.21.0

### ISSUE THREAD

**Issue by thanos1983** [cri-o/cri-o#4833]
**Description**

The new crio-socket v1.21.0 it is failing to launch the node(s) with the error:

```bash
May 03 17:08:58 <nodename> crio[10050]: time="2021-05-03 17:08:58.586270644+02:00" level=error msg="Container creation error: creating cgroup directory `/sys/fs/cgroup/net_prio,net_cls/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podb6c7cb425bef80bb327583bad4f8a302.slice/crio-e843b741b52c8e2699437978276a0fff1218b0c7d4151047072bb916e27ef7e7.scope`: No such file or directory\n" id=b13f1178-3dd4-407d-ba52-10e9c3719e03 name=/runtime.v1alpha2.RuntimeService/RunPodSandbox
```

I tried to deploy with packages versions:

v1.20.6 and v1.21.0

**Steps to reproduce the issue:**
1. Start a new Master node with the latest version of CRI-O socker v1.21.0 and kubernetes packages version v1.21.0.
2. Try to bring up the node and observer the error logs

**Describe the results you received:**

The node is not coming up.

**Describe the results you expected:**

Expected the node to start without this error.

**Additional information you deem important (e.g. issue happens only occasionally):**

The directory of the node is formatted to overlay, the socket is up and running without any problems.

**Output of `crio --version`:**

```bash
$ crio --version
crio version 1.21.0
Version:       1.21.0
GitCommit:     bc1ef35a932acc2f6f3b6d3eb19a4f68aa9423f6
GitTreeState:  dirty
BuildDate:     1980-01-01T00:00:00Z
GoVersion:     go1.15.7
Compiler:      gc
Platform:      linux/amd64
Linkmode:      static
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The node is RH 7.9. Sample:

```bash
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.9 (Maipo)
```

Other information related to cgroup:

```bash
$ ls -la /sys/fs/cgroup
total 0
drwxr-xr-x. 13 root root 340 Apr  6 07:22 .
drwxr-xr-x.  9 root root   0 Apr 28 13:38 ..
drwxr-xr-x.  5 root root   0 Apr  6 07:22 blkio
lrwxrwxrwx.  1 root root  11 Apr  6 07:22 cpu -> cpu,cpuacct
drwxr-xr-x.  5 root root   0 Apr  6 07:22 cpu,cpuacct
lrwxrwxrwx.  1 root root  11 Apr  6 07:22 cpuacct -> cpu,cpuacct
drwxr-xr-x.  4 root root   0 Apr  6 07:22 cpuset
drwxr-xr-x.  5 root root   0 Apr  6 07:22 devices
drwxr-xr-x.  4 root root   0 Apr  6 07:22 freezer
drwxr-xr-x.  4 root root   0 Apr  6 07:22 hugetlb
drwxr-xr-x.  5 root root   0 Apr  6 07:22 memory
lrwxrwxrwx.  1 root root  16 Apr  6 07:22 net_cls -> net_cls,net_prio
drwxr-xr-x.  4 root root   0 Apr  6 07:22 net_cls,net_prio
lrwxrwxrwx.  1 root root  16 Apr  6 07:22 net_prio -> net_cls,net_prio
drwxr-xr-x.  4 root root   0 Apr  6 07:22 perf_event
drwxr-xr-x.  5 root root   0 Apr  6 07:22 pids
drwxr-xr-x.  5 root root   0 Apr  6 07:22 systemd

$ findmnt -R /sys/fs/cgroup
TARGET                            SOURCE FSTYPE OPTIONS
/sys/fs/cgroup                    tmpfs  tmpfs  ro,nosuid,nodev,noexec,seclabel,mode=755
|-/sys/fs/cgroup/systemd          cgroup cgroup rw,nosuid,nodev,noexec,relatime,seclabel,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd
|-/sys/fs/cgroup/perf_event       cgroup cgroup rw,nosuid,nodev,noexec,relatime,seclabel,perf_event
|-/sys/fs/cgroup/cpu,cpuacct      cgroup cgroup rw,nosuid,nodev,noexec,relatime,seclabel,cpuacct,cpu
|-/sys/fs/cgroup/blkio            cgroup cgroup rw,nosuid,nodev,noexec,relatime,seclabel,blkio
|-/sys/fs/cgroup/memory           cgroup cgroup rw,nosuid,nodev,noexec,relatime,seclabel,memory
|-/sys/fs/cgroup/pids             cgroup cgroup rw,nosuid,nodev,noexec,relatime,seclabel,pids
|-/sys/fs/cgroup/net_cls,net_prio cgroup cgroup rw,nosuid,nodev,noexec,relatime,seclabel,net_prio,net_cls
|-/sys/fs/cgroup/freezer          cgroup cgroup rw,nosuid,nodev,noexec,relatime,seclabel,freezer
|-/sys/fs/cgroup/hugetlb          cgroup cgroup rw,nosuid,nodev,noexec,relatime,seclabel,hugetlb
|-/sys/fs/cgroup/devices          cgroup cgroup rw,nosuid,nodev,noexec,relatime,seclabel,devices
`-/sys/fs/cgroup/cpuset           cgroup cgroup rw,nosuid,nodev,noexec,relatime,seclabel,cpuset
```

**Comment by haircommander** [comment]
@kolyshkin @giuseppe PTAL

**Comment by giuseppe** [comment]
the error seems to come from crun.

Have you configured CRI-O to use crun instead of runc?  What version?

The error should be fixed in the last release of crun.

**Comment by thanos1983** [comment]
> the error seems to come from crun.
> 
> Have you configured CRI-O to use crun instead of runc? What version?
> 
> The error should be fixed in the last release of crun.

Hello @giuseppe,

Thank you for your time. I have this configuration:

```bash
$ cat /etc/crio/crio.conf.d/10-crun.conf
[crio.runtime]
default_runtime = "crun"

[crio.runtime.runtimes.crun]
allowed_annotations = [
    "io.containers.trace-syscall",
]
```

Has something changed?

Looking forward to your reply.

BR / Thanos

**Comment by saschagrunert** [comment]
We ship crun as default for the static binary bundle. I think we have to cherry-pick the latest bump and alrease a new v1.21 patch.

**Comment by saschagrunert** [comment]
Fix in https://github.com/cri-o/cri-o/pull/4835

**Comment by thanos1983** [comment]
> We ship crun as default for the static binary bundle. I think we have to cherry-pick the latest bump and alrease a new v1.21 patch.

I downgraded to socket 1.20.2 and I see:

```bash
$ crun -V
crun version 0.15
commit: 56ca95e61639510c7dbd39ff512f80f626404969
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
```

I will update again one node to 1.21.0 and see if the problem is resolved.

The fix that you applied is expected to be included in the new release? If so do you have an estimate of release?

Thanks in advance for your time and effort.

BR / Thanos

**Comment by saschagrunert** [comment]
@thanos1983 yes it will be part of the next 1.21.x release, but I do not have an estimate yet. We can cut releases fairly ad-hoc :)
