### ISSUE TITLE
Feature Request: CRI-O support for Windows Kubernetes nodes

### ISSUE THREAD

**Issue by khatrig** [cri-o/cri-o#4842]
**Description**

Kubernetes and most cloud Kubernetes providers currently support windows nodes. It'd be great if crio can support windows as well so there are more container runtime options to choose from when dealing with heterogeneous clusters.

**Comment by haircommander** [comment]
Thanks for opening the issue! This will serve as a good tracking issue. We will definitely need help from the community if we want to implement this
