### ISSUE TITLE
Does it still support ubuntu16.04? 

### ISSUE THREAD

**Issue by ccnankai** [cri-o/cri-o#4978]
Hi,
I encountered a lot of problems in the process of building from source code. Are there any pre-compiled binaries available?

**Comment by ccnankai** [comment]
@saschagrunert 
That is to say, if I want to use ubuntu16.04, I can only build  CRIO from the source code, and there is no installation package that can be used directly, right?

**Comment by haircommander** [comment]
what version are you looking for? The first option @saschagrunert posted was to install using apt

**Comment by ccnankai** [comment]
@haircommander 
ubuntu16.04 can not use apt to install crio, can only use to build from source code, thank you very much.

**Comment by saschagrunert** [comment]
@ccnankai the static binary bundle contains a `Makefile` which should work on Ubuntu 16.04, too.
