### ISSUE TITLE
container_runtime_crio_image_* metrics may have excessive cardinality

### ISSUE THREAD

**Issue by simonpasquier** [cri-o/cri-o#4982]
**Description**

Since #2912, CRI-O exposes metrics about image pulls and layers:
* container_runtime_crio_image_pulls_by_digest
* container_runtime_crio_image_layer_reuse
* container_runtime_crio_image_pulls_by_name
* container_runtime_crio_image_pulls_successes

These metrics can have very high cardinality, especially because of labels such as `digest`, `size` and `name`. For some of the OpenShift CI clusters, we've seen that these metrics account for more than 50% of all metrics collected by Prometheus (e.g. about 5M series out of 10M).

I can understand how the granularity is useful for troubleshooting and debugging but labels with such cardinality can be problematic since it increases the memory usage of Prometheus (as stated in the [Prometheus docs](https://prometheus.io/docs/practices/instrumentation/#do-not-overuse-labels)). I would rather see histogram metrics that allow to view the distribution of values (e.g. `container_runtime_crio_image_pulls_bucket`).

**Steps to reproduce the issue:**
1. Run many container images with different digest IDs and many layers 
2.
3.

**Describe the results you received:**

The number of metrics exposed by CRI-O increases by a lot. 

**Describe the results you expected:**

No to little increase in the number of metrics collected.

**Additional information you deem important (e.g. issue happens only occasionally):**

We've decided for now that the cluster monitoring operator will configure Prometheus to [drop](https://github.com/openshift/cluster-monitoring-operator/blob/3c0353e0c3049ec755c9aff0aeb0b091f6d7f0a9/assets/control-plane/service-monitor-kubelet.yaml#L96-L100) these metrics to avoid excessive memory usage.

**Output of `crio --version`:**

```
1.21.1-3.rhaos4.8.gite1bc46b.el8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS but valid for other environments too.

**Comment by saschagrunert** [comment]
Thank you for the report @simonpasquier. I think throttling the image metrics would make sense. Right now, we update every metric once per second:

https://github.com/cri-o/cri-o/blob/f44811cd26500f0db7cc611ec2f6d47a8966cdf1/server/image_pull.go#L242

Do you think that some metrics are not helpful at all or should we just limit them? 

I can also imagine that we add a configuration option to opt-in to certain metrics, where everything is enabled by default.

**Comment by simonpasquier** [comment]
I think that an opt-in/opt-out configuration option would totally make sense.

Looking at the example you provide, the `size` label for `container_runtime_crio_image_pulls_by_digest` is clearly unbounded + it's duplicating the value of the metric. I'm not sure to understand exactly how CRI-O records the metric: is it tracking the size for every layer for every image that has ever been pulled?

As I said earlier, I would rather see an histogram metric like:

```
container_runtime_crio_image_layer_size_bytes_bucket{le="1024"} 12
container_runtime_crio_image_layer_size_bytes_bucket{le="32768"} 45
container_runtime_crio_image_layer_size_bytes_bucket{le="1048576"} 56
...
container_runtime_crio_image_layer_size_bytes_bucket{le="1073741824"} 67
container_runtime_crio_image_layer_size_bytes_bucket{le="+Inf"} 68
container_runtime_crio_image_layer_size_bytes_sum 1.987e+09
container_runtime_crio_image_layer_size_bytes_count 68
```
Which would allow to ask questions such as "what's the 90th-percentile size across all pulled layers?".

Regarding whether the other metrics are useful or not, I don't know enough about CRI-O to judge but from a general standpoint, the primary goal of metrics is for alerting and understanding usage and it seems to me that the `container_runtime_crio_image_*` metrics are more targeted towards forensics and auditing.

**Comment by saschagrunert** [comment]
> I think that an opt-in/opt-out configuration option would totally make sense.

I agree, let's do that.


> Looking at the example you provide, the `size` label for `container_runtime_crio_image_pulls_by_digest` is clearly unbounded + it's duplicating the value of the metric. I'm not sure to understand exactly how CRI-O records the metric: is it tracking the size for every layer for every image that has ever been pulled?

If we assume that images get removed from nodes, then in case of:

```
> sudo crictl pull k8s.gcr.io/build-image/kube-cross:v1.16.0-1
> sudo crictl rmi k8s.gcr.io/build-image/kube-cross:v1.16.0-1
> sudo crictl pull k8s.gcr.io/build-image/kube-cross:v1.16.0-1
```

The metrics for a digest like `3381b1c1e8e00f9b8dbab5f0a00915b5dc9257e26a864e82f865982396b17a9b` would double the value:

```
container_runtime_crio_image_pulls_by_digest{digest="sha256:3381b1c1e8e00f9b8dbab5f0a00915b5dc9257e26a864e82f865982396b17a9b",mediatype="application/vnd.docker.image.rootfs.diff.tar.gzip",name="k8s.gcr.io/build-image/kube-cross:v1.16.0-1",size="221777959"} 4.43555918e+08
```

> As I said earlier, I would rather see an histogram metric like:
> …
> Which would allow to ask questions such as "what's the 90th-percentile size across all pulled layers?".

Sounds like a good idea to add! :)

**Comment by saschagrunert** [comment]
@simonpasquier may I ask you to give #5059 and #5061 a look?

**Comment by saschagrunert** [comment]
This is done
