### ISSUE TITLE
how to pass custom environment variables 

### ISSUE THREAD

**Issue by ccnankai** [cri-o/cri-o#4988]
hi, 
1. When using the critcl command to create pods and containers, how to pass custom environment variables into the container.
Is it now supported to pass  environment variables via crictl? Just like the docker -e parameter works.

2. Where is the description of each item in container-config.json  pod-config.json? I want more configuration options, but I don't know what the optional keywords are. Is it possible to configure custom environment variables in the container-config.json or pod-config.json file?

**Comment by haircommander** [comment]
you can use the `envs` field in the container config: https://github.com/kubernetes/cri-api/blob/bdd07c8ff51faf13238c2da120aed933546eab4d/pkg/apis/runtime/v1/api.proto#L792

the container/pod config jsons are the json format for the CRI API, the docs for which you can find here https://github.com/kubernetes/cri-api/blob/master/pkg/apis/runtime/v1/api.proto (specifically PodSandboxConfig and ContainerConfig)

**Comment by ccnankai** [comment]
@haircommander 
This file is so helpful.     Thank you very much.

**Comment by ckruegerkpmg** [comment]
```
envs:
  - Key: "ZZZZ"
    Value: "ZZZ"
```
