### ISSUE TITLE
kubectl 1.21 and crio fail to follow stream_idle_timeout #5563

### ISSUE THREAD

**Issue by aojea** [cri-o/cri-o#4995]
#### Description

Clone of https://github.com/containerd/containerd/issues/5563

#### Steps to reproduce the issue:

1. Create a cluster with crio.
2. Use a version 1.21 kubectl
3. Exec into a pod and see that it will not follow the stream_idle_timeout limit
4. Describe the results you received:

Did not get kicked out.

#### Describe the results you expected:

kicked out after the stream_idle_timeout time.

#### Any other relevant information (runC version, CRI configuration, OS/Kernel version, etc.):

I've created an issue with Kubernetes about this issue as well. kubernetes/kubernetes#102569

**Comment by saschagrunert** [comment]
Thank you for reporting this issue! Looks like we correctly pass the configuration option to the streaming server, so the bug must be somewhere in the vendored code.

**Comment by aojea** [comment]
> Thank you for reporting this issue! Looks like we correctly pass the configuration option to the streaming server, so the bug must be somewhere in the vendored code.

/assign

I'm working on it, just only updating one of the issues to have all the information in the same place
https://github.com/containerd/containerd/issues/5563#issuecomment-861064648

**Comment by haircommander** [comment]
work has stalled upstream: https://github.com/moby/spdystream/pull/86

**Comment by terinjokes** [comment]
Taking a look at #6699 and I've noticed that `stream_idle_timeout` doesn't seem to take effect either, even with no kubectl running to send pings. Can this get reopened?

**Comment by saschagrunert** [comment]
CRI-O v1.21 is out of support since quite some time. Do we need to keep this issue open?
