### ISSUE TITLE
Verbose systemd logs for mount succeeded

### ISSUE THREAD

**Issue by msschl** [cri-o/cri-o#5064]
**Description**

```
Jul 09 12:15:42 lxkubenode02 systemd[1]: run-runc-bd72a510b8f38c6337dfa0298f9cc6969b355fa3da4770143244f74d46fb52f8-runc.4po0xy.mount: Succeeded.
Jul 09 12:15:42 lxkubenode02 systemd[663855]: run-runc-bd72a510b8f38c6337dfa0298f9cc6969b355fa3da4770143244f74d46fb52f8-runc.4po0xy.mount: Succeeded.
Jul 09 12:15:44 lxkubenode02 systemd[1]: run-runc-b611a3bdf936d64e8983e045c27cd142949b6a54e772846f7750ca7ced35e5ea-runc.u9nGFW.mount: Succeeded.
Jul 09 12:15:44 lxkubenode02 systemd[663855]: run-runc-b611a3bdf936d64e8983e045c27cd142949b6a54e772846f7750ca7ced35e5ea-runc.u9nGFW.mount: Succeeded.
Jul 09 12:15:46 lxkubenode02 systemd[663855]: run-runc-ce7517c93e09e8f18ed5483cce138483781a7d8d34322bb1543c2163694772ee-runc.bjm8Fp.mount: Succeeded.
Jul 09 12:15:46 lxkubenode02 systemd[1]: run-runc-ce7517c93e09e8f18ed5483cce138483781a7d8d34322bb1543c2163694772ee-runc.bjm8Fp.mount: Succeeded.
Jul 09 12:15:49 lxkubenode02 systemd[1]: run-runc-b611a3bdf936d64e8983e045c27cd142949b6a54e772846f7750ca7ced35e5ea-runc.rv3k3B.mount: Succeeded.
Jul 09 12:15:49 lxkubenode02 systemd[663855]: run-runc-b611a3bdf936d64e8983e045c27cd142949b6a54e772846f7750ca7ced35e5ea-runc.rv3k3B.mount: Succeeded.
Jul 09 12:15:52 lxkubenode02 systemd[663855]: run-runc-bd72a510b8f38c6337dfa0298f9cc6969b355fa3da4770143244f74d46fb52f8-runc.pnqjUW.mount: Succeeded.
Jul 09 12:15:52 lxkubenode02 systemd[1]: run-runc-bd72a510b8f38c6337dfa0298f9cc6969b355fa3da4770143244f74d46fb52f8-runc.pnqjUW.mount: Succeeded.
```

It looks like a [issue docker had once](https://github.com/docker/for-linux/issues/679), and is related to healthchecks.

**Output of `crio --version`:**

```
$ crio --version
INFO[0000] Starting CRI-O, version: 1.20.3, git: 50065140109e8dc4b8fd6dc5d2b587e5cb7ed79d(clean)
crio version 1.20.3
Version:       1.20.3
GitCommit:     50065140109e8dc4b8fd6dc5d2b587e5cb7ed79d
GitTreeState:  clean
BuildDate:     2021-06-03T20:25:45Z
GoVersion:     go1.15.2
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- K8s cluster deployed with kubeadm on ubuntu 20.04 vms

**Comment by saschagrunert** [comment]
Thank you for submitting the issue @msschl! I think we do not have influence on this behavior from a CRI-O perspective, so it's probably more a systemd related issue.

**Comment by msschl** [comment]
Replay from @poettering [systemd/systemd#20184](https://github.com/systemd/systemd/issues/20184#issuecomment-889155159)

> 
> seems pretty broken in docker to leak all these mounts to the host.
> 
> I am not convinced we should stop logging about units starting and shutting down. That said, you can manually configure things that way if you like, since [c2503e3](https://github.com/systemd/systemd/commit/c2503e359a3a03b73acce0a92d27b1b8f54ff92c). You could use that to define a drop-in that turns it off for all those messy docker mounts.
> 
> But I think it's pretty broken that docker lets its management mounts leak into the host like that. They are doing something wrong there...

So when docker is doing something wrong, then is the same true for either runc or cri-o?

**Comment by saschagrunert** [comment]
> But I think it's pretty broken that docker lets its management mounts leak into the host like that. They are doing something wrong there...

I'm wondering what the alternative would be. I could imagine that the mounts are held in a dedicated namespace, but then we would require additional management to keep them open if processes like crio or runc exit.

**Comment by haircommander** [comment]
we are actually working on moving cri-o to a mount namespace on startup in some situations https://github.com/cri-o/cri-o/pull/5974
