### ISSUE TITLE
cri-o version 1.20.x for s390x

### ISSUE THREAD

**Issue by vivkong** [cri-o/cri-o#5075]
cri-o v1.20.x is not available for s390x on OBS but v1.18.3 is.  Can it be added? Thanks.

https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable:cri-o:1.20

For reference: https://build.opensuse.org/project/monitor/devel:kubic:libcontainers:stable:cri-o:1.18:1.18.3

**Comment by haircommander** [comment]
any particular distro you want it for?

**Comment by vivkong** [comment]
Sorry forgot to mention - yes Ubuntu 20.04 please.

**Comment by haircommander** [comment]
should be done! feel free to close if it works for you :)

**Comment by vivkong** [comment]
Thanks for the fast turnaround!  It's now available on OBS.
