### ISSUE TITLE
cri-o not available in apt-based repositories

### ISSUE THREAD

**Issue by mrksngl** [cri-o/cri-o#5105]
**Description**

I followed the instructions on https://github.com/cri-o/cri-o/blob/master/install.md#apt-based-operating-systems
I did that before and it always worked. However, on a new machine today, it told me that `cri-o` cannot be found.

I use ubuntu 18.02, but it seems that my findings true for other distributions as well, see below.

**Steps to reproduce the issue:**
1. Use apt sources `deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /` and `deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/ /` as described by the guidelines
2. `apt-get update`
3. `apt-cache search cri-o`

**Describe the results you received:**
Package `cri-o` is not found

**Describe the results you expected:**
Package `cri-o` should be found

**Additional information you deem important (e.g. issue happens only occasionally):**
I was having a look into the repository and saw that https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.21/xUbuntu_18.04/ does indeed not include `cri-o`. Same goes for other distributions and `cri-o` version as well, as far as I can see.  
Looking further, I actually found a package, but in https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.21:/1.21.0/xUbuntu_18.04/
Note the "1.21:/1.21.0/" here, which **does not match** "$VERSION/".

**Output of `crio --version`:**
Could not install, but wanted to get 1.21

**Additional environment details (AWS, VirtualBox, physical, etc.):**
not applicable

**Comment by haircommander** [comment]
sorry, I half packaged 1.21.2 but didn't finish, so that  broke stuff. I'll fix today

**Comment by haircommander** [comment]
should be fixed now!

**Comment by mrksngl** [comment]
confirmed, works again
