### ISSUE TITLE
node configuration validation for memory swap cgroup failed node not configured with memory swap

### ISSUE THREAD

**Issue by ccnankai** [cri-o/cri-o#5108]
-->

**Description**
According to the installation instructions [https://github.com/cri-o/cri-o/blob/master/install.md](url) cri-o was successfully installed. But when I typed the `crio `command, there were two fata-level errors.

**ERROR:node configuration validation for memory swap cgroup failed node not configured with memory swap
ERROR: Validating api config: already existing connection on /var/run/ciro/crio.sock**

**Steps to reproduce the issue:**
1.apt install cri-o ,cri-o-runc
2.
`cat <<EOF | sudo tee /etc/modules-load.d/crio.conf
overlay
br_netfilter
EOF

sudo modprobe overlay
sudo modprobe br_netfilter

cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
net.bridge.bridge-nf-call-iptables  = 1
net.ipv4.ip_forward                 = 1
net.bridge.bridge-nf-call-ip6tables = 1
EOF

sudo sysctl --system

cat >>/etc/crio/crio.conf.d/02-cgroup-manager.conf<<EOF
[crio.runtime]
conmon_cgroup = "pod"
cgroup_manager = "cgroupfs"
EOF`

**Describe the results you received:**
`crio`

![image](https://user-images.githubusercontent.com/33537489/126427478-5963d8d8-3212-4d60-b087-3fb9703ec33c.png)
`journalctl -u crio`

![image](https://user-images.githubusercontent.com/33537489/126427652-fbb1c87b-035b-4ece-96cc-c2f9473f017e.png)

**Output of `crio --version`:**
![image](https://user-images.githubusercontent.com/33537489/126425640-6a360b9f-d6f0-405c-985d-63b078d5feb4.png)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

`lsb_release -a`
![image](https://user-images.githubusercontent.com/33537489/126425653-4675c24e-8330-4197-a47b-8e02e13cc63e.png)

`uname -a 
`![image](https://user-images.githubusercontent.com/33537489/126425854-7523b268-6ad1-48ee-8cb7-c2888fbb53e1.png)

k8s version:1.20.4

`crictl info`
![image](https://user-images.githubusercontent.com/33537489/126427807-ee7fd6a9-ed22-4133-957e-3c717531f6b3.png)

**Comment by haircommander** [comment]
hm, the errors here aren't actually a big deal. it just means the memory swap cgroup isn't configured. I have opened https://github.com/cri-o/cri-o/pull/5111 to update the log level so it's less alarming

**Comment by ccnankai** [comment]
Got it. Thank you very much.
