### ISSUE TITLE
CRI-O 1.20.3 metrics does not run on https (based on documentation settings)

### ISSUE THREAD

**Issue by thanos1983** [cri-o/cri-o#5112]
**Description**
Based on the documentation [cri-o-metrics](https://github.com/cri-o/cri-o/blob/472b3aecb053f29fa6697d9ec5471c31dd03cdf8/tutorials/metrics.md#cri-o-metrics) if we add paths to cert / key and restart CRI-O the metrics is expected to run on https.

**Steps to reproduce the issue:**
1. Add crt and key as documented [cri-o-metrics](https://github.com/cri-o/cri-o/blob/472b3aecb053f29fa6697d9ec5471c31dd03cdf8/tutorials/metrics.md#cri-o-metrics)
2. Restart CRI-O
3. Navigate to https://hostname:port/metrics and try if it returns the metrics.
4. On my case even after applying the configurations I can only get the metrics on http://hostname:port/metrics.

**Describe the results you received:**
I can only get the metrics on http://hostname:port/metrics instead of https://hostname:port/metrics. It seems that we are missing a https flag somewhere.

**Describe the results you expected:**
I would expect the metrics to be propagated on https://hostname:port/metrics

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```bash
$ crio -v
INFO[0000] Starting CRI-O, version: 1.20.3, git: 50065140109e8dc4b8fd6dc5d2b587e5cb7ed79d(dirty)
crio version 1.20.3
Version:       1.20.3
GitCommit:     50065140109e8dc4b8fd6dc5d2b587e5cb7ed79d
GitTreeState:  dirty
BuildDate:     1980-01-01T00:00:00Z
GoVersion:     go1.15.7
Compiler:      gc
Platform:      linux/amd64
Linkmode:      static
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Bare metal node running on RH7:

```bash
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.9 (Maipo)
```

**Comment by saschagrunert** [comment]
Hey @thanos1983, this will work only for v1.22.0 which has not been released, yet.

**Comment by thanos1983** [comment]
> Hey @thanos1983, this will work only for v1.22.0 which has not been released, yet.

Oh too bad :( thanks for the tip we can close the ticket :)

**Comment by thanos1983** [comment]
> Hey @thanos1983, this will work only for v1.22.0 which has not been released, yet.

Last quick question. Is there any possibility that you will be releasing a backward combatibility for socket 1.20?

Thank you again for your time and effort.

BR / Thanos

**Comment by saschagrunert** [comment]
@thanos1983 usually we do not backport such large features to maintenance branches to reduce the risk of introducing regressions.

**Comment by thanos1983** [comment]
> @thanos1983 usually we do not backport such large features to maintenance branches to reduce the risk of introducing regressions.

It makes 100% sense :). No worries I will try to update my cluster to 1.22 once it is released the socket and also the package.

Thank you again for your time and effort.

Have a nice day.

BR / Thanos
