### ISSUE TITLE
CRI-O can't remove containers that create very deep directory trees

### ISSUE THREAD

**Issue by sfowl** [cri-o/cri-o#5126]
**Description**
CRI-O cannot remove containers that create very deep directory trees. [CRI-O uses](https://github.com/cri-o/cri-o/blob/af2035b294e34cfe64863922d985468d27d9de79/vendor/github.com/containers/storage/store.go#L2495) `os.RemoveAll()` from the Go standard library, which uses a large amount of memory, proportionate to the directory tree depth, which triggers OOM Killer during container removal, killing a large number of system processes. 

CRI-O itself will be one of the last processes killed due to:
```
/usr/lib/systemd/system/crio.service:OOMScore Adjust=-999
```
**Steps to reproduce the issue:**
1. Start a container that attempts to create a deeply nested directory tree (millions of subdirectories)
2. Observe that container process eventually dies (either by oom-killer or disk space exhaustion)
3. Remove container with `crictl rm`
4. Observe sharp increase in crio memory usage, exhausting system memory, triggering OOM killer

**Describe the results you received:**
System memory sharply increases, causing OOM killer to start killing processes.
Later (after crio has restarted) `crictl ps -a` will report that no containers exist, however the dangling filesystem remains in /var/lib/containers/storage

**Describe the results you expected:**
Container image was successfully removed without trigger OOM killer 

**Additional information you deem important (e.g. issue happens only occasionally):**

I used create.go from this stdlib issue to test: https://github.com/golang/go/issues/47390

```
# cat Dockerfile
FROM ubi8/ubi

COPY create /

CMD /create /tmp/deep

# cat container-config.json
{
  "metadata": {
      "name": "create-deep-dirs-container"
  },
  "image":{
      "image": "localhost/deep"
  },
  "log_path":"0.log",
  "linux": {
  }
}

# cat pod-config.json
{
  "metadata": {
      "name": "create-deep-dirs",
      "namespace": "default",
      "attempt": 1,
      "uid": "hdishd83djaidwnduwk28bcsb"
  },
  "log_directory": "/tmp",
  "linux": {
  }
}
# go build create.go
# podman build -t localhost/deep .
# crictl run container-config.json pod-config.json
```

**Output of `crio --version`:**

```
crio version 1.21.2-5.rhaos4.8.gitb27d974.el8
Version:    1.21.2-5.rhaos4.8.gitb27d974.el8
GoVersion:  go1.16.4
Compiler:   gc
Platform:   linux/amd64
Linkmode:   dynamic
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

RHEL 8.4 virtual machine. 8GB RAM, no swap (just like RHCOS)

**Comment by saschagrunert** [comment]
Thank you for the detailed report @sfowl! :pray: 

That's unfortunate, _but looks_ like a corner case to me. It may be appropriate to wait for the golang fix before we take any action. What's your point on that (cc @haircommander)?

**Comment by haircommander** [comment]
we are able to set inode quotas for the read write layer, so a container user would be prevented from dosing the system *in some cases*. we'd also need quotas on volumes, which would probably require extensions to kubernetes

**Comment by sfowl** [comment]
inode quota pr: https://github.com/containers/storage/pull/970
