### ISSUE TITLE
CRI-O is not honoring Stopsignal passed as signal number

### ISSUE THREAD

**Issue by trishnendu** [cri-o/cri-o#5148]
In CRI-O code , the GetStopSignal() function is passing the input string directly to unix.SignalNum function without checking if it is an integer (in string format). As unix.SignalNum() supports only a limited number of POSIX signals, for special stop signals (like SIGRTMIN+3 needed to stop  systemd pods), we need to pass it by signal number. Containerd and docker are both supporting StopSignal to be passed as signal number or a signal name

**Comment by haircommander** [comment]
fixed inhttps://github.com/cri-o/cri-o/pull/5366
