### ISSUE TITLE
The ubuntu 21.04 system package is missing

### ISSUE THREAD

**Issue by lework** [cri-o/cri-o#5151]
The ubuntu 21.04 system package is missing

http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.21/

**Comment by saschagrunert** [comment]
Thank you for the hint @lework, the packages are now available: http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.21/xUbuntu_21.04/
