### ISSUE TITLE
How to export the image of the node when I use cro-i in k8s

### ISSUE THREAD

**Issue by klvchen** [cri-o/cri-o#5156]
How to export the image of the node when I use cro-i in k8s, if I use docker, I can use docker save, is there any similar tool for cro-i, thank you~

**Comment by saschagrunert** [comment]
Hey @klvchen, unfortunately the Container Runtime Interface (CRI) does not support image exports for now. What you can do is using [Podman](https://podman.io) to save the image in the same way docker does. I hope this helps in your use case.
