### ISSUE TITLE
Pulling image error - No space left on device (small /var/tmp)

### ISSUE THREAD

**Issue by VictorCallejas** [cri-o/cri-o#5187]
Hi,

I am getting this error when kubernetes tries to pull images. The nodes have a very small _/var/tmp_ directory.

`FATA[0002] pulling image: rpc error: code = Unknown desc = Error writing blob: error storing blob to file
"/var/tmp/storage178245615/2": write /var/tmp/storage178245615/2: no space left on device`

For that reason I have been trying to change this temporal directory to another location, but cri-o seems to not be catching this new configuration.

- I have tried to set up the big_files_temporary_dir flag
--big-files-temporary-dir=...`

- Then I tried to setup the TMPDIR enviroment variable, as that is the case with podman and I saw some references in the cri-o code that link that variable to /var/tmp directory by default.
`export TMPDIR=/dsk1/kubernetes/var/lib/containers/storage`

None of this options is working. So I do not know if I need to use a different flag or configuration parameter or it is an error.

cri-o version 1.21.1

Thanks.

**Comment by haircommander** [comment]
hey @VictorCallejas thanks for opening the issue

you can add the following drop-in file into `/etc/crio/crio.conf.d` to specify this:
```
[crio.image]
big_files_temporary_dir = "/dsk1/kubernetes/var/lib/containers/storage"
```

**Comment by VictorCallejas** [comment]
hi @haircommander thanks for your fast response! Sorry for the delay but some nodes needed a linux kernel update.

Seems to be working, so maybe when I specified _--big-files-temporary-dir_ before, maybe was defined in other place too and there was a priority conflict. Thanks!

Now I got and error in the next steps:
```
FATA[0005] pulling image: rpc error: code = Unknown desc = Error committing the finished image: error adding layer with blob "sha256:9dfd690186849486e(exit status 1): write /usr/share/cracklib/pw_dict.pwd: no space left on device
```
I imagine this error is not about the temporal dir, but the last one where the image is going to be stored.

For that I changed in /etc/crio/crio.conf
```
[crio]
root="/dsk1/kubernetes/var/lib/containers/storage"
```

Then the problem is at crio startup:
```
Validating root config: failed to get store to set defaults: remount /dsk1/kubernetes/var/lib/containers/storage/overlay, flags: 0x40000: invalid argument
```
That directory is an NFS, so I did tried other storage_drivers with no luck.

Then I see here https://github.com/containers/storage/blob/main/docs/containers-storage.conf.5.md , this message:
```
A common use case for this field is to provide a local storage directory when user home directories are NFS-mounted (podman does not support container storage over NFS).
```

Any solution for this?

Thank you very much.

**Comment by haircommander** [comment]
sanity check: are you running CRI-O as root? I know rootless podman runs into issues with NFS because it doesn't support user namespaces well, but AFAIK CRI-O should be able to access?

cc @nalind @giuseppe @rhatdan

**Comment by VictorCallejas** [comment]
Yes we are running crio as root

**Comment by VictorCallejas** [comment]
I made a mistake in the previous message, my team just told me that they are mounting `/dsk1` in the node as any other directory and not as an NFS. This makes the error even more strange. 

Sorry for the mistake.

**Comment by haircommander** [comment]
can I have the /etc/mtab entry for dsk1? It seems to be the same as this issue https://github.com/containers/podman/issues/8647#issuecomment-742008111

**Comment by gavol** [comment]
Here is it:

/dev/sda7 /dsk1 ext4 rw,relatime,data=ordered 0 0

**Comment by haircommander** [comment]
can you try setting
```
# Set to skip a PRIVATE bind mount on the storage home directory.  Only supported by
# certain container storage drivers
skip_mount_home = "true"
```
in /etc/containers/storage.conf

**Comment by gavol** [comment]
Sorry for the delay in may answer, unfortunately the nodes were down for maintenance.
The skip_mount_home setting seems to work.

I have tried to restart crio without that option and it was complaining; I have then set that specific option and it could restart without any error (so far).

Thanks.

**Comment by haircommander** [comment]
glad we could figure it out!

**Comment by gavol** [comment]
That would not have been possible without your precious help. Thanks again.
