### ISSUE TITLE
Kubernetes node e2e test fail (and flake) with recent `master` commit

### ISSUE THREAD

**Issue by harche** [cri-o/cri-o#5202]
**Description**

Master branch of crio is very flaky with node e2e tests. While the commit  `4d14fd61d2d533a0bb81557b54d3505be830efa7` and  earlier are relatively stable provided the host is using runc v1.0.1 

**Steps to reproduce the issue:**
1. Run node e2e tests 
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by saschagrunert** [comment]
As discussed earlier, I think https://github.com/cri-o/cri-o/pull/5113 is the suspicious PR introducing the breaking change.

**Comment by harche** [comment]
We need to bump up the crio commit in upstream node e2e tests and see if they pass fine.

**Comment by saschagrunert** [comment]
Let's give it a try in https://github.com/cri-o/cri-o/pull/6007
