### ISSUE TITLE
possible bug in openpgp_tag.sh

### ISSUE THREAD

**Issue by rockmenjack** [cri-o/cri-o#5219]
Hi, I am trying to compile crio and enable image signing support, but in [hack/openpgp_tag.sh](https://github.com/cri-o/cri-o/blob/master/hack/openpgp_tag.sh), the check is a `! gpgme-config --libs`. Are we suppose to enable this feature when  `gpgme-config --libs` succeed?

**Comment by saschagrunert** [comment]
I would say yes, the logic seems inverted. Do you wanna open a PR to fix that?

**Comment by haircommander** [comment]
fixed by #5238
