### ISSUE TITLE
Packages for debian 11

### ISSUE THREAD

**Issue by LittleFox94** [cri-o/cri-o#5240]
Some days ago, debian 11 (bullseye) was released - I'd love to see cri-o packaged for debian 11.

Already asked in Slack before making this issue, but since there wasn't a response in 18h (which I would think is enough time if someone knows there are plans to answer with "it's planned"), I thought this issue will probably not hurt :)

If there is any work required to add support for debian 11, I'm happy to provide it :)

**Comment by saschagrunert** [comment]
I enabled debian 11 in obs, let's see if the packages build successfully :)

**Comment by LittleFox94** [comment]
Nice, thank you @saschagrunert :)

**Comment by saschagrunert** [comment]
Seems to work, so closing this one

**Comment by LittleFox94** [comment]
Working great on my first debian 11 k8s node, too :)

**Comment by saschagrunert** [comment]
> Working great on my first debian 11 k8s node, too :)

Awesome, feel free to reach out anytime if you see any bugs or strange behavior. :pray:

**Comment by yjqg6666** [comment]
How about updating the install.md doc regarding debian bullseye which should not be referenced as debian testing anymore, debian CodeName should be preferred?

**Comment by yjqg6666** [comment]
@haircommander Are GNU/Debian 11 bullseye(currently stable) and bookwork (currently testing) supported?

**Comment by haircommander** [comment]
11 bullseye is, haven't investigated bookwork yet
