### ISSUE TITLE
Cri-o 1.22.0 packages not available for centos7, debian10, fedora33, raspbian10, xUbuntu18.04

### ISSUE THREAD

**Issue by grunlab** [cri-o/cri-o#5267]
Cri-o 1.22.0 packages are currently not available for centos7, debian10, fedora33, raspbian10 & xUbuntu18.04

Example for centos7:
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.22/CentOS_7/x86_64/
--> the RPM cri-o-1.22.0-11.1.el7.x86_64.rpm is missing

**Comment by haircommander** [comment]
sorry for the delay, thanks for opening the issue. They're all broken for a variety of different and exciting reasons. is there a distro in particular you are looking for, or do you want the support matrix to be more accurate?

**Comment by grunlab** [comment]
I'm looking for those two distro/arch in particular:
- centos_7 / x86_64 : for a professional usage
- raspbian_10 / armhf : for a personal usage

**Comment by haircommander** [comment]
for centos 7 I am still waiting on golang 1.16 to make it into EPEL, not sure how long that will take. I will look at raspbian tomorrow. thanks for the patience :)

**Comment by justabaka** [comment]
Any ideas on when it's going to be possible to build packags for CentOS 7 or what packages is okay to substitute them with? 1.22 was realeased almost a month ago.

I'd build that myself, no problem, but it feels a bit weird.

**Comment by haircommander** [comment]
> Any ideas on when it's going to be possible to build packags for CentOS 7 or what packages is okay to substitute them with? 1.22 was realeased almost a month ago.
> 
> I'd build that myself, no problem, but it feels a bit weird.

yeah understood. I have updated the package to import a custom golang. let's see if that does it...

**Comment by haircommander** [comment]
It seems centos 7 has succeeded!

**Comment by haircommander** [comment]
I believe all of the versions here are about to successfully build. @grunlab can you PTAL and let me know if you think this can be closed?

**Comment by grunlab** [comment]
# For raspbian_10 / armhf:

I've just tried to upgrade cri-o from 1.21.3 to 1.22.0 on a raspbian_10 / armhf node ... there is something very strange ... it looks that finally a downgrade to 1.19.4 happened instead !?

Before the upgrade --> CONTAINER-RUNTIME = cri-o://1.21.3
```
$ kc get node master-01 -o wide
NAME        STATUS                     ROLES                  AGE    VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                       KERNEL-VERSION      CONTAINER-RUNTIME
master-01   Ready,SchedulingDisabled   control-plane,master   253d   v1.21.5   192.168.0.101   <none>        Debian GNU/Linux 10 (buster)   5.4.142-odroidxu4   cri-o://1.21.3
```

After the upgrade --> CONTAINER-RUNTIME = cri-o://1.19.4 !!!
```
$ kc get node master-01 -o wide
NAME        STATUS                     ROLES                  AGE    VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                       KERNEL-VERSION      CONTAINER-RUNTIME
master-01   Ready,SchedulingDisabled   control-plane,master   253d   v1.21.5   192.168.0.101   <none>        Debian GNU/Linux 10 (buster)   5.4.142-odroidxu4   cri-o://1.19.4
```

apt sources list for cri-o:
```
$ cat /etc/apt/sources.list.d/cri-o.list 
deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Raspbian_10/ /
deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.22/Raspbian_10/ /
```

Rollback:
- uninstall cri-o
- replace 1.22 by 1.21 in /etc/apt/sources.list.d/cri-o.list 
- reinstall cri-o ... back to cri-o 1.21.3


# For centos_7 / x86_64:

I still don't see the RPM file cri-o-1.22.0-xx.1.el7.x86_64.rpm in https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.22/CentOS_7/x86_64/

**Comment by justabaka** [comment]
Looks great, will test it later. Thank you very much!

**Comment by grunlab** [comment]
centos7/x86_64 --> cri-o 1.22.0 RPM is now available. I will also test it

**Comment by haircommander** [comment]
oh jeez, it seems like raspbian hit https://github.com/cri-o/cri-o/issues/5329 as well. I found the issue and it should be fixed

**Comment by grunlab** [comment]
I've just tested cri-o 1.22.0 on centos7/x86_64 --> it looks ok:

````
$ sudo crictl version
Version:  0.1.0 <-- I don't really understand what this version is ?
RuntimeName:  cri-o
RuntimeVersion:  1.22.0 <-- ok
RuntimeApiVersion:  v1alpha2
````

I will check reaspbian10/armhf tonight (French time)

**Comment by haircommander** [comment]
We now have support for every distro listed here, and I believe this is fixed. @grunlab can you close this issue if you confirm the weird cri-o version thing is fixed?

**Comment by grunlab** [comment]
I confirm, it is OK on raspbian10/armhf as well.
Issue closed. Thank you.

**Comment by haircommander** [comment]
excellent to hear!
