### ISSUE TITLE
"failed to connect: dial unix: missing address" log spam when using kata-containers 2.2.0 as runtime

### ISSUE THREAD

**Issue by timricese** [cri-o/cri-o#5276]
**Description**

Discussed and diagnosed on kata-containers slack https://katacontainers.slack.com/archives/C86U7NZND/p1630576915021800 where it was recommended to report this here.

When using kata-containers 2.2.0 on kubernetes 1.21.4, cri-o 1.21.2 the cri-o log fills with events such as 
```
Sep 03 08:37:14 pumped-gator kata[113928]: time="2021-09-03T08:37:14.186516187Z" level=error msg="forward event" error="failed to connect: dial unix: missing address"
Sep 03 08:37:14 pumped-gator crio[47547]: time="2021-09-03T08:37:14.186516187Z" level=error msg="forward event" error="failed to connect: dial unix: missing address"
Sep 03 08:37:14 pumped-gator kata[113928]: time="2021-09-03T08:37:14.212663769Z" level=error msg="forward event" error="failed to connect: dial unix: missing address"
Sep 03 08:37:14 pumped-gator crio[47547]: time="2021-09-03T08:37:14.212663769Z" level=error msg="forward event" error="failed to connect: dial unix: missing address"
``` 

when starting/stopping pods and even when using `kubectl exec` to get a shell in a running pod. 

Other than the presence of error messages in the log everything seems to work.

This was diagnosed by @fgiudici as follows:

> Francesco Giudici  5 hours ago
> The address arg in the katav2 shim binary is used to give a connection back to the containerd socket, connecting via a containerd client. The containerd client protocol is not spoken by CRI-O, and that part was never used in CRI-O. So, nothing should affect CRI-O - kata workloads.
> The address arg requires ... and address value. As there is no address speaking containerd client protocol in CRI-O the address is missing.
> 
> Francesco Giudici  5 hours ago
> This was just ignored in 2.1
> 
> Francesco Giudici  5 hours ago
> in 2.2 we updated the vendored containerd code to v1.5.4
> 
> Francesco Giudici  5 hours ago
> When kata uses the containerd shim code to publish the event, now the check on the address is performed (it wasn't before)
> 
> Francesco Giudici  5 hours ago
> and that error pops out.

**Steps to reproduce the issue:**
1. install kubernetes 1.21 with crio 1.21.2 and kata containers 2.2.0
2. start a pod using a kata-container runtime
3. ???

**Describe the results you received:**
Lots of errors in the log, but functioning pod

**Describe the results you expected:**
Functioning pod with  no error messages

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.21.2
Version:       1.21.2
GitCommit:     aaefa6b173f79384c6a2a627e5074a7f5b02957f
GitTreeState:  clean
BuildDate:     2021-07-20T20:44:03Z
GoVersion:     go1.15.2
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
bare metal, ubuntu 20.04

**Comment by fgiudici** [comment]
This has been fixed on kata-containers side: [kata PR 3736](https://github.com/kata-containers/kata-containers/pull/3736).
The fix will be available starting from kata-containers release 2.3.3.
