### ISSUE TITLE
Can not pull image docker.io/calico/kube-controllers:v3.20.0 with crictl on CRI-O 1.21.2

### ISSUE THREAD

**Issue by thanos1983** [cri-o/cri-o#5282]
**Description**

Launching cluster with CRI-O 1.21.2 and kubernetes version 1.21.[3-4] results in problem because CRI-O socket does not pull the image.

**Steps to reproduce the issue:**
1. Install CRI-O socket 1.21.2
2. Run crictl or launch cluster with this socket
3. Observer stdout / stderr

Sample:

```bash
vagrant@k8s-master:~$ sudo crictl pull docker.io/calico/kube-controllers:v3.20.0 -D
FATA[0033] pulling image: rpc error: code = Unknown desc = Error reading manifest v3.20.0 in docker.io/calico/kube-controllers: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

**Describe the results you received:**
Error that the socket has reached maximum number of pull request.

**Describe the results you expected:**
Being able to download the image without timeout.

**Additional information you deem important (e.g. issue happens only occasionally):**
I can pull the relevant images with CRI-O 1.22.0 and kubernetes 1.22.1.

**Output of `crio --version`:**

```bash
vagrant@k8s-master:~$ crio --version
crio version 1.21.2
Version:       1.21.2
GitCommit:     aaefa6b173f79384c6a2a627e5074a7f5b02957f
GitTreeState:  clean
BuildDate:     2021-08-24T13:40:40Z
GoVersion:     go1.15.2
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox

**Comment by saschagrunert** [comment]
Hey @thanos1983, thank you for opening this issue. Unfortunately we cannot do much here because it's a limitation of the docker registry. I'm not sure what the plans of the calico projects are, but maybe they can host their images in a registry which does not face such limitations.

**Comment by thanos1983** [comment]
> Hey @thanos1983, thank you for opening this issue. Unfortunately we cannot do much here because that's a limitation of the docker registry. I'm not sure what the plans of the calico projects are, but maybe they can host their images in a registry which does not face such limitations.

Hello @saschagrunert,

You are absolutely right. Apologies for raising the ticket with CRI-O team.

Initially I was running my cluster with 1.22 everything was working fine I switched to 1.21 to test something and things started to break. Once I tried to switch back to 1.22 I noticed the problem.

This is nothing to do with CRI-O I am closing the ticket.

Thanks again for the quick follow up.

BR / Thanos
