### ISSUE TITLE
Error converting YAML to JSON: yaml: line 124: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by thanos1983** [cri-o/cri-o#5285]
**Description**

Deploying cluster.yaml file directly through GitHub is failing. The problem is not occurring when a user copies and deploys the file locally. It seems to be a character somewhere that is messing up the deployment.

**Steps to reproduce the issue:**
1. Simply deploy metrics (sample): `kubectl create -f https://github.com/cri-o/cri-o/blob/master/contrib/metrics-exporter/cluster.yaml`
2. If we download the file and apply exactly the same thing e.g. `kubectl create -f cluster.yaml` it works perfectly.
3.

**Describe the results you received:**
Error: `error converting YAML to JSON: yaml: line 124: mapping values are not allowed in this context`

**Describe the results you expected:**
The metrics to be deployed normally without any issues.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**
This is not related with CRI-O socket it is related with the file (special characters or something).

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Bare Metal

**Comment by saschagrunert** [comment]
Thank you for the report @thanos1983, a fix is incoming in #5286

**Comment by thanos1983** [comment]
@saschagrunert  - I still get the error. I see that the fix was merged in master. I will test again tomorrow in case that was not yet updated for some reason.
