### ISSUE TITLE
Make s390x arch packages available for xUbuntu_20.04

### ISSUE THREAD

**Issue by spowelljr** [cri-o/cri-o#5292]
Similar to #2467, [minikube](https://github.com/kubernetes/minikube) now supports the s390x arch as of our last release. The current version of cri-o we're using 1.20, has a deb package for s390x https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.20/xUbuntu_20.04/. I'm in the process of updating cri-o to 1.22 but found that there's no package for s390x https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.22/xUbuntu_20.04/ and will have to unsupport the cri-o runtime for s390x builds.

**Comment by haircommander** [comment]
I've flipped the bit for s390x for ubuntu 20.04 and ubuntu 20.10, it should be ready in an hour or so

**Comment by spowelljr** [comment]
Awesome @haircommander, thank you very much!

**Comment by spowelljr** [comment]
I see the there now, thanks you very much! Since you flipped the bit, will it be available for all future releases as well, or is this something you have to manually do everytime?

**Comment by haircommander** [comment]
if I've setup my scripts correctly, it should propegate to future releases!

**Comment by spowelljr** [comment]
Thank you for doing that, much appreciated!
