### ISSUE TITLE
CRI-O missing for ubuntu 21.04 on arm64.

### ISSUE THREAD

**Issue by Rina-Y** [cri-o/cri-o#5300]
After setting up the repositories for ubuntu 21.04 on a freshly installed arm64 device, I found that apt could not find the `cri-o` package.  Decided to take a look using my web browser, and seems that regardless of what version of cri-o i checked a repository for, there was no arm64 build in the 21.04 cri-o repositories.  There are arm64 builds in some of the 20.10 repositories, but none in the 21.04.  I'll do a source build for myself, but I just wanted to make sure someone knew that there was missing bits in the repos.  The shared repo (the one without the version) did contain arm64 builds at least!

**Comment by haircommander** [comment]
Thanks for letting me know! I am not sure what is going on with the repo and I've got a number of things to keep track of but rest assured this is still on my list :) thanks for your patience

**Comment by haircommander** [comment]
Ok I think 1.22 is built for ubuntu 21.04. Thanks for the patience!
