### ISSUE TITLE
Allow the registry using self-singed ca-certificate

### ISSUE THREAD

**Issue by rayshoo** [cri-o/cri-o#5311]
**Description**

**Steps to reproduce the issue:**
1. I generated self-signed ca-certificate with openssl
2. I generated crt, key file with self-signed ca as provider
3. I use those on private docker registry
4. when I try to pull images from my registry with kubernetes based on crio runtime, get this error log `Failed to pull image "m1.dev/rayshoo/ubuntu:1.0": rpc error: code = Unknown desc = error pinging docker registry m1.dev: Get "https://m1.dev/v2/": x509: certificate signed by unknown authority`
5.  I cant find any allow self-signed ca-certificate option in /etc/crio/crio.conf, but docker, containerd runtime provide that.

**Describe the results you received:**
`Failed to pull image "m1.dev/rayshoo/ubuntu:1.0": rpc error: code = Unknown desc = error pinging docker registry m1.dev: Get "https://m1.dev/v2/": x509: certificate signed by unknown authority`

**Describe the results you expected:**
image pull success and get running pod status

**Additional information you deem important (e.g. issue happens only occasionally):**
Don't want the insecure option instead of adding ownca allow

**Output of `crio --version`:**

```
INFO[0000] Starting CRI-O, version: 1.20.3, git: 50065140109e8dc4b8fd6dc5d2b587e5cb7ed79d(clean) 
crio version 1.20.3
Version:       1.20.3
GitCommit:     50065140109e8dc4b8fd6dc5d2b587e5cb7ed79d
GitTreeState:  clean
BuildDate:     2021-07-14T23:38:00Z
GoVersion:     go1.15.2
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtualbox, kubelet v1.20.10, crio runtime, openssl self-signed ca-certificate with private docker registry

**Comment by haircommander** [comment]
@QiWang19 can you PTAL

**Comment by QiWang19** [comment]
@rayshoo  /etc/crio/crio.conf does not have the cert-dir configurations. The https://github.com/containers/image/blob/main/docs/containers-certs.d.5.md#description points out the `$HOME/.config/containers/certs.d` or `/etc/containers/certs.d` can be used to store the certificates.

**Comment by rayshoo** [comment]
@QiWang19 Thank you very much! I appreciate to you. Good luck and have a nice day!! :)
