### ISSUE TITLE
s390x package went missing for xUbuntu_20.04

### ISSUE THREAD

**Issue by spowelljr** [cri-o/cri-o#5341]
Hi, I asked for s390x package to be added for 1.22 for xUbuntu_20.04 in this issue #5292.

The deb package was added and everything was fine, however, today I've discovered that the package has gone missing and that the s390x folder is empty.

https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.22/xUbuntu_20.04/s390x/

![Screen Shot 2021-09-22 at 12 15 35 PM](https://user-images.githubusercontent.com/44844360/134407383-aae34349-65e6-46ca-9063-7368979c2873.png)

Can also see that the folder was last updated on the 17th in comparison to the rest of the files and folders that were updated today.

**Comment by haircommander** [comment]
sorry, undergoing some package reconfiguring, let me flip some switches

**Comment by spowelljr** [comment]
The packages are back now, thank you very much!

**Comment by haircommander** [comment]
happy to help, thanks for using CRI-O :)
