### ISSUE TITLE
mounting "devpts" to rootfs at "/dev/pts" caused: mount through procfs: invalid argument

### ISSUE THREAD

**Issue by jennydaman** [cri-o/cri-o#5348]
**Description**

I am trying to play around with the `uid_mappings` and `gid_mappings` settings of cri-o. I tried setting custom values for `uid_mappings` and `gid_mappings` in `/etc/crio/crio.conf`. Containers were no longer able to be created.

I was unable to find any documentation nor examples on how to use these features, if someone could link me to this, it would be helpful. More generally, I would like to enact some userns solution.

I am also unsure how to approach debugging. I could not find any other case of this error message from a Google search. It would be useful for the [debugging guide](https://github.com/cri-o/cri-o/blob/main/tutorials/debugging.md) to be expanded.

**Steps to reproduce the issue:**

1. Start with an Ubuntu 20.04 box
2. Install Kubernetes using [kubespray](https://kubespray.io/) v2.16.0 with `container_manager: crio` 
3. On a worker node, edit `/etc/crio/crio.conf` with `uid_mappings = "0:1234567:1"`
4. Schedule a pod on the node, e.g.

```yaml
kind: Pod
apiVersion: v1
metadata:
  name: wow
spec:
  containers:
  - name: test-nothing
    image: busybox:stable
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "echo lol"
  restartPolicy: "Never"
```

**Describe the results you received:**

```
 time="2021-09-24 13:39:41.219309596-04:00" level=error msg="Container creation error: time=\"2021-09-24T13:39:41-04:00\" level=error msg=\"container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting \\\"devpts\\\" to rootfs at \\\"/dev/pts\\\" caused: mount through procfd: invalid argument\"\n" id=30f25337-c14a-4201-b8e8-1a07ad01984f name=/runtime.v1alpha2.RuntimeService/RunPodSandbox
```

**Describe the results you expected:**

Container runs.

**Additional information you deem important (e.g. issue happens only occasionally):**

cri-o is working with its default settings, where containers are run as `root`.

**Output of `crio --version`:**

```
crio --version
crio version 1.21.2
Version:       1.21.2
GitCommit:     aaefa6b173f79384c6a2a627e5074a7f5b02957f
GitTreeState:  clean
BuildDate:     2021-07-20T20:44:03Z
GoVersion:     go1.15.2
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I have tried this on two different physical machines, where both were provisioned by the same run of Kubespray.

**Comment by haircommander** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
that error is coming from runc

**Comment by jennydaman** [comment]
Thank you for looking into it. It is caused by the fix, meaning would it work if I _downgrade_ to `runc` version 1.0.0-rc94?
Presumably, downgrading would not be advisable?

**Comment by giuseppe** [comment]
I'd suggest to not do that, or you inherit again the security issue.

I'll take a look to see if there is anything we can do in CRI-O, in the meanwhile it is probably safer to not use `uid_mapping/gid_mapping`rather than using an older runc version.

**Comment by giuseppe** [comment]
it seems to work locally (Fedora 34) with the latest runc development version and kernel 5.13.16-200.fc34.x86_64.

Could you try upgrading runc?

**Comment by AkihiroSuda** [comment]
> uid_mappings = "0:1234567:1"

You have to map 65536 UIDs and GIDs, at least.
