### ISSUE TITLE
Support ppc64le for CentOS 8

### ISSUE THREAD

**Issue by EGuesnet** [cri-o/cri-o#5356]
**Description**

Currently, cri-o is built only for x86_64 for CentOS 8. We have need of cri-o on Power. It seems Open Build Service can support it.
Can you add support of ppc64le for CentOS 8?

Thanks.

**Comment by haircommander** [comment]
I've toggled the knob, it should be ready in an hour or so!

**Comment by haircommander** [comment]
I did so on 1.22, is there a specific version you're looking for?

**Comment by EGuesnet** [comment]
There is no need of a specific version.
I cannot find it at https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.22/CentOS_8/ppc64le/,  there is no cri-o file.
CentOS 8 and CentOS 8 Stream ppc64le are labelled "excluded" in https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable:cri-o:1.22/cri-o.

**Comment by haircommander** [comment]
oops, had to update the spec. should be working now!

**Comment by EGuesnet** [comment]
I confirm it works.
Thanks!
