### ISSUE TITLE
Wrong link in Install.md

### ISSUE THREAD

**Issue by EGuesnet** [cri-o/cri-o#5357]
**Description**

Install.md has two wrong link.

**Steps to reproduce the issue:**
1. Click to "openSUSE's OBS" link

2. Click to "open an issue" link.

**Describe the results you received:**

1. Go to "https://github.com/cri-o/cri-o/blob/main/build.opensuse.org"
Error 404

2. Go to https://github.com/cri-o/cri-o/blob/main/github.com/cri-o/cri-o/issues/new
Error 404

**Describe the results you expected:**

1. Go to https://build.opensuse.org (I think).
2. Go to https://github.com/cri-o/cri-o/issues/new

**Comment by haircommander** [comment]
would you like to open a PR to fix?
