### ISSUE TITLE
The repository 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  Release' does not have a Release file.

### ISSUE THREAD

**Issue by thanos1983** [cri-o/cri-o#5368]
**Description**
It seems yesterday the key got updated see repo [repositories / devel: / kubic: / libcontainers: / stable / xUbuntu_20.10 Release.key](https://mirrorcache.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.10/Release.key.mirrorlist)

It breaks my deployments with CRI-O on Ubuntu :(

**Steps to reproduce the issue:**
1. Follow the steps as it is documented [cri-o/tutorials/install-distro.md](https://github.com/cri-o/cri-o/blob/8d4d158935929800c4300b82eb4b5a83ded400f4/tutorials/install-distro.md)
2. `echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list`
3. Then run update (result see below):

```bash
apt-get update
Hit:1 http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.21/xUbuntu_20.04  InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease                                                                                                  
Ign:3 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  InRelease                                           
Hit:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease                                                                                          
Hit:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease                                                            
Err:6 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  Release                 
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 195.135.221.134 443]
Hit:8 http://security.ubuntu.com/ubuntu focal-security InRelease                                     
Get:7 https://packages.cloud.google.com/apt kubernetes-xenial InRelease [9,383 B]
Reading package lists... Done       
E: The repository 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Describe the results you received:**
Broken release for Ubuntu new key.

**Describe the results you expected:**
The key should be fine as it used to be.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
1.21
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Bare Metal

**Comment by marcusbooyah** [comment]
@thanos1983 I had the same issue. You need to install the latest `ca-certificates` package.

```
sudo apt install ca-certificates -y
```

**Comment by thanos1983** [comment]
> apt install ca-certificates -y

Hello @marcusbooyah ,

You are absolutely right. I did not even think about the CAs. I thought of checking when the key was updated but not to pull (stupid of me).

Thanks a lot for the quick response :).

**Comment by haircommander** [comment]
should this be included in the set of prerequisite packages (currently gnupg and curl are also required)

**Comment by thanos1983** [comment]
> should this be included in the set of prerequisite packages (currently gnupg and curl are also required)

I think so too that it should be documented.

**Comment by thanos1983** [comment]
I should also mention that without `sudo apt upgrade -y` it does not work for me :( so we might to add also this.

**Comment by haircommander** [comment]
would you care to open a PR with what worked for you @thanos1983 ? if you do, you may want to base it off of https://github.com/cri-o/cri-o/pull/5369/ to prevent conflicts

**Comment by thanos1983** [comment]
> would you care to open a PR with what worked for you @thanos1983 ? if you do, you may want to base it off of #5369 to prevent conflicts

Sure will do it during the weekend.
