### ISSUE TITLE
Why does crio mount /dev/vda1 on /var/lib/containers/storage/overlay?

### ISSUE THREAD

**Issue by dilyanpalauzov** [cri-o/cri-o#5401]
```
# crio --version
INFO[0000] RDT is not enabled: failed to detect resctrl mount point: resctrl not found in /proc/mounts 
crio version 1.22.0
Version:          1.22.0
GitCommit:        unknown
GitTreeState:     unknown
BuildDate:        2021-09-29T11:21:39Z
GoVersion:        go1.16.8
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        containers_image_openpgp, containers_image_ostree_stub, seccomp, selinux
SeccompEnabled:   true
AppArmorEnabled:  false
```
I have no storage.conf and no registry.conf  files.  My `/etc/crio/crio.conf.d/10-crio.conf` contains:
```
[crio.runtime]
default_runtime = "crun"

#[crio.runtime.runtimes]
[crio.runtime.runtimes.crun]
runtime_path="/usr/bin/crun"
```

The root of my system is /dev/vda1 ⇔ / 
```
# mount                           
/dev/vda1 on / type ext4 (rw,relatime,errors=remount-ro)
```
My crio.service file is 
```
[Unit]
Description=Container Runtime Interface for OCI (CRI-O)
Documentation=https://github.com/cri-o/cri-o
Wants=network-online.target
Before=kubelet.service
After=network-online.target

[Service]
Type=notify
EnvironmentFile=-/etc/sysconfig/crio
Environment=GOTRACEBACK=crash
ExecStart=/usr/local/bin/crio \
          $CRIO_CONFIG_OPTIONS \
          $CRIO_RUNTIME_OPTIONS \
          $CRIO_STORAGE_OPTIONS \
          $CRIO_NETWORK_OPTIONS \
          $CRIO_METRICS_OPTIONS
ExecReload=/bin/kill -s HUP $MAINPID
TasksMax=infinity
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
OOMScoreAdjust=-999
TimeoutStartSec=0
Restart=on-abnormal

[Install]
WantedBy=multi-user.target
Alias=cri-o.service
```
and /etc/sysconfig/crio does not exist.  I do not have kubelet on the system.

When I call `systemctl start crio`, crun is not running, and I see this additional mount:
```
# mount
/dev/vda1 on /var/lib/containers/storage/overlay type ext4 (rw,relatime,errors=remount-ro)
```
When I call `systemctl stop crio` the mount
```
/dev/vda1 on /var/lib/containers/storage/overlay type ext4 (rw,relatime,errors=remount-ro)
```
disappears.  The content of /var/lib/containers/storage/overlay does not change during the mount.

Why does crio mount /dev/vda1 on /var/lib/containers/storage/overlay?

**Comment by haircommander** [comment]
@giuseppe @nalind do y'all have any ideas here?

**Comment by giuseppe** [comment]
it is just a bind mount on itself.

`mount --bind /var/lib/containers/storage/overlay /var/lib/containers/storage/overlay`

In this way it can be made `private` and the mounts below it do not propagate to the containers.

I am closing the issue since it is done on purpose this way.

**Comment by dilyanpalauzov** [comment]
So doing `mount --bind` on itself, lists the root of the file system on `mount -a` before `on`.  I confirm this is the case, while the `mount -a` output makes absolutely no sense.

**Comment by subash-krishnan** [comment]
I'm getting the below error while initializing the kubernetes cluster using kubeadm.
We are using the CRI-O as our container runtime.

error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-proxy:v1.24.7: output: E1019 00:23:44.369568    5786 remote_image.go:242] "PullImage from image service failed" err="rpc error: code = Unknown desc = writing blob: adding layer with blob \"sha256:ef3e2250672ad8b00821570e47a92fa542899519f9243214b3865e54b5e4037e\": creating overlay mount to /var/lib/containers/storage/overlay/f4a29b5d278215c98ee94218edb90d715fab25fa46747d4cf2d0f14c728e4f6e/merged, mount_data=\"nodev,metacopy=on,lowerdir=/var/lib/containers/storage/overlay/l/VUQ3D3YII4XAM2BTV4HQY4DUCH:/var/lib/containers/storage/overlay/l/T2B6RT5ZYO5JZ3KCWBVCMDE73N,upperdir=/var/lib/containers/storage/overlay/f4a29b5d278215c98ee94218edb90d715fab25fa46747d4cf2d0f14c728e4f6e/diff,workdir=/var/lib/containers/storage/overlay/f4a29b5d278215c98ee94218edb90d715fab25fa46747d4cf2d0f14c728e4f6e/work\": no such file or directory" image="k8s.gcr.io/kube-proxy:v1.24.7"
time="2022-10-19T00:23:44+03:00" level=fatal msg="pulling image: rpc error: code = Unknown desc = writing blob: adding layer with blob \"sha256:ef3e2250672ad8b00821570e47a92fa542899519f9243214b3865e54b5e4037e\": creating overlay mount to /var/lib/containers/storage/overlay/f4a29b5d278215c98ee94218edb90d715fab25fa46747d4cf2d0f14c728e4f6e/merged, mount_data=\"nodev,metacopy=on,lowerdir=/var/lib/containers/storage/overlay/l/VUQ3D3YII4XAM2BTV4HQY4DUCH:/var/lib/containers/storage/overlay/l/T2B6RT5ZYO5JZ3KCWBVCMDE73N,upperdir=/var/lib/containers/storage/overlay/f4a29b5d278215c98ee94218edb90d715fab25fa46747d4cf2d0f14c728e4f6e/diff,workdir=/var/lib/containers/storage/overlay/f4a29b5d278215c98ee94218edb90d715fab25fa46747d4cf2d0f14c728e4f6e/work\": no such file or directory"
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

**Comment by haircommander** [comment]
I think you may be hitting a different error, could you open a new issue please?
