### ISSUE TITLE
Make metrics follow Prometheus best practices and reduce cardinality

### ISSUE THREAD

**Issue by discordianfish** [cri-o/cri-o#5426]
The prometheus metric names don't follow the best practices:

- all counters should be suffixed by `_total`
- all metrics should use base units (so seconds, not microseconds)

Beside that, some label values are unbound, leading to high cardinality (at least `crio_image_pulls_by_*`).

Arguably some metric names could be improved (crio_image_pulls_by_digest should include bytes if it reflects bytes pulled).

Since changing the metrics is a breaking change for dashboards and alerts, ideally this happens only once and new metrics are carefully reviewed to follow the best practices.

/cc @bwplotka Maybe something for you? :)

**Comment by discordianfish** [comment]
@saschagrunert Won't have time to look into that in the near future but might get back to it if nobody else does

**Comment by swghosh** [comment]
I am looking into this, @discordianfish can you please mark me as assignee?
