### ISSUE TITLE
Cannot install Cri-o 1.19.4 on Ubuntu 20.04

### ISSUE THREAD

**Issue by iusetabs** [cri-o/cri-o#5480]
**Description**

I cannot install cri-o 1.19.4 on Ubuntu 20.04. I receive` E: Unable to locate package cri-o. ` 

Has 1.19.4 been correctly packaged for Ubuntu 20.04? 

**Steps to reproduce the issue:**
1.    `echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.19:/1.19.4/xUbuntu_20.04/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list`
2. `  echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:1.19:1.19.4.list
`
3. `  curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.19:/1.19.4/xUbuntu_20.04/Release.key | apt-key add - > /dev/null 2>&1
`
4. `  curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key | apt-key add - > /dev/null 2>&1
`

5. `  apt-get --assume-yes update`

6.  `apt-get --assume-yes install cri-o cri-o-runc`

**Describe the results you received:**
 E: Unable to locate package cri-o. 

**Describe the results you expected:**
To be able to install Cri-o 1.19.4

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by haircommander** [comment]
cri-o 1.19 is out of support, is it possible to use a newer version? If not I can try to take a look, but it'll be best-effort

**Comment by iusetabs** [comment]
I can use a newer version sure 😄 However I checked and 1.19.4 seems like it cannot at all be installed using apt for any distribution. Maybe this is something bigger than just 20.04?

**Comment by haircommander** [comment]
hm weird. I'll try to take a look, but no promises. since it's EOL, I am  gonna close this. please let me know if you have a trouble with 1.20 or later :smiley:
