### ISSUE TITLE
Official Ubuntu Repos only install 1.1

### ISSUE THREAD

**Issue by ldanielw1** [cri-o/cri-o#5526]
Latest installs with `apt-get` on ubuntu only install 1.1 - is there any chance we can get an update up to 1.5?

**Comment by haircommander** [comment]
sorry, what is at version 1.1? I don't think cri-o technically ever released a 1.1 (we skipped from 1.0 to 1.9 to match kubernetes releases)

**Comment by ldanielw1** [comment]
oh man I'm so sorry, posted in the wrong repo. Please ignore this ticket...

**Comment by haircommander** [comment]
all good, hope you find your issue
