### ISSUE TITLE
Packaging for AlmaLinux 8 requested

### ISSUE THREAD

**Issue by AndreasDavour** [cri-o/cri-o#5553]
**Description**

Considering the status of CentOS 8 having changed, it would be quite interesting to have AlmaLinux 8 as a supported packaged operating system. 

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by haircommander** [comment]
we're limited by the distros SUSE's OBS (build.opensuse.org) supports. However, I see no reason why the centos 8 or centos stream 8 versions wouldn't install correctly. Can you give those a try?

**Comment by AndreasDavour** [comment]
I did and got a bunch of issues with the repos, and I did not get it to work by just substituting for CentOS 8. 
I guess I could dig deeper into why, and probably will have to then. It does look like there's something wrong with the repos, though when I took a quite peek with a browser.

**Comment by AndreasDavour** [comment]
I did some more tests, and managed to get CentOS 8 settings to work on AlmaLinux. It was a copy and paste error.
