### ISSUE TITLE
cri-o Debian_11 repository - Add armhf support

### ISSUE THREAD

**Issue by grunlab** [cri-o/cri-o#5562]
Could you please add armhf support inside cri-o Debian_11 repository:
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.22/Debian_11/

My configuration:
- hdw: odroid hc1 (armhf)
- os: armbian-bullseyes (debian 11) --> https://www.armbian.com/odroid-hc1/

Note: when running armbian-buster (debian 10), pointing to Raspbian_10 cri-o repo is working perfectly:
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.22/Raspbian_10/

Maybe Raspbian_11 cri-o repo should also be created?

**Comment by grunlab** [comment]
armv7l should be ok:
```
adrien@worker-02:~$ uname -a
Linux worker-02 5.4.160-odroidxu4 #21.08.6 SMP PREEMPT Mon Nov 22 12:18:25 UTC 2021 armv7l GNU/Linux
```

**Comment by haircommander** [comment]
I've added them!

**Comment by grunlab** [comment]
Perfect, armhf packages are now available for the version 1.22:
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.22/Debian_11/

I was able to install cri-o on my host:
```
adrien@worker-02:~$ uname -a
Linux worker-02 5.4.160-odroidxu4 #21.08.6 SMP PREEMPT Mon Nov 22 12:18:25 UTC 2021 armv7l GNU/Linux

adrien@worker-02:~$ cat /etc/apt/sources.list.d/cri-o.list 
deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_11/ /
deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.22/Debian_11/ /

adrien@worker-02:~$ sudo crictl version
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.22.1
RuntimeApiVersion:  v1alpha2

adrien@worker-02:~$ sudo systemctl status crio
● crio.service - Container Runtime Interface for OCI (CRI-O)
     Loaded: loaded (/lib/systemd/system/crio.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-01-25 20:21:16 CET; 17min ago
       Docs: https://github.com/cri-o/cri-o
   Main PID: 15882 (crio)
      Tasks: 17
     Memory: 9.3M
        CPU: 1.632s
     CGroup: /system.slice/crio.service
             └─15882 /usr/bin/crio
```

Could you please make sure that armv7l will also be available for the next releases --> currently missing in 1.23 : https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.23/Debian_11/

**Comment by haircommander** [comment]
ah yes I'll update 1.23. future releases will be built off of that so they should inherit them after

**Comment by grunlab** [comment]
Perfect. Thank you.
