### ISSUE TITLE
Error: error creating mtab directory

### ISSUE THREAD

**Issue by materkey** [cri-o/cri-o#5563]
**Description**

**Steps to reproduce the issue:**
1. run container image - https://github.com/remote-android/redroid-doc

**Describe the results you received:**
mtab error, container do not running

**Describe the results you expected:**
container is running

**Additional information you deem important (e.g. issue happens only occasionally):**
this problem fixed in podman 
https://github.com/containers/podman/pull/12267/commits/9f4d63f91bba116d2deb85a0af041611d0b85082
https://github.com/containers/podman/issues/12189
**Output of `crio --version`:**

```
crio version 1.22.0
Version:          1.22.0
GitCommit:        6becad23eadd7dfdd25fd8df386bf3b706cf7758
GitTreeState:     clean
BuildDate:        2021-10-06T16:29:17Z
GoVersion:        go1.16.8
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        exclude_graphdriver_devicemapper, seccomp
SeccompEnabled:   true
AppArmorEnabled:  false
```
it is also reproducible in latest version
**Additional environment details (AWS, VirtualBox, physical, etc.):**
openstack kvm vm

**Comment by haircommander** [comment]
@QiWang19  could you PTAL

**Comment by materkey** [comment]
https://github.com/cri-o/cri-o/pull/5564#issuecomment-1020455754
