### ISSUE TITLE
Is there a lib like `github.com/containerd/containerd` for using?

### ISSUE THREAD

**Issue by jwcesign** [cri-o/cri-o#5565]
I want to use the lib for calling api of crio, is there any lib like `github.com/containerd/containerd`?
Like this: https://pkg.go.dev/github.com/containerd/containerd

**Comment by haircommander** [comment]
the main way of talking to CRI-O is through the CRI API grpc socket. you can see a reference client implementation in [crictl](https://github.com/kubernetes-sigs/cri-tools/tree/master/cmd/crictl).

**Comment by jwcesign** [comment]
Hi, @haircommander , I want to call pause/unpause for cri-o, but in CRI API, there is no this function. Is there a way to do this?

**Comment by haircommander** [comment]
ah I see. We don't technically support any operations that aren't needed by the CRI. what are you trying to do? it's possible you could pause the underlying container, do your work, and unpause it. I've never tried it and it's possible the kubelet could get confused, but if you're already subverting the kubelet and calling operations directly in cri-o that'll likely happen anyway

**Comment by jwcesign** [comment]
Thanks @haircommander , I see the podman can call pause command, I will check it how it pause the containers.
