### ISSUE TITLE
Checksum details for the releases.

### ISSUE THREAD

**Issue by hasan4791** [cri-o/cri-o#5600]
Hello team,

I'm looking for checksum details for the release in this link and not able find one. We need this to check the file integrity after every download.

https://github.com/cri-o/cri-o/releases/tag/v1.21.4

Thank you

**Comment by haircommander** [comment]
hello @hasan4791 we don't currently post checksum values. I see it as a good RFE, but it may take some work to automate, or add to the manual overhead of doing cri-o releases (which is not negligible). Do you have any interest in automating checksum generation and uploading with our github actions workflow?

**Comment by hasan4791** [comment]
@haircommander here you go sir.

**Comment by hasan4791** [comment]
@haircommander I can see the PR is merged to main & cherrypicked to the releases but getting this error from UI.

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>
No such object: cri-o/artifacts/cri-o.amd64.53ada6de691b5c48f03b7975f3e8d5216fc13cea.tar.gz.sha256sum
</Details>
</Error>
```

**Comment by haircommander** [comment]
@saschagrunert can you tell why this failed https://github.com/cri-o/cri-o/runs/5321158327?check_suite_focus=true?

**Comment by saschagrunert** [comment]
Yeah we should add them to the artifacts passed around in the CI. A fix is incoming in https://github.com/cri-o/cri-o/pull/5844
