### ISSUE TITLE
Impelemt none-CRI API - PauseContainer

### ISSUE THREAD

**Issue by jwcesign** [cri-o/cri-o#5632]
## Background
for podman and containerd, both provider the api to pause/unpause running processing in container.
Like: https://docs.podman.io/en/latest/_static/api.html#operation/ContainerPauseLibpod
There is many usecase for customers. For my team, we use it to set the instance to idle state(where process is moved to freeze cgroup)

## What I want
Maybe the implementation need to be considered, it's not standard CRI interface.

**Comment by jwcesign** [comment]
cc @haircommander

**Comment by haircommander** [comment]
I find myself wondering if one can use runc to directly pause the containers from underneath cri-o. you should be able to do so with `runc pause $ctr_id`. Can you  give that a try and let me know if that works for you?

**Comment by haircommander** [comment]
related to https://github.com/cri-o/cri-o/issues/5565

**Comment by haircommander** [comment]
so this is for an autoscaling situation where you want to pause unneeded containers when they're not being used?

**Comment by jwcesign** [comment]
I check the oci level code of cri-o, I think it's possible to do this with `runc pause $ctr_id`.
Yes, it's related with autoscaling in knative(a serverless framework).  the situation is:
* there is a sidecar in pod, it's a reverse proxy, all requests to user-container will pass this sidecar first.
* when the sidecar found there is no request, it will call cri level to pause user-container for saving cpu cost(like idle state).
* when the sidecar found the request comes, it will cal cri level to unpause user-container for serving.

Yes, maybe we can call oci level to pause/unpause, but I prefer to call it on cri level, because k8s call cri level.

**Comment by jwcesign** [comment]
If u agree, I can take this part and implement it. Just like `curl -v --unix-socket /var/run/crio/crio.sock http://localhost/info`

**Comment by jwcesign** [comment]
So what's about the processing?

**Comment by jwcesign** [comment]
I not try, but I check the code: https://github.com/cri-o/cri-o/blob/120c7d215ea49b2f20651d454837550928a85b6d/internal/oci/oci.go#L309

**Comment by saschagrunert** [comment]
@jwcesign have there been efforts to support it in the CRI? I have another use case in mind to pause a container.

**Comment by jwcesign** [comment]
@saschagrunert Still no, what usecase u have?

**Comment by saschagrunert** [comment]
> @saschagrunert Still no, what usecase u have? If @cri-o/cri-o-maintainers accept this feature, I would like to implement it. Because we need this to save cpu when idle.

I had a use case for https://github.com/cri-o/cri-o/issues/5720, but pausing the container caused issues together with the handing of them in Kubernetes. Therefore I decided to stop the containers.

**Comment by jwcesign** [comment]
@saschagrunert I see, but it looks like there is no way to do this now. I think for your usecase, u only can can cri level interface.

**Comment by jwcesign** [comment]
Hi, @haircommander , so maybe we can do this now(I am willing to implement this)? like `/info`?
