### ISSUE TITLE
REQUEST: New reviewer status for @klihub

### ISSUE THREAD

**Issue by klihub** [cri-o/cri-o#5640]
### GitHub Username

@klihub

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have one sponsor from the list of approvers in at least one OWNERS file within one of the CRI-O repository
- [X] I have spoken to my sponsor ahead of this application, and they have agreed to sponsor my application

### Sponsor

@haircommander

### List of contributions to the CRI-O project

- Merged PRs:
  - #5263
  - #5548
  - #5579
  - #5586
- Pending PRs:
  - #5571
  - #5596
  - #5639
- PRs still in draft/experimental state:
  - #5318

**Comment by haircommander** [comment]
+1 I've appreciated your looking into CI failures and investigating new features related to devices and NRI

**Comment by fidencio** [comment]
+1 from me a well.

**Comment by saschagrunert** [comment]
+1 !

**Comment by fidencio** [comment]
Closing this one it's been solved by #5654!

Thanks for becoming an official reviewer of the project!
