### ISSUE TITLE
REQUEST: New membership for @QiWang19

### ISSUE THREAD

**Issue by QiWang19** [cri-o/cri-o#5642]
### GitHub Username

@QiWang19

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have one sponsor from the list of approvers in at least one OWNERS file within one of the CRI-O repository
- [X] I have spoken to my sponsor ahead of this application, and they have agreed to sponsor my application

### Sponsor

@mrunalp

### List of contributions to the CRI-O project

PR authored: 
- https://github.com/cri-o/cri-o/pull/5577
- https://github.com/cri-o/cri-o/pull/5423

**Comment by haircommander** [comment]
+1, here are a [couple of other commits[(https://github.com/cri-o/cri-o/commits?author=QiWang19) you've authored, not to mention having knowledge about c/image

**Comment by saschagrunert** [comment]
+1 :partying_face:

**Comment by fidencio** [comment]
Yay!
+1.
