### ISSUE TITLE
REQUEST: New membership for wgahnagl

### ISSUE THREAD

**Issue by wgahnagl** [cri-o/cri-o#5649]
### GitHub Username

@wgahnagl

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have one sponsor from the list of approvers in at least one OWNERS file within one of the CRI-O repository
- [X] I have spoken to my sponsor ahead of this application, and they have agreed to sponsor my application

### Sponsor

@haircommander

### List of contributions to the CRI-O project

#3933
#3960
#4257
#4290
#4402
#4529
#5007

**Comment by haircommander** [comment]
+1 you've worked on a number of structural changes and bug fixes. #5007 was especially of note because of how annoying the task was :smiley:

**Comment by saschagrunert** [comment]
+1 !

**Comment by fidencio** [comment]
+1

**Comment by fidencio** [comment]
Closing this one it's been solved by #5654!

Thanks for becoming an official reviewer of the project!
