### ISSUE TITLE
cri-o installation for version 1.20 on CentOS 7 fails 

### ISSUE THREAD

**Issue by Markus-SWAG** [cri-o/cri-o#5712]
Trying to install cri-o based on https://github.com/cri-o/cri-o/blob/main/install.md#other-yum-based-operating-systems fails. 

    # export VERSION=1.20
    # export OS=CentOS_7
 
 Output:
 
    # yum install cri-o
Loaded plugins: fastestmirror
Repository docker-ce-stable is listed more than once in the configuration
http://mirror.centos.org/centos/7/virt/x86_64/xen-46/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please create a bug on https://bugs.centos.org/

devel_kubic_libcontainers_stable                                                                                                                                                       | 1.3 kB  00:00:00
devel_kubic_libcontainers_stable_cri-o_1.20                                                                                                                                            | 1.3 kB  00:00:00
imeyer_runit/x86_64/signature                                                                                                                                                          |  836 B  00:00:00
imeyer_runit/x86_64/signature                                                                                                                                                          | 1.0 kB  00:00:01 !!!
(1/2): devel_kubic_libcontainers_stable_cri-o_1.20/primary                                                                                                                             | 1.7 kB  00:00:00
(2/2): devel_kubic_libcontainers_stable/primary                                                                                                                                        |  13 kB  00:00:01
Loading mirror speeds from cached hostfile
 * base: download.cf.centos.org
 * centos-virt-xen-epel: d2lzkl7pfhq30w.cloudfront.net
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: download.cf.centos.org
 * updates: download.cf.centos.org
devel_kubic_libcontainers_stable                                                                                                                                                                        39/39
devel_kubic_libcontainers_stable_cri-o_1.20                                                                                                                                                               5/5
Resolving Dependencies
--> Running transaction check
---> Package cri-o.x86_64 0:1.20.6-7.2.el7 will be installed
--> Processing Dependency: containers-common >= 1:0.1.31-14 for package: cri-o-1.20.6-7.2.el7.x86_64
--> Processing Dependency: containernetworking-plugins >= 0.7.5-1 for package: cri-o-1.20.6-7.2.el7.x86_64
--> Processing Dependency: conmon >= 2.0.2-1 for package: cri-o-1.20.6-7.2.el7.x86_64
--> Running transaction check
---> Package conmon.x86_64 2:2.0.29-1.el7.1.2 will be installed
---> Package containernetworking-plugins.x86_64 0:1.0.0-0.2.rc1.el7.1.2 will be installed
---> Package containers-common.noarch 4:1-18.el7.22.1 will be installed
--> Processing Dependency: slirp4netns for package: 4:containers-common-1-18.el7.22.1.noarch
--> Processing Dependency: oci-runtime for package: 4:containers-common-1-18.el7.22.1.noarch
Package 2:runc-1.0.1-0.el7.1.3.x86_64 is obsoleted by containerd.io-1.4.12-3.1.el7.x86_64 which is already installed
--> Processing Dependency: fuse-overlayfs for package: 4:containers-common-1-18.el7.22.1.noarch
--> Running transaction check
---> Package containerd.io.x86_64 0:1.4.12-3.1.el7 will be updated
---> Package containerd.io.x86_64 0:1.4.13-3.1.el7 will be an update
---> Package containers-common.noarch 4:1-18.el7.22.1 will be installed
--> Processing Dependency: oci-runtime for package: 4:containers-common-1-18.el7.22.1.noarch
Package 2:runc-1.0.1-0.el7.1.3.x86_64 is obsoleted by containerd.io-1.4.12-3.1.el7.x86_64 which is already installed
---> Package fuse-overlayfs.x86_64 0:1.5.0-1.el7.1.1 will be installed
--> Processing Dependency: libfuse3.so.3(FUSE_3.2)(64bit) for package: fuse-overlayfs-1.5.0-1.el7.1.1.x86_64
--> Processing Dependency: libfuse3.so.3(FUSE_3.0)(64bit) for package: fuse-overlayfs-1.5.0-1.el7.1.1.x86_64
--> Processing Dependency: fuse3 for package: fuse-overlayfs-1.5.0-1.el7.1.1.x86_64
--> Processing Dependency: libfuse3.so.3()(64bit) for package: fuse-overlayfs-1.5.0-1.el7.1.1.x86_64
---> Package slirp4netns.x86_64 0:1.1.8-4.el7.7.1 will be installed
--> Processing Dependency: libslirp.so.0(SLIRP_4.1)(64bit) for package: slirp4netns-1.1.8-4.el7.7.1.x86_64
--> Processing Dependency: libslirp.so.0(SLIRP_4.0)(64bit) for package: slirp4netns-1.1.8-4.el7.7.1.x86_64
--> Processing Dependency: libslirp.so.0()(64bit) for package: slirp4netns-1.1.8-4.el7.7.1.x86_64
--> Running transaction check
---> Package containers-common.noarch 4:1-18.el7.22.1 will be installed
--> Processing Dependency: oci-runtime for package: 4:containers-common-1-18.el7.22.1.noarch
Package 2:runc-1.0.1-0.el7.1.3.x86_64 is obsoleted by containerd.io-1.4.12-3.1.el7.x86_64 which is already installed
---> Package fuse3.x86_64 0:3.6.1-4.el7 will be installed
--> Processing Dependency: /etc/fuse.conf for package: fuse3-3.6.1-4.el7.x86_64
---> Package fuse3-libs.x86_64 0:3.6.1-4.el7 will be installed
---> Package libslirp.x86_64 0:4.3.1-4.el7 will be installed
--> Running transaction check
---> Package containers-common.noarch 4:1-18.el7.22.1 will be installed
--> Processing Dependency: oci-runtime for package: 4:containers-common-1-18.el7.22.1.noarch
Package 2:runc-1.0.1-0.el7.1.3.x86_64 is obsoleted by containerd.io-1.4.12-3.1.el7.x86_64 which is already installed
---> Package fuse.x86_64 0:2.9.2-11.el7 will be installed
--> Finished Dependency Resolution
Error: Package: 4:containers-common-1-18.el7.22.1.noarch (devel_kubic_libcontainers_stable)
           Requires: oci-runtime
           Available: 2:runc-1.0.1-0.el7.1.3.x86_64 (devel_kubic_libcontainers_stable)
               oci-runtime
           Available: runc-1.0.0-64.rc8.el7.centos.x86_64 (extras)
               Not found
           Available: runc-1.0.0-65.rc8.el7.centos.x86_64 (extras)
               Not found
           Available: runc-1.0.0-67.rc10.el7_8.x86_64 (extras)
               Not found
           Available: runc-1.0.0-69.rc10.el7_9.x86_64 (extras)
               Not found
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by haircommander** [comment]
does this work if you don't have docker-ce installed?

**Comment by Markus-SWAG** [comment]
Even on machines, where docker-ce was never installed, the installation fails.

The only way of installing that works is using this link:
[Add repository and install manually](https://software.opensuse.org/download/package?package=cri-o&project=devel%3Akubic%3Alibcontainers%3Astable%3Acri-o%3A1.20#manualCentOS) | For CentOS 7 run the following as root
`cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.20/CentOS_7/devel:kubic:libcontainers:stable:cri-o:1.20.repo
yum install cri-o`

This is basically the same installation as in https://github.com/cri-o/cri-o/blob/main/install.md#other-yum-based-operating-systems, leaving out the instantiation of the repo as it is done in the first step:
`curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/devel:kubic:libcontainers:stable.repo`.
 What is missing, if that repo is not used? Is the cri-o installation missing something?

**Comment by Markus-SWAG** [comment]
I'm not quite sure whether I get your point. 
By "the other repo" you mean  `devel:kubic:libcontainers:stable.repo`?
If that is added then the issue occurs. 
The issue does not occur if that is left out.

**Comment by haircommander** [comment]
oh sorry I misunderstood. yeah that is not good. good news: you can install cri-o, right? bad news, the package is messed up. I'll take a look

**Comment by Markus-SWAG** [comment]
And again good news: I overlooked that docker-ce repo has been there twice, when I remove both of them it seems to work. 
Sorry for not seeing this earlier and wasting your time ...

**Comment by Markus-SWAG** [comment]
I had another test to confirm. 
cri-o can be only installed, if the Docker CE repositories are completely removed, and the docker-ce*.repo files from /etc/yum.repos.d/ have been removed.
This conflicts with the document [Running CRI-O on kubernetes cluster](https://github.com/cri-o/cri-o/blob/main/tutorials/kubernetes.md#running-cri-o-on-kubernetes-cluster). It contains "docker" commands, but does not really say that Docker has to be uninstalled and all repository links have to disappear before installing cri-o.
Just one more question: Is it really intended, that cri-o cannot be installed correctly, if the Docker repositories are there?

**Comment by hasan4791** [comment]
Just few more logs, tried installing crio 1.20 on centos:7 container image & found that the rpms are not getting downloaded from the "devel_kubic_libcontainers_stable" package path, though the install command lists the rpms under that path. Here are the list of RPMs failed to download & attached complete log.
```
Error downloading packages:
  containernetworking-plugins-1.0.0-0.2.rc1.el7.1.2.x86_64: [Errno 256] No more mirrors to try.
  2:runc-1.0.1-1.el7.2.1.x86_64: [Errno 256] No more mirrors to try.
  slirp4netns-1.1.8-4.el7.7.1.x86_64: [Errno 256] No more mirrors to try.
  2:conmon-2.1.0-2.3.1.x86_64: [Errno 256] No more mirrors to try.
  4:containers-common-1-19.el7.28.1.noarch: [Errno 256] No more mirrors to try.
  fuse-overlayfs-1.5.0-1.el7.1.1.x86_64: [Errno 256] No more mirrors to try.
  cri-o-1.20.7-3.1.el7.x86_64: [Errno 256] No more mirrors to try.
  libslirp-4.3.1-4.el7.x86_64: [Errno 256] No more mirrors to try.
```

PS: I haven't configured any mirrors.
[install.logs.txt](https://github.com/cri-o/cri-o/files/8523625/install.logs.txt)

**Comment by Markus-SWAG** [comment]
> I had another test to confirm. cri-o can be only installed, if the Docker CE repositories are completely removed, and the docker-ce*.repo files from /etc/yum.repos.d/ have been removed. This conflicts with the document [Running CRI-O on kubernetes cluster](https://github.com/cri-o/cri-o/blob/main/tutorials/kubernetes.md#running-cri-o-on-kubernetes-cluster). It contains "docker" commands, but does not really say that Docker has to be uninstalled and all repository links have to disappear before installing cri-o. Just one more question: Is it really intended, that cri-o cannot be installed correctly, if the Docker repositories are there?

Any news on cri-o installation conflicting with an existing Docker installation, when changing from Docker runtime to cri-o?

**Comment by haircommander** [comment]
@Markus-SWAG I have updated the containers common package to allow installing next to docker-ce (by accepting runc as satisfying oci-runtime). Can you attempt to install?

@hasan4791 what's `yum repolist`

**Comment by Markus-SWAG** [comment]
@haircommander I attempted to install and it worked. Thanks.

**Comment by Markus-SWAG** [comment]
@haircommander Thanks for your support.
