### ISSUE TITLE
/tmp/kubeadm.yaml: no such file or directory

### ISSUE THREAD

**Issue by broosted** [cri-o/cri-o#5725]
following kubeadm guide with cri-o and getting error with script provided for configuring kubelet
on ec2
FAILED! => {"changed": true, "cmd": "./config.sh", "delta": "0:00:00.718120", "end": "2022-03-15 17:31:46.876402", "msg": "non-zero return code", "rc": 1, "start": "2022-03-15 17:31:46.158282", "stderr": "Error: stat /tmp/kubeadm.yaml: no such file or directory", "stderr_lines": ["Error: stat /tmp/kubeadm.yaml: no such file or directory"], "stdout": "Printing to /tmp/kubeadm.yaml", "stdout_lines": ["Printing to /tmp/kubeadm.yaml"]}

ansible playbook
---
- hosts: aws_ec2
  become: yes
  tasks:
    - name: copy file
      ansible.builtin.copy:
        src: config.sh
        dest: config.sh
        mode: 'u+x'
    - name: get update
      shell: 
          "./config.sh"

[config.sh.txt](https://github.com/cri-o/cri-o/files/8255866/config.sh.txt)

**Comment by haircommander** [comment]
hm what version of kubeadm are you using? if I don't have a /tmp/kubeadm.yaml my script works fine. Have you tried setting KUBEADM_CONFIG to a different path?

**Comment by broosted** [comment]
1.23
yes the script works fine if I copy it and run it directly in ec2 console. it might be a permission issue

**Comment by haircommander** [comment]
did setting a different KUBEADM_CONFIG path help?

**Comment by broosted** [comment]
yes I had to dodge /tmp directory and any root paths because sudo on ec2 wasn't working so I changed the KUBEADM_CONFIG in the script:

`#!/bin/bash                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                              
set -euo pipefail                                                                                                                                                                                                                             
                                                                                                                                                                                                                                              
KUBEADM_CONFIG="${1-kubeadm.yaml}"                                                                                                                                                                                                              
echo "Printing to $KUBEADM_CONFIG"                                                                                                                                                                                                                   
                                                                                                                                                                                                                                              
if [ -d "$KUBEADM_CONFIG" ]; then                                                                                                                                                                                                                    
    echo "$KUBEADM_CONFIG is a directory!"                                                                                                                                                                                                           
    exit 1                                                                                                                                                                                                                                    
fi                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                              
if [ ! -d $(dirname "$KUBEADM_CONFIG") ]; then                                                                                                                                                                                                       
    echo "please create directory $(dirname $KUBEADM_CONFIG)"                                                                                                                                                                                        
    exit 1                                                                                                                                                                                                                                    
fi                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                              
if [ ! $(which yq) ]; then                                                                                                                                                                                                                    
    echo "please install yq"                                                                                                                                                                                                                  
    exit 1                                                                                                                                                                                                                                    
fi                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                              
if [ ! $(which kubeadm) ]; then                                                                                                                                                                                                               
    echo "please install kubeadm"                                                                                                                                                                                                             
    exit 1                                                                                                                                                                                                                                    
fi                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                              
kubeadm config print init-defaults --component-configs=KubeletConfiguration > "$KUBEADM_CONFIG"                                                                                                                                                      
yq -i eval 'select(.nodeRegistration.criSocket) |= .nodeRegistration.criSocket = "unix:///var/run/crio/crio.sock"' "$KUBEADM_CONFIG"
`

**Comment by haircommander** [comment]
future reference, I believe you can call `config.sh kubeadm.yaml` as it takes the value of `$1` if specified. I forgot about that

is this resolved @broosted ?

**Comment by broosted** [comment]
yes thanks @haircommander

**Comment by haircommander** [comment]
excellent to hear!
