### ISSUE TITLE
cri-o packages are missing for 1.21 and Ubuntu 20.04 LTS 

### ISSUE THREAD

**Issue by Quarky9** [cri-o/cri-o#5730]
### What happened?

Trying to install cri-o fails on Ubuntu 20.04 LTS using the opensuse.org mirrors.

Missing see: 
https://mirrorcache.opensuse.org/download/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.21/xUbuntu_20.04/

V 1.20 are available:
https://mirrorcache.opensuse.org/download/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.20/xUbuntu_20.04/
or V1.22
https://mirrorcache.opensuse.org/download/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.22/xUbuntu_20.04/

### What did you expect to happen?

cri-o to install like the days before.

### How can we reproduce it (as minimally and precisely as possible)?

compare mirror content.

### CRI-O and Kubernetes version

<details>

```
V1.21
```

</details>

### OS version

<details>

```Ubuntu 20.04 LTS
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by haircommander** [comment]
oops, sorry, missed a step and they weren't building right. I have updated the builds so things should be populated shortly

**Comment by Quarky9** [comment]
Thank you so much for quick turn around ! Much appreciated. Just tested and seems work at least for amd64 which I tested.

**Comment by haircommander** [comment]
happy to help!
