### ISSUE TITLE
Unable to install cri-o on Raspberry Pi OS

### ISSUE THREAD

**Issue by fuele** [cri-o/cri-o#5743]
### What happened?

I'm following the instructions on installing cri-o 1.23 with apt on Raspberry Pi OS 11, 64 bit and I've come across a dependency that cannot be resolved.
```
$ sudo apt-get install cri-o cri-o-runc
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cri-o:armhf : Depends: containers-common:armhf (>= 0.1.27) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

 It appears that the apt repository ` https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Raspbian_10` only has version `100:1-22` of containers-common when it needs to be at least version 0.1.27. I'm not quite sure why they have a different versioning schema.

I don't know if this is something this group can fix, or if I have to go track down the folks who manage the opensuse repository. In which case I'd appreciate if you could point me in their direction.

### What did you expect to happen?

To install cri-o successfully

### How can we reproduce it (as minimally and precisely as possible)?

- On a raspberry pi 4 model b
- Run
```
export OS=Raspbian_10
export VERSION=1.23

echo "deb [signed-by=/usr/share/keyrings/libcontainers-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
echo "deb [signed-by=/usr/share/keyrings/libcontainers-crio-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.list

mkdir -p /usr/share/keyrings
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | gpg --dearmor -o /usr/share/keyrings/libcontainers-archive-keyring.gpg
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/Release.key | gpg --dearmor -o /usr/share/keyrings/libcontainers-crio-archive-keyring.gpg

apt-get update
apt-get install cri-o cri-o-runc
```

### Anything else we need to know?

Additionally, Raspberry Pi OS has version 11 out now. I can see that the second APT repository (https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/) has Raspbian_11 as an option, but the first APT repository (https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/) does not.

I tried both setting OS=Raspbian_10 and mixing and matching Raspbian_10 and Raspbian_11.

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# paste output here
```

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/arm64"}
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux pi4 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by haircommander** [comment]
oh goodness, I'm sorry @fuele I have just seen this. Do any of the debian installation paths work for you? I don't know which knob I need to enable to help for `armhf` I don't see any targets for it

**Comment by fuele** [comment]
I tried using `VERSION=1.23` and `OS=Debian_11`  and I was able to install crio successfully.

**Comment by fuele** [comment]
I guess we could close it. The packages still aren't up to date, but there is a workaround.
