### ISSUE TITLE
Security advisory received for CRI-O vulnerability in AKS but unable to work out if that affects us

### ISSUE THREAD

**Issue by asyedtri** [cri-o/cri-o#5744]
### What happened?

we have received following advisory https://github.com/cri-o/cri-o/security/advisories/GHSA-6x2m-w449-qwx7

It says that it affects versions greater than 1.19.0 then it says Patched versions are 1.19.6, 1.20.7, 1.21.6, 1.22.3, 1.23.2, 1.24.0

we have AKS version 1.20.13. as we are few versions ahead in the release 1.20.x It looks like we shouldnt be affected but could you confirm this?

Thanks

### What did you expect to happen?

More clarity in the advisory

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# paste output here
```

```console
$ kubectl --version
# paste output here
```
1.20.13
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>
Azure Kubernetes Service version 1.20.13

**Comment by haircommander** [comment]
that looks like a version of AKS, not of cri-o. Can you do a `kubectl get nodes -o wide`? that should show the runtime version

**Comment by asyedtri** [comment]
***@***.***


Thanks Peter,



Ali Syed​
Azure DevOps Engineer
e: ***@***.******@***.***>
w: www.tritrials.com<http://www.tritrials.com/>
***@***.***<http://www.tritrials.com/>
***@***.***<https://www.linkedin.com/company/triumph-research-intelligence/>
***@***.***<https://twitter.com/TRI_OPRA_RBM>
***@***.***<http://www.tritrials.com/>
Any views or opinions presented in this e-mail are solely those of the author and do not necessarily represent those of Triumph Research Intelligence Limited or any other company in its corporate group. The information in this e-mail is confidential and is intended solely for the recipient. Access, copying or re-use of information in it by anyone else is unauthorised. If you are not the intended recipient please delete the e-mail or inform the sender by reply.

Registered office:  1 Signet Court, Swanns Road, Cambridge, CB5 8LA. Registered in England & Wales under No. 08718740.

**Comment by asyedtri** [comment]
Peter

Could you respond to this ticket please?

We just want to make sure that us being on version 1.20.13 will not be affected by this security threat. I have read that CRI-CO follows AKS version, so it seems to be the case that we are covered but we want to be certain about it.

Thanks,

Ali Syed​
Azure DevOps Engineer
e: ***@***.******@***.***>
w: www.tritrials.com<http://www.tritrials.com/>
***@***.***<http://www.tritrials.com/>
***@***.***<https://www.linkedin.com/company/triumph-research-intelligence/>
***@***.***<https://twitter.com/TRI_OPRA_RBM>
***@***.***<http://www.tritrials.com/>
Any views or opinions presented in this e-mail are solely those of the author and do not necessarily represent those of Triumph Research Intelligence Limited or any other company in its corporate group. The information in this e-mail is confidential and is intended solely for the recipient. Access, copying or re-use of information in it by anyone else is unauthorised. If you are not the intended recipient please delete the e-mail or inform the sender by reply.

Registered office:  1 Signet Court, Swanns Road, Cambridge, CB5 8LA. Registered in England & Wales under No. 08718740.

From: Ali Syed
Sent: 21 March 2022 13:35
To: cri-o/cri-o ***@***.***>; cri-o/cri-o ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [cri-o/cri-o] Security advisory received for CRI-O vulnerability in AKS but unable to work out if that affects us (Issue #5744)

***@***.***


Thanks Peter,



Ali Syed​
Azure DevOps Engineer
e: ***@***.******@***.***>
w: www.tritrials.com<http://www.tritrials.com/>
***@***.***<http://www.tritrials.com/>
***@***.***<https://www.linkedin.com/company/triumph-research-intelligence/>
***@***.***<https://twitter.com/TRI_OPRA_RBM>
***@***.***<http://www.tritrials.com/>
Any views or opinions presented in this e-mail are solely those of the author and do not necessarily represent those of Triumph Research Intelligence Limited or any other company in its corporate group. The information in this e-mail is confidential and is intended solely for the recipient. Access, copying or re-use of information in it by anyone else is unauthorised. If you are not the intended recipient please delete the e-mail or inform the sender by reply.

Registered office:  1 Signet Court, Swanns Road, Cambridge, CB5 8LA. Registered in England & Wales under No. 08718740.

**Comment by asyedtri** [comment]
Hi

Can you please respond to this ticket?

Thanks

Ali Syed​
Azure DevOps Engineer
e: ***@***.******@***.***>
w: www.tritrials.com<http://www.tritrials.com/>
***@***.***<http://www.tritrials.com/>
***@***.***<https://www.linkedin.com/company/triumph-research-intelligence/>
***@***.***<https://twitter.com/TRI_OPRA_RBM>
***@***.***<http://www.tritrials.com/>
Any views or opinions presented in this e-mail are solely those of the author and do not necessarily represent those of Triumph Research Intelligence Limited or any other company in its corporate group. The information in this e-mail is confidential and is intended solely for the recipient. Access, copying or re-use of information in it by anyone else is unauthorised. If you are not the intended recipient please delete the e-mail or inform the sender by reply.

Registered office:  1 Signet Court, Swanns Road, Cambridge, CB5 8LA. Registered in England & Wales under No. 08718740.

From: Ali Syed
Sent: 22 March 2022 14:46
To: 'cri-o/cri-o' ***@***.***>; 'cri-o/cri-o' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [cri-o/cri-o] Security advisory received for CRI-O vulnerability in AKS but unable to work out if that affects us (Issue #5744)

Peter

Could you respond to this ticket please?

We just want to make sure that us being on version 1.20.13 will not be affected by this security threat. I have read that CRI-CO follows AKS version, so it seems to be the case that we are covered but we want to be certain about it.

Thanks,

Ali Syed​
Azure DevOps Engineer
e: ***@***.******@***.***>
w: www.tritrials.com<http://www.tritrials.com/>
***@***.***<http://www.tritrials.com/>
***@***.***<https://www.linkedin.com/company/triumph-research-intelligence/>
***@***.***<https://twitter.com/TRI_OPRA_RBM>
***@***.***<http://www.tritrials.com/>
Any views or opinions presented in this e-mail are solely those of the author and do not necessarily represent those of Triumph Research Intelligence Limited or any other company in its corporate group. The information in this e-mail is confidential and is intended solely for the recipient. Access, copying or re-use of information in it by anyone else is unauthorised. If you are not the intended recipient please delete the e-mail or inform the sender by reply.

Registered office:  1 Signet Court, Swanns Road, Cambridge, CB5 8LA. Registered in England & Wales under No. 08718740.

From: Ali Syed
Sent: 21 March 2022 13:35
To: cri-o/cri-o ***@***.******@***.***>>; cri-o/cri-o ***@***.******@***.***>>
Cc: Author ***@***.******@***.***>>
Subject: RE: [cri-o/cri-o] Security advisory received for CRI-O vulnerability in AKS but unable to work out if that affects us (Issue #5744)

***@***.***


Thanks Peter,



Ali Syed​
Azure DevOps Engineer
e: ***@***.******@***.***>
w: www.tritrials.com<http://www.tritrials.com/>
***@***.***<http://www.tritrials.com/>
***@***.***<https://www.linkedin.com/company/triumph-research-intelligence/>
***@***.***<https://twitter.com/TRI_OPRA_RBM>
***@***.***<http://www.tritrials.com/>
Any views or opinions presented in this e-mail are solely those of the author and do not necessarily represent those of Triumph Research Intelligence Limited or any other company in its corporate group. The information in this e-mail is confidential and is intended solely for the recipient. Access, copying or re-use of information in it by anyone else is unauthorised. If you are not the intended recipient please delete the e-mail or inform the sender by reply.

Registered office:  1 Signet Court, Swanns Road, Cambridge, CB5 8LA. Registered in England & Wales under No. 08718740.

**Comment by haircommander** [comment]
@asyedtri are you able to see my messages? what is the output of kubectl get nodes -o wide on an AKS 1.20.13 cluster

**Comment by asyedtri** [comment]
@haircommander responded to your mail from within outlook on Monday at 1335 and hearing back first time today at 1452. Now responding via Git portal. Looks like emails were lost between us. here's the output as you suggested


**kubectl get nodes -o wide**

**NAME                                STATUS   ROLES   AGE   VERSION    INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME**
aks-agentpool-32958352-vmss000000   Ready    agent   33d   v1.20.13   10.240.0.4    <none>        Ubuntu 18.04.6 LTS   5.4.0-1068-azure   containerd://1.4.12+azure-2

**Comment by haircommander** [comment]
@asyedtri it looks like you're using containerd `containerd://1.4.12+azure-2` so you are not affected
