### ISSUE TITLE
apt-get reports wrong file size for cri-o_1.23.2~0_amd64.deb in provo-mirror.opensuse.org

### ISSUE THREAD

**Issue by andrej-gomozov** [cri-o/cri-o#5802]
### What happened?

This is happening already several weeks without any resoltuion.
When attempting to install crio on Debian, getting such error.

```
Failed to fetch https://provo-mirror.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.23/xUbuntu_20.04/amd64/cri-o_1.23.2~0_amd64.deb  File has unexpected size (19924448 != 19927184). Mirror sync in progress? [IP: 91.193.113.70 443]
Hashes of expected file:
    - SHA256:fceaf56ef025b2d1d51e00b14be0c0672b90e57ef296885de262c158fcc45821
    - SHA1:e827019a0105650dcb76691670a0dfdb53ce9ad9 [weak]
    - MD5Sum:25280e0e961531115e4ed7e7e76dcdd3 [weak]
    - Filesize:19927184
```

### What did you expect to happen?

Successful installation of package.

### How can we reproduce it (as minimally and precisely as possible)?

Try to install it from repository https://provo-mirror.opensuse.org

### Anything else we need to know?

Opened issues in several places and was advised that problem seems to be in how cri-o is packaged, not a mirror sync problem.
See https://github.com/openSUSE/mirrorbrain/issues/71

Could be similar issue as in https://github.com/cri-o/cri-o/issues/5470 ?

### CRI-O and Kubernetes version

N/A

### OS version

N/A

### Additional environment details (AWS, VirtualBox, physical, etc.)

N/A

**Comment by haircommander** [comment]
gah I am not sure how it happened. I've been trying really hard to bump the version number when I change anything. I don't remember having changed anything after it was first published. I'll try to be better about it.

meanwhile, I've released cri-o_1.23.2~1 on the 1.23 stream. I hope that fixes it for you

**Comment by andrej-gomozov** [comment]
@haircommander yes, it works now. Thank you for quick fix :-)

**Comment by haircommander** [comment]
glad to hear!

**Comment by andrej-gomozov** [comment]
Hi @haircommander. Seems like this is happening again. Could you please check?

**Comment by haircommander** [comment]
darn, I rebuilt them again.. PTAL?

**Comment by andrej-gomozov** [comment]
@haircommander it's fine now, thanks :-)
