### ISSUE TITLE
offline install CRI-O

### ISSUE THREAD

**Issue by willzhang** [cri-o/cri-o#5805]
### What happened?

the network is not good，how to offline install CRI-O with binary package.

like containerd:

https://github.com/containerd/nerdctl/releases

### What did you expect to happen?

offline install CRI-O

### How can we reproduce it (as minimally and precisely as possible)?

is this enough ,i want know the official docs for offline installation

```
tar Cxzvvf /usr/local cri-o.amd64.c03e400ec69fb22256a1b9c8f3ae8011a3539582.tar.gz --strip=1
cd 
cp /usr/local/contrib/crio.service /etc/systemd/system/
systemctl start crio
```

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
latest
```

```console
$ kubectl --version
# paste output here
```

</details>

### OS version

<details>

```console
ubuntu 20.04 LTS
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
physical
</details>

**Comment by haircommander** [comment]
you should be able to run the install binary included in that bundle according to https://github.com/cri-o/cri-o/tree/main/contrib/bundle#cri-o-static-build-bundle

**Comment by haircommander** [comment]
and that will do the required installation of all of the binaries and config files

**Comment by willzhang** [comment]
> 

it's confuse me , i don't know how to use it ， the instlal script have many env in it.

```
root@ubuntu:~# git clone https://github.com/cri-o/cri-o --depth=1
root@ubuntu:~# cd cri-o/contrib/bundle
root@ubuntu:~/cri-o/contrib/bundle# chmod +x install
```

```
root@ubuntu:~/cri-o/contrib/bundle# sudo ./install
+ install -d -m 755 
install: cannot create directory ‘’: No such file or directory
+ install -D -m 755 -t  cni-plugins/*
install: cannot stat 'cni-plugins/*': No such file or directory
+ install -D -m 644 -t  contrib/10-crio-bridge.conf
install: cannot stat 'contrib/10-crio-bridge.conf': No such file or directory
+ install -D -m 755 -t  bin/conmon
install: cannot stat 'bin/conmon': No such file or directory
+ install -D -m 755 -t  bin/crictl
install: cannot stat 'bin/crictl': No such file or directory
+ install -d -m 755 
install: cannot create directory ‘’: No such file or directory
+ install -d -m 755 
install: cannot create directory ‘’: No such file or directory
+ install -d -m 755 
install: cannot create directory ‘’: No such file or directory
+ install -d -m 755 
install: cannot create directory ‘’: No such file or directory
+ install -D -m 755 -t  bin/crio-status
install: cannot stat 'bin/crio-status': No such file or directory
+ install -D -m 755 -t  bin/crio
install: cannot stat 'bin/crio': No such file or directory
+ install -D -m 644 -t  etc/crictl.yaml
install: cannot stat 'etc/crictl.yaml': No such file or directory
+ install -D -m 644 -t  etc/crio-umount.conf
install: cannot stat 'etc/crio-umount.conf': No such file or directory
+ install -D -m 644 -t /crio etc/crio.conf
install: cannot stat 'etc/crio.conf': No such file or directory
+ install -D -m 644 -t /crio/crio.conf.d etc/10-crun.conf
install: cannot stat 'etc/10-crun.conf': No such file or directory
+ install -D -m 644 -t /man5 man/crio.conf.5
install: cannot stat 'man/crio.conf.5': No such file or directory
+ install -D -m 644 -t /man5 man/crio.conf.d.5
install: cannot stat 'man/crio.conf.d.5': No such file or directory
+ install -D -m 644 -t /man8 man/crio-status.8
install: cannot stat 'man/crio-status.8': No such file or directory
+ install -D -m 644 -t /man8 man/crio.8
install: cannot stat 'man/crio.8': No such file or directory
+ install -D -m 644 -t  completions/bash/crio
install: cannot stat 'completions/bash/crio': No such file or directory
+ install -D -m 644 -t  completions/fish/crio.fish
install: cannot stat 'completions/fish/crio.fish': No such file or directory
+ install -D -m 644 -t  completions/zsh/_crio
install: cannot stat 'completions/zsh/_crio': No such file or directory
+ install -D -m 644 -t  contrib/policy.json
install: cannot stat 'contrib/policy.json': No such file or directory
+ install -D -m 644 -t  contrib/crio.service
install: cannot stat 'contrib/crio.service': No such file or directory
+ install -D -m 755 -t  bin/pinns
install: cannot stat 'bin/pinns': No such file or directory
+ install -D -m 755 -t  bin/crun
install: cannot stat 'bin/crun': No such file or directory
+ [  = amd64 ]
+ [ -n  ]
```

**Comment by haircommander** [comment]
oops, sorry, you need to use the install path in the bundlle, not in the cri-o repo. the one in the bundle has `contrib/bundle/install-paths` file that is in the cri-o repo prepended. for me it looks like:
```
 #/usr/bin/env sh
DESTDIR=${DESTDIR:-}
PREFIX=${PREFIX:-/usr/local}
ETCDIR=${ETCDIR:-/etc}
CONTAINERS_DIR=${CONTAINERS_DIR:-$ETCDIR/containers}
CNIDIR=${CNIDIR:-$ETCDIR/cni/net.d}
BINDIR=${BINDIR:-$PREFIX/bin}
MANDIR=${MANDIR:-$PREFIX/share/man}
OCIDIR=${OCIDIR:-$PREFIX/share/oci-umount/oci-umount.d}
BASHINSTALLDIR=${BASHINSTALLDIR:-$PREFIX/share/bash-completion/completions}
FISHINSTALLDIR=${FISHINSTALLDIR:-$PREFIX/share/fish/completions}
ZSHINSTALLDIR=${ZSHINSTALLDIR:-$PREFIX/share/zsh/site-functions}
SYSTEMDDIR=${SYSTEMDDIR:-$PREFIX/lib/systemd/system}
OPT_CNI_BIN_DIR=${OPT_CNI_BIN_DIR:-/opt/cni/bin}

SELINUX=
if selinuxenabled 2>/dev/null; then
    SELINUX=-Z
fi
ARCH=${ARCH:-amd64}
set -x
install $SELINUX -d -m 755 "$DESTDIR$CNIDIR"
install $SELINUX -D -m 755 -t "$DESTDIR$OPT_CNI_BIN_DIR" cni-plugins/*
install $SELINUX -D -m 644 -t "$DESTDIR$CNIDIR" contrib/10-crio-bridge.conf
install $SELINUX -D -m 755 -t "$DESTDIR$BINDIR" bin/conmon
install $SELINUX -D -m 755 -t "$DESTDIR$BINDIR" bin/crictl
install $SELINUX -d -m 755 "$DESTDIR$BASHINSTALLDIR"
install $SELINUX -d -m 755 "$DESTDIR$FISHINSTALLDIR"
install $SELINUX -d -m 755 "$DESTDIR$ZSHINSTALLDIR"
install $SELINUX -d -m 755 "$DESTDIR$CONTAINERS_DIR"
install $SELINUX -D -m 755 -t "$DESTDIR$BINDIR" bin/crio-status
install $SELINUX -D -m 755 -t "$DESTDIR$BINDIR" bin/crio
install $SELINUX -D -m 644 -t "$DESTDIR$ETCDIR" etc/crictl.yaml
install $SELINUX -D -m 644 -t "$DESTDIR$OCIDIR" etc/crio-umount.conf
install $SELINUX -D -m 644 -t "$DESTDIR$ETCDIR/crio" etc/crio.conf
install $SELINUX -D -m 644 -t "$DESTDIR$ETCDIR/crio/crio.conf.d" etc/10-crun.conf
install $SELINUX -D -m 644 -t "$DESTDIR$MANDIR/man5" man/crio.conf.5
install $SELINUX -D -m 644 -t "$DESTDIR$MANDIR/man5" man/crio.conf.d.5
install $SELINUX -D -m 644 -t "$DESTDIR$MANDIR/man8" man/crio-status.8
install $SELINUX -D -m 644 -t "$DESTDIR$MANDIR/man8" man/crio.8
install $SELINUX -D -m 644 -t "$DESTDIR$BASHINSTALLDIR" completions/bash/crio
install $SELINUX -D -m 644 -t "$DESTDIR$FISHINSTALLDIR" completions/fish/crio.fish
install $SELINUX -D -m 644 -t "$DESTDIR$ZSHINSTALLDIR" completions/zsh/_crio
install $SELINUX -D -m 644 -t "$DESTDIR$CONTAINERS_DIR" contrib/policy.json
install $SELINUX -D -m 644 -t "$DESTDIR$SYSTEMDDIR" contrib/crio.service
install $SELINUX -D -m 755 -t "$DESTDIR$BINDIR" bin/pinns
install $SELINUX -D -m 755 -t "$DESTDIR$BINDIR" bin/crun

if [ "$ARCH" = amd64 ]; then
    install $SELINUX -D -m 755 -t "$DESTDIR$BINDIR" bin/runc
fi
```

**Comment by willzhang** [comment]
> 糟糕，抱歉，您需要使用捆绑包中的安装路径，而不是 cri-o 存储库中的安装路径。捆绑包中的`contrib/bundle/install-paths`文件前面有 cri-o repo 中的文件。对我来说，它看起来像：
> 
> ```
>  #/usr/bin/env sh
> DESTDIR=${DESTDIR:-}
> PREFIX=${PREFIX:-/usr/local}
> ETCDIR=${ETCDIR:-/etc}
> CONTAINERS_DIR=${CONTAINERS_DIR:-$ETCDIR/containers}
> CNIDIR=${CNIDIR:-$ETCDIR/cni/net.d}
> BINDIR=${BINDIR:-$PREFIX/bin}
> MANDIR=${MANDIR:-$PREFIX/share/man}
> OCIDIR=${OCIDIR:-$PREFIX/share/oci-umount/oci-umount.d}
> BASHINSTALLDIR=${BASHINSTALLDIR:-$PREFIX/share/bash-completion/completions}
> FISHINSTALLDIR=${FISHINSTALLDIR:-$PREFIX/share/fish/completions}
> ZSHINSTALLDIR=${ZSHINSTALLDIR:-$PREFIX/share/zsh/site-functions}
> SYSTEMDDIR=${SYSTEMDDIR:-$PREFIX/lib/systemd/system}
> OPT_CNI_BIN_DIR=${OPT_CNI_BIN_DIR:-/opt/cni/bin}
> 
> SELINUX=
> if selinuxenabled 2>/dev/null; then
>     SELINUX=-Z
> fi
> ARCH=${ARCH:-amd64}
> set -x
> install $SELINUX -d -m 755 "$DESTDIR$CNIDIR"
> install $SELINUX -D -m 755 -t "$DESTDIR$OPT_CNI_BIN_DIR" cni-plugins/*
> install $SELINUX -D -m 644 -t "$DESTDIR$CNIDIR" contrib/10-crio-bridge.conf
> install $SELINUX -D -m 755 -t "$DESTDIR$BINDIR" bin/conmon
> install $SELINUX -D -m 755 -t "$DESTDIR$BINDIR" bin/crictl
> install $SELINUX -d -m 755 "$DESTDIR$BASHINSTALLDIR"
> install $SELINUX -d -m 755 "$DESTDIR$FISHINSTALLDIR"
> install $SELINUX -d -m 755 "$DESTDIR$ZSHINSTALLDIR"
> install $SELINUX -d -m 755 "$DESTDIR$CONTAINERS_DIR"
> install $SELINUX -D -m 755 -t "$DESTDIR$BINDIR" bin/crio-status
> install $SELINUX -D -m 755 -t "$DESTDIR$BINDIR" bin/crio
> install $SELINUX -D -m 644 -t "$DESTDIR$ETCDIR" etc/crictl.yaml
> install $SELINUX -D -m 644 -t "$DESTDIR$OCIDIR" etc/crio-umount.conf
> install $SELINUX -D -m 644 -t "$DESTDIR$ETCDIR/crio" etc/crio.conf
> install $SELINUX -D -m 644 -t "$DESTDIR$ETCDIR/crio/crio.conf.d" etc/10-crun.conf
> install $SELINUX -D -m 644 -t "$DESTDIR$MANDIR/man5" man/crio.conf.5
> install $SELINUX -D -m 644 -t "$DESTDIR$MANDIR/man5" man/crio.conf.d.5
> install $SELINUX -D -m 644 -t "$DESTDIR$MANDIR/man8" man/crio-status.8
> install $SELINUX -D -m 644 -t "$DESTDIR$MANDIR/man8" man/crio.8
> install $SELINUX -D -m 644 -t "$DESTDIR$BASHINSTALLDIR" completions/bash/crio
> install $SELINUX -D -m 644 -t "$DESTDIR$FISHINSTALLDIR" completions/fish/crio.fish
> install $SELINUX -D -m 644 -t "$DESTDIR$ZSHINSTALLDIR" completions/zsh/_crio
> install $SELINUX -D -m 644 -t "$DESTDIR$CONTAINERS_DIR" contrib/policy.json
> install $SELINUX -D -m 644 -t "$DESTDIR$SYSTEMDDIR" contrib/crio.service
> install $SELINUX -D -m 755 -t "$DESTDIR$BINDIR" bin/pinns
> install $SELINUX -D -m 755 -t "$DESTDIR$BINDIR" bin/crun
> 
> if [ "$ARCH" = amd64 ]; then
>     install $SELINUX -D -m 755 -t "$DESTDIR$BINDIR" bin/runc
> fi
> ```

Thank you so much， i don't see the install file before. maybe this install method should put to release page.

**Comment by haircommander** [comment]
yeah or highlighted better on the `install.md`
