### ISSUE TITLE
Crio uses kubelet parameter "container-log-max-files" not in all cases

### ISSUE THREAD

**Issue by rpr-github** [cri-o/cri-o#5863]
Container log file rotation with crio can be configured like this:
The crio container log file size can be defined in crio.conf with “log_size_max”.
Kubelet provides a parameter “--container-log-max-size” for the log file size which however is ignored by crio.
There is no crio parameter for the file count for log rotation.
So, container log rotation can be configured with the crio parameter “log_size_max” and the kubelet parameter “--container-log-max-files”.

The issue is that usage of the kubelet parameter “--container-log-max-files” by crio depends on the value of the crio parameter “log_size_max”. Cases:
1.
If "log_size_max" is defined in crio.conf, then the kubelet parameter "--container-log-max-files" is ignored – if "log_size_max" has a low value, e. g. 1 MB or less.
2.
However, if "log_size_max" has higher values, e. g. 10 MB (“10.000.000”) or higher, then the kubelet parameter "--container-log-max-files" is considered, and multiple log files are maintained with correct size – is EXPECTED behaviour.
3.
If "log_size_max" is not defined in crio.conf, then the kubelet parameter "--container-log-max-files" is considered. Some crio default size (a few GBytes, not documented) is used.
4.
The same behaviour is observed, if "log_size_max" is extremely high (beyond some internal limit), e. g. 50 GB: "--container-log-max-files" is considered. Some default size (a few GBytes) is applied.

Crio version: 1.20.7
Kubernetes version: v1.20.5

**Comment by haircommander** [comment]
yeah for this reason we're deprecating log_size_max in cri-o 1.24.0. If you'd like to use the kubelet version, I recommend just setting cri-o's to unlimited so the only limit is imposed by the kubelet

**Comment by rpr-github** [comment]
The kubelet parameter “--container-log-max-size” is NOT considered in ANY case, even if the crio parameter "log_size_max" is omitted.
and
Kubelet's “--container-log-max-files” is only considered if "log_size_max" has high values, e. g. 10 MB

So, currently log rotation can only be defined with the combination of a crio parameter and a kubelet parameter - not just with the 2 kubelet parameters “--container-log-max-size” and “--container-log-max-files”.
And for an administrator, it is unpredictable whether there is log rotation with a single file or multiple files, as configured.
For us, this looks like bug, and waiting for 1.24 does not sound very promising.

**Comment by haircommander** [comment]
if you set cri-o's `log-size-max` to `-1`, then we disable internal log rotation, and you should get the behavior you're looking for (predictable rotation from the kubelet)

**Comment by rpr-github** [comment]
I tried with  "log-size-max" set to "-1".
The effect is the same as with omitting "log-size-max":
- crio uses the kubelet parameter "--container-log-max-files"  
- but it ignores "container-log-max-size", 
- and the files grow beyond 1 GB

**Comment by haircommander** [comment]
I would be interested in seeing the kubelet and cri-o logs to see what's going on

**Comment by rpr-github** [comment]
Sorry for the delay! The attachment contains log files of crio and kubelet when a container was started writing to stdout very fast. In the "good" case with log file size 20MB, 4 log files are maintained as configured in the kubelet parameter. In the "bad" case with log file size 200KB, just 1 log file exists which is overwritten every few seconds.
Please let me know whether the logging level should e increased to get more details.
Thanks a lot

[Log-Rotation.zip](https://github.com/cri-o/cri-o/files/8880241/Log-Rotation.zip)

**Comment by haircommander** [comment]
fwiw we have begun deprecating the cri-o specific log-size-max in favor of kubelet's container-log-max-files argument
