### ISSUE TITLE
CentOS7 - cri-o-1.24 has missing requirements of containernetworking-plugins >= ('0', '1.0.0', '1')

### ISSUE THREAD

**Issue by SiliconAlley** [cri-o/cri-o#5891]
### What happened?

When installing cri-o-1.24 from the rpm out of the opensuse.org repositories it denies the installation because there is no needed version of containernetworking-plugins (1.0.0) available. There is still the old RC1 containernetworking-plugins-1.0.0-0.2.rc1.el7.1.2.x86_64.rpm which worked with cri-o-1.23.
In this way there is no possibility to update cri-o and even K8S, as both versions must be the same.

Worked around like this, but leaves a mess on my systems:

Going to the projects github page https://github.com/containernetworking/plugins we find under releases a cni-plugins-linux-amd64-v1.1.1.tgz to download which fits our cpu architecture.
The rpm installs here: /usr/libexec/cni/ So we find everything from the tgz also here installed by the rpm. Let’s try to manually place the newer version here to successful update crio.
Let's backup, what yum installed, change into /tmp get the package and untar it:
mv /usr/libexec/cni/ /usr/libexec/cni_old && cd /tmp && wget https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz && mkdir -p /usr/libexec/cni && tar xvf cni-plugins-linux-amd64-v1.1.1.tgz -C /usr/libexec/cni

Install crio with the --skip-broken option, to work around the problem also didn’t work. But downloading the rpm and install with options while still in /tmp:
[root@k8s1 tmp]# wget https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24/CentOS_7/x86_64/cri-o-1.24.0-5.1.el7.x86_64.rpm

[root@k8s1 tmp]# rpm -ivh --nodeps --replacefiles cri-o-1.24.0-5.1.el7.x86_64.rpm

Preparing...                          ################################# [100%]
Updating / installing...
   1:cri-o-0:1.24.0-5.1.el7           warning: /etc/crio/crio.conf created as /etc/crio/crio.conf.rpmnew
################################# [100%]

Cluster runs on 1.24 as you see below.

### What did you expect to happen?

cri-o-1.24 installs from rpm with all dependencies and is ready to use.

### How can we reproduce it (as minimally and precisely as possible)?

[root@k8s1]# yum update cri-o

--> Running transaction check
---> Package cri-o.x86_64 0:1.23.2-5.1.el7 will be updated
---> Package cri-o.x86_64 0:1.24.0-5.1.el7 will be an update

Error: Package: cri-o-1.24.0-5.1.el7.x86_64 (devel_kubic_libcontainers_stable_cri-o_1.24)
           Requires: containernetworking-plugins >= 1.0.0-1
           Installed: containernetworking-plugins-1.0.0-0.2.rc1.el7.1.2.x86_64 (@devel_kubic_libcontainers_stable)
               containernetworking-plugins = 1.0.0-0.2.rc1.el7.1.2
           Available: containernetworking-plugins-0.8.1-1.el7.centos.x86_64 (extras)
               containernetworking-plugins = 0.8.1-1.el7.centos
           Available: containernetworking-plugins-0.8.1-2.el7.centos.x86_64 (extras)
               containernetworking-plugins = 0.8.1-2.el7.centos
           Available: containernetworking-plugins-0.8.1-4.el7.centos.x86_64 (extras)
               containernetworking-plugins = 0.8.1-4.el7.centos
           Available: containernetworking-plugins-0.8.3-3.el7.centos.x86_64 (extras)
               containernetworking-plugins = 0.8.3-3.el7.centos

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
WARN[0000] Failed to decode the keys ["secret" "secret.opts"] from "/usr/share/containers/containers.conf".
crio version 1.24.0
Version:          1.24.0
GitCommit:        0ba47c9b3e52eee95d898be84500c38c9fe032c9
GitTreeState:     clean
BuildDate:        2022-05-13T16:03:45Z
GoVersion:        go1.18.2
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        exclude_graphdriver_devicemapper, seccomp
SeccompEnabled:   true
AppArmorEnabled:  false
```

```console
$ kubectl --version
kubectl --version didn't work
[root@k8s1]# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:38:19Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -a
Linux k8s1.domain.here 3.10.0-1160.62.1.el7.x86_64 #1 SMP Tue Apr 5 16:57:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
running as virtual machine on VMware platform
</details>

**Comment by haircommander** [comment]
Okay I believe I've fixed it. can you give it a try  @SiliconAlley

**Comment by SiliconAlley** [comment]
Thanks @haircommander,

I see it in the repo now. Let me try to solve my mess with yum.

**Comment by SiliconAlley** [comment]
Again many thanks,

it worked updating the containernetworking-plugins package (as I untared the same one). Then I had to remove with yum the old cri-o version cause yum couldn't reinstall and told me I have "multilib version problems", as I installed with rpm already.
