### ISSUE TITLE
Missing ARM64 builds for cri-o / 1.24 / Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by michalpenka** [cri-o/cri-o#5899]
### What happened?

After adding repository https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24/xUbuntu_22.04/ cri-o cannot be installed on ARM64 machines.

Please provide ARM64 builds for CRI-0 1.24 (and all the future versions) for Ubuntu 22.04 LTS (and all the future versions).

### What did you expect to happen?

ARM64 builds exist in the repository and can be installed on Ubuntu 22.04 LTS

### How can we reproduce it (as minimally and precisely as possible)?

1. Install Ubuntu 22.04LTS on ARM64 machine
2. Add https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24/xUbuntu_22.04/  repository
3. Install crio using apt
4. Observe missing package

### Anything else we need to know?

I guess all the raspberry pi community is affected. Now that Kubernetes 1.24 dropped support for Docker and community looking for alternatives, there are only hacky ways to achieve this.

Also, while there exist builds for Debian_11 and the repository can be technically added, it results into conflicts when installing tools such as buildah.

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
none
```

```console
$ kubectl --version
1.24
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux xxx 5.15.0-1006-raspi #6-Ubuntu SMP PREEMPT Mon Apr 25 12:50:48 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by haircommander** [comment]
oops, updated! should be available in an hour or so

**Comment by spowelljr** [comment]
Can confirm this is resolved now

**Comment by michalpenka** [comment]
I cannot confirm as I moved to containerd for the moment. But I see the packages are present in the repo and @spowelljr confirmed independently. Thank you!

**Comment by haircommander** [comment]
Thanks for the confirmation, I will close this now
