### ISSUE TITLE
CRI-O Installation for RHEL 9

### ISSUE THREAD

**Issue by ssrini78** [cri-o/cri-o#5905]
I want to download  packaged CRI-O in RHEL 9. These instructions do not work, as the link: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/" does not have path specific to RHEL or CentOS 9.

curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/devel:kubic:libcontainers:stable.repo
curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/$OS/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo
yum install cri-o

What is the recommended method for downloading packaged CRI-O in RHEL 9?

**Comment by haircommander** [comment]
Sorry we don't currently have a recommended way of installing. You may have some luck installing with the rhel 8 or centos 8 instructions. OBS doesn't yet support either centos or rhel 9

**Comment by ssrini78** [comment]
Thanks for your feedback Peter. I will proceed with RHEL 8 packages
