### ISSUE TITLE
cri-o stop container failed

### ISSUE THREAD

**Issue by Bamboer** [cri-o/cri-o#5929]
### What happened?

Hi ,
  We found a node with a Node-Exporter service that is always in the CrashLoopBackoff state(node-exporter run with DaemonSet model).We found that the container worked fine at runc, but stopped at CRI-O and Kubelet. It is possible that cri-o get a successful  response from runc.

  kubectl logs node-exporterxxx    get  port occupancy error is always displayed(we didn't  run kubectl delete pod node-exporterxxx command).
  netstat -tnlp      we can find the node-exporter is running (node command).
![image](https://user-images.githubusercontent.com/57797847/172034079-1bac1016-c4a8-4e2e-99df-c2a70e8b3946.png)

  nc -zv localhost 9100   get open 

  pstree   get node-exporter is running
![image](https://user-images.githubusercontent.com/57797847/172033414-9ccb4d57-1fc2-4d10-a0c5-51211de0ebef.png)

  crictl get pod  get node-exporter name
  
![image](https://user-images.githubusercontent.com/57797847/172034196-6a831252-31cc-4bb5-ad00-00b71abe4068.png)

  crlctl ps  get none 
![image](https://user-images.githubusercontent.com/57797847/172033525-abb8ddf0-de1d-4ff5-a433-3036bc166dd6.png)

runc list 

![00D6F811E1AA8E11CCD1325544611A79](https://user-images.githubusercontent.com/57797847/172888769-2a95c3cf-3d15-4328-a56c-c6981965a175.jpg)

container's state.json file 
![image](https://user-images.githubusercontent.com/57797847/172889573-f3bf0d02-ded7-447d-a90a-d22376760f1b.png)

### What did you expect to happen?

Know why it's happening and how to fix it.

### How can we reproduce it (as minimally and precisely as possible)?

You can try to simulate runc's stop response, but don't actually stop the container.

### CRI-O and Kubernetes version

$ crio --version
# 1.18.4
$ kubectl --version
# 1.18.9

### OS version

# On Linux:
$ cat /etc/centos-release  
# Centos Linux release 7.9.2009
$ uname -a
# 5.6.4

### Additional environment details (AWS, VirtualBox, physical, etc.)

I will provide the information you need.

**Comment by haircommander** [comment]
this cri-o version is pretty old but I'll try best-effort to help out. I think I'll need the crio logs around the time the container disappeared. was crio restarted and did it fail to restore?

**Comment by Bamboer** [comment]
> this cri-o version is pretty old but I'll try best-effort to help out. I think I'll need the crio logs around the time the container disappeared. was crio restarted and did it fail to restore?

thank for you reply. The scene of the first incident was so old that there was no log of the container disappearing.  do you have any suggestions or idea for this event ?

**Comment by Bamboer** [comment]
> this cri-o version is pretty old but I'll try best-effort to help out. I think I'll need the crio logs around the time the container disappeared. was crio restarted and did it fail to restore?

here is the crio log.
[crio.log.zip](https://github.com/cri-o/cri-o/files/8875411/crio.log.zip)

**Comment by Bamboer** [comment]
We have found many such problems, which are all in hostNetWork mode.

**Comment by Bamboer** [comment]
we found that the container application process exited, but the container process remained. Kubelet also received an error indicating that the port was occupied.
