### ISSUE TITLE
Document supported hardware architectures

### ISSUE THREAD

**Issue by zamazan4ik** [cri-o/cri-o#5980]
Hi!

Could you please put the information about supported architectures to the documentation please? E.e. about supported architectures for different operating systems, some specific requirements to the supported instructions, if you have any (e.g. maybe AVX is required - I do not know).

This kind of information is important for the end-users.

Thanks in advance!

**Comment by saschagrunert** [comment]
Hey @zamazan4ik, I agree it would be beneficial to have this information available. Do you think you will work on those docs as part of a PR?

**Comment by saschagrunert** [comment]
Sounds good, I would probably list them as:

- linux/amd64: Fully integration and e2e tested
- linux/arm64: Bundled and build tested
- linux/i386: Build tested

I'm not sure if we test other architectures in conjunction with OpenShift.

We can also list the platforms build in OBS: https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable:cri-o:1.24
