### ISSUE TITLE
`cri-o:/1.24/xUbuntu_20.04/s390x/` is missing

### ISSUE THREAD

**Issue by spowelljr** [cri-o/cri-o#6000]
Hi there, looking to update cri-o in [minikube](https://github.com/kubernetes/minikube) from 1.22 to 1.24, however the `s390x` arch is missing for 1.24. I'm assuming there was simply a build error or something similar.

On a side note, thanks for adding armv7 arch for 1.24!

https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24/xUbuntu_20.04/

**Comment by haircommander** [comment]
I toggled them! should be available in an hour or so
