### ISSUE TITLE
Vagrant box is unavailable and dependencies package missing from Ubuntu 22.04

### ISSUE THREAD

**Issue by mtardy** [cri-o/cri-o#6015]
### What happened?

I tried to build cri-o first with the given Vagrantfile and it could not complete since [the Vagrant box used is hosted externally](https://app.vagrantup.com/fedora/boxes/30-cloud-base) and the external URL no longer works, unfortunately: https://download.fedoraproject.org/pub/fedora/linux/releases/30/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-30-1.2.x86_64.vagrant-virtualbox.box.

I then tried to build it on a Ubuntu and some of the package dependencies seem not to exist on Ubuntu 22.04, I tried [this list](https://github.com/cri-o/cri-o/blob/main/install.md#debian-bullseye-or-higher---ubuntu-2004-or-higher), but `containers-common` and `cri-o-runc` were missing.

Anyway, even without the 2 packages, I achieved to build the 3 binaries with `make`, so it's not really a big problem, just wanted to signal that the URL was down and the doc was maybe wrong for Ubuntu 22.04.

### What did you expect to happen?

I expected the Vagrantfile to be a way to build the project, and the list of dependencies to exist on Ubuntu 22.04.

### How can we reproduce it (as minimally and precisely as possible)?

- For the Vagrantfile thing, I guess you can just do `vagrant up` on any system that supports the VirtualBox provider.
- For the dependencies, it's possible to test on any Ubuntu 22.04 install, I suggest the `generic/ubuntu2204` vagrant box1

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
INFO[2022-06-29 17:26:48.042280131Z] Starting CRI-O, version: 1.23.0, git: 13052a38b9b62812ee2648ea82c11b413a0219df(clean) 
Version:          1.23.0
GitCommit:        13052a38b9b62812ee2648ea82c11b413a0219df
GitTreeState:     clean
BuildDate:        2022-06-29T17:16:56Z
GoVersion:        go1.18.3
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        containers_image_openpgp, containers_image_ostree_stub, seccomp, selinux
SeccompEnabled:   true
AppArmorEnabled:  false
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux 5.15.0-33-generic #34-Ubuntu SMP Wed May 18 13:34:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
I don't think it's relevant but I tried the `vagrant up` on an x86 macOS machine, and the build on a Ubuntu 22.04 x86 running in a VirtualBox VM.
</details>

**Comment by haircommander** [comment]
ah there's a broken link in the README. you need to enable the kubic repo as describe [here](https://github.com/cri-o/cri-o/blob/main/install.md#apt-based-operating-systems) to get cri-o-runc and containers-common

also, what vagrant file are you using?

**Comment by mtardy** [comment]
> ah there's a broken link in the README. you need to enable the kubic repo as describe [here](https://github.com/cri-o/cri-o/blob/main/install.md#apt-based-operating-systems) to get cri-o-runc and containers-common
> 
> 
> 
> also, what vagrant file are you using?

Aaaah sorry then!!

The main vagrant file in the root folder https://github.com/cri-o/cri-o/blob/main/Vagrantfile.

**Comment by haircommander** [comment]
I would say that vagrant file is barely supported. I have opened a PR to remove it. I would follow the `install.md` instructions and we can fix issues there if we find new ones
