### ISSUE TITLE
Package Request

### ISSUE THREAD

**Issue by lkelting** [cri-o/cri-o#6024]
Can there be packages of the latest CRI-O added for Alma 9 x86_64.

This will be used for a Kubernetes install.

I would be happy to help contribute and test if someone is able to point me in the right direction for taking part in the project on the Suse build service. This is going to be needed on Rocky 9 when it is out of beta, and being a part of the process would be helpful.

**Comment by haircommander** [comment]
I'm afraid there's no el9 in obs yet. I intend on building in epel9, but haven't gotten time to do so

**Comment by haircommander** [comment]
sounds great, thanks @skelting1 !

**Comment by haircommander** [comment]
btw here's the el{7,8} definition https://build.opensuse.org/package/view_file/devel:kubic:libcontainers:stable:cri-o:1.24/cri-o/cri-o.spec?expand=1

**Comment by skelting1** [comment]
Through the power of doing the exact same thing several days later, 1.24.1 is compiling and working just fine. (Same line adjustments were made to change the rhel version checks from 8 to 9)

**Comment by haircommander** [comment]
hah, well I'm glad you have figured it out! Eventually, I'd like the code that packages cri-o to live in this repo, but it doesn't yet. I'll ping you when we make that migration / when I package for el 9, which ever comes first 😄

**Comment by haircommander** [comment]
we'll be packaging into a copr repo for OKD that will provide el9 packages. @LorbusChris do you have a link to the repo?

**Comment by LorbusChris** [comment]
sure :) https://copr.fedorainfracloud.org/coprs/g/OKD/okd/

Note that the CentOS community has already asked us to go through the usual packaging steps via the CentOS Stream dist-git, so we'll additionally do that eventually

**Comment by jcpunk** [comment]
With the copr builds seeming to work, would you be willing to try and get this into EPEL9?

**Comment by haircommander** [comment]
@LorbusChris with the work you're doing for https://github.com/cri-o/cri-o/issues/6986 will that include adding el 9 packages?

**Comment by LorbusChris** [comment]
Once we move the Fedora package back to a standard RPM, my plan is to leverage https://packet.dev for (semi-)automated builds. If EPEL builds can also be automated that way, we can certainly do that. I will not maintain EPEL builds manually, though.

Alternatively, one can already use the CentOS Stream 9 cri-o builds from cbs.centos.org.

**Comment by cyqsimon** [comment]
Ping.

So is this indeed no longer going to happen?

**Comment by saschagrunert** [comment]
@cyqsimon you should be able to use the packages from https://github.com/cri-o/packaging for Alma Linux.

**Comment by cyqsimon** [comment]
@saschagrunert Yep it seems to work alright for Rocky 9. Thanks!
