### ISSUE TITLE
Support reload of cri-o config to add runtimes

### ISSUE THREAD

**Issue by elezar** [cri-o/cri-o#6036]
Is it possible to trigger a restart of crio to apply new runtime configurations without requiring a node reboot? e.g. through `SIGHUP` or by watching for changes at `/etc/crio/crio.d`.

## Motivation

When configuring additional runtimes (e.g. the NVIDIA Container Runtime or Kata), we want to make modifications to the `crio.conf` file (or a file in `/etc/crio/crio.d`). For example adding:
```
$ cat crio.conf

[crio]

  [crio.runtime]
    default_runtime = "nvidia"

    [crio.runtime.runtimes]

      [crio.runtime.runtimes.nvidia]
        runtime_path = "/usr/bin/nvidia-container-runtime"
        runtime_type = "oci"
```
(we don't always set the default runtime)

When using the GPU Operator to deploy the components required to enable access to GPUs in containers, this configuration update is performed by an operand managed by the operator. In the case of `docker` and `containerd` the equivalent configuration modifications are made and the docker or containerd daemons are restarted (e.g. using SIGHUP) to ensure that the newly configured runtime is available to run containers -- either using runtime classes, or as the default runtime.

These configuration options are also cleaned up when the operand responsible for applying the configuration is shut down, triggering another reload of the configuration.

**Comment by haircommander** [comment]
This makes sense to me! I find myself wondering if we should only accept new additions and not change the runtime configuration in-place. Do you have any bandwidth to try implementing this @elezar?

**Comment by elezar** [comment]
@haircommander we could start out with only allowing new runtimes and then see what the implications are w.r.t. removing existing ones (although that is strictly speaking also a use case we would be interested in).

With regards to trying to implement this, I should be able to give it a go but will require some guidance.

My first assumption would be that I would have to extend the `Reload*` functionality [here](https://github.com/cri-o/cri-o/blob/main/pkg/config/reload.go#L64-L90) with something for the runtimes.

**Comment by elezar** [comment]
I have created #6056 as a first pass.

**Comment by haircommander** [comment]
you are on the right track 😄
