### ISSUE TITLE
CRI-O installation failing

### ISSUE THREAD

**Issue by Lakshmi-Patneedi** [cri-o/cri-o#6037]
### What happened?

**We are installing CRI-O, in this way**
1. curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/devel:kubic:libcontainers:stable.repo
2. curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/$OS/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo
3. dnf install cri-o

**Issue:**
dnf install cri-o
![image](https://user-images.githubusercontent.com/94051091/177763315-47553b26-6822-4d32-a6f2-3d6cdc6bb838.png)

When we did curl to the cri-o url:
![image](https://user-images.githubusercontent.com/94051091/177763641-84c8d3a5-5b89-4c75-8d70-c9db411c9e6d.png)

### What did you expect to happen?

After adding repos, if we do yum install cri-o. Installation should be successful.

### How can we reproduce it (as minimally and precisely as possible)?

Add these URL's to /etc/yum.repos.d in RHEL 8.x or Rocky 8.x OS. 
1. https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/devel:kubic:libcontainers:stable.repo
2. https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.21/CentOS_8/devel:kubic:libcontainers:stable:cri-o:1.21.repo
3. Run yum install cri-o

### Anything else we need to know?

Please suggestion some ways to install cri-o 1.21.0 version. On RHEL 8.x and Rocky 8.x OS's

### CRI-O and Kubernetes version

CRI-O version: 1.21
Kubernetes version: 1.21

### OS version

On:
RHEL 8.x
Rocky 8.x

### Additional environment details (AWS, VirtualBox, physical, etc.)

Physical servers

**Comment by haircommander** [comment]
I am guessing you figured it out, which is great to hear!
