### ISSUE TITLE
Container failed to create when feature gate NodeSwap enabled

### ISSUE THREAD

**Issue by james58899** [cri-o/cri-o#6040]
### What happened?

Container failed to create when k8s feature gate `NodeSwap` enabled and create a pod with memory limit.

error:
```
container d5b9277fc2aae6dda6d132bf242b2678a1884e5112b7dca1022aae52a6126530 create failed because memory swap limit (-1) cannot be lower than memory limit (4294967296)
```

### What did you expect to happen?

Create container without error and unlimited swap, or at least success create container but not set swap limit setting.

### How can we reproduce it (as minimally and precisely as possible)?

1. Kubernetes cluster with feature gate `NodeSwap` enabled
2. Setting MemorySwap.SwapBehavior=UnlimitedSwap in the kubelet config
3. Create a pod with the memory limit

### Anything else we need to know?

kubelet will setting MemorySwapLimitInBytes=-1 when SwapBehavior=UnlimitedSwap.

Error from:
https://github.com/cri-o/cri-o/blob/fa262bc87353c45940931402a76f9175a4e01fa6/server/container_create_linux.go#L394-L404

kubelet code:
https://github.com/kubernetes/kubernetes/blob/4569e646ef161c0262d433aed324fec97a525572/pkg/kubelet/kuberuntime/kuberuntime_container_linux.go#L72-L87

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.24.0
Version:          1.24.0
GoVersion:        go1.18
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        seccomp, selinux
SeccompEnabled:   true
AppArmorEnabled:  false
```

```console
$ kubectl version --short
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.23.8
```

</details>

### OS version

<details>

```console
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="36 (Server Edition)"
ID=fedora
VERSION_ID=36
VERSION_CODENAME=""
PLATFORM_ID="platform:f36"
PRETTY_NAME="Fedora Linux 36 (Server Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:36"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f36/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=36
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=36
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Server Edition"
VARIANT_ID=server
$ uname -a
Linux oktw-k8s-2 5.18.9-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jul 2 15:56:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
Physical (QEMU based VM), kubernetes managed by kubeadm.
</details>

**Comment by haircommander** [comment]
hey sorry for the late response! This should be fixed in https://github.com/cri-o/cri-o/pull/6139
