### ISSUE TITLE
Container rootfs not removed

### ISSUE THREAD

**Issue by shinji62** [cri-o/cri-o#6050]
Hello,
I am trying to debug an issue where potentially container rootfs is not remove leading to space to fill up. Most likely when receive Remove Container
crio[27512]: time="2022-07-12 13:28:04.920114867Z" level=info msg="Removed container 676f31c6572d8666db9f76b205feac89320893bf27b72c44b673600d936dd7cd: runners/default-k8s-runner-tqgnz-hfs95/runner" id=6f564226-48d6-4f08-9e2a-183919e28664 name=/runtime.v1alpha2.RuntimeService/RemoveContainer

to be honest I don’t know where to look, like the relation between the container uuid and the uuid use on /var/lib/containers/storage.

I will expect the rootfs of the container to be remove when crio receive the removeContainer info

**Comment by haircommander** [comment]
yeah I would also expect the rootfs to be removed after a remove container request. Note, kubelet won't submit a remove container request immediately after a container is deleted from the kube api. this allows for logs to be scraped and other such diagnostics. I would expect the rootfs to be somewhere like `/var/lib/containers/storage/overlay-containers/676f31c6572d8666db9f76b205feac89320893bf27b72c44b673600d936dd7cd` I think (my memory is fuzzy at the moment on the precise path). You should be able to run `find /var/lib/containers/ -name 676f31c6572d8666db9f76b205feac89320893bf27b72c44b673600d936dd7cd` to find it

**Comment by shinji62** [comment]
Thanks @haircommander so in this case what is `/var/lib/containers/storage/overlay/` comparing to `/var/lib/containers/storage/overlay-containers/` ?

**Comment by nalind** [comment]
The `/var/lib/containers/storage/overlay-containers/containers.json` file will have an entry in it which includes the container's ID and the ID of the container's read-write layer.

Running it through something like `jq 'map(select(.id=="676f31c6572d8666db9f76b205feac89320893bf27b72c44b673600d936dd7cd"))[].layer'` should help in finding that layer ID.  That layer ID corresponds to a directory under `/var/lib/containers/storage/overlay` where the layer's contents are stored.

The container's ID also corresponds to a directory under `/var/lib/containers/storage/overlay-containers` which will typically be used for related items that aren't part of the containr's rootfs, for example the configuration file that's passed to the runtime.
