### ISSUE TITLE
contrib/cni/README.md suggests installing outdated CNI version 0.3.1, not supported by Kubernetes

### ISSUE THREAD

**Issue by dilyanpalauzov** [cri-o/cri-o#6080]
### What happened?

According to https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/ Kubernetes supports CNI-plugins with minimum specification version 0.4.0, but prefers version 1.0.0.

https://github.com/cri-o/cri-o/tree/main/contrib/cni#configuration-directory suggests copying files from `cri-o.git/contrib/cni` to `/etc/cni/net.d`.  The files in  `cri-o.git/contrib/cni` contain `"cniVersion": "0.3.1"`.

Please elaborate why it is suggested to utilize the 0.3.1 interface, instead of a newer interface, supported by Kubernetes?

### What did you expect to happen?

Not applicable.

### How can we reproduce it (as minimally and precisely as possible)?

Not applicable.

### Anything else we need to know?

Not applicable.

### CRI-O and Kubernetes version

Not applicable.

### OS version

Not applicable.

### Additional environment details (AWS, VirtualBox, physical, etc.)

Not applicable.

**Comment by haircommander** [comment]
yeah we use 1.0.0 and greater now

**Comment by haircommander** [comment]
thanks for noticing all of these inconsistencies!

**Comment by afbjorklund** [comment]
`kubernetes-cni` uses 0.8.7, which is less than 1.0.0

Currently that is leading to conflicts, with Kubic rpms.

**Comment by afbjorklund** [comment]
"kubernetes-cni" was updated to 1.1.1, so should be OK

**Comment by afbjorklund** [comment]
The "kubernetes-cni" package still contains 0.8.6 (not supporting criVersion 1.0.0), but I guess cri-o comes with its own "containernetworking-plugins" package anyway...

**Comment by dilyanpalauzov** [comment]
cri-o/contrib/cni/11-crio-ipv4-bridge.conflist contains `"cniVersion": "0.3.1"`.  Can this be reopened, until this is lifted to 1.0.0, too?

cri-o/contrib/cni/99-loopback.conflist has no `plugins` element, therefore it does not need `.conflist` file extension.

For the record, recently the 99-loopback file got a `"name": "loopback"` element, which was again recently removed.
