### ISSUE TITLE
annotation ≠ io.kubernetes.cri-o.userns-mode auto

### ISSUE THREAD

**Issue by dilyanpalauzov** [cri-o/cri-o#6135]
### What happened?

https://github.com/cri-o/cri-o/blob/main/tutorials/userns.md describes the value "auto" of the annotation `io.kubernetes.cri-o.userns-mode`.  Please describe what other values are accepted for the annotation.

### What did you expect to happen?

Not applicable.

### How can we reproduce it (as minimally and precisely as possible)?

Not applicable.

### CRI-O and Kubernetes version

Not applicable.

### OS version

Not applicable.

### Additional environment details (AWS, VirtualBox, physical, etc.)

Not applicable.

**Comment by haircommander** [comment]
I would say this is duplicated with https://github.com/cri-o/cri-o/issues/5030

I agree, this is still an issue
