### ISSUE TITLE
When removing container with graceful shutdown time, crictl stats gets stuck for the same time

### ISSUE THREAD

**Issue by yangjunmyfm192085** [cri-o/cri-o#6147]
### What happened?

as discussed in  [#111738](https://github.com/kubernetes/kubernetes/issues/111738), When graceful delete time is set to 30s, the `crictl stats` command gets stuck for 30s, and when it is set to 120s, the ` crictl stats` command gets stuck for 120s.

### What did you expect to happen?

The `crictl stats` command works fine when the container is removed

### How can we reproduce it (as minimally and precisely as possible)?

kubernetes performs deployment scaling down operations

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# paste output here
```
crio version 1.23.0
Version:          1.23.0
GitCommit:        9b7f5ae815c22a1d754abfbc2890d8d4c10e240d
GitTreeState:     dirty
BuildDate:        1980-01-01T00:00:00Z
GoVersion:        go1.17.4
Compiler:         gc
Platform:         linux/amd64
Linkmode:         static
BuildTags:        apparmor, exclude_graphdriver_devicemapper, seccomp, selinux
SeccompEnabled:   true
AppArmorEnabled:  true

```console
$ kubectl --version
# paste output here
Client Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.0-alpha.2.981+985c9202ccd250", GitCommit:"985c9202ccd250a5fe22c01faf0d8f83d804b9f3", GitTreeState:"clean", BuildDate:"2022-08-06T08:53:16Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.0-alpha.2.981+985c9202ccd250", GitCommit:"985c9202ccd250a5fe22c01faf0d8f83d804b9f3", GitTreeState:"clean", BuildDate:"2022-08-06T08:53:16Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
# paste output here
Linux ubuntu 5.19.0-051900-generic #202207312230 SMP PREEMPT_DYNAMIC Sun Jul 31 22:34:11 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by haircommander** [comment]
This could be solved by updating the crio stats collection frequency 
```
[crio.stats]
stats_collection_frequency = 10
```
would update the stats every 10 seconds, and allow for the collection of them to be independent of the reporting of them. When set to 0, they're generated on demand, which causes the locking issue you're seeing. The precise value you'll have to figure out based on your own needs for how accurate you want the stats vs how much cpu is taken generating the stats

**Comment by yangjunmyfm192085** [comment]
> This could be solved by updating the crio stats collection frequency
> 
> ```
> [crio.stats]
> stats_collection_frequency = 10
> ```
> 
> would update the stats every 10 seconds, and allow for the collection of them to be independent of the reporting of them. When set to 0, they're generated on demand, which causes the locking issue you're seeing. The precise value you'll have to figure out based on your own needs for how accurate you want the stats vs how much cpu is taken generating the stats

Let me try it. Thanks for the response

**Comment by haircommander** [comment]
given there's a workaround, and one day we will move to having stats generation happen periodically instead of on demand, I am opting to close this
