### ISSUE TITLE
Overlay2 does not work in the pod

### ISSUE THREAD

**Issue by tomglaza** [cri-o/cri-o#6157]
### What happened?

We are in the process of migrating our kubernetes klaster from docker-ce to cri-o and have found an issue with some of Our workloads. These particular workloada are Our CI pipelines wich use Docker-in-Docker aproach. On the old nodes, these workloads work fine, but on the new nodes, docker tends to use fuse-overlayfs as storage driver instead of overlay2. In this configuration IO speed is two times lower then on docker-ce despite useing same hardware below. If We force docker to use overlay2 on cri-o, pod fails to start and in dmesg on the host We see: "overlayfs: filesystem on '/var/lib/docker/check-overlayfs-support390169170/upper' not supported as upperdir".
Please advise is this a bug or if We just need to fix cri-o.conf (like adding CAPS or something).

### What did you expect to happen?

Docker started inside cri-o should use overlay2 storage driver.

### How can we reproduce it (as minimally and precisely as possible)?

$ kubectl run test --privileged --image docker:dind
$ kubectl exec -it test -- sh
/ # docker info 2>&1 | grep Storage
 Storage Driver: vfs
Should by:
 Storage Driver: overlay2

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.21.6
Version:       1.21.6
GitCommit:     c03e400ec69fb22256a1b9c8f3ae8011a3539582
GitTreeState:  clean
BuildDate:     2022-03-16T17:45:34Z
GoVersion:     go1.16.12
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

```console
$ kubectl --version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="AlmaLinux"
VERSION="8.5 (Arctic Sphynx)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.5 (Arctic Sphynx)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.5"
$ uname -a
Linux master-1.k8s.internal 4.18.0-348.el8.x86_64 #1 SMP Tue Nov 9 06:28:28 EST 2021 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

It is physical.
```console
# xfs_info /var/lib/containers/
meta-data=/dev/mapper/kubernetes-crio isize=512    agcount=16, agsize=6553472 blks
             =                       sectsz=512   attr=2, projid32bit=1
             =                       crc=1        finobt=1, sparse=1, rmapbt=0
             =                       reflink=1    bigtime=0 inobtcount=0
data      =                       bsize=4096   blocks=104855552, imaxpct=25
             =                       sunit=128    swidth=256 blks
naming =version 2              bsize=4096   ascii-ci=0, ftype=1
log        =internal log           bsize=4096   blocks=51200, version=2
             =                       sectsz=512   sunit=8 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
```

</details>

**Comment by haircommander** [comment]
for cri-o: the `overlay` driver is `overlay2`. What you're encountering is a pretty old bug that we've not found the cause, but an easy fix/workaround is just setting `overlay`

**Comment by tomglaza** [comment]
Could You explain me where should I set this `overlay`?
Because crio uses it AFAICT:

```console
# crio-status i
cgroup driver: systemd
storage driver: overlay
storage root: /var/lib/containers/storage
default GID mappings (format <container>:<host>:<size>):
  0:0:4294967295
default UID mappings (format <container>:<host>:<size>):
  0:0:4294967295
```

And dind refuses to start with it:

```console
# kubectl run -it test --privileged --env="DOCKER_DRIVER=overlay" --image docker:dind
...
WARN[2022-08-23T05:42:56.946348998Z] [graphdriver] WARNING: the overlay storage-driver is deprecated, and will be removed in a future release 
ERRO[2022-08-23T05:42:56.950445607Z] failed to mount overlay: invalid argument     storage-driver=overlay
```

**Comment by haircommander** [comment]
`/etc/containers/storage.conf` is typically where cri-o reads the storage information. 

To clarify your use case: are you trying to run cri-o in the container, or run docker in a container run by cri-o?

**Comment by tomglaza** [comment]
OK, my `/etc/containers/storage.conf` without comments is:

```ini
[storage]
driver = "overlay"
runroot = "/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = [
]
[storage.options.overlay]
mountopt = "nodev,metacopy=on"
[storage.options.thinpool]
```

I am trying to run docker in a container run by cri-o.

**Comment by haircommander** [comment]
I don't think CRI-O is doing any configuring here. I think you need to configure the image you're using to use the correct driver. It's possible you need to mount something into the container or give it privilege so it's actually able to run with overlay
