### ISSUE TITLE
Missing Arm64 build cri-o / 1.23 / Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by jmcgrath207** [cri-o/cri-o#6160]
### What happened?

Build doesn't appear in repo.

https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.23/xUbuntu_20.04/

Arm release - https://github.com/cri-o/cri-o/releases/tag/v1.23.3

This seems to be related to issue https://github.com/cri-o/cri-o/issues/5899

### What did you expect to happen?

To work

### How can we reproduce it (as minimally and precisely as possible)?

Download with apt-get

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# paste output here
```

```console
$ kubectl --version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by haircommander** [comment]
oh goodness, I am sorry, this totally slipped through the cracks.

**Comment by jmcgrath207** [comment]
no worries @haircommander , I have move on and upgrade to 1.24 which if I remember correctly wasn't a issue.

**Comment by haircommander** [comment]
excellent to hear! I am glad you figured something out. I will re-close this, and if it's still failing for someone new, they can reopen
