### ISSUE TITLE
Skip backup configuration files ending in ~

### ISSUE THREAD

**Issue by dilyanpalauzov** [cri-o/cri-o#6190]
### What happened?

When I edit a file X.conf under /etc/crio/crio.conf.d/, emacs creates a backup X.conf~.  Then crio thinks it shall parse the X.conf~ file and more importantly, the settings in X.conf~ take precedence over the settings in X.conf .

This is very nasty and I cannot think of other software, that bahaves like this.

### What did you expect to happen?

Not applicable.

### How can we reproduce it (as minimally and precisely as possible)?

Not applicable.

### CRI-O and Kubernetes version

Not applicable.

### OS version

Not applicable.

### Additional environment details (AWS, VirtualBox, physical, etc.)

Not applicable.

**Comment by saschagrunert** [comment]
Hey @dilyanpalauzov, thank you for the request. Do you mind proposing a PR to fix the behavior?

**Comment by dilyanpalauzov** [comment]
No.  I do not suggest any concrete way to fix this, but handling only *conf files is a good idea.  Neither do I know golang and the internals of cri-o.

**Comment by saschagrunert** [comment]
Right now we parse all files there:

https://github.com/cri-o/cri-o/blob/e5b367d4802ee1558851995ecad6aaa57b8fb3d6/pkg/config/config.go#L698-L718

The thing is that we could exclude some extensions of files starting with a `.`, but where to start and where to end? Changing the parser to only accept `*.conf` files will be a breaking change.

**Comment by dilyanpalauzov** [comment]
> Changing the parser to only accept *.conf files will be a breaking change.

Any form on logic modification here will be a breaking change.
