### ISSUE TITLE
Pulling container images fails on CentOS Stream 8

### ISSUE THREAD

**Issue by brianmcarey** [cri-o/cri-o#6197]
### What happened?

Pulling images fails due to a unknown key in `/etc/containers/policy.json` on Centos Stream 8 with cri-o 1.24.2 installed. 

```shell
[root@localhost ~]# crictl pull k8s.gcr.io/kube-apiserver:v1.24.4
FATA[0000] pulling image: rpc error: code = Unknown desc = invalid policy in "/etc/containers/policy.json": Unknown key "keyPaths" 
```
The same image can be pulled successfully using podman
```
[root@localhost brian]# podman pull k8s.gcr.io/kube-apiserver:v1.24.4
Trying to pull k8s.gcr.io/kube-apiserver:v1.24.4...
Getting image source signatures
Copying blob f5bb0a2b916a done  
Copying blob b9f88661235d done  
Copying blob cca57b588e6e done  
Copying config 6cab9d1bed done  
Writing manifest to image destination
Storing signatures
6cab9d1bed1be49c215505c1a438ce0af66eb54b4e95f06e52037fcd36631f3d
```

This issue looks to have been introduced by updates in the latest containers-common rpm (containers-common-1-40.module_el8.7.0+1196+721f4eb0.x86_64)

Pulling images succeed after downgrading containers-common
```
[root@localhost ~]# rpm -qa | grep containers-common
containers-common-1-40.module_el8.7.0+1196+721f4eb0.x86_64

[root@localhost ~]# cat /etc/containers/policy.json | grep keyPath
		    "keyPaths": ["/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release", "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta"]
		    "keyPaths": ["/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release", "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta"]

[root@localhost ~]# crictl pull quay.io/kubevirtci/fedora:36-2208010931
FATA[0003] pulling image: rpc error: code = Unknown desc = invalid policy in "/etc/containers/policy.json": Unknown key "keyPaths"

[root@localhost ~]# dnf downgrade containers-common
....
...

[root@localhost ~]# rpm -qa | grep containers-common
containers-common-1-23.module_el8.7.0+1106+45480ee0.x86_64

[root@localhost ~]# cat /etc/containers/policy.json | grep keyPath
		    "keyPath": "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"
		    "keyPath": "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"

[root@localhost ~]# crictl pull quay.io/kubevirtci/fedora:36-2208010931
Image is up to date for quay.io/kubevirtci/fedora@sha256:486fd5578f93fbc57a519e34ad4b7cac927c3f8a95409baedf0c19e9f287c207
```

### What did you expect to happen?

Images are pulled successfully

### How can we reproduce it (as minimally and precisely as possible)?

- Install Centos Stream 8
- Run a dnf upgrade
   `dnf upgrade`
- Install cri-o following the documented install procedure for `CentOS_8_Stream`
- Install cri-tools to get crictl
   `dnf install -y cri-tools`
- Enable crio and start crio
   `systemctl enable crio --now`
- Try to pull an image
```
[root@localhost ~]# crictl pull quay.io/kubevirtci/fedora:36-2208010931
FATA[0003] pulling image: rpc error: code = Unknown desc = invalid policy in "/etc/containers/policy.json": Unknown key "keyPaths"
```

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
[root@localhost ~]# crio --version
WARN[0000] Failed to decode the keys ["network.network_backend"] from "/usr/share/containers/containers.conf". 
crio version 1.24.2
Version:          1.24.2
GitCommit:        bd548b04f78a30e1e9d7c17162714edd50edd6ca
GitTreeState:     clean
BuildDate:        2022-08-09T18:58:47Z
GoVersion:        go1.18.2
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        exclude_graphdriver_devicemapper, seccomp
SeccompEnabled:   true
AppArmorEnabled:  false
```

```console
$ kubectl --version
NOT INSTALLED
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
[root@localhost ~]# cat /etc/os-release 
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
$ uname -a
[root@localhost ~]# uname -a
Linux localhost.localdomain 4.18.0-408.el8.x86_64 #1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
Tested in a Centos Stream 8 VM

Also seen in some automation testing carried out by Kubevirt
For example:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/857/check-provision-k8s-1.24/1565236465217048576
</details>

**Comment by ccravens** [comment]
Thank you for reporting on this, I was about to as I had been dealing with this as well.

To fix this for now I created the following ansible step:

```yaml
- name: keyPaths Fix
  lineinfile:
    path: /etc/containers/policy.json
    regexp: '^.*keyPaths.*'
    line: '                    "keyPath": "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"'
```

**Comment by Mahesh-Gunda-Maersk** [comment]
we are also facing same issue. what change w.r.t CIRO ??

**Comment by rabin-io** [comment]
CRI-O is just not up 2 dates with the recent key options in file `/etc/containers/policy.json`

**Comment by Fredouye** [comment]
Hi

same issue with CRI-O 1.24.3 on Alma Linux after the recent (a few days ago) 8.7 update, which updated containers-common to 1.43

Modification of /etc/containers/policy.json as explained here did the trick.

**Comment by cyiping** [comment]
[Problem]
Name:                 kube-proxy-sfs92
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Service Account:      kube-proxy
Node:                 rh91-worker2/10.10.90.101
Start Time:           Fri, 02 Dec 2022 16:30:04 +0800
Labels:               controller-revision-hash=b9c5d5dc4
                      k8s-app=kube-proxy
                      pod-template-generation=1
Annotations:          <none>
Status:               Pending
IP:                   10.10.90.101
IPs:
  IP:           10.10.90.101
Controlled By:  DaemonSet/kube-proxy
Containers:
  kube-proxy:
    Container ID:  
    Image:         registry.k8s.io/kube-proxy:v1.25.3
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/local/bin/kube-proxy
      --config=/var/lib/kube-proxy/config.conf
      --hostname-override=$(NODE_NAME)
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
    Mounts:
      /lib/modules from lib-modules (ro)
      /run/xtables.lock from xtables-lock (rw)
      /var/lib/kube-proxy from kube-proxy (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-2q5b2 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-proxy:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-proxy
    Optional:  false
  xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
  lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  
  kube-api-access-2q5b2:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason                  Age                   From     Message
  ----     ------                  ----                  ----     -------
  Warning  FailedCreatePodSandBox  85s (x5062 over 18h)  kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = error creating pod sandbox with name "k8s_kube-proxy-sfs92_kube-system_ce2a652d-ab3f-4647-b8d3-7aebddb9f990_0": invalid policy in "/etc/containers/policy.json": Unknown key "keyPaths"

------------------------

[solution]
# sudo podman image trust set -f /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release registry.access.redhat.com
# sudo podman image trust set -f /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release registry.redhat.io
# cat <<EOF > /etc/containers/registries.d/registry.access.redhat.com.yaml
docker:
     registry.access.redhat.com:
         sigstore: https://access.redhat.com/webassets/docker/content/sigstore
EOF
# cat <<EOF > /etc/containers/registries.d/registry.redhat.io.yaml
docker:
     registry.redhat.io:
         sigstore: https://registry.redhat.io/containers/sigstore
EOF

**Comment by haircommander** [comment]
@mtrmac @vrothberg WDYT is a good way to fix this? keyPaths is defined on CentOS 8 but upgrading the vendor in 1.24 branch to c/image 5.22 introduces more changes than I would like to. I tried taking a look at cherry-picking https://github.com/containers/image/pull/1609 to release-5.19 but it's not clean at all. do either of you have bandwidth to help me out?

**Comment by mtrmac** [comment]
@haircommander Isn’t CRI-O, in RHEL, only supported as part of OpenShift, with OpenShift-managed configuration? For that, the Centos-shipped `policy.json` defaults are just not relevant. I might be completely mistaken about that part.

I’m fine with with backporting that in principle, but for me to do that, that seems like a typical RHEL sustaining work that should have a RHEL customer and a RHEL business case — or something similar for another product.

---

(I also naively assumed, without thinking about it at all, that CRI-O keeps up with Podman in terms of vendored dependencies, but actually that seems not to be something we have a process for…)

**Comment by haircommander** [comment]
This is for our upstream users who use CentOS and CRI-O outside of Openshift :slightly_smiling_face: CRI-O has a different support policy from podman. basically we support a release branch for a year for upstream, and backport bugs to them. 1.24 is still within our support window, and since this causes CRI-O to not function at all, it feels qualifying to me

**Comment by haircommander** [comment]
I would be open to fixing myself, but I'd need some hand holding, though I think you'd do it much faster :sweat_smile:

**Comment by mtrmac** [comment]
That’s fair, it would probably be faster for me to do this. Given end of year and competing priorities, I can’t promise doing this backport within the next month or so. This issue been open for over 3 months now, so can it wait one more?

(Note to self: From a quick look, the conflicts in the implementation are basically trivial Go version update things; the tests would be most of the work.)

---

(Separately: c/image 5.21 seems to have been released at the time of CRI-O 1.24.0. Is there some process improvement that could be done to ensure the dependencies do not lag so far behind be fore committing to that year-long lifecycle? There seems to be a bot running … from time to time now, so maybe that process improvement has already happened.)

**Comment by haircommander** [comment]
yeah I am not sure why dependabot didn't upgrade in time for 1.24.0. There may have been issues with it, it's hard to keep up with all of the dependabot PRs. That said, I think it makes sense to make an effort as a community to keep the dependencies as up-to-date as possible before we cut a release. I'll go through the PRs now in preparation for 1.26 to begin that.

Thanks for helping, waiting another month should be fine IMO, there is a workaround already anyway

**Comment by tkagn** [comment]
Similar issue on RHEL 8.6 with `containers-common-2:1-43` . Had to edit `etc/containers/policy.json`. Set keypath as @ccravens instructed. Edited keypath

`{
    "default": [
        {
            "type": "insecureAcceptAnything"
        }
    ],
    "transports": {
        "docker": {
            "registry.access.redhat.com": [
                {
                    "type": "signedBy",
                    "keyType": "GPGKeys",
                    "keyPath": "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"
                }
            ],
            "registry.redhat.io": [
                {
                    "type": "signedBy",
                    "keyType": "GPGKeys",
                    "keyPath": "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"
                }
            ]
        },
        "docker-daemon": {
            "": [
                {
                    "type": "insecureAcceptAnything"
                }
            ]
        }
    }
}
`

**Comment by tkagn** [comment]
Noticed changes in this commit - https://gitlab.com/redhat/centos-stream/rpms/containers-common/-/commit/04645c4a84442da3324eea8f6538a5768e69919a

**Comment by pchrz** [comment]
Thank you for spelling it out so nicely @tkagn, that did the trick for me running AlmaLinux 8.7 using cri-o 1.24.4 and containers-common-1-43

**Comment by Udayendu** [comment]
> Similar issue on RHEL 8.6 with `containers-common-2:1-43` . Had to edit `etc/containers/policy.json`. Set keypath as @ccravens instructed. Edited keypath
> 
> `{ "default": [ { "type": "insecureAcceptAnything" } ], "transports": { "docker": { "registry.access.redhat.com": [ { "type": "signedBy", "keyType": "GPGKeys", "keyPath": "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release" } ], "registry.redhat.io": [ { "type": "signedBy", "keyType": "GPGKeys", "keyPath": "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release" } ] }, "docker-daemon": { "": [ { "type": "insecureAcceptAnything" } ] } } }`

I was trying to deploy Kubernetes on Rocky Linux 8.8 and had the same issue. After fixing the `policy.json` as mentioned above, I was able to pull the images. I had the following version of `containers-common` package in the system.

```
# rpm -qi containers-common
Name        : containers-common
Epoch       : 2
Version     : 1
Release     : 64.module+el8.8.0+1265+fa25dd7a
Architecture: x86_64
Install Date: Sat May 20 23:08:59 2023
Group       : Unspecified
Size        : 521080
License     : ASL 2.0
Signature   : RSA/SHA256, Wed May 17 03:08:41 2023, Key ID 15af5dac6d745a60
Source RPM  : containers-common-1-64.module+el8.8.0+1265+fa25dd7a.src.rpm
Build Date  : Wed May 17 02:52:24 2023
Build Host  : ord1-prod-x86build005.svc.aws.rockylinux.org
Relocations : (not relocatable)
Packager    : infrastructure@rockylinux.org
Vendor      : Rocky
Summary     : Common configuration and documentation for containers
Description :
This package contains common configuration files and documentation for container
tools ecosystem, such as Podman, Buildah and Skopeo.

It is required because the most of configuration files and docs come from projects
which are vendored into Podman, Buildah, Skopeo, etc. but they are not packaged
separately.
```
