### ISSUE TITLE
Missing crio 1.25 centos8 stream rpms

### ISSUE THREAD

**Issue by karmab** [cri-o/cri-o#6209]
### What happened?

i went to download the 1.25 rpms for said os but they are not there

### What did you expect to happen?

I expected those rpms to be there

### How can we reproduce it (as minimally and precisely as possible)?

access https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25/CentOS_8_Stream/x86_64/ and search for rpms

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# paste output here
```

```console
$ kubectl --version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by Sc0th** [comment]
Hi are there any plans to address this, I am aware of the other repo noted above, but it has issues (the packaged systemd files are wrong for starters....)

**Comment by Sc0th** [comment]
DNS it’s always DNS.

In all seriousness, thank you, your time is appreciated.
