### ISSUE TITLE
Cri-o 1.25 packages missing for armhf

### ISSUE THREAD

**Issue by grunlab** [cri-o/cri-o#6231]
Cri-o 1.25 packages are currently missing for armhf arch (it is the case for debian_xx, rapsbian_xx and ubuntu_xx distros)

For example, no cri-o 1.25 deb file currently available for armhf / debian_11:
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25/Debian_11/armhf/

Whereas it was ok for cri-o 1.24:
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24/Debian_11/armhf/

**Comment by sbwfnhn** [comment]
have the same problem

```
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25:/1.25.0/CentOS_8/x86_64/
```

```
[root@master01:yum.repos.d] # dnf repolist
repo id                                                                                              repo name
appstream                                                                                            Rocky Linux 9 - AppStream
baseos                                                                                               Rocky Linux 9 - BaseOS
crb                                                                                                  Rocky Linux 9 - CRB
devel_kubic_libcontainers_stable                                                                     Stable Releases of Upstream github.com/containers packages (CentOS_8)
devel_kubic_libcontainers_stable_cri-o_1.25                                                          devel:kubic:libcontainers:stable:cri-o:1.25 (CentOS_8)
epel                                                                                                 Extra Packages for Enterprise Linux 9 - x86_64
extras                                                                                               Rocky Linux 9 - Extras
kubernetes                                                                                           Kubernetes
[root@master01:yum.repos.d] # 
[root@master01:yum.repos.d] # 
[root@master01:yum.repos.d] # 
[root@master01:yum.repos.d] # cat devel\:kubic\:libcontainers\:stable\:cri-o\:1.25.repo 
[devel_kubic_libcontainers_stable_cri-o_1.25]
name=devel:kubic:libcontainers:stable:cri-o:1.25 (CentOS_8)
type=rpm-md
baseurl=https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25/CentOS_8/
gpgcheck=1
gpgkey=https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25/CentOS_8/repodata/repomd.xml.key
enabled=1
[root@master01:yum.repos.d] # 
[root@master01:yum.repos.d] # 
[root@master01:yum.repos.d] # dnf install cri-o
Last metadata expiration check: 0:18:39 ago on Thu 15 Sep 2022 09:42:28 AM CST.
No match for argument: cri-o
```

**Comment by haircommander** [comment]
sorry for the delay y'all!

hm I can't see a build target for armhf. I see armv6l and armv7l, do either of those meet your needs
for centos, I've attempted to retrigger. it's not immediately clear what's going on

**Comment by grunlab** [comment]
armv7l would be perfect.
Thank you

**Comment by grunlab** [comment]
It looks ok now for debian_11, raspbian_11, xubuntu_xx:
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25/Debian_11/armhf/
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25/Raspbian_11/armhf/
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25/xUbuntu_22.04/armhf/

But still not available for debian_10 and raspbian_10:
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25/Debian_10/armhf/
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25/Raspbian_10/armhf/

Thank you

**Comment by grunlab** [comment]
up
Thank you

**Comment by grunlab** [comment]
Cri-o 1.25 packages are now available for Debian 10 armhf.
I've installed them ... all is ok, You can close the issue.
Thank you
