### ISSUE TITLE
CRI-O 1.25 package not found (Ubuntu 18.04)

### ISSUE THREAD

**Issue by bandwiches** [cri-o/cri-o#6246]
### What happened?

CRI-O not found in repo's when following the install instructions for version 1.25, but the installation instructions work when using 1.23 as the version.

### What did you expect to happen?

Expected to install CRI-O version 1.25.

### How can we reproduce it (as minimally and precisely as possible)?

Follow the install instructions, export VERSION=1.25, continue with the instructions until installing CRI-O.

```
$ sudo apt install cri-o
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package cri-o
```

Restart install instructions from beginning using VERSION=1.23 -- success.

### Anything else we need to know?

No

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# N/A
```

```console
$ kubectl --version
# N/A
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# VERSION="18.04.6 LTS (Bionic Beaver)"
$ uname -a
# Linux [redacted] 4.15.0-191-generic #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
Running on a standard bare-metal virtual machine
</details>

**Comment by ginglis13** [comment]
confirmed the same issue after following install instructions for Ubuntu 18.04, and further verified:

version 1.23, `cat /var/lib/apt/lists/download.opensuse.org_repositories_devel:_kubic:_libcontainers:_stable:_cri-o:_1.23_xUbuntu%5f18.04_Packages` shows `cri-o` and go dependencies in list of packages

version 1.25, `cat /var/lib/apt/lists/download.opensuse.org_repositories_devel:_kubic:_libcontainers:_stable:_cri-o:_1.25_xUbuntu%5f18.04_Packages` only shows `dh-golang` in list of packages

**Comment by haircommander** [comment]
yeah there's some incompatibilities I haven't had time to look into. Thanks for opening the issue, I will try to take a look when I find a moment

**Comment by lazystone** [comment]
Yeah repo looks completely empty for 1.25
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25/xUbuntu_18.04/

For comparison https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24/xUbuntu_18.04/

Bad thing is that we already on 1.25

**Comment by haircommander** [comment]
I tried tuning some knobs. seems to only be working for x86, but it's moving forward. hopefully it is fixed

**Comment by haircommander** [comment]
the package is now available for x86
