### ISSUE TITLE
Retester bot is not running

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#6247]
### What happened?

with our new CI, the retester bot isn't recognizing the tests have failed

### What did you expect to happen?

the bot says `/retest-required` when a required test has failed

### How can we reproduce it (as minimally and precisely as possible)?

create a PR that has failing tests and give it the required labels

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# paste output here
```

```console
$ kubectl --version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by fmuyassarov** [comment]
Hi @haircommander ,
Is there an example PR that I can have a look ?

**Comment by haircommander** [comment]
originally we enabled it in https://github.com/openshift/release/pull/16482 and then we've moved CI in https://github.com/openshift/release/pull/30733

intuitively I wouldn't expect a behavior change. it's possible the bot is just funky now

**Comment by haircommander** [comment]
hm I  don't think this is fixed yet. while `/retest` works again, the retester bot was something that used to run on PRs that have `lgtm` and `approve` labels. It would call `/retest-required` to re-run tests until they pass

**Comment by saschagrunert** [comment]
@cri-o/cri-o-maintainers do we still want this? I'd say we further enhance the test robustness.

**Comment by saschagrunert** [comment]
Closing for now, I assume we don't want this any more.
