### ISSUE TITLE
CRI-O 1.24 package not found (Ubuntu) 

### ISSUE THREAD

**Issue by yankay** [cri-o/cri-o#6290]
### What happened?

The ubuntu can not install with the:

`apt-get install cri-o=1.24*`

Because of there are **no package** at the:

- https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24/xUbuntu_22.04/

And there are 1.25 package at the:

- https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.23/xUbuntu_22.04/
- https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25/xUbuntu_22.04/

### What did you expect to happen?

`apt-get install cri-o=1.24*` can work

### How can we reproduce it (as minimally and precisely as possible)?

```
export OS=xUbuntu_22.04
export VERSION=1.24

echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
echo "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.list

curl -L https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/$OS/Release.key | apt-key add -
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | apt-key add -

apt-get update
apt-get install cri-o cri-o-runc
```

### CRI-O and Kubernetes version

1.24

### OS version

Ubuntu_22.04

### Additional environment details (AWS, VirtualBox, physical, etc.)

Vmware

**Comment by afbjorklund** [comment]
See https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable:cri-o:1.24 for subproject vs distro status

**Comment by haircommander** [comment]
sorry, I messed up the package a bit and there were two concurrent packages that fussed with it. they should be present now.

**Comment by yankay** [comment]
Thanks @afbjorklund @haircommander
