### ISSUE TITLE
CRI-O 1.25 package not found (Centos 8) 

### ISSUE THREAD

**Issue by yankay** [cri-o/cri-o#6291]
### What happened?

The Centos 8 can not install CRI-O 1.25

Because of there are no package at the:

https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25/CentOS_8/x86_64/

And there are package at the:

- https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24/CentOS_8/x86_64/
- https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.23/CentOS_8/x86_64/

### What did you expect to happen?

The Centos 8 can install CRI-O 1.25

### How can we reproduce it (as minimally and precisely as possible)?

Follow the install command at the https://cri-o.io/

### CRI-O and Kubernetes version

1.25

### OS version

Centos 8

### Additional environment details (AWS, VirtualBox, physical, etc.)

VM

**Comment by haircommander** [comment]
yeah I'm having troubles with the CentOS_8 target in OBS now. I am not sure what is happening :cry:

**Comment by yankay** [comment]
From the https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable:cri-o:1.25/cri-o.

I guess, If we run the Build again, it would success.

**Comment by gavol** [comment]
I have the same problem but with CentOS 7. That is actually preventing us to move to k8s 1.25,
Is there a way we can help with that? Thanks.

**Comment by haircommander** [comment]
Okay I've finally put together a build for centos 7, 8 and stream 8! thanks for the patience everyone
