### ISSUE TITLE
Container with exec entrypoint never restarted if conmon process exits

### ISSUE THREAD

**Issue by johnsler** [cri-o/cri-o#6295]
### What happened?

I am using oracle kubernetes engine (OKE) which has been using cri-o for container runtime since [1.20.8](https://docs.oracle.com/en-us/iaas/Content/ContEng/Concepts/contengaboutk8sversions.htm).

As part of a resiliency test container and associated conmon processes are killed. 

Containers with exec'd entrypoints are never restarted and kubernetes fails to detect any state change. No probes are issued and the Pod remains healthy!

Happy to attach simplified example for reproduction if needed.
In the meantime :
- what is the keepalive process for conmon?
- why don't container probes detect failure when container and parent conmon aren't running?

### What did you expect to happen?

I expected liveness probe to fail and the container to be restarted.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a simple deployment with a container entrypoint that is exec'd (not forked!)
2. Shell onto the node running search for the container process using ps. 
3. Kill container (pid) and it's monitor (ppid) using kill (KILL or TERM). 
4. Re-issue the ps to confirm the container and it's conmon have exited. 
5. Describe pod in kubectl and observe that it is still reported as ready with no failed probes. 

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.22.3-1.el7
Version:          1.22.3-1.el7
GitCommit:        unknown
GitTreeState:     unknown
BuildDate:        2022-04-12T05:02:57Z
GoVersion:        go1.16.13
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        exclude_graphdriver_devicemapper, containers_image_ostree_stub, seccomp, selinux
SeccompEnabled:   true
AppArmorEnabled:  false
```

```console
$ kubectl --version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"c999fea1e6dbf111d64000dfaaff45edaa4c34d2", GitTreeState:"clean", BuildDate:"2022-01-11T12:16:14Z", GoVersion:"go1.16.12 BoringCrypto", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="7.9"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Oracle Linux Server 7.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.9
$ uname -a
Linux oke-cloxtlcyazq-n72grsjwoeq-sblwxe2n2oq-0 5.4.17-2136.310.7.1.el7uek.x86_64 #2 SMP Wed Aug 17 15:14:21 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
OCI (Oracle Cloud Infrastructure) OKE (Oracle Kubernetes Engine).
https://www.oracle.com/in/cloud/
https://www.oracle.com/in/cloud/cloud-native/container-engine-kubernetes/
</details>

**Comment by haircommander** [comment]
yeah we briefly had some code to detect when conmon had exited, but it was racy and error prone. I've recently had a request to address it again, so I may take a look soon, but I would say fixing is a while off. I wish pidfd support in kernels was more common now so we could utilize them in all cases

**Comment by johnsler** [comment]
I looks like the issue can be potentially worked around by switching my container entrypoint from exec to fork.

**Comment by johnsler** [comment]
In terms of a fix, it looks like conmon approach was taken in principal to remove a single point of failure for logging. With this in mind, the fix should probably ensure that probes are always called regardless of conmon state. This limits the failure case to containers without probes. Thoughts?

**Comment by haircommander** [comment]
so the problem is that the container's lifecycle gets detached from cri-o. exec probes should still run for a spell--until the container exits. once it does, the node may get in a weird state because there's no conmon to tell cri-o the container exited
