### ISSUE TITLE
CRI-O 1.21 package not found (Ubuntu 22.04)

### ISSUE THREAD

**Issue by Dovonun** [cri-o/cri-o#6314]
### What happened?

The CRI-O 1.21 package for Ubuntu 22.04 is missing.

### What did you expect to happen?

Expected to install CRI-O version 1.21

### How can we reproduce it (as minimally and precisely as possible)?

```bash
export VERSION=1.21
export OS=xUbuntu_22.04
echo "deb [signed-by=/usr/share/keyrings/libcontainers-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
echo "deb [signed-by=/usr/share/keyrings/libcontainers-crio-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.list

mkdir -p /usr/share/keyrings
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | gpg --dearmor -o /usr/share/keyrings/libcontainers-archive-keyring.gpg
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/Release.key | gpg --dearmor -o /usr/share/keyrings/libcontainers-crio-archive-keyring.gpg

apt-get update
apt-get install cri-o cri-o-runc
```

### Anything else we need to know?

On WSL and bare-metal.

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# paste output here
```

```console
$ kubectl --version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
Linux studio-pc 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
Running on a dell bare-metal server, also tested in WSL.
</details>

**Comment by haircommander** [comment]
I don't know if we ever actually built it for ubuntu 22.04. Technically, cri-o 1.21 is out of upstream support. Any chance you can use a newer version :smiley:

**Comment by Dovonun** [comment]
I would love to use a newer version, but I have an on-premis cluster with a GitLab deployment. Gitlab does currently not support versions newer than 1.21. [GitLab-1.22-support-issue](https://gitlab.com/groups/gitlab-org/-/epics/6883)

And mixing Kubelet 1.21.X with a newer cri-o version does not sound wise. Would that be an option?
