### ISSUE TITLE
cri-o assumes criu binary is in /usr/sbin/criu

### ISSUE THREAD

**Issue by hesch** [cri-o/cri-o#6337]
### What happened?

I tried to restore a container from an checkpoint image following the not yet published article here: https://github.com/kubernetes/website/pull/37412
The checkpointing process worked without any problems.

On restore the conmon process did not find my criu executable which is located in `/usr/local/sbin/criu` on my machine.

### What did you expect to happen?

cri-o should find the CRIU executable on restore if it is in the PATH.

### How can we reproduce it (as minimally and precisely as possible)?

1. Install CRIU in a non-standard location
2. Create a checkpoint image
3. Try to restore the checkpoint image

### Anything else we need to know?

It seems this is implemented here:

https://github.com/cri-o/cri-o/blob/1e6fd9c520d03d47835d1d4c3209e0f77c38f542/internal/oci/runtime_oci.go#L189-L194

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.25.0
Version:        1.25.0
GitCommit:      1e6fd9c520d03d47835d1d4c3209e0f77c38f542
GitCommitDate:  2022-10-20T13:28:54Z
GitTreeState:   clean
BuildDate:      2022-10-21T14:17:22Z
GoVersion:      go1.19.2
Compiler:       gc
Platform:       linux/arm
Linkmode:       dynamic
BuildTags:
  containers_image_ostree_stub
  containers_image_openpgp
  seccomp
  selinux
LDFlags:          unknown
SeccompEnabled:   true
AppArmorEnabled:  false
Dependencies:
```

```console
$ kubectl --version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2+k3s1", GitCommit:"53c268d8eb90ceea5e1c7865f89db5c7fb8763bc", GitTreeState:"clean", BuildDate:"2022-09-28T16:30:18Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/arm"}
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
$ uname -a
Linux node1 5.15.74-v7l-hs-cr-kernel+ #1 SMP Mon Oct 17 19:16:10 CEST 2022 armv7l GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by adrianreber** [comment]
Some time ago `runc` had a parameter to specify the location of the CRIU binary. This was recently removed from `runc`. Today the CRIU binary needs to be in the `$PATH` for runc to find it. That is why I added that line the way it is. In previous versions it used to search for the CRIU binary in the path and then specify it for `runc` where it is. Since `runc` removed it I only extended the path.

Extending the `$PATH` to `/usr/local/sbin` is probably correct in this case. I can provide a simple PR to fix it.

@hesch I would not try to use a 32bit arm platform to test checkpoint/restore. It has very limited test coverage and I would recommend a 64bit platform: aarch64, x86_64, ppc64le, s390x

**Comment by hesch** [comment]
Shouldn't we search for the binary in `$PATH` and then add the containing folder to `$PATH` instead of just guessing the directory of CRIU?

@adrianreber  Thanks for the heads up on the platform. Until now I did not run into problems caused by 32bit arm, but I will keep this in mind should I run into problems.

**Comment by adrianreber** [comment]
> Shouldn't we search for the binary in `$PATH` and then add the containing folder to `$PATH` instead of just guessing the directory of CRIU?

Yes. That would be better. The current situation comes from `runc` dropping its `--criu` parameter, I changed the code during development to work without it. During restore `conmon` is started with a `$PATH` not containing `../sbin`, I added `/usr/sbin/` to the `$PATH` and it worked then I forgot about it and you are the first to stumble over it.

**Comment by adrianreber** [comment]
I had a closer look at the code and it was just plain wrong. I set the path to `/usr/sbin/$PATH`. There should have at least been a `:` somewhere.

Anyway, thanks for opening this issue and #6338 should fix it.
