### ISSUE TITLE
runc tty not attached - unable to start container process: open /dev/pts/0: operation not permitted

### ISSUE THREAD

**Issue by opipenbe** [cri-o/cri-o#6341]
### What happened?

https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/x86_64/ repository provides runc-1.0.1-1.

crictl exec -it 30e28c59b4d1f -- /bin/sh
ERRO[0000] exec failed: unable to start container process: open /dev/pts/0: operation not permitted 
FATA[0000] execing command in container: command terminated with exit code 255

Also mentioned in https://github.com/containerd/containerd/issues/7219

In runc v1.1.4 it is fixed: https://github.com/opencontainers/runc/releases

### What did you expect to happen?

tty attach is succesful

### How can we reproduce it (as minimally and precisely as possible)?

Follow yum based operating system installation guide: https://github.com/cri-o/cri-o/blob/main/install.md#other-yum-based-operating-systems

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.24.3
Version:          1.24.3
GitCommit:        0e724229f2a81e08a5e05cef0b125ee0dadda08e
GitTreeState:     clean
BuildDate:        2022-10-07T18:28:48Z
GoVersion:        go1.18.4
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        exclude_graphdriver_devicemapper, seccomp
SeccompEnabled:   true
AppArmorEnabled:  false
```

```console
$ kubectl --version
v1.24.6
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
Rocky Linux release 9.0 (Blue Onyx)
$ uname -r
5.14.0-70.26.1.el9_0.x86_64
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
Other
</details>

**Comment by haircommander** [comment]
@kolyshkin PTAL
