### ISSUE TITLE
Cannot install CRI-O on CentOS 8 - no cri-o rpm in opensuse repo

### ISSUE THREAD

**Issue by NerRox** [cri-o/cri-o#6369]
### What happened?

Hello! I am trying to install CRI-O on my CentOS 8 VM. I added the repo file following the instructions from this page https://cri-o.io
The `yum install cri-o` command failed, so I looked into the source repository - and there is no cri-o RPM for CentOS 8.
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25/CentOS_8/x86_64/
Can you add it there please?

### What did you expect to happen?

Adding CRI-O RPM to the repo for CentOS 8

### How can we reproduce it (as minimally and precisely as possible)?

Try to install CRI-O for CentOS 8

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# paste output here
```

```console
$ kubectl --version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by haircommander** [comment]
thanks for trying out CRI-O. we've hit some issues in OBS that I haven't been able to figure out. This is a dup of https://github.com/cri-o/cri-o/issues/6291 and we can track further there
