### ISSUE TITLE
Unable to locate 1.25 cri-o package on Debian 10

### ISSUE THREAD

**Issue by S0LERA** [cri-o/cri-o#6380]
### What happened?

When installing 1.25 cri-o and cri-o-runc packages on Debian 10, the output is:
`E: Unable to locate package cri-o
`

### What did you expect to happen?

cri-o and cri-o-runc packages are installed on the node.

### How can we reproduce it (as minimally and precisely as possible)?

Following the installation instructions on this repo, setting env variable OS to Debian_10 and VERSION to 1.25 or 1.25.1

### Anything else we need to know?

I checked the repository: [http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25/Debian_10/](http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25/Debian_10/) and the packages are not present.

### CRI-O and Kubernetes version

Kubernetes version: Not installed
CRI-O version: Not installed

### OS version

ID="azure"
VERSION="20220328-962"
AZURE_VERSION="0.20220328.962"
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
Azure
</details>

**Comment by haircommander** [comment]
fixed the build, it should make its way into the repos soon
