### ISSUE TITLE
Please, add support for CentOS Stream 9

### ISSUE THREAD

**Issue by renich** [cri-o/cri-o#6385]
All said in the title. Thank you. 

FWIW, I'm using the CentOS_Stream_8 repository in CS9 and it works fine, it seems.

**Comment by haircommander** [comment]
there should be CentOS_Stream_9 support for 1.25 now. Is there another version you're looking for?

**Comment by renich** [comment]
It isn't listed here:

https://github.com/cri-o/cri-o/blob/main/install.md#other-yum-based-operating-systems

Tried setting $OS to CentOS_Stream_9; and VERSION to 1.25 and it didn't work. 

https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.25/CentOS_Stream_9/devel:kubic:libcontainers:stable:cri-o:1.25.repo

**Comment by haircommander** [comment]
it's CentOS_9_Stream: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25/CentOS_9_Stream/x86_64/

Ah yeah we do have a documentation limitation, would you like to open a PR to fix :innocent:

**Comment by renich** [comment]
Awesome. Thanks. I'll update the docs and offer a pull request.

**Comment by renich** [comment]
@haircommander what about this one?: 

https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/devel:kubic:libcontainers:stable.repo

I don't see a CentOS_9 version of it.

**Comment by haircommander** [comment]
there is no CentOS_9 because the only el9 variant of CentOS is CentOS stream

**Comment by haircommander** [comment]
this was done for 1.25 and 1.26 in the OBS repos
