### ISSUE TITLE
yum repo is not avaliable in 'https://github.com/cri-o/cri-o/blob/release-1.26/install.md'

### ISSUE THREAD

**Issue by Lazast** [cri-o/cri-o#6401]
### What happened?

follow part "[Other yum based operating systems](https://github.com/cri-o/cri-o/blob/release-1.26/install.md#other-yum-based-operating-systems)" , the url follows return 404 on "CentOS Linux release 7.6.1810 (Core)"
```
curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/devel:kubic:libcontainers:stable.repo
curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/$OS/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo
```

### What did you expect to happen?

the url work well

### How can we reproduce it (as minimally and precisely as possible)?

provide yum repos avaliable

### CRI-O and Kubernetes version

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -a
Linux deployer 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
vm created by kvm
</details>

**Comment by camaeel** [comment]
@Lazast  Try changing `devel:kubic:libcontainers:` to `devel:\kubic:\libcontainers:\` (add slashes after colons)

**Comment by saschagrunert** [comment]
We probably should update our docs with respect to that. @camaeel do you wanna spin-up a PR for that?

**Comment by camaeel** [comment]
@Lazast this can be closed.
