### ISSUE TITLE
OpenTelemetry tracing enhancements

### ISSUE THREAD

**Issue by saschagrunert** [cri-o/cri-o#6419]
The following enhancements to the current OpenTelemetry implementation can be done as follow-up of https://github.com/cri-o/cri-o/pull/6343:

- [x] Cleanup the log interceptors if possible: https://github.com/cri-o/cri-o/pull/6343#pullrequestreview-1163050522
- [x] Consider using our own log wrapper instead of `logrus.WithContext`: https://github.com/cri-o/cri-o/pull/6343#discussion_r1010237823
- [ ] double check integration with kubelet and conmon-rs (if all traces are passed correctly as well as their links)
- [ ] Quantify the performance impact of tracing

@haircommander @vrutkovs anything I'm missing here?

**Comment by haircommander** [comment]
one more piece from my end would be double check on the performance impact of tracing

**Comment by vrutkovs** [comment]
> Consider using our own log wrapper instead of logrus.WithContext

This one seems to be done no, no `WithContext` outside of `log` found

**Comment by vrutkovs** [comment]
Not sure how to approach 
>Quantify the performance impact of tracing

Hopefully we could compare unit-test performance?

Do we want to remove spans which are known to be tiny? If the overhead for tracing is significant we might want to trim some of the tracing calls.

**Comment by saschagrunert** [comment]
@vrutkovs I think comparing the as-is state with and without tracing would be a good start (single time comparison). I also wonder what happens if we enable tracing but the OTLP endpoint is/becomes unavailable.

**Comment by vrutkovs** [comment]
>Quantify the performance impact of tracing
I ran quick test today - OKD 4.12 as a base, running latest cri-o as of 0bfbd36f2.

First I ran conformance tests for 2 hrs and then enabled tracing (sent to Grafana.net using an agent) and ran conformance again. If I'm reading `sum by (operation_type) (container_runtime_crio_operations_latency_microseconds)` metrics correctly, we get 1-20ms increase in latency with tracing enabled, which is not too bad imo.

Here's a [prometheus snapshot](https://drive.google.com/file/d/1tz_fOwGV_uJryGLekV73tD8yQp9AKr7m/view?usp=sharing) I collected if you want to dig into details

**Comment by saschagrunert** [comment]
> > Quantify the performance impact of tracing
> 
> I ran quick test today - OKD 4.12 as a base, running latest cri-o as of [0bfbd36](https://github.com/cri-o/cri-o/commit/0bfbd36f2884d691abddedd173088db17693b5f7).
> 
> First I ran conformance tests for 2 hrs and then enabled tracing (sent to Grafana.net using an agent) and ran conformance again. If I'm reading `sum by (operation_type) (container_runtime_crio_operations_latency_microseconds)` metrics correctly, we get 1-20ms increase in latency with tracing enabled, which is not too bad imo.

Thank you! That really helps understanding the impact on tracing. I think we're fine with that results. I think it would be worth documenting them somewhere in the metrics guide, or extending the metrics guide to cover telemetry as well.

@vrutkovs @haircommander assuming that collecting telemetry data will only happen over a period of time, do you think that it makes sense to make the implementation more bullet proof, for example: What happens if OTLP goes down but tracing is setup in CRI-O? Will CRI-O block from that point on?

**Comment by vrutkovs** [comment]
>What happens if OTLP goes down but tracing is setup in CRI-O? Will CRI-O block from that point on?

We're using https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc, which requires explicit WithBlock() option to block until server returns the response. We don't have it set, so if otel collector is not replying, CRI-O will not get blocked (but traces would be lost). I tested this by bringing up collector as a pod, so it starts after CRI-O is already running - and verified by updating the collector in flight

**Comment by saschagrunert** [comment]
Agreed
