### ISSUE TITLE
where should I report security issues?

### ISSUE THREAD

**Issue by b0b0haha** [cri-o/cri-o#6454]
### What happened?

It seems the mailing list: private [cncf-crio-security@lists.cncf.io](mailto:cncf-crio-security@lists.cncf.io) list  can't receive the email. Where should I report the vul? Is the mailing list updated?

### What did you expect to happen?

Get the correct mailing list.

### How can we reproduce it (as minimally and precisely as possible)?

none

### CRI-O and Kubernetes version

none

### OS version

none

### Additional environment details (AWS, VirtualBox, physical, etc.)

none

**Comment by haircommander** [comment]
Interesting, that is the correct email. I've just submitted a test email and it successfully sent/was received. Is your email client sending an error when you attempt to send/is it bounced back?

**Comment by b0b0haha** [comment]
> Interesting, that is the correct email. I've just submitted a test email and it successfully sent/was received. Is your email client sending an error when you attempt to send/is it bounced back?

The error message I received is as below:
host lb01.groups.io[45.79.81.153] said: 500 Invalid request (in reply to RCPT TO command)
