### ISSUE TITLE
Restart container too slowly about 11s

### ISSUE THREAD

**Issue by gaochuang** [cri-o/cri-o#6462]
### What happened?

I kill  pid 1 process in container and container will restart, when the container is ready again, it takes 11 seconds.

`zdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net hyperkube[4783]: I1219 03:08:41.196091    4783 prober.go:121] "Probe failed" probeType="Liveness" pod="cran1/po-cran1-ahm-0" podUID=8045d5d5-eed5-4298-a5e7-c4cb9eeceb0c containerName="ctr-cran1-l1commproxy" probeResult=failure output="Get \"http://172.21.0.221:49210/\": dial tcp 172.21.0.221:49210: connect: connection refused"
Dec 19 03:08:41 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net hyperkube[4783]: I1219 03:08:41.196151    4783 kubelet.go:2235] "SyncLoop (probe)" probe="liveness" status="unhealthy" pod="cran1/po-cran1-ahm-0"
Dec 19 03:08:41 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net hyperkube[4783]: I1219 03:08:41.197669    4783 kuberuntime_manager.go:710] "Message for Container of pod" containerName="ctr-cran1-l1commproxy" containerStatusID={Type:cri-o ID:226f263aad8d5b2162a576939a261777f1fcc5a56e9ab4b5ddda5b8bbc3d99c3} pod="cran1/po-cran1-ahm-0" containerMessage="Container ctr-cran1-l1commproxy failed liveness probe, will be restarted"
Dec 19 03:08:41 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net hyperkube[4783]: I1219 03:08:41.197741    4783 kuberuntime_container.go:729] "Killing container with a grace period" pod="cran1/po-cran1-ahm-0" podUID=8045d5d5-eed5-4298-a5e7-c4cb9eeceb0c containerName="ctr-cran1-l1commproxy" containerID="cri-o://226f263aad8d5b2162a576939a261777f1fcc5a56e9ab4b5ddda5b8bbc3d99c3" gracePeriod=30
Dec 19 03:08:41 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net crio[4181]: time="2022-12-19 03:08:41.197999623Z" level=info msg="Stopping container: 226f263aad8d5b2162a576939a261777f1fcc5a56e9ab4b5ddda5b8bbc3d99c3 (timeout: 30s)" id=ba7bb693-3ea3-4b2f-94e3-0f6ee93d5840 name=/runtime.v1.RuntimeService/StopContainer
Dec 19 03:08:41 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net crio[4181]: time="2022-12-19 03:08:41.199141231Z" level=info msg="Stopped container 226f263aad8d5b2162a576939a261777f1fcc5a56e9ab4b5ddda5b8bbc3d99c3: cran1/po-cran1-ahm-0/ctr-cran1-l1commproxy" id=ba7bb693-3ea3-4b2f-94e3-0f6ee93d5840 name=/runtime.v1.RuntimeService/StopContainer
Dec 19 03:08:41 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net crio[4181]: time="2022-12-19 03:08:41.200683978Z" level=info msg="Checking image status: image-registry.openshift-image-registry.svc:5000/cran1/l1commproxy:1.10.0" id=2fefdb55-e723-4bd2-b4a5-e5cde0f61381 name=/runtime.v1.ImageService/ImageStatus
Dec 19 03:08:41 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net crio[4181]: time="2022-12-19 03:08:41.200942612Z" level=info msg="Image status: &ImageStatusResponse{Image:&Image{Id:579f131bf0169e9b8b42084cf12b83da508cf24c06dca0a6b6caab69328afdf4,RepoTags:[image-registry.openshift-image-registry.svc:5000/cran1/l1commproxy:1.10.0],RepoDigests:[image-registry.openshift-image-registry.svc:5000/cran1/l1commproxy@sha256:381153536c0dff0bb4eb0a6b2559bcbea00d24e0f28fff98a504ed16fbe9c113],Size_:134371531,Uid:nil,Username:,Spec:nil,},Info:map[string]string{},}" id=2fefdb55-e723-4bd2-b4a5-e5cde0f61381 name=/runtime.v1.ImageService/ImageStatus
Dec 19 03:08:41 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net hyperkube[4783]: I1219 03:08:41.201405    4783 provider.go:102] Refreshing cache for provider: *credentialprovider.defaultDockerConfigProvider
Dec 19 03:08:41 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net crio[4181]: time="2022-12-19 03:08:41.201795265Z" level=info msg="Pulling image: image-registry.openshift-image-registry.svc:5000/cran1/l1commproxy:1.10.0" id=1e9594d0-7d07-4dbd-abd1-e1b6ca6ca44b name=/runtime.v1.ImageService/PullImage
Dec 19 03:08:41 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net crio[4181]: time="2022-12-19 03:08:41.202895812Z" level=info msg="Trying to access \"image-registry.openshift-image-registry.svc:5000/cran1/l1commproxy:1.10.0\""
Dec 19 03:08:41 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net hyperkube[4783]: I1219 03:08:41.232209    4783 generic.go:296] "Generic (PLEG): container finished" podID=8045d5d5-eed5-4298-a5e7-c4cb9eeceb0c containerID="226f263aad8d5b2162a576939a261777f1fcc5a56e9ab4b5ddda5b8bbc3d99c3" exitCode=1
Dec 19 03:08:41 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net hyperkube[4783]: I1219 03:08:41.232258    4783 kubelet.go:2163] "SyncLoop (PLEG): event for pod" pod="cran1/po-cran1-ahm-0" event=&{ID:8045d5d5-eed5-4298-a5e7-c4cb9eeceb0c Type:ContainerDied Data:226f263aad8d5b2162a576939a261777f1fcc5a56e9ab4b5ddda5b8bbc3d99c3}
Dec 19 03:08:41 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net crio[4181]: time="2022-12-19 03:08:41.250223073Z" level=info msg="Pulled image: image-registry.openshift-image-registry.svc:5000/cran1/l1commproxy@sha256:381153536c0dff0bb4eb0a6b2559bcbea00d24e0f28fff98a504ed16fbe9c113" id=1e9594d0-7d07-4dbd-abd1-e1b6ca6ca44b name=/runtime.v1.ImageService/PullImage
Dec 19 03:08:41 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net crio[4181]: time="2022-12-19 03:08:41.321883909Z" level=info msg="Checking image status: image-registry.openshift-image-registry.svc:5000/cran1/l1commproxy:1.10.0" id=37725ac6-1f36-46eb-8e31-627f76c62d8f name=/runtime.v1.ImageService/ImageStatus
Dec 19 03:08:41 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net crio[4181]: time="2022-12-19 03:08:41.322142283Z" level=info msg="Image status: &ImageStatusResponse{Image:&Image{Id:579f131bf0169e9b8b42084cf12b83da508cf24c06dca0a6b6caab69328afdf4,RepoTags:[image-registry.openshift-image-registry.svc:5000/cran1/l1commproxy:1.10.0],RepoDigests:[image-registry.openshift-image-registry.svc:5000/cran1/l1commproxy@sha256:381153536c0dff0bb4eb0a6b2559bcbea00d24e0f28fff98a504ed16fbe9c113],Size_:134371531,Uid:nil,Username:,Spec:nil,},Info:map[string]string{},}" id=37725ac6-1f36-46eb-8e31-627f76c62d8f name=/runtime.v1.ImageService/ImageStatus
Dec 19 03:08:41 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net crio[4181]: time="2022-12-19 03:08:41.323478924Z" level=info msg="Creating container: cran1/po-cran1-ahm-0/ctr-cran1-l1commproxy" id=6250ad5b-2347-4234-b3e1-07966323483c name=/runtime.v1.RuntimeService/CreateContainer
Dec 19 03:08:41 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net crio[4181]: time="2022-12-19 03:08:41.323580342Z" level=warning msg="Allowed annotations are specified for workload []"
Dec 19 03:08:42 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[1]: run-runc-66fe00b5e9907c45444bab9b5d707fbdd2d87247279e207883d85443362ec173-runc.u38cJo.mount: Succeeded.
Dec 19 03:08:42 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[2826]: run-runc-66fe00b5e9907c45444bab9b5d707fbdd2d87247279e207883d85443362ec173-runc.u38cJo.mount: Succeeded.
Dec 19 03:08:43 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[1]: run-runc-c9ee5c9a96ec25af47a45f30c77c2a12304ca1957f65a7d054de11c83512f152-runc.qaVpe5.mount: Succeeded.
Dec 19 03:08:43 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[2826]: run-runc-c9ee5c9a96ec25af47a45f30c77c2a12304ca1957f65a7d054de11c83512f152-runc.qaVpe5.mount: Succeeded.
Dec 19 03:08:43 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[1]: run-runc-6490d7e92572472471593d403d48f53a82994194743c0cbe0321c76c9a12c28c-runc.kPP50q.mount: Succeeded.
Dec 19 03:08:43 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[1]: run-runc-dca767e160b5a32784d7d6431ff862b0c46444badf253014f6b7ecd564278178-runc.xsXHqj.mount: Succeeded.
Dec 19 03:08:43 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[2826]: run-runc-6490d7e92572472471593d403d48f53a82994194743c0cbe0321c76c9a12c28c-runc.kPP50q.mount: Succeeded.
Dec 19 03:08:43 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[2826]: run-runc-dca767e160b5a32784d7d6431ff862b0c46444badf253014f6b7ecd564278178-runc.xsXHqj.mount: Succeeded.
Dec 19 03:08:44 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[2826]: run-runc-1e2ac4290e367918cf404a74b8ba5c28fbbbe924fd82718f52c3814f403fbd62-runc.V2bLuU.mount: Succeeded.
Dec 19 03:08:44 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[1]: run-runc-1e2ac4290e367918cf404a74b8ba5c28fbbbe924fd82718f52c3814f403fbd62-runc.V2bLuU.mount: Succeeded.
Dec 19 03:08:44 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[1]: Started crio-conmon-b5f1e94402ec0109511f03f34f676c136659c2552d10de6a18d36d11ff3b9f75.scope.
Dec 19 03:08:45 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[1]: run-runc-03dfd7f2b439dfeae1e519dd755538dc93ce5a327f1311ecd22d8d87e64a71d7-runc.EYNVUr.mount: Succeeded.
Dec 19 03:08:45 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[1]: run-runc-03fbba222d9d20292f7070bbae7744d1096e788913045db7f96b2b421295c449-runc.3Fo1ey.mount: Succeeded.
Dec 19 03:08:45 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[2826]: run-runc-03fbba222d9d20292f7070bbae7744d1096e788913045db7f96b2b421295c449-runc.3Fo1ey.mount: Succeeded.
Dec 19 03:08:45 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[1]: Started libcontainer container b5f1e94402ec0109511f03f34f676c136659c2552d10de6a18d36d11ff3b9f75.
Dec 19 03:08:45 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net kernel: get vf[0] stats not supported
Dec 19 03:08:45 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net kernel: get vf[1] stats not supported
Dec 19 03:08:46 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[1]: run-runc-b90d1bea5f2be54810e09a7edcea8b8764a5ab858b857aae8281993983a24955-runc.lo5muH.mount: Succeeded.
Dec 19 03:08:46 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[2826]: run-runc-b90d1bea5f2be54810e09a7edcea8b8764a5ab858b857aae8281993983a24955-runc.lo5muH.mount: Succeeded.
Dec 19 03:08:46 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[1]: run-runc-4f0a5de90b1908c745f30f261f9459fb9d4deb202a6e89a2a6fc29e8c3ead088-runc.10HlBH.mount: Succeeded.
Dec 19 03:08:47 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[1]: run-runc-7c12d41aa2a6cc4ab3866a61acf1b4bddc32bcd183f89b5e3e8cc02278290b4a-runc.B8LC8f.mount: Succeeded.
Dec 19 03:08:47 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[2826]: run-runc-7c12d41aa2a6cc4ab3866a61acf1b4bddc32bcd183f89b5e3e8cc02278290b4a-runc.B8LC8f.mount: Succeeded.
Dec 19 03:08:48 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[1]: run-runc-f731df6b48b749f1947ff7b43d6653d3d270835e63b80ee0c6d56073dabd9e60-runc.MPLBHz.mount: Succeeded.
Dec 19 03:08:48 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[2826]: run-runc-f731df6b48b749f1947ff7b43d6653d3d270835e63b80ee0c6d56073dabd9e60-runc.MPLBHz.mount: Succeeded.
Dec 19 03:08:48 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[1]: run-runc-ac03c2e167f64191814b106cc117a22dacd2c820e4865c555c480cddeecac977-runc.WTlTsC.mount: Succeeded.
Dec 19 03:08:48 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[2826]: run-runc-ac03c2e167f64191814b106cc117a22dacd2c820e4865c555c480cddeecac977-runc.WTlTsC.mount: Succeeded.
Dec 19 03:08:48 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net crio[4181]: time="2022-12-19 03:08:48.554215872Z" level=info msg="Created container b5f1e94402ec0109511f03f34f676c136659c2552d10de6a18d36d11ff3b9f75: cran1/po-cran1-ahm-0/ctr-cran1-l1commproxy" id=6250ad5b-2347-4234-b3e1-07966323483c name=/runtime.v1.RuntimeService/CreateContainer
Dec 19 03:08:48 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net crio[4181]: time="2022-12-19 03:08:48.555587243Z" level=info msg="Starting container: b5f1e94402ec0109511f03f34f676c136659c2552d10de6a18d36d11ff3b9f75" id=1a1d4382-d315-4e63-a20f-c0f79befeb9f name=/runtime.v1.RuntimeService/StartContainer
Dec 19 03:08:49 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[2826]: run-runc-352935356fa8d4bf583956414ecc2a73aaf4757ee579d1b7dd4e24ef826d7993-runc.eo9gqS.mount: Succeeded.
Dec 19 03:08:49 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[2826]: run-runc-265eff6ec12d78b62e1bb60a09a6d2323c2bdaf17131480420d966693aff1dea-runc.rcNiB0.mount: Succeeded.
Dec 19 03:08:49 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net ovs-vswitchd[2531]: ovs|02282|connmgr|INFO|br-ex<->unix#1750: 2 flow_mods in the last 0 s (2 adds)
Dec 19 03:08:51 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[2826]: run-runc-c9ee5c9a96ec25af47a45f30c77c2a12304ca1957f65a7d054de11c83512f152-runc.5kkcWJ.mount: Succeeded.
Dec 19 03:08:51 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[1]: run-runc-c9ee5c9a96ec25af47a45f30c77c2a12304ca1957f65a7d054de11c83512f152-runc.5kkcWJ.mount: Succeeded.
Dec 19 03:08:52 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[2826]: run-runc-6490d7e92572472471593d403d48f53a82994194743c0cbe0321c76c9a12c28c-runc.0EjjwB.mount: Succeeded.
Dec 19 03:08:52 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[1]: run-runc-6490d7e92572472471593d403d48f53a82994194743c0cbe0321c76c9a12c28c-runc.0EjjwB.mount: Succeeded.
Dec 19 03:08:52 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net crio[4181]: time="2022-12-19 03:08:52.918338084Z" level=info msg="Started container" PID=1108551 containerID=b5f1e94402ec0109511f03f34f676c136659c2552d10de6a18d36d11ff3b9f75 description=cran1/po-cran1-ahm-0/ctr-cran1-l1commproxy id=1a1d4382-d315-4e63-a20f-c0f79befeb9f name=/runtime.v1.RuntimeService/StartContainer sandboxID=a98df2aebd605cb6910eb068abd1926bcb1fa5b512863c885fc606f430626619
Dec 19 03:08:53 master0.hzdx-l1-10-64-70-194.ocp.hz.nsn-rdnet.net systemd[1]: run-runc-1e2ac4290e367918cf404a74b8ba5c28fbbbe924fd82718f52c3814f403fbd62-runc.6JG1Ez.mount: Succeeded.

`

### What did you expect to happen?

The container should be restored in the shortest time.

### How can we reproduce it (as minimally and precisely as possible)?

kill pid 1 process in container

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# paste output here
```
[core@hz-ran-l1-10-64-69-82 ~]$ crio version
INFO[2022-12-20 01:31:29.647469423Z] Starting CRI-O, version: 1.23.3-16.rhaos4.10.gitd7c9b35.el8, git: () 
Version:          1.23.3-16.rhaos4.10.gitd7c9b35.el8
GoVersion:        go1.17.12
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        exclude_graphdriver_devicemapper, containers_image_ostree_stub, seccomp, selinux
SeccompEnabled:   true
AppArmorEnabled:  false
```console
$ kubectl --version
# paste output here
```
[core@hz-ran-l1-10-64-69-82 ~]$ oc version
Client Version: 4.10.0-202208301216.p0.gdd2bcd0.assembly.stream-dd2bcd0
Server Version: 4.10.32
Kubernetes Version: v1.23.5+012e945
</details>

### OS version

<details>

``[core@hz-ran-l1-10-64-69-82 ~]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux CoreOS"
VERSION="410.84.202209061703-0"
ID="rhcos"
ID_LIKE="rhel fedora"
VERSION_ID="4.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 410.84.202209061703-0 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::coreos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://docs.openshift.com/container-platform/4.10/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.10"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.10"
OPENSHIFT_VERSION="4.10"
RHEL_VERSION="8.4"
OSTREE_VERSION='410.84.202209061703-0'`console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
`core@hz-ran-l1-10-64-69-82 ~]$ uname -a
Linux hz-ran-l1-10-64-69-82 4.18.0-305.62.1.el8_4.x86_64 #1 SMP Thu Aug 11 12:07:27 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux``

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
openshift
</details>

**Comment by haircommander** [comment]
did you mean to close this @gaochuang ? are you all set here?

**Comment by gaochuang** [comment]
> did you mean to close this @gaochuang ? are you all set here?
Sorry to reply you so late.  I'm not sure if this is a kubelet issue or a cri-o issue.

**Comment by gaochuang** [comment]
> > did you mean to close this @gaochuang ? are you all set here?
> > Sorry to reply you so late.  I'm not sure if this is a kubelet issue or a cri-o issue.

@haircommander
