### ISSUE TITLE
Remove the `UpdateContainerStatus` call when `evented pleg` is enabled

### ISSUE THREAD

**Issue by sairameshv** [cri-o/cri-o#6465]
I am still pretty anxious about adding this call. this means for every single pod event there's a corresponding call to `runc state` and all the overhead of managing a new process. We really shouldn't need this call, and if we do, we're not reacting to a container exit correctly, or are sending the event too early

_Originally posted by @haircommander in https://github.com/cri-o/cri-o/pull/6404#discussion_r1049969804_

**Comment by sairameshv** [comment]
Intent of this issue is to track the work to remove the UpateContainerStatus call while sending the container and sandbox lifecycle events when the evented pleg is enabled.

**Comment by haircommander** [comment]
hey @Omkar0114 ! thanks for your interest. Currently, everytime a PLEG event is generated, the function [UpdateContainerStatus() is called](https://github.com/cri-o/cri-o/blob/cb892e7a3f6452701779931b7a21038f38e6e1b9/server/server.go#L1019-L1022). the object would be to remove that call, and create a test suite that verifies the events are correctly emitted without it. any additional thoughts @sairameshv ?

**Comment by Omkar0114** [comment]
Thanks a lot, @haircommander for the information! I started working on this issue! 
I'll comment here for any clarification and also for my approach to solving this issue.

**Comment by Omkar0114** [comment]
Hi @haircommander 
my approach for [UpdateContainerStatus() is called](https://github.com/cri-o/cri-o/blob/cb892e7a3f6452701779931b7a21038f38e6e1b9/server/server.go#L1019-L1022) is removing this function call and adding appropriate test case for the same in the [server_test.go](https://github.com/cri-o/cri-o/blob/cb892e7a3f6452701779931b7a21038f38e6e1b9/server/server_test.go) file. 

Am I going in the right direction @haircommander?

**Comment by sairameshv** [comment]
Hello @Omkar0114 , Thanks for your interest.

You would have to remove the UpdateContainerStatus() function call and make sure [this](https://github.com/cri-o/cri-o/blob/cb892e7a3f6452701779931b7a21038f38e6e1b9/test/ctr.bats#L142) test case passes.
The above test case verifies the evented_pleg feature's functionality.

**Comment by Omkar0114** [comment]
Thanks, @sairameshv!

**Comment by Omkar0114** [comment]
HI @haircommander @sairameshv , 
I am getting this error while setting up CRI-O on Ubuntu I posted on Slack. Can anyone point out what I am missing here?
https://kubernetes.slack.com/archives/CAZH62UR1/p1692042588099639

**Comment by Omkar0114** [comment]
Hi While setting up the testing environment I am getting these errors. 
What I am majorly missing? @haircommander @sairameshv 
![image](https://github.com/cri-o/cri-o/assets/88308267/4e63f04c-00a2-4da8-9f7f-7e12b4a0077e)

**Comment by haircommander** [comment]
did you follow https://github.com/cri-o/cri-o/tree/main/contrib/cni ? I think you need to install containernetworking-plugins

**Comment by Omkar0114** [comment]
Hi @haircommander 
Thanks, I installed the cni plugins successfully. But now countered these new errors
 I am trying to resolve this
![image](https://github.com/cri-o/cri-o/assets/88308267/e2efb95f-cb68-4cd3-8883-472e5fb42108)

**Comment by Omkar0114** [comment]
Hey @haircommander, 
after removing the [UpdateContainerStatus()](https://github.com/cri-o/cri-o/blob/cb892e7a3f6452701779931b7a21038f38e6e1b9/server/server.go#L1019-L1022) call I ran this test case https://github.com/cri-o/cri-o/blob/cb892e7a3f6452701779931b7a21038f38e6e1b9/test/ctr.bats#L142 

And test case is passing, as you can see here- 
![image](https://github.com/cri-o/cri-o/assets/88308267/8c2a794f-0040-4ee9-ad03-84ba78efcdd1)

What other things should I check?

**Comment by haircommander** [comment]
I think it's worth opening a PR with the changes and we can test our evented-pleg job too to make sure there aren't regressions there
