### ISSUE TITLE
Evented PLEG - All the clients must receive the events

### ISSUE THREAD

**Issue by sairameshv** [cri-o/cri-o#6466]
something worth noting is, as it is now, all clients share the same events source, so if we add a `crictl events` call, kubelet will miss those events... I don't think it's vital to address now but is something we may want to fix in the future

_Originally posted by @haircommander in https://github.com/cri-o/cri-o/issues/6404#issuecomment-1330869709_

**Comment by sairameshv** [comment]
As of today, Kubelet is the only client that receives the container and sandbox lifecycle events. In future, if an another client (Ex: `crictl get events`) is added, only one of the clients receives the events.
This should be thought through and designed in such a way that all the clients would receive the lifecycle events of containers and sandboxes.

**Comment by Abhishek-569** [comment]
I want to work on this issue. Any tips and suggestions will be helpful.

**Comment by haircommander** [comment]
sure @Abhishek-569 ! it may help adding a `crictl events` target first so you have two clients to test with

**Comment by Freggy** [comment]
Hey @haircommander, I was searching for a good first issue to start contributing to cri-o and found this one. Since there was no open pull request for over a month I thought, I might work on this. I hope this is okay.

**Comment by haircommander** [comment]
That sounds great! Please do 😄 thanks for your interest

**Comment by Freggy** [comment]
Nice, I already created this pull request: https://github.com/cri-o/cri-o/pull/6838
