### ISSUE TITLE
crio-run-c install on ubuntu 18.04

### ISSUE THREAD

**Issue by bandwiches** [cri-o/cri-o#6469]
The following keys were missing when following the instructions for adding the backports repo on a fresh Ubuntu 18.04 server.

```bash
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E98404D386FA1D9
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
```

**Comment by haircommander** [comment]
do you have any desire to open a PR to update the documentation @bandwiches ?

**Comment by bandwiches** [comment]
sure, i'll give a go
