### ISSUE TITLE
1.26.0: Failing build

### ISSUE THREAD

**Issue by dvzrv** [cri-o/cri-o#6474]
### What happened?

Hi! I'm packaging cri-o for Arch Linux. When trying to build 1.26.0 I ran into build failures due to btrfs.

* btrfs-progs 6.1
* go 1.19.4
* apparmor 3.1.2
* go-md2man 2.0.2
* libassuan 2.5.5
* libseccomp 2.5.4
* ostree 2022.7

### What did you expect to happen?

The build succeeds.

### How can we reproduce it (as minimally and precisely as possible)?

```
  export CGO_CPPFLAGS="$CPPFLAGS"
  export CGO_CFLAGS="$CFLAGS"
  export CGO_CXXFLAGS="$CXXFLAGS"
  export CGO_LDFLAGS="$LDFLAGS"
  export GOFLAGS="-buildmode=pie -trimpath -ldflags=-linkmode=external -mod=readonly -modcacherw"

  make V=1 GO_MD2MAN=/usr/bin/go-md2man
```

### Anything else we need to know?

```
# github.com/containers/storage/drivers/btrfs
_output/pkg/mod/github.com/containers/storage@v1.44.0/drivers/btrfs/btrfs.go:385:11: args.lim.max_referenced undefined (type _Ctype_struct_btrfs_qgroup_limit has no field or method max_referenced)
# github.com/containers/storage/drivers/btrfs
_output/pkg/mod/github.com/containers/storage@v1.44.0/drivers/btrfs/btrfs.go:385:11: args.lim.max_referenced undefined (type _Ctype_struct_btrfs_qgroup_limit has no field or method max_referenced)
make: *** [Makefile:202: bin/crio-status] Error 2
make: *** Waiting for unfinished jobs....
make: *** [Makefile:199: bin/crio] Error 2
```

[cri-o-1.26.0-1-x86_64-build.log](https://github.com/cri-o/cri-o/files/10304482/cri-o-1.26.0-1-x86_64-build.log)

### CRI-O and Kubernetes version

n/a

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
$ uname -a
Linux hmbx 6.1.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 21 Dec 2022 22:27:55 +0000 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

n/a

**Comment by 65a** [comment]
seems to affect all versions linking BTRFS

**Comment by dvzrv** [comment]
@haircommander do you have time to look into this? The problem is currently unfortunately blocking the update of all kubernetes tooling etc. on Arch Linux

**Comment by haircommander** [comment]
hey y'all, sorry, I was on holiday break. I believe https://github.com/cri-o/cri-o/pull/6479 will fix this, once backported to 1.26 branch. Is someone able to verify that for me?

**Comment by dvzrv** [comment]
I just built your branch and that was successful, thanks!

**Comment by haircommander** [comment]
Excellent! I think we will have a 1.26.1 this week or next week ( I want to get a couple more fixes in) is that timeline acceptable?

**Comment by dvzrv** [comment]
Since I have all the other stuff in our testing repository already, sooner would be preferred over later of course :laughing: 
If it works for you, you may also release more patch level releases after this one (as this at least allows downstreams to build 1.26.0).

There are also a few changes in regards to the cni configs, that I need to adhere to when updating.

**Comment by haircommander** [comment]
yeah the CNI fix is another, and there's one more that I would like in. I will prioritize this work :)

**Comment by haircommander** [comment]
by the way--is there a script or something that could be run in cri-o CI to catch these issues in the future? we could also automate some of your workflows of releasing for Arch if desired

**Comment by dvzrv** [comment]
It's certainly possible to also build cri-o using our official Arch Linux container image!
The package release workflow on Arch Linux is bound to a set of verified packagers doing this job though. As long as there is a functioning source tarball, anyone in that group can use our build script for cri-o (see https://github.com/archlinux/svntogit-community/blob/packages/cri-o/trunk/PKGBUILD) to publish a package from it.

**Comment by haircommander** [comment]
makes sense, fedora is the same way. Thanks for your work packaging cri-o on Arch btw :)

**Comment by dvzrv** [comment]
@haircommander any news on this? Would love to be able to move kubernetes 1.26.0 out of testing :)

**Comment by haircommander** [comment]
sorry one more PR that needs addressing, I am hoping for tomorrow. thanks for your patience

**Comment by dvzrv** [comment]
@haircommander thanks! 1.26.1 fixes the issue! :tada:
