### ISSUE TITLE
docs-generation/completion targets are cumbersome to use

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#6499]
As they take into account the configuration values on the node they're being run on. We have a couple of options:
- configure them to ignore local configuration
- create a containerized version and create an image that has the configuration CI (and the community) expects for generating these

**Comment by jrvaldes** [comment]
Yes.

**Comment by haircommander** [comment]
a follow-up item to this is updating the CONTRIBUTING.md to include instructions on running the various static linters/documentation validation jobs (possibly also creating a new make target to run them all)

**Comment by haircommander** [comment]
dropping the selinux option https://github.com/cri-o/cri-o/discussions/6511 would make this easier, this is often one that is different than the default

**Comment by jrvaldes** [comment]
@haircommander  looks like https://github.com/cri-o/cri-o/discussions/6511 should come first. Is this issue blocked until the  `selinux` option changes are completed?

**Comment by haircommander** [comment]
I wouldn't mark it a hard blocker, but yeah: the selinux option is determined from whether selinux is enabled. even if the default is that selinux is not enabled, running make completions docs-generation` will mark selinux as enabled. Even inside of a container, I believe it would still change selinux. I believe that's the only option that uses the state of the node to determine what it is, all the rest use files on disk

**Comment by jrvaldes** [comment]
Thanks for the explanation.

**Comment by jrvaldes** [comment]
/unassign
 
https://github.com/cri-o/cri-o/discussions/6511 should be closed first, will lower the complexity.

**Comment by AHB102** [comment]
@haircommander I am new to open source, can I work on this ?

**Comment by AHB102** [comment]
@haircommander Can you please elaborate the issue? I'm a bit confused

**Comment by haircommander** [comment]
basically if you run `make completions` or `make docs-generation` the command takes into account the user and configuration on the node you're running it in. We should find a way to help users make the completions and docs that so that the defaults are taken, which will lower the threshold for new users making a change to the config. does that make sense?
