### ISSUE TITLE
skip tests on doc update PRs

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#6500]
we run lots of tests we don't really need to in documentation fixes. podman has the option to skip CI if the title of the PR has [CI:DOCS] prefix. it would be cool to have a similar mechanism here. this could end up being trivial if prow has a knob for it, I haven't checked

**Comment by haircommander** [comment]
@sohankunkerkar does this interest you?

**Comment by amit-62** [comment]
Hello @haircommander I want to work on this issue. Can you please help me to solve this issue.
Thank you.

**Comment by haircommander** [comment]
awesome that sounds great @amit-62 ! How familiar are you with prow configuration? the one for cri-o lives in https://github.com/openshift/release/blob/master/ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-main-presubmits.yaml I am not very familiar with prow configuration so I would love your help researching how to express this

**Comment by amit-62** [comment]
I am also not familiar with prow configuration. I want to learn and try to solve issue.

**Comment by haircommander** [comment]
excellent! let me know if I can provide any guidance :)

**Comment by amit-62** [comment]
Currently I am going through prow documentation. I will try to solve it as soon as possible.

**Comment by amit-62** [comment]
Hi @haircommander  while reading prow documentation I have across a solution that `skip_if_only_changed: "^docs/|\\.(md|adoc)$|^(README|LICENSE)$"`. Can you please look into it at this [link](https://docs.prow.k8s.io/docs/jobs/#triggering-jobs-based-on-changes).
Thank you.

**Comment by haircommander** [comment]
that looks like exactly what we're looking for! well done :smiley: would you like to open a PR?

**Comment by amit-62** [comment]
okay I will do it.

**Comment by amit-62** [comment]
I have created [PR](https://github.com/openshift/release/pull/35388) pelase review and suggest improvements.

**Comment by amit-62** [comment]
I want to work on more issue which one I should look for. Please help me find some issue.

**Comment by haircommander** [comment]
fixed with https://github.com/openshift/release/pull/35388
