### ISSUE TITLE
404 errors for kubic release keys (1.24.0, 1.25.0, 1.26.0)

### ISSUE THREAD

**Issue by jefflill** [cri-o/cri-o#6513]
### What happened?

We're unable to install CRI-O on Kubernetes 1.24.0.  I poked around and it looks like the **Release.key** files are missing on Kubic.  All of these requests are failing with 404s:

https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/1.24.0/Release.key
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/1.25.0/Release.key
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/1.26.0/Release.key

This is probablyrelated to: #6512

### What did you expect to happen?

I expected these key files to be downloadable.

### How can we reproduce it (as minimally and precisely as possible)?

Just try to GET the links above.

### CRI-O and Kubernetes version

Kubernetes: 1.24.0
CRI-O: 1.24.0

### OS version

<details>

```console
# On Linux:
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

# paste output here
$ uname -a
Linux ubuntu 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
Hyper-V
</details>

**Comment by haircommander** [comment]
does running with the latest CRI-O 1.24.4 work for you? we ensure compatibility on the minor version, so the patch version (x.y.z <- the z) doesn't have to match.

**Comment by jefflill** [comment]
This started working again yesterday.  Sorry, I should have updated the issue.

You can close this now.

**Comment by haircommander** [comment]
ah interesting, glad it is working now. closing
