### ISSUE TITLE
Checkpoint/Restore: If the restored process crashes there is no retry possible

### ISSUE THREAD

**Issue by hesch** [cri-o/cri-o#6515]
### What happened?

I noticed that if I restore a container and somewhere down the line the process crashes, it will not be restarted. CRI-O will report back the error: 
```
Error: kubelet may be retrying requests that are timing out in CRI-O due to system load: error reserving ctr name k8s_the-count_test-pod_default_e4c734af-cf12-4013-9aef-7387e07e52bd_0 for id 4ebf87079692b8a9a80634f6112404b12a5e088b6e1fbd9
```

### What did you expect to happen?

I think the restore should be retryable especially since Kubernetes already has an implementation for `CrashLoopBackoff`.

### How can we reproduce it (as minimally and precisely as possible)?

1. Checkpoint a Pod
2. Restore the Pod
3. Kill the container process

### Anything else we need to know?

The error message comes from here:
https://github.com/cri-o/cri-o/blob/7fbf54b055077bb126b95d11d866f3b0eab77ec5/server/container_restore.go#L300-L302

In the normal container create code path if the name is already reserved, the previously created container is returned. @adrianreber Can the restore also do that? 

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.25.0
Version:        1.25.0
GitCommit:      9a628897a447501688a8462efc179037c2199f98
GitCommitDate:  2022-12-21T09:42:15Z
GitTreeState:   dirty
BuildDate:      2023-01-05T01:33:02Z
GoVersion:      go1.18.1
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:
  containers_image_ostree_stub
  libdm_no_deferred_remove
  containers_image_openpgp
  seccomp
  selinux
LDFlags:           -X github.com/cri-o/cri-o/internal/pkg/criocli.DefaultsPath="" -X github.com/cri-o/cri-o/internal/version.buildDate=2023-01-05T01:33:02Z
SeccompEnabled:   true
AppArmorEnabled:  false
Dependencies:
```

```console
$ kubectl --version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:29:58Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux chrd-w-c208 5.15.0-57-generic #63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by adrianreber** [comment]
> In the normal container create code path if the name is already reserved, the previously created container is returned. @adrianreber Can the restore also do that?

Sounds like a good idea. Will look into it. Thanks for the report.

**Comment by varungup90** [comment]
Hi @adrianreber 

I see issue is auto-closed, was there a resolution reached? Getting similar error on restore.

```
Events:
  Type     Reason     Age    From               Message
  ----     ------     ----   ----               -------
  Normal   Scheduled  6m14s  default-scheduler  Successfully assigned default/ndb-dbengine-init-1-vedbm-shenxyzg194-xndlv to 127.0.0.1
  Normal   Pulled     6m13s  kubelet            Container image "hub.byted.org/bytendb2b/bytendb_dbengine_serverless:6788d00a7941226cc882b0c1f398ba7c" already present on machine
  Normal   Created    6m13s  kubelet            Created container ndb-dbengine-init
  Normal   Started    6m13s  kubelet            Started container ndb-dbengine-init
  Normal   Killing    31s    kubelet            Container ndb-dbengine-init definition changed, will be restarted
  Normal   Pulled     0s     kubelet            Container image "localhost/serverless10:latest" already present on machine
  Warning  Failed     0s     kubelet            Error: kubelet may be retrying requests that are timing out in CRI-O due to system load: error reserving ctr name k8s_ndb-dbengine-init_ndb-dbengine-init-1-vedbm-shenxyzg194-xndlv_default_a218b1a3-f5fc-4e42-9480-d4c8c6d04915_0 for id 0ae896104127a531c60acf40e98fc15d6c192e374ab08f93261f12c7342d838a: name is reserved
```

**Comment by hesch** [comment]
This "bug" is not the root cause of why your process is crashing. I just brought it up as a nice to have. Also the error message shown by CRI-O in this case is not helpful.

To resolve this on your end, you need to find out why your container is crashing. For me it was because of slightly different CPU architectures, which led to an illegal instruction being executed down the line somewhere.

**Comment by varungup90** [comment]
@hesch I manually restarted the container, as part of extensive testing post restore. 

If I create a pod from source image and restart the container manually, then container will restart as expected. But if I create a pod with checkpoint image (restore the pod), then restarting a container does not work. That is my concern due to behavior difference, not sure if this is a bug or expected behavior for a restored pod?

**Comment by hesch** [comment]
@varungup90 At the moment it is not possible to restart restored containers. So in a way this is expected. 

In principle there should be nothing wrong with restoring a container multiple times, but it is not implemented yet.

**Comment by adrianreber** [comment]
> I see issue is auto-closed, was there a resolution reached?

Not really. We need to define what happens if a restored container crashes. Do we restore from checkpoint or restart from scratch. I guess restore from checkpoint is the expected outcome. Not sure if it really helps. If it fails because CRIU fails then it will just keep on failing. Restoring on a CPU with the wrong feature will result in the same problem after restoring multiple times.

**Comment by WhaleSpring** [comment]
Hi @adrianreber!
When trying to restore a container, I encountered the same error as above. Is there a method to solve it?
On the container runs  a python3 flask app, and I find the container will be `Running` for about 20 seconds and than it will be error . If I delete the pod to restart it it will be ` CreateContainerError `. And I found the image of checkpoint are less than the container image.
![image](https://github.com/cri-o/cri-o/assets/81799971/e2882622-6d46-4e30-a27f-9df683b98cd9)
I want to know how to find out the cause of this problem and solve it. Maybe it's the problem of python3's container?

**Comment by hesch** [comment]
@WhaleSpring As stated in the comments above, restarting restored containers is not possible. If you want to fix the root cause of the bug, you need to investigate what is making your containers crash in the first place. Fixing this in CRI-O will only mitigate the crashes, because CRI-O will be able to restart the crashed containers.

@adrianreber also can we reopen this? AFAIK this is not fixed and we should implement a solution. In my opinion restoring the same checkpoint would be the expected behaviour, because the container was created from the checkpoint image in the first place.

**Comment by WhaleSpring** [comment]
> @WhaleSpring As stated in the comments above, restarting restored containers is not possible. If you want to fix the root cause of the bug, you need to investigate what is making your containers crash in the first place. Fixing this in CRI-O will only mitigate the crashes, because CRI-O will be able to restart the crashed containers.
> 
> @adrianreber also can we reopen this? AFAIK this is not fixed and we should implement a solution. In my opinion restoring the same checkpoint would be the expected behaviour, because the container was created from the checkpoint image in the first place.

Thank you. My understanding is that some of my configurations caused this issue when CRI-O attempted to recover the container. When I create a new cluster, it can restore a container normally, and I will continue to verify what changes caused this error.

**Comment by WhaleSpring** [comment]
> @WhaleSpring As stated in the comments above, restarting restored containers is not possible. If you want to fix the root cause of the bug, you need to investigate what is making your containers crash in the first place. Fixing this in CRI-O will only mitigate the crashes, because CRI-O will be able to restart the crashed containers.
> 
> @adrianreber also can we reopen this? AFAIK this is not fixed and we should implement a solution. In my opinion restoring the same checkpoint would be the expected behaviour, because the container was created from the checkpoint image in the first place.

Could you please tell me how to check the cause of container crash？

**Comment by hesch** [comment]
@WhaleSpring You can debug this just like you would any other crash. Look at the Logs or if that doesn't help, attach a debugger and see if you can find out what's happening.

**Comment by WhaleSpring** [comment]
> @WhaleSpring You can debug this just like you would any other crash. Look at the Logs or if that doesn't help, attach a debugger and see if you can find out what's happening.

Maybe my issue is caused by something in OpenFaaS Function Container, for the sake that I can restore a ngix pod in a worker node when OpenFaaS Function Pod can't do it. Although I don't know what resulted the crash, but it seems that CRI-O can't restore a OpenFaaS function.
