### ISSUE TITLE
ci-e2e-conmonrs flakes

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#6523]
### Which jobs are failing?

ci-e2e-conmonrs

### Which tests are failing?

Kubernetes e2e suite: [It] [sig-cli] Kubectl client Simple pod should support inline execution and attach

### Since when has it been failing?

Since before winter break

### Testgrid link

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/cri-o_cri-o/6514/pull-ci-cri-o-cri-o-main-ci-e2e-conmonrs/1612940150650703872

### Reason for failure (if possible)

I'm hoping https://github.com/containers/conmon-rs/pull/991 fixes

**Comment by sohankunkerkar** [comment]
I don't see that test flake anymore. I'm closing this for now but feel free to open it if you see this issue again.
