### ISSUE TITLE
Packages not found (1.25.*) (Ubuntu 18.04)

### ISSUE THREAD

**Issue by bandwiches** [cri-o/cri-o#6526]
### What happened?

It appears that all the CRI-O (1.25.*) packages are missing from the Ubuntu 18.04 repo's.

### What did you expect to happen?

Expected `apt` to install  `cri-o` and `cri-o-runc` packages

`cri-o` errored (could not be located)
`cri-o-runc` was found.

### How can we reproduce it (as minimally and precisely as possible)?

You can actually view it [here](https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/)

I browsed all the `1.25:/` and `1.25/` directories and all the `Ubuntu 18.04` directories were missing the package.  Checked a few `Ubuntu 22.04` directories and they appeared to have the packages. 

### Anything else we need to know?

N/A

### CRI-O and Kubernetes version

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ uname -a
Linux ###### 4.15.0-201-generic #212-Ubuntu SMP Mon Nov 28 11:29:59 UTC 2022 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
Physical
</details>

**Comment by SungYil** [comment]
we have same problem . How do I solve the problem?

**Comment by Yessoami** [comment]
I have same problem with k8s 1.25, ubuntu 22.04 now. I also need solution for this issue asap.

**Comment by flavono123** [comment]
Got a same issue for Ubuntu 20.04.

Specify the repository with the crio patch version, it works for now(.../1.25:/**1.25.2**/xUbuntu_20.04/ ):
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25:/1.25.2/xUbuntu_20.04/

**Comment by bandwiches** [comment]
If you want to install from repo I'd suggest the workaround from @flavono123

Another alternative is to browse to the releases and install the package manually.   I did this yesterday for my node using the 1.25.1 release and it worked fine.

**Comment by haircommander** [comment]
sorry everyone! I messed something up with the package trying to fix https://github.com/cri-o/cri-o/issues/6513 the fix is on its way

**Comment by flavono123** [comment]
Confirmed now the following repo works:
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25/xUbuntu_20.04/

**Comment by bandwiches** [comment]
Looks good to me as well, thanks!
