### ISSUE TITLE
Missing ARM64 Builds for xUbuntu_22.04

### ISSUE THREAD

**Issue by isugimpy** [cri-o/cri-o#6533]
### What happened?

When attempting to install various ARM64 builds (1.22.x, 1.23.x) for xUbuntu_22.04, no ARM64 packages are available.

### What did you expect to happen?

The packages would be in the repository and be installable.

### How can we reproduce it (as minimally and precisely as possible)?

Attempt to install 1.22.x or 1.23.x on ARM64 using the xUbuntu_22.04 path.  The install will fail indicating that the cri-o package does not exist.

### CRI-O and Kubernetes version

No version data as the packages cannot be installed due to the repository issue.

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux ip-10-8-55-217.ec2.internal 5.15.0-1023-aws #27-Ubuntu SMP Thu Oct 20 16:46:19 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by haircommander** [comment]
I toggled the switches for 1.22 and 1.23, should be ready in an hour or so

**Comment by isugimpy** [comment]
Is there anywhere to watch the status on those builds?  I thought I'd see them in GH actions, but nothing was triggered around the time you mentioned, and I don't see the files in the remote repo.

**Comment by haircommander** [comment]
you can go to https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable:cri-o:1.23/cri-o and see the build progress! they seem to be built now, can you try now?

**Comment by isugimpy** [comment]
Build artifacts are present now.  Thank you!
