### ISSUE TITLE
cri-o 1.25.2 packages missing for centos7 x86_64

### ISSUE THREAD

**Issue by grunlab** [cri-o/cri-o#6543]
### What happened?

cri-o 1.25.2 packages are currently missing for centos7 x86_64:
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25:/1.25.2/CentOS_7/x86_64/

Thank you for your support

### What did you expect to happen?

n/a

### How can we reproduce it (as minimally and precisely as possible)?

n/a

### Anything else we need to know?

n/a

### CRI-O and Kubernetes version

n/a

### OS version

n/a

### Additional environment details (AWS, VirtualBox, physical, etc.)

n/a

**Comment by grunlab** [comment]
Crio 1.25.2 build failed for centos7 x86_64:
https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable:cri-o:1.25/cri-o
https://build.opensuse.org/package/live_build_log/devel:kubic:libcontainers:stable:cri-o:1.25/cri-o/CentOS_7/x86_64

Thank you for your support

**Comment by SiliconAlley** [comment]
Hi,
same issue for 1.26 CentOS...

Thank you for the info and links. 1.26 has also build failed.

What goes on behind the scenes? Is there some automation to solve failed builds? I was seeking for 1.26.1 for the same architecture.

**Comment by haircommander** [comment]
both 1.26 and 1.25 should be fixed now, PTAL

**Comment by SiliconAlley** [comment]
Many thanks haircommander. I see 1.26.1 in the repo now. Will try later to fetch it. But not 1.25.2 @grunlab

**Comment by grunlab** [comment]
Effectively, 1.25.2 builds are still KO for Centos7/8:

https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25/CentOS_7/x86_64/
https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable:cri-o:1.25/cri-o

**Comment by haircommander** [comment]
whoops, should be fixed now!

**Comment by SiliconAlley** [comment]
Thanks, I see it. Also need it, as I cannot jump from 1.24 to 1.26 regarding the skew policy.

**Comment by grunlab** [comment]
1.25.2 packages for centos x86_64 are now available.
I've just installed them on centos7, all is OK
Thank you
