### ISSUE TITLE
`crio-status` could be a sub command of `crio`: `crio status`

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#6546]
I can't remember why we went with a separate binary, but coupling them  would reduce binaries installed and probably not increase the binary size that much

**Comment by saschagrunert** [comment]
Indeed, I'm wondering why we have not done this initially.

**Comment by theVJagrawal** [comment]
hey @saschagrunert i want to work on this issue so can you please elaborate it more

**Comment by haircommander** [comment]
hey @theVJagrawal , @navishidhu already opened a PR to fix here https://github.com/cri-o/cri-o/pull/6557
