### ISSUE TITLE
cri-o > 1.26 unknown service runtime.v1alpha2.RuntimeService

### ISSUE THREAD

**Issue by chg-dio** [cri-o/cri-o#6554]
### What happened?

Hello,

I guess this might not be a cri-o topic but I am not really sure were else to aks for help.
I use a install script to install cri-o into flatcar that is working without any problems until cri-o 1.25.2

I want to update to 1.26.1 but after the inital deployment I can't use any of my tools, e.g. crictl or kubeadm even if the status of the crio service is fine (expand details) I always get some error messages like this one:

<details>

```
worker1 ~ # crio-status info
cgroup driver: systemd
storage driver: overlay
storage root: /opt/var/lib/containers/storage
default GID mappings (format <container>:<host>:<size>):
  0:0:4294967295
default UID mappings (format <container>:<host>:<size>):
  0:0:4294967295
 ```
 ```
worker1 ~ # crio -v
crio version 1.26.1
Version:        1.26.1
GitCommit:      69945ab622a70ab01f4b0df10b107bc48e38dc9e
GitCommitDate:  2023-01-10T21:20:34Z
GitTreeState:   dirty
BuildDate:      1980-01-01T00:00:00Z
GoVersion:      go1.19.4
Compiler:       gc
Platform:       linux/amd64
Linkmode:       static
BuildTags:
  static
  netgo
  osusergo
  exclude_graphdriver_btrfs
  exclude_graphdriver_devicemapper
  seccomp
  apparmor
  selinux
LDFlags:          unknown
SeccompEnabled:   true
AppArmorEnabled:  false
Dependencies:
```
```
worker1 ~ # systemctl status crio
● crio.service - Container Runtime Interface for OCI (CRI-O)
     Loaded: loaded (/etc/systemd/system/crio.service; enabled; vendor preset: disabled)
     Active: active (running) since Thu 2023-01-19 12:12:13 UTC; 6min ago
       Docs: https://github.com/cri-o/cri-o
   Main PID: 860 (crio)
      Tasks: 7
     Memory: 71.2M
        CPU: 128ms
     CGroup: /system.slice/crio.service
             └─860 /opt/bin/crio

Jan 19 12:12:13 worker1 crio[860]: time="2023-01-19 12:12:13.675823117Z" level=info msg="Conmon does support the --log-global-size-max option"
Jan 19 12:12:13 worker1 crio[860]: time="2023-01-19 12:12:13.686787095Z" level=info msg="Found CNI network crio (type=bridge) at /etc/cni/net.d/11-crio-ipv4-bridge.conflist"
Jan 19 12:12:13 worker1 crio[860]: time="2023-01-19 12:12:13.686816691Z" level=info msg="Updated default CNI network name to crio"
Jan 19 12:12:13 worker1 crio[860]: time="2023-01-19 12:12:13.718765057Z" level=warning msg="Error encountered when checking whether cri-o should wipe containers: open /var/run/crio/version: no such file or directory"
Jan 19 12:12:13 worker1 crio[860]: time="2023-01-19 12:12:13.719083023Z" level=info msg="Starting seccomp notifier watcher"
Jan 19 12:12:13 worker1 crio[860]: time="2023-01-19 12:12:13.719122167Z" level=info msg="Create NRI interface"
Jan 19 12:12:13 worker1 crio[860]: time="2023-01-19 12:12:13.719129080Z" level=info msg="NRI interface is disabled in the configuration."
Jan 19 12:12:13 worker1 crio[860]: time="2023-01-19 12:12:13.719989143Z" level=error msg="Writing clean shutdown supported file: open /var/lib/crio/clean.shutdown.supported: no such file or directory"
Jan 19 12:12:13 worker1 crio[860]: time="2023-01-19 12:12:13.720022476Z" level=error msg="Failed to sync parent directory of clean shutdown file: open /var/lib/crio: no such file or directory"
Jan 19 12:12:13 worker1 systemd[1]: Started Container Runtime Interface for OCI (CRI-O).
```

</details>

Tools usage  (everything is fine with crio <= 1.25.2):

```
worker1 ~ # crictl image
FATA[0000] listing images: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService
```

```
worker1 ~ # kubeadm init --config=kubeadm-config.yaml
[init] Using Kubernetes version: v1.26.0
[preflight] Running pre-flight checks
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR CRI]: container runtime is not running: output: time="2023-01-19T17:19:41Z" level=fatal msg="getting status of runtime: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
```

### What did you expect to happen?

crictl or kubeadm are able to use the crio runtime

### How can we reproduce it (as minimally and precisely as possible)?

1.) Install FlatCar
2.) Use the CRI-O install steps below

```
"sudo mkdir -p /opt/var/lib/{containers,etcd,kubelet}",
"sudo ln -s /opt/var/lib/containers /var/lib/containers",
"sudo ln -s /opt/var/lib/etcd /var/lib/etcd",
"sudo ln -s /opt/var/lib/kubelet /var/lib/kubelet",
"cd ~",
# "URL=$(curl -s https://api.github.com/repos/cri-o/cri-o/releases | jq -r '. |= sort_by(.tag_name) | .[-1] | .assets[] | select(.name|test(\"amd64.*.tar.gz$\")) | .browser_download_url')",
"curl -sL https://github.com/cri-o/cri-o/releases/download/${var.crio_version}/cri-o.amd64.${var.crio_version}.tar.gz | tar xzvf -",
"cd cri-o",
"sudo cp bin/* /opt/bin/",
"sudo mkdir -p /opt/cni/bin",
"sudo cp cni-plugins/* /opt/cni/bin/",
"sudo cp etc/crio-umount.conf /etc/",
"sudo mkdir -p /etc/crio/crio.conf.d",
"sudo cp etc/crio.conf /etc/crio/",
"sudo cp etc/10-crun.conf /etc/crio/crio.conf.d/",
"sudo cp etc/crictl.yaml /etc/",
"sudo mkdir -p /etc/cni/net.d",
"sudo cp contrib/11-crio-ipv4-bridge.conflist /etc/cni/net.d/",
# cri-o <= 1.25.2 # "sudo cp contrib/10-crio-bridge.conf /etc/cni/net.d/",
"sudo mkdir /etc/containers",
"sudo cp contrib/policy.json /etc/containers/",
"sudo sh -c \"sed 's:/usr/local/bin:/opt/bin:g' contrib/crio.service  > /etc/systemd/system/crio.service\"",
"sudo systemctl daemon-reload",
"sudo systemctl stop docker containerd",
"sudo systemctl mask docker containerd",
"sudo systemctl enable crio",
"sudo systemctl start crio"
```

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
worker1 ~ # crio --version
crio version 1.26.0
Version:        1.26.0
GitCommit:      214b77367c48acd75a08610ac8d0941540347691
GitCommitDate:  2022-12-23T04:59:24Z
GitTreeState:   dirty
BuildDate:      1980-01-01T00:00:00Z
GoVersion:      go1.18.1
Compiler:       gc
Platform:       linux/amd64
Linkmode:       static
BuildTags:
  static
  netgo
  osusergo
  exclude_graphdriver_btrfs
  exclude_graphdriver_devicemapper
  seccomp
  apparmor
  selinux
LDFlags:          -s -w -X github.com/cri-o/cri-o/internal/pkg/criocli.DefaultsPath="" -X github.com/cri-o/cri-o/internal/version.buildDate=1980-01-01T00:00:00Z -s -w -linkmode external -extldflags "-static -lm"
SeccompEnabled:   true
AppArmorEnabled:  false
Dependencies:

```

```console
$ kubectl --version
Client Version: v1.26.1
Kustomize Version: v4.5.7
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=3374.2.2
VERSION_ID=3374.2.2
BUILD_ID=2023-01-11-0143
SYSEXT_LEVEL=1.0
PRETTY_NAME="Flatcar Container Linux by Kinvolk 3374.2.2 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar.org/"
BUG_REPORT_URL="https://issues.flatcar.org"
FLATCAR_BOARD="amd64-usr"
CPE_NAME="cpe:2.3:o:flatcar-linux:flatcar_linux:3374.2.2:*:*:*:*:*:*:*"
$ uname -a
Linux worker1 5.15.79-flatcar #1 SMP Wed Jan 11 01:09:45 -00 2023 x86_64 AMD EPYC Processor AuthenticAMD GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
Hetzner Cloud
</details>

**Comment by haircommander** [comment]
hey @chg-dio it looks like the crictl version used to determine
```
        [ERROR CRI]: container runtime is not running: output: time="2023-01-19T17:19:41Z" level=fatal msg="getting status of runtime: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
```
do you know the version of crictl in flatcar?

**Comment by chg-dio** [comment]
Yes, of course. I always use the crictl version shipped with the release version I download, e.g.:

`"curl -sL https://github.com/cri-o/cri-o/releases/download/v1.25.2/cri-o.amd64.v1.25.2.tar.gz | tar xzvf -`

The only change I make is the version bump and this change within the install script:

```
        # cri-o >= 1.26.0
        "sudo cp contrib/11-crio-ipv4-bridge.conflist /etc/cni/net.d/",
        # cri-o <= 1.25.2
        # "sudo cp contrib/10-crio-bridge.conf /etc/cni/net.d/",
```

I made a complete test with booth versions, because I mixed up some stuff in my first post. Please note that kubeadm throw the same error, not only crictl:

```
[ERROR CRI]: container runtime is not running: output: time="2023-01-20T08:27:48Z" level=fatal msg="getting status of runtime: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
```

cri-o v1.25.2
crictl v1.19.0
kubeadm v1.25.2

<details>

```
$ crictl images
IMAGE               TAG                 IMAGE ID            SIZE
```
```
$ kubeadm init
node1 ~ # kubeadm init --config=kubeadm.yaml
W0120 08:07:21.272051    1757 common.go:84] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta2". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0120 08:07:21.272834    1757 common.go:84] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta2". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0120 08:07:21.273157    1757 initconfiguration.go:119] Usage of CRI endpoints without URL scheme is deprecated and can cause kubelet errors in the future. Automatically prepending scheme "unix" to the "criSocket" with value "/var/run/crio/crio.sock". Please update your configuration!
I0120 08:07:21.555077    1757 version.go:256] remote version is much newer: v1.26.1; falling back to: stable-1.25
[init] Using Kubernetes version: v1.25.6
[preflight] Running pre-flight checks
        [WARNING SystemVerification]: missing optional cgroups: blkio
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
...
...
...
Your Kubernetes control-plane has initialized successfully!
```
```
$ crio-status info
cgroup driver: systemd
storage driver: overlay
storage root: /var/lib/containers/storage
default GID mappings (format <container>:<host>:<size>):
  0:0:4294967295
default UID mappings (format <container>:<host>:<size>):
  0:0:4294967295
```
```
$ crio -v
Version:        1.25.2
GitCommit:      1d7407e62446d25ca4fa77c9f6853143ec994d15
GitCommitDate:  2023-01-10T08:32:36Z
GitTreeState:   dirty
BuildDate:      1980-01-01T00:00:00Z
GoVersion:      go1.18.1
Compiler:       gc
Platform:       linux/amd64
Linkmode:       static
BuildTags:
  static
  netgo
  osusergo
  exclude_graphdriver_btrfs
  exclude_graphdriver_devicemapper
  seccomp
  apparmor
  selinux
LDFlags:          -s -w -X github.com/cri-o/cri-o/internal/pkg/criocli.DefaultsPath="" -X github.com/cri-o/cri-o/internal/version.buildDate=1980-01-01T00:00:00Z -s -w -linkmode external -extldflags "-static -lm"
SeccompEnabled:   true
AppArmorEnabled:  false
Dependencies:
```
```
$ systemctl status crio
crio.service - Container Runtime Interface for OCI (CRI-O)
     Loaded: loaded (/etc/systemd/system/crio.service; enabled; vendor preset: disabled)
     Active: active (running) since Fri 2023-01-20 07:45:17 UTC; 3min 18s ago
       Docs: https://github.com/cri-o/cri-o
   Main PID: 1270 (crio)
      Tasks: 7
     Memory: 23.6M
        CPU: 82ms
     CGroup: /system.slice/crio.service
             └─1270 /opt/bin/crio

Jan 20 07:45:17 node1 crio[1270]: time="2023-01-20 07:45:17.396322695Z" level=info msg="Conmon does support the --sync option"
Jan 20 07:45:17 node1 crio[1270]: time="2023-01-20 07:45:17.396355256Z" level=info msg="Conmon does support the --log-global-size-max option"
Jan 20 07:45:17 node1 crio[1270]: time="2023-01-20 07:45:17.396992682Z" level=info msg="Conmon does support the --sync option"
Jan 20 07:45:17 node1 crio[1270]: time="2023-01-20 07:45:17.397022748Z" level=info msg="Conmon does support the --log-global-size-max option"
Jan 20 07:45:17 node1 crio[1270]: time="2023-01-20 07:45:17.398980100Z" level=info msg="Found CNI network crio (type=bridge) at /etc/cni/net.d/10-crio-bridge.conf"
Jan 20 07:45:17 node1 crio[1270]: time="2023-01-20 07:45:17.399017119Z" level=info msg="Updated default CNI network name to crio"
Jan 20 07:45:17 node1 crio[1270]: time="2023-01-20 07:45:17.433627074Z" level=warning msg="Error encountered when checking whether cri-o should wipe containers: open /var/run/crio/version: no such file or directory"
Jan 20 07:45:17 node1 crio[1270]: time="2023-01-20 07:45:17.433920313Z" level=error msg="Writing clean shutdown supported file: open /var/lib/crio/clean.shutdown.supported: no such file or directory"
Jan 20 07:45:17 node1 crio[1270]: time="2023-01-20 07:45:17.433939840Z" level=error msg="Failed to sync parent directory of clean shutdown file: open /var/lib/crio: no such file or directory"
Jan 20 07:45:17 node1 systemd[1]: Started Container Runtime Interface for OCI (CRI-O).

```

</details>

cri-o v1.26.1
crictl v1.19.0
kubeadm v1.26.1

<details>

```
```
$ crictl images
FATA[0000] listing images: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService
```
```
$ kubeadm init
node1 ~ # kubeadm init --config=kubeadm-config.yaml
W0120 08:27:48.064407    1482 common.go:84] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta2". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0120 08:27:48.064699    1482 common.go:84] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta2". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0120 08:27:48.065455    1482 initconfiguration.go:119] Usage of CRI endpoints without URL scheme is deprecated and can cause kubelet errors in the future. Automatically prepending scheme "unix" to the "criSocket" with value "/var/run/crio/crio.sock". Please update your configuration!
[init] Using Kubernetes version: v1.26.1
[preflight] Running pre-flight checks
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR CRI]: container runtime is not running: output: time="2023-01-20T08:27:48Z" level=fatal msg="getting status of runtime: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
```
```
$ crio-status info
cgroup driver: systemd
storage driver: overlay
storage root: /var/lib/containers/storage
default GID mappings (format <container>:<host>:<size>):
  0:0:4294967295
default UID mappings (format <container>:<host>:<size>):
  0:0:4294967295
```
```
$ crio -v
crio version 1.26.1
Version:        1.26.1
GitCommit:      69945ab622a70ab01f4b0df10b107bc48e38dc9e
GitCommitDate:  2023-01-10T21:20:34Z
GitTreeState:   dirty
BuildDate:      1980-01-01T00:00:00Z
GoVersion:      go1.19.4
Compiler:       gc
Platform:       linux/amd64
Linkmode:       static
BuildTags:
  static
  netgo
  osusergo
  exclude_graphdriver_btrfs
  exclude_graphdriver_devicemapper
  seccomp
  apparmor
  selinux
LDFlags:          unknown
SeccompEnabled:   true
AppArmorEnabled:  false
Dependencies:
```
```
$ systemctl status crio
crio.service - Container Runtime Interface for OCI (CRI-O)
     Loaded: loaded (/etc/systemd/system/crio.service; enabled; vendor preset: disabled)
     Active: active (running) since Fri 2023-01-20 08:21:28 UTC; 7min ago
       Docs: https://github.com/cri-o/cri-o
   Main PID: 1269 (crio)
      Tasks: 7
     Memory: 23.4M
        CPU: 85ms
     CGroup: /system.slice/crio.service
             └─1269 /opt/bin/crio

Jan 20 08:21:28 node1 crio[1269]: time="2023-01-20 08:21:28.366238749Z" level=info msg="Conmon does support the --log-global-size-max option"
Jan 20 08:21:28 node1 crio[1269]: time="2023-01-20 08:21:28.367856643Z" level=info msg="Found CNI network crio (type=bridge) at /etc/cni/net.d/11-crio-ipv4-bridge.conflist"
Jan 20 08:21:28 node1 crio[1269]: time="2023-01-20 08:21:28.367873855Z" level=info msg="Updated default CNI network name to crio"
Jan 20 08:21:28 node1 crio[1269]: time="2023-01-20 08:21:28.399942072Z" level=warning msg="Error encountered when checking whether cri-o should wipe containers: open /var/run/crio/version: no such file or directory"
Jan 20 08:21:28 node1 crio[1269]: time="2023-01-20 08:21:28.400372269Z" level=info msg="Starting seccomp notifier watcher"
Jan 20 08:21:28 node1 crio[1269]: time="2023-01-20 08:21:28.400468700Z" level=info msg="Create NRI interface"
Jan 20 08:21:28 node1 crio[1269]: time="2023-01-20 08:21:28.400533121Z" level=info msg="NRI interface is disabled in the configuration."
Jan 20 08:21:28 node1 crio[1269]: time="2023-01-20 08:21:28.400719080Z" level=error msg="Writing clean shutdown supported file: open /var/lib/crio/clean.shutdown.supported: no such file or directory"
Jan 20 08:21:28 node1 crio[1269]: time="2023-01-20 08:21:28.400794742Z" level=error msg="Failed to sync parent directory of clean shutdown file: open /var/lib/crio: no such file or directory"
Jan 20 08:21:28 node1 systemd[1]: Started Container Runtime Interface for OCI (CRI-O).

```

</details>

**Comment by grassdionera** [comment]
It seems that we have a Problem that looks similar, with neuvector running in Kubernetes

We have neuvector configured to use crio as runtime and it was running successfully until the update of k8s and crio to 1.26.0.
Since that update the neuvector controller pod throws the following error and exits
`unknown service runtime.v1alpha2.RuntimeService`



neuvector: 5.1.0
k8s: 1.26.0
crio: 1.26.0

```
neuvector-controller-pod-8b5d8f7d7-d6ffw 2023-01-20T08:27:13.943|INFO|CTL|system.NewSystemTools: cgroup v2
neuvector-controller-pod-8b5d8f7d7-d6ffw 2023-01-20T08:27:13.943|INFO|CTL|container.Connect: - endpoint=
neuvector-controller-pod-8b5d8f7d7-d6ffw 2023-01-20T08:27:13.944|WARN|CTL|container.parseEndpointWithFallbackProtocol: no error unix /var/run/crio/crio.sock.
neuvector-controller-pod-8b5d8f7d7-d6ffw 2023-01-20T08:27:13.945|ERRO|CTL|container.crioConnect: Fail to get crio version - error=rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
neuvector-controller-pod-8b5d8f7d7-d6ffw 2023-01-20T08:27:13.945|ERRO|CTL|main.main: Failed to initialize - error=Unknown container runtime
neuvector-controller-pod-8b5d8f7d7-d6ffw 2023-01-20T08:27:13|MON|Process ctrl exit status 254, pid=7
neuvector-controller-pod-8b5d8f7d7-d6ffw 2023-01-20T08:27:13|MON|Process ctrl exit with non-recoverable return code. Monitor Exit!!
```

**Comment by haircommander** [comment]
So the root of the problem is the client isn't using CRI v1. Since Kubernetes moved to CRI v1, other clients should do so as well (or at least support both and fallback like the Kubelet did for a couple of releases). I assumed kubeadm was calling crictl to do this check, but it's possible it nests a cri client internally. I tried poking around a bit and couldn't find where in kubeadm this happens.

Possibly worth opening an issue there, as well as in neuvector? It would be my ideal to continue to not support CRI v1alpha2 as it required a lot of code to do so

**Comment by chg-dio** [comment]
https://github.com/kubernetes-sigs/cri-tools/issues/1069

**Comment by chg-dio** [comment]
I will close this issue since it is not a cri-o topic at all.
Thanks for your input haircommander.

**Comment by Nurlan199206** [comment]
i got same issue help plss

`unknown service runtime.v1alpha2.runtimeservice`

**Comment by haircommander** [comment]
what client are you using @Nurlan199206 ? can you update it to a version that uses v1 of the CRI?
