### ISSUE TITLE
REQUEST: New organization membership for adrianreber

### ISSUE THREAD

**Issue by adrianreber** [cri-o/cri-o#6562]
### GitHub Username

@adrianreber

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have one sponsor from the list of approvers in at least one OWNERS file within the CRI-O repository
- [X] I have spoken to my sponsor ahead of this application, and they have agreed to sponsor my application

### Sponsor

@haircommander

### List of contributions to the CRI-O project

- https://github.com/cri-o/cri-o/pull/1427
- https://github.com/cri-o/cri-o/pull/1926
- https://github.com/cri-o/cri-o/pull/4199
- https://github.com/cri-o/cri-o/pull/6181
- https://github.com/cri-o/cri-o/pull/6203
- https://github.com/cri-o/cri-o/pull/6338
- https://github.com/cri-o/cri-o/pull/6342
- https://github.com/cri-o/cri-o/pull/6379

**Comment by saschagrunert** [comment]
+1 for Adrian! :partying_face:

**Comment by haircommander** [comment]
LGTM :tada:

**Comment by haircommander** [comment]
I've sent you an invitation @adrianreber :)
