### ISSUE TITLE
REQUEST: New reviewer status for littlejawa

### ISSUE THREAD

**Issue by littlejawa** [cri-o/cri-o#6578]
### GitHub Username

littlejawa

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have one sponsor from the list of approvers in at least one OWNERS file within the CRI-O repository
- [X] I have spoken to my sponsor ahead of this application, and they have agreed to sponsor my application

### Sponsor

haircommander

### List of contributions to the CRI-O project

Ongoing PRs:
- #6531
- #6280

Merged PRs:
- #6382
- #6381
- #6165
- #5956
- #5041

Reported issues:
- #6350
- #6175
- #5896

Reviewed PRs:
- #6486
- #6257
- #6123
- #5035

**Comment by haircommander** [comment]
LGTM thanks for your work @littlejawa !

**Comment by saschagrunert** [comment]
+1 from my side!

**Comment by haircommander** [comment]
I've sent an invitation @littlejawa . Welcome to the org :tada:

**Comment by littlejawa** [comment]
Thanks a lot.
Happy to help where I can :-)
