### ISSUE TITLE
Reason field for OOM-killed containers is Error instead of OOMKilled

### ISSUE THREAD

**Issue by mimowo** [cri-o/cri-o#6580]
### What happened?

We are aiming to standardize the OOM killer handling by container runtimes (https://github.com/kubernetes/kubernetes/issues/112910). 

The idea is to standardize that the reason message for OOM killed container is `OOMKilled`, and from our experiments (see: https://github.com/kubernetes/kubernetes/pull/113205) this is the case for containerd (cgroupv1, cgroupv2) and cri-o with cgroupv1. 

However, the container reason for cri-o with cgroupv2 is Error. I guess I should create an issue in CRI-O, but asking here as this might be in progress or solved already (e.g. the testing setup uses an older version). Let me know if you are aware of the status.

### What did you expect to happen?

The `reason` field of an OOMKilled container to equal `OOMKilled`.

### How can we reproduce it (as minimally and precisely as possible)?

This is currently reproduced in the k/k e2e test: https://github.com/kubernetes/kubernetes/pull/113205/files.
See the log output: 
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/113205/pull-kubernetes-node-crio-cgrpv2-e2e/1617805702506483712/

```
{ failed [FAILED] pod: "oomkill-target-pod", container: "oomkill-target-container" has unexpected reason: "Error"
Expected
    <string>: Error
to equal
    <string>: OOMKilled
```

### CRI-O and Kubernetes version

<details>
Reproducible on k/k test infra (as in the test)

```console
$ crio --version
# paste output here
```

```console
$ kubectl --version
# paste output here
```
Latest k8s (master for 1.27)

</details>

### OS version

<details>
  Reproducible on k/k test infra (as in the test)
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
  Reproducible on k/k test infra (as in the test)
</details>

**Comment by haircommander** [comment]
I've spent the day looking into this. It's pretty bizarre because running a similar test (but with crictl) manually gives me the correct state, though running the test fails. I will continue to look at this

**Comment by mimowo** [comment]
@haircommander thanks for looking into this, so it might be just about the test setup (like the old version of something).

Also, asking @harche, as you added the `pull-kubernetes-node-crio-cgrpv2-e2e-kubetest2` test: https://github.com/kubernetes/test-infra/commit/cf9d6c389e43afe386113227357159760dffc0cc. Could you please look into this or suggest how to debug the tests?

**Comment by saschagrunert** [comment]
It's a corner case in conmon and conmon-rs which we should cover. See https://github.com/containers/conmon-rs/pull/1054

**Comment by mimowo** [comment]
@saschagrunert thank you for looking into this! Hope it helps and we can proceed with adding the test in upstream and standardization.

**Comment by com6056** [comment]
Sorry to bump an old issue, but looks like this was released in https://github.com/containers/conmon/releases/tag/v2.1.6, any chance we can get that dependency updated here to pull in that fix? Thanks! 🙌
