### ISSUE TITLE
REQUEST: New organization membership for hasan4791

### ISSUE THREAD

**Issue by hasan4791** [cri-o/cri-o#6598]
### GitHub Username

@hasan4791

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have one sponsor from the list of approvers in at least one OWNERS file within the CRI-O repository
- [X] I have spoken to my sponsor ahead of this application, and they have agreed to sponsor my application

### Sponsor

@haircommander

### List of contributions to the CRI-O project

- https://github.com/cri-o/cri-o/pull/5613
- https://github.com/cri-o/cri-o/pull/6570
- https://github.com/cri-o/cri-o/pull/6579
- https://github.com/cri-o/cri-o/pull/6589

**Comment by haircommander** [comment]
LGTM :)

**Comment by saschagrunert** [comment]
+1 from my side!

**Comment by haircommander** [comment]
You've been invited. Thanks for your contributions!
