### ISSUE TITLE
Skip CI test jobs on PRs with no code changes

### ISSUE THREAD

**Issue by jrvaldes** [cri-o/cri-o#6604]
Follow-up to https://github.com/cri-o/cri-o/issues/6500

The regular expression introduced in https://github.com/openshift/release/pull/35388 is not picking up the expected files. 

For example, in https://github.com/cri-o/cri-o/pull/6576 the `kata-jenkins` CI job was [triggered](http://jenkins.katacontainers.io/job/kata-containers-2-crio-PR/4759/) where the PR only contains documentation [changes](https://github.com/cri-o/cri-o/pull/6576/files). 

This issue should extend the scope of https://github.com/cri-o/cri-o/issues/6500 to skip CI jobs for the following changes:
- docs/
- tutorials/
- .github/
- .gitignore
- *.md
- [OWNERS](https://github.com/cri-o/cri-o/blob/main/OWNERS)
- [SECURITY_CONTACTS](https://github.com/cri-o/cri-o/blob/main/SECURITY_CONTACTS)

**Comment by haircommander** [comment]
I think we could skip `.github`, `logo`, `tutorials`, `build` in addition to the currently present items

**Comment by jrvaldes** [comment]
Makes sense; I will take a stab to nail this down. 

/assign

**Comment by jrvaldes** [comment]
@haircommander , In addition, this update should accommodate the presubmit jobs for release branches as well. i.e. https://github.com/openshift/release/blob/master/ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.24-presubmits.yaml for `release-1.24`, and so on.

**Comment by haircommander** [comment]
agreed!

**Comment by jrvaldes** [comment]
@haircommander  I couldn't find any `build` directory in the repo, so I did not include it in the regex.

Opened https://github.com/openshift/release/pull/36028.

**Comment by jrvaldes** [comment]
> agreed!

Do you recommend proposing the changes in the same PR for `main` or use separate PRs for each release branch?

**Comment by haircommander** [comment]
we can do all in one
