### ISSUE TITLE
Why namespace for crio metrics exporter is hardcoded ?

### ISSUE THREAD

**Issue by djkormo** [cri-o/cri-o#6607]
https://github.com/cri-o/cri-o/blob/6e861a881c1c7124836228c7c7b9abb696f6c283/contrib/metrics-exporter/main.go#L21

`level=fatal msg="Unable to run: %vcreating scrape config map: configmaps is forbidden: User \"system:serviceaccount:monitoring:cri-o-metrics-exporter\" cannot create resource \"configmaps\" in API group \"\" in the namespace \"cri-o-metrics-exporter\""
`

**Comment by haircommander** [comment]
If I were to guess, @saschagrunert didn't see the need in making it configurable. We would definitely welcome a PR making it configurable if you're interested @djkormo

**Comment by amarlearning** [comment]
@haircommander, @djkormo, thank you for raising this issue. I have read through the context and I am interested in contributing by working on it. Would it be possible for you to assign this issue to me so I can start working on a solution? I would appreciate any additional information or guidance you can provide to help me get started.

**Comment by djkormo** [comment]
See my changes in https://github.com/djkormo/cri-o/tree/main/contrib/metrics-exporter. Look at main.go file and variable POD_NAMESPACE. Next Look at deployment with adding this variable to pod env.

**Comment by amarlearning** [comment]
@djkormo Thanks for the quick response, if you have already made the changes, please go ahead and make the PR. I will find something else to work on 😄

**Comment by saschagrunert** [comment]
Thank you for picking this up @djkormo! :pray: Indeed the configuration was not a requirement at creation time.
