### ISSUE TITLE
No cri-o package for SLES 15 SP4

### ISSUE THREAD

**Issue by dmitry-irtegov** [cri-o/cri-o#6617]
The install instruction suggest that cri-o is present in a standard repositories of OpenSUSE-based systems.
But I did not find it in SUSE Linux Enterprise server 15 SP4, even after I enabled SUSE_Package_Hub_x86_64 service

**Comment by saschagrunert** [comment]
Hey @dmitry-irtegov, thank you for reaching out! Unfortunately we do not maintain the packages for SLES distributions at all. So I assume it would be required to open an issue at the SUSE side.
