### ISSUE TITLE
Runtime service generates unexpected CONTAINER_DELETED_EVENT on container stop

### ISSUE THREAD

**Issue by akornatskyy** [cri-o/cri-o#6625]
### What happened?

Runtime service generates unexpected CONTAINER_DELETED_EVENT on container stop

### What did you expect to happen?

container stop should not generate CONTAINER_DELETED_EVENT.

### How can we reproduce it (as minimally and precisely as possible)?

1. start server
2. client getContainerEvents
3. run pod -> CONTAINER_STARTED_EVENT
4. create container -> CONTAINER_CREATED_EVENT
5. start container -> CONTAINER_STARTED_EVENT
6. stop container -> CONTAINER_STOPPED_EVENT, CONTAINER_DELETED_EVENT
7. rm container -> CONTAINER_DELETED_EVENT

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.26.1
Version:        1.26.1
GitCommit:      69945ab622a70ab01f4b0df10b107bc48e38dc9e
GitCommitDate:  2023-01-10T21:20:34Z
GitTreeState:   dirty
BuildDate:      1980-01-01T00:00:00Z
GoVersion:      go1.19.4
Compiler:       gc
Platform:       linux/amd64
Linkmode:       static
BuildTags:      
  static
  netgo
  osusergo
  exclude_graphdriver_btrfs
  exclude_graphdriver_devicemapper
  seccomp
  apparmor
  selinux
LDFlags:          unknown
SeccompEnabled:   true
AppArmorEnabled:  false
Dependencies:     

```
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
Debian
$ uname -a
6.1
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

-

**Comment by hasan4791** [comment]
Looks like 2 events are being generated, DELETED then STOPPED
https://github.com/cri-o/cri-o/blob/main/server/container_stop.go#L45
https://github.com/cri-o/cri-o/blob/main/server/sandbox_stop_linux.go#L97

**Comment by akornatskyy** [comment]
fantastic... just closed since no one cares.

**Comment by haircommander** [comment]
I'm pretty sure this was closed because https://github.com/cri-o/cri-o/pull/6633 fixed it. did you get a chance to check it out?

**Comment by akornatskyy** [comment]
with the next release, I guess it will come soon.
