### ISSUE TITLE
panic: close of closed channel

### ISSUE THREAD

**Issue by akornatskyy** [cri-o/cri-o#6626]
### What happened?

```
panic: close of closed channel

goroutine 1 [running]:
github.com/cri-o/cri-o/server.(*Server).Shutdown(0xc0008e8000, {0xc000b0f724?, 0xc000866ec0?})
	github.com/cri-o/cri-o/server/server.go:354 +0x1b2
main.main.func2(0xc00014dc40)
	github.com/cri-o/cri-o/cmd/crio/main.go:409 +0x17b2
github.com/urfave/cli/v2.(*Command).Run(0xc000200140, 0xc00014dc40, {0xc0001101f0, 0x1, 0x1})
	github.com/urfave/cli/v2@v2.23.7/command.go:271 +0xa42
github.com/urfave/cli/v2.(*App).RunContext(0xc000560000, {0x297cdf8?, 0xc000124000}, {0xc0001101f0, 0x1, 0x1})
	github.com/urfave/cli/v2@v2.23.7/app.go:333 +0x665
github.com/urfave/cli/v2.(*App).Run(...)
	github.com/urfave/cli/v2@v2.23.7/app.go:310
main.main()
	github.com/cri-o/cri-o/cmd/crio/main.go:446 +0x69a
```

### What did you expect to happen?

no panic

### How can we reproduce it (as minimally and precisely as possible)?

this happen when you `ctrl+c` stop server.

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
1.26.1
```
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
Debian
$ uname -a
6.1
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by hasan4791** [comment]
It looks like the channel is already closed during the signal handling, here
https://github.com/cri-o/cri-o/blob/main/cmd/crio/main.go#L376

And again its is being attempted here
https://github.com/cri-o/cri-o/blob/main/cmd/crio/main.go#L409

**Comment by haircommander** [comment]
thanks for identifying that @hasan4791 I think https://github.com/cri-o/cri-o/pull/6630 is the way to go here

**Comment by haircommander** [comment]
we reverted the original patch here https://github.com/cri-o/cri-o/pull/6651 because it caused ci breakages

**Comment by kwilczynski** [comment]
Was this ever confirmed fixed?
