### ISSUE TITLE
Runtime service does not dispatch first event after client reconnect

### ISSUE THREAD

**Issue by akornatskyy** [cri-o/cri-o#6627]
### What happened?

Runtime service does not dispatch first event after client reconnect

### What did you expect to happen?

after re-connect the first event should be delivered.

### How can we reproduce it (as minimally and precisely as possible)?

1. start server
2. client getContainerEvents
3. run pod -> CONTAINER_STARTED_EVENT
4. client disconnect
5. client connect (getContainerEvents)
6. create container -> no event
7. start container -> CONTAINER_STARTED_EVENT

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
1.26.1
```
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
Debian
$ uname -a
6.1
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by sairameshv** [comment]
I tried reproducing the issue and couldn't observe any event once the client disconnects and connects back as the Evented PLEG in kubelet retries, falls back to Generic PLEG if it exceeds the maximum retries when failed.
Reference: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/pleg/evented.go#L182

@akornatskyy , Could you paste the kubelet log snippets when the client is disconnected, connected back?
That might actually help in debugging this issue further !!
Thanks.

**Comment by akornatskyy** [comment]
I am not using `kubelet`...

**Comment by harche** [comment]
@akornatskyy Evented PLUG is currently in the alpha stage of development and is considered to be a feature-gated product. As such, it is not recommended for use without the kubelet.

**Comment by akornatskyy** [comment]
well, right. I saw it is feature-gated. however, that's still a bug to fix.

**Comment by harche** [comment]
In the current implementation the events are not buffered at the server side. They are meant to be streamed immediately and then discarded. If the event was successfully delivered the first time, the runtime doesn't store it any further.  

While the current implementation might expose the shortcoming explained in this bug, the evented pleg has been designed from k8s point of view. Storing/Caching past events would provided no value in k8s setup.

**Comment by harche** [comment]
In the long run we want to support other clients (such as `crictl`) for evented pleg.

**Comment by akornatskyy** [comment]
this one has no relation to dispatching past events

**Comment by harche** [comment]
Oh sorry, my bad. 

As long as the code at https://github.com/cri-o/cri-o/blob/f226e91c417f51fe24a0a6d141482c3181de7beb/server/container_create.go#L481 and/or https://github.com/cri-o/cri-o/blob/f226e91c417f51fe24a0a6d141482c3181de7beb/server/sandbox_run_linux.go#L955 is hit, you should be able to see `CONTAINER_CREATED_EVENT`. 

It maybe possible that create container/sandbox code is returning that function before the event can be generated.
