### ISSUE TITLE
Tarball install script should install crio.service file into /etc/systemd/system on CoreOS

### ISSUE THREAD

**Issue by plevart** [cri-o/cri-o#6666]
### What happened?

When installing cri-o via tarball on CoreOS which installs it by default into `/usr/local` and subdirectories, the systemd unit file `crio.service` is installed into directory `/usr/local/lib/systemd/system`.
Due to CoreOS issue: https://github.com/coreos/rpm-ostree/issues/1936 this file is not picked up by systemd on boot since `/usr/local` on CoreOS is just a symlink to `/var/usrlocal` and `/var` is mounted after systemd already starts.
The end result is that crio doesn't start after OS reboot.
Perhaps the unit file could be installed into directory `/etc/systemd/system` instead? At least on CoreOS?

### What did you expect to happen?

I expected that enabled crio.service systemd unit is started at boot.

### How can we reproduce it (as minimally and precisely as possible)?

Install crio-o via tarball install script on CoreOS. Reboot OS. See that crio is not started:

```
[root@uniapp ~]# systemctl status crio
○ crio.service - Container Runtime Interface for OCI (CRI-O)
     Loaded: loaded (/usr/local/lib/systemd/system/crio.service; enabled; preset: disabled)
     Active: inactive (dead)
       Docs: https://github.com/cri-o/cri-o
```

### CRI-O and Kubernetes version

crio 1.26.1

### OS version

Fedora CoreOS 37.20230122.3.0

### Additional environment details (AWS, VirtualBox, physical, etc.)

VirtualBox in my situation, but could be anywhere CoreOS is possible to install.

**Comment by hasan4791** [comment]
@plevart Would be great, if you get me the details of /etc/os-release file from core-os. Might save some time

**Comment by plevart** [comment]
```
[core@uniapp ~]$ cat /etc/os-release 
NAME="Fedora Linux"
VERSION="37.20230122.3.0 (CoreOS)"
ID=fedora
VERSION_ID=37
VERSION_CODENAME=""
PLATFORM_ID="platform:f37"
PRETTY_NAME="Fedora CoreOS 37.20230122.3.0"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:37"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=37
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=37
SUPPORT_END=2023-11-14
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='37.20230122.3.0'
```

**Comment by plevart** [comment]
Looks good.
