### ISSUE TITLE
cri-o api equivalent for crictl inspect command

### ISSUE THREAD

**Issue by coolninja1504** [cri-o/cri-o#6667]
Hi All,

I have been exploring the crictl command to fetch the container information.
crictl inspect <container-id> is very useful command , and giving lot of useful information about the container 

sh-4.4# crictl inspect 4546535
I am looking to fetch the same information programmatically using go , just like go_client fetch info using the  kubernetes api .

Can you guys please let me know if there are any go client using with I can fetch data from cri-o apis ? Is there any documentation link that I can check for the same ?

Thanks,
Ashish

**Comment by saschagrunert** [comment]
Hey @coolninja1504 you can use `crio-status` to get container information as well: https://github.com/cri-o/cri-o/blob/main/docs/crio-status.8.md

Would that fit for your use case?

**Comment by coolninja1504** [comment]
Hi @saschagrunert  , thanks a lot for replying.
Actually we don't want to use the crictl or crio-status command , but want to achieve the same through a go application , by invoking the crio apis .

Can you please suggest any go package or crio api  that can help us to do the same ?

**Comment by haircommander** [comment]
you could do something similar as our internal client library https://github.com/cri-o/cri-o/blob/main/internal/client/client.go

Alternatively, we could export this library--it has been fairly stable and I don't expect any of the items to change.
If we did do this, a note is CRI-O doesn't guarantee go API guarantees, so even though the library has been stable, it is possible it will be changed

**Comment by coolninja1504** [comment]
Thanks a lot for replying @haircommander .

"Alternatively, we could export this library" - can you please mention this library name also ?

**Comment by haircommander** [comment]
the one linked: https://github.com/cri-o/cri-o/blob/main/internal/client/client.go

**Comment by coolninja1504** [comment]
Thanks for pointing out to the link  @haircommander ,
I have some more questions . 
Is it possible we can access the cri-o apis from a container running inside the kubernetes cluster ? 
or any way with which we can access the crictl commands from inside the container running  in the cluster ?

**Comment by haircommander** [comment]
I would guess you could if you mounted in `/var/run/crio/crio.sock` and pointed crictl to it. There would likely be some selinux weirdness so the container probably has to be privileged to do so

**Comment by saschagrunert** [comment]
This request seems to be similar to https://github.com/containerd/containerd/issues/8085

**Comment by coolninja1504** [comment]
Thanks a lot @haircommander  for the suggestion . After mounting /var/run/crio/crio.sock in my container , I am able to get the  container information using the container_id, but iyt works only when I am running my container as  privileged . Is there any way I can mount this without the privilege access ?

**Comment by haircommander** [comment]
sorry for the late reply--unfortunately not. accessing the cri-o socket needs to be a privileged operation, as direct access to the socket allows a user to do anything to the node. There's discussion on breaking up read only operations in the CRI and allowing unprivileged access to that, but it's not possible today.
