### ISSUE TITLE
Failing integration test - test_cgroupfs

### ISSUE THREAD

**Issue by n4j** [cri-o/cri-o#6673]
### Which jobs are failing?

test_cgroupfs is failing for branches `release-1.{25, 24, 23}`

### Which tests are failing?

1. test infra ctr cpuset
2. test workload gets configured to defaults
3. test workload can override defaults
4. test workload should not be set if not defaulted or specified
5. test workload pod gets configured to defaults
6. test workload can override pod defaults
7. test workload pod should not be set if not defaulted or specified
8. test workload pod should not be set if annotation not specified
9. test workload pod should override infra_ctr_cpuset option

### Since when has it been failing?

The earliest failure which I could find is from 2/Dec/2022 in PR https://github.com/cri-o/cri-o/pull/6417

### Testgrid link

https://github.com/cri-o/cri-o/actions/runs/4247050539/jobs/7384625332

**Comment by n4j** [comment]
Some more test failure examples
https://github.com/cri-o/cri-o/actions/runs/4244223767/jobs/7378029537
https://github.com/cri-o/cri-o/actions/runs/4165447327/jobs/7228235479

**Comment by n4j** [comment]
@haircommander Need some clarification here, in [test/helpers.bash#L309](https://github.com/cri-o/cri-o/blob/release-1.25/test/helpers.bash#L309) custom config is created which has cgroup manager in the config which is passed via arg `CONTAINER_CGROUP_MANAGER`

However, in `start_crio_no_setup` CRIO_CONFIG is passed which would contain default `cgroup_manager` which is `systemd`.

Is this intentional?

**Comment by haircommander** [comment]
oops, sorry for the delay @n4j . so the `CRIO_CUSTOM_CONFIG` is written to the `CONFIG_DIR` which is passed as the `-d` option in CRI-O. the config is generated (in order of precidence from least to most): defaults in binary, config file, files in config dir (alphanumerically), environment variables and cli flags. so the file in the config dir will overrride the config file

**Comment by kannon92** [comment]
I got this test failreu on my PR actually: https://github.com/cri-o/cri-o/pull/7236

**Comment by haircommander** [comment]
though a different test failed:
[not ok 60 fail to clear podman containers when shutdown file not found but container still running](https://github.com/cri-o/cri-o/actions/runs/5941749429/job/16114287053?pr=7236)
