### ISSUE TITLE
REQUEST: New organization membership for n4j

### ISSUE THREAD

**Issue by n4j** [cri-o/cri-o#6680]
### GitHub Username

n4j

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have one sponsor from the list of approvers in at least one OWNERS file within the CRI-O repository
- [x] I have spoken to my sponsor ahead of this application, and they have agreed to sponsor my application

### Sponsor

@haircommander

### List of contributions to the CRI-O project

Issues
1. https://github.com/cri-o/cri-o/issues/6349
2. https://github.com/cri-o/cri-o/issues/6673

PRs
1. https://github.com/cri-o/cri-o/pull/6641
4. https://github.com/cri-o/cri-o/pull/6640
5. https://github.com/cri-o/cri-o/pull/6636
6. https://github.com/cri-o/cri-o/pull/6638

**Comment by saschagrunert** [comment]
+1 from my side! :+1:

**Comment by haircommander** [comment]
LGTM, thanks for your work so far!

**Comment by haircommander** [comment]
invite sent! welcome to the team
