### ISSUE TITLE
REQUEST: New org member status for arcolife

### ISSUE THREAD

**Issue by arcolife** [cri-o/cri-o#6685]
### GitHub Username

@arcolife

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have one sponsor from the list of approvers in at least one OWNERS file within the CRI-O repository
- [X] I have spoken to my sponsor ahead of this application, and they have agreed to sponsor my application

### Sponsor

@haircommander

### List of contributions to the CRI-O project

- https://github.com/cri-o/cri-o/issues/4622
- https://github.com/cri-o/cri-o/pull/4845
- https://github.com/cri-o/cri-o/pull/4868

**Comment by haircommander** [comment]
Invite sent! welcome :)
