### ISSUE TITLE
Any gui and webui ？

### ISSUE THREAD

**Issue by mmm8955405** [cri-o/cri-o#6700]
### What happened?

Any gui and webui

### What did you expect to happen?

Any gui and webui

### How can we reproduce it (as minimally and precisely as possible)?

Any gui and webui

### Anything else we need to know?

Any gui and webui

### CRI-O and Kubernetes version

Any gui and webui

### OS version

Any gui and webui

### Additional environment details (AWS, VirtualBox, physical, etc.)

Any gui and webui

**Comment by haircommander** [comment]
sorry, it's not clear what you're looking for here

**Comment by haircommander** [comment]
CRI-O can only be interacted with through CLI (it is itself a binary, and the programs that communicate with it do so through unix socket)

**Comment by n4j** [comment]
@mmm8955405 If your query is resolved then can we close this issue?

cri-o can be interacted with via Unix socket via gRPC or via crictl cli, there is no perceived use case for GUI here.

Do you see any use case here?

**Comment by n4j** [comment]
There hasn't been any update from the reporter, closing the issue for now feel free to reopen if needed.

/close
