### ISSUE TITLE
FIPS Compliant crio

### ISSUE THREAD

**Issue by shashipratap** [cri-o/cri-o#6725]
Hi Team ,
I am using OKE and want to verify if my crio is FIPS compliant or not. 
Is there a way I can identify ?
Is there a way to enable it?

**Comment by hasan4791** [comment]
I doubt the binaries are FIPS compliant. What made you look for this?
```
[root@fedora bin]#  go tool nm crio | grep FIPS
reading crio: no symbol section
reading crio: no symbols
[root@fedora bin]#  go tool nm crio | grep -i dlopen_openssl
reading crio: no symbol section
reading crio: no symbols
```

**Comment by hasan4791** [comment]
On Openshift its fips compliant and you can check the binary yourself using the above commands.
For more info
https://developers.redhat.com/articles/2022/05/31/your-go-application-fips-compliant#
https://github.com/cri-o/cri-o/issues/5256

**Comment by haircommander** [comment]
you need a special go compiler to enable FIPs mode in CRI-O: https://github.com/cri-o/cri-o/issues/5256#issuecomment-909756678

**Comment by hasan4791** [comment]
@haircommander are we deliberately not loading the symbols in crio during build time?

**Comment by hasan4791** [comment]
```
[root@chasan-rhel8-testing bin]# go version
go version go1.19.6 linux/amd64
[root@chasan-rhel8-testing bin]# which go
/root/fips/go/go/bin/go
[root@chasan-rhel8-testing bin]# go tool nm /root/fips/go/go/bin/go | grep FIPS
  962e40 T _cgo_5019e8d6299c_Cfunc__goboringcrypto_FIPS_mode
 10ace18 d _g_FIPS_mode
 102f0b0 d crypto/tls.defaultCipherSuitesFIPS
 102f130 d crypto/tls.defaultFIPSCipherSuitesTLS13
 102f150 d crypto/tls.defaultFIPSCurvePreferences
  5d3fe0 t vendor/github.com/golang-fips/openssl-fips/openssl._Cfunc__goboringcrypto_FIPS_mode.abi0
 102e008 d vendor/github.com/golang-fips/openssl-fips/openssl._cgo_5019e8d6299c_Cfunc__goboringcrypto_FIPS_mode
  5deb40 t vendor/github.com/golang-fips/openssl-fips/openssl.enableBoringFIPSMode
 10ad1fc d vendor/github.com/golang-fips/openssl-fips/openssl.strictFIPS
[root@chasan-rhel8-testing bin]# 
[root@chasan-rhel8-testing bin]# go tool nm crio | grep -i dlopen_openssl
reading crio: no symbol section
reading crio: no symbols
[root@chasan-rhel8-testing bin]# 
```

**Comment by haircommander** [comment]
@lsm5 and @mrunalp were the people that did the work getting fips mode together.

**Comment by lsm5** [comment]
If it's a fedora build or something from the kubic repos, it's very likely not fips compliant. 

What does `rpm -q cri-o-$WHATEVER_VERSION` look like on your env ?

**Comment by hasan4791** [comment]
> If it's a fedora build or something from the kubic repos, it's very likely not fips compliant. 
> 
> 
> 
> What does `rpm -q cri-o-$WHATEVER_VERSION` look like on your env ?

I compiled from source using the fips go  1.19.6.

**Comment by lsm5** [comment]
> > If it's a fedora build or something from the kubic repos, it's very likely not fips compliant.
> > What does `rpm -q cri-o-$WHATEVER_VERSION` look like on your env ?
> 
> I compiled from source using the fips go 1.19.6.

where did you fetch this go compiler from? Are you able to build crio using the `libtrust_openssl` buildtag ?

**Comment by hasan4791** [comment]
Initially i tried to build crio using fips go1.18 version on RHEL8 but it failed. So i had to build fips go 1.19 version from this branch
https://github.com/golang-fips/go/tree/go1.19-fips-release

And regarding the buildtag, No i haven't included it. Is there any docs on this? If not, probably i could add, once i understand the complete process.

**Comment by hasan4791** [comment]
Btw, @haircommander how often are we bumping the go version. Reason being is for fips the go version always lacks behind and if we use new go feature in our code it might break when building fips enabled binary.

**Comment by hasan4791** [comment]
> hmm, don't know if any of the RHEL builds have easily accessible public links, but let me provide you a podman example:
> 
> See: https://github.com/containers/podman/blob/main/podman.spec.rpkg#L23
> 
> So, if you have `go build ... bin/crio ...` try: `go build -tags "libtrust_openssl" ... bin/crio ...`

After enabling symbols, i can now see the openssl-fips symbol without adding libtrust_openssp build tag.

```
[root@chasan-rhel8-testing cri-o]# go build -tags "exclude_graphdriver_btrfs btrfs_noversion" -o bin/crio github.com/cri-o/cri-o/cmd/crio
[root@chasan-rhel8-testing cri-o]# cd bin/
[root@chasan-rhel8-testing bin]# go tool nm crio | grep -i dlopen_openssl
 2cb12f0 T _cgo_5019e8d6299c_Cfunc__goboringcrypto_DLOPEN_OPENSSL
 136fa60 t local.vendor/github.com/golang-fips/openssl-fips/openssl._Cfunc__goboringcrypto_DLOPEN_OPENSSL.abi0
 136fa60 T vendor/github.com/golang-fips/openssl-fips/openssl._Cfunc__goboringcrypto_DLOPEN_OPENSSL.abi0
 4b4dcb0 D vendor/github.com/golang-fips/openssl-fips/openssl._cgo_5019e8d6299c_Cfunc__goboringcrypto_DLOPEN_OPENSSL
[root@chasan-rhel8-testing bin]# 
```

**Comment by shashipratap** [comment]
@hasan4791 I need to ensure my entire infra is FIPS compliant thats why I am looking for it.
In my case the nodes are oracle linux , how do I check on them if I have FIPS enabled in crio?

**Comment by hasan4791** [comment]
@shashipratap Though i wait for others to acknowledge, I think crio & other components on OKE must be FIPS compliant. You need to check this file in your node "/proc/sys/crypto/fips_enabled". If its 1, then containers will detect hosts are in FIPS mode and "/proc/sys/crypto/fips_enabled" appears with the host's value in all container PID namespaces.

**Comment by shashipratap** [comment]
@hasan4791 my nodes are not running in FIPS mode , OKE says whatever we run is FIPS compliant and whatever customer runs its their responsibility , OKE nodes are from a custom image not given by OKE but crio we are not doing anything and it is coming from OKE , I just want to verify its FIPS compliant

**Comment by lsm5** [comment]
> ```
> [root@chasan-rhel8-testing cri-o]# go build -tags "exclude_graphdriver_btrfs btrfs_noversion" -o bin/crio github.com/cri-o/cri-o/cmd/crio
> [root@chasan-rhel8-testing cri-o]# cd bin/
> [root@chasan-rhel8-testing bin]# go tool nm crio | grep -i dlopen_openssl
>  2cb12f0 T _cgo_5019e8d6299c_Cfunc__goboringcrypto_DLOPEN_OPENSSL
>  136fa60 t local.vendor/github.com/golang-fips/openssl-fips/openssl._Cfunc__goboringcrypto_DLOPEN_OPENSSL.abi0
>  136fa60 T vendor/github.com/golang-fips/openssl-fips/openssl._Cfunc__goboringcrypto_DLOPEN_OPENSSL.abi0
>  4b4dcb0 D vendor/github.com/golang-fips/openssl-fips/openssl._cgo_5019e8d6299c_Cfunc__goboringcrypto_DLOPEN_OPENSSL
> [root@chasan-rhel8-testing bin]# 
> ```


@hasan4791 can't find any `github.com/golang-fips/openssl-fips` anywhere in my cri-o checkout on main and release-1.26 branches. I do see `github.com/containers/libtrust` though. Anyway, looks like github.com/golang-fips/openssl-fips does define `HashSignECDSA`  which seems to do the same job as `ecdsa.HashSign` in libtrust, available from the rhel go compiler using `libtrust_openssl`.

**Comment by hasan4791** [comment]
@lsm5 Back to @shashipratap query, how to verify that OKE components are FIPS compliant? Seems we aren't loading symbols in our runtimes and in that case what is the alternate way to check?

**Comment by shashipratap** [comment]
@lsm5 pointers would be helpful for user to identify

**Comment by lsm5** [comment]
> @lsm5 pointers would be helpful for user to identify

@haircommander who are the right people to ping for OKE?

**Comment by hasan4791** [comment]
> 

OKE is Oracle Kubernetes Engine. So it must be either vanilla or customized Kubernetes but not Openshift.

**Comment by lsm5** [comment]
> OKE is Oracle Kubernetes Engine. So it must be either vanilla or customized Kubernetes but not Openshift.

Hmm, I'm guessing OKE has its own ways of building cri-o? @shashipratap maybe you'll have better luck reaching out to them instead?
