### ISSUE TITLE
gcloud crashing with invalid start byte

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#6738]
### Which jobs are failing?

ci/prow/ci-cgroupv2-e2e
ci/prow/ci-cgroupv2-e2e-crun
ci/prow/ci-cgroupv2-e2e-features
ci/prow/ci-cgroupv2-integration
ci/prow/ci-crun-e2e
ci/prow/ci-e2e
ci/prow/ci-e2e-conmonrs
ci/prow/ci-fedora-integration
ci/prow/ci-rhel-critest
ci/prow/ci-rhel-e2e

### Which tests are failing?

provisioning

### Since when has it been failing?

last couple of days?

### Testgrid link

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/cri-o_cri-o/6736/pull-ci-cri-o-cri-o-main-ci-cgroupv2-e2e-crun/1636027198131408896

### Reason for failure (if possible)

```
 ERROR: gcloud crashed (UnicodeDecodeError): 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte 
```
related to https://stackoverflow.com/questions/59855169/unicodedecodeerror-utf-8-codec-cant-decode-byte-0x8b-in-position-1-invalid

**Comment by sohankunkerkar** [comment]
I don't think we are hitting this issue anymore. Closing this for now. Feel free to open it if you see this issue again.
