### ISSUE TITLE
fsync() contention when container logs get rotated can block containers writing to stdout/stderr

### ISSUE THREAD

**Issue by rmt** [cri-o/cri-o#6743]
### What happened?

When kubelet rotates logs and asks the remote runtime to reopen logs, a blocking fsync() occurs in conmon.  The pipe buffers can fill in the meantime while waiting for fsync() to complete, blocking writes to stdout/stderr.

conmon has an option called --no-sync-log which can alleviate this problem (and should arguably be the default)
However, podman does not support setting this.
And neither does cri-o, which uses podman.

The required changes should probably be driven by CRI-O.

This will usually not be noticed on a local disk or with low-volume logs, and very intermittently if the max-log-file-size is sufficiently large.  However, we have logs on an AWS EBS (GP3) volume and there is latency involved, and the max log file size was quite low given the amount of logs produced, which made the issue very obvious and got us to dig into it.

I suspect that this is that this is behind a significant number of (usually minor) latency spikes that people see.

### What did you expect to happen?

Writing to stdout from a container should not block under normal circumstances

### How can we reproduce it (as minimally and precisely as possible)?

Do lots writes and fsync()s on the container log volume while producing lots logs in a tight loop from one or more k8s containers, and set the max-log-file-size lower.   During log rotation / when the pipe is blocked, fewer log lines will be produced.  In a real world scenario, this might be HTTP requests that are delayed.

### Anything else we need to know?

Calling fsync on the critical path when writing log files is probably a bad thing

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.23.5
Version:          1.23.5
GitCommit:        d12c2842e9e4d051a2496e1740f846ffa22b3f1d
GitTreeState:     clean
BuildDate:        2023-01-10T21:30:25Z
GoVersion:        go1.17.5
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        exclude_graphdriver_devicemapper, seccomp
SeccompEnabled:   true
AppArmorEnabled:  false
```

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14", GitCommit:"3321ffc07d2f046afdf613796f9032f4460de093", GitTreeState:"clean", BuildDate:"2022-11-09T13:40:19Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14", GitCommit:"3321ffc07d2f046afdf613796f9032f4460de093", GitTreeState:"clean", BuildDate:"2022-11-09T13:32:47Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/arm64"}
```
</details>

### OS version

<details>

```console
$ cat /etc/os-release 
NAME="Rocky Linux"
VERSION="8.7 (Green Obsidian)"

$ uname -a
Linux ip-10-118-82-234.ec2.internal 4.18.0-425.10.1.el8_7.x86_64 #1 SMP Thu Jan 12 16:32:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
AWS GP3 with shared volume group for /var/log/pods and /var/log/containers, which doesn't do anything good for I/O contention or consistency, of course.
</details>

**Comment by rmt** [comment]
Ping?  I can also open bugs against the podman and/or conmon projects, if that is desired.

**Comment by haircommander** [comment]
sorry for the delay @rmt! I think having an option in cri-o to not sync the log makes sense to me. I don't think we can make it the default because I would expect admins to assume their logs will persist and sudden reboots would cause changes to be lost without the fsyncs. That said, I definitely think it could be a configurable option.

long term, a better way to handle this is a double buffer like in https://github.com/containers/conmon/issues/38, though at this point that's more likely to happen in conmon-rs.

@arcolife do you have any interest in taking this on?

**Comment by arcolife** [comment]
thanks @haircommander I'll pick this up very soon. Let me assign myself for now.

**Comment by haircommander** [comment]
I see your point, and I agree! I think long term we can consider having fsync off by default. I think it should begin configurable, and start off as on by default to allow us to try it out and make sure there are no regressions. If we find it's better, we can move it to the default.

does anyone have any interest in taking this on?

**Comment by rmt** [comment]
I'd honestly put up a PR to disable fsync on log rotation completely with a clear explanation as to why, and see if anyone argues otherwise.

I suspect that this fsync-on-rotate was for an imaginary use-case - the implementer probably thought it made sense, but it doesn't.

Important logs are, in almost all cases, shipped off to dedicated log storage systems and the current fsync-on-rotate behaviour can get in the way of that by introducing delays to writing logs, plus of course in the extreme scenario of blocking container's stdout/stderr and further impacting filesystem performance.

**Comment by arcolife** [comment]
I'll start by introducing the flag, a few tests and we can have a discussion about its permanency thereafter. 

Thanks for the pointers so far and please continue to link any relevant issues/discussions here until then.

**Comment by saschagrunert** [comment]
Is this still in progress?

**Comment by arcolife** [comment]
just haven't found the time yet. I'll make time this weekend.

**Comment by rmt** [comment]
I would recommend keeping this open until fixed.  It is definitely a performance bottleneck for many workloads, even if it's unlikely to be noticed / pinpointed as a problem by most engineers.

**Comment by rtreffer** [comment]
I did an initial attempt with the most simplistic approach I could think of (passthrough of a `no_sync_log` option).
Happy to change everything about it :shrug:

**Comment by rtreffer** [comment]
So... I tried to _test_ how bad this is.
Setup:
* RPI 4 with cooling fan
* ubuntu noble (server preinstalled image) on sdcard (cheap 128GB A1)
* [Custom CRI-O 1.31](https://github.com/rtreffer/cri-o/tree/release-1.31%2Bfsync)
* [kubelet from kubernetes 1.31 beta](https://github.com/kubernetes/kubernetes/releases/tag/v1.31.0-beta.0) in standalone mode
* [go application to test stdout write latency](https://github.com/rtreffer/experiments/blob/main/stdoutlat/cmd/main.go)
* some [systemd unit files and pod config](https://github.com/rtreffer/experiments/tree/main/stdoutlat/os)

I reran each test twice, testing at 10Hz, checking the latest 10k samples each time.

The setup consists of a single pod with 5 sidecars, each one terminating after 1..5 seconds and getting restarted every 5 minutes.

Results with fsync:
```
run #1
tick 12619
latency report: min=25.87µs p50=47.444µs p90=171.016µs p99=495.715µs p999=3.343946ms max=6.381066ms avg=91.012µs stddev=206.123µs
  16.384µs -> 32.767µs  (     82) |                              |
  32.768µs -> 65.535µs  (   7590) |******************************|
  65.536µs -> 131.071µs (   1274) |*****                         |
 131.072µs -> 262.143µs (    262) |*                             |
 262.144µs -> 524.287µs (    745) |***                           |
 524.288µs -> 1.049ms   (     30) |                              |
   1.049ms -> 2.097ms   (      1) |                              |
   2.097ms -> 4.194ms   (      8) |                              |
   4.194ms -> 8.389ms   (      8) |                              |

run #2
tick 11417
latency report: min=26.703µs p50=44.666µs p90=144.258µs p99=496.273µs p999=5.38353ms max=6.491502ms avg=95.75µs stddev=264.761µs
  16.384µs -> 32.767µs  (    417) |**                            |
  32.768µs -> 65.535µs  (   7246) |******************************|
  65.536µs -> 131.071µs (   1294) |*****                         |
 131.072µs -> 262.143µs (    188) |*                             |
 262.144µs -> 524.287µs (    795) |***                           |
 524.288µs -> 1.049ms   (     30) |                              |
   1.049ms -> 2.097ms   (      5) |                              |
   2.097ms -> 4.194ms   (      6) |                              |
   4.194ms -> 8.389ms   (     19) |                              |
```

Results without fsync:
```
run #1
tick 11417
latency report: min=19.74µs p50=44.851µs p90=78.017µs p99=488.466µs p999=780.896µs max=6.699377ms avg=72.026µs stddev=165.476µs
  16.384µs -> 32.767µs  (    146) |*                             |
  32.768µs -> 65.535µs  (   8354) |******************************|
  65.536µs -> 131.071µs (    871) |***                           |
 131.072µs -> 262.143µs (    184) |*                             |
 262.144µs -> 524.287µs (    419) |**                            |
 524.288µs -> 1.049ms   (     18) |                              |
   1.049ms -> 2.097ms   (      0) |                              |
   2.097ms -> 4.194ms   (      3) |                              |
   4.194ms -> 8.389ms   (      5) |                              |

run #2
tick 12018
latency report: min=26.018µs p50=41.962µs p90=75.387µs p99=455.321µs p999=5.123658ms max=6.176593ms avg=70.513µs stddev=209.685µs
  16.384µs -> 32.767µs  (    488) |**                            |
  32.768µs -> 65.535µs  (   8249) |******************************|
  65.536µs -> 131.071µs (    733) |***                           |
 131.072µs -> 262.143µs (     90) |                              |
 262.144µs -> 524.287µs (    408) |*                             |
 524.288µs -> 1.049ms   (     16) |                              |
   1.049ms -> 2.097ms   (      1) |                              |
   2.097ms -> 4.194ms   (      4) |                              |
   4.194ms -> 8.389ms   (     11) |                              |
```

I am mostly concerned about tail latencies and there is a clear improvement. However I think I need to be more aggressive on sampling and number of samples to get stable results (e.g. 25k samples, 25Hz, 10 sidecars, higher delays for the sidecars).

RPIs are notorious for slow IO, however this RPI was doing nothing more than this logging.
I have high confidence that I will find similar issues on busy/large AWS machines backed by EBS (known for sporadic latency spikes), especially if it overlaps with high IO load (read: pulling images).

**Comment by rtreffer** [comment]
My last comment was scewed by the cpufreq govenor, switching to performance and retrying.

**Comment by rtreffer** [comment]
Ok, after going to the performance scheduler the deltas are small but still somewhat noticable

**with fsync**
```
run #1
tick 51105
latency report (50000 entries): min=8.223µs p50=12.778µs p90=37.203µs p99=178.256µs p999=323.995µs max=15.764414ms avg=21.659µs stddev=80.111µs
   8.192µs -> 16.383µs  (  37194) |******************************|
  16.384µs -> 32.767µs  (   6782) |*****                         |
  32.768µs -> 65.535µs  (   4342) |****                          |
  65.536µs -> 131.071µs (    204) |                              |
 131.072µs -> 262.143µs (   1349) |*                             |
 262.144µs -> 524.287µs (    111) |                              |
 524.288µs -> 1.049ms   (     12) |                              |
   1.049ms -> 2.097ms   (      4) |                              |
   2.097ms -> 4.194ms   (      1) |                              |
   4.194ms -> 8.389ms   (      0) |                              |
   8.389ms -> 16.777ms  (      1) |                              |

run #2
tick 51106
latency report (50000 entries): min=8.426µs p50=11.982µs p90=31.407µs p99=170.405µs p999=279.663µs max=853.062µs avg=19.049µs stddev=27.784µs
   8.192µs -> 16.383µs  (  40043) |******************************|
  16.384µs -> 32.767µs  (   5133) |****                          |
  32.768µs -> 65.535µs  (   3411) |***                           |
  65.536µs -> 131.071µs (    148) |                              |
 131.072µs -> 262.143µs (   1197) |*                             |
 262.144µs -> 524.287µs (     59) |                              |
 524.288µs -> 1.049ms   (      9) |                              |

run #3
tick 51104
latency report (50000 entries): min=8.092µs p50=11.722µs p90=31.722µs p99=173.461µs p999=292.31µs max=1.166835ms avg=19.138µs stddev=28.64µs
   4.096µs -> 8.191µs   (      2) |                              |
   8.192µs -> 16.383µs  (  40218) |******************************|
  16.384µs -> 32.767µs  (   4933) |****                          |
  32.768µs -> 65.535µs  (   3376) |***                           |
  65.536µs -> 131.071µs (    187) |                              |
 131.072µs -> 262.143µs (   1207) |*                             |
 262.144µs -> 524.287µs (     70) |                              |
 524.288µs -> 1.049ms   (      6) |                              |
   1.049ms -> 2.097ms   (      1) |                              |
```

**without fsync**

```
run #1
tick 55115
latency report (50000 entries): min=8.334µs p50=11.648µs p90=29.351µs p99=168.276µs p999=270.719µs max=1.174242ms avg=18.709µs stddev=28.161µs
   8.192µs -> 16.383µs  (  41707) |******************************|
  16.384µs -> 32.767µs  (   3689) |***                           |
  32.768µs -> 65.535µs  (   3080) |**                            |
  65.536µs -> 131.071µs (    141) |                              |
 131.072µs -> 262.143µs (   1326) |*                             |
 262.144µs -> 524.287µs (     49) |                              |
 524.288µs -> 1.049ms   (      7) |                              |
   1.049ms -> 2.097ms   (      1) |                              |

run #2
tick 53109
latency report (50000 entries): min=8.26µs p50=11.87µs p90=30.685µs p99=168.813µs p999=285.144µs max=853.154µs avg=19.112µs stddev=28.11µs
   8.192µs -> 16.383µs  (  40596) |******************************|
  16.384µs -> 32.767µs  (   4707) |***                           |
  32.768µs -> 65.535µs  (   3188) |**                            |
  65.536µs -> 131.071µs (    180) |                              |
 131.072µs -> 262.143µs (   1221) |*                             |
 262.144µs -> 524.287µs (    104) |                              |
 524.288µs -> 1.049ms   (      4) |                              |

run #3
tick 51106
latency report (50000 entries): min=9.055µs p50=11.888µs p90=30.092µs p99=170.756µs p999=292.533µs max=772.303µs avg=19.102µs stddev=28.516µs
   8.192µs -> 16.383µs  (  40876) |******************************|
  16.384µs -> 32.767µs  (   4512) |***                           |
  32.768µs -> 65.535µs  (   3089) |**                            |
  65.536µs -> 131.071µs (    154) |                              |
 131.072µs -> 262.143µs (   1298) |*                             |
 262.144µs -> 524.287µs (     62) |                              |
 524.288µs -> 1.049ms   (      9) |                              |
```

And how does **containerd** look? Worse than both cri-o versions

```
run #1 (image pull)
tick 51107
latency report (50000 entries): min=10.185µs p50=17.537µs p90=38.777µs p99=178.498µs p999=287.959µs max=30.203323ms avg=25.389µs stddev=137.87µs
   8.192µs -> 16.383µs  (  20392) |******************************|
  16.384µs -> 32.767µs  (  20000) |***************************** |
  32.768µs -> 65.535µs  (   8486) |************                  |
  65.536µs -> 131.071µs (    173) |                              |
 131.072µs -> 262.143µs (    893) |*                             |
 262.144µs -> 524.287µs (     44) |                              |
 524.288µs -> 1.049ms   (      9) |                              |
   1.049ms -> 2.097ms   (      2) |                              |
   2.097ms -> 4.194ms   (      0) |                              |
   4.194ms -> 8.389ms   (      0) |                              |
   8.389ms -> 16.777ms  (      0) |                              |
  16.777ms -> 33.554ms  (      1) |                              |

run #2
tick 51105
latency report (50000 entries): min=10.371µs p50=16.073µs p90=37.981µs p99=175.793µs p999=261.052µs max=2.124453ms avg=22.995µs stddev=27.354µs
   8.192µs -> 16.383µs  (  26335) |******************************|
  16.384µs -> 32.767µs  (  15262) |*****************             |
  32.768µs -> 65.535µs  (   7408) |********                      |
  65.536µs -> 131.071µs (    173) |                              |
 131.072µs -> 262.143µs (    773) |*                             |
 262.144µs -> 524.287µs (     40) |                              |
 524.288µs -> 1.049ms   (      7) |                              |
   1.049ms -> 2.097ms   (      1) |                              |
   2.097ms -> 4.194ms   (      1) |                              |
```

**Comment by rtreffer** [comment]
Ok, after spending to much of a Sunday with this :laughing: ....
* Adding background IO didn't do much except leveling the field a bit :thinking: 
* Going up in log volume seems to remove noise
* Disabling the fsync results in a faster and more stable logging path

So here are some numbers from high logging rates (still not a high volume as long lines are short)
```
fsync
 500 lines/s: p50=9.482µs p99=59.925µs avg=14.244µs stddev=20.535µs
1000 lines/s: p50=9.407µs p99=58.074µs avg=13.53µs  stddev=20.074µs
2000 lines/s: p50=9.407µs p99=42.555µs avg=10.971µs stddev=12.189µs
5000 lines/s: p50=9.315µs p99=47.295µs avg=11.718µs stddev=19.822µs
no fsync
 500 lines/s: p50=9.518µs p99=50.296µs avg=13.099µs stddev=136.836µs (one 30ms outlier)
1000 lines/s: p50=9.314µs p99=44.222µs avg=11.214µs stddev=15.826µs
2000 lines/s: p50=9.37µs  p99=38.333µs avg=10.494µs stddev=10.068µs
5000 lines/s: p50=9.296µs p99=40.407µs avg=10.517µs stddev=12.954µs
```
**Overall a ~10% improvement.** I would like to see this in production.

There is a bug in my measurement as a stall can cause missed ticks which will skew the metrics (writing 1000 lines/s with a >1ms spike can hide a second write getting paused). This makes the effect of tail latency less visible, the measurements are thus still a valid lower bound.

I haven't seen (or at least not reproduced) the IO stall. I have seen it for a different reason in production though.

I will stop my attempts to reproduce this for now, I think there is enough material in here for now, let me know if you would like to see something specific. It should be reproducible for others though.
I also hope this was somewhat informative/entertaining or at least helpful. It was at least a fun weekend for me :smile:

**Comment by haircommander** [comment]
I do think it's worthy of being wary of removing fsyncs. We hit corruptions in the past because we dropped the fsyncs. I can't remember the details but it did cause us to revert that change. I am open to the cri-o change to allow the option in conmon, but I do think we should warn the user with a log saying what they're opting into (so as to maybe avoid issues if something goes wrong)

**Comment by rtreffer** [comment]
I think I am aligned with being wary about it, I put into one of the comment for the option
```
This can improve performance but may result in data loss on hard system crashes.
```

I will make sure that this is consistent across the different ways to set it and add logging. Especially under hard crashes it might make it impossible to debug the cause with disabled fsync.
