### ISSUE TITLE
e2e and integration tests are failing

### ISSUE THREAD

**Issue by sohankunkerkar** [cri-o/cri-o#6751]
### Which jobs are failing?

e2e-{aws,gcp}-ovn
{fedora,cgroupv2}-integration
{cgroupv2,rhel,crun,conmonrs}-e2e

### Which tests are failing?

one of the [upstream sig-network tests](https://github.com/kubernetes/kubernetes/pull/116232) is failing for all e2e jobs and the following bats tests are failing for {fedora,cgroupv2}-integration:
```
not ok 169 setup_file failed
# (from function `setup_file' in test file ./irqbalance.bats, line 16)
#   `if ! command -v irqbalance > /dev/null; then' failed with status 0
ok 174 metrics with default port # skip Metrics port 9090 not listening
ok 175 metrics with random port
ok 176 metrics with operations quantile
ok 177 secure metrics with random port
ok 178 secure metrics with random port and missing cert/key
not ok 179 metrics container oom
# (in test file ./metrics.bats, line 117)
#   `METRIC=$(curl -sf "http://localhost/:$PORT/metrics" | grep '^container_runtime_crio_containers_oom_total')' failed
```

### Since when has it been failing?

Since two weeks

### Testgrid link

e2e failure: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/cri-o_cri-o/6750/pull-ci-cri-o-cri-o-main-ci-cgroupv2-e2e/1638178250037399552

integration tests failure: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/cri-o_cri-o/6750/pull-ci-cri-o-cri-o-main-ci-cgroupv2-integration/1638178252549787648

### Reason for failure (if possible)

All e2e jobs failed due to https://github.com/kubernetes/kubernetes/pull/116232 and the integration tests failure is still unknown, it needs more digging.

**Comment by sohankunkerkar** [comment]
I don't think the failure for `e2e-{aws-gcp}-ovn` is related to cri-o
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/cri-o_cri-o/6752/pull-ci-cri-o-cri-o-main-e2e-gcp-ovn/1638313267560452096

**Comment by sohankunkerkar** [comment]
[This](https://github.com/cri-o/cri-o/pull/6777) PR fixed the integration tests failure

**Comment by saschagrunert** [comment]
Closing this, feel free to reopen or creating a new issue if required.
