### ISSUE TITLE
File contrib/cni/99-loopback.conflist doesn't have name attribute inside release v1.26.2

### ISSUE THREAD

**Issue by andrejusc** [cri-o/cri-o#6760]
### What happened?

For recent v1.26.2 release and this file in it:
https://github.com/cri-o/cri-o/blob/v1.26.2/contrib/cni/99-loopback.conflist
content is such:
````
{
    "cniVersion": "1.0.0",
    "type": "loopback"
}
````
while such release has dependency  on CNI plugins v1.1.1 here:
https://github.com/cri-o/cri-o/blob/v1.26.2/dependencies.yaml#L30
````
  - name: cni-plugins
    version: v1.1.1
````

and that plugin's version then uses types of v1.0.1 here:
https://github.com/containernetworking/plugins/blob/v1.1.1/go.mod#L9
````
github.com/containernetworking/cni v1.0.1
````

and to my understanding it should be aligned to NetConfList type (based on 99-loopback.conflist extension) of v1.0.1 from here:
https://github.com/containernetworking/cni/blob/v1.0.1/pkg/types/types.go#L77

where it has such:
````
Name         string     `json:"name,omitempty"`
````

### What did you expect to happen?

Expect to see `name ` attribute inside 99-loopback.conflist file (could see so far that in main for CNI plugins v1.2.0 case).

### How can we reproduce it (as minimally and precisely as possible)?

Try see involved NetConfList definition

### CRI-O and Kubernetes version

cri-o: v1.26.2

### OS version

N/A

### Additional environment details (AWS, VirtualBox, physical, etc.)

N/A

**Comment by saschagrunert** [comment]
Hm, we probably can pick the CNI plugins update into the release branch. :thinking:

**Comment by andrejusc** [comment]
Sure, if that pick up doesn't break anything - would be awesome. What is potential ETA for next 1.26.x release?

**Comment by saschagrunert** [comment]
@haircommander are we happy with another v1.26.3 this/next week?

**Comment by haircommander** [comment]
+1 from me

**Comment by andrejusc** [comment]
@saschagrunert - thank you for quick turnaround with new release 1.26.3, appreciated. I suppose this now could be closed

**Comment by saschagrunert** [comment]
Yep, fixed with https://github.com/cri-o/cri-o/releases/tag/v1.26.3
