### ISSUE TITLE
cosign signature check does not pin issuer/identity in signature

### ISSUE THREAD

**Issue by nicholasdille** [cri-o/cri-o#6781]
The release notes for v1.26.3 explain how to check the cosign keyless signature for CRI-O. But the description does not specify an issuer or identity. Instead any value is accepted.

This opens the attack vector that a malicious file with a valid signature passes the check when executing the command from the release notes.

The command needs to be improved:

```bash
> export COSIGN_EXPERIMENTAL=1
> cosign verify-blob cri-o.amd64.v1.26.3.tar.gz \
    --certificate-identity-regexp 'https://github.com/cri-o/cri-o/.github/workflows/test.yml@refs/tags/v.*' \
    --certificate-oidc-issuer https://token.actions.githubusercontent.com \
    --signature cri-o.amd64.v1.26.3.tar.gz.sig \
    --certificate cri-o.amd64.v1.26.3.tar.gz.cert
```

**Comment by haircommander** [comment]
thanks for reporting the issue @nicholasdille do you have any interest in  submitting a fix?

**Comment by nicholasdille** [comment]
I'll give it a try 😁
