### ISSUE TITLE
 Issue with cri-o being inactive since system reboot and change in ImageContentSourcePolicy in OpenShift

### ISSUE THREAD

**Issue by bmanoj27** [cri-o/cri-o#6783]
### What happened?

I am using CRI-O in an  OpenShift 4.8 Air-Gapper Cluster, right after I have changed the imageContentSourcePolicy from an old local registry to a new local registry which led to the nodes restart,
After the restart the CRI-O has been in inactive state.

Tried rebooting the system but still didn't work and also unable to clear the storage.

rm -rf /var/lib/containers/*
rm: cannot remove '/var/lib/containers/storage/overlay': Device or resource busy

[root@worker01 core]# systemctl status crio
● crio.service - Open Container Initiative Daemon
   Loaded: loaded (/usr/lib/systemd/system/crio.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/crio.service.d
           └─10-mco-default-madv.conf, 10-mco-profile-unix-socket.conf, 20-nodenet.conf
   Active: inactive (dead)
     Docs: https://github.com/cri-o/cri-o

### What did you expect to happen?

The expected thing to happen is to CRI-O starting normally and the 
/etc/containers/registries.conf mirror configs to be changed to new registry.

### How can we reproduce it (as minimally and precisely as possible)?

The current issue can be reproduced in an Air-Gap OpenShift Cluster which used an existing mirror registry and then changing the mirror config to a new registry by using a imagecontentsourcepolicy which will restart the nodes.

### Anything else we need to know?

I have attached the  'sudo journalctl -u crio' logs here.
[crio-status-cut.txt](https://github.com/cri-o/cri-o/files/11132484/crio-status-cut.txt)

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.21.8-10.rhaos4.8.git6fe8786.el8
Version:    1.21.8-10.rhaos4.8.git6fe8786.el8
GoVersion:  go1.16.12
Compiler:   gc
Platform:   linux/amd64
Linkmode:   dynamic

```

```console
$ kubectl --version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"61f31e904c2ad33d390e068e84dd83fd840177c6", GitTreeState:"clean", BuildDate:"2022-12-07T13:11:43Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux CoreOS"
VERSION="48.84.202212211644-0"
ID="rhcos"
ID_LIKE="rhel fedora"
VERSION_ID="4.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 48.84.202212211644-0 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::coreos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://docs.openshift.com/container-platform/4.8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.8"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.8"
OPENSHIFT_VERSION="4.8"
RHEL_VERSION="8.4"
OSTREE_VERSION='48.84.202212211644-0'
$ uname -a
Linux worker01 4.18.0-305.72.1.el8_4.x86_64 #1 SMP Thu Nov 17 09:15:11 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
The Machine is hosted in VMWare ESXI
</details>

**Comment by haircommander** [comment]
I'm afraid this isn't the right channel for Openshift issues (unless the issue was found using OKD). Can you report an issue through your Red Hat account please?
