### ISSUE TITLE
Add option for setting memory.oom.group in CRIO

### ISSUE THREAD

**Issue by jlpedrosa** [cri-o/cri-o#6787]
Kernel in cgroups v2 has an option memory.oom.group which would make all the pids of a given container to get killed on OOM
```
+  memory.oom.group
+	A read-write single value file which exists on non-root
+	cgroups.  The default value is "0".
+
+	Determines whether the cgroup should be treated as a single
+	unit by the OOM killer. If set, the cgroup and its descendants
+	are killed together or not at all. This can be used to avoid
+	partial kills to guarantee workload integrity.
+
+	Tasks with the OOM protection (oom_score_adj set to -1000)
+	are treated as an exception and are never killed.
+
+	If the OOM killer is invoked in a cgroup, it's not going
+	to kill any tasks outside of this cgroup, regardless
+	memory.oom.group values of ancestor cgroups.
```
This can be beneficial for some workloads in where the container creates/forks multiple processes, and partial failures/OOMs causes noise as the heath probes would still succeed. 

Allowing per installation setting that allows to set this croup setting would help by killing all the PIDs in the cgroup.
Discussions: 
Slack CRIO https://kubernetes.slack.com/archives/CAZH62UR1/p1679578876963139
Slac sig-node: https://kubernetes.slack.com/archives/C0BP8PW9G/p1679649131585659

@haircommander Requested me to create this issue.

**Comment by hasan4791** [comment]
@haircommander We've got a comment on this issue in Kubernetes's issue which seems like user needs to handle the process lifecycle in their application. What would be our take here?

**Comment by haircommander** [comment]
I think having the option to have the kernel handle it correctly is a good one. It is sounding like this will make its way into kubelet instead of happening in cri-o, possibly as some sort of pod spec option so it can be disabled for the handful of applications that handle it right

**Comment by sohankunkerkar** [comment]
related to https://github.com/kubernetes/kubernetes/issues/117070

**Comment by sohankunkerkar** [comment]
Alright, this has been added to the kubelet codebase itself: https://github.com/kubernetes/kubernetes/pull/117793
