### ISSUE TITLE
file crio.conf packaged by tar.gz file need be improved

### ISSUE THREAD

**Issue by wongcai** [cri-o/cri-o#6800]
### What happened?

\# Maximum grpc send message size in bytes. If not set or <=0, then CRI-O will default to 16 * 1024 * 1024.
\# grpc_max_send_msg_size = 83886080

\# Maximum grpc receive message size. If not set or <= 0, then CRI-O will default to 16 * 1024 * 1024.
\# grpc_max_recv_msg_size = 83886080

comments in the crio.conf, which distributed by released tar.gz file ,should be updated

### What did you expect to happen?

 "16 * 1024 * 1024" should be "80 * 1024 * 1024"

### How can we reproduce it (as minimally and precisely as possible)?

 leave a **crio.conf** sample file in the git ,eg **crictl.yaml** ,and then keep update when need

### Anything else we need to know?

older version tar.gz file impacted

### CRI-O and Kubernetes version

NA

### OS version

NA

### Additional environment details (AWS, VirtualBox, physical, etc.)

NA

**Comment by haircommander** [comment]
great catch! would you care to open a PR to update?

**Comment by wongcai** [comment]
您好，邮件已收到，我会尽快给您回复。
-------purple grape

**Comment by wongcai** [comment]
it seems problem about packaging engineering. 
I am not sure whether the PR will fix it

**Comment by haircommander** [comment]
that PR should fix the problem, when it merges and we release a new version, it will be included in the package :)

**Comment by sohankunkerkar** [comment]
@haircommander can we close this issue as we already have the latest version?

**Comment by haircommander** [comment]
yeah this is fixed in 1.27.0
