### ISSUE TITLE
Binary from 1.26.3 archive reports version as 1.26.0

### ISSUE THREAD

**Issue by andrejusc** [cri-o/cri-o#6802]
### What happened?

Downloaded such 1.26.3 archive from release area https://github.com/cri-o/cri-o/releases/tag/v1.26.3:
https://storage.googleapis.com/cri-o/artifacts/cri-o.amd64.v1.26.3.tar.gz

Unpacked it and invoked version check for crio binary:
```
$ cri-o/bin/crio --version
crio version 1.26.0
Version:        1.26.0
GitCommit:      a22a6a49215c0bb1e14830317903f15aa93a7bd4
GitCommitDate:  2023-03-29T18:59:47Z
GitTreeState:   dirty
BuildDate:      1980-01-01T00:00:00Z
GoVersion:      go1.19.4
Compiler:       gc
Platform:       linux/amd64
Linkmode:       static
BuildTags:      
  static
  netgo
  osusergo
  exclude_graphdriver_btrfs
  exclude_graphdriver_devicemapper
  seccomp
  apparmor
  selinux
LDFlags:          unknown
SeccompEnabled:   true
AppArmorEnabled:  false
Dependencies:     
````

### What did you expect to happen?

I would expect it to report 1.26.3 as version

### How can we reproduce it (as minimally and precisely as possible)?

See above

### CRI-O and Kubernetes version

See above

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
Linux virtualbox 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by haircommander** [comment]
oops! thanks for opening the issue. It seems the tag for 1.26.3 was incorrectly set. I am working on fixing it now

**Comment by olleman42** [comment]
@haircommander You're probaby aware, but it appears that the deb packages on the 1.26 are missing now instead (this appears to be true for all debian-flavored dists).
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.26/xUbuntu_22.04/

Thanks!

**Comment by haircommander** [comment]
oops thanks for the warning I messed up the reversion, it should be on its way back to 1.26.2 now

**Comment by andrejusc** [comment]
@haircommander - I was particularly interested in 1.26.3 due to my previously raised another issue in this repo: https://github.com/cri-o/cri-o/issues/6760, which was addressed and was supposedly targeted into 1.26.3 inclusion.

So hopefully we could still fix that reported incorrect versioning aspect and re-release then 1.26.3 or whatever it takes.

**Comment by haircommander** [comment]
yeah we're working on releasing 1.26.3 properly here https://github.com/cri-o/cri-o/pull/6803#

**Comment by haircommander** [comment]
https://github.com/cri-o/cri-o/releases/tag/v1.26.3 has the correct binaries, though the artifacts directory hasn't seemed to catch up. @saschagrunert are you able to manually upload the artifacts from the release there during your day tomorrow?

**Comment by andrejusc** [comment]
Closing this as reported issue is resolved now and both downloads:
https://storage.googleapis.com/cri-o/artifacts/cri-o.amd64.v1.26.3.tar.gz
https://github.com/cri-o/cri-o/releases/download/v1.26.3/cri-o.amd64.v1.26.3.tar.gz

when untarred now report correct version 1.26.3:
```
$ cri-o/bin/crio --version
crio version 1.26.3
Version:        1.26.3
GitCommit:      afec31f8173b63dd189911deff7dcef5d01621f8
GitCommitDate:  2023-04-10T17:47:33Z
GitTreeState:   dirty
BuildDate:      1980-01-01T00:00:00Z
GoVersion:      go1.19.4
Compiler:       gc
Platform:       linux/amd64
Linkmode:       static
BuildTags:      
  static
  netgo
  osusergo
  exclude_graphdriver_btrfs
  exclude_graphdriver_devicemapper
  seccomp
  apparmor
  selinux
LDFlags:          unknown
SeccompEnabled:   true
AppArmorEnabled:  false
Dependencies:     
``` 

Thank you for quick turnaround here.
