### ISSUE TITLE
cri-o 1.25.3 packages missing for centos7 x86_64

### ISSUE THREAD

**Issue by grunlab** [cri-o/cri-o#6811]
cri-o 1.25.3 packages are currently missing for centos7 x86_64:
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25:/1.25.3/CentOS_7/x86_64/

cri-o 1.25.3 build failed for centos7 x86_64:
https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable:cri-o:1.25/cri-o
https://build.opensuse.org/package/live_build_log/devel:kubic:libcontainers:stable:cri-o:1.25/cri-o/CentOS_7/x86_64

Thank you

**Comment by sohankunkerkar** [comment]
@haircommander any idea about this one?

**Comment by sohankunkerkar** [comment]
It looks like the cri-o package is back in centos7 and the build looks green as well. I'm closing this issue for now.
