### ISSUE TITLE
Trouble installing cri-o and podman on Ubuntu 22.04

### ISSUE THREAD

**Issue by spowelljr** [cri-o/cri-o#6814]
Seeing if anyone has experienced this and knows how to resolve it.

I'm trying to update the base image of our kicbase image on minikube from Ubuntu 20.04 to 22.04. With Ubuntu 22.04, `podman` is now installed via the default Ubuntu repos, it includes the dependencies `golang-github-containers-image` and`golang-github-containers-common`. `cri-o` is still installed via the `opensuse.org` repo, it includes the dependencies `containers-image` and `containers-common`. This results in a conflict because `golang-github-containers-common` and `containers-common` both try to modify `/etc/containers/policy.json` and `golang-github-containers-image` and `containers-image` both try to modify `/etc/containers/registries.conf`, resulting in the inability to apt install them both.

Sorry if there's a simple or known fix for this I overlooked.

```
09:11:08 #123 6.848 Preparing to unpack .../golang-github-containers-image_5.16.0-3_all.deb ...
09:11:08 #123 6.851 Unpacking golang-github-containers-image (5.16.0-3) ...
09:11:08 #123 6.854 dpkg: error processing archive /var/cache/apt/archives/golang-github-containers-image_5.16.0-3_all.deb (--unpack):
09:11:08 #123 6.854  trying to overwrite '/etc/containers/registries.conf', which is also in package containers-common 100:1-22
09:11:08 #123 6.874 Selecting previously unselected package golang-github-containers-common.
09:11:08 #123 6.877 Preparing to unpack .../golang-github-containers-common_0.44.4+ds1-1_all.deb ...
09:11:08 #123 6.882 Unpacking golang-github-containers-common (0.44.4+ds1-1) ...
09:11:08 #123 6.885 dpkg: error processing archive /var/cache/apt/archives/golang-github-containers-common_0.44.4+ds1-1_all.deb (--unpack):
09:11:08 #123 6.885  trying to overwrite '/etc/containers/policy.json', which is also in package containers-common 100:1-22
09:11:08 #123 6.913 Selecting previously unselected package podman.
09:11:08 #123 6.916 Preparing to unpack .../podman_3.4.4+ds1-1ubuntu1_amd64.deb ...
09:11:08 #123 6.921 Unpacking podman (3.4.4+ds1-1ubuntu1) ...
09:11:08 #123 7.270 Errors were encountered while processing:
09:11:08 #123 7.270  /var/cache/apt/archives/golang-github-containers-image_5.16.0-3_all.deb
09:11:08 #123 7.270  /var/cache/apt/archives/golang-github-containers-common_0.44.4+ds1-1_all.deb
09:11:08 #123 7.283 E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by hasan4791** [comment]
tried installing podman & cri-o in ubuntu22.04 container image by following this link and haven't got any errors.
https://www.linuxtechi.com/install-crio-container-runtime-on-ubuntu/

**Comment by spowelljr** [comment]
I followed the instructions but got the same thing, but then I tried installing podman before adding the `opensuse.org` repository and it worked, so it seems the order is the key. Thanks for getting me to revisit this @hasan4791!

**Comment by hasan4791** [comment]
Thanks, if all good we can close the issue
