### ISSUE TITLE
`cwd` fallback for ephemeral UID not functioning

### ISSUE THREAD

**Issue by nitzmahone** [cri-o/cri-o#6830]
### What happened?

The home directory added at startup to `/etc/passwd` for ephemeral UIDs (eg the default random UIDs generated by Openshift) will use the `HOME` envvar if specified in the container config, but [should fall back to the configured `cwd` for the container if not](https://github.com/cri-o/cri-o/blob/1b8b2843363c38845f44ce845d4b01ffa3436093/server/container_create.go#L210-L212). The `HOME` override works properly, but the cwd fallback does not appear to function even when the container build and config do not set `HOME` anywhere. Setting `cwd` (either via `WORKDIR` or explicitly via `working_dir` in a container JSON) is working properly as the default cwd, but is not reflected in the generated `/etc/passwd`- it seems to always be `/` when the `cwd` fallback should be used. 

The fallback-to-cwd behavior works as expected in `podman`, and the code for the `cwd` fallback exists in CRI-O (see link above), but I'm unable to get it to function.

### What did you expect to happen?

When running a container as a UID that doesn't exist in `/etc/passwd` and has `cwd` set, that the `/etc/passwd` entry created for that UID uses `cwd` as the homedir instead of always defaulting to `/`.

### How can we reproduce it (as minimally and precisely as possible)?

I was originally hitting this on Openshift, but have since reproduced it locally on Fedora 37 with just the OS-packaged CRI-O 1.24, runc, and cri-tools. 

Using the [container.json.txt](https://github.com/cri-o/cri-o/files/11276389/container.json.txt) and [pod.json.txt](https://github.com/cri-o/cri-o/files/11276390/pod.json.txt) json files attached (which use a vanilla Alpine container, ephemeral UID 12345, and sets cwd via the container config, but it behaves the same when the container specifies `WORKDIR`):

```console
$crictl exec $(crictl run container.json.txt pod.json.txt) sh -c 'whoami; pwd; echo $HOME; tail -n 1 /etc/passwd'; crictl rmp -a -f
12345
/root
/
12345:x:12345:0:12345 user:/:/sbin/nologin
Stopped sandbox e8f1eab2fb6be36b7d738d2879a53cebfc36d06e329269d25be4d85294f1a923
Removed sandbox e8f1eab2fb6be36b7d738d2879a53cebfc36d06e329269d25be4d85294f1a923
```

You can see from the output that we're running as UID 12345, that `working_dir` is being respected, but that `$HOME` is `/`, which matches the `/etc/passwd` generated entry. The fallback code *should* be setting it to `/root` in this case.

### Anything else we need to know?

The homedir fallback behavior is very important for containers that need to function well for both "listed" and "unlisted" users while preserving proper POSIX user separation within the container (Ansible execution environments, in our case).  

`/` is about the worst-possible choice for a default, since build-time permissions  on `/` are often discarded, and/or GID0 is not allowed to modify them, so ephemeral users in GID0 end up with a homedir there's no way they can ever write to.

Just blindly setting `HOME` to a fixed directory during the container build also causes a number of other issues that break POSIX user semantics, so we've been resorting to a custom entrypoint script that corrects /etc/passwd and `HOME` after the fact, which is also arguably unsafe and can break in numerous ways. This really needs to be configured in a functional way by the time user code starts running in the container.

### CRI-O and Kubernetes version

<details>

```console
$ crio --version

crio version 1.24.3
Version:          1.24.3
GoVersion:        go1.19.1
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        seccomp, selinux
SeccompEnabled:   true
AppArmorEnabled:  false
```

```console
$ kubectl --version
(N/A)
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="37 (KDE Plasma)"
ID=fedora
VERSION_ID=37
VERSION_CODENAME=""
PLATFORM_ID="platform:f37"
PRETTY_NAME="Fedora Linux 37 (KDE Plasma)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:37"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f37/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=37
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=37
SUPPORT_END=2023-11-14
VARIANT="KDE Plasma"
VARIANT_ID=kde

$ uname -a
Linux mdavis-p1 6.1.13-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Feb 22 17:53:57 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

NA

**Comment by nitzmahone** [comment]
Tracked down the problem- `Cwd` is being sampled by `setupContainerUser` before it's been calculated and reset based on "reality", so it always uses the default of `/`. The following naive change (deferring the user setup until after `containerCwd` has been calculated) makes things work the way I'd expect, though I don't know what else it might break - "worked on my machine! :laughing: ...

```
diff --git a/server/container_create_linux.go b/server/container_create_linux.go
index 627cf01d3..0db28e1dc 100644
--- a/server/container_create_linux.go
+++ b/server/container_create_linux.go
@@ -674,19 +674,6 @@ func (s *Server) createSandboxContainer(ctx context.Context, ctr ctrfactory.Cont
                specgen.AddProcessEnv(parts[0], parts[1])
        }
 
-       // Setup user and groups
-       if linux != nil {
-               if err := setupContainerUser(ctx, specgen, mountPoint, mountLabel, containerInfo.RunDir, securityContext, containerImageConfig); err != nil {
-                       return nil, err
-               }
-       }
-
-       // Add image volumes
-       volumeMounts, err := addImageVolumes(ctx, mountPoint, s, &containerInfo, mountLabel, specgen)
-       if err != nil {
-               return nil, err
-       }
-
        // Set working directory
        // Pick it up from image config first and override if specified in CRI
        containerCwd := "/"
@@ -703,6 +690,19 @@ func (s *Server) createSandboxContainer(ctx context.Context, ctr ctrfactory.Cont
                return nil, err
        }
 
+       // Setup user and groups; must be after containerCwd has been determined, since it can be used as a homedir fallback
+       if linux != nil {
+               if err := setupContainerUser(ctx, specgen, mountPoint, mountLabel, containerInfo.RunDir, securityContext, containerImageConfig); err != nil {
+                       return nil, err
+               }
+       }
+
+       // Add image volumes
+       volumeMounts, err := addImageVolumes(ctx, mountPoint, s, &containerInfo, mountLabel, specgen)
+       if err != nil {
+               return nil, err
+       }
+
        // Add secrets from the default and override mounts.conf files
        secretMounts := subscriptions.MountsWithUIDGID(
                mountLabel,
```

**Comment by nitzmahone** [comment]
NP- will try to do so when I've got some time to get my setup in line with the kubernetes contribution requirements... Sadly we had to go back to a custom entrypoint script that tries to hack around the problem in various ways to ensure that everything lines up anyway, but it'd be nice to move toward a world where such things aren't necessary! Now if only Docker would get on board :wink:

**Comment by nitzmahone** [comment]
I'm happy to draft up a blog post on the broader "why?" as well as the CRI-O-specific "how?"- might also be a good starting point for a broader conversation around trying to standardize expectations for this behavior across the container ecosystem (podman and CRI-O are very similar, especially once this bug is fixed). 

I'll have to see how painful the tests I have in mind are to actually pull off (as a Python semi-guru and Go semi-dilettante :wink:), but assuming I can get workable tests put together, maybe I'll just link or inline paste the CRI-O "how?" part into the test code, and if the "where DO our docs live?" problem ever gets solved, happy to contribute that back in another form.

**Comment by haircommander** [comment]
sounds great! however much you feel like contributing we'll be happy to accept

**Comment by haircommander** [comment]
hey @nitzmahone are you still thinking of working on this?

**Comment by nitzmahone** [comment]
I'd definitely like to- getting the code doing the right thing is the easy part (and mostly already solved), but with all the different layers involved, I don't have a good idea of how to properly create anti-regression tests for it that will actually validate that it's working properly. The last time I was looking at that stuff, there were only a handful of unit tests that really weren't doing a good job at all- seems like it calls for an integration test, but I couldn't figure out where to put it or where y'all's tests even run...

**Comment by haircommander** [comment]
yeah the `test/` directory is the best place for integration tests (which test cri-o specific behavior e2e using crictl). Given that, is the approach clear to you? I'm happy to advise on the test if you find yourself stuck.

**Comment by nitzmahone** [comment]
More or less- I need to roll some tests anyway for our supplied container entrypoint scripts that try to probe for and paper over all the differences and bugs between various runtimes/configs, so I'm guessing parts of that will be pretty easy to repurpose as a test for the desired behavior here. Just gotta figure out how to do what I want under bats...
