### ISSUE TITLE
1.27 not available in opensuse.org

### ISSUE THREAD

**Issue by spowelljr** [cri-o/cri-o#6836]
Tried to update to 1.27 using the [apt instructions](https://github.com/cri-o/cri-o/blob/v1.27.0/install.md#apt-based-operating-systems) but 1.27 is not yet present in opensuse.

https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/

**Comment by haircommander** [comment]
sorry I've had delays on building because of Kubecon. I will take care of this tomorrow

**Comment by Jeansen** [comment]
@haircommander Gread, thx. Shouldn't we try automating it?

**Comment by Jeansen** [comment]
I'd be willing to help. If you point me in the right directions ... ;-)

**Comment by haircommander** [comment]
> I'd be willing to help. If you point me in the right directions ... ;-)

thanks for the offer! is there somewhere I can contact you directly? (on the upstream k8s slack, for instance?)

**Comment by Jeansen** [comment]
@haircommander Yes, I am on the k8s slack. You can find my by my ID `U04V9V133V5`.

**Comment by Jeansen** [comment]
> > I'd be willing to help. If you point me in the right directions ... ;-)
> 
> thanks for the offer! is there somewhere I can contact you directly? (on the upstream k8s slack, for instance?)

@haircommander Did you try to get in touch? I've not received anything, so far.

**Comment by haircommander** [comment]
> > > I'd be willing to help. If you point me in the right directions ... ;-)
> > 
> > 
> > thanks for the offer! is there somewhere I can contact you directly? (on the upstream k8s slack, for instance?)
> 
> @haircommander Did you try to get in touch? I've not received anything, so far.

I have not, and I'm not able to find you. can you message me @haircommander please?
