### ISSUE TITLE
drop config migration

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#6884]
The option hasn't been populated since 1.17ish, and is largely dead code now. We should either update it to newer version or (more likely) drop the option.

Follow up of https://github.com/cri-o/cri-o/pull/6742#discussion_r1186320379

**Comment by onumengine** [comment]
Hello @haircommander
I can't find the contribution guide anywhere. Is this issue still open? I'll like to work on it

**Comment by patrickishaf** [comment]
hi @haircommander 
I can't find the contribution guide anywhere. Is this issue still open? (I want to work on it)

**Comment by haircommander** [comment]
@jbpratt has opened a PR for it already. Have you looked at https://github.com/cri-o/cri-o/blob/main/CONTRIBUTING.md yet?

/assign jbpratt
