### ISSUE TITLE
Confusing download URL for automated scripts

### ISSUE THREAD

**Issue by ezintz** [cri-o/cri-o#6888]
### What happened?

I am using kubespray to setup a cluster. While trying to add v1.27.0 to my cluster, for k8s and cri-o, the download failed because the release changed to https://storage.googleapis.com/cri-o/artifacts/cri-o.arm64.{{checksum}}.tar.gz

### What did you expect to happen?

I was expecting to find cri-o v1.27.0 by calling the usual URL e.g. https://storage.googleapis.com/cri-o/artifacts/cri-o.arm64.{{version}}.tar.gz for arm64.

### How can we reproduce it (as minimally and precisely as possible)?

Try to access the URL https://storage.googleapis.com/cri-o/artifacts/cri-o.arm64.v1.27.0.tar.gz

### CRI-O and Kubernetes version

<details>

not relevant for this issue.

</details>

### OS version

<details>

```console
Linux gru01 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:08 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
not relevant for this issue.
</details>

**Comment by haircommander** [comment]
this is all fixed then @ezintz ?

**Comment by ezintz** [comment]
I tried it manually and it worked, it seems there is a redirect setup (: So I would say yes
