### ISSUE TITLE
transfer.md is out of date

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#6896]
our documentation for transfering from docker claims some equivalences between cri-o and docker that aren't true. Specifically: all (or at least most) of the podman commands won't work with cri-o. we should clean them up and describe why there's no 1:1 mapping

**Comment by amarlearning** [comment]
@haircommander i would like to work on this. It would be great if you can assign it to me.

**Comment by haircommander** [comment]
thanks @amarlearning !
