### ISSUE TITLE
Checkpointing fails with OOM storing pipe

### ISSUE THREAD

**Issue by varungup90** [cri-o/cri-o#6936]
I am trying to run checkpoint/restore using Kubernetes 1.25.6 version + CRIO. First I tried with open-source mysql:8.0.33-debian, and checkpoint/restore works as expected. Now I am trying to do the same with our database application which is modified version of open-source mysql and here I am getting below error.

<img width="1121" alt="image" src="https://github.com/cri-o/cri-o/assets/12226243/33fd3308-f488-4f87-a56b-be3c7c182531">

<img width="1051" alt="image" src="https://github.com/cri-o/cri-o/assets/12226243/7b2c639b-dc12-4cc1-8c62-8e21f4084f68">

Installation setup
<img width="1124" alt="image" src="https://github.com/cri-o/cri-o/assets/12226243/32d28228-1614-4afb-8221-1d1ba575658b">

**Comment by adrianreber** [comment]
I would recommend to open this ticket at CRIU (https://github.com/checkpoint-restore/criu) and not CRI-O as it is not really a CRI-O problem. Please include the complete criu log as text and not as a screenshot.

Looking at the CRIU code this could be an easy fix. There is a hardcoded limit of 1024 pipes with data in CRIU and it seems your software is the first one to hit this problem. The array storing the data is hardcoded to 1024.

If you want you can try to recompile CRIU locally with and setting the define `NR_PIPES_WITH_DATA` to something bigger.

My recommendation is to close this ticket here and open it at CRIU with a full log file. Maybe try to recompile CRIU with `NR_PIPES_WITH_DATA` set to a higher value.

**Comment by varungup90** [comment]
@adrianreber After following your suggestion, I am able to checkpoint our application. But I am getting [error](https://github.com/checkpoint-restore/criu/issues/2185) on restoring and error message is not descriptive enough to root cause it. PTAL. I will close this task.
