### ISSUE TITLE
Centos7 x86_64 - Cri-o version 1.26.3 seen as 1.26.0 at kubernetes level

### ISSUE THREAD

**Issue by grunlab** [cri-o/cri-o#6947]
Hi,

I've upgraded cri-o from 1.25.3 to 1.26.3 on one of my cluster node:

```
fr0-vsiaas-8325$ sudo rpm -qa cri-o
cri-o-1.26.3-7.2.el7.x86_64
```

But the cri-o version seen at kubernetes level is 1.26.0 instead of 1.26.3 ?
```
$ kc get node fr0-vsiaas-8325 -o wide
NAME              STATUS   ROLES           AGE    VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                                      KERNEL-VERSION                CONTAINER-RUNTIME
fr0-vsiaas-8325   Ready    control-plane   2y2d   v1.25.8   10.125.57.29   <none>        Red Hat Enterprise Linux Server 7.9 (Maipo)   3.10.0-1160.90.1.el7.x86_64   cri-o://1.26.0
```

Is that normal ?

Thank you

**Comment by grunlab** [comment]
Hi,

Additionally, cri-tools version 1.21.0 for Centos7 (https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/x86_64) looks now outdated for cri-o 1.26 (where the API v1alpha2 has been replaced by v1):

```
fr0-vsiaas-8325$ crictl -v
crictl version 1.21.0
```

```
fr0-vsiaas-8325$ sudo crictl ps
FATA[0000] listing containers: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
```

So could you please also update the version of the package cri-tools for Centos7 in order to be compatible with cri-o 1.26 and later ?

Thank you

**Comment by haircommander** [comment]
holy cow I'm sorry, this fell under the radar. I am building cri-tools 1.26.0 now. As for the version issue, that's pretty weird. when you do a `crio -v` what is the output?

**Comment by grunlab** [comment]
No pb for the delay of the response. No hurry on my side regarding this issue.
I will test again the upgrade of crio from 1.25 to 1.26 in the coming days.
I keep you informed.

**Comment by grunlab** [comment]
Hi,
I've just installed cri-o 1.26.4 and all is ok now.

```
$ kc get node -o wide fr0-vsiaas-8325
NAME              STATUS                     ROLES           AGE      VERSION    INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                                      KERNEL-VERSION                CONTAINER-RUNTIME
fr0-vsiaas-8325   Ready,SchedulingDisabled   control-plane   2y122d   v1.25.10   10.125.57.29   <none>        Red Hat Enterprise Linux Server 7.9 (Maipo)   3.10.0-1160.99.1.el7.x86_64   cri-o://1.26.4
```
