### ISSUE TITLE
Can't get repo for RHEL 8

### ISSUE THREAD

**Issue by OranGeNaL** [cri-o/cri-o#6954]
I can't get repo from https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/devel:kubic:libcontainers:stable.repo

There is only **languages:/** directory in **https://download.opensuse.org/repositories/devel:/**.

**Comment by saschagrunert** [comment]
Seems to be related to https://progress.opensuse.org/issues/129721
