### ISSUE TITLE
Document configuration deprecation process

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#6959]
We do have a process for deprecating/changing our config, but it's not documented anywhere.

**Comment by Naresh-chandanbatve** [comment]
hey @haircommander 
I would like to take this one..
can you assign this to me.

also share the process to document and where would yo like to document it.

**Comment by prash240303** [comment]
Hello @haircommander can u please more elaborate the issue so that i can work on it as  a starting contributor (good first issue)

**Comment by haircommander** [comment]
basically, the highlights are:
- config options are removed following a deprecation process.
    - config options are not removed mid patch stream (an option present in 1.1.1 will not be removed in 1.1.2)
- before an option is removed, it will be marked deprecated for at least one release
    - deprecation is marked by editing the documentation, the CLI help text and ideally also a log in CRI-O
- Usually, a config option is dropped because it is no longer relevant, or it has been replaced by an option in the Kubelet
- Generally, the toml library CRI-O uses to render a config will ignore unknown values. However, unrecognized CLI flags will cause CRI-O to fail.
    - thus, sometimes a CLI flag will be left in cri-o for an extra release, but it will be disabled, and only keep its place to give users more time to remove it.

**Comment by saschagrunert** [comment]
@sarthaksarthak9 I'm clearing the assignment for now, feel free to reassign if you still want to work on this

**Comment by AHB102** [comment]
@haircommander I'm new to open source, can I work on this issue ?  From what I understand I just have to document steps for deprecating/changing our configs, mentioned by you in this conversation, right ?

**Comment by haircommander** [comment]
correct @AHB102 thanks!

**Comment by haircommander** [comment]
yeah please do

**Comment by AHB102** [comment]
@haircommander I have created a document based on the highlights , but it explain the deprecation process in a broad, generalized way, so should I create a PR and refine it incrementally by committing changes ? 
I do need some help for the finer details of the exact process.

**Comment by haircommander** [comment]
thanks, let's start with a PR and move back to a doc if needed

**Comment by SD-13** [comment]
Seems like this issue is resolved. Can we close this?
