### ISSUE TITLE
REQUEST: New org member status for @amarlearning

### ISSUE THREAD

**Issue by amarlearning** [cri-o/cri-o#6968]
### GitHub Username

@amarlearning

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have one sponsor from the list of approvers in at least one OWNERS file within the CRI-O repository
- [X] I have spoken to my sponsor ahead of this application, and they have agreed to sponsor my application

### Sponsor

@haircommander

### List of contributions to the CRI-O project

**Authored PR** 
- https://github.com/cri-o/cri-o/pull/6289
- https://github.com/cri-o/cri-o/pull/6475
- https://github.com/cri-o/cri-o/pull/6476
- https://github.com/cri-o/cri-o/pull/6891
- https://github.com/cri-o/cri-o/pull/6942

**Comment by haircommander** [comment]
+1 from me!

**Comment by saschagrunert** [comment]
+1 from my side as well!

**Comment by haircommander** [comment]
sorry for the delay, I've sent you a request! Welcome to the organization :)
