### ISSUE TITLE
bad logic in "ctr with node level pid namespace should not leak children" 

### ISSUE THREAD

**Issue by kolyshkin** [cri-o/cri-o#6979]
### What happened?

_filing this so I won't forget_

In this test case, we get ALL conmon pids, and thus it is not working as it should in case of parallel tests, or if someone is running other containers, etc.

Here's the problematic line:

https://github.com/cri-o/cri-o/blob/395d32218aa2173c6f9c0cfa940741c90c29d4c0/test/ctr.bats#L1005

(instead of getting OUR conmon pid, we get all of them).

The second problem is, conmon itself is not included into the check (should it? I think so).

Now, there are a few approaches to fixing this:

1. Get the conmon pid from the pidfile, e.g.

```bash
       conmon_pid="$(find $TESTDIR -path '*/userdata/conmon-pidfile' -type f -exec cat '{}' \;)"
       kill -0 "$conmon_pid" # Sanity check -- make sure conmon_pid is valid.
       processes=$(list_all_children "$conmon_pid" $conmon_pid)
```

Here we also add the conmon's own pid.

2. In case the conmon pid is not needed (it was not used in the original test except for getting childrent), we can get container init pid and go from there.

3. We can get the list of pids from the cgroup.

**Comment by kolyshkin** [comment]
@haircommander do you think we should add conmon's own pid to the list of pids being checked, or not? The approach to use depends on the answer.

**Comment by haircommander** [comment]
(we spoke offline, but answering for posterity) conmon's own pid should not be included, the test is looking for all of the pids inside the container
