### ISSUE TITLE
[issue] Release.key of v1.27.0 for Debian 11 is missing

### ISSUE THREAD

**Issue by yjqg6666** [cri-o/cri-o#6980]
### What happened?

[Release key of v1.27.0 for Debian 11](https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/v1.27.0/Debian_11/Release.key) is not found and got 404 page.

### What did you expect to happen?

It should be available.

### How can we reproduce it (as minimally and precisely as possible)?

View the URL from a browser.

### CRI-O and Kubernetes version

v1.27.1

### OS version

Debian 11 Bullseye

### Additional environment details (AWS, VirtualBox, physical, etc.)

Any OS.

**Comment by yjqg6666** [comment]
From [the dir list](https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/), the recent one is   1.24 or more specifically 1.24.3 and not the version listed in [the github release page](https://github.com/cri-o/cri-o/releases).

**Comment by yjqg6666** [comment]
I would like to propose to update [the installation instruction](https://github.com/cri-o/cri-o/blob/main/install.md#apt-based-operating-systems).

**Comment by haircommander** [comment]
the path you're looking for is https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.27:/1.27.0/Debian_11/Release.key
we don't include the `v` and if you're looking for a specific release (and not the streaming minor release 1.27.z), you need to specify 1.27:/1.27.0

**Comment by wp4nuv** [comment]
> I would like to propose to update [the installation instruction](https://github.com/cri-o/cri-o/blob/main/install.md#apt-based-operating-systems).

I found this same problem when installing. The instructions imply there is already a variable $VERSION already set. A documentation update should also include this variable and a proposed value, same as with the OS name.

**Comment by haircommander** [comment]
@wp4nuv would you like to submit a PR to update the instructions to be clearer?

**Comment by wp4nuv** [comment]
I can, but TBH, this is my first time using CRI-O, so while it’s easy to assume to set $VERSION at the latest, it may not always be true.  Can there be a moment when using the latest may not be helpful?

**Comment by haircommander** [comment]
VERSION should correspond to the CRI-O version you want. We recommend matching the minor version (1.y) to match the kubernetes minor version. For instance, if you're using kubernetes 1.27.z, we'd recommend VERSION to either be 1.27 (a rolling release of the latest of our 1.27 branch) or pinned to a specific CRI-O version if they want to upgrade more intentionally, which would set VERSION to 1.27:1.27.0 or any other specific version

does that make sense?

**Comment by wp4nuv** [comment]
Yeah, thanks.  I can manage from here.  Is there any requirement for a new contributor to have before being allowed to submit a PR?

**Comment by haircommander** [comment]
excellent to hear! we just ask you [sign your PR](https://github.com/cri-o/cri-o/blob/main/CONTRIBUTING.md#sign-your-prs)

**Comment by yjqg6666** [comment]
@wp4nuv Any update?

**Comment by wp4nuv** [comment]
I am so sorry, I’ve been swamped with work, and an unexpected trip to care for my mom has derailed me.

**Comment by haircommander** [comment]
don't worry about it @wp4nuv take your time :) if you want us to take it over please feel free to let us know

**Comment by wp4nuv** [comment]
I finally got a second to write my edits to the `install-distro.md` document.  I've noticed that the `Supported Versions` matrix only goes up to version 1.18. Would any updates to that matrix make any difference for the listed operating systems?  How far back should that matrix go?

**Comment by wp4nuv** [comment]
I keep finding weird things in the document. Would it make sense to make a new issue for those? The issue is that to install a patch version on a `yum` operating system, the assumption that the `$VARIABLE` value can be both a directory-separated value and not a separated value, breaks down due to the directory structure in the repository.  
This is not a problem with Apt-based systems.

**Comment by haircommander** [comment]
sorry for the delay @wp4nuv please feel free to open new issues / PRs if you have any!
