### ISSUE TITLE
/var/lib/containers/storage/overlay unused containers root FS not getting cleaned

### ISSUE THREAD

**Issue by shashipratap** [cri-o/cri-o#6981]
### What happened?

/var/lib/containers/storage/overlay on k8s nodes contains the root FS of all containers running on that node , there are a lot of root FS which do not belong to any running container which is causing space to be used on nodes and eventually pods getting evicted due to low ephermal storage

### What did you expect to happen?

unused root FS sha directory which are not associated with any container should be removed from the /var/lib/containers/storage/overlay directory

### How can we reproduce it (as minimally and precisely as possible)?

create a cluster in OCI console and use oracle linux 7.9 nodes in it 

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.23.3-144.el7
Version:          1.23.3-144.el7
GitCommit:        unknown
GitTreeState:     unknown
BuildDate:        2023-03-15T20:49:19Z
GoVersion:        go1.19.6 A1727 X:boringcrypto
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        exclude_graphdriver_devicemapper, containers_image_ostree_stub, seccomp, selinux
SeccompEnabled:   true
AppArmorEnabled:  false
```

```console
$ kubectl version --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "23",
    "gitVersion": "v1.23.5",
    "gitCommit": "c285e781331a3785a7f436042c65c5641ce8a9e9",
    "gitTreeState": "clean",
    "buildDate": "2022-03-16T15:51:05Z",
    "goVersion": "go1.17.8",
    "compiler": "gc",
    "platform": "darwin/arm64"
  },
  "serverVersion": {
    "major": "1",
    "minor": "23",
    "gitVersion": "v1.23.4",
    "gitCommit": "0b25cacbeba0b73f720022544dd02ffe9e67017e",
    "gitTreeState": "clean",
    "buildDate": "2022-03-16T11:33:38Z",
    "goVersion": "go1.17.7 BoringCrypto",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="7.9"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Oracle Linux Server 7.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.9
$ uname -a
Linux oke-cmwagxoyvfq-npya4mblquq-scz3hvrucya-1 5.4.17-2136.317.5.3.el7uek.x86_64 #2 SMP Thu Mar 16 19:26:27 PDT 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

OCI k8s cluster with oracle linux 7.9 nodes

**Comment by whygyc** [comment]
Storage provides a cleanup function, which I believe CRI-O needs to call at the appropriate time to clean up incorrect rootFS. This seems like a simple fix.

Reference:
https://github.com/cri-o/cri-o/blob/cde8de8a4e32a5d1972cbb01bd236db6ae75e5b6/vendor/github.com/containers/storage/store.go#L3543-L3546

https://github.com/containers/storage/pull/1424/commits/ddf18d41da7a74841cc862c3337578ae1f8634fe

**Comment by haircommander** [comment]
yeah a periodic garbage collection of dangling layers makes sense to me. I would naively expect that to be cleaned up when we remove containers though (cc @nalind @giuseppe ). Is it possible they're sticking around because kubelet hasn't triggered garbage collection on them?

**Comment by nalind** [comment]
Layers that are part of images should already be automatically removed when the only image that uses them is removed.  The `GarbageCollect()` call is intended for cleaning up content that's expected to be left behind when a node that has the `transient_store` option enabled is rebooted, and that tends to be done at boot-time by the `podman-clean-transient` systemd service, which should be enabled when that option is used.  It should be harmless to use it at other times, though.

**Comment by whygyc** [comment]
> Layers that are part of images should already be automatically removed when the only image that uses them is removed. The `GarbageCollect()` call is intended for cleaning up content that's expected to be left behind when a node that has the `transient_store` option enabled is rebooted, and that tends to be done at boot-time by the `podman-clean-transient` systemd service, which should be enabled when that option is used. It should be harmless to use it at other times, though.

In line 262, we specified `Volatile: true` as an option for CreateContainer.

https://github.com/cri-o/cri-o/blob/e46a5207f2a05ad224b98dfc49f77fb996bb30ce/internal/storage/runtime.go#L260-L267

On the storage side, even if transient_store is not specified, a similar storage method is still used (using the `noSync` option and storing in the `volatile-layers.json` file).
For CRI-O, whether `transient_store` is specified only affects whether `volatileDir` is `layerdir` or `rundir`. In practice, we are already using the `volatile-layers.json` file.

https://github.com/cri-o/cri-o/blob/e46a5207f2a05ad224b98dfc49f77fb996bb30ce/vendor/github.com/containers/storage/store.go#L1698-L1702


This could also potentially lead to "Losing track of containers and layers can potentially happen in the case of some kind of unclean shutdown," even if `transient_store` is not specified.
Therefore, I believe CRI-O should add handling to avoid this situation.

**Comment by haircommander** [comment]
@whygyc would you like to open a PR adding the call? from the sounds of it, we could just call it at CRI-O startup once, as most of the cases it covers are to handle node reboots

**Comment by whygyc** [comment]
> @whygyc would you like to open a PR adding the call? from the sounds of it, we could just call it at CRI-O startup once, as most of the cases it covers are to handle node reboots

Ok, I'll try it

**Comment by pl4nty** [comment]
I'm not sure this is related to node reboots, I've seen similar symptoms consistently on OKE nodes that haven't been rebooted since creation. Is there a command to check whether a root fs SHA belongs to a running container? I didn't have much luck with `k debug node` and `crictl`. I use Flux CD which runs a few ephemeral pods on schedules, and might exacerbate the issue if `var/lib/containers/storage/overlay` isn't being cleaned up properly

**Comment by haircommander** [comment]
so if the container is still around after the reboot, you can look at its config.json runtime config at 
`/var/lib/containers/storage/overlay-containers/$container_id/userdata/config.json`
then, the path will be in the `.root.path`, like so:
```
cat /var/lib/containers/storage/overlay-containers/$container_id/userdata/config.json | jq .root.path
```
or you can use grep through overlay-containers to find that rootfs sha

**Comment by whygyc** [comment]
> I'm not sure this is related to node reboots, I've seen similar symptoms consistently on OKE nodes that haven't been rebooted since creation. Is there a command to check whether a root fs SHA belongs to a running container? I didn't have much luck with `k debug node` and `crictl`. I use Flux CD which runs a few ephemeral pods on schedules, and might exacerbate the issue if `/var/lib/containers/storage/overlay` isn't being cleaned up properly

The `/var/lib/containers/storage/overlay` directory contains not only the layers of running containers but also the layers of images. So, if you notice that even without running containers, this directory contains many folders, it is mostly normal because those folders are the layers of the images.

Currently, there is no command to confirm this. However, you can execute the following commands to obtain the currently managed SHAs:
```
cat /var/lib/containers/storage/overlay-layers/layers.json | jq . | grep "id\""
cat /var/lib/containers/storage/overlay-layers/volatile-layers.json | jq . | grep "id\""
```
In normal circumstances, the `id` in the output results should include the names of all folders under the `/var/lib/containers/storage/overlay` directory (except the `l` folder).
