### ISSUE TITLE
Issues with CRIO/CNI interactions

### ISSUE THREAD

**Issue by prabhakar-oracle** [cri-o/cri-o#6984]
### What happened?

1. Currently it is not possible to configure the timeout period for the execution of the CNI plugin. The timeout is hardcoded to 60 seconds in CRIO code
2. The actual error during the interaction between CRIO and CNI plugin is not logged clearly to indicate the reason for failure
3. CRIO should have better handling of the CNI errors. Currently there is no handling of the errors from CNI. For instance, the error could be due to a timeout in the processing of the CNI request. But the errors are forwarded to Kubelet (when CRIO is used with Kubernetes)
4. CRIO metrics are not populated with accurate data to reflect the actual latency in executing the CNI commands

### What did you expect to happen?

1. The timeout for the execution of CNI operations should be configurable in CRIO
2. In case of timeout in CNI, the log messages should be clear in CRIO to indicate why CNI command failed 
3. CRIO should handle the CNI errors in better - retry in case of timeouts
4. The CRIO metrics should be populated to correctly populate the distribution of the latency values for various CNI commands (Currently the metrics seem to exist but no populated)

### How can we reproduce it (as minimally and precisely as possible)?

Instrument the CNI to take more than 60 seconds to process the CNI DEL command.

This issue was seen across CRIO versions, we used CRIO versions corresponding to Kubernetes 1.22/1.23/1.24 to list a few.

### CRI-O and Kubernetes version

<details>

```
$ crio version
WARN[0000] Failed to decode the keys ["storage.options.override_kernel_check"] from "/etc/containers/storage.conf".
INFO[2023-05-29 16:31:06.643708347Z] Starting CRI-O, version: 1.23.3-144.el7, git: unknown(unknown)
Version:          1.23.3-144.el7
GitCommit:        unknown
GitTreeState:     unknown
BuildDate:        2023-03-15T20:49:19Z
GoVersion:        go1.19.6 A1727 X:boringcrypto
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        exclude_graphdriver_devicemapper, containers_image_ostree_stub, seccomp, selinux
SeccompEnabled:   true
AppArmorEnabled:  false
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="7.9"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Oracle Linux Server 7.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.9

$ uname -a
Linux host-10-64-220-173 5.4.17-2136.317.5.3.el7uek.x86_64 #2 SMP Thu Mar 16 19:26:27 PDT 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by PaulFurtado** [comment]
@prabhakar-oracle what behavior do you see when these timeouts occur? Does kubelet end up retrying the request or does the pod get stuck?

**Comment by prabhakar-oracle** [comment]
The POD termination is stuck till we do kubelet restart

**Comment by PaulFurtado** [comment]
I also just added a `sleep(1000)` in our CNI plugin's ADD and DEL hooks to test this. I think this may be the source of a lot of our cri-o problems. We are in AWS, so the CNI plugin can take a long time to allocate ENIs and IP addresses when facing rate-limits.

I've confirmed that this definitely results in our "named is reserved" bugs that prevent pods from ever starting after CNI has timed out. That said, the timeout on the DEL hook doesn't seem to behave incorrectly to me on cri-o 1.25: cri-o just retries the CNI DEL hook until it executes within the timeout. Does your CNI DEL consistently take more than 60s?

**Comment by haircommander** [comment]
@prabhakar-oracle all of the listed issues I am open to fixing. Do you have any desire to open a PR to update? I'd be happy to collaborate :)

**Comment by haircommander** [comment]
> CRIO should have better handling of the CNI errors. Currently there is no handling of the errors from CNI. For instance, the error could be due to a timeout in the processing of the CNI request. But the errors are forwarded to Kubelet (when CRIO is used with Kubernetes)

what are you imagining would happen here?

**Comment by prabhakar-oracle** [comment]
> > CRIO should have better handling of the CNI errors. Currently there is no handling of the errors from CNI. For instance, the error could be due to a timeout in the processing of the CNI request. But the errors are forwarded to Kubelet (when CRIO is used with Kubernetes)
> 
> what are you imagining would happen here?

Kubelet is terrible in handling errors from the container runtime. In this scenario, i see that the pod is stuck in terminating state and this issue was recovered by restarting kubelet

**Comment by prabhakar-oracle** [comment]
>

**Comment by prabhakar-oracle** [comment]
> I also just added a `sleep(1000)` in our CNI plugin's ADD and DEL hooks to test this. I think this may be the source of a lot of our cri-o problems. We are in AWS, so the CNI plugin can take a long time to allocate ENIs and IP addresses when facing rate-limits.
> 
> I've confirmed that this definitely results in our "named is reserved" bugs that prevent pods from ever starting after CNI has timed out. That said, the timeout on the DEL hook doesn't seem to behave incorrectly to me on cri-o 1.25: cri-o just retries the CNI DEL hook until it executes within the timeout. Does your CNI DEL consistently take more than 60s?

Yes @PaulFurtado we found an internal regression which caused the latency and this internal issue is fixed now. But wanted to callout the underlying issue in crio

**Comment by kwilczynski** [comment]
Was there ever any consensus here about what to do to move forward?
