### ISSUE TITLE
PSA: Plan to retire the Fedora cri-o module and move back to a standard RPM

### ISSUE THREAD

**Issue by LorbusChris** [cri-o/cri-o#6986]
We're planning to retire the Fedora cri-o module.
Instead, the plan is to release cri-o and cri-tools as standard RPMs, starting with the Fedora 39/cri-o 1.28 cycle.

Please let us know here if this change poses a problem to your workflows.

Fedora ticket: https://pagure.io/fedora-infrastructure/issue/11351

cc @haircommander

**Comment by LorbusChris** [comment]
We'll likely do the switch for Fedora 39.

**Comment by saschagrunert** [comment]
@LorbusChris anything we have to do from the CRI-O side?

**Comment by LorbusChris** [comment]
https://pagure.io/releng/issue/11661
