### ISSUE TITLE
error while using  grpc  internal client library

### ISSUE THREAD

**Issue by coolninja1504** [cri-o/cri-o#6999]
I am trying to use the  cri-o's internal client library https://github.com/cri-o/cri-o/blob/main/internal/client/client.go as follows for getting some container information :

```
 package main

import (
        "context"
        "log"
        "fmt"
        "github.com/cri-o/cri-o/internal/client"
        "google.golang.org/grpc"
)
func createContainerdClient() (*client.CrioClient, error) {
        client, err := client.New("/var/run/crio/crio.sock")
        if err != nil {
                log.Fatal("Failed  for Conn ", err)
                return nil, err
        }
        return client, nil
}

func getContainerInfo() {
         client, err := createContainerdClient()
        if err != nil {
                log.Fatal("Failed to create containerd client:", err)
        }
}

func main() {
        getContainerInfo()
}
```

But getting the following error while compiling:

```
package main
        main.go:7:9: use of internal package github.com/cri-o/cri-o/internal/client not allowed
```

Can you please let me know  how can  I use the client for getting container information ?

Thanks

**Comment by coolninja1504** [comment]
> we intentionally don't expose our client because it's not meant to be a library. What are you trying to acheieve? could you use the crictl client instead?

Thanks a lot for replying @haircommander  . I want to get the details of the container by giving the containerd_id through go code.
I was using  cri-o's HTTP API  to get those details,  but saw this msg that this http api is  not stable   :
https://github.com/cri-o/cri-o#the-http-status-api

> there exists an additional HTTP API to retrieve further runtime status information about CRI-O. Please be aware that this API is not considered to be stable and production use-cases should not rely on it.

Then I tried  to use the client to get this info from cri-o's gRPC Server , and got the error.

Can you please let me know how can I interact with cri-o's grpc to get container information.

**Comment by haircommander** [comment]
you could do something like https://github.com/kubernetes-sigs/cri-tools/blob/master/cmd/crictl/main.go#L58
and then interact with it like https://github.com/kubernetes-sigs/cri-tools/blob/master/cmd/crictl/info.go#L70

**Comment by coolninja1504** [comment]
Hi @haircommander  , thanks a lot for referring to the code.

Instead of using getRuntimeService as mentioned  in https://github.com/kubernetes-sigs/cri-tools/blob/master/cmd/crictl/main.go#L58  , I have used  cri-api library bindings  as follows:

 ```
                client := pb.NewRuntimeServiceClient(conn)
                ContainerStatusRequest := &pb.ContainerStatusRequest{
                        ContainerId: containerid,
                        Verbose:     true,
                }
                containerStatus, err := client.ContainerStatus(context.Background(),  ContainerStatusRequest)
                if err != nil {
                        log.Fatalf("Failed to get containers status: %v", err)
                }

```
With this code , I am getting the required container information when container-id is provided. 

Can you please let me know if this is correct and  is supported by cri-o ?

**Comment by haircommander** [comment]
yes this is a supported method! interacting through the CRI is the best way to communicate with cri-o :)

**Comment by coolninja1504** [comment]
Thanks for confirming.
