### ISSUE TITLE
Deprecate and remove device mapper storage driver

### ISSUE THREAD

**Issue by kolyshkin** [cri-o/cri-o#7002]
It seems that no one is using devicemapper storage driver nowadays, since overlayfs is so much better.

Can it be deprecated and removed? I see that moby/moby did that recently.

See also: https://github.com/containers/storage/issues/1619

**Comment by haircommander** [comment]
+1 from me, but we should have a slower deprecation process. 1.28, we can warn the user if they're using devmapper and mark as deprecated, and 1.29 we can drop support

**Comment by saschagrunert** [comment]
+1 from my side, putting it into the project board
