### ISSUE TITLE
Constant "Failed to create pod sandbox: rpc error: code = DeadlineExceeded" and "name is reserved" errors

### ISSUE THREAD

**Issue by PaulFurtado** [cri-o/cri-o#7010]
### What happened?

We have been running cri-o on about 4,000 nodes for two months now and it has degraded to a basically unusable state.

On so many nodes we see these DeadlineExceeded errors creating pod sandboxes, which is then followed up with "name is reserved" errors that make it impossible for a given pod to recover without someone getting paged. Deleting a pod that ends up in this state will fix the "name is reserved" issue for that pod, but inevitably once a node starts hitting these it seems like it is guaranteed to have additional pods end up this state. At this point, we have automation scanning the kubelet logs for "name is reserved", then draining all pods off the node because it is the only way we can keep things running smoothly.

Initially, I thought that https://github.com/cri-o/cri-o/issues/6984 might be the issue but our CNI plugin logs statistics about execution time, scanning the logs I see that there is no execution time that exceeds 10s and no logs indicating that some CNI execution started and did not complete.

For example, our CNI will log:
```
Jun 01 10:17:22 ip-172-16-120-56 crio[638717]: cni-helper | pid=278871 | 2023-06-01 10:17:21,974 | INFO     | hs_cni_helpers.cni_entrypoint | Handling CNI DEL command
... bunch of stuff ...
Jun 01 10:17:22 ip-172-16-120-56 crio[638717]: cni-helper | pid=278871 | 2023-06-01 10:17:21,996 | INFO     | hs_cni_helpers.cni_entrypoint | Total code runtime: 0.072s. Total process runtime: 0.714s.
Jun 01 10:17:22 ip-172-16-120-56 crio[638717]: cni-helper | pid=278871 | 2023-06-01 10:17:21,996 | INFO     | hs_cni_helpers.cni_entrypoint | Other durations: lock_host-ipsets-lock=0.000s, lock_host-routes-lock=0.000s, lock_ipam-state=0.000s
```
We add `pid=278871` to each CNI log line so that we can grep through logs to construct a complete execution.

Here's what we have from the crio log: https://gist.githubusercontent.com/PaulFurtado/046e4fa3e79bf3206122327a0b08b0af/raw/d77d3dbe38bbdf296187c1e5520d17952e22262f/crio-ip-172-16-120-56-redacted.log
goroutine stacks: https://gist.githubusercontent.com/PaulFurtado/046e4fa3e79bf3206122327a0b08b0af/raw/bf7a186c39841814dcb1b2b6b5e0e264eb637d71/crio-goroutine-stacks-2023-06-01T161220Z.log

### What did you expect to happen?

cri-o should not get stuck creating pods so often

### How can we reproduce it (as minimally and precisely as possible)?

It's hard to say. If you run cri-o at scale for months, I cannot imagine how you could ever not run into this though.

If anything seems obvious from the logs or the goroutines, I'm happy to help test the theory.

### Anything else we need to know?

In many cases where cri-o is stuck, `crictl inspect` will block on some container. That did not happen at all in this case though.

### CRI-O and Kubernetes version

<details>

```console
# crio --version
crio version 1.23.4
Version:          1.23.4
GitCommit:        a6a1e6ebf4c4baca7ca7d57f069a4e0cd89056cd
GitTreeState:     dirty
BuildDate:        1980-01-01T00:00:00Z
GoVersion:        go1.17.4
Compiler:         gc
Platform:         linux/amd64
Linkmode:         static
BuildTags:        apparmor, exclude_graphdriver_devicemapper, seccomp, selinux
SeccompEnabled:   true
AppArmorEnabled:  false
 QA - iad03  [root@ip-172-18-63-2
```

```console
# kubectl version --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "23",
    "gitVersion": "v1.23.16",
    "gitCommit": "60e5135f758b6e43d0523b3277e8d34b4ab3801f",
    "gitTreeState": "archive",
    "buildDate": "2023-05-17T15:49:52Z",
    "goVersion": "go1.19.5",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "serverVersion": {
    "major": "1",
    "minor": "23",
    "gitVersion": "v1.23.16",
    "gitCommit": "60e5135f758b6e43d0523b3277e8d34b4ab3801f",
    "gitTreeState": "archive",
    "buildDate": "2023-05-17T15:49:52Z",
    "goVersion": "go1.19.5",
    "compiler": "gc",
    "platform": "linux/arm64"
  }
}
```

</details>

### OS version

<details>

```console
# cat /etc/os-release 
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

# uname -a
Linux ip-172-18-63-221 5.15.86-hs36.el8.x86_64 cri-o/ocicni#1 SMP Thu Mar 2 01:02:06 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
- AWS (non-EKS)
</details>

**Comment by hasan4791** [comment]
@PaulFurtado Does it occur in any specific scenarios or randomly after sometime?

**Comment by PaulFurtado** [comment]
@hasan4791 it seems to be randomly after some time, but it could just be that not many pods were moving around for a while and then teams started doing some deploys. Once a node starts acting up like this, it can happen for the simplest of pods just as likely as the most complex.

Does anything unexpected stand out to you from the goroutine stacks? If you notice any hint there, I might be able to drill into it

**Comment by haircommander** [comment]
@PaulFurtado I am seeing a lot of calls to `StatsForContainers`, can you show me your crio config? are you using crictl stats on those nodes or have you patched the kubelet to use cri stats for cri-o?

**Comment by haircommander** [comment]
so the `name is reserved` error is kind of a misnomer, what it's actually saying is "kubelet is retrying requests before cri-o can process them". The reasoning behind cri-o's depends on the node's state. @jdbarnes-isi can you post the cri-o logs with the `name is reserved` error so we can see what the cause may be

**Comment by jdbarnes-isi** [comment]
replying in the other related issue https://github.com/cri-o/ocicni/issues/114#issuecomment-1584585625

**Comment by dgl** [comment]
We are seeing a similar issue with cri-o 1.24.5.

In particular, we see a nearly identical case where a goroutine is seemingly stuck on I/O operations, similar...
<details><summary>to this one, extracted from the goroutine stack above</summary>

```
goroutine 33825823 [runnable]:
syscall.Syscall6(0x106, 0xffffffffffffff9c, 0xc0111488f0, 0xc00e66b488, 0x100, 0x0, 0x0)
	syscall/asm_linux_amd64.s:43 +0x5
syscall.fstatat(0x0, {0xc011148840, 0xa3}, 0xc00e66b488, 0xa3)
	syscall/zsyscall_linux_amd64.go:1441 +0x10f
syscall.Lstat(...)
	syscall/syscall_linux_amd64.go:74
os.lstatNolog.func1(...)
	os/stat_unix.go:46
os.ignoringEINTR(...)
	os/file_posix.go:246
os.lstatNolog({0xc011148840, 0x6})
	os/stat_unix.go:45 +0x5b
os.Lstat({0xc011148840, 0xa3})
	os/stat.go:22 +0x34
path/filepath.walk({0xc007237780, 0x77}, {0x23dd410, 0xc0132535f0}, 0xc01208f4e8)
	path/filepath/path.go:436 +0x1db
path/filepath.walk({0xc007236000, 0x73}, {0x23dd410, 0xc013249790}, 0xc01208f4e8)
	path/filepath/path.go:442 +0x28f
path/filepath.Walk({0xc007236000, 0x73}, 0xc01208f4e8)
	path/filepath/path.go:505 +0x6c
github.com/containers/storage/pkg/directory.Usage({0xc007236000, 0x73})
	github.com/containers/storage@v1.37.2/pkg/directory/directory_unix.go:24 +0x11a
github.com/containers/storage/drivers/overlay.(*Driver).ReadWriteDiskUsage(0xc00be9d680, {0xc0021b6eae, 0x40})
	github.com/containers/storage@v1.37.2/drivers/overlay/overlay_cgo.go:20 +0xdf
github.com/cri-o/cri-o/internal/lib/stats.(*StatsServer).writableLayerForContainer(0xc00061ad40, 0xc000e3c280)
	github.com/cri-o/cri-o/internal/lib/stats/stats_server.go:193 +0x1af
github.com/cri-o/cri-o/internal/lib/stats.(*StatsServer).populateWritableLayer(0x1dc05c0, 0xc007d5ff50, 0xc000052058)
	github.com/cri-o/cri-o/internal/lib/stats/stats_server.go:174 +0x25
github.com/cri-o/cri-o/internal/lib/stats.(*StatsServer).updateContainer(0xc00061ad40, 0xc000e3c280, 0xc00059ca80)
	github.com/cri-o/cri-o/internal/lib/stats/stats_server.go:147 +0x195
github.com/cri-o/cri-o/internal/lib/stats.(*StatsServer).statsForContainer(0xc00061ad78, 0xc0005b7340, 0x0)
	github.com/cri-o/cri-o/internal/lib/stats/stats_server.go:322 +0x7b
github.com/cri-o/cri-o/internal/lib/stats.(*StatsServer).StatsForContainers(0xc00061ad40, {0xc008266680, 0x44, 0x0})
	github.com/cri-o/cri-o/internal/lib/stats/stats_server.go:311 +0x185
github.com/cri-o/cri-o/server.(*Server).ListContainerStats(0xc0006f0700, {0x23babc0, 0xc00152ea20}, 0xc00396c6c0)
	github.com/cri-o/cri-o/server/container_stats_list.go:30 +0x149
github.com/cri-o/cri-o/server/cri/v1.(*service).ListContainerStats(0xc00152ea20, {0x23babc0, 0xc00152ea20}, 0xc01208f9f0)
	github.com/cri-o/cri-o/server/cri/v1/rpc_list_container_stats.go:12 +0x26
k8s.io/cri-api/pkg/apis/runtime/v1._RuntimeService_ListContainerStats_Handler.func1({0x23babc0, 0xc00152ea20}, {0x1f81160, 0xc00396c6c0})
	k8s.io/cri-api@v0.23.0-alpha.3/pkg/apis/runtime/v1/api.pb.go:9217 +0x78
github.com/cri-o/cri-o/internal/log.UnaryInterceptor.func1({0x23babc0, 0xc00152e930}, {0x1f81160, 0xc00396c6c0}, 0xc000164a40, 0xc007ed2768)
	github.com/cri-o/cri-o/internal/log/interceptors.go:56 +0xc3
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x23babc0, 0xc00152e930}, {0x1f81160, 0xc00396c6c0})
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/cri-o/cri-o/server/metrics.UnaryInterceptor.func1({0x23babc0, 0xc00152e930}, {0x1f81160, 0xc00396c6c0}, 0xc00a0ce320, 0xc00a0ce340)
	github.com/cri-o/cri-o/server/metrics/interceptors.go:24 +0xb2
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x23babc0, 0xc00152e930}, {0x1f81160, 0xc00396c6c0})
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x23babc0, 0xc00152e930}, {0x1f81160, 0xc00396c6c0}, 0xc000164bb8, 0x1dd4de0)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xbf
k8s.io/cri-api/pkg/apis/runtime/v1._RuntimeService_ListContainerStats_Handler({0x200ebc0, 0xc0005acda8}, {0x23babc0, 0xc00152e930}, 0xc00f7a27e0, 0xc000b8db90)
	k8s.io/cri-api@v0.23.0-alpha.3/pkg/apis/runtime/v1/api.pb.go:9219 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00059d340, {0x23f46c0, 0xc009d2af00}, 0xc0003d1440, 0xc003a216b0, 0x344eb08, 0x0)
	google.golang.org/grpc@v1.42.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00059d340, {0x23f46c0, 0xc009d2af00}, 0xc0003d1440, 0x0)
	google.golang.org/grpc@v1.42.0/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.42.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.42.0/server.go:919 +0x294
```

</details>

How does it happen that all the stats requests are blocked behind this? (you can see from the time listed on some of the semacquires they've been there a while). My guess is something like a pod being deleted at the same time stats happen to be digging into its contents and then a deadlock(?). In our case we can end up with the overlay having quite a difference to the original container, so it makes sense it could take some time to look at the contents.

In the goroutine stack linked above there's also a goroutine blocked on RemoveStatsForSandbox:

```
        sync.(*Mutex).Lock(...) sync/mutex.go:81
        github.com/cri-o/cri-o/internal/lib/stats.(*StatsServer).RemoveStatsForSandbox(0xc0002a13b0, 0xc00b3a8e00)
	github.com/cri-o/cri-o/internal/lib/stats/stats_server.go:287 +0x58
github.com/cri-o/cri-o/internal/lib.(*ContainerServer).RemoveSandbox
```

which further means things are blocked on the ContainerServer mutex, which explains even AddSandbox blocking.

(I'm also curious how this stats call is happening, we don't have PodAndContainerStatsFromCRI enabled.)

**Comment by dgl** [comment]
Given /var/run is a symlink to /run I think we can update the crio.sock to /var/run to workaround this *very* surprising behaviour.
