### ISSUE TITLE
Support Debian 12

### ISSUE THREAD

**Issue by alexstaeding** [cri-o/cri-o#7040]
Debian 12 "bookworm" has been [released](https://www.debian.org/News/2023/20230610).

Following from #5598 and #5599, add the `Debian_12` OS variable to the installation instructions and [download.opensuse.org/repositories](https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.27/).

**Comment by haircommander** [comment]
OBS doesn't yet have support for debian 12, so this will have to wait until it does

**Comment by haircommander** [comment]
I have just toggled the knob for debian 12 in 1.25-1.27
