### ISSUE TITLE
Error: Kubelet may be retrying requests that are timing out in CRI-O due to system load context deadline exceeded: error reserving ctr name

### ISSUE THREAD

**Issue by vjvel** [cri-o/cri-o#7044]
We are getting the below error while mount the pvc volume for the minio. This pvc has 1.7TB and 900GB of data. it not mounting to the pod and container is failed to start with below error. 

 ----     ------  ----                    ----     -------
  Normal   Pulled  47m (x77 over 3h35m)    kubelet  Container image "minio/minio:RELEASE.2021-10-06T23-36-31Z" already present on machine
  Warning  Failed  5m22s (x53 over 3h33m)  kubelet  Error: context deadline exceeded
  Warning  Failed  53s (x36 over 149m)     kubelet  (combined from similar events): Error: Kubelet may be retrying requests that are timing out in CRI-O due to system load: context deadline exceeded: error reserving ctr name k8s_minio_data-analytics-prod-pool-0-3_oci-prod-data-analytics_8dec4302-e6b4-4874-9a60-ea305b96347f_0 for id 8424e8fdc1a42daec5810b43a8baf7a9a80f7835a843fc104fe9f621a14983cb: name is reserved

**Comment by haircommander** [comment]
btw this is more of a cri-o issue, so I've moved it here

in newer cri-o's, there is a message in the logs that says the stage the container or pod creation is stuck at. I see it's not been released in 1.24 yet. I'm planning on doing a new 1.24 release this week which will hopefully be the last one on that minor version. If you upgrade to that, you can see the stage it's stuck at, which will help determine the issue

as a note: the `TrySkipVolumeSELinuxLabel` annotation only works if the volume is correctly labeled. this will happen automatically on a container restart, but would need to be done manually for the first time. you can manually set the selinuxOptions in the pod spec, and then pre-label the volume if you'd like

**Comment by jdbarnes-isi** [comment]
Does this mean that even if we fix this for now we will have problems if we end up re-deploying the app and the PVC tries to label it for the first time again?

**Comment by haircommander** [comment]
or unless the same selinux labels are chosen for the pod. they're generated randomly by cri-o unless they're set statically in the pod spec

**Comment by jdbarnes-isi** [comment]
OK, thank you. that's helpful. Should we just presume to choose an arbitrary value (s0,cNNN,cPPP) and manually set it on our container specs in order to avoid the relabeling delays going forward? It was not an issue until we re-deployed and had to mount from scratch again, but then the error exhibited constantly until we found the issue ticket. Also, is there any way to tell k8s/crio to accept the cost of a secure filesystem relabel (at least once)? 

Finally, thanks for the patch/update that notes the stuck position. Really appreciate that and it will be extremely helpful for us :).

**Comment by haircommander** [comment]
> Also, is there any way to tell k8s/crio to accept the cost of a secure filesystem relabel (at least once)?

crio and kubelet should be doing this now. There will be some alerts through the system (they should appear every 4 minutes while the initial creation is stuck) but crio should be doing its best to do that relabel only once per new container creation. Kubelet complaining about it should mostly be noise

**Comment by wayden88** [comment]
Quick question regarding this issue—are there any fixes or patches available? The customer is still experiencing the issue in the Azure Red Hat OpenShift environment. Please let me know if there are any updates.
