### ISSUE TITLE
Failed to kill container with error - failed to get container 'stopped' status

### ISSUE THREAD

**Issue by sunil-barhate** [cri-o/cri-o#7053]
### What happened?

1. Create statefulSet.
2. After sometime scale down the statefulSet.
3. Pod stuck in Terminating state forever.
4. Pod stuck in terminating state because the container is still in running state.

### What did you expect to happen?

Pod should have been deleted.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create statefulSet.
2. Scale down the statefulSet
3. Issue will occur if not then scale up statefulSet and retry step 1 and 2.

### CRI-O and Kubernetes version

<details>

```console
$ $ crio --version
crio version 1.25.3
Version:        1.25.3
GitCommit:      unknown
GitCommitDate:  unknown
GitTreeState:   clean
BuildDate:      2023-04-17T06:03:55Z
GoVersion:      go1.19
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:      
  rpm_crashtraceback
  exclude_graphdriver_btrfs
  btrfs_noversion
  exclude_graphdriver_devicemapper
  libdm_no_deferred_remove
  seccomp
  containers_image_openpgp
LDFlags:          -X github.com/cri-o/cri-o/internal/pkg/criocli.DefaultsPath= -X  github.com/cri-o/cri-o/internal/version.buildDate=2023-04-17T06:03:55Z -X  github.com/cri-o/cri-o/internal/version.gitCommit=592efcda1042c3f675b0299757a51450d38458ea -X  github.com/cri-o/cri-o/internal/version.version=1.25.3 -X  github.com/cri-o/cri-o/internal/version.gitTreeState=clean  -B 0x556ca6f7ed5d0984fcdcc050604df283750a8c04 -extldflags '-Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld ' -compressdwarf=false
SeccompEnabled:   true
AppArmorEnabled:  false
Dependencies: 
```

```console
$ kubectl version --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "25",
    "gitVersion": "v1.25.10",
    "gitCommit": "e770bdbb87cccdc2daa790ecd69f40cf4df3cc9d",
    "gitTreeState": "clean",
    "buildDate": "2023-05-17T14:12:20Z",
    "goVersion": "go1.19.9",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v4.5.7",
  "serverVersion": {
    "major": "1",
    "minor": "25",
    "gitVersion": "v1.25.10",
    "gitCommit": "e770bdbb87cccdc2daa790ecd69f40cf4df3cc9d",
    "gitTreeState": "clean",
    "buildDate": "2023-05-17T14:06:35Z",
    "goVersion": "go1.19.9",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}

```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.6 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.6 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
$ uname -a
Linux appserv51 4.18.0-372.9.1.el8.x86_64 #1 SMP Tue May 10 14:48:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
Physical machines
</details>

**Comment by sunil-barhate** [comment]
1. Pod in terminating state

fio-sts-local-7   1/1     Terminating   0          17h

2. Pod description

$ kubectl  describe pod fio-sts-local-7 
Name:                      fio-sts-local-7
Namespace:                 default
Priority:                  0
Service Account:           default
Node:                      appserv51/172.16.6.151
Start Time:                Wed, 14 Jun 2023 06:18:16 -0700
Labels:                    app=fio-local
                           controller-revision-hash=fio-sts-local-65646fdd66
                           statefulset.kubernetes.io/pod-name=fio-sts-local-7
Annotations:               <none>
Status:                    Terminating (lasts 14h)
Termination Grace Period:  30s
IP:                        
IPs:                       <none>
Controlled By:             StatefulSet/fio-sts-local
Containers:
  fio-sts-local:
    Container ID:   cri-o://4bbbc006f606958022cb32f65bdbd0b64159e1247142d34ee43b395cad213207
    Image:          diamanti/fio:v1.0
    Image ID:       9f2af5fa4682b314348a3a1fe46191352c38e2a0e31959ef287069c52ee4c9cd
    Port:           <none>
    Host Port:      <none>
    **State:          Running**
      Started:      Wed, 14 Jun 2023 06:18:26 -0700
    Ready:          True
    Restart Count:  0
    Environment:
      SIZE:  5G
      RW:    randrw
      RT:    86400
    Mounts:
      /data from data-local (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-blpfq (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  data-local:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-local-fio-sts-local-7
    ReadOnly:   false
  kube-api-access-blpfq:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason         Age                  From     Message
  ----     ------         ----                 ----     -------
  Normal   Killing        30m (x574 over 12h)  kubelet  Stopping container fio-sts-local
  Warning  FailedMount    20m (x357 over 12h)  kubelet  MountVolume.SetUp failed for volume "pvc-a505952a-2f19-4c86-8226-442689c2d9f8" : rpc error: code = Internal desc = [pvc-a505952a-2f19-4c86-8226-442689c2d9f8] Failed to patch volume attachment with error: Volume "pvc-a505952a-2f19-4c86-8226-442689c2d9f8" Attach failed: Volume "pvc-a505952a-2f19-4c86-8226-442689c2d9f8" attachment c2dec5e2-0aa8-11ee-b118-a4bf01147f07 patching failed. Volume is in down state
  Warning  FailedKillPod  23s (x598 over 12h)  kubelet  error killing pod: [failed to "KillContainer" for "fio-sts-local" with KillContainerError: "rpc error: code = Unknown desc = failed to get container 'stopped' status 4bbbc006f606958022cb32f65bdbd0b64159e1247142d34ee43b395cad213207: failed to get container stopped status: 30s timeout reached", failed to "KillPodSandbox" for "6897cf5f-e73f-43ab-8068-7843f4cc9aaf" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to stop container for pod sandbox 2f2c5585344a94eddce318399e51081f6547466202b755f6057d2f624bc38b81: failed to get container 'stopped' status k8s_fio-sts-local_fio-sts-local-7_default_6897cf5f-e73f-43ab-8068-7843f4cc9aaf_0: failed to get container stopped status: 30s timeout reached"]

3. Kubelete logs,

$ journalctl -u kubelet.service -f | grep 4bbbc006f606958022cb32f65bdbd0b64159e1247142d34ee43b395cad213207
Jun 14 23:44:35 appserv51 kubelet[3673966]: I0614 23:44:35.383984 3673966 kuberuntime_container.go:702] "Killing container with a grace period" pod="default/fio-sts-local-7" podUID=6897cf5f-e73f-43ab-8068-7843f4cc9aaf containerName="fio-sts-local" containerID="cri-o://4bbbc006f606958022cb32f65bdbd0b64159e1247142d34ee43b395cad213207" gracePeriod=30
Jun 14 23:45:05 appserv51 kubelet[3673966]: E0614 23:45:05.385100 3673966 remote_runtime.go:505] "StopContainer from runtime service failed" err="rpc error: code = Unknown desc = failed to get container 'stopped' status 4bbbc006f606958022cb32f65bdbd0b64159e1247142d34ee43b395cad213207: failed to get container stopped status: 30s timeout reached" containerID="4bbbc006f606958022cb32f65bdbd0b64159e1247142d34ee43b395cad213207"
Jun 14 23:45:05 appserv51 kubelet[3673966]: E0614 23:45:05.385157 3673966 kuberuntime_container.go:707] "Container termination failed with gracePeriod" err="rpc error: code = Unknown desc = failed to get container 'stopped' status 4bbbc006f606958022cb32f65bdbd0b64159e1247142d34ee43b395cad213207: failed to get container stopped status: 30s timeout reached" pod="default/fio-sts-local-7" podUID=6897cf5f-e73f-43ab-8068-7843f4cc9aaf containerName="fio-sts-local" containerID="cri-o://4bbbc006f606958022cb32f65bdbd0b64159e1247142d34ee43b395cad213207" gracePeriod=30
Jun 14 23:45:05 appserv51 kubelet[3673966]: E0614 23:45:05.385184 3673966 kuberuntime_container.go:732] "Kill container failed" err="rpc error: code = Unknown desc = failed to get container 'stopped' status 4bbbc006f606958022cb32f65bdbd0b64159e1247142d34ee43b395cad213207: failed to get container stopped status: 30s timeout reached" pod="default/fio-sts-local-7" podUID=6897cf5f-e73f-43ab-8068-7843f4cc9aaf containerName="fio-sts-local" containerID={Type:cri-o ID:4bbbc006f606958022cb32f65bdbd0b64159e1247142d34ee43b395cad213207}

4. crio logs,

Jun 14 23:50:37 appserv51 crio[3673640]: time="2023-06-14 23:50:37.383837278-07:00" level=info msg="Stopping container: 4bbbc006f606958022cb32f65bdbd0b64159e1247142d34ee43b395cad213207 (timeout: 30s)" id=b50aed30-a7c2-4efb-83dc-3c5667da2c74 name=/runtime.v1.RuntimeService/StopContainer
Jun 14 23:51:07 appserv51 crio[3673640]: time="2023-06-14 23:51:07.385586828-07:00" level=info msg="Stopping pod sandbox: 2f2c5585344a94eddce318399e51081f6547466202b755f6057d2f624bc38b81" id=a663cf12-f3f6-4467-846d-43dcd51ba0f7 name=/runtime.v1.RuntimeService/StopPodSandbox
Jun 14 23:51:51 appserv51 crio[3673640]: time="2023-06-14 23:51:51.384687150-07:00" level=info msg="Stopping container: 4bbbc006f606958022cb32f65bdbd0b64159e1247142d34ee43b395cad213207 (timeout: 30s)" id=1b142fe3-bdf0-4917-b220-c61228f3a548 name=/runtime.v1.RuntimeService/StopContainer
Jun 14 23:52:21 appserv51 crio[3673640]: time="2023-06-14 23:52:21.385688044-07:00" level=info msg="Stopping pod sandbox: 2f2c5585344a94eddce318399e51081f6547466202b755f6057d2f624bc38b81" id=1c5e89ee-f893-44c2-b099-d09f881b63cf name=/runtime.v1.RuntimeService/StopPodSandbox
Jun 14 23:53:06 appserv51 crio[3673640]: time="2023-06-14 23:53:06.383993888-07:00" level=info msg="Stopping container: 4bbbc006f606958022cb32f65bdbd0b64159e1247142d34ee43b395cad213207 (timeout: 30s)" id=b354e6f5-f3d4-42cb-b9ce-f969403b17a5 name=/runtime.v1.RuntimeService/StopContainer
Jun 14 23:53:36 appserv51 crio[3673640]: time="2023-06-14 23:53:36.385199346-07:00" level=info msg="Stopping pod sandbox: 2f2c5585344a94eddce318399e51081f6547466202b755f6057d2f624bc38b81" id=152e8ce7-e598-4d32-bbb2-153972f5c37c name=/runtime.v1.RuntimeService/StopPodSandbox
Jun 14 23:54:05 appserv51 crio[3673640]: time="2023-06-14 23:54:05.834956122-07:00" level=info msg="Checking image status: registry.k8s.io/pause:3.8" id=e74ea029-d880-4ca4-896b-19d0a6fd19cc name=/runtime.v1.ImageService/ImageStatus
Jun 14 23:54:05 appserv51 crio[3673640]: time="2023-06-14 23:54:05.835270937-07:00" level=info msg="Image registry.k8s.io/pause:3.8 not found" id=e74ea029-d880-4ca4-896b-19d0a6fd19cc name=/runtime.v1.ImageService/ImageStatus
Jun 14 23:54:18 appserv51 crio[3673640]: time="2023-06-14 23:54:18.384204374-07:00" level=info msg="Stopping container: 4bbbc006f606958022cb32f65bdbd0b64159e1247142d34ee43b395cad213207 (timeout: 30s)" id=d476cf99-7e88-4359-b30a-cd5231b57a01 name=/runtime.v1.RuntimeService/StopContainer


5. crictl ps output,
$ sudo crictl ps | grep fio
4bbbc006f6069       docker.io/diamanti/fio@sha256:6f47ab2dd0ee3ed33feb2714d64211dc30169f297f47d9eba9d5829418151540                                  18 hours ago        Running             fio-sts-local              0                   2f2c5585344a9

6. crictl inspect output file attached.
[crictl-inspect-output.txt](https://github.com/cri-o/cri-o/files/11754010/crictl-inspect-output.txt)

**Comment by haircommander** [comment]
hm why are you using cri-o 1.23 with kubelet 1.25? also, can we have the crio config?

**Comment by sunil-barhate** [comment]
It is also reproducible with cri-o 1.25 with kubelet 1.25.

attaching the crio.conf
[crio.txt](https://github.com/cri-o/cri-o/files/11828959/crio.txt)

**Comment by sunil-barhate** [comment]
any update on this?

**Comment by haircommander** [comment]
unfortunately not yet though I've heard this reported elsewhere too and am directing some attention at it
