### ISSUE TITLE
Update OpenSUSE (zypper) package?

### ISSUE THREAD

**Issue by dominic-p** [cri-o/cri-o#7072]
I'm trying to get started with cri-o on MicroOS, and it looks like the most recent release available for that platform is 1.24 (see [package repo here](https://mirrorcache-us.opensuse.org/tumbleweed/repo/oss/x86_64/) or just run `zypper info cri-o`).

Is there any way we can get an updated release for OpenSUSE?

**Comment by haircommander** [comment]
@saschagrunert are you able to do this?

**Comment by saschagrunert** [comment]
I think it's still inferred from kubic: https://build.opensuse.org/package/show/devel:kubic/cri-o 

We don't actually maintain those packages. Or do we want to add opensuse distributions to https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable:cri-o:1.27 ?

**Comment by dominic-p** [comment]
Thanks for looking into this. I'm actually considering abandoning MicroOS in favor of Debian, but again, it looks like the the most recent build available is 1.24.

Maybe I'm reading the [install instructions](https://github.com/cri-o/cri-o/blob/main/install.md#apt-based-operating-systems) wrong (also on [cri-o.io](https://cri-o.io/))? I apologize if I'm missing something obvious.

**Comment by haircommander** [comment]
nope you're not reading that incorrectly: the docs are out of date. If openSUSE isn't going to update cri-o again we may want to drop the installation instructions to prevent future confusion. 

@dominic-p since you found it, would you like the honor of updating the documentation?

**Comment by dominic-p** [comment]
Thanks for the update. PR incoming on the doc update, but I'm not 100% sure I understand the current situation with Debian.

Is it up to openSUSE to provide a build for Debian 12 (as well as Stable/Testing) or is the CRI-O team in charge of that and we're just using the openSUSE build service?

I guess it doesn't matter either way in terms of the install instructions, but it would be good to know if Debian will be a supported platform going forward.

**Comment by haircommander** [comment]
yeah it's out of our control which operating systemds OBS supports, but we add support for any that a user asks for that is available (assuming less than a certain amount of work is required to support it)

**Comment by dominic-p** [comment]
Thanks for the explanation there. I did some digging, and it looks like Debian 12 has [recently been added](https://lists.opensuse.org/archives/list/buildservice@lists.opensuse.org/thread/C2XZW24F6VM5ZYB47Y7N24BUYNMCNH4D/) as a build target to OBS. So, that's a good sign.

Could we consider this a user asking for that platform to be supported? :)

**Comment by haircommander** [comment]
heard! I have added the builds to 1.25-1.27. Lemme know if they don't show up in an hour or so

**Comment by dominic-p** [comment]
Thank you so much! I really appreciate that.

Should I add Debian 12 to the tables I just modified in the previous PRs?

**Comment by dominic-p** [comment]
Done. Thanks again for your help on this!

I guess once the doc update PRs are merged we can close this, but I'll leave that up to you.
