### ISSUE TITLE
install.md not working for CentOS 9 Stream

### ISSUE THREAD

**Issue by g1lby** [cri-o/cri-o#7098]
### What happened?

I was following the install guide at https://github.com/cri-o/cri-o/blob/main/install.md#readme because I was looking for a Kubernetes compatible container-runtime to proceed with my setup of a K8s cluster.

It seems like there is an issue at the opensuse-mirror (or a typo in the url?), if the environment variable is set to `OS=CentOS_9_Stream`, as described in step "Install packaged versions of CRI-O".
The file populated via 
`curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/devel:kubic:libcontainers:stable.repo`
looks like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>Resource is no longer available!</title>
<link rev="made" href="mailto:webmaster@opensuse.org" />
<style type="text/css"><!--/*--><![CDATA[/*><!--*/
    body { color: #000000; background-color: #FFFFFF; }
    a:link { color: #0000CC; }
    p, address {margin-left: 3em;}
    span {font-size: smaller;}
/*]]>*/--></style>
</head>
<body>
<h1>Resource is no longer available!</h1>
<p>
    The requested URL is no longer available on this server and there is no
    forwarding address.
    If you followed a link from a foreign page, please contact the
    author of this page.
</p>
<p>
If you think this is a server error, please contact
the <a href="mailto:webmaster@opensuse.org">webmaster</a>.
</p>
<h2>Error 404</h2>
<address>
  <a href="/">download.opensuse.org</a><br />
  <span>Apache</span>
</address>
</body>
</html>
```

Therefore, I can't proceed with the install-guide for obvious reasons... :)
`Warning: failed loading '/etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.27.repo', skipping.`

### What did you expect to happen?

Expecting a folder for CentOS_9_Stream here: 
[http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/](http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/)

Working `yum install` command, correct URLs for downloading the yum repolist.

### How can we reproduce it (as minimally and precisely as possible)?

On a CentOS 9 Stream server:

`export OS=CentOS_9_Stream`
`export VERSION=1.27`
`curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/devel:kubic:libcontainers:stable.repo`

and/or verify the opensuse mirror missing the CentOS_9_Stream distro:
http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/

### Anything else we need to know?

I was just checking the CentOS_8_Stream location instead and saw, that this repo contains these packages: 

```
buildah-1.22.3-1.el8.7.2.x86_64.rpm
buildah-tests-1.22.3-1.el8.7.2.x86_64.rpm
catatonit-0.1.5-1.el8.6.2.x86_64.rpm
conmon-2.1.2-1.1.1.x86_64.rpm
containernetworking-plugins-1.1.1-1.el8.2.7.x86_64.rpm
containernetworking-plugins-unit-test-devel-1.1.1-1.el8.2.7.x86_64.rpm
cri-tools-1.24.0-.el8.1.8.x86_64.rpm
crun-0.20.1-1.el8.3.47.x86_64.rpm
fuse-overlayfs-1.5.0-1.el8.5.6.x86_64.rpm
golang-github-cpuguy83-go-md2man-1.0.7-13.el8.14.100.x86_64.rpm
runc-1.0.1-1.el8.1.6.x86_64.rpm
skopeo-1.4.1-1.el8.3.1.x86_64.rpm
skopeo-tests-1.4.1-1.el8.3.1.x86_64.rpm
```

Since I'm just at the beginning of my Kubernetes journey, I was wondering: The install.md says that cri-o doesn't need the `containernetworking-plugins` anymore, but do I need them or anything else from this repository if I'm installing a K8s cluster from scratch? Plus I already installed `buildah-1.30.0-2.el9.x86_64` as well as `skopeo-1.12.0-3.el9.x86_64` from the appstream repo.

I'm really new to this and want to learn for a production environment, sorry if any question seems stupid.

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
-bash: crio: command not found
```

```console
$ kubectl version --output=json
-bash: kubectl: command not found
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release

NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

$ uname -a
Linux ct-00.<hostname_redacted>.com 5.14.0-331.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jun 22 15:26:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
AWS EC2
</details>

**Comment by haircommander** [comment]
I've attempted to add it to the repo. Let me know in an hour or so if it didn't work!

**Comment by g1lby** [comment]
Awesome, thanks so much for the quick fix!
