### ISSUE TITLE
Support more CNI plugin capabilities

### ISSUE THREAD

**Issue by welsper-young** [cri-o/cri-o#7122]
Is there any plan to support below CNI plugin capability?
`"capabilities": {
     "io.kubernetes.cri.pod-annotations": true
}`
This capability allows pass Pod annotations to CNI plugin.
Like (https://github.com/kubernetes/kubernetes/issues/69882#issuecomment-1509077177)

**Comment by welsper-young** [comment]
Thanks for your brilliant work!

**Comment by haircommander** [comment]
@welsper-young would you be willing to test a PR with the new ocicni version merged to make sure it works as you'd expect?

**Comment by welsper-young** [comment]
> @welsper-young would you be willing to test a PR with the new ocicni version merged to make sure it works as you'd expect?

Well, i test the capability on my toy kubernetes cluster, and it doesn't work.
I have a demo cni plugin which just prints the stdin args, and i configure it with `"capabilities": { "io.kubernetes.cri.pod-annotations": true }`. What i expected is the pod annotations can be found in the log. However, nothing appeared and the runtimeConfig filed was even nil.
So, I view the codes for setting up pod network. And i found the pod annotations are never set to the runtimeConfig.
And i try set the pod annotations in below segements, and finally it works as expected.
https://github.com/cri-o/cri-o/blob/3113dd23e0e9a0367b373cd5e550c270a9d367d4/server/sandbox_network.go#L232-L246
Below is what I changed:
```
	network := s.config.CNIPlugin().GetDefaultNetworkName()
	podAnnotations := sb.Annotations()
	return ocicni.PodNetwork{
		Name:      sb.KubeName(),
		Namespace: sb.Namespace(),
		UID:       sb.Metadata().Uid,
		Networks:  []ocicni.NetAttachment{},
		ID:        sb.ID(),
		NetNS:     sb.NetNsPath(),
		RuntimeConfig: map[string]ocicni.RuntimeConfig{
			network: {
				Bandwidth:      bwConfig,
				CgroupPath:     sb.CgroupParent(),
				PodAnnotations: &podAnnotations,
			},
		},
	}, nil
```

**Comment by sohankunkerkar** [comment]
@welsper-young Certainly! I have been working on fixing the issue and have made progress with testing. However, due to the emergence of some high-priority tasks, I had to pause my efforts temporarily. Are you interested in contributing by creating a PR for it?

**Comment by welsper-young** [comment]
> @welsper-young Certainly! I have been working on fixing the issue and have made progress with testing. However, due to the emergence of some high-priority tasks, I had to pause my efforts temporarily. Are you interested in contributing by creating a PR for it?

OK! The ocicni version should be updated to the latest, right? Is this behavior safe?

**Comment by sohankunkerkar** [comment]
> > @welsper-young Certainly! I have been working on fixing the issue and have made progress with testing. However, due to the emergence of some high-priority tasks, I had to pause my efforts temporarily. Are you interested in contributing by creating a PR for it?
> 
> OK! The ocicni version should be updated to the latest, right? Is this behavior safe?

Yeah, that's a good point. How about you vendor the main branch from `ocicni` and try adding this code with bats tests for CI testing?

**Comment by haircommander** [comment]
I think vendoring from latest main is safe. The code moves very slowly

**Comment by saschagrunert** [comment]
We can cut a new ocicni release once the tests are green in the PR. This way we can ensure that we release only working bits.

**Comment by MaoJianwei** [comment]
I need this too, when it will be released by kubernetes?

a CNI plugin cannot get any annotations about the pod/deployment from the stdin at all, now, at 1.28.2 version.

many thanks

**Comment by MaoJianwei** [comment]
could you please make this change for 'networkStop' and 'newPodNetwork' functions? for cmdAdd and cmdDel.

thanks @welsper-young @LenkaSeg
