### ISSUE TITLE
Remove sonatype-lift scanner

### ISSUE THREAD

**Issue by saschagrunert** [cri-o/cri-o#7150]
The service is being shut down in the future. Can we remove it from this repository?

![screenshot](https://github.com/cri-o/cri-o/assets/695473/2746258a-e75a-431b-9640-aaa7ae7de1a4)

**Comment by Pushkarm029** [comment]
hey @saschagrunert Please assign me this issue

**Comment by iuriatan** [comment]
From [lift docs](https://help.sonatype.com/lift/using-lift#UsingLift-lift-in-pull-requests), it seems it's all set up in Sonatype Lift's console:
> When visiting [the Lift Console](https://lift.sonatype.com/), you will see a list showing all repositories the Lift app is installed on.
> From this screen, you can select any repository for Lift to get started analyzing.
> Even without a repository scan, repositories with Lift installed will be analyzed every time you create a pull request in GitHub as described below.

Am I right? I'd be glad to handle this if it's a matter of commit/merge. Can you add any instructions?

**Comment by haircommander** [comment]
correct, it needed an admin. I've removed it
