### ISSUE TITLE
image pull time

### ISSUE THREAD

**Issue by paneda1998** [cri-o/cri-o#7161]
Hi
I need some metrics to understand the time spend on pulling each image by name

i need this to prepare sli and slo for my k8s cluster
also need to understand average time of pulling image in each cluster and ...

**Comment by saschagrunert** [comment]
Hey @paneda1998, thank you for the request. We only have all metrics here: https://github.com/cri-o/cri-o/blob/main/tutorials/metrics.md

Metrics "by name" tend to have a high cardinality which is why we deprecated them.

**Comment by paneda1998** [comment]
Hey again
thanks.
