### ISSUE TITLE
`GetContainerEvents()` succeeds, but next `Recv()` returns EOF.

### ISSUE THREAD

**Issue by thediveo** [cri-o/cri-o#7164]
### What happened?

Background: I'm in the process of adding CRI support to a [Go module for tracking container workloads](https://github.com/thediveo/whalewatcher/blob/feature/cri-o/engineclient/cri/) ("whalewatcher"). This module is ultimately used in the [Siemens Edgeshark](https://github.com/siemens/edgeshark) application for diagnosing virtual container communication.

For the workload tracking (=running containers) I'm using the `GetContainerEvents()` call on the CRI runtime service API; this (remote) call succeeds for both cri-o 1.26 as well as for containerd 1.7.x; this returns a `runtimev1.RuntimeService_GetContainerEventsClient`.

However, when next calling `Recv()` on this container events client, it returns an EOF error for cri-o, whereas containerd correctly blocks and sends container events as they become available.

### What did you expect to happen?

Calling `Recv()` on a container events client returned by `GetContainerEvents` returns container events without any error, but not an "EOF" error.

### How can we reproduce it (as minimally and precisely as possible)?

- Docker CE needs to be locally installed; tested with 24.0, but any decent recent version should suffice.
- Go 1.20.6 installed.
- check out github.com/thediveo/whalewatcher at [commit fe8e7db548ecf89bd0332571760974421d787aa5](https://github.com/thediveo/whalewatcher/commit/fe8e7db548ecf89bd0332571760974421d787aa5).
- in the repo's toplevel directory, run `go test -v -exec sudo ./engineclient/cri -ginkgo.v`

This test should abort with the following error message:

```console
CRI API [It] watches
/home/harald/github/whalewatcher/engineclient/cri/cri_test.go:222

  [FAILED] Unexpected error:
      <*errors.errorString | 0xc0001180f0>: 
      EOF
      {s: "EOF"}
  occurred
  In [It] at: /home/harald/github/whalewatcher/engineclient/cri/cri_test.go:232 @ 07/24/23 13:14:36.46
```

### CRI-O and Kubernetes version

- CRI-O version 1.26 for Debian_11, installed as follows:

```console
OS=Debian_11 && VERSION=1.26 \
    && apt-get update \
    && apt-get install -y --no-install-recommends gnupg \
    && echo "deb [signed-by=/usr/share/keyrings/libcontainers-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /" \
        > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list \
    && echo "deb [signed-by=/usr/share/keyrings/libcontainers-crio-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/ /" \
        > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.list \
    && mkdir -p /usr/share/keyrings \
    && curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key  \
        | gpg --dearmor -o /usr/share/keyrings/libcontainers-archive-keyring.gpg \
    && curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/Release.key \
        | gpg --dearmor -o /usr/share/keyrings/libcontainers-crio-archive-keyring.gpg \
    && apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y -o Dpkg::Options::="--force-confold" cri-o cri-o-runc \
    && systemctl enable crio
```

### OS version

- host: Ubuntu 23.04 lunar
- container: kindest/base:${KINDEST_BASE_TAG}, FROM debian:bullseye-slim

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by haircommander** [comment]
cc @sairameshv @harche

**Comment by harche** [comment]
@thediveo Thanks for reporting this issue.

**Comment by MdSahil-oss** [comment]
@haircommander I would like to work on it.

**Comment by haircommander** [comment]
as @MdSahil-oss found in https://github.com/cri-o/cri-o/pull/7257, the EOF goes away when you set the cri-o config field to true, did you do this @thediveo ?

**Comment by thediveo** [comment]
@haircommander no, I was totally oblivious to such an engine setting. I would have expected that a CRI API provider denies any attempt to the `GetContainerEvents` method, but never dreamt of it accepting the API call and then turning around a biting its thumb at me when reading the returned event stream...

**Comment by haircommander** [comment]
@MdSahil-oss that could be a good extension, where CRI-O detects whether the config field is specified, and fails on GetContainerEvents with a message saying why

**Comment by thediveo** [comment]
@haircommander @MdSahil-oss can confirm that using cri-o 1.28 in a KinD kindest/base container with the following configuration successfully sends events.

`/etc/crio/crio.conf`:
```toml
[crio.runtime]
enable_pod_events=true
```

Thank you very much for your help! From my perspective my issue is resolved.

Now back to hunting self-made issues in my unit tests and refactoring them so as to run them with both containerd as well as cri-o.

**Comment by thediveo** [comment]
With some refactoring and dealing with slightly different API behavior interpretations between containerd and cri-o now all my unit tests for tracking pod/container workload pass on both container engines.
