### ISSUE TITLE
cri-o cannot pull images from sonatype repository

### ISSUE THREAD

**Issue by zozo6015** [cri-o/cri-o#7174]
### What happened?

I have a private repository configured using nexus sonatype. When I am trying to pull the image from the sonatype I am getting a 404 instead of be able to pull the pull the image.

### What did you expect to happen?

Login to the repository using ImagePullSecret and pull the repository

### How can we reproduce it (as minimally and precisely as possible)?

create a sonatype repository configure docker hosted repository on it. Push an image. Configure a pod on a kubernetes cluster (1.27.0) that uses crio container engine and configure the image to be pulled by the private nexus repository. Alternatively podman has the same issue so you can just use podman.

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.27.0
Version:        1.27.0
GitCommit:      unknown
GitCommitDate:  unknown
GitTreeState:   clean
BuildDate:      2023-04-25T18:11:41Z
GoVersion:      go1.19
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:      
  apparmor
  seccomp
  containers_image_ostree_stub
  exclude_graphdriver_btrfs
  exclude_graphdriver_devicemapper
  containers_image_openpgp
LDFlags:          -s -w -X github.com/cri-o/cri-o/internal/pkg/criocli.DefaultsPath="" -X github.com/cri-o/cri-o/internal/version.buildDate=2023-04-25T18:11:41Z 
SeccompEnabled:   true
AppArmorEnabled:  true
```

```console
$ kubectl version --output=json
#1.27.0
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux idfint-worker3 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
cluster is created on ovh dedicated bare metal nodes with 16 core and 32GB ram cpu
</details>

**Comment by haircommander** [comment]
@mtrmac can you PTAL? it gets a 404 that docker/containerd don't get. some convo is here https://kubernetes.slack.com/archives/CAZH62UR1/p1690269709595609

**Comment by haircommander** [comment]
<details>
<summary>debug logs</summary>
Jul 25 15:37:20 idfint-worker1 crioÄ325889Å: time="2023-07-25 15:37:20.466874524Z" level=debug msg="Request: &ExecSyncRequestäContainerId:e179bba8cd4b9936c72be15eaf18d3d3a7ae57f0f6fbdbe27aa1a3bf5a239f0f,Cmd:Ä/bin/calico-node -felix-ready -bird-readyÅ,Timeout:10,å" file="otel-collector/interceptors.go:62" id=9ca7e0fa-8edc-4dfb-b08b-9b827aa5ed7c name=/runtime.v1.RuntimeService/ExecSync
Jul 25 15:37:20 idfint-worker1 crioÄ325889Å: time="2023-07-25 15:37:20.509968528Z" level=debug msg="Using registries.d directory /etc/containers/registries.d" file="docker/registries_d.go:80"
Jul 25 15:37:20 idfint-worker1 crioÄ325889Å: time="2023-07-25 15:37:20.510316320Z" level=info msg="Trying to access ö"repo.veracityid.com/activemq:5.16.3ö"" file="docker/docker_image_src.go:87"
Jul 25 15:37:20 idfint-worker1 crioÄ325889Å: time="2023-07-25 15:37:20.510382370Z" level=debug msg="Returning credentials for repo.veracityid.com/activemq from DockerAuthConfig" file="config/config.go:274"
Jul 25 15:37:20 idfint-worker1 crioÄ325889Å: time="2023-07-25 15:37:20.510434990Z" level=debug msg=" Lookaside configuration: using ö"default-dockerö" configuration" file="docker/registries_d.go:221"
Jul 25 15:37:20 idfint-worker1 crioÄ325889Å: time="2023-07-25 15:37:20.510488281Z" level=debug msg=" No signature storage configuration found for repo.veracityid.com/activemq:5.16.3, using built-in default file:///var/lib/containers/sigstore" file="docker/registries_d.go:176"
Jul 25 15:37:20 idfint-worker1 crioÄ325889Å: time="2023-07-25 15:37:20.510552980Z" level=debug msg="Looking for TLS certificates and private keys in /etc/docker/certs.d/repo.veracityid.com" file="tlsclientconfig/tlsclientconfig.go:20"
Jul 25 15:37:20 idfint-worker1 crioÄ325889Å: time="2023-07-25 15:37:20.510614478Z" level=debug msg=" Sigstore attachments: using ö"default-dockerö" configuration" file="docker/registries_d.go:254"
Jul 25 15:37:20 idfint-worker1 crioÄ325889Å: time="2023-07-25 15:37:20.510678104Z" level=debug msg="GET https://repo.veracityid.com/v2/" file="docker/docker_client.go:631"
Jul 25 15:37:20 idfint-worker1 crioÄ325889Å: time="2023-07-25 15:37:20.583707398Z" level=debug msg="Received container exit code: 0, message: " file="oci/runtime_oci.go:670" id=9ca7e0fa-8edc-4dfb-b08b-9b827aa5ed7c name=/runtime.v1.RuntimeService/ExecSync
Jul 25 15:37:20 idfint-worker1 crioÄ325889Å: time="2023-07-25 15:37:20.583967205Z" level=debug msg="Response: &ExecSyncResponseäStdout:ÄFILTEREDÅ,Stderr:ÄFILTEREDÅ,ExitCode:0,å" file="otel-collector/interceptors.go:74" id=9ca7e0fa-8edc-4dfb-b08b-9b827aa5ed7c name=/runtime.v1.RuntimeService/ExecSync
Jul 25 15:37:20 idfint-worker1 crioÄ325889Å: time="2023-07-25 15:37:20.727296630Z" level=debug msg="Ping https://repo.veracityid.com/v2/ status 404" file="docker/docker_client.go:834"
Jul 25 15:37:20 idfint-worker1 crioÄ325889Å: time="2023-07-25 15:37:20.727456980Z" level=debug msg="GET https://repo.veracityid.com/v1/_ping" file="docker/docker_client.go:631"
Jul 25 15:37:20 idfint-worker1 crioÄ325889Å: time="2023-07-25 15:37:20.755814961Z" level=debug msg="Ping https://repo.veracityid.com/v1/_ping status 404" file="docker/docker_client.go:864"
Jul 25 15:37:20 idfint-worker1 crioÄ325889Å: time="2023-07-25 15:37:20.756022805Z" level=debug msg="Accessing ö"repo.veracityid.com/activemq:5.16.3ö" failed: pinging container registry repo.veracityid.com: StatusCode: 404, ön<!DOCTYPE html>ön<html lang=ö"enö">ön<head>ön  <title>..." file="docker/docker_image_src.go:95"
Jul 25 15:37:20 idfint-worker1 crioÄ325889Å: time="2023-07-25 15:37:20.756188781Z" level=debug msg="Error preparing image repo.veracityid.com/activemq:5.16.3: pinging container registry repo.veracityid.com: StatusCode: 404, ön<!DOCTYPE html>ön<html lang=ö"enö">ön<head>ön  <title>..." file="server/image_pull.go:148" id=16c9beab-144d-4b48-8929-f82f24f99d40 name=/runtime.v1.ImageService/PullImage
Jul 25 15:37:20 idfint-worker1 crioÄ325889Å: time="2023-07-25 15:37:20.756345633Z" level=debug msg="Response error: pinging container registry repo.veracityid.com: StatusCode: 404, ön<!DOCTYPE html>ön<html lang=ö"enö">ön<head>ön  <title>..." file="otel-collector/interceptors.go:71" id=16c9beab-144d-4b48-8929-f82f24f99d40 name=/runtime.v1.ImageService/PullImage
Jul 25 15:37:20 idfint-worker1 crioÄ325889Å: time="2023-07-25 15:37:20.834389507Z" level=debug msg="Request: &ListPodSandboxRequestäFilter:nil,å" file="otel-collector/interceptors.go:62" id=41ca4793-b0dd-4e2d-bbb7-022ceb75aace name=/runtime.v1.RuntimeService/ListPodSandbox
Jul 25 15:37:20 idfint-worker1 crioÄ325889Å: time="2023-07-25 15:37:20.835085722Z" level=debug msg="Response: &ListPodSandboxResponseäItems:ÄÅ*PodSandboxä&PodSandboxäId:f1d5be70f899fe72b1279c074fa8f1b63c57b30a6e3db1767981b2426c341b2a,Metadata:&PodSandboxMetadataäName:activemq-5dbcdfd48d-qqtjc,Uid:f8e56015-0009-4f09-a3ca-ab0ad4078a0c,Namespace:idfint,Attempt:0,å,State:SANDBOX_READY,CreatedAt:1690299266512947912,Labels:mapÄstringÅstringäapp: amq,io.kubernetes.container.name: POD,io.kubernetes.pod.name: activemq-5dbcdfd48d-qqtjc,io.kubernetes.pod.namespace: idfint,io.kubernetes.pod.uid: f8e56015-0009-4f09-a3ca-ab0ad4078a0c,pod-template-hash: 5dbcdfd48d,tier: backend,type: queue,å,Annotations:mapÄstringÅstringäkubernetes.io/config.seen: 2023-07-25T15:34:26.165713443Z,kubernetes.io/config.source: api,å,RuntimeHandler:,å,&PodSandboxäId:5ad6c5a433f4dda3026ecc8467bd919b54747cb09bf223613fdb69399129ad65,Metadata:&PodSandboxMetadataäName:node-shell-e094c397-e5c2-4be2-8160-c013d3691313,Uid:c7079247-ea89-43e4-985f-fa2cdf249368,Namespace:kube-system,Attempt:0,å,State:SANDBOX_READY,CreatedAt:1690298780565634898,Labels:mapÄstringÅstringäio.kubernetes.container.name: POD,io.kubernetes.pod.name: node-shell-e094c397-e5c2-4be2-8160-c013d3691313,io.kubernetes.pod.namespace: kube-system,io.kubernetes.pod.uid: c7079247-ea89-43e4-985f-fa2cdf249368,å,Annotations:mapÄstringÅstringäkubernetes.io/config.seen: 2023-07-25T15:26:20.219446322Z,kubernetes.io/config.source: api,å,RuntimeHandler:,å,&PodSandboxäId:14ec45cefac85d623e51ece80db4bdbc3cced8eabc9d29e0293d49d0cf4b3e8e,Metadata:&PodSandboxMetadataäName:busybox,Uid:5a656ef8-411f-495e-b38f-635d97a683b3,Namespace:default,Attempt:0,å,State:SANDBOX_READY,CreatedAt:1690295265534210797,Labels:mapÄstringÅstringäio.kubernetes.container.name: POD,io.kubernetes.pod.name: busybox,io.kubernetes.pod.namespace: default,io.kubernetes.pod.uid: 5a656ef8-411f-495e-b38f-635d97a683b3,role: busybox,å,Annotations:mapÄstringÅstringäkubectl.kubernetes.io/last-applied-configuration: äö"apiVersionö":ö"v1ö",ö"kindö":ö"Podö",ö"metadataö":äö"annotationsö":äå,ö"labelsö":äö"roleö"ö"busyboxö"å,ö"nameö":ö"busyboxö",ö"namespaceö":ö"defaultö"å,ö"specö":äö"containersö":Ääö"argsö":Äö"while true; do date; sleep 10; doneö"Å,ö"commandö":Äö"shö",ö"-cö"Å,ö"imageö":ö"alpine:latestö",ö"nameö":ö"testö"åÅååön,kubernetes.io/config.seen: 2023-07-25T14:27:45.179524375Z,kubernetes.io/config.source: api,å,RuntimeHandler:,å,&PodSandboxäId:62ec0c6534152c545e8bb20507cf8c8dce7aa0f205b752abbd05753ac1fa4171,Metadata:&PodSandboxMetadataäName:rook-ceph-osd-prepare-idfint-worker1-4cp99,Uid:2dc0d719-42f5-4c32-8910-c17df04860e8,Namespace:rook-ceph,Attempt:0,å,State:SANDBOX_NOTREADY,CreatedAt:1690294583742491338,Labels:mapÄstringÅstringäapp: rook-ceph-osd-prepare,batch.kubernetes.io/controller-uid: 31a7c641-19b1-44e0-a01f-469b8991c757,batch.kubernetes.io/job-name: rook-ceph-osd-prepare-idfint-worker1,ceph.rook.io/pvc: ,controller-uid: 31a7c641-19b1-44e0-a01f-469b8991c757,io.kubernetes.container.name: POD,io.kubernetes.pod.name: rook-ceph-osd-prepare-idfint-worker1-4cp99,io.kubernetes.pod.namespace: rook-ceph,io.kubernetes.pod.uid: 2dc0d719-42f5-4c32-8910-c17df04860e8,job-name: rook-ceph-osd-prepare-idfint-worker1,rook_cluster: rook-ceph,å,Annotations:mapÄstringÅstringäkubernetes.io/config.seen: 2023-07-25T14:16:23.398295087Z,kubernetes.io/config.source: api,å,RuntimeHandler:,å,&PodSandboxäId:6424eb565e8ab4a8ba5d6f232f4d85824101feaf4673305951520b4e321cc060,Metadata:&PodSandboxMetadataäName:rook-ceph-tools-68b98695bb-9vxl8,Uid:1dd3f3ac-1e9a-4a0c-ac26-a03fee0b1062,Namespace:rook-ceph,Attempt:0,å,State:SANDBOX_READY,CreatedAt:1690294257343823275,Labels:mapÄstringÅstringäapp: rook-ceph-tools,io.kubernetes.container.name: POD,io.kubernetes.pod.name: rook-ceph-tools-68b98695bb-9vxl8,io.kubernetes.pod.namespace: rook-ceph,io.kubernetes.pod.uid: 1dd3f3ac-1e9a-4a0c-ac26-a03fee0b1062,pod-template-hash: 68b98695bb,å,Annotations:mapÄstringÅstringäkubernetes.io/config.seen: 2023-07-25T14:10:56.983562421Z,kubernetes.io/config.source: api,å,RuntimeHandler:,å,&PodSandboxäId:58574bd59e36f79e06f40ae69038ba9fe4ca4989640b98adbe5902ed630200ea,Metadata:&PodSandboxMetadataäName:rook-ceph-mgr-b-5fdfb4bb66-tqjwx,Uid:93125f57-da4e-4bf7-b4bd-85ea69e80dbb,Namespace:rook-ceph,Attempt:0,å,State:SANDBOX_READY,CreatedAt:1690294247313452916,Labels:mapÄstringÅstringäapp: rook-ceph-mgr,app.kubernetes.io/component: cephclusters.ceph.rook.io,app.kubernetes.io/created-by: rook-ceph-operator,app.kubernetes.io/instance: b,app.kubernetes.io/managed-by: rook-ceph-operator,app.kubernetes.io/name: ceph-mgr,app.kubernetes.io/part-of: rook-ceph,ceph_daemon_id: b,ceph_daemon_type: mgr,instance: b,io.kubernetes.container.name: POD,io.kubernetes.pod.name: rook-ceph-mgr-b-5fdfb4bb66-tqjwx,io.kubernetes.pod.namespace: rook-ceph,io.kubernetes.pod.uid: 93125f57-da4e-4bf7-b4bd-85ea69e80dbb,mgr: b,mgr_role: active,pod-template-hash: 5fdfb4bb66,rook.io/operator-namespace: rook-ceph,rook_cluster: rook-ceph,å,Annotations:mapÄstringÅstringäkubernetes.io/config.seen: 2023-07-25T14:10:46.941918260Z,kubernetes.io/config.source: api,prometheus.io/port: 9283,prometheus.io/scrape: true,å,RuntimeHandler:,å,&PodSandboxäId:4aa5d3a1f84542407325eade44115dafc409ea3685b26572eff45573b849ea5d,Metadata:&PodSandboxMetadataäName:nfs-nfs-subdir-external-provisioner-8888897cd-jx9vz,Uid:c304c5f8-fd76-4423-9119-1a4636109701,Namespace:kube-system,Attempt:0,å,State:SANDBOX_READY,CreatedAt:1690294197762171653,Labels:mapÄstringÅstringäapp: nfs-subdir-external-provisioner,io.kubernetes.container.name: POD,io.kubernetes.pod.name: nfs-nfs-subdir-external-provisioner-8888897cd-jx9vz,io.kubernetes.pod.namespace: kube-system,io.kubernetes.pod.uid: c304c5f8-fd76-4423-9119-1a4636109701,pod-template-hash: 8888897cd,release: nfs,å,Annotations:mapÄstringÅstringäkubernetes.io/config.seen: 2023-07-25T14:09:56.800751079Z,kubernetes.io/config.source: api,å,RuntimeHandler:,å,&PodSandboxäId:0d2d81694497b237b22d40132b9bd525097055f8180814a54a3a334c1696ceb7,Metadata:&PodSandboxMetadataäName:rook-ceph-operator-bb77fcc55-gfckq,Uid:5222c380-729c-4cf7-b064-5530445249b1,Namespace:rook-ceph,Attempt:0,å,State:SANDBOX_READY,CreatedAt:1690294197184922880,Labels:mapÄstringÅstringäapp: rook-ceph-operator,io.kubernetes.container.name: POD,io.kubernetes.pod.name: rook-ceph-operator-bb77fcc55-gfckq,io.kubernetes.pod.namespace: rook-ceph,io.kubernetes.pod.uid: 5222c380-729c-4cf7-b064-5530445249b1,pod-template-hash: bb77fcc55,å,Annotations:mapÄstringÅstringäkubernetes.io/config.seen: 2023-07-25T14:09:56.802603325Z,kubernetes.io/config.source: api,å,RuntimeHandler:,å,&PodSandboxäId:077c7bb89e3fca1c8b89ed727ddc1129a89622dda2ba5ae6cea81876a84d0fb2,Metadata:&PodSandboxMetadataäName:csi-cephfsplugin-provisioner-86788ff996-ctr27,Uid:1a4760ef-4981-4ecf-904a-5ea0ed1ff1ca,Namespace:rook-ceph,Attempt:0,å,State:SANDBOX_READY,CreatedAt:1690294197152419536,Labels:mapÄstringÅstringäapp: csi-cephfsplugin-provisioner,contains: csi-cephfsplugin-metrics,io.kubernetes.container.name: POD,io.kubernetes.pod.name: csi-cephfsplugin-provisioner-86788ff996-ctr27,io.kubernetes.pod.namespace: rook-ceph,io.kubernetes.pod.uid: 1a4760ef-4981-4ecf-904a-5ea0ed1ff1ca,pod-template-hash: 86788ff996,å,Annotations:mapÄstringÅstringäkubernetes.io/config.seen: 2023-07-25T14:09:56.799685355Z,kubernetes.io/config.source: api,å,RuntimeHandler:,å,&PodSandboxäId:92f3ced984d8a7c0c68920c5d50039e02221fbeda86633f3e91f1c9f5ff1cb5c,Metadata:&PodSandboxMetadataäName:rook-ceph-mon-a-9596b4548-hb7hf,Uid:b9666211-1e92-43f7-befe-7ce22dbf1b16,Namespace:rook-ceph,Attempt:0,å,State:SANDBOX_READY,CreatedAt:1690294178597386509,Labels:mapÄstringÅstringäapp: rook-ceph-mon,app.kubernetes.io/component: cephclusters.ceph.rook.io,app.kubernetes.io/created-by: rook-ceph-operator,app.kubernetes.io/instance: a,app.kubernetes.io/managed-by: rook-ceph-operator,app.kubernetes.io/name: ceph-mon,app.kubernetes.io/part-of: rook-ceph,ceph_daemon_id: a,ceph_daemon_type: mon,io.kubernetes.container.name: POD,io.kubernetes.pod.name: rook-ceph-mon-a-9596b4548-hb7hf,io.kubernetes.pod.namespace: rook-ceph,io.kubernetes.pod.uid: b9666211-1e92-43f7-befe-7ce22dbf1b16,mon: a,mon_cluster: rook-ceph,pod-template-hash: 9596b4548,rook.io/operator-namespace: rook-ceph,rook_cluster: rook-ceph,å,Annotations:mapÄstringÅstringäkubernetes.io/config.seen: 2023-07-25T14:09:38.248020250Z,kubernetes.io/config.source: api,å,RuntimeHandler:,å,&PodSandboxäId:ca22149e92c92bc90e18ba5e5c305cedc0df2812924665325d30acef16ecc0f8,Metadata:&PodSandboxMetadataäName:rook-ceph-crashcollector-idfint-worker1-558d8f876c-dfxgj,Uid:7ee0dd00-78f9-486e-b4d4-f440e2a34b95,Namespace:rook-ceph,Attempt:0,å,State:SANDBOX_READY,CreatedAt:1690294178590913405,Labels:mapÄstringÅstringäapp: rook-ceph-crashcollector,ceph-version: 17.2.6-0,ceph_daemon_id: crash,crashcollector: crash,io.kubernetes.container.name: POD,io.kubernetes.pod.name: rook-ceph-crashcollector-idfint-worker1-558d8f876c-dfxgj,io.kubernetes.pod.namespace: rook-ceph,io.kubernetes.pod.uid: 7ee0dd00-78f9-486e-b4d4-f440e2a34b95,kubernetes.io/hostname: idfint-worker1,node_name: idfint-worker1,pod-template-hash: 558d8f876c,rook_cluster: rook-ceph,å,Annotations:mapÄstringÅstringäkubernetes.io/config.seen: 2023-07-25T14:09:38.246138738Z,kubernetes.io/config.source: api,å,RuntimeHandler:,å,&PodSandboxäId:ae2725b1ed7495e8734b2b00caa4ea66cd7cf16a9ad7377835665d97ad8d34fa,Metadata:&PodSandboxMetadataäName:rook-ceph-osd-0-7ccd7857cd-lw2tk,Uid:788bb09c-e2ba-4371-95d4-4eab4618cd79,Namespace:rook-ceph,Attempt:0,å,State:SANDBOX_READY,CreatedAt:1690294016752978061,Labels:mapÄstringÅstringäapp: rook-ceph-osd,app.kubernetes.io/component: cephclusters.ceph.rook.io,app.kubernetes.io/created-by: rook-ceph-operator,app.kubernetes.io/instance: 0,app.kubernetes.io/managed-by: rook-ceph-operator,app.kubernetes.io/name: ceph-osd,app.kubernetes.io/part-of: rook-ceph,ceph-osd-id: 0,ceph_daemon_id: 0,ceph_daemon_type: osd,device-class: hdd,failure-domain: idfint-worker1,io.kubernetes.container.name: POD,io.kubernetes.pod.name: rook-ceph-osd-0-7ccd7857cd-lw2tk,io.kubernetes.pod.namespace: rook-ceph,io.kubernetes.pod.uid: 788bb09c-e2ba-4371-95d4-4eab4618cd79,osd: 0,pod-template-hash: 7ccd7857cd,portable: false,rook.io/operator-namespace: rook-ceph,rook_cluster: rook-ceph,topology-location-host: idfint-worker1,topology-location-root: default,å,Annotations:mapÄstringÅstringäcni.projectcalico.org/containerID: 4bbd900dda6db937697be90da6efa3401fc7b146206e5747326b420604fe8eb5,cni.projectcalico.org/podIP: ,cni.projectcalico.org/podIPs: ,kubernetes.io/config.seen: 2023-07-25T14:06:41.134625132Z,kubernetes.io/config.source: api,å,RuntimeHandler:,å,&PodSandboxäId:971b8072fbdccad6b9b14e25ee367747f14b00be7ff25714dd2ed845ed7f20c2,Metadata:&PodSandboxMetadataäName:prometheus-prometheus-node-exporter-kqlgw,Uid:3818f58f-b8cc-4cd1-84cc-978dab78bd3b,Namespace:monitoring,Attempt:0,å,State:SANDBOX_READY,CreatedAt:1690294002071082540,Labels:mapÄstringÅstringäapp: prometheus-node-exporter,chart: prometheus-node-exporter-3.3.1,controller-revision-hash: 754cb5b74b,heritage: Helm,io.kubernetes.container.name: POD,io.kubernetes.pod.name: prometheus-prometheus-node-exporter-kqlgw,io.kubernetes.pod.namespace: monitoring,io.kubernetes.pod.uid: 3818f58f-b8cc-4cd1-84cc-978dab78bd3b,jobLabel: node-exporter,pod-template-generation: 1,release: prometheus,å,Annotations:mapÄstringÅstringäcluster-autoscaler.kubernetes.io/safe-to-evict: true,kubernetes.io/config.seen: 2023-07-25T14:06:41.134649856Z,kubernetes.io/config.source: api,å,RuntimeHandler:,å,&PodSandboxäId:26d170bb7cb99e05307bf94add2862bb032da268be9ddcf0b34a83250e3981ab,Metadata:&PodSandboxMetadataäName:csi-rbdplugin-tbmw4,Uid:212176c6-da9c-40cc-809a-9ecbc7548888,Namespace:rook-ceph,Attempt:0,å,State:SANDBOX_READY,CreatedAt:1690294002070737154,Labels:mapÄstringÅstringäapp: csi-rbdplugin,contains: csi-rbdplugin-metrics,controller-revision-hash: 668dcbdc65,io.kubernetes.container.name: POD,io.kubernetes.pod.name: csi-rbdplugin-tbmw4,io.kubernetes.pod.namespace: rook-ceph,io.kubernetes.pod.uid: 212176c6-da9c-40cc-809a-9ecbc7548888,pod-template-generation: 2,å,Annotations:mapÄstringÅstringäkubernetes.io/config.seen: 2023-07-25T14:06:41.134654155Z,kubernetes.io/config.source: api,å,RuntimeHandler:,å,&PodSandboxäId:ef29123c7f8934406b3fae9a68fd9ec77da1966d2cd71bc3b51d26d199f4d167,Metadata:&PodSandboxMetadataäName:csi-cephfsplugin-b5tst,Uid:a5630311-39bc-489f-969b-be64108bf119,Namespace:rook-ceph,Attempt:0,å,State:SANDBOX_READY,CreatedAt:1690294002070181755,Labels:mapÄstringÅstringäapp: csi-cephfsplugin,contains: csi-cephfsplugin-metrics,controller-revision-hash: 569c7b7d97,io.kubernetes.container.name: POD,io.kubernetes.pod.name: csi-cephfsplugin-b5tst,io.kubernetes.pod.namespace: rook-ceph,io.kubernetes.pod.uid: a5630311-39bc-489f-969b-be64108bf119,pod-template-generation: 2,å,Annotations:mapÄstringÅstringäkubernetes.io/config.seen: 2023-07-25T14:06:41.134606977Z,kubernetes.io/config.source: api,å,RuntimeHandler:,å,&PodSandboxäId:3074a2ddf9d51189bf07ecdb1e8b76ec3e5ea0ddc60d62097245a46270f28e7f,Metadata:&PodSandboxMetadataäName:kube-proxy-v2rhm,Uid:5d7a6d43-070e-420c-bc1c-0d223fd0c92d,Namespace:kube-system,Attempt:0,å,State:SANDBOX_READY,CreatedAt:1690294001750576224,Labels:mapÄstringÅstringäcontroller-revision-hash: 56999f657b,io.kubernetes.container.name: POD,io.kubernetes.pod.name: kube-proxy-v2rhm,io.kubernetes.pod.namespace: kube-system,io.kubernetes.pod.uid: 5d7a6d43-070e-420c-bc1c-0d223fd0c92d,k8s-app: kube-proxy,pod-template-generation: 1,å,Annotations:mapÄstringÅstringäkubernetes.io/config.seen: 2023-07-25T14:06:41.134673026Z,kubernetes.io/config.source: api,å,RuntimeHandler:,å,&PodSandboxäId:57295825e99777952d2600a05071ad5a1aac978523221960f7ac3395312622bb,Metadata:&PodSandboxMetadataäName:calico-node-q8rh6,Uid:80c608ef-85b8-4436-8ef2-9bf4a1f888ab,Namespace:kube-system,Attempt:0,å,State:SANDBOX_READY,CreatedAt:1690294001675396783,Labels:mapÄstringÅstringäcontroller-revision-hash: 754b4dfc9f,io.kubernetes.container.name: POD,io.kubernetes.pod.name: calico-node-q8rh6,io.kubernetes.pod.namespace: kube-system,io.kubernetes.pod.uid: 80c608ef-85b8-4436-8ef2-9bf4a1f888ab,k8s-app: calico-node,pod-template-generation: 1,å,Annotations:mapÄstringÅstringäkubernetes.io/config.seen: 2023-07-25T14:06:41.134634073Z,kubernetes.io/config.source: api,å,RuntimeHandler:,å,å,å" file="otel-collector/interceptors.go:74" id=41ca4793-b0dd-4e2d-bbb7-022ceb75aace name=/runtime.v1.RuntimeService/ListPodSandbox
</details>

**Comment by mtrmac** [comment]
I don’t have an account on that Slack instance.

AFAICT from

> `Ping https://repo.veracityid.com/v2/ status 404`

There just isn’t a container registry running on that host[:port], as visible from CRI-O.

**Comment by zozo6015** [comment]
This is a route created based on the user-agent if it's Docker.* or Containerd* then it routes it to the sonatype docker registry.

**Comment by mtrmac** [comment]
Well then, change the route rule? If every single client pretended to be Docker, there would be no point in making decisions based on the user-agent value.

**Comment by zozo6015** [comment]
Can I have the user agents cri-o is using?

**Comment by haircommander** [comment]
@mtrmac do you know the user agent handy?

**Comment by mtrmac** [comment]
https://github.com/cri-o/cri-o/blob/aed4aaafee37877be3825a3c5c155247e08474e1/pkg/config/config.go#L805 ?

But fundamentally switching functionality based on User-Agent is _wrong_. Podman, Buildah, and other software, use their own values.
