### ISSUE TITLE
Verify correctness and performance impact of CRI stats

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#7175]
as we approach a world where CRI-O is collecting the stats and metrics for containers, we need to verify the metrics CRI-O collects are collected accurately and efficiently. This issue is to track that work

**Comment by MdSahil-oss** [comment]
Great @haircommander, The project idea looks relevant to the issue https://github.com/cri-o/cri-o/issues/6747, So working on the issue #6747 will give me more clear understanding of this project idea :)

**Comment by VishSinh** [comment]
Hi, I've been exploring potential projects and I find this issue particularly of interest. I did go over through the issue mentioned by @MdSahil-oss  to gain some more understanding.

I would like to dive more deeper into this. @haircommander  @MdSahil-oss  Can you provide some guidance or initial pointers to help me get started? 

Also if possible I'd like a little brief on the particular issue as to what all should be tracked and what outcomes are expected from this.

**Comment by MdSahil-oss** [comment]
Hi @VishSinh, It's nice to see you here but sadly informing you that I've been preparing to work on this project as an LFX mentee, So it would be better if you look for other LFX projects to get more chances to be selected as a mentee.

**Comment by VishSinh** [comment]
Oh, I see. Yeah, its alright.

**Comment by dims** [comment]
@MdSahil-oss please check the eligibility criteria for a prior participant ... ( https://docs.linuxfoundation.org/lfx/mentorship/mentees )

**Comment by sarthaksarthak9** [comment]
> Hi @VishSinh, It's nice to see you here but sadly informing you that I've been preparing to work on this project as an LFX mentee, So it would be better if you look for other LFX projects to get more chances to be selected as a mentee.
> 
> I hope it makes sense to you :)

you are not yet selected?

**Comment by sarthaksarthak9** [comment]
@haircommander  could you pls share more about this project

**Comment by anirudhprabhakaran3** [comment]
Hi! Wanted to register my interest in this project for the upcoming LFX term. I will come up with a proposal for the same, thanks!

**Comment by AdityaVardhanSingh** [comment]
Hey looking forward to the application, it seems a good project for lfx hoping to connect with mentors and get involved in the project.

**Comment by saschagrunert** [comment]
Added this to our roadmap in blocked state. @haircommander is there any information missing to get started with this? If not, please move it into "Backlog" state.

**Comment by haircommander** [comment]
@Mo-Fatah will work on this :)

**Comment by saschagrunert** [comment]
Can't assign the issue to @Mo-Fatah, so I'm using @haircommander :upside_down_face:
