### ISSUE TITLE
make use of c/storage Check() and Repair() functions

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#7177]
currently, crio wipe checks if the node improperly shut down, and if so just removes the whole image store. this is a very heavy hammer. in https://github.com/containers/storage/pull/1569 @nalind added the abiliity to do consistency checks and repair the OS. We should update crio wipe to utilize them instead of removing the directory.

**Comment by MdSahil-oss** [comment]
@haircommander I would like to work on this :)

**Comment by nalind** [comment]
> currently, crio wipe checks if the node improperly shut down, and if so just removes the whole image store. this is a very heavy hammer. in [containers/storage#1569](https://github.com/containers/storage/pull/1569) @nalind added the abiliity to do consistency checks and repair the OS.

I need to be clear about expectations here - there isn't enough redundancy in how we store layer contents to be able to reliably _repair_ images when we detect that some of their contents have been modified or removed:  in most if not all cases, the repair logic is still going to remove what there is left of the image, with the expectation that it will be pulled again.

**Comment by haircommander** [comment]
that's perfect! that vastly improves from our current situation of just removing the whole c/storage if we detect an unclean shutdown
