### ISSUE TITLE
Wrong repo address in installation instructions

### ISSUE THREAD

**Issue by FerminCastro** [cri-o/cri-o#7181]
### What happened?

https://github.com/cri-o/cri-o/blob/main/install.md#readme is using

curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/$OS/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo
yum install cri-o

which fails for specific versions like 1.23.X, 1.24.X etc

### What did you expect to happen?

Retrieve the correct repo file

### How can we reproduce it (as minimally and precisely as possible)?

Set VERSION to 1.24.1 (for example) and use instructions at https://github.com/cri-o/cri-o/blob/main/install.md#readme

### Anything else we need to know?

Instead it should use
SUBVERSION=$(echo $VERSION | awk -F'.' '{print $1"."$2}')
(or your choice of string trim)

curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:${VERSION}.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/${SUBVERSION}:/${VERSION}/$OS/devel:kubic:libcontainers:stable:cri-o:${SUBVERSION}:${VERSION}.repo

### CRI-O and Kubernetes version

Irrelevant to the problem

### OS version

<details>
CENTOS_7
```console
# On Linux:
$ cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="7.8"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
PRETTY_NAME="Oracle Linux Server 7.8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:8:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.8
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.8

$ uname -a
Linux olk8-m1 4.14.35-1902.302.2.el7uek.x86_64 #2 SMP Fri Apr 24 14:24:11 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

Not relevant

**Comment by FerminCastro** [comment]
```
[opc@olk8-m1 ~]$ export OS=CentOS_7
[opc@olk8-m1 ~]$ export VERSION=1.24:1.24.6
[opc@olk8-m1 ~]$ curl https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/${VERSION}:/${VERSION}/${OS}/devel:kubic:libcontainers:stable:cri-o:${VERSION}:${VERSION}.repo
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>Resource is no longer available!</title>
...
[opc@olk8-m1 ~]$ echo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/${VERSION}:/${VERSION}/${OS}/devel:kubic:libcontainers:stable:cri-o:${VERSION}:${VERSION}.repo
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24:1.24.6:/1.24:1.24.6/CentOS_7/devel:kubic:libcontainers:stable:cri-o:1.24:1.24.6:1.24:1.24.6.repo


[opc@olk8-m1 ~]$ export VERSION=1.24.6
[opc@olk8-m1 ~]$ export SUBVERSION=$(echo $VERSION | awk -F'.' '{print $1"."$2}')

[opc@olk8-m1 ~]$  curl https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/${SUBVERSION}:/${VERSION}/$OS/devel:kubic:libcontainers:stable:cri-o:${SUBVERSION}:${VERSION}.repo
[devel_kubic_libcontainers_stable_cri-o_1.24_1.24.6]
name=devel:kubic:libcontainers:stable:cri-o:1.24:1.24.6 (CentOS_7)
type=rpm-md
baseurl=https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24:/1.24.6/CentOS_7/
gpgcheck=1
gpgkey=https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24:/1.24.6/CentOS_7/repodata/repomd.xml.key
enabled=1
[opc@olk8-m1 ~]$
[opc@olk8-m1 ~]$ echo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/${SUBVERSION}:/${VERSION}/$OS/devel:kubic:libcontainers:stable:cri-o:${SUBVERSION}:${VERSION}.repo
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24:/1.24.6/CentOS_7/devel:kubic:libcontainers:stable:cri-o:1.24:1.24.6.repo
[opc@olk8-m1 ~]$

```


I think the problem is the first appearance of VERSION in the first url

**Comment by haircommander** [comment]
hm I see what you mean. Would you like to open a PR to fix?

**Comment by haircommander** [comment]
typically we recommend forking CRI-O and targetting doc changes to the main branch with a PR. No need to update any of the dev branches

**Comment by FerminCastro** [comment]
I added you as reviewer for the PR

**Comment by FerminCastro** [comment]
I am not sure how to make https://github.com/cri-o/cri-o/pull/7206 progress. There is no plausible url shortening that i can think off and ni fact the current text at https://github.com/cri-o/cri-o/blob/main/install.md#readme keep the url in all its length

**Comment by FerminCastro** [comment]
Doc at https://github.com/cri-o/cri-o/blob/main/install.md#readme contains the "SUBVERSION" fix now. Closing
