### ISSUE TITLE
Cannot download artifacts for v1.25.4

### ISSUE THREAD

**Issue by akishkin** [cri-o/cri-o#7188]
### What happened?

I'm downloading tar.gz via link https://storage.googleapis.com/cri-o/artifacts/cri-o.amd64.v1.25.4.tar.gz
get XML reply:
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: cri-o/artifacts/cri-o.amd64.v1.25.4.tar.gz</Details>
</Error>
```

### What did you expect to happen?

Archive to be downloaded

### How can we reproduce it (as minimally and precisely as possible)?

curl https://storage.googleapis.com/cri-o/artifacts/cri-o.amd64.v1.25.4.tar.gz

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# paste output here
```

```console
$ kubectl version --output=json
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by haircommander** [comment]
it seems the static building jobs failed https://github.com/cri-o/cri-o/actions/runs/5717963421/job/15594908659 I tried running locally and failed. thanks for the report!

**Comment by haircommander** [comment]
I don't currently have an arm64 node to do the builds, and also am having trouble connecting to the google cloud bucket, but the amd64 files are in the release now. Is this sufficient for now @akishkin ? @saschagrunert is on vacation this week and will be coming back next week and should be able to help me

**Comment by saschagrunert** [comment]
I've manually built the files and uploaded them. 
![screenshot](https://github.com/cri-o/cri-o/assets/695473/68c26855-e67d-44d4-b63a-0df9931afd0e)

**Comment by akishkin** [comment]
Yeah, that works now, thanks!
