### ISSUE TITLE
/run/crio used too much inodes

### ISSUE THREAD

**Issue by lance5890** [cri-o/cri-o#7222]
### What happened?

1. one pod has scheduled in this node, but kubelet event shows no space left in device, the df -i shows as follows:
<img width="539" alt="image" src="https://github.com/cri-o/cri-o/assets/30207518/cb153a05-d315-48eb-8b7b-da6d13e2a020">

```
[ccadmin@master1 crio]$ df -i
Filesystem        Inodes  IUsed     IFree IUse% Mounted on
devtmpfs         1048576    572   1048004    1% /dev
tmpfs            8180617      2   8180615    1% /dev/shm
tmpfs             819200  819200  0       **100%** /run

```

2. The /run/crio dir has too much dirs, as follows:

```
[ccadmin@master1 crio]$ pwd
/run/crio
[ccadmin@master1 crio]$ sudo ls -l  | wc -l
812088

```

### What did you expect to happen?

I just want to know how to check why the /run/crio used too much inodes

### How can we reproduce it (as minimally and precisely as possible)?

This only happened once in one node, and we remove the /run/crio has already resolve this problem

### Anything else we need to know?

The crio logs has many error logs as follows:
’‘’
level=error msg="Container creation error: time=\"2023-08-14T10:22:22+08:00\" level=error msg=\"runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: failed to write \\\"b *:* m\\\": write /sys/fs/cgroup/devices/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pode16e9478_41e3_4359_bc62_69627b3aebc6.slice/crio-8675c76b29c7f6503d9932e3da4095aec9ef5ebcd21dae93458af5cb6af20847.scope/devices.allow: operation not permitted\"\n" id=7ad3fecd-e866-4986-aed9-b9253615754b name=/runtime.v1.RuntimeService/CreateContainer
‘’‘

'''
conmon 55ed9d39e1c888460d19 <error>: Failed to write conmon pidfile: Failed to create file “/run/containers/storage/overlay-containers/55ed9d39e1c888460d195860f794376516293861e09f1fb692b7031339f96557/userdata/conmon-pidfile.QFXT91”: No space left on device: No space left on device
Aug 16 07:12:46 gwxz-101a149u-ecs1 crio[9558]: time="2023-08-16 07:12:46.151381944+08:00" level=info msg="createCtr: deleting container ID 
'''

_No response_

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# paste output here
"1.24.3"
```

```console
$ kubectl version --output=json
# paste output here
v1.25.8
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
Linux master1 5.15.67-7.cl9.x86_64
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by lance5890** [comment]
help wanted

**Comment by lance5890** [comment]
@haircommander

**Comment by saschagrunert** [comment]
I assume this can be fixed with https://github.com/containers/conmon/pull/384. Can you try conmon v2.1.7?

**Comment by lance5890** [comment]
> I assume this can be fixed with [containers/conmon#384](https://github.com/containers/conmon/pull/384). Can you try conmon v2.1.7?

Thanks so much

**Comment by haircommander** [comment]
did that fix your issue @lance5890 ?

**Comment by lance5890** [comment]
> did that fix your issue @lance5890 ?

I will let u known when I try this fix,  thanks guys

**Comment by lance5890** [comment]
> did that fix your issue @lance5890 ?

I have tried the fix, it does work, thanks @haircommander  @saschagrunert
