### ISSUE TITLE
DEB packages for v1.28 are missing

### ISSUE THREAD

**Issue by bubnovd** [cri-o/cri-o#7247]
### What happened?

[Packages of v1.28 for APT based repositories](https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.28/xUbuntu_22.04/amd64/) is not found and got 404 page.

### What did you expect to happen?

It should be available.

### How can we reproduce it (as minimally and precisely as possible)?

View the URL from a browser.

### CRI-O and Kubernetes version

v1.28

### OS version

All APT based distributives: Ubuntu, Debian, Raspbian

### Additional environment details (AWS, VirtualBox, physical, etc.)

Any APT based OS.

**Comment by hasan4791** [comment]
OBS systems had major outage yesterday and came back to online few hours back. This would be addressed soon.

**Comment by pzi123** [comment]
The same for RPM https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.28/CentOS_8_Stream/x86_64/  is missing cri-o-1.28*.rpm

**Comment by hasan4791** [comment]
Updated the packages, can you all check once!!

**Comment by hasan4791** [comment]
Shall this issue be closed if things are resolved?
