### ISSUE TITLE
Unable to locate package cri-o on Ubuntu 22.04

### ISSUE THREAD

**Issue by c-x-berger** [cri-o/cri-o#7253]
### What happened?

```
# apt update
[...]
Get:7 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.28/xUbuntu_22.04  InRelease [1,632 B]
```
```
# apt install cri-o cri-o-runc
[...]
E: Unable to locate package cri-o
```

### What did you expect to happen?

install CRI-O

### How can we reproduce it (as minimally and precisely as possible)?

follow `install.md` on Ubuntu 22.04 for version 1.28

### Anything else we need to know?

similar to #6380, looks like the binaries aren't present on download.opensuse.org

### CRI-O and Kubernetes version

<details>
n/a, could not install
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux evergiven 5.15.0-79-generic #86-Ubuntu SMP Mon Jul 10 16:07:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
physical box
</details>

**Comment by hasan4791** [comment]
Dup of https://github.com/cri-o/cri-o/issues/7247

**Comment by haircommander** [comment]
should be fixed now
