### ISSUE TITLE
Add an endpoint for heap dumps

### ISSUE THREAD

**Issue by sohankunkerkar** [cri-o/cri-o#7307]
### What happened?

This issue aims to add an endpoint for heap dumps in CRI-O, which can be a valuable debugging and diagnostics feature. You can get help from the existing WIP [PR](https://github.com/cri-o/cri-o/pull/5197).

### What did you expect to happen?

N/A

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### Anything else we need to know?

https://github.com/cri-o/cri-o/pull/5197

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# paste output here
```

```console
$ kubectl version --output=json
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by MeenuyD** [comment]
Hello, I am ready to create PR but I do not understand this Idea: Add a subcommand to crio-status to dump to a specific file location. can you explain

**Comment by sohankunkerkar** [comment]
We are planning to deprecate the `crio-status` command in 1.29, so my ideal bet is to add a command line flag to `crio`.
@saschagrunert wdyt?

**Comment by saschagrunert** [comment]
@sohankunkerkar sounds good to me!

**Comment by sohankunkerkar** [comment]
Alright, @MeenuyD, the idea is to add a command line argument called `--enable-heap-dump`. When the user sets that flag, CRI-O will generate a file at the specified location containing heap dump information. Let's add that option here: https://github.com/cri-o/cri-o/blob/main/pkg/config/config.go#L237. You can see [this](https://github.com/cri-o/cri-o/issues/6835) example PR to get more information.

**Comment by sohankunkerkar** [comment]
@MeenuyD do you want to pursue the changes?

**Comment by hernandanielg** [comment]
hey @sohankunkerkar I want to contribute with this if you allow me :) (_I'll need some help tho_)

**Comment by shipra101** [comment]
I would like to work on this if no one is on it

**Comment by kwilczynski** [comment]
@shipra101, a person is already assigned, and @hernandanielg might still be working on it.

**Comment by hernandanielg** [comment]
I waited for the decision on this, I thought it wasn't required anymore 🤷🏻 
https://github.com/cri-o/cri-o/pull/7328#discussion_r1433451818

I can re-open that PR and give it a try for sure, just let me know how to proceed

Thanks! 🙇🏻

**Comment by saschagrunert** [comment]
@cri-o/cri-o-maintainers how do we want to proceed with this?

**Comment by sohankunkerkar** [comment]
I think we need some consensus on https://github.com/cri-o/cri-o/discussions/7615

**Comment by saschagrunert** [comment]
Working on this as part of https://github.com/cri-o/cri-o/pull/8702
