### ISSUE TITLE
Multi-arch support for a test image

### ISSUE THREAD

**Issue by BbolroC** [cri-o/cri-o#7321]
### What happened?

A test image (e.g. `quay.io/crio/fedora-crio-ci:latest`) only supports for `x86_64`. It would be great to support other architectures to run the test. 

Background: I ran into a test failure for `ctr termination reason Completed` on s390x and realised the test image does not support the architecture. So I tried to natively build an image with [Dockerfile](https://github.com/cri-o/cri-o/blob/main/test/testdata/Dockerfile), made it available at a local registry (e.g. `localhost:5000`) and ran a test but got:

```
level=info msg="Creating container: //" file="server/container_create.go:314" id=3278243c-02e0-4e44-a1a3-dec9a5ed11fa name=/runtime.v1.RuntimeService/CreateContainer
level=debug msg="Initializing stage for resource k8s_container1_podsandbox1_redhat.test.crio_redhat-test-crio_1 to container creating" file="resourcestore/resourcestore.go:219" id=3278243c-02e0-4e44
-a1a3-dec9a5ed11fa name=/runtime.v1.RuntimeService/CreateContainer
level=warning msg="Allowed annotations are specified for workload []" file="config/workloads.go:100"
level=debug msg="parsed reference into \"[overlay@/tmp/tmp.DcQGA4MKcV/crio+/tmp/tmp.DcQGA4MKcV/crio-run]localhost:5000/fedora-crio-ci:latest\"" file="storage/storage_transport.go:185"
level=debug msg="reference \"[overlay@/tmp/tmp.DcQGA4MKcV/crio+/tmp/tmp.DcQGA4MKcV/crio-run]localhost:5000/fedora-crio-ci:latest\" does not resolve to an image ID" file="storage/storage_reference.go
:146"
level=info msg="createCtr: releasing container name k8s_container1_podsandbox1_redhat.test.crio_redhat-test-crio_1" file="resourcestore/resourcecleaner.go:69" id=3278243c-02e0-4e44-a1a3-dec9a5ed11fa
 name=/runtime.v1.RuntimeService/CreateContainer
level=debug msg="Response error: image not known" file="otel-collector/interceptors.go:71" id=3278243c-02e0-4e44-a1a3-dec9a5ed11fa name=/runtime.v1.RuntimeService/CreateContainer
```

If the support is not viable, I would be grateful if someone lets me know how to run the test locally. Thanks.

### What did you expect to happen?

N/A

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.29.0
Version:        1.29.0
GitCommit:      a3d1e58a24bb538836a8c3c88cd2ae20d00c2d03
GitCommitDate:  2023-09-20T07:40:36Z
GitTreeState:   clean
BuildDate:      2023-09-20T08:46:12Z
GoVersion:      go1.20.2
Compiler:       gc
Platform:       linux/s390x
Linkmode:       dynamic
BuildTags:
  seccomp
  selinux
  exclude_graphdriver_btrfs
  exclude_graphdriver_devicemapper
  libdm_no_deferred_remove
LDFlags:          unknown
SeccompEnabled:   true
AppArmorEnabled:  false
```

```console
$ kubectl version --output=json
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="9.2 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.2 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2
$ uname -a
Linux kata-gha-runner-builder-05 5.14.0-284.30.1.el9_2.s390x #1 SMP Fri Aug 25 09:26:01 EDT 2023 s390x s390x s390x GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by haircommander** [comment]
cc @sohankunkerkar 

i don't know if the cri-o project has capacity to maintain multiple arches when the true purpose is for our CI. You could push that image to a registry and replace the location in the IMAGES() list in `test/helpers.bash` and then update the location in the `test/testdata/container*.json` and I would expect that to work

**Comment by BbolroC** [comment]
@haircommander Thanks for the help. The local test works by following your advice. I missed to configure the array `IMAGES` at `test/common.sh`.  I will close this because it does not look simple for the community to support multi-arch test images. (look feasible, but not that valuable compared to efforts for this 😉 )
