### ISSUE TITLE
Release v1.28.2 ahead of KubeCon

### ISSUE THREAD

**Issue by saschagrunert** [cri-o/cri-o#7411]
@cri-o/cri-o-maintainers I'd like to propose a v1.28.2 before KubeCon, to get the latest and greatest changes in. Would you be happy with that?

**Comment by kwilczynski** [comment]
@saschagrunert, I would! :tada:

**Comment by haircommander** [comment]
yeah makes sense to me

**Comment by saschagrunert** [comment]
Done: https://github.com/cri-o/cri-o/releases/tag/v1.28.2

The packages are available as well: https://build.opensuse.org/project/show/isv:kubernetes:addons:cri-o:stable:v1.28
CI run: https://github.com/cri-o/packaging/actions/runs/6731497655
