### ISSUE TITLE
crio proxy settings

### ISSUE THREAD

**Issue by okdadmin** [cri-o/cri-o#7437]
### What happened?

I want to settings proxy config for crio. How can I edit this: /usr/lib/systemd/system/crio.service please?
I want to put in config: Environment="HTTP_PROXY=http://proxy.mav.hu:3028/" "HTTPS_PROXY=http://proxy.mav.hu:3028/" "NO_PROXY="okdt.mav.hu,localhost,127.0.0.1,100.248.152.0/24"

### What did you expect to happen?

I don't know.

### How can we reproduce it (as minimally and precisely as possible)?

I don't know.

### CRI-O and Kubernetes version

okd4.10

### OS version

Fedora CoreOS 35

### Additional environment details (AWS, VirtualBox, physical, etc.)

OKD4.10

**Comment by saschagrunert** [comment]
Hey @okdadmin, have you tried manually editing the systemd unit file?

**Comment by okdadmin** [comment]
Hi,
Yes of corse! I'm asking because it doesn't work.

**Comment by okdadmin** [comment]
OKD4.10
Fedora coreos 35
/usr/lib/systemd/system/crio.service

[root@master1 ~]# mount | grep /usr
/dev/sda4 on /usr type xfs (ro,relatime,seclabel,attr2,inode64,logbufs=8,logbsize=32k,prjquota)

**Comment by kwilczynski** [comment]
@okdadmin, setting up an HTTP proxy for CRI-O to use should work fine for pulling container images.

If you need to permanently update the systemd unit file for CRI-O while deployed atop CoreOS, then deploying a systemd drop-in or environment configuration could help. See:

- [Using systemd drop-in units](https://github.com/awesome-docs/coreos-docs/blob/master/os/using-systemd-drop-in-units.md)
- [Using environment variables in systemd units](https://github.com/awesome-docs/coreos-docs/blob/master/os/using-environment-variables-in-systemd-units.md)

**Comment by vikas027** [comment]
If someone lands here, setting up proxy variables `/usr/lib/systemd/system/crio.service` did not worked for me. I had to do the below.

```bash
# cat /etc/systemd/system/crio.service.d/http-proxy.conf
[Service]
Environment="HTTP_PROXY=http://<redacted>:8080"
Environment="HTTPS_PROXY=http://<redacted>:8080"

# systemctl daemon-reload
# systemctl restart crio
```
