### ISSUE TITLE
Feature request: add option to set metrics listen address (not just port)

### ISSUE THREAD

**Issue by ricardbejarano** [cri-o/cri-o#7446]
### What happened?

When using `--enable-metrics` you only get to tweak the port via `--metrics-port=9090`.

Apparently, from [this line](https://github.com/cri-o/cri-o/blob/main/server/metrics/metrics.go#L365), there's no support to also tweak the listen address/interface of the metrics server.

### What did you expect to happen?

I'd like to have the ability to tweak such parameter, like [containerd](https://github.com/containerd/containerd/blob/main/docs/man/containerd-config.toml.5.md?plain=1#L73), for instance.

### How can we reproduce it (as minimally and precisely as possible)?

N/A.

### Anything else we need to know?

There wasn't an option to file a feature request, so I used the Bug Report template.

### CRI-O and Kubernetes version

<details>

```console
# crio --version
crio version 1.28.1
Version:        1.28.1
GitCommit:      664b9cfab06732a307087511c6523c4302f74043
GitCommitDate:  2023-10-26T22:14:35Z
GitTreeState:   clean
BuildDate:      1970-01-01T00:00:00Z
GoVersion:      go1.20.10
Compiler:       gc
Platform:       linux/amd64
Linkmode:       static
BuildTags:      
  static
  netgo
  osusergo
  exclude_graphdriver_btrfs
  exclude_graphdriver_devicemapper
  seccomp
  apparmor
  selinux
LDFlags:          unknown
SeccompEnabled:   true
AppArmorEnabled:  true
```

```console
$ kubectl version --output=json
N/A
```

</details>

### OS version

<details>

```console
$ cat /etc/os-release
N/A
$ uname -a
N/A
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
N/A

</details>

**Comment by kwilczynski** [comment]
@ricardbejarano, thank you for getting in touch!

You do have an interesting timing, admittedly, as we recently did discuss this, but in terms of potentially changing it so that most of the listeners CRI-O will be moved to initially, and by default, listen to localhost (127.0.0.1) for improved default security.

This change will also, as a side effect, expose the ability to set different IP addresses for the metrics listener.

**Comment by ricardbejarano** [comment]
Yup, I'd do exactly that: add the option to set the address, but default to loopback.

**Comment by saschagrunert** [comment]
> I'd like to have the ability to tweak such parameter, like [containerd](https://github.com/containerd/containerd/blob/main/docs/man/containerd-config.toml.5.md?plain=1#L73), for instance.

What is the use case for this?

**Comment by ricardbejarano** [comment]
Many.

For instance, as @kwilczynski said, it enables tighter default security by just listening on `127.0.0.1`, but allowing the user to override it as they please.

Myself, I need it so that the metrics endpoint is only available to one of the networks the hosts belong to, without having to deal with CRI-O specific firewall rules on all hosts.

**Comment by saschagrunert** [comment]
Yeah I was more interested in the non-localhost ones. Makes sense to me.

**Comment by kwilczynski** [comment]
@saschagrunert @ricardbejarano, I can think of another popular use-case.

A typical deployment choice for bare-metal deployments is to have separate production/public and management networks.

This enables, if supported, services to only listen on a specific IP address from such a specific network. The interface might be a dedicated NIC or a VLAN. Such an approach is often desired for extra security.

Also, as @ricardbejarano said, it also avoids complex firewall rules.

**Comment by Utkar5hM** [comment]
Hi @saschagrunert, Can I work on this issue?

**Comment by kwilczynski** [comment]
@Utkar5hM, there is nothing to be done here. This issue will be resolved once https://github.com/cri-o/cri-o/issues/7448 is completed.

**Comment by AHB102** [comment]
This issue will be resolved once #7448 right ? or something has to be done for this specific issue ? I'm new to open source, trying to contribute, please forgive my "newbieness"

**Comment by ricardbejarano** [comment]
@AHB102 i think so.
Nothing to ask forgiveness for!

**Comment by kwilczynski** [comment]
@ricardbejarano, this feature has been closed via:

- https://github.com/cri-o/cri-o/pull/7677
- https://github.com/cri-o/cri-o/pull/7714

You now have `--metrics-host` and `--metrics-port` available. Hopefully, this will cover your use case. :smile:

**Comment by ricardbejarano** [comment]
Excellent! Thank you!

Closing.
