### ISSUE TITLE
Use 127.0.0.1 as the default address to listen on for other listeners

### ISSUE THREAD

**Issue by kwilczynski** [cri-o/cri-o#7448]
Some time ago, the streaming endpoint was moved to only listen on localhost (127.0.0.1) and a random port to improve the default security stance in CRI-O; see:

- https://github.com/cri-o/cri-o/pull/1714

This change has also been incorporated in OpenShift via the Machine Config Operator (MCO):

- https://github.com/openshift/machine-config-operator/pull/3853

However, there are still other listeners that can be enabled in CRI-O that would listen on any address (0.0.0.0), often without a way to move them to either localhost or any other address for that matter, per:

- The Go profiling (pprof) endpoint:

**Note:** This does not affect accessing the profiling endpoint via the Unix socket CRI-O uses.

https://github.com/cri-o/cri-o/blob/5633698da2814bc4e97f56f701d747853069a91c/internal/criocli/criocli.go#L804-L809

https://github.com/cri-o/cri-o/blob/5633698da2814bc4e97f56f701d747853069a91c/cmd/crio/main.go#L233-L242

- The Prometheus (metrics) endpoint:

**Note:** This does not affect accessing the metrics endpoint via the Unix socket that can be additionally configured.

https://github.com/cri-o/cri-o/blob/5633698da2814bc4e97f56f701d747853069a91c/pkg/config/config.go#L889-L892

https://github.com/cri-o/cri-o/blob/5633698da2814bc4e97f56f701d747853069a91c/server/metrics/metrics.go#L364-L370

- The Tracing endpoint:

https://github.com/cri-o/cri-o/blob/5633698da2814bc4e97f56f701d747853069a91c/pkg/config/config.go#L893-L897

https://github.com/cri-o/cri-o/blob/5633698da2814bc4e97f56f701d747853069a91c/internal/oci/runtime_pod.go#L61-L74

Tracing shares implementation details with the [conmon-rs](https://github.com/containers/conmon-rs) project:

- [conmon-rs/pkg/client/client.go#L101-L111](https://github.com/containers/conmon-rs/blob/5d9cd8d30fa57ae548514124dc3bcba093366a61/pkg/client/client.go#L101-L111)

```go
type Tracing struct {
	// Enabled tells the server to run with OpenTelemetry tracing.
	Enabled bool

	// Endpoint is the GRPC tracing endpoint for OLTP.
	// Defaults to "http://localhost:4317"
	Endpoint string

	// Tracer allows the client to create additional spans if set.
	Tracer trace.Tracer
}
```

- [conmon-rs/pkg/client/client.go#L333-L340](https://github.com/containers/conmon-rs/blob/5d9cd8d30fa57ae548514124dc3bcba093366a61/pkg/client/client.go#L333-L340)

```go
if config.Tracing != nil && config.Tracing.Enabled {
	c.tracingEnabled = true
	args = append(args, "--enable-tracing")

	if config.Tracing.Endpoint != "" {
		args = append(args, "--tracing-endpoint", config.Tracing.Endpoint)
	}
}
```

- [conmon-rs/server/src/config.rs#L119-L125](https://github.com/containers/conmon-rs/blob/main/conmon-rs/server/src/config.rs#L119-L125)

```rust
#[get = "pub"]
#[arg(
    default_value("http://localhost:4317"),
    env(concat!(prefix!(), "TRACING_ENDPOINT")),
    long("tracing-endpoint"),
    short('t'),
    value_name("URL")
)]
```

---

Thus, it might be prudent also to move these remaining endpoints to listen on localhost (127.0.0.1) as a sensible default, which would improve the default security stance a little more, especially as there aren't any reasons to the contrary, for these services to listen on anything else than localhost.

It should also be possible for the users to set any desired listen address both for Go profiling and the Prometheus metrics endpoints - both of which are hardcoded at the moment.

Related:

- https://github.com/cri-o/cri-o/issues/7446
- https://github.com/containerd/cri/issues/777
- https://github.com/kubernetes/kubernetes/issues/36666

**Comment by kwilczynski** [comment]
I also noticed that currently, it's not possible to enable the Prometheus metrics endpoint to be only available via the Unix socket that can be optionally configured like the Go profiling (pprof) endpoint, as the Unix socket listener can only be enabled if the metrics are already enabled which also entails enabling the usual listener - and this might not be desirable in some cases.

Related code:

https://github.com/cri-o/cri-o/blob/5633698da2814bc4e97f56f701d747853069a91c/server/metrics/metrics.go#L354-L385

**Comment by haircommander** [comment]
I think this makes sense to me :)

**Comment by sswastik02** [comment]
Hi,
Is this still a valid issue ? If yes, I would like to contribute to this issue.

Thanks

**Comment by saschagrunert** [comment]
@kwilczynski is there anything left open which could be done by @sswastik02 :)

**Comment by kwilczynski** [comment]
@saschagrunert, yes.

We only moved streaming and metrics ports to use **127.0.0.1** as default. I will revisit what is still left and how to go about it, and report back later.

**Comment by kwilczynski** [comment]
@bitoku, would you like to take this one too?

**Comment by bitoku** [comment]
yes, thanks.
/assign

**Comment by bitoku** [comment]
#8495 #8506 https://github.com/containers/conmon-rs/pull/2391
Since these PRs are merged. I'm closing this issue.

I'll create a new issue for this. https://github.com/cri-o/cri-o/issues/7448#issuecomment-1784546795

**Comment by kwilczynski** [comment]
@bitoku, thank you for seeing this through to completion!
