### ISSUE TITLE
Restoring a openfaas function results in " Error: image not known" . So what determines that whether a container checkpoint image could be recognized while restoring it? 

### ISSUE THREAD

**Issue by WhaleSpring** [cri-o/cri-o#7474]
### Which jobs are failing?

When I try to restore a checkpoint image from a openfaas function container, image not known, why and how to solve it ?
![image](https://github.com/cri-o/cri-o/assets/81799971/2e0eacd3-44a1-423d-bfd9-8335fe88fd70)

### Which tests are failing?

 Restore a checkpoint image from a openfaas function container

### Since when has it been failing?

[]

### Reason for failure (if possible)

Maybe something in the container couldn't be restored?

**Comment by WhaleSpring** [comment]
It seem to be a matter that resulted by Centos7 , it's a really bad idea to build a cluster at a so old linux server at the beginning.

**Comment by kwilczynski** [comment]
@WhaleSpring, thank you for taking care of this!
