### ISSUE TITLE
Crio installation/update failure on x64 Ubuntu 20.04 

### ISSUE THREAD

**Issue by seantywork** [cri-o/cri-o#7479]
### What happened?

I'm frequently installing/updating crio as a Kubernetes OCI runtime engine on x64 Ubuntu 20.04

The issue has been recurring from roughly 8:00 AM November 14, 2023 with no automatic or random success observed.

I think the issue below 

- https://github.com/containers/podman/issues/20690

is somewhat reflecting the same thing I'm struggling with now.

Below is the installation log

```bash
+ sudo apt-get update
Hit:1 http://kr.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 https://baltocdn.com/helm/stable/debian all InRelease
Get:3 http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.27/xUbuntu_20.04  InRelease [1632 B]
Hit:4 http://kr.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:5 http://kr.archive.ubuntu.com/ubuntu focal-backports InRelease
Get:6 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  InRelease [1642 B]
Hit:7 http://kr.archive.ubuntu.com/ubuntu focal-security InRelease
Fetched 3274 B in 2s (2167 B/s)
Reading package lists... Done
+ sudo apt-get install cri-o cri-o-runc -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  conmon containers-common
Suggested packages:
  containernetworking-plugins
The following NEW packages will be installed:
  conmon containers-common cri-o cri-o-runc
0 upgraded, 4 newly installed, 0 to remove and 83 not upgraded.
Need to get 3631 kB/32.4 MB of archives.
After this operation, 133 MB of additional disk space will be used.
Err:1 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  cri-o-runc 1.0.1~2
  Redirection from https to 'http://mirror.aardsoft.fi/opensuse/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/amd64/cri-o-runc_1.0.1~2_amd64.deb' is forbidden [IP: 195.135.223.226 443]
E: Failed to fetch https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/amd64/cri-o-runc_1.0.1~2_amd64.deb  Redirection from https to 'http://mirror.aardsoft.fi/opensuse/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/amd64/cri-o-runc_1.0.1~2_amd64.deb' is forbidden [IP: 195.135.223.226 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

```  

### What did you expect to happen?

smooth and complete installation as usual

### How can we reproduce it (as minimally and precisely as possible)?

Try out the official installation steps on x64 Ubuntu 20.04 please

### CRI-O and Kubernetes version

both are 1.27

### OS version

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### Additional environment details (AWS, VirtualBox, physical, etc.)

on Qemu virtual machine

**Comment by seantywork** [comment]
Okay, I got it working by doing just one thing

within my installation script I've changed the below part 

```bash
echo "deb [signed-by=/usr/share/keyrings/libcontainers-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
echo "deb [signed-by=/usr/share/keyrings/libcontainers-crio-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.list

mkdir -p /usr/share/keyrings
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | gpg --dearmor -o /usr/share/keyrings/libcontainers-archive-keyring.gpg
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/Release.key | gpg --dearmor -o /usr/share/keyrings/libcontainers-crio-archive-keyring.gpg

```

to below one (note the https -> http)

```bash
echo "deb [signed-by=/usr/share/keyrings/libcontainers-archive-keyring.gpg] http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
echo "deb [signed-by=/usr/share/keyrings/libcontainers-crio-archive-keyring.gpg] http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.list

mkdir -p /usr/share/keyrings
curl -L http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | gpg --dearmor -o /usr/share/keyrings/libcontainers-archive-keyring.gpg
curl -L http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/Release.key | gpg --dearmor -o /usr/share/keyrings/libcontainers-crio-archive-keyring.gpg

```

So, my cautious suggestion for those who try to update CRIO, please try changing the protocol specified in files within /etc/apt/sources.list.d/ directory and then see if what happens

**Comment by saschagrunert** [comment]
Isn't this a security risk to downgrade from https to http? I'm wondering what has changed at the openSUSE side for this. BTW, I see the issue across various repositories.

**Comment by seantywork** [comment]
Definitely minus for security.

But the problem for me was that I couldn't sit down and wait for the openSUSE or APT or whomever guys to fix it for me so I had to come up with a workaround  :(
And also, I see from time to time APT update or install request travel to non-tls endpoint mirrors

**Comment by seantywork** [comment]
> Isn't this a security risk to downgrade from https to http? I'm wondering what has changed at the openSUSE side for this. BTW, I see the issue across various repositories.

Definitely minus for security.

But the problem for me was that I couldn't sit down and wait for the openSUSE or APT or whomever guys to fix it for me so I had to come up with a workaround :(
And also, I see from time to time APT update or install request travel to non-tls endpoint mirrors

**Comment by saschagrunert** [comment]
@seantywork I see. I'm trying to reach OBS support to find out what's broken. I definitely have not seen this issue before, yet.

**Comment by seantywork** [comment]
> @seantywork I see. I'm trying to reach OBS support to find out what's broken. I definitely have not seen this issue before, yet.

Thanks for your work! Hope it works out for all of us :)

**Comment by saschagrunert** [comment]
The issue should be resolved now, can you confirm @seantywork ?

**Comment by kwilczynski** [comment]
I can confirm for Japan and Netherlands - both locations receive redirects to respective mirrors that use HTTPS.

**Comment by seantywork** [comment]
I can confirm in South Korea the issue seems to have been resolved, thanks!
