### ISSUE TITLE
container create failed: read from sync socket

### ISSUE THREAD

**Issue by luomengY** [cri-o/cri-o#7509]
### What happened?

When using crun as the underlying CR, an error message "read from sync socket" is generated when creating a container in sandbox. However, when using runc as the underlying CR, everything works fine together. The version of CRI-O is 1.28.2, the version of crun is 1.11.1, the version of runc is 1.1.10, and the version of crictl is v1.28.0.
![de157b0507f7f5a2d1da99c6541cc27](https://github.com/cri-o/cri-o/assets/110345347/0479932d-4283-4840-af15-e5e8bbba031d)

### What did you expect to happen?

When CRI-O uses crunc as a CR, it can create containers normally through the CRI interface.

### How can we reproduce it (as minimally and precisely as possible)?

Add edge nodes using kubedge v1.15.0 and execute: “keadm join --kubeedge-version v1.15.0 --remote-runtime-endpoint unix:///run/crio/crio.sock   --cloudcore-ipport 192.168.101.100:10000  --token xxxxxxxxxxxxxxxxxxxx”.

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# paste output here
```
CRI-O:v1.28.2
runc:1.1.10
crun:1.11.1
```console
$ kubectl version --output=json
# paste output here
```
kubeedge v1.15.0,The k8s version that kubedge relies on is v1.26.7.

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```
NAME="openEuler"
VERSION="22.03 (LTS-SP2)"
ID="openEuler"
VERSION_ID="22.03"
PRETTY_NAME="openEuler 22.03 (LTS-SP2)"
ANSI_COLOR="0;31"
</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
vmware: v1.15.0
</details>

**Comment by saschagrunert** [comment]
@luomengY this seems to be related to https://github.com/containers/crun/issues/1338

Which kind of packages are you using?

**Comment by saschagrunert** [comment]
@luomengY are you using the packages from https://github.com/cri-o/packaging ?

**Comment by luomengY** [comment]
> @luomengY are you using the packages from https://github.com/cri-o/packaging ?

from: https://storage.googleapis.com/cri-o/artifacts/cri-o.amd64.v1.28.2.tar.gz

**Comment by saschagrunert** [comment]
@luomengY I re-packaged v1.28.2, can you try the same again with the new bundle on https://storage.googleapis.com/cri-o/artifacts/cri-o.amd64.v1.28.2.tar.gz ?

**Comment by luomengY** [comment]
> @luomengY I re-packaged v1.28.2, can you try the same again with the new bundle on https://storage.googleapis.com/cri-o/artifacts/cri-o.amd64.v1.28.2.tar.gz ?

I tried and there's no problem now. The version of crun is 1.12.

**Comment by saschagrunert** [comment]
Thanks!

/close

**Comment by saschagrunert** [comment]
@luomengY it sets it automatically to true if SELinux is enabled on the system: 

https://github.com/cri-o/cri-o/blob/6e26c2a7386cdf107aa1bbbc94faff0be06d4160/pkg/config/config.go#L845

https://github.com/cri-o/cri-o/blob/6e26c2a7386cdf107aa1bbbc94faff0be06d4160/pkg/config/config_linux.go#L17-L19

**Comment by luomengY** [comment]
> @luomengY it sets it automatically to true if SELinux is enabled on the system:
> 
> https://github.com/cri-o/cri-o/blob/6e26c2a7386cdf107aa1bbbc94faff0be06d4160/pkg/config/config.go#L845
> 
> https://github.com/cri-o/cri-o/blob/6e26c2a7386cdf107aa1bbbc94faff0be06d4160/pkg/config/config_linux.go#L17-L19
But I found that v1.23.2 and v1.28.2 have both given default values for the -- selinux parameter, and the default values for both versions are different. I want to know if the changes before and after the versions were considered in this context?
![error](https://github.com/cri-o/cri-o/assets/110345347/2cdb661b-2137-4f1c-81a0-df0fd9b8a785)
