### ISSUE TITLE
kubulet failed to boot with the error 'cgroup manager.Set failed: openat2 /sys/fs/cgroup/kubepods.slice/cpu.weight: no such file or directory'

### ISSUE THREAD

**Issue by wangyugui-e16** [cri-o/cri-o#7569]
### What happened?

kubulet 1.28 /cri-o 1.28 failed to boot with the error 'cgroup manager.Set failed: openat2 /sys/fs/cgroup/kubepods.slice/cpu.weight: no such file or directory'

### What did you expect to happen?

We need some doc to make it to work.

### How can we reproduce it (as minimally and precisely as possible)?

'kubeadm init' failed to finish.
and  then  we find the error in /var/log/message(group manager.Set failed: openat2 /sys/fs/cgroup/kubepods.slice/cpu.weight: no such file or directory).

### Anything else we need to know?

I tried '[engine] cgroup_manager = "systemd"' and [crio.runtime] cgroup_manager = "systemd"' in /etc/crio/crio.conf.

it still fail to work.

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
```
INFO[2023-12-11 15:52:18.216046897+08:00] Starting CRI-O, version: 1.28.2, git: unknown(clean)
Version:        1.28.2
GitCommit:      unknown
GitCommitDate:  unknown
GitTreeState:   clean
BuildDate:      2023-12-10T11:34:08Z
GoVersion:      go1.20.10
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:
  rpm_crashtraceback
  seccomp
  selinux
LDFlags:          -X github.com/cri-o/cri-o/internal/pkg/criocli.DefaultsPath= -X  github.com/cri-o/cri-o/internal/version.buildDate=2023-12-10T11:34:08Z -X  github.com/cri-o/cri-o/internal/version.gitCommit=e7be4e160f3cc3810b3f6c9fbf225697d772a9ad -X  github.com/cri-o/cri-o/internal/version.version=1.28.2 -X  github.com/cri-o/cri-o/internal/version.gitTreeState=clean  -B 0x9b401fbd087c74c740f6dccc47beaa82c7ca9674 -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  ' -compressdwarf=false
SeccompEnabled:   true
AppArmorEnabled:  false
```console
$ kubectl version --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "28",
    "gitVersion": "v1.28.4",
    "gitCommit": "bae2c62678db2b5053817bc97181fcc2e8388103",
    "gitTreeState": "clean",
    "buildDate": "2023-11-15T16:58:22Z",
    "goVersion": "go1.20.11",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v5.0.4-0.20230601165947-6ce0bf390ce3"
}
```
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
Rocky Linux release 9.3 (Blue Onyx)
$ uname -a
Linux T7610 6.6.5-1.el7.x86_64
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
physical DELL T7610
</details>

**Comment by wangyugui-e16** [comment]
no cgroup info in 'kubeadm config print init-defaults '
···
#     kubeadm config print init-defaults | cat
apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 1.2.3.4
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  name: node
  taints: null
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.k8s.io
kind: ClusterConfiguration
kubernetesVersion: 1.28.0
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
scheduler: {}
···

**Comment by wangyugui-e16** [comment]
or is this a bug fo k8s 1.28.4?
but k8s 1.28.4 works well with containerd 1.6.23.

**Comment by haircommander** [comment]
hm your kubeadm config specifies containerd as your CRI implementation, but this is the CRI-O repo. you'll need to choose one. If you use cri-o and still hit this, can you post the crio logs and the kubelet logs? If you go with containerd, you'll want to open an issue in github.com/containerd/containerd

**Comment by wangyugui-e16** [comment]
it seems cgroup v2 releated.   but yet not clear whether it is a issue of cri-o or  k8s.

**Comment by wangyugui-e16** [comment]
> hm your kubeadm config specifies containerd as your CRI implementation, but this is the CRI-O repo. you'll need to choose one. If you use cri-o and still hit this, can you post the crio logs and the kubelet logs? If you go with containerd, you'll want to open an issue in github.com/containerd/containerd

sorry that the result of 'kubeadm config print init-defaults ' is meanless, because there are some auto detect feature in kubeadm.

**Comment by wangyugui-e16** [comment]
on rockylinux 9.3 with systemd.unified_cgroup_hierarchy=0, 'kubeadm init' work well.
but on rockylinux 9.3 default with systemd.unified_cgroup_hierarchy=1, 'kubeadm init' failed.

the result of 'grep kubepods /var/log/message'
```
Dec 18 10:11:17 T7610 crio[1521]: time="2023-12-18 10:11:17.199464442+08:00" level=info msg="Got pod network &{Name:coredns-66f779496c-txmsb Namespace:kube-system ID:a11773454a130c9e25f5983a49e8dc95577aca88c5e7cad93d238d58eddd5537 UID:7848093e-6a5f-4b0c-8861-9d2e33677864 NetNS: Networks:[{Name:crio Ifname:eth0}] RuntimeConfig:map[crio:{IP: MAC: PortMappings:[] Bandwidth:<nil> IpRanges:[] CgroupPath:kubepods-burstable-pod7848093e_6a5f_4b0c_8861_9d2e33677864.slice}] Aliases:map[]}"
Dec 18 10:11:17 T7610 crio[1521]: time="2023-12-18 10:11:17.231600142+08:00" level=info msg="Got pod network &{Name:coredns-66f779496c-szk6s Namespace:kube-system ID:c243c67af6682c276efc7f6a717ee11ee61f2c89faa225bdfb9472124e5893bf UID:54e7acd3-a068-40a1-a5d3-f2ee3628129b NetNS: Networks:[{Name:crio Ifname:eth0}] RuntimeConfig:map[crio:{IP: MAC: PortMappings:[] Bandwidth:<nil> IpRanges:[] CgroupPath:kubepods-burstable-pod54e7acd3_a068_40a1_a5d3_f2ee3628129b.slice}] Aliases:map[]}"
Dec 18 10:11:17 T7610 systemd[1]: Created slice libcontainer container kubepods.slice.
Dec 18 10:11:17 T7610 kubelet[1622]: E1218 10:11:17.929504    1622 cgroup_manager_linux.go:476] cgroup manager.Set failed: openat2 /sys/fs/cgroup/kubepods.slice/cpu.weight: no such file or directory
Dec 18 10:11:17 T7610 kubelet[1622]: E1218 10:11:17.929595    1622 kubelet.go:1511] "Failed to start ContainerManager" err="failed to initialize top level QOS containers: root container [kubepods] doesn't exist"
```

**Comment by wangyugui-e16** [comment]
cpu.weight is not shown in  /sys/fs/cgroup ,  just cpu.stat

any advice to enable cpu.weight of /sys/fs/cgroup, or disable  cpu.weight  of k8s?

**Comment by wangyugui-e16** [comment]
in kernel upstream such as 5.15.y/6.1.y, k8s failed by 'cpu.weight: no such file'

# tail /sys/fs/cgroup/cgroup.controllers /sys/fs/cgroup/cgroup.subtree_control
==> /sys/fs/cgroup/cgroup.controllers <==
cpuset cpu io memory hugetlb pids rdma misc

==> /sys/fs/cgroup/cgroup.subtree_control <==
io memory hugetlb pids rdma misc

but in EL9 redhat kernel 5.14.0-362.13.1.el9_3.x86_64, k8s works well.
# tail /sys/fs/cgroup/cgroup.controllers /sys/fs/cgroup/cgroup.subtree_control
==> /sys/fs/cgroup/cgroup.controllers <==
cpuset cpu io memory hugetlb pids rdma misc

==> /sys/fs/cgroup/cgroup.subtree_control <==
cpuset cpu io memory hugetlb pids rdma misc

**Comment by wangyugui-e16** [comment]
with CONFIG_RT_GROUP_SCHED disabled kernel, 'kubeadm init' works well now.
