### ISSUE TITLE
Find an alternative to the `imageRef` field

### ISSUE THREAD

**Issue by saschagrunert** [cri-o/cri-o#7579]
With the resolution of https://github.com/cri-o/cri-o/issues/7143, we now only show the image ID as part of the `imageRef` field. We may provide users the additional information which image they specified. Maybe by using the user specified image: https://github.com/kubernetes/kubernetes/pull/118652

**Comment by haircommander** [comment]
I do also think we should investigate moving the kubelet away from using ImageRef

**Comment by saschagrunert** [comment]
We're going to implement the change in the CRI to fix that issue.
