### ISSUE TITLE
Attaching seccomp profiles as OCI artifacts to container images

### ISSUE THREAD

**Issue by saschagrunert** [cri-o/cri-o#7580]
Goal is to provide a standard way to attach files / configurations to container images by using OCI artifact references.

#### Story

As an end user, I’d like to attach OCI artifacts like seccomp profiles to container images, so that I do not have to distribute them using third party solutions.

#### Tech goals
- Be able to attach an OCI artifact to an existing image.
- Pull the artifact automatically on image pull.
- Be able to configure the destination of the artifact.

**Comment by haircommander** [comment]
How would this integrate with PSA? would we install the profile to localhost path, or have a new option to specify the seccomp profile is coming from the image?

**Comment by saschagrunert** [comment]
> How would this integrate with PSA? would we install the profile to localhost path, or have a new option to specify the seccomp profile is coming from the image?

My first thought was to use a localhost path specified in the artifact (by annotation?). The profile still needs to be part of the pod manifest, but now the image takes care of shipping it rather than the cluster admin.

**Comment by sftim** [comment]
How would folks feel about getting a real media type assigned for these OCI objects? That would address a lot of the concerns I've had in reviewing https://github.com/kubernetes/website/pull/45121

**Comment by saschagrunert** [comment]
> How would folks feel about getting a real media type assigned for these OCI objects? That would address a lot of the concerns I've had in reviewing [kubernetes/website#45121](https://github.com/kubernetes/website/pull/45121)

I'm happy to move forward with this.
