### ISSUE TITLE
Install/upgrade on Debian 12 fails due to incorrect files in the repository mirrors

### ISSUE THREAD

**Issue by jaakristioja** [cri-o/cri-o#7587]
### What happened?

`apt-get dist-upgrade` fails:

```
Get:1 https://mirror.aardsoft.fi/opensuse/repositories/devel%3A/kubic%3A/libcontainers%3A/stable/Debian_12  libcap2-bin 100:2.48-1 [443 kB]
Err:1 https://mirror.aardsoft.fi/opensuse/repositories/devel%3A/kubic%3A/libcontainers%3A/stable/Debian_12  libcap2-bin 100:2.48-1
  File has unexpected size (443292 != 442640). Mirror sync in progress? [IP: 192.168.2.31 8080]
  Hashes of expected file:
   - SHA256:adb98eff3f89c685523614d3436e92fcd79119ed02af97e1d5ed9a91d1211d4d
   - SHA1:66dd2dd07b9f93c907c1d8c74169efdb7031fd89 [weak]
   - MD5Sum:358ecda0503c0b18d260a6c13cdefbf9 [weak]
   - Filesize:442640 [weak]
E: Failed to fetch https://mirror.aardsoft.fi/opensuse/repositories/devel%3A/kubic%3A/libcontainers%3A/stable/Debian_12/amd64/libcap2-bin_2.48-1_amd64.deb  File has unexpected size (443292 != 442640). Mirror sync in progress? [IP: 192.168.2.31 8080]
   Hashes of expected file:
    - SHA256:adb98eff3f89c685523614d3436e92fcd79119ed02af97e1d5ed9a91d1211d4d
    - SHA1:66dd2dd07b9f93c907c1d8c74169efdb7031fd89 [weak]
    - MD5Sum:358ecda0503c0b18d260a6c13cdefbf9 [weak]
    - Filesize:442640 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

### What did you expect to happen?

The mirrors should provide the correct file.

### How can we reproduce it (as minimally and precisely as possible)?

For example, building a container using the following Dockerfile will fail with the above error:

```
FROM debian:12
RUN \
  apt-get update -y \
  && apt-get --no-install-recommends --no-install-suggests dist-upgrade -Vy \
      ca-certificates \
      curl \
      gnupg \
  && curl https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_12/Release.key \
      | gpg --dearmor > /usr/share/keyrings/libcontainers-archive-keyring.gpg \
  && chmod 644 /usr/share/keyrings/libcontainers-archive-keyring.gpg \
  && echo "deb [signed-by=/usr/share/keyrings/libcontainers-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_12/ /" \
      > /etc/apt/sources.list.d/libcontainers.list \
  && apt-get update -y \
  && apt-get install -Vy libcap2-bin
```

### Anything else we need to know?

Possibly incomplete build or upload of the files to the OpenSUSE mirrors?

### CRI-O and Kubernetes version

Irrelevant

### OS version

Debian 12

### Additional environment details (AWS, VirtualBox, physical, etc.)

amd64

**Comment by kwilczynski** [comment]
@jaakristioja, thank you for getting in touch.

This, sadly, has nothing to do with CRI-O. Usually, when a mirror does a full synchronisation before the metadata is regenerated, these issues arise when you try to use such a mirror. You can try choosing a different mirror manually rather than rely on the redirect the Open Build Service (OBS) sends through.

You can also wait, and this issue should eventually resolve itself, as it usually does.

**Comment by jaakristioja** [comment]
> This, sadly, has nothing to do with CRI-O. Usually, when a mirror does a full synchronisation before the metadata is regenerated, these issues arise when you try to use such a mirror. You can try choosing a different mirror manually rather than rely on the redirect the Open Build Service (OBS) sends through.
> 
> You can also wait, and this issue should eventually resolve itself, as it usually does.

The issue did resolve itself, but I think it was unlikely that this was the case, because identical wrong files were present on multiple different mirrors.

Please also see https://github.com/openSUSE/MirrorCache/issues/440#issuecomment-1855407491 for an alternative explanation.

**Comment by kwilczynski** [comment]
@jaakristioja, thank you for the follow-up.

So it's more with us building a new package with the same name, which is different—provided that I understand the linked comment correctly.

@saschagrunert, if this something we should address, perhaps implement the workaround they suggest? Not sure if we want some release numbers to be appended automatically to our version number - it would look slightly awkward with it per (an example):

```
1.28.1~0-3
```

Unless the release is appended before the `~0`, which would be more sensible, per (an example):

```
1.28.1-3~0
```

Thoughts?

**Comment by saschagrunert** [comment]
For the old kubic repos I would not change anything at all to avoid breaking changes. But for the new [packaging](https://github.com/cri-o/packaging) ones we could define how we want it.
