### ISSUE TITLE
How to set cgroup to cgroupfs for CRI-O?

### ISSUE THREAD

**Issue by luomengY** [cri-o/cri-o#7605]
### What happened?

When I set the  ”--cgroup-manager“ of CRI-O to cgroupfs, I restarted CRIO and found that CRIO failed to start.

### What did you expect to happen?

When I set the cgroup manager of CRI-O to cgroupfs, CRIO can be used normally.

### How can we reproduce it (as minimally and precisely as possible)?

1. Set "ExecStart=/usr/local/bin/crio  --cgroup-manager cgroupfs " in crio. service.
2. Execution: 
    sudo systemctl daemon-reload
    sudo systemctl enable --now crio
    sudo systemctl restart crio

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# paste output here
```
v1.28.2
```console
$ kubectl version --output=json
# paste output here
```
v1.21.2
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
ubuntu 
$ uname -a
# paste output here
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
physical
</details>

**Comment by haircommander** [comment]
the kubelet version you mentioned is "v1.21.2" is that correct? also can we have the output of `crio --cgroup-manager cgroupfs`?
