### ISSUE TITLE
REQUEST: New organization membership for kannon92

### ISSUE THREAD

**Issue by kannon92** [cri-o/cri-o#7607]
### GitHub Username

@kannon92

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have one sponsor from the list of approvers in at least one OWNERS file within the CRI-O repository
- [X] I have spoken to my sponsor ahead of this application, and they have agreed to sponsor my application

### Sponsor

@haircommander

### List of contributions to the CRI-O project

PRs open: https://github.com/cri-o/cri-o/pulls?q=is%3Apr+is%3Aopen+kannon92
PRs closed/merged: https://github.com/cri-o/cri-o/pulls?q=is%3Apr+author%3A%40me+is%3Aclosed
I am a member of the crio org for kubernetes ci. This has mostly been focusing on keeping the CI running for CRIO.

**Comment by haircommander** [comment]
LGTM :)

**Comment by saschagrunert** [comment]
+1 from my side!

**Comment by haircommander** [comment]
invite sent :) welcome :tada:
