### ISSUE TITLE
`test/seccomp_notifier.bats` tests don't work on `linux/arm64`

### ISSUE THREAD

**Issue by saschagrunert** [cri-o/cri-o#7630]
https://github.com/cri-o/cri-o/pull/7620 shows that the tests have to be disabled to let the CI pass on the linux/arm64 platform.

Goal of this issue is to investigate why the tests fail and fix them appropriately.

/help
/good-first-issue

**Comment by LufffyZoro** [comment]
Hi @saschagrunert,

I may not be a developer, but I've been digging into the logs for "integration/cgroupfs/amd64" and came across a couple of errors causing the CI job to fail:

Error 1: level=fatal msg="validating runtime config: monitor fields translation: failed to translate monitor fields for runtime runc: cgroupfs manager conmon cgroup should be 'pod' or empty" file="crio/main.go:459"

Error 2: level=fatal msg="validate service connection: validate CRI v1 runtime API for endpoint \"unix:///tmp/tmp.Kv2d2j3L55/crio.sock\": rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial unix /tmp/tmp.Kv2d2j3L55/crio.sock: connect: no such file or directory\"

This is my first dive into this, and I'd love to hear your thoughts on this!

**Comment by haircommander** [comment]
good find @LufffyZoro . error 1 would be the cause, and error 2 is the symptom. If crio doesn't start (error 1) then crictl can't connect to it (error 2). We'll need to update the config of the test to correctly be configured for cgroupfs

**Comment by saschagrunert** [comment]
@LufffyZoro thank you for the investigation, are you interested in contributing the fix?

**Comment by LufffyZoro** [comment]
@saschagrunert,

Yes, though I'm new to all this, I might need some help, still, I'll try my best to resolve this issue.

**Comment by hasan4791** [comment]
Hey, is this still an issue? I tried today on main branch by removing the arch check, which works fine on aarch64. 

```
++ bats --jobs 4 --tap seccomp_notifier.bats
1..4
ok 1 seccomp notifier with runtime/default
ok 2 seccomp notifier with runtime/default but not stop
ok 3 seccomp notifier with custom profile
ok 4 seccomp notifier should not work if annotation is not allowed

real	0m16.794s
user	0m18.542s
sys	0m4.982s

real	0m31.206s
user	0m25.461s
sys	0m8.149s
[root@toolbox cri-o]# uname -a
Linux toolbox 6.7.9-200.fc39.aarch64 #1 SMP PREEMPT_DYNAMIC Wed Mar  6 20:03:23 UTC 2024 aarch64 GNU/Linux
[root@toolbox cri-o]#
```

**Comment by saschagrunert** [comment]
@hasan4791 maybe not, do you want to propose the CI update to not exclude them?

**Comment by saschagrunert** [comment]
This is done
