### ISSUE TITLE
DEB packages for v1.29 are missing

### ISSUE THREAD

**Issue by msschl** [cri-o/cri-o#7631]
### What happened?

Probably same as in #7247

[Packages of v1.29 for APT based repositories](https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.29/xUbuntu_22.04/amd64/) is not found and got 404 page.

### What did you expect to happen?

It should be available.

### How can we reproduce it (as minimally and precisely as possible)?

View the URL from a browser.

### CRI-O and Kubernetes version

v1.29

### OS version

All APT based distributives: Ubuntu, Debian, Raspbian

### Additional environment details (AWS, VirtualBox, physical, etc.)

Any APT based OS.

**Comment by msschl** [comment]
Is there a delay after a release on github until the packages are available on opensuse?
Otherwise is there anything that can make the publish process to the package registry more reliable?

**Comment by saschagrunert** [comment]
Yes, there is a slight delay. But the packages are available now on https://github.com/cri-o/packaging

**Comment by msschl** [comment]
Trying to add the new key `https://pkgs.k8s.io/core:/stable:/1.29/deb/Release.key` results in a 403

**Comment by saschagrunert** [comment]
@msschl that's because the CDN cache needs to be populated first. Let's give it 1-2 hours and please try again.

**Comment by msschl** [comment]
Ok, we now switched to the new CRI-O pkgs.k8s.io package repository.
It is working fine after waiting for a 2 hours
