### ISSUE TITLE
ocp static pod has no need to set pod as privileged: true

### ISSUE THREAD

**Issue by lance5890** [cri-o/cri-o#7695]
1. I find the openshift static pod use securityContext: privileged: true, which has security Risk, and I found the original PR is https://github.com/openshift/cluster-kube-apiserver-operator/pull/629  @haircommander

2. By default pods that run as root will have write access to the file system exposed by hostPath

3. I have also checked the crio etcd container config in "/var/lib/containers/storage/overlay-containers/xxxx/userdata/config.json", it show as follows without privileged: true option:

maybe we just need read and write option to the /var/lib/etcd dir , compared the etcd container with privileged: true , the main diffrences are in the capabilities option

```
             "user": {
                        "uid": 0,
                        "gid": 0,
                        "additionalGids": [
                                0
                        ]
                },
               "capabilities": {
                        "bounding": [
                                "CAP_CHOWN",
                                "CAP_DAC_OVERRIDE",
                                "CAP_FSETID",
                                "CAP_FOWNER",
                                "CAP_SETGID",
                                "CAP_SETUID",
                                "CAP_SETPCAP",
                                "CAP_NET_BIND_SERVICE",
                                "CAP_KILL"
                        ],
                        "effective": [
                                "CAP_CHOWN",
                                "CAP_DAC_OVERRIDE",
                                "CAP_FSETID",
                                "CAP_FOWNER",
                                "CAP_SETGID",
                                "CAP_SETUID",
                                "CAP_SETPCAP",
                                "CAP_NET_BIND_SERVICE",
                                "CAP_KILL"
                        ],
                        "permitted": [
                                "CAP_CHOWN",
                                "CAP_DAC_OVERRIDE",
                                "CAP_FSETID",
                                "CAP_FOWNER",
                                "CAP_SETGID",
                                "CAP_SETUID",
                                "CAP_SETPCAP",
                                "CAP_NET_BIND_SERVICE",
                                "CAP_KILL"
                        ]
                },

....
                {
                        "destination": "/var/lib/etcd/",
                        "type": "bind",
                        "source": "/var/lib/etcd",
                        "options": [
                                "rw",
                                "rbind",
                                "rprivate",
                                "bind"
                        ]
                }

```

/help

**Comment by haircommander** [comment]
yeah this is more of a question about openshift's security framework. I can put on my openshift engineer hat to answer, but upstream cri-o isn't the appropriate place for openshift questions :) 

basically: the openshift release payload (which includes KAS operator) is a set of trusted pods that are allowed to have privilege. It's a tool they need to do the important work they need to. The biggest risk of privilege is giving it to something untrusted.

that said, I think you're correct the KAS operator could potentially do without privilege. it's a pretty heavy hammer. I think this would be best tracked as an issue in the openshift org

**Comment by lance5890** [comment]
> yeah this is more of a question about openshift's security framework. I can put on my openshift engineer hat to answer, but upstream cri-o isn't the appropriate place for openshift questions :)
> 
> basically: the openshift release payload (which includes KAS operator) is a set of trusted pods that are allowed to have privilege. It's a tool they need to do the important work they need to. The biggest risk of privilege is giving it to something untrusted.
> 
> that said, I think you're correct the KAS operator could potentially do without privilege. it's a pretty heavy hammer. I think this would be best tracked as an issue in the openshift org

sorry for misleading, thanks all the same
