### ISSUE TITLE
Is it possible make CRI-O prefer mirror registry from registries.conf than from the internet?

### ISSUE THREAD

**Issue by engineater** [cri-o/cri-o#7713]
Is it possible make CRI-O prefer mirror registry from registries.conf than from the internet?

My settings for CRI-O looks like this
```console
$ cat <<EOF >> /etc/containers/registries.conf
[[registry]]
  prefix=""
  location = "quay.io"
  blocked = false

  [[registry.mirror]]
    location = "192.168.1.100:8133"
    insecure = true
EOF
```

So the "192.168.1.100:8133" is my proxy mirror registry for https://quay.io .
If my host has  strait access throw the internet to https://quay.io then CRI-O prefer pull images from https://quay.io than from mirror registry "192.168.1.100:8133".

So what I do:
```console
$ cat <<EOF >> /etc/hosts
0.0.0.0     quay.io
EOF
```

And after this CRI-O pull quay.io's images  only from "192.168.1.100:8133", this what i want.

Question is:  Does CRI-O have more elegant solution to set prefere pull images from mirror registry than the internet?

**Comment by kwilczynski** [comment]
@engineater, thank you for getting in touch!

You basically want a redirect or a rewrite type of thing? I am not sure if that can be done...

A simple redirect can be done as follows (a classic example):

```toml
[[registry]]
prefix = "docker.io"
location = "mirror.gcr.io"
```

However, this heavily relies on tags parity and for local registries might be cumbersome to use.

CRI-O supports setting up HTTP and HTTPS proxies for pulling images. Would this work for you?

**Comment by kwilczynski** [comment]
@engineater, to add.

This is not a limitation of CRI-O per se, it's related to what the [containers/conmon](https://github.com/containers/common) package offers, which CRI-O uses internally.

**Comment by engineater** [comment]
@kwilczynski, thank you for your answer.

What I have done:
```console
$ vi /etc/hosts
### delete this line
# 0.0.0.0     quay.io

# in this file
$ vi /etc/containers/registries.conf
### ### replace this block
###[[registry]]
###  prefix=""
###  location = "quay.io"
###  blocked = false

###  [[registry.mirror]]
###    location = "192.168.1.100:8133"
###    insecure = true

### ### on this one
[[registry]]
  prefix="quay.io"
  location = "192.168.1.100:8133"
  blocked = false
  insecure = true
```

And this  work for me 😉

**Comment by kwilczynski** [comment]
@engineater, I am glad this approach worked for you! :tada:
