### ISSUE TITLE
crio stuck without any logs

### ISSUE THREAD

**Issue by lance5890** [cri-o/cri-o#7740]
### What happened?

1. we found the node notready,  as the container runtime is unvailable, and then kubelet set the node status to notready

![image](https://github.com/cri-o/cri-o/assets/30207518/f574bbba-4163-49f2-8854-5619a81822bd)

2. we found the crio status is active, but the crio do not print logs anymore about one day ago(02-05 14:31:55), but when we restart the crio(02-06 11:55:15), it can recover again

![image](https://github.com/cri-o/cri-o/assets/30207518/75a8801f-d146-4f9a-81ec-a629df48e638)

![image](https://github.com/cri-o/cri-o/assets/30207518/6b473b27-8b25-48fd-b04c-c5adae41c5dc)

3. I have check the dmesg log and the sar info, these infos are normal

### What did you expect to happen?

1 do we have any other logs to know what happened with cri-o
2 if there is some way to recover cri-o automatically when it no longer worked

### How can we reproduce it (as minimally and precisely as possible)?

has no idea

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# paste output here
crio version 1.25.4
Version:        1.25.4

```

```console
$ kubectl version --output=json
# paste output here
v1.25.8
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
5.15.131-3.cl9.x86_64
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by lance5890** [comment]
@haircommander  @kwilczynski

**Comment by saschagrunert** [comment]
@lance5890 you can switch to `log_level = "debug"`, but those are pretty large.

Is something like `sudo crictl ps` possible when in that state?

**Comment by lance5890** [comment]
> @lance5890 you can switch to `log_level = "debug"`, but those are pretty large.
> 
> Is something like `sudo crictl ps` possible when in that state?

The cri-o is already restarted when I check the cri-o log, I have no idea if the crictl ps can show containers or not.

Do u have ever encountered this situation before?

**Comment by saschagrunert** [comment]
@lance5890 not sure if exactly, but under system pressure and low available resources it could be possible that socket connection is not responding.

**Comment by kwilczynski** [comment]
@lance5890, was your system under memory pressure? Were there any OOM kills in the kernel ring buffer (`dmesg`)?

Also, when this happened, was the CPU heavily utilised? I see your CRI-O used (before the restart) relatively a lot of memory as reported per `systemctl status` (I wish we had `/proc/$(pidof crio)/status` from that time), which makes me think this is a busy system (worker node).

**Comment by kwilczynski** [comment]
@lance5890, any update? Are there any more issues?

Or should we consider this issue a fluke and close it?
