### ISSUE TITLE
Mirror configuration automatic reload

### ISSUE THREAD

**Issue by phillebaba** [cri-o/cri-o#7748]
Currently cri-o supports reloading mirror configuration by either restarting the process or sending a SIGHUP signal to the process. In comparison Containerd reload the mirror configuration every time an image is pulled. Would there be interest in exploring the possibility of automatically reloading mirror configuration?

The reason I am asking is because I am looking at adding support for cri-o in my project https://github.com/XenitAB/spegel/. One of the blockers right now is that the end user experience would be a lot more complicated for cri-o users if they have to figure out some method of writing mirror configuration on their own.

**Comment by kwilczynski** [comment]
@phillebaba, thank you for getting in touch!

Just so we understand better. The ideal scenario would be when spegel drops a newly generated mirror configuration drop-in in a dot-d directory, and then CRI-O picks it up and reloads its internal state, correct? Or do you want to have an API of sorts to call?

Theoretically, we could have a directory watch and even support the current approach that containerd employs. I suppose this would be hidden behind some option to enable this feature.

**Comment by phillebaba** [comment]
I think that either solution would work. Right now Spegel will write the Containerd mirror configuration before starting, by mounting the host path. An API would work just as well but I would guess that it would be just more complicated. I have had requests to specifically support Open Shift which would also add a lot of other complexity in regards to security constraints that I have not looked at yet. I also know of vanilla Kubernetes users who are running cri-o on some or all nodes.

**Comment by haircommander** [comment]
Intersting idea! setting an inotify on the registry paths could work. Something to note: in the past, I have heard hesitation about updating registries without a drain/reboot because it hides potential misconfiguration in future pull image failures. Not opposed, just mentioning there may be cases where even if we do this, we still want to drain/reboot between updates to make sure misconfiguration is identified easier

**Comment by haircommander** [comment]
@phillebaba agreed! I think the delayed failure on incorrect value is the trouble. That said, it would end up being delayed with a reboot and `IfNotPresent` or `Never` pull policies anyway, so there's only so much we can do.

All that is to say, I'm interested in helping support this case. Do you have any interest adding support in cri-o for inotify based configuration reload @phillebaba ?
