### ISSUE TITLE
Issue creating oci hooks with Minikube

### ISSUE THREAD

**Issue by ChucklesDroid** [cri-o/cri-o#7789]
### What happened?

This issue follows the email conversation I had with @sohankunkerkar . I was trying to setup sample oci hooks using minikube with crio as container runtime. The minikube cluster was ran with the following command: `minikube start --container-runtime=crio` , on doing so it automatically selected the kvm2 driver with K8s version 1.28.3 and crio version 1.24.1. Following this hooks.json file was placed in `/usr/share/containers/oci/hooks.d` along with hook script(it had the reqd executable permissions) which only contained the createContainer hook in it inside the vm(minikube ssh). I also checked the `/etc/crio/crio.conf` to make sure hooks directory was set correctly. I tried to look for logs in the location as specified by crio.conf but found that `/var/logs/crio/pods/` was empty.
UPDATE: added the log data in a gist and linked it in the comment below

Hooks.json is as follows:
```
{
  "version": "1.0.0",
  "hooks": {
    "createContainer": [
      {
        "path": "/usr/share/containers/oci/hooks.d/create-container.sh"
      }
    ]
  },
  "when": {
    "always": "true"
  },
  "stages": ["createContainer"]
}

```

create-container.sh is as follows:
```
#! /usr/bin/bash
# SPDX-FileCopyrightText: 2024 Aakarsh MJ <mj.akarsh@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

export KUBEARMOR_LOG_FILE="/home/$USER/kubearmor.log"
echo "create-container-executed": $(date -I) $(date +%T) >> $KUBEARMOR_LOG_FILE
```

### What did you expect to happen?

I expected the create-contaner.sh to run when I created a new pod. This script would set an environment variable and create a log file containing the time when script was run but neither of them was created.

### How can we reproduce it (as minimally and precisely as possible)?

By placing the hooks.json and create-container.sh in `/usr/share/containers/oci/hooks.d/` or any of the hooks dir location specified by `/etc/crio/crio.conf`. I have provided the contents of both hooks.json and create-container.sh above.

### Anything else we need to know?

Following was the output of `minikube start --container-runtime=crio`:
![minikube-start](https://github.com/cri-o/cri-o/assets/71250179/01f2468d-7d4e-42fd-ad35-412faa247da2)

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# Obtained from the minikube vm
crio version 1.24.1
Version:          1.24.1
GitCommit:        a3bbde8a77c323aa6a485da9a9046299155c6016
GitTreeState:     dirty
BuildDate:        2023-11-07T07:32:32Z
GoVersion:        go1.19.9
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        exclude_graphdriver_devicemapper, containers_image_ostree_stub, seccomp
SeccompEnabled:   true
AppArmorEnabled:  false

```

```console
$ kubectl version --output=json
# Obtained from the host machine
{
  "clientVersion": {
    "major": "1",
    "minor": "26",
    "gitVersion": "v1.26.12",
    "gitCommit": "df63cd7cd818dd2262473d2170f4957c6735ba53",
    "gitTreeState": "archive",
    "buildDate": "2024-01-09T00:00:00Z",
    "goVersion": "go1.20.12",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v4.5.7",
  "serverVersion": {
    "major": "1",
    "minor": "28",
    "gitVersion": "v1.28.3",
    "gitCommit": "a8a1abc25cad87333840cd7d54be2efaf31a3177",
    "gitTreeState": "clean",
    "buildDate": "2023-10-18T11:33:18Z",
    "goVersion": "go1.20.10",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
WARNING: version difference between client (1.26) and server (1.28) exceeds the supported minor version skew of +/-1

```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
NAME="Fedora Linux"
VERSION="38 (KDE Plasma)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (KDE Plasma)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="KDE Plasma"
VARIANT_ID=kde

$ uname -a
# paste output here
Linux fedora 6.6.9-100.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Jan  1 20:31:07 UTC 2024 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
Minikube was used to setup the cluster.
</details>

**Comment by ChucklesDroid** [comment]
Hi I was able to get log data using `journalctl -u crio`. I have added the data in this gist file: https://gist.github.com/ChucklesDroid/d3285f7ef1dd262223b2044918aeec01

**Comment by sohankunkerkar** [comment]
@ChucklesDroid Thank you for raising this issue. Upon reviewing the crio logs, it appears that the following error occurred:
```sh
level=error msg="Failed loading hooks for /usr/share/containers/oci/hooks.d/hooks.json: parsing hook \"/usr/share/containers/oci/hooks.d/hooks.json\": 1.0.0: json: cannot unmarshal string into Go struct field When.when.always of type bool" file="hooks/monitor.go:55"
```
It seems like the value of `always` in the hooks.json file needs to be a boolean. Please consider updating it accordingly. I believe this adjustment should address the issue.

**Comment by ChucklesDroid** [comment]
That definitley helped out. However I am still unable to run the script. So after I changed it to boolean value. It complained about missing property hook:path. So I had to update json to the following:
```
{
  "version": "1.0.0",
  "hook": {
    "path": "/usr/share/containers/oci/hooks.d/create-container.sh"
  },
  "when": {
    "always": true
  },
  "stages": ["createContainer"]
}

```
* So a question arises is  [this](https://github.com/opencontainers/runtime-spec/blob/v1.0.2/config.md#posix-platform-hooks) outdated or am I understanding it wrong ?
* Also I can now see that hooks.json was accepted however my script still didnt run:
```
Feb 18 03:22:59 minikube crio[714]: time="2024-02-18 03:22:59.057434927Z" level=debug msg="hook hooks.json matched; adding to stages [createContainer]" file="hooks/hooks.go:111"
```
I had provided 0755 permissions to the bash script specified above, is there something wrong with the bash script used?

**Comment by kwilczynski** [comment]
@ChucklesDroid, some documentation around hooks can be found at the following:

- [containers/common/pkg/hooks/README.md](https://github.com/containers/common/tree/main/pkg/hooks/README.md)
- [containers/common/pkg/hooks/docs/oci-hooks.5.md](https://github.com/containers/common/blob/main/pkg/hooks/docs/oci-hooks.5.md)

Would this help?

**Comment by ChucklesDroid** [comment]
Hi @kwilczynski , Thanks for responding !
I have gone through both of those resources and found 2 conflicting docs which mentioned about the schema related to hooks. [posix-platform-hooks](https://github.com/opencontainers/runtime-spec/blob/v1.0.2/config.md#posix-platform-hooks) and the [hooks schema](https://github.com/containers/common/blob/main/pkg/hooks/docs/oci-hooks.5.md) like I mentioned in my previous comment.

Looking at the [logs](https://gist.github.com/ChucklesDroid/8ac4965a5682a2a25ecd0b968f9ae0ba) the hooks.json seem to be accepted as noted by this line in the log:
```
Feb 18 03:22:59 minikube crio[714]: time="2024-02-18 03:22:59.057434927Z" level=debug msg="hook hooks.json matched; adding to stages [createContainer]" file="hooks/hooks.go:111"
```
However the bash script didn't run.(The bash script can be found above specified in the issue). So I am a bit confused what might be going wrong on my end with the script

**Comment by kwilczynski** [comment]
@ChucklesDroid, try running CRI-O with the the `debug` log level set.

Perhaps you can spot something in the more verbose output.

That said, you can also update your script such that there is some logging added. For example:

```shell
#!/usr/bin/env bash
exec 1> /tmp/hook.log 2>&1
set -ex

env

KUBEARMOR_LOG_FILE="/tmp/kubearmor.log"
echo "create-container-executed": $(date -I) $(date +%T) >> $KUBEARMOR_LOG_FILE
```

However, just looking at your original script, I am sure that the `$USER` variable might be set to a different user that you expect (or even unset in some cases as there is no guarantee for it to be present), since it's CRI-O that would run this script in the end, and you might have no permission to write to the location where the directory is pointing to (also, I assume that there is no `/home/root` on your file system at the moment). You have no error control enabled in your script (the `set -e`), as such, it will fail silently.

**Comment by ChucklesDroid** [comment]
I am in tears Thank you for your help @kwilczynski it finally works !! You were right about $USER variable. I found this in the log file:
```
+ export KUBEARMOR_LOG_FILE=/home//kubearmor.log
+ KUBEARMOR_LOG_FILE=/home//kubearmor.log
```

Just one more thing I need to clarify. Whats the difference between [posix-platform-hooks](https://github.com/opencontainers/runtime-spec/blob/v1.0.2/config.md#posix-platform-hooks) and [hooks-schema](https://github.com/containers/common/blob/main/pkg/hooks/docs/oci-hooks.5.md)?

**Comment by sohankunkerkar** [comment]
>Just one more thing I need to clarify. Whats the difference between [posix-platform-hooks](https://github.com/opencontainers/runtime-spec/blob/v1.0.2/config.md#posix-platform-hooks) and [hooks-schema](https://github.com/containers/common/blob/main/pkg/hooks/docs/oci-hooks.5.md)?

Yeah, this is an interesting question. CRI-O follows the [hooks-schema](https://github.com/containers/common/blob/main/pkg/hooks/docs/oci-hooks.5.md) in containers/common to execute OCI hooks in Kubernetes. The schema details haven't changed for more than four years now. I suspect there might be a slight divergence from [OpenContainers/runtime-spec](https://github.com/opencontainers/runtime-spec/blob/v1.0.2/config.md#posix-platform-hooks) concerning the `hooks` aspect, at least.

@cri-o/cri-o-maintainers Any idea here?

**Comment by kwilczynski** [comment]
As far as I can tell (from looking at both links to hooks documentation), the `containers/common` package defined its own hooks schema, which CRI-O implemented. It does not look like the Open Containres one has been implemented.

**Comment by saschagrunert** [comment]
The [hooks of the runtime spec](https://github.com/opencontainers/runtime-spec/blob/v1.0.2/config.md#posix-platform-hooks) are implemented by runc / crun, while OCI hooks are a thing supported by CRI-O itself.

**Comment by kwilczynski** [comment]
@ChucklesDroid, now that you have things working, can we close this issue?

**Comment by ChucklesDroid** [comment]
yes lets close this @kwilczynski. Thank you everyone for your help, I appreciate that
