### ISSUE TITLE
Kubernetes pod require authentication from private registry

### ISSUE THREAD

**Issue by cloudcafetech** [cri-o/cri-o#7808]
### What happened?

Trying to install pod used image from private registry (10.182.0.22:5000) .
Added insecure registry in crio.conf file. 

Error throwing as below

```
Warning  Failed     23s                kubelet            Error: ImagePullBackOff
  Normal   Pulling    12s (x2 over 23s)  kubelet            Pulling image "10.182.0.22:5000/flannel/flannel-cni-plugin:v1.4.0-flannel1"
  Warning  Failed     12s (x2 over 23s)  kubelet            Failed to pull image "10.182.0.22:5000/flannel/flannel-cni-plugin:v1.4.0-flannel1": reading manifest v1.4.0-flannel1 in 10.182.0.22:5000/flannel/flannel-cni-plugin: authentication required
  Warning  Failed     12s (x2 over 23s)  kubelet            Error: ErrImagePull
```

### What did you expect to happen?

POD should pull images from private registry.

Seems its need to authenticate the private registry.
Is there any where (configuration) I can put Registry credentials ?

any solution ?

### How can we reproduce it (as minimally and precisely as possible)?

Kubeadm 1.28
Private Registry docker container

### Anything else we need to know?

FYI , I am able to pull image from Private registry using crictl command

```
more /etc/crio/crio.conf | grep insecure_regis
# this file. Otherwise, leave   insecure_registries and registries commented out to
#   insecure_registries = [
  insecure_registries = [ "10.182.0.22:5000" ]

```
```
root@master1:~# crictl pull --creds admin:adminpass 10.182.0.22:5000/flannel/flannel-cni-plugin:v1.4.0-flannel1
Image is up to date for 10.182.0.22:5000/flannel/flannel-cni-plugin@sha256:5e95ad3829908270d491b55787467c96c343f0e169878ddcf6ce6b0f80609c0a
```

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# paste output here
```
crio version 1.26.4
Version:        1.26.4
GitCommit:      unknown
GitCommitDate:  unknown
GitTreeState:   clean
BuildDate:      2023-08-22T06:53:41Z
GoVersion:      go1.19
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:
  apparmor
  seccomp
  containers_image_ostree_stub
  exclude_graphdriver_btrfs
  exclude_graphdriver_devicemapper
  containers_image_openpgp
LDFlags:          -s -w -X github.com/cri-o/cri-o/internal/pkg/criocli.DefaultsPath="" -X github.com/cri-o/cri-o/internal/version.buildDate=2023-08-22T06:53:41Z
SeccompEnabled:   true
AppArmorEnabled:  true
Dependencies:

```console
$ kubectl version --output=json
# paste output here
```{
  "clientVersion": {
    "major": "1",
    "minor": "28",
    "gitVersion": "v1.28.7",
    "gitCommit": "c8dcb00be9961ec36d141d2e4103f85f92bcf291",
    "gitTreeState": "clean",
    "buildDate": "2024-02-14T10:40:48Z",
    "goVersion": "go1.21.7",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v5.0.4-0.20230601165947-6ce0bf390ce3",
  "serverVersion": {
    "major": "1",
    "minor": "28",
    "gitVersion": "v1.28.6",
    "gitCommit": "be3af46a4654bdf05b4838fe94e95ec8c165660c",
    "gitTreeState": "clean",
    "buildDate": "2024-01-17T13:39:00Z",
    "goVersion": "go1.20.13",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by kwilczynski** [comment]
@cloudcafetech, were you able to configure authentication?

If so, then I would like to close this issue, if that's OK.

**Comment by kwilczynski** [comment]
I will close this issue now. I hope you were able to use the suggested setting to authenticate with the registry successfully.
