### ISSUE TITLE
Is there a document that lists best practices to follow while using CRI-O

### ISSUE THREAD

**Issue by alpana17** [cri-o/cri-o#7841]
As there is hardening guideline from CIS for Docker, is there some hardening guideline for CRI-O or may be some document that lists best practices to be followed while using CRI-O?
It can have list like:
- permission of conf files?
- any setting that should not be assigned particular value
 or any other guideline

**Comment by kwilczynski** [comment]
@alpana17, thank you for reaching out!

Would you mind moving this question to our [discussions](https://github.com/cri-o/cri-o/discussions) section?

**Comment by alpana17** [comment]
@kwilczynski It can be moved to discussions. No issues with me

**Comment by kwilczynski** [comment]
@alpana17, converting issues to discussions is currently or still, rather, broken on GitHub, sadly.

As such, I will close this issue, and you can open a discussion item. Sorry for the inconvenience.
