### ISSUE TITLE
cri-o v1.29 for s390x

### ISSUE THREAD

**Issue by MaryJulian17** [cri-o/cri-o#7911]
Hi, I'm on Ubuntu_20.04, looking at the https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.29/deb repo, and I don't see any s390x images. Is s390x still supported?

**Comment by saschagrunert** [comment]
Hey @MaryJulian17, not yet. We're working on it in https://github.com/cri-o/packaging/pull/79.

**Comment by saschagrunert** [comment]
That's done. @MaryJulian17 do you have a change to test the binaries and packages somewhere?

**Comment by MaryJulian17** [comment]
> That's done. @MaryJulian17 do you have a change to test the binaries and packages somewhere?

Thank you, I've been testing it today, and can't seem to get past a segfault when trying to start the crio service. I see:

Apr 22 18:48:43 2a6a24511454 systemd[1]: Starting Container Runtime Interface for OCI (CRI-O)...
Apr 22 18:48:43 2a6a24511454 kernel: User process fault: interruption code 0010 ilc:3 in crio[1000000+2e08000]
Apr 22 18:48:43 2a6a24511454 kernel: User PSW : 0705000180000000 0000000002924b9e
Apr 22 18:48:43 2a6a24511454 kernel:           R:0 T:1 IO:1 EX:1 Key:0 M:1 W:0 P:1 AS:0 CC:0 PM:0 RI:0 EA:3
Apr 22 18:48:43 2a6a24511454 kernel: User GPRS: 0000000000000000 0000000000000000 0000000000000000 0000000000000000
Apr 22 18:48:43 2a6a24511454 kernel:           0000000003e49ac0 0000000000000000 0000000000000000 000003ffd4cfeda8
Apr 22 18:48:43 2a6a24511454 kernel:           0000000000000000 0000000000000000 000003ffd4cfed68 0000000003f4eac8
Apr 22 18:48:43 2a6a24511454 kernel:           000003ff9db65ca0 00000000031acec8 0000000000000000 000003ffd4cfec88
Apr 22 18:48:43 2a6a24511454 kernel: User Code: 0000000002924b8e: e310a0000004#011lg#011%r1,0(%r10)#012           0000000002924b94: b9040001#011#011lgr#011%r0,%r1#012          #0000000002924b98: e300a0080008#011ag#011%r0,8(%r10)#012          >0000000002924b9e: e3e080080004#011lg#011%r14,8(%r8)#012           0000000002924ba4: e3e0f0a00024#011stg#011%r14,160(%r15)#012           0000000002924baa: a7210004#011#011tmll#011%r2,4#012           0000000002924bae: 41b31000#011#011la#011%r11,0(%r3,%r1)#012           0000000002924bb2: a7840007#011#011brc#0118,0000000002924bc0
Apr 22 18:48:43 2a6a24511454 kernel: Last Breaking-Event-Address:
Apr 22 18:48:43 2a6a24511454 kernel: [<0000000002924ad0>] 0x2924ad0
Apr 22 18:48:43 2a6a24511454 systemd[1]: crio.service: Main process exited, code=dumped, status=11/SEGV
Apr 22 18:48:43 2a6a24511454 systemd[1]: crio.service: Failed with result 'core-dump'.

**Comment by MaryJulian17** [comment]
After a bit more investigation, I found that the 'crio-conmon' executable was throwing the segfault.

**Comment by saschagrunert** [comment]
@MaryJulian17 we build all of them using nixpkgs using `crossSystem`:
```nix
(import ./nixpkgs.nix {
  crossSystem = {
    config = "s390x-unknown-linux-gnu";
  };
  overlays = [ (import ./overlay.nix) ];
}).callPackage ./derivation.nix
{ }
```
https://github.com/cri-o/cri-o/blob/main/nix/default-s390x.nix

I was wondering if a nixpkgs update (to the latest `master` magically resolves that issue), but that's blocked on https://github.com/NixOS/nixpkgs/pull/302574 for now.

**Comment by MaryJulian17** [comment]
I think that matches what we're seeing. When I build cri-o on a s390x machine or using go cross compile, I don't see a segfault. When I use the exectuables from the packaged rpm or release artifact, cri-o, crio-conmon, and crio-run immediatly return a segfault.

**Comment by kwilczynski** [comment]
> I think that matches what we're seeing. When I build cri-o on a s390x machine or using go cross compile, I don't see a segfault. 
> [...]

Thank you for doing this! I was about to ask whether this was the case.

**Comment by saschagrunert** [comment]
I think the issue is related to `glibc.static`. When building CRI-O without statically linking by applying this patch:

```patch
diff --git a/nix/derivation.nix b/nix/derivation.nix
index 5668337f3..38b68ad77 100644
--- a/nix/derivation.nix
+++ b/nix/derivation.nix
@@ -17,7 +17,7 @@ with pkgs; buildGo122Module {
   ];
   buildInputs = [
     glibc
-    glibc.static
+    #glibc.static
     gpgme
     libassuan
     libgpgerror
@@ -26,10 +26,7 @@ with pkgs; buildGo122Module {
     libselinux
   ];
   prePatch = ''
-    export CFLAGS='-static -pthread'
-    export LDFLAGS='-s -w -static-libgcc -static'
-    export EXTRA_LDFLAGS='-s -w -linkmode external -extldflags "-static -lm"'
-    export BUILDTAGS='static netgo osusergo exclude_graphdriver_btrfs exclude_graphdriver_devicemapper seccomp apparmor selinux'
+    export BUILDTAGS='exclude_graphdriver_btrfs exclude_graphdriver_devicemapper seccomp apparmor selinux'
     export CGO_ENABLED=1
     export CGO_LDFLAGS='-lgpgme -lassuan -lgpg-error'
     export SOURCE_DATE_EPOCH=0
diff --git a/pinns/Makefile b/pinns/Makefile
index 599ada4b1..c30dc3b68 100644
--- a/pinns/Makefile
+++ b/pinns/Makefile
@@ -3,7 +3,7 @@ obj = $(src:.c=.o)
 
 STRIP ?= strip
 override LIBS +=
-CFLAGS ?= -std=c99 -Os -Wall -Werror -Wextra -static
+CFLAGS ?= -std=c99 -Os -Wall -Werror -Wextra
 
 all: ../bin/pinns
```

Then I'm able to run CRI-O:

```
> qemu-s390x ./result/bin/crio --version
crio version 1.30.0
Version:        1.30.0
GitCommit:      13efa1ae1ad17a9cc8162275e6c290887c3ba28b
GitCommitDate:  2024-04-23T13:20:32Z
GitTreeState:   dirty
BuildDate:      1970-01-01T00:00:00Z
GoVersion:      go1.22.0
Compiler:       gc
Platform:       linux/s390x
Linkmode:       dynamic
BuildTags:
  exclude_graphdriver_btrfs
  exclude_graphdriver_devicemapper
  seccomp
  apparmor
  selinux
LDFlags:          unknown
SeccompEnabled:   false
AppArmorEnabled:  false
```

**Comment by saschagrunert** [comment]
Openedd https://github.com/NixOS/nixpkgs/issues/306473 for clairication. We can also consider switching to musl libc for s390x.
