### ISSUE TITLE
CRI-O v1.29.2

### ISSUE THREAD

**Issue by DVVolkov** [cri-o/cri-o#7912]
### What happened?

curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | gpg --dearmor -o /usr/share/keyrings/libcontainers-archive-keyring.gpg

gpg: no valid OpenPGP data found.

https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key 
Resource is no longer available! 404

### What did you expect to happen?

I'm waiting for an active link to the key

### How can we reproduce it (as minimally and precisely as possible)?

Reproduse:
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | gpg --dearmor -o /usr/share/keyrings/libcontainers-archive-keyring.gpg
or visit
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key 

### Anything else we need to know?

Internet access is available, VPN, proxy are not used

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
can`t install
```

```console
$ kubectl version --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "28",
    "gitVersion": "v1.28.8",
    "gitCommit": "fc11ff34c34bc1e6ae6981dc1c7b3faa20b1ac2d",
    "gitTreeState": "clean",
    "buildDate": "2024-03-15T00:07:05Z",
    "goVersion": "go1.21.8",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v5.0.4-0.20230601165947-6ce0bf390ce3"
}
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
# Linux node1.internal 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
VirtualBox
</details>

**Comment by saschagrunert** [comment]
@DVVolkov, the kubic repositories are deprecated in favor of https://github.com/cri-o/packaging

**Comment by haircommander** [comment]
where did you find where to download @DVVolkov ? I have opened a PR to update cri-o.io but I'd like to know if you heard of the old paths somewhere else

**Comment by DVVolkov** [comment]
@haircommander, i found it here https://github.com/cri-o/cri-o/blob/main/install.md#apt-based-operating-systems, and I'm surprised that this method didn't work for me

**Comment by kannon92** [comment]
We are trying to clear this up. https://github.com/cri-o/cri-o/pull/7924

**Comment by saschagrunert** [comment]
Can we close this one now?

**Comment by unixbird** [comment]
Just attempted this after a kubeadm upgrade to 1.29 and found that I get the same issue.

**Comment by saschagrunert** [comment]
As mentioned, the kubic (libcontainers/stable) repositories are deprecated in favor of https://github.com/cri-o/packaging
