### ISSUE TITLE
Installation instruction has wrong URI

### ISSUE THREAD

**Issue by ischilling** [cri-o/cri-o#7917]
### What happened?

The URI's in the installation instruction lead to **download.opensuse.org** - but that is wrong, to my understanding the location is meanwhile **pkgs.k8s.io**.

https://kubernetes.io/blog/2023/10/10/cri-o-community-package-infrastructure/ is one of the resources for the new? URI, at least this instruction works.

### What did you expect to happen?

package URI is correct

### How can we reproduce it (as minimally and precisely as possible)?

walk through your instructions

### Anything else we need to know?

the instruction at https://kubernetes.io/blog/2023/10/10/cri-o-community-package-infrastructure/ is working (even though not as versatile as the here given instruction). Also it does not support of crio-o-crunch...

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# paste output here
```

```console
$ kubectl version --output=json
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by kannon92** [comment]
Hey @ischilling could you point us to the instructions you used? We are trying to figure out how to best clean this up to make this more clear.

**Comment by haircommander** [comment]
https://github.com/cri-o/cri-o.io/pull/63 potentially fixes this

**Comment by sohankunkerkar** [comment]
https://github.com/cri-o/cri-o.io/pull/63 has merged. Closing this issue for now.
