### ISSUE TITLE
Crio 1.28.4 packages missing in repo for centos7 x86_64

### ISSUE THREAD

**Issue by grunlab** [cri-o/cri-o#7942]
### What happened?

Crio 1.28.4 packages missing in repo for centos7 x86_64

### What did you expect to happen?

Packages should be present

### How can we reproduce it (as minimally and precisely as possible)?

n/a

### Anything else we need to know?

n/a

### CRI-O and Kubernetes version

n/a

### OS version

n/a

### Additional environment details (AWS, VirtualBox, physical, etc.)

n/a

**Comment by isugimpy** [comment]
Also missing for xUbuntu_22.04 and others.

**Comment by haircommander** [comment]
I have triggered the builds! let me know if it works

**Comment by grunlab** [comment]
Hi,
For centos7 x86_64, all is ok
Thank you
