### ISSUE TITLE
crio v1.29.2 config reload does not update pinned_images

### ISSUE THREAD

**Issue by hexfusion** [cri-o/cri-o#7954]
### What happened?

```
$ crio --version
crio version 1.29.2-9.rhaos4.16.git5052e1a.el9
Version:        1.29.2-9.rhaos4.16.git5052e1a.el9
```
If I update pinned_images  config

```
[crio]
  [crio.image]
    pinned_images = ["quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:86d26e7ebcccd6f07a75db5b1e56283b25c2ee1c6a755d6ffc5a4d59beb9c504"]
```
reload service
```
$ systemctl reload crio.service
```
config appearss to reload correct after catching HUP signal.
```
$ journalctl -u crio | grep "pinned images"
Apr 02 17:44:09 ip-10-0-14-61 crio[1096516]: time="2024-04-02 17:44:09.569932578Z" level=info msg="Updated new pinned images: [quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:86d26e7ebcccd6f07a75db5b1e56283b25c2ee1c6a755d6ffc5a4d59beb9c504]
```

client reports the image as unpinned
```
crictl image --pinned quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:86d26e7ebcccd6f07a75db5b1e56283b25c2ee1c6a755d6ffc5a4d59beb9c504
IMAGE                                            TAG                 IMAGE ID            SIZE                PINNED
quay.io/openshift-release-dev/ocp-v4.0-art-dev   <none>              7948809a7f475       672MB               false
```
if I restart the service it shows pinned

### What did you expect to happen?

reload of config would update pinned_images

### How can we reproduce it (as minimally and precisely as possible)?

this was tested on nightly 4.16 payload

### CRI-O and Kubernetes version

```
$ crio --version
crio version 1.29.2-9.rhaos4.16.git5052e1a.el9
Version:        1.29.2-9.rhaos4.16.git5052e1a.el9
```

kubelet --version
Kubernetes v1.29.2+258f1d5

### OS version

```
Linux ip-10-0-14-61 5.14.0-432.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Mar 20 20:26:59 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
```
# cat /etc/os-release
NAME="CentOS Stream CoreOS"
ID="rhcos"
ID_LIKE="rhel fedora"
VERSION="416.94.202403300731-0"
VERSION_ID="4.16"
VARIANT="CoreOS"
VARIANT_ID=coreos
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream CoreOS 416.94.202403300731-0"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:9::coreos"
HOME_URL="https://centos.org/"
DOCUMENTATION_URL="https://docs.okd.io/latest/welcome/index.html"
BUG_REPORT_URL="https://access.redhat.com/labs/rhir/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.16"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.16"
OPENSHIFT_VERSION="4.16"
RHEL_VERSION=9.4
OSTREE_VERSION="416.94.202403300731-0"
```

### Additional environment details (AWS, VirtualBox, physical, etc.)

aws OCP 4.16 nightly

**Comment by haircommander** [comment]
yeah we have to opt-into config options being reloaded instead of having it happen by default. We can definitely update cri-o to do so for pinned images. @cri-o/cri-o-maintainers any takers?

**Comment by roman-kiselenko** [comment]
I have some cycles.
/assign

**Comment by haircommander** [comment]
ah so we do have code that updates, but i think we cache the pinned field in the image store: https://github.com/cri-o/cri-o/blob/main/internal/storage/image.go#L58 
So we'll need to invalidate the cache entries, or just update the fields somehow...

**Comment by kwilczynski** [comment]
I wonder if this is somehow marginally related?

- https://github.com/cri-o/cri-o/issues/7586

**Comment by sohankunkerkar** [comment]
It seems like the initial implementation works only when CRI-O restarts. One thing we can do here is to update the image cache only when there's a change to the list of pinned_images, and we can have a corresponding function in `internal/storage/image.go` called `UpdateImageCache` to update the Pinned field for a given image. And you can call that in `startReloadWatcher`, maybe?

**Comment by hexfusion** [comment]
does this make sense to you @roman-kiselenko ?

**Comment by roman-kiselenko** [comment]
@hexfusion SGTM, I'm going to work on this.
