### ISSUE TITLE
Conmon Package Not Updated

### ISSUE THREAD

**Issue by isugimpy** [cri-o/cri-o#7968]
### What happened?

Found that conmon 2.1.2 is the latest version provided in the package repos.

### What did you expect to happen?

Expected the conmon package bundled in the CRI-O repos to be a modern version.

### How can we reproduce it (as minimally and precisely as possible)?

Click [this link](https://rsync.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/) and look in any of the directories.

### Anything else we need to know?

It's surprising that this is so far behind.  We ended up getting hit with a bug in production which was actually fixed in 2.1.7, and were surprised to see that 2.1.2 is the latest available package.  CRI-O has references to 2.1.10 here in the repo, but seemingly something is going on with packaging?  https://github.com/cri-o/cri-o/pull/7619 was merged months ago.

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.27.2
Version:        1.27.2
GitCommit:      unknown
GitCommitDate:  unknown
GitTreeState:   clean
BuildDate:      2023-12-08T18:56:30Z
GoVersion:      go1.19
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:      
  apparmor
  seccomp
  containers_image_ostree_stub
  exclude_graphdriver_btrfs
  exclude_graphdriver_devicemapper
  containers_image_openpgp
LDFlags:          -s -w -X github.com/cri-o/cri-o/internal/pkg/criocli.DefaultsPath="" -X github.com/cri-o/cri-o/internal/version.buildDate=2023-12-08T18:56:30Z 
SeccompEnabled:   true
AppArmorEnabled:  false
```

```console
$ kubectl version --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "27",
    "gitVersion": "v1.27.10",
    "gitCommit": "0fa26aea1d5c21516b0d96fea95a77d8d429912e",
    "gitTreeState": "clean",
    "buildDate": "2024-01-17T13:46:28Z",
    "goVersion": "go1.20.13",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v5.0.1"
}
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux ip-10-9-0-19.ec2.internal 6.2.0-1012-aws #12~22.04.1-Ubuntu SMP Thu Sep  7 14:01:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
AWS EC2
</details>

**Comment by saschagrunert** [comment]
All new repos in https://github.com/cri-o/packaging support the latest conmon, so I'm considering this as resolved now.

**Comment by haircommander** [comment]
@isugimpy are you using the new k8s repos for cri-o packages or are you on an older branch? sorry this one fell to the wayside
