### ISSUE TITLE
Time Sync problems after restore VM/Node from snapshot

### ISSUE THREAD

**Issue by Jeansen** [cri-o/cri-o#8033]
### What happened?

I have a playground cluster setup with QEMEU/KVM. When I try out new tings, I create a snapshot. All VMs are paused, a Snapshot is created, and then I can continue. If something breaks, I restore the VMs to the latest or some other defined state. After that, I sync the time in all VMs (Nodes), but I also have to e.g. restart the Pods for calico, cert-manager and others because they don't reflect the current time. I am not sure, if this is related to cri-o but so far, it's my best shot because the time is correct on each node and the next layer beneath any application container is the container runtime.

### What did you expect to happen?

I would expect all Pods to reflect the time of then odes they are running on.

### How can we reproduce it (as minimally and precisely as possible)?

Create a cluster with kubeadm where Nodes are VMs. Take a snaphot of each node and restore it some time later. Check the time in existing pods.

### Anything else we need to know?

When I reset time, I do the following from within my code:

```
virsh domtime ${machineName} --now
```

An alternative approach I used before that (wich does not change the problem) was to execute the following on each node:

```
sudo sytemctl restart chronyd.service
```

Then, I connect via SSH onto that node and run:

```
sudo chronyc tracking
```

Which will show me that the time is correct.

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
$ crio --version
crio version 1.29.2
Version:        1.29.2
GitCommit:      d317b5dc918bbfbc78481072a0d93e572aa8d0e8
GitCommitDate:  2024-02-22T19:23:38Z
GitTreeState:   clean
BuildDate:      1970-01-01T00:00:00Z
GoVersion:      go1.21.1
Compiler:       gc
Platform:       linux/amd64
Linkmode:       static
BuildTags:
  static
  netgo
  osusergo
  exclude_graphdriver_btrfs
  exclude_graphdriver_devicemapper
  seccomp
  apparmor
  selinux
LDFlags:          unknown
SeccompEnabled:   true
AppArmorEnabled:  false
```

```console
$ kubectl version --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "29",
    "gitVersion": "v1.29.2",
    "gitCommit": "4b8e819355d791d96b7e9d9efe4cbafae2311c88",
    "gitTreeState": "clean",
    "buildDate": "2024-02-14T10:40:49Z",
    "goVersion": "go1.21.7",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v5.0.4-0.20230601165947-6ce0bf390ce3",
  "serverVersion": {
    "major": "1",
    "minor": "29",
    "gitVersion": "v1.29.3",
    "gitCommit": "6813625b7cd706db5bc7388921be03071e1a492d",
    "gitTreeState": "clean",
    "buildDate": "2024-03-14T23:58:36Z",
    "goVersion": "go1.21.8",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}```

</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux worker3-k8s.lan 6.1.0-20-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.85-1 (2024-04-11) x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
Running in QEMU/KVM Virtual Hosts.
</details>

**Comment by sohankunkerkar** [comment]
@Jeansen Thanks for reporting this issue. I was wondering if setting the [timezone](https://github.com/cri-o/cri-o/blob/main/docs/crio.conf.5.md?plain=1#L324) in CRI-O config will help in this case.

**Comment by Jeansen** [comment]
@sohankunkerkar I don't think so. First, if I kill the Pods, the new ones pick up the right time. Second, as it is written in the timezone setting, it would pick up the hosts settings if not otherwise specified. And to elaborate on this a bit more. I reset my VMs on 12th. And a couple days later cert-manager complained about invalid certificates with a time difference of 4 days! After I refreshed the deployment, all was well again. So, no timezone issue here.

**Comment by sohankunkerkar** [comment]
I see the problem here. I think this behavior is expected because containers inherit their initial time from the host system when they are created. However, once running, they maintain their own internal clock, which may drift from the host's time over time. When you restore a snapshot, the host's time gets reset, but the container's internal clock doesn't automatically reset. One thing we can do here is to add a watcher when CRI-O starts a container and look for changes to the host system time, and adjust the container's time accordingly.

**Comment by kwilczynski** [comment]
This is a known issue that has been affecting any container users who suspend or hibernate their machines, mainly desktop and workstation users, whether they use Linux, macOS, or Windows.

Most of our users run CRI-O on hosts that almost never are suspended or hibernated. I think Podman and Docker, for their desktop-targeting applications, solved this for the users—at least Docker did in the past.

Fix, or a workaround for the time being can be administered as follows:

- Ensure `chrony` or `ntpd` updates time on the virtual machine host
- Ensure `chrony` or `ntpd` updates time within the virtual machine (so container host)
- Run `hwclock -s` inside, assuming that the binary is installed

You can turn this into a one-liner in the shell that iterates over running containers and runs `crictl exec` (with `--sync`) inside. It has to be run as a privileged user.

There are also smaller services to synchronise time, like the bespoke offering from linuxkit per:

- [host-timesync-daemon](https://github.com/linuxkit/linuxkit/tree/master/pkg/host-timesync-daemon)

There is also the systemd way and projects that use HTTP as time sources, etc.

Do let me know if the `hwclock -s` worked for you.

In the long term, as @sohankunkerkar said, we would need to take care of these within CRI-O.

An interesting problem that has avoided us for a long time, indeed. 😄

**Comment by Jeansen** [comment]
Guys, thanks for the quick replies. Much appreciated! :-) Actually, I wasn't aware that only the initial time was set in a container. I thought this is taken every time from the host (since containers share the kernel...). But, obviously this is not the case.
I agree, this is some sort of a "special" case for home-lab guys, like myself. On the other hand, at work we do have all Nodes running in VMs and those VMs have snapshots, too. Only difference is, snapshots there do not keep the memory state, like in my case.
I also tried of simply draining each Node and rebooting it. Anyway, I'll try your tips, @kwilczynski . Should I close issue then?

**Comment by Jeansen** [comment]
So, `hwclock -s` is not working for me, especially not for cert-manager Pods. I think I'll just iterate through the Nodes, drain them and reboot. But at some point in the future I'd definitely be happy to have some sort of a watch available in CRI-O.

**Comment by kwilczynski** [comment]
@Jeansen, not working as in the time hasn't been updated, or there was an error?

**Comment by Jeansen** [comment]
@kwilczynski Not working as in there is no shell in the Container (probably distroless)

**Comment by kwilczynski** [comment]
Some bits for reference:

- [Time namespaces](https://lwn.net/Articles/766089/)
- [[PATCHv8 00/34] kernel: Introduce Time Namespace](https://lore.kernel.org/lkml/20191112012724.250792-15-dima@arista.com/t/)
- https://github.com/opencontainers/runtime-spec/pull/1151
- https://github.com/containers/crun/pull/257
- https://github.com/containers/crun/pull/743
- https://github.com/containers/crun/pull/1184
- https://github.com/opencontainers/runc/issues/2345
- https://github.com/opencontainers/runc/pull/3876

**Comment by Jeansen** [comment]
I see. So Containers create their own time namespace .... Thanks for the list of reference :-)

**Comment by kwilczynski** [comment]
@Jeansen, it's more of a matter of CRI-O not using time namespaces as of yet, even though crun and runc added support some time ago. We never seen this as needed or as a priority. That said, I am not sure if containerd also added support.

**Comment by kwilczynski** [comment]
@Jeansen, looking into this a little more in-depth.

Sadly, the new time namespace's limitations make this not really feasible. It probably would explain why there has yet to be a wider adoption of this new namespace.

Per the man page ([time_namespaces(7)](https://www.man7.org/linux/man-pages/man7/time_namespaces.7.html)):

> In a new time namespace that has had no member processes, the
> clock offsets can be modified by writing newline-terminated
> records of the same form to the timens_offsets file. The file
> can be written to multiple times, but after the first process has
> been created in or has entered the namespace, [write(2)](https://www.man7.org/linux/man-pages/man2/write.2.html)s on this
>  file fail with the error EACCES.

This means that updating the time-related offsets would not be possible with the processes running within a namespace.

As such, there isn't a better option now than restarting Pods.

**Comment by Jeansen** [comment]
@kwilczynski Oh, too bad. Thank you very much for the details and your invested time. I'll simply have to be a bit more patient then, when I reset my cluster and do rolling restarts in addition ...
