### ISSUE TITLE
Unable to run pods with apparmor type "Unconfined"

### ISSUE THREAD

**Issue by aanm** [cri-o/cri-o#8080]
### What happened?

We have receiving reports of users unable to run Cilium wtih cri-o 1.30-dev

Cilium has been using the annotations to run the containers in uncofined mode:
```
        container.apparmor.security.beta.kubernetes.io/cilium-agent: "unconfined"
```

Since k8s 1.30 this is no longer possible. However, even with
```
  appArmorProfile:
    type: "Unconfined"
```
set at the pod level, users are still unable to run Cilium successful. As reported by one of the users the problematic code seems to be on [this](https://github.com/cri-o/cri-o/blob/b4b0482fc65e3d0b7530b21beab48b547ded65c1/internal/config/apparmor/apparmor_linux.go#L123) function as it doesn't seem to handle the case for `Unconfined` mode.

### What did you expect to happen?

Cilium to start successfully

### How can we reproduce it (as minimally and precisely as possible)?

Perhaps @orimanabu can provide the steps to reproduce the issue.

### CRI-O and Kubernetes version

<details>
k8s v1.30
CRI-O v1.30-dev

</details>

### OS version

<details>

```console
Ubuntu 24.04
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

Cilium upstream issue https://github.com/cilium/cilium/issues/32198

**Comment by orimanabu** [comment]
Hi, thank you for taking this issue.
The steps to reproduce is:

1. Install k8s v1.30 and CRI-O v1.30.0-dev on Ubuntu 24.04 following this steps: https://github.com/cri-o/packaging?tab=readme-ov-file#distributions-using-deb-packages
1. Make k8s cluster using kubeadm
1. Install cilium with `cilium install`
