### ISSUE TITLE
crio is crashed during container restore

### ISSUE THREAD

**Issue by tonyaw** [cri-o/cri-o#8083]
### What happened?

1. I'm following this procedure to test container checkpoint/restore with Kubernetes 1.30:
    https://kubernetes.io/blog/2022/12/05/forensic-container-checkpointing-alpha/#restore-checkpointed-container-standalone
2. After I created checkpoint of container started by Kubernetes successfully, I deleted Kubernetes cluster, and try to restore a container via crio.
3. I used following json to create pod sandbox:
    crictl runp pod-config.json
```json
{
    "metadata": {
        "name": "clone-sandbox",
        "namespace": "default",
        "attempt": 1,
        "uid": "hdishd83djaidwnduwk28bcsb"
    },
    "linux": {
    }
}
````
5. Then I used following json to restore container from checkpoint:
    crictl create ef80f5a8c32b7 container-config.json pod-config.json
```json
{
  "metadata": {
      "name": "test"
  },
  "image":{
      "image": "/home/tonyaw/k8s/kubelet/checkpoints/checkpoint-tonyaw-deploy-78fdd8bbf5-5p2zf_default-test-2024-04-29T20:43:15+08:00.tar"
  }
}
```
6. crictl is failed, and crio is crashed:
```
[root@test-host kubelet]# crictl create 96480f6885a14 container-config.json pod-config.json
 E0429 20:50:58.512622   44825 remote_runtime.go:319] "CreateContainer in sandbox from runtime service failed" err="rpc error: code = Dead
 lineExceeded desc = context deadline exceeded" podSandboxID="96480f6885a14"
```

crio journal log and backtrace:
[crio-crash-log.txt](https://github.com/cri-o/cri-o/files/15149831/crio-crash-log.txt)

### What did you expect to happen?

container is restored successfully.

### How can we reproduce it (as minimally and precisely as possible)?

Follow procedure https://kubernetes.io/blog/2022/12/05/forensic-container-checkpointing-alpha/#restore-checkpointed-container-standalone to restore a container with Kubernetes 1.30.
The issue shall happen when you restore the container.

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
WARN[0000] Failed to decode the keys ["storage.options.override_kernel_check"] from "/etc/containers/storage.conf"
crio version 1.30.0
Version:        1.30.0
GitCommit:      a3de11a8aa3070c8b040054461ce82314c95baf2
GitCommitDate:  2024-04-26T16:51:03Z
GitTreeState:   clean
BuildDate:      1970-01-01T00:00:00Z
GoVersion:      go1.22.0
Compiler:       gc
Platform:       linux/amd64
Linkmode:       static
BuildTags:
  static
  netgo
  osusergo
  exclude_graphdriver_btrfs
  exclude_graphdriver_devicemapper
  seccomp
  apparmor
  selinux
LDFlags:          unknown
SeccompEnabled:   true
AppArmorEnabled:  false
```

```console
$ kubectl version --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "30",
    "gitVersion": "v1.30.0",
    "gitCommit": "7c48c2bd72b9bf5c44d21d7338cc7bea77d0ad2a",
    "gitTreeState": "clean",
    "buildDate": "2024-04-17T17:36:05Z",
    "goVersion": "go1.22.2",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v5.0.4-0.20230601165947-6ce0bf390ce3"
}
The connection to the server 10.67.39.251:6443 was refused - did you specify the right host or port?
```
I deleted Kubernetes cluster, as crictl can't create pod successfully if Kubernetes cluster is up with calico.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
Linux foss-ssc-11 5.1.11-1.el7.elrepo.x86_64 #1 SMP Mon Jun 17 15:51:08 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by tonyaw** [comment]
```
/usr/bin/crio --enable-criu-support=true
```
crio is enabled criu support

**Comment by rst0git** [comment]
@tonyaw CRI-O uses annotations to identify an OCI images that contain checkpoint. For example, you can use `buildah` to convert a tar archive into an OCI image as follows:
```
newcontainer=$(buildah from scratch)
buildah add $newcontainer /var/lib/kubelet/checkpoints/checkpoint-<pod-name>_<namespace-name>-<container-name>-<timestamp>.tar /
buildah config --annotation=io.kubernetes.cri-o.annotations.checkpoint.name=<container-name> $newcontainer
buildah commit $newcontainer checkpoint-image:latest
buildah rm $newcontainer
```
cc: @adrianreber

**Comment by kwilczynski** [comment]
The most relevant to the panic:

```console
Apr 29 20:51:45 test-host crio[44862]: github.com/cri-o/cri-o/server.(*Server).CRImportCheckpoint(0xc000600808, {0x240b070, 0xc0006d79e0}, 0xc0005d7860, {0xc000037670, 0xd}, {0xc000481300, 0x19})
Apr 29 20:51:45 test-host crio[44862]: github.com/cri-o/cri-o/server/container_restore.go:273 +0x17de fp=0xc000659510 sp=0xc000658e00 pc=0x1960f1e
Apr 29 20:51:45 test-host crio[44862]: github.com/cri-o/cri-o/server.(*Server).CreateContainer(0xc000600808, {0x240b070, 0xc0006d79e0}, 0xc0006d71a0)
Apr 29 20:51:45 test-host crio[44862]: github.com/cri-o/cri-o/server/container_create.go:346 +0x290 fp=0xc000659848 sp=0xc000659510 pc=0x194abd0
```

This is because the following are `nil` (missing):

```go
if createConfig.Linux.Resources != nil {
	containerConfig.Linux.Resources = createConfig.Linux.Resources
}
```

There is no `linux` attribute present in the JSON linked.

While this restore might have not worked due to missing of some of the important properties, CRI-O should handle the missing attributes more gracefully.

**Comment by adrianreber** [comment]
@rst0git restoring from a tar file is supported, just not from Kubernetes. Using `crictl` that is possible.

@kwilczynski You are right, there should be an additional check. Thanks. I can also open a PR if you want.

**Comment by adrianreber** [comment]
> > [...]
> > @kwilczynski You are right, there should be an additional check. Thanks. I can also open a PR if you want.
> 
> No worries. I appreciate the offer, but this has been on my TODO list since last week. I told @haircommander about this issue independently since I also stumbled upon it while doing some manual testing.
> 
> I will look at [kubernetes/cri-api/pkg/apis/runtime/v1/api.proto](https://github.com/kubernetes/cri-api/blob/master/pkg/apis/runtime/v1/api.proto) to see what else we would consider a "required" field and then update our code to correctly validate some of these attributes.
> 
> Unless you have some ideas from the top of your head?

No, I would have just fixed the existing problem. I would just checked that we do not access element of substructures without checking that the structures actually exist. Tag me on the PR and I will review it.

**Comment by adrianreber** [comment]
@tonyaw Checkpoint/Restore support was never fully supported on CentOS/RHEL 7. You should try something newer.

**Comment by tonyaw** [comment]
@adrianreber @kwilczynski @rst0git , 
Thanks for your comments. May I ask what I can do to make this checkpoint/restore work?
My requirement is to checkpoint a container from Kubernetes, and restore it in pure crio or Kubernetes environment.
My follow up questions:
1. What CentOS verison do you suggest, is CentOS8 good enough?
2. Is there kernel version required?
3. For the "pod-config.json" and "container-config.json" I provided, any change can be made to make it work even with crio 1.30?
4. Any other configuration from Kubernetes/crio/criu shall be made? The following link is unclear to following :-(:
https://kubernetes.io/blog/2022/12/05/forensic-container-checkpointing-alpha/#restore-checkpointed-container-standalone

**Comment by kwilczynski** [comment]
@tonyaw, to add to what @adrianreber said already:

> > ```
> > 1. What CentOS verison do you suggest, is CentOS8 good enough?
> > ```
> 
> Yes, that should work.

CentOS 7 is also due for EOL (End of Life) very soon (June 30th this year), see:

- [What to know about CentOS Linux EOL
](https://www.redhat.com/en/topics/linux/centos-linux-eol)
- [Planning for CentOS Linux 7 End of Life: Transition to Red Hat Enterprise Linux](https://www.redhat.com/en/engage/centos-migration-level-up)

So you might have to move to CentOS Stream or Fedora at some point.

> > ```
> > 2. Is there kernel version required?
> > ```
> 
> The CentOS 8 kernel has been tested to work as far as I know.

As the CRIU support has been mainlined in the Linux kernel 3.11, as such, so you should be fine. Unless CentOS 7 runs such an old kernel release. For more details, see CRIU's [Check the kernel](https://criu.org/Check_the_kernel).

> > ```
> > 3. For the "pod-config.json" and "container-config.json" I provided, any change can be made to make it work even with crio 1.30?
> > ```
> 
> For testing (see https://github.com/cri-o/cri-o/blob/main/test/checkpoint.bats#L45) we use the following two files:
> 
> * https://github.com/cri-o/cri-o/blob/main/test/testdata/sandbox_config.json
> * https://github.com/cri-o/cri-o/blob/main/test/testdata/container_sleep.json
> 
> Looking at @kwilczynski comment you need the `linux` part of `container_sleep.json` to make it work. `linux: {}` could be all there is needed. I think https://kubernetes.io/blog/2022/12/05/forensic-container-checkpointing-alpha/#restore-checkpointed-container-standalone does not provide the complete JSON file, just the important parts that you need to change.

If you have an existing container you wish to snapshot, then see if inspecting it (using `crictl inspect`) would have the necessary details you could reuse to seed the missing JSON file sections. Otherwise, there is also a container configuration stored on the file system where the current containers metadata is usually stored, this could be used too, to see what to configure.

**Comment by kwilczynski** [comment]
Having a look at the Protocol Buffers schema, there does not seem to be anything that is specifically required, per:

```proto
// LinuxContainerResources specifies Linux specific configuration for
// resources.
message LinuxContainerResources {
    // CPU CFS (Completely Fair Scheduler) period. Default: 0 (not specified).
    int64 cpu_period = 1;
    // CPU CFS (Completely Fair Scheduler) quota. Default: 0 (not specified).
    int64 cpu_quota = 2;
    // CPU shares (relative weight vs. other containers). Default: 0 (not specified).
    int64 cpu_shares = 3;
    // Memory limit in bytes. Default: 0 (not specified).
    int64 memory_limit_in_bytes = 4;
    // OOMScoreAdj adjusts the oom-killer score. Default: 0 (not specified).
    int64 oom_score_adj = 5;
    // CpusetCpus constrains the allowed set of logical CPUs. Default: "" (not specified).
    string cpuset_cpus = 6;
    // CpusetMems constrains the allowed set of memory nodes. Default: "" (not specified).
    string cpuset_mems = 7;
    // List of HugepageLimits to limit the HugeTLB usage of container per page size. Default: nil (not specified).
    repeated HugepageLimit hugepage_limits = 8;
    // Unified resources for cgroup v2. Default: nil (not specified).
    // Each key/value in the map refers to the cgroup v2.
    // e.g. "memory.max": "6937202688" or "io.weight": "default 100".
    map<string, string> unified = 9;
    // Memory swap limit in bytes. Default 0 (not specified).
    int64 memory_swap_limit_in_bytes = 10;
}
```

```proto
// LinuxContainerConfig contains platform-specific configuration for
// Linux-based containers.
message LinuxContainerConfig {
    // Resources specification for the container.
    LinuxContainerResources resources = 1;
    // LinuxContainerSecurityContext configuration for the container.
    LinuxContainerSecurityContext security_context = 2;
}
```

```proto
// ContainerResources holds resource limits configuration for a container.
message ContainerResources {
    // Resource limits configuration specific to Linux container.
    LinuxContainerResources linux = 1;
    // Resource limits configuration specific to Windows container.
    WindowsContainerResources windows = 2;
}
```

This means that we can do a simple nil checks and be done with it. Perhaps issue a warning along the way, if we deem it a useful thing to do.

**Comment by tonyaw** [comment]
@kwilczynski  @adrianreber,
Thanks for your comments!
I need some time to upgrade my env to CentOS8.

On CentOS7, after I added "linux" section, the container can be restored with no error, but can't be up. Container status is Unknown:
```
[root@test-host home]# crictl ps --all
CONTAINER           IMAGE                                                              CREATED             STATE               NAME                ATTEMPT             POD ID              POD
1e38e6cecdf41       46f91d7c212fc2969fddec8e778995d891a7b604e6ed283d37f5825c42681fd0   5 days ago          Unknown             test                0                   f1999c38cae34       tonyaw-deploy-78fdd8bbf5-6mnrh
[root@test-host home]#
```
The crictl inspect result is as following:
[crictl-inspect.txt](https://github.com/cri-o/cri-o/files/15215487/crictl-inspect.txt)

Could you please help to check if there is obvious error?

My kernel version is:
5.1.11-1.el7.elrepo.x86_64

**Comment by kwilczynski** [comment]
@tonyaw, what do you mean when you say "can't be up"?

Are you having an error when you try to start the restored container?

**Comment by tonyaw** [comment]
No error during container creation, but container's status is "Unknown":
```
[root@test-host home]# crictl ps --all
CONTAINER           IMAGE                                                              CREATED             STATE               NAME                ATTEMPT             POD ID              POD
1e38e6cecdf41       46f91d7c212fc2969fddec8e778995d891a7b604e6ed283d37f5825c42681fd0   5 days ago          Unknown             test                0                   f1999c38cae34       tonyaw-deploy-78fdd8bbf5-6mnrh
[root@test-host home]#
```

**Comment by tonyaw** [comment]
Please find the "crictl inspect" output for this Unknown container here:
https://github.com/cri-o/cri-o/issues/8083#issuecomment-2095109468

**Comment by tonyaw** [comment]
I removed the old pod and container, and did the restore again.
This time, I captured all the command output and crio logs(by "journalctl -u crio -f").
Please help to check.
My concern is to upgrade to CentOS8 may be not helpful if we don't know the root cause. :-(

Command output:
[crictl.txt](https://github.com/cri-o/cri-o/files/15217185/crictl.txt)

crio logs(by "journalctl -u crio -f") for all the commands:
[crio.log](https://github.com/cri-o/cri-o/files/15217188/crio.log)

**Comment by adrianreber** [comment]
> My concern is to upgrade to CentOS8 may be not helpful if we don't know the root cause. :-(

Your current OS will be end of life in two months, so what your are trying to do doesn't make much sense. We know that it was never tested on CentOS 7.

Looking at your log you only create the container. You also need to start the container. I already provided a link to the test script of CRI-O. You need to take a look at that.

**Comment by tonyaw** [comment]
> > My concern is to upgrade to CentOS8 may be not helpful if we don't know the root cause. :-(
> 
> Your current OS will be end of life in two months, so what your are trying to do doesn't make much sense. We know that it was never tested on CentOS 7.
> 
> Looking at your log you only create the container. You also need to start the container. I already provided a link to the test script of CRI-O. You need to take a look at that.

Thanks for your comment, I will upgrade to CentOS8 recently.
I tried "crictl start", and got error. What does this error mean?
```
[root@foss-ssc-11 test]# crictl start cdc9864e3a5c7
E0506 13:45:49.617593   64446 remote_runtime.go:343] "StartContainer from runtime service failed" err=<
        rpc error: code = Unknown desc = failed to restore container cdc9864e3a5c73437de70fb52343a7798a5bd0b3a86b429d7400e26c02c83e55: container restore failed: time="2024-05-06T13:45:49+08:00" level=error msg="criu failed: type NOTIFY errno 0\nlog file: /run/containers/storage/overlay-containers/cdc9864e3a5c73437de70fb52343a7798a5bd0b3a86b429d7400e26c02c83e55/userdata/restore.log"
 > containerID="cdc9864e3a5c7"
FATA[0000] starting the container "cdc9864e3a5c7": rpc error: code = Unknown desc = failed to restore container cdc9864e3a5c73437de70fb52343a7798a5bd0b3a86b429d7400e26c02c83e55: container restore failed: time="2024-05-06T13:45:49+08:00" level=error msg="criu failed: type NOTIFY errno 0\nlog file: /run/containers/storage/overlay-containers/cdc9864e3a5c73437de70fb52343a7798a5bd0b3a86b429d7400e26c02c83e55/userdata/restore.log"
[root@foss-ssc-11 test]#
```

**Comment by adrianreber** [comment]
Now the restore of CRIU failed. Now you need to provide us with: `/run/containers/storage/overlay-containers/cdc9864e3a5c73437de70fb52343a7798a5bd0b3a86b429d7400e26c02c83e55/userdata/restore.log`.

This file is usually deleted by CRI-O. You need to tell CRIU to create the log file in a different location.

```shell
# echo "log-file /tmp/criu.log" >> /etc/criu/runc.conf
```

And then share `/tmp/criu.log` with us.

**Comment by adrianreber** [comment]
Are you starting the container with Kubernetes and restoring outside of Kubernetes? That will not work. If you do that you have to adapt your json file to contain all the mountpoints that Kubernetes would define during create/start.

Just use Kubernetes to restore the container.

**Comment by tonyaw** [comment]
Right. The reason about why I'm doing in this way is as following:
https://kubernetes.io/blog/2022/12/05/forensic-container-checkpointing-alpha/#restore-checkpointed-container-standalone
"With the checkpoint tar archive it is possible to restore the container **outside of Kubernetes in a sandboxed instance of CRI-O**." 
So actually, it is impossible. Right?
If Yes, I suggest to modify the blog so that it won't confuse others. :-)

I will to try use Kubernetes to checkpoint and restore to see what will happen, and keep you posted.

**Comment by rst0git** [comment]
```
mnt: 		Will mount 2233 from /var/lib/kubelet/pods/51e3eb40-752e-4eeb-91cb-4bb61f90868b/volumes/kubernetes.io~projected/kube-api-access-b78wn (E)
mnt: 		Will mount 2233 @ /tmp/.criu.mntns.PmL0Et/13-0000000000/run/secrets/kubernetes.io/serviceaccount
mnt: 	Read 2233 mp @ /tmp/.criu.mntns.PmL0Et/13-0000000000/run/secrets/kubernetes.io/serviceaccount
Error (criu/mount.c:2830): mnt: No mapping for /run/secrets mountpoint
```

@tonyaw The error that appears during `crictl start` occurs because the mountpoint `/run/secrets` has not been created. CRI-O needs to be configured to create this mountpoint.

> So actually, it is impossible. Right?

I believe Adrian recommends restoring with Kubernetes because it would be easier. While restoring a container outside of Kubernetes is possible, it requires additional configurations that Kubernetes would otherwise handle automatically.

**Comment by tonyaw** [comment]
When I use Kubernetes to restore, I got following error from crio:
```
May 07 13:15:50 foss-ssc-11 crio[43377]: time="2024-05-07 13:15:50.751727049+08:00" level=info msg="Creating container: default/tonyaw-deploy-78fdd8bbf5-2wjzr/test" id=76a5f610-4ada-43f6-b2ef-ff7054b69cb4 name=/runtime.v1.RuntimeService/CreateContainer
May 07 13:15:50 foss-ssc-11 crio[43377]: time="2024-05-07 13:15:50.754199989+08:00" level=warning msg="error reserving ctr name k8s_**test**_**tonyaw-deploy-78fdd8bbf5-2wjzr_default_1576c347-d24a-4d30-906c-e62f24f638f0**_0 for id 243756edfe5f81bfcc9bb12e2942902be9ce7198a3a364e9496708beaa1e139c: name is reserved"
```

What name is reserved?
The pod name and container name is same as the checkpoint:
```
/var/lib/kubelet/checkpoints/checkpoint-**tonyaw-deploy-78fdd8bbf5-2wjzr**_default-**test**-2024-05-07T13:04:13+08:00.tar
```

**Comment by adrianreber** [comment]
> "With the checkpoint tar archive it is possible to restore the container **outside of Kubernetes in a sandboxed instance of CRI-O**."
> So actually, it is impossible. Right?

No, it is possible, but you have to define the necessary mount points in your create request.

**Comment by adrianreber** [comment]
> When I use Kubernetes to restore, I got following error from crio:
> 
> ```
> May 07 13:15:50 foss-ssc-11 crio[43377]: time="2024-05-07 13:15:50.751727049+08:00" level=info msg="Creating container: default/tonyaw-deploy-78fdd8bbf5-2wjzr/test" id=76a5f610-4ada-43f6-b2ef-ff7054b69cb4 name=/runtime.v1.RuntimeService/CreateContainer
> May 07 13:15:50 foss-ssc-11 crio[43377]: time="2024-05-07 13:15:50.754199989+08:00" level=warning msg="error reserving ctr name k8s_**test**_**tonyaw-deploy-78fdd8bbf5-2wjzr_default_1576c347-d24a-4d30-906c-e62f24f638f0**_0 for id 243756edfe5f81bfcc9bb12e2942902be9ce7198a3a364e9496708beaa1e139c: name is reserved"
> ```
> 
> What name is reserved? The pod name and container name is same as the checkpoint:
> 
> ```
> /var/lib/kubelet/checkpoints/checkpoint-**tonyaw-deploy-78fdd8bbf5-2wjzr**_default-**test**-2024-05-07T13:04:13+08:00.tar
> ```

Is the original pod and container still running? You have to remove it first.

**Comment by tonyaw** [comment]
Pod is deleted before restore:
```
[root@foss-ssc-11 criu]# kubectl get pods | grep tonyaw
No resources found in default namespace.
[root@foss-ssc-11 criu]# crictl pods | grep tonyaw
[root@foss-ssc-11 criu]# cat restored-clone.yaml
apiVersion: v1
kind: Pod
metadata:
  name: tonyaw-deploy-78fdd8bbf5-2wjzr
spec:
  containers:
  - name: test
    image: localhost/checkpoint-image:tonyaw0507
[root@foss-ssc-11 criu]# kubectl create -f restored-clone.yaml
pod/tonyaw-deploy-78fdd8bbf5-2wjzr created
[root@foss-ssc-11 criu]# kubectl get pods | grep tonyaw
tonyaw-deploy-78fdd8bbf5-2wjzr   0/1     CreateContainerError   0          3s
[root@foss-ssc-11 criu]# kubectl describe pod tonyaw-deploy-78fdd8bbf5-2wjzr | grep reserved
  Warning  Failed     12s                kubelet            Error: kubelet may be retrying requests that are timing out in CRI-O due to system load: error reserving ctr name k8s_test_tonyaw-deploy-78fdd8bbf5-2wjzr_default_886b3bc5-a36a-4bbf-90be-323a2fb3d5b8_0 for id e2acdfe7e1450777a9bb7a608556c055620bfe4af3bef44f816be87dd7c28d48: name is reserved
[root@foss-ssc-11 criu]#
```
May I ask if the restored pod/container must have same name with the previous one?

Also, I observed the container is created, but exited:
```
[root@foss-ssc-11 criu]# crictl ps --all | grep test
60ef2e3a86132       46f91d7c212fc2969fddec8e778995d891a7b604e6ed283d37f5825c42681fd0   About a minute ago   Exited              test                        0                   44efd9514fe4e       tonyaw-deploy-78fdd8bbf5-2wjzr
```

**Comment by adrianreber** [comment]
> May I ask if the restored pod/container must have same name with the previous one?

No.

Do you get a new log file from CRIU? If yes, please share.

At this  point your questions have nothing to do with the initial crash you reported.

**Comment by tonyaw** [comment]
Right. I can open an new ticket if you want.
Restore again:
```
[root@foss-ssc-11 criu]# kubectl get pods | grep tonyaw
No resources found in default namespace.
[root@foss-ssc-11 criu]# crictl pods | grep tonyaw
[root@foss-ssc-11 criu]# ls
checkpoints  container-config.json  pod-config.json  rbac.yaml  restored-clone.yaml
[root@foss-ssc-11 criu]# cat restored-clone.yaml
apiVersion: v1
kind: Pod
metadata:
  name: tonyaw-deploy-78fdd8bbf5-2wjzr
spec:
  containers:
  - name: test
    image: localhost/checkpoint-image:tonyaw0507
    command:
    - sh
    - -c
    - /bin/bash
    stdin: true
[root@foss-ssc-11 criu]# kubectl create -f restored-clone.yaml
pod/tonyaw-deploy-78fdd8bbf5-2wjzr created
[root@foss-ssc-11 criu]# kubectl get pods | grep tonyaw
tonyaw-deploy-78fdd8bbf5-2wjzr   0/1     CreateContainerError   0          9s
[root@foss-ssc-11 criu]# kubectl create -f restored-clone.yaml
Error from server (AlreadyExists): error when creating "restored-clone.yaml": pods "tonyaw-deploy-78fdd8bbf5-2wjzr" already exists
[root@foss-ssc-11 criu]# kubectl describe pod tonyaw-deploy-78fdd8bbf5-2wjzr | grep reserved
  Warning  Failed     14s               kubelet            Error: kubelet may be retrying requests that are timing out in CRI-O due to system load: error reserving ctr name k8s_test_tonyaw-deploy-78fdd8bbf5-2wjzr_default_5d0d6aaf-ea6e-4f4a-933b-90b198eea473_0 for id 59d095c2979f0192ff5a240e4c461047c997e3b35a5b41150b9e2d789b3fc41a: name is reserved
  Warning  Failed     1s                kubelet            Error: kubelet may be retrying requests that are timing out in CRI-O due to system load: error reserving ctr name k8s_test_tonyaw-deploy-78fdd8bbf5-2wjzr_default_5d0d6aaf-ea6e-4f4a-933b-90b198eea473_0 for id bc6ab133e0821817e8a05042d77c1de4ac78cbbe817a07b15920c5e6794fa808: name is reserved
[root@foss-ssc-11 criu]#
```

criu.log:
[criu.log](https://github.com/cri-o/cri-o/files/15232402/criu.log)

You can also find crio log as following:
```
May 07 15:39:10 foss-ssc-11 crio[43377]: time="2024-05-07 15:39:10.747436766+08:00" level=info msg="Checking image status: localhost/checkpoint-image:tonyaw0507" id=ac04884e-0e08-4c9c-91a3-b43129146791 name=/runtime.v1.ImageService/ImageStatus
May 07 15:39:10 foss-ssc-11 crio[43377]: time="2024-05-07 15:39:10.747901040+08:00" level=info msg="Image status: &ImageStatusResponse{Image:&Image{Id:b45518616f45957357bbc05a67bb70cc7656ad7d66907541ef8a521715a70278,RepoTags:[localhost/checkpoint-image:tonyaw0507],RepoDigests:[localhost/checkpoint-image@sha256:5c72c5916a78f1760a1e9427b221a7676abbd8b5a92a1cf043cb4bf183137364],Size_:400516,Uid:nil,Username:,Spec:&ImageSpec{Image:,Annotations:map[string]string{io.kubernetes.cri-o.annotations.checkpoint.name: test,},UserSpecifiedImage:,RuntimeHandler:,},Pinned:false,},Info:map[string]string{},}" id=ac04884e-0e08-4c9c-91a3-b43129146791 name=/runtime.v1.ImageService/ImageStatus
May 07 15:39:10 foss-ssc-11 crio[43377]: time="2024-05-07 15:39:10.749397333+08:00" level=info msg="Checking image status: localhost/checkpoint-image:tonyaw0507" id=d625105a-7ddc-47e1-9599-69f3d3c362db name=/runtime.v1.ImageService/ImageStatus
May 07 15:39:10 foss-ssc-11 crio[43377]: time="2024-05-07 15:39:10.749713675+08:00" level=info msg="Image status: &ImageStatusResponse{Image:&Image{Id:b45518616f45957357bbc05a67bb70cc7656ad7d66907541ef8a521715a70278,RepoTags:[localhost/checkpoint-image:tonyaw0507],RepoDigests:[localhost/checkpoint-image@sha256:5c72c5916a78f1760a1e9427b221a7676abbd8b5a92a1cf043cb4bf183137364],Size_:400516,Uid:nil,Username:,Spec:&ImageSpec{Image:,Annotations:map[string]string{io.kubernetes.cri-o.annotations.checkpoint.name: test,},UserSpecifiedImage:,RuntimeHandler:,},Pinned:false,},Info:map[string]string{},}" id=d625105a-7ddc-47e1-9599-69f3d3c362db name=/runtime.v1.ImageService/ImageStatus
May 07 15:39:10 foss-ssc-11 crio[43377]: time="2024-05-07 15:39:10.751075110+08:00" level=info msg="Creating container: default/tonyaw-deploy-78fdd8bbf5-2wjzr/test" id=916a1be1-9295-4b7d-b673-e39ef6d741ea name=/runtime.v1.RuntimeService/CreateContainer
May 07 15:39:10 foss-ssc-11 crio[43377]: time="2024-05-07 15:39:10.753067262+08:00" level=warning msg="error reserving ctr name k8s_test_tonyaw-deploy-78fdd8bbf5-2wjzr_default_5d0d6aaf-ea6e-4f4a-933b-90b198eea473_0 for id 94dd975736a8f1dfceb064c850688eb45ee0c45b44803b4c843db3a0f51ae69f: name is reserved"
```

**Comment by adrianreber** [comment]
Why are you running `kubectl create -f restored-clone.yaml` twice?

**Comment by adrianreber** [comment]
Please also push your checkpoint image to a registry so I can try it locally.

**Comment by tonyaw** [comment]
The second "kubectl create" is run by mistake.

1. I attached the checkpoint as following:
[checkpoint-tonyaw-deploy-78fdd8bbf5-2wjzr_default-test-2024-05-07T13_04_13+08_00.zip](https://github.com/cri-o/cri-o/files/15232787/checkpoint-tonyaw-deploy-78fdd8bbf5-2wjzr_default-test-2024-05-07T13_04_13%2B08_00.zip)

2. unzip the previous file to get a tar
3. use following procedure to build an image:
```shell
newcontainer=$(buildah from scratch)
buildah add $newcontainer /var/lib/kubelet/checkpoints/checkpoint-<pod-name>_<namespace-name>-<container-name>-<timestamp>.tar /
buildah config --annotation=io.kubernetes.cri-o.annotations.checkpoint.name=<container-name> $newcontainer
buildah commit $newcontainer checkpoint-image:latest
buildah rm $newcontainer
```
4. Use following manifest to create the pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: tonyaw-deploy-78fdd8bbf5-2wjzr
spec:
  containers:
  - name: test
    image: localhost/checkpoint-image:tonyaw0507
    command:
    - sh
    - -c
    - /bin/bash
    stdin: true
```
5. Kubernetes in use is:
```
[root@foss-ssc-11 criu]# kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
[root@foss-ssc-11 criu]#
```

**Comment by adrianreber** [comment]
I cannot restore that container because your kernel is too old. Or mine is too new.

I see that you are not running anything in your container. This has not been tested. Try it without `stdin: true`. Run something in your container. For restore you can remove `command:`.

**Comment by tonyaw** [comment]
Looks like "pid 1 can't be a shell" is the root case. :-D

1. Use following manifest to create a pod:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tonyaw
  name: tonyaw-deploy
  namespace: default
spec:
  selector:
    matchLabels:
      app: tonyawdeploy
  template:
    metadata:
      labels:
        app: tonyawdeploy
    spec:
      containers:
      - image: dolphm/network-tools:latest
        name: test
        command:
        - sh
        - -c
        - while true; do echo "$(date)" >> test.log; sleep 1; done 
```
2. Use following pod to restore:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: tonyaw-deploy-clone
spec:
  containers:
  - name: test-ttt
    image: localhost/checkpoint-image:tonyaw050701        
```
3. pod can be restored successfully:
```
[root@foss-ssc-11 criu]# kubectl exec -ti tonyaw-deploy-clone bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
bash-4.4# ls
bin       dev       etc       home      lib       media     mnt       proc      root      run       sbin      srv       sys       test.log  tmp       usr       var
bash-4.4# vi test.log
Tue May  7 09:08:07 UTC 2024
Tue May  7 09:08:08 UTC 2024
Tue May  7 09:08:09 UTC 2024
# tonyaw: you can see a gap here.
Tue May  7 09:17:22 UTC 2024
Tue May  7 09:17:23 UTC 2024
Tue May  7 09:17:24 UTC 2024
bash-4.4# ps aux
PID   USER     TIME   COMMAND
    1 root       0:00 sh -c while true; do echo "$(date)" >> test.log; sleep 1; done
  219 root       0:00 bash
  414 root       0:00 sleep 1
  415 root       0:00 ps aux
bash-4.4# exit
[root@foss-ssc-11 criu]#        
```
Thanks for your great support!

May I ask another question?
If there are multiple process running in the container, will all the processes will be checkpoint/restore, or only pid 1? :-)

**Comment by adrianreber** [comment]
> 3. pod can be restored successfully:

Great.

> Looks like "pid 1 can't be a shell" is the root case. :-D

This is technically not correct. In your current example your PID 1is also a shell: 
```
1 root       0:00 sh -c while true; do echo "$(date)" >> test.log; sleep 1; done
```

So far no one was using `stdin: true`. Usually stdin is connected to `/dev/null` in your case it was connected to a pipe.

> If there are multiple process running in the container, will all the processes will be checkpoint/restore, or only pid 1? :-)

Yes, if those processes are child processes of PID 1. CRIU always checkpoints a complete process tree. The target PID and all child processes.

It is important to know that `crictl exec` or `kubectl exec` creates processes which are not child processes of PID 1. So if you exec into a container and start additional processes they will not be checkpointed because they are not child processes of PID 1.

**Comment by tonyaw** [comment]
Thanks for your detail info!
I will leave the ticket open to fix of original issue, and you can close the ticket if you want. :-)
