### ISSUE TITLE
add documentation for using cri-o with flatcar

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#8172]
now that flatcar supports [sysexts](https://www.flatcar.org/blog/2024/04/os-innovation-with-systemd-sysext/), you can now install cri-o in a supported way. I've never used flatcar, but if anyone with experience (or who wants to gain experience) wants to document how to do so in our repo, we'd happily accept a new installation tutorial!

it seems there's already a [basis extension](https://github.com/flatcar/sysext-bakery/blob/main/create_crio_sysext.sh)

**Comment by 7h3-3mp7y-m4n** [comment]
hey I would like to take this issue

**Comment by Aakash788** [comment]
Hii @haircommander can i start working on this issue??

**Comment by haircommander** [comment]
yeah! that'd be amazing, thanks for volunteering @Aakash788
