### ISSUE TITLE
Add support for Supplemental Groups Policy

### ISSUE THREAD

**Issue by mrunalp** [cri-o/cri-o#8230]
Kubernetes added support for supplemental groups policy which should be implemented in CRI-O https://github.com/kubernetes/kubernetes/pull/117842

**Comment by everpeace** [comment]
@sohankunkerkar Thank you for signing up for this issue🙇. 

I am the author of the [KEP-3619](https://github.com/kubernetes/enhancements/issues/3619), and working on containerd to implement supplemental groups policy: https://github.com/containerd/containerd/pull/9737

Now, I target to alpha-release this feature in v1.31. I would be glad if we could expect this implemented in cri-o by v1.31. Or, if you didn't have enough bandwidth for v1.31, I am glad to work on this also in cri-o for v1.31 (I expect you will be one of the reviewers for my PR with mrunalp, in this case).

WDYT?

**Comment by kwilczynski** [comment]
@everpeace, thank you for getting in touch!

I believe @sohankunkerkar is looking into getting an implementation done for CRI-O. That said, we can, if you don't mind, add you as reviewer, once there is an open Pull Request to look at.

**Comment by everpeace** [comment]
@kwilczynski Thank you for the quick response!

> I believe @sohankunkerkar is looking into getting an implementation done for CRI-O. That said, we can, if you don't mind, add you as reviewer, once there is an open Pull Request to look at.

That sounds great! Yeah, I would be glad to review the PR 🙇
