### ISSUE TITLE
crictl -D image failed -> choosing image instance: no image found in manifest list for architecture arm64 ,variant "v8", OS linux

### ISSUE THREAD

**Issue by xuegege5290** [cri-o/cri-o#8283]
### What happened?

When i use the command "crictl -D images" to list images ,but got the result :
choosing image instance: no image found in manifest list for architecture arm64 ,variant "v8", OS linux
<img width="911" alt="0880c4c80710ef9cd51a" src="https://github.com/cri-o/cri-o/assets/50316538/9520882d-a74a-4c13-8370-ee9398804dad">
Despite restarting Crio, the issue remains; it could be due to a corrupted image, but I am unable to determine which image is corrupted. How should I resolve this kind of problem?

### What did you expect to happen?

The command crictl -D images can list the corresponding images.

### How can we reproduce it (as minimally and precisely as possible)?

Create a corrupted image?Perhaps there is a problem with the cache, but the issue persists after restarting.

### Anything else we need to know?

Use the XFS file system

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.25.4
Version:        1.25.4
GitCommit:      d11943a56e4b8d8fc50452cdc8fdf243c75ccf1e
GitCommitDate:  2024-05-07T01:16:06Z
GitTreeState:   dirty
BuildDate:      2024-06-12T07:50:33Z
GoVersion:      go1.19.13
Compiler:       gc
Platform:       linux/arm64
Linkmode:       dynamic
BuildTags:
  osusergo
  netgo
  exclude_graphdriver_devicemapper
  containers_image_ostree_stub
  libdm_no_deferred_remove
  containers_image_openpgp
  seccomp
  selinux
LDFlags:          unknown
SeccompEnabled:   true
AppArmorEnabled:  false
Dependencies:
```

```console
$ kubectl version --output=json
 "gitVersion": "v1.25.8-1+2b6d997c6-dirty"
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux  5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

Physical machine.

**Comment by xuegege5290** [comment]
I only know that it should have entered the following logic:
```go
func (svc *imageService) appendCachedResult(systemContext *types.SystemContext, ref types.ImageReference, image *storage.Image, results []ImageResult, newImageCache imageCache) ([]ImageResult, error) {
	var err error
	svc.imageCacheLock.Lock()
	cacheItem, ok := svc.imageCache[image.ID]
	svc.imageCacheLock.Unlock()
	if !ok {
		cacheItem, err = svc.buildImageCacheItem(systemContext, ref)
		if err != nil {
			return results, err
		}
		if newImageCache == nil {
			svc.imageCacheLock.Lock()
			svc.imageCache[image.ID] = cacheItem
			svc.imageCacheLock.Unlock()
		} else {
			newImageCache[image.ID] = cacheItem
		}
	} else if newImageCache != nil {
		newImageCache[image.ID] = cacheItem
```
And the enter into the function of  buildImageCacheItem
https://github.com/cri-o/cri-o/pull/7336

**Comment by xuegege5290** [comment]
If I have disturbed you, I apologize sincerely.
@haircommander

**Comment by haircommander** [comment]
I think you could use the container-storage utility can check the storage : https://github.com/containers/storage/blob/main/cmd/containers-storage/check.go 
I would recommend compiling the version corresponding to your crio version to make sure the libraries are matched

**Comment by xuegege5290** [comment]
> I think you could use the container-storage utility can check the storage : https://github.com/containers/storage/blob/main/cmd/containers-storage/check.go I would recommend compiling the version corresponding to your crio version to make sure the libraries are matched

I have used the version 1.48 of containers-storage with the -D check option, but it reports problematic images in any identical environment, even though the same environment is functioning normally. However, the version 1.25 does not have the check functionality.

**Comment by xuegege5290** [comment]
> I think you could use the container-storage utility can check the storage : https://github.com/containers/storage/blob/main/cmd/containers-storage/check.go I would recommend compiling the version corresponding to your crio version to make sure the libraries are matched
I feel that using this tool is risky. Although I haven't delved deeply into understanding the code, in actual use, the version 1.48 has altered files on my host machine.
Are there any other methods that can resolve this? It confuses me.

**Comment by xuegege5290** [comment]
> I think you could use the container-storage utility can check the storage : https://github.com/containers/storage/blob/main/cmd/containers-storage/check.go I would recommend compiling the version corresponding to your crio version to make sure the libraries are matched
I feel that using this tool is risky. Although I haven't delved deeply into understanding the code, in actual use, the version 1.48 has altered files on my host machine.
Are there any other methods that can resolve this? It confuses me.

**Comment by nalind** [comment]
`check` isn't written to change anything unless the `-r` flag is also supplied, the big exception being some "repairing symlinks" logic in the overlay driver that it can trigger in the course of normal operations.  The diagnostic information that it outputs would be helpful for discerning the differences.

The "choosing instance" error suggests to me that at one point, an image was pulled specifying a tag that refers to a manifest list, and that the pull requested a version of the image that was built for a platform other than the system's default.  With podman, for example, using `podman pull --platform=linux/amd64` would pull the x86_64 version of an image instead the arm64 version of an image, which is what the system would normally attempt to pull.  If the image hadn't been built for arm64, this would be how I'd have attempted to run it using emulation.

**Comment by xuegege5290** [comment]
> interesting I wouldn't expect it to modify anything cc @nalind
> 
> actually thinking about this more, I don't know if this is a storage corruption but more of an issue with the image itself. The error seems to be the specific OS/variant pair aren't supported by that image. is this a new issue/have you been using this image on these nodes before?

This is the containers-storage -D check infomation
```bash
layer 0d1435bd79e4253e2c086d5c6340525740f16628bfb80aa95b333f983bbf537d:
 layer 0d1435bd79e4253e2c086d5c6340525740f16628bfb80aa95b333f983bbf537d: /usr/share/doc/ca-certificates(size
:18921￫0,mode:0644￫0755,mtime:0x0￫0x66601297), layer content modified
layer 6f630b722183a5df873b142a9a7ac70213aa1e3397260a05c104d7b45b077a74:
 layer 6f630b722183a5df873b142a9a7ac70213aa1e3397260a05c104d7b45b077a74: /usr/share/doc/ca-certificates(size
:18921￫0,mode:0644￫0755,mtime:0x0￫0x66601297), layer content modified
layer 5b4e17bd99f05bbc63abfcf0e4d3e50059c6d5f201a203ba4dd0457f81806ce5:
 layer 5b4e17bd99f05bbc63abfcf0e4d3e50059c6d5f201a203ba4dd0457f81806ce5: /usr/share/doc/ca-certificates(size
:18921￫0,mode:0644￫0755,mtime:0x0￫0x66601297), layer content modified
layer 1ec240a64060a2436ca0d9c56cd391c6876629601e2dcd5ebfe43f5ad82aac97:
 layer 1ec240a64060a2436ca0d9c56cd391c6876629601e2dcd5ebfe43f5ad82aac97: /usr/share/doc/ca-certificates(size
:18921￫0,mode:0644￫0755,mtime:0x0￫0x66601297), layer content modified
layer e13241ddd8ffa4d149bcc4a9fa5baa1ec313e48f07264474ea7fa9b811e7015c:
 layer e13241ddd8ffa4d149bcc4a9fa5baa1ec313e48f07264474ea7fa9b811e7015c: layer in lower level storage driver
 not accounted for
image 65f7b8ac2c927cd4ab642820fee7d9b7b49f275ef5af077a8b779c3ad2c320f2:
 layer 6f630b722183a5df873b142a9a7ac70213aa1e3397260a05c104d7b45b077a74: /usr/share/doc/ca-certificates(size
:18921￫0,mode:0644￫0755,mtime:0x0￫0x66601297), layer content modified
 layer 0d1435bd79e4253e2c086d5c6340525740f16628bfb80aa95b333f983bbf537d: /usr/share/doc/ca-certificates(size
:18921￫0,mode:0644￫0755,mtime:0x0￫0x66601297), layer content modified
image 7ad27228c9bbe5f8d88f3fefe6f202976381912638d50e7fa9d4020a288c1175:
 layer 5b4e17bd99f05bbc63abfcf0e4d3e50059c6d5f201a203ba4dd0457f81806ce5: /usr/share/doc/ca-certificates(size
:18921￫0,mode:0644￫0755,mtime:0x0￫0x66601297), layer content modified
 layer 0d1435bd79e4253e2c086d5c6340525740f16628bfb80aa95b333f983bbf537d: /usr/share/doc/ca-certificates(size
:18921￫0,mode:0644￫0755,mtime:0x0￫0x66601297), layer content modified
image bf92b8bba0a3609f301d44549563835bf97bddb7050c9223e2cd51859ca4da4a:
 layer 1ec240a64060a2436ca0d9c56cd391c6876629601e2dcd5ebfe43f5ad82aac97: /usr/share/doc/ca-certificates(size
:18921￫0,mode:0644￫0755,mtime:0x0￫0x66601297), layer content modified
 layer 0d1435bd79e4253e2c086d5c6340525740f16628bfb80aa95b333f983bbf537d: /usr/share/doc/ca-certificates(size
:18921￫0,mode:0644￫0755,mtime:0x0￫0x66601297), layer content modified
container 4fc4a9d24aabb97c85363fb86c6911f618e02d1214b3aad8057150eb15018330:
 layer 5b4e17bd99f05bbc63abfcf0e4d3e50059c6d5f201a203ba4dd0457f81806ce5: /usr/share/doc/ca-certificates(size
:18921￫0,mode:0644￫0755,mtime:0x0￫0x66601297), layer content modified
 layer 0d1435bd79e4253e2c086d5c6340525740f16628bfb80aa95b333f983bbf537d: /usr/share/doc/ca-certificates(size
:18921￫0,mode:0644￫0755,mtime:0x0￫0x66601297), layer content modified
container 847973855a473a85ed394578c678fe9278cc956f4943d3c299e3c5d7ea126380:
 layer 6f630b722183a5df873b142a9a7ac70213aa1e3397260a05c104d7b45b077a74: /usr/share/doc/ca-certificates(size
:18921￫0,mode:0644￫0755,mtime:0x0￫0x66601297), layer content modified
 layer 0d1435bd79e4253e2c086d5c6340525740f16628bfb80aa95b333f983bbf537d: /usr/share/doc/ca-certificates(size
:18921￫0,mode:0644￫0755,mtime:0x0￫0x66601297), layer content modified
container edab86ecf9c624637a2069f97d456020c445380f34fc63bb166421477550868b:
 layer 1ec240a64060a2436ca0d9c56cd391c6876629601e2dcd5ebfe43f5ad82aac97: /usr/share/doc/ca-certificates(size
:18921￫0,mode:0644￫0755,mtime:0x0￫0x66601297), layer content modified
 layer 0d1435bd79e4253e2c086d5c6340525740f16628bfb80aa95b333f983bbf537d: /usr/share/doc/ca-certificates(size
:18921￫0,mode:0644￫0755,mtime:0x0￫0x66601297), layer content modified
shutdown: a layer is mounted: layer is in use by a container
5 layer errors, 0 read-only layer errors, 3 image errors, 0 read-only image errors, 3 container errors      

```
In this host ,the crictl -D imagescommand executed without any issues.

**Comment by xuegege5290** [comment]
> `check` isn't written to change anything unless the `-r` flag is also supplied, the big exception being some "repairing symlinks" logic in the overlay driver that it can trigger in the course of normal operations. The diagnostic information that it outputs would be helpful for discerning the differences.
> 
> The "choosing instance" error suggests to me that at one point, an image was pulled specifying a tag that refers to a manifest list, and that the pull requested a version of the image that was built for a platform other than the system's default. With podman, for example, using `podman pull --platform=linux/amd64` would pull the x86_64 version of an image instead the arm64 version of an image, which is what the system would normally attempt to pull. If the image hadn't been built for arm64, this would be how I'd have attempted to run it using emulation.

I used the `crictl inspecti imageID` command to read the manifests of these container images, all of which are based on the arm64 architecture. Additionally, I can view the image list using the `podman images` command; the version of podman I am using is 1.4.4. However, the `crictl -D images` command is unable to read information. I have compared the `ListImages` functions of both podman and crio, and found that they differ in this particular part of the function.
```go
results, err = svc.appendCachedResult(systemContext, ref, image, results, newImageCache)
			if err != nil {
				// skip reporting errors if the images haven't finished pulling
				if os.IsNotExist(err) {
					donePulling := true
					for _, name := range image.Names {
						if _, ok := ImageBeingPulled.Load(name); ok {
							donePulling = false
							break
						}
					}
```

**Comment by nalind** [comment]
podman 1.4.4 is just shy of five years old, so it's been a while, but I don't remember the storage library changing the inode numbers of the parent directories that it uses for the things it stores for each layer.  (The link count increasing also suggests that it gained a subdirectory, possibly while being mounted for scanning.)

I'm very confused about why a NewImage() call in cri-o would end up attempting to choose the arm64 version of an image from a list when it's running on an amd64 system.  It had me thinking that this was an arm64 system.

**Comment by xuegege5290** [comment]
> podman 1.4.4 is just shy of five years old, so it's been a while, but I don't remember the storage library changing the inode numbers of the parent directories that it uses for the things it stores for each layer. (The link count increasing also suggests that it gained a subdirectory, possibly while being mounted for scanning.)
> 
> I'm very confused about why a NewImage() call in cri-o would end up attempting to choose the arm64 version of an image from a list when it's running on an amd64 system. It had me thinking that this was an arm64 system.

Oh, I'm sorry for pasting the wrong host information; it has been fixed. It is indeed the arm64 architecture.

**Comment by xuegege5290** [comment]
> podman 1.4.4 is just shy of five years old, so it's been a while, but I don't remember the storage library changing the inode numbers of the parent directories that it uses for the things it stores for each layer. (The link count increasing also suggests that it gained a subdirectory, possibly while being mounted for scanning.)
> 
> I'm very confused about why a NewImage() call in cri-o would end up attempting to choose the arm64 version of an image from a list when it's running on an amd64 system. It had me thinking that this was an arm64 system.


Yes, I've also noticed the growth in inodes, but this is the read-only layer of the image (and it's the base layer, i.e., the parent layer). Why would the inode increase? It's very puzzling! Does the `containers-storage -D check` command change the inode of the read-only layer?

Back to the original question, what is the significance of the `NewImage()` call, and why does `ListImages` need to invoke `NewImage()`? Additionally, what does the cache in the `appendCachedResult` and `buildImageCacheItem` functions refer to? Is it data in memory or data on the disk in directories like `/run` or `/var/lib/containers/`?

**Comment by xuegege5290** [comment]
@haircommander  @nalind 
When creating a dual-architecture image from a single-architecture image, the intermediate single-architecture image is not deleted, and there is an issue with the image manifest. This issue is consistently reproducible. Thank you, I will close this issue. However, the behavior of the `containers-storage -D check` command puzzles me, and it cannot accurately locate the problem with the corrupted image. I will go back to the storage community to ask questions. Thank you for the help.
