### ISSUE TITLE
Flaky test on Kata runtime (reload_config)

### ISSUE THREAD

**Issue by roman-kiselenko** [cri-o/cri-o#8324]
### Which jobs are failing?

fedora-kata - reload_config

### Which tests are failing?

`kata_skip_reload_config `
https://github.com/cri-o/cri-o/blob/88fe8766ede790f465e1e86b0eccba0818736b32/contrib/test/ci/vars.yml#L109-L110

### Since when has it been failing?

This issue is used to track the status of flaky tests. The test is disabled after merge:

https://github.com/cri-o/cri-o/pull/8213 https://github.com/cri-o/cri-o/pull/7976

**Comment by littlejawa** [comment]
As explained in the [original PR](https://github.com/cri-o/cri-o/pull/8213#issuecomment-2175438242), the tests are not flaky only for kata, they are flaky for all configurations.
The kata use case is just revealing it.

In their principle, those tests are reloading crio config, then verify the content of the configuration without waiting for the reload process to complete.

For a default configuration file, the reload it quick enough to complete, and the test succeed.
For any non-default configuration, there is a chance of failure. That's typically the case for kata, where the added runtime makes the reload longer.

The tests that were added with #7976 actually started to fail in other CI jobs (without kata), and were fixed [here](https://github.com/cri-o/cri-o/commit/c3bfcd3b4cbe8b364a9c69c149e966d61cb732b6).
The fix consists in adding a log at the end of the reload process in crio, and add a call to "wait_for_log" in the tests to synchronize on this log message, making sure the test doesn't try to access the configuration before it's reloaded.

Now for the test introduced with #8213, this fix can't be applied as is: the test is doing 2 reloads, and "wait_for_log" gets out on the first occurrence of the message.
This means that the first "wait_for_log" would block as expected, but the second would not block, and the flakyness would persist.

I will try to see if I can modify "wait_for_log" to offer an option to wait for multiple occurrences of a message, or find another way to synchronize this test with crio's workflow.
