### ISSUE TITLE
Documentation should use stable releases instead of prerelease

### ISSUE THREAD

**Issue by afbjorklund** [cri-o/cri-o#8353]
Currently the documentation says:

```
KUBERNETES_VERSION=v1.30
PROJECT_PATH=prerelease:/main
```

`https://pkgs.k8s.io/core:/stable:/$KUBERNETES_VERSION/`
`https://pkgs.k8s.io/addons:/cri-o:/$PROJECT_PATH/`

While it should use stable for both?

```
KUBERNETES_VERSION=v1.30
CRIO_VERSION=$KUBERNETES_VERSION
```

`https://pkgs.k8s.io/core:/stable:/$KUBERNETES_VERSION/`
`https://pkgs.k8s.io/addons:/cri-o:/stable:/$CRIO_VERSION/`

----

Probably also need to be synched, between the locations:

https://cri-o.io/#distribution-packaging

https://docs.k8s.io/setup/production-environment/container-runtimes/#cri-o

Probably "packaging" is the one that is most up-to-date ?

https://github.com/cri-o/cri-o/blob/main/install.md#install-packaged-versions-of-cri-o

https://github.com/cri-o/packaging/blob/main/README.md#usage

----

Related issue:

* #8338

- [x] https://github.com/cri-o/cri-o.io/blob/master/index.md

- [x] https://github.com/cri-o/packaging/blob/main/README.md

**Comment by afbjorklund** [comment]
Documentation on how to install cri-o without a package manager seems to be missing?

It is only intermingled with the build-from-source docs, and adds lots of details like `nix`

**Comment by saschagrunert** [comment]
> While it should use stable for both?

Yes, working on this in https://github.com/cri-o/packaging/pull/128

**Comment by afbjorklund** [comment]
> Documentation on how to install cri-o without a package manager seems to be missing?

This was a misunderstanding, the commands for installation are available in a bash script:

https://github.com/cri-o/packaging/blob/main/README.md#using-the-static-binary-bundles-directly

Instead of stating each command like in the Kubernetes documenation, all are run at once:

> `curl https://raw.githubusercontent.com/cri-o/packaging/main/get | bash`

It expects `-t` to be set to the version, like the `$KUBERNETES_VERSION` that was used above.

```
curl https://raw.githubusercontent.com/cri-o/packaging/main/get | bash -s -- -t $CRIO_VERSION
```

**Comment by saschagrunert** [comment]
I assume we're done here. Thank you for the input @afbjorklund!
