### ISSUE TITLE
Documentation deb repository links do not work

### ISSUE THREAD

**Issue by SimonBaeumer** [cri-o/cri-o#8358]
### What happened?

I've tried to install cri-o based on the [install.md](https://github.com/cri-o/cri-o/blob/main/install.md#apt-based-operating-systems) documentation. The links did not worked and returned a `404` HTTP error.

### What did you expect to happen?

Fetch the release key from the linked page.

### How can we reproduce it (as minimally and precisely as possible)?

```
$ export VERSION="v1.30.0"
$ export OS="xUbuntu_24.04"
$ curl -L https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/$OS/Release.key
<...>
<h1>Resource is no longer available!</h1>
<...>

$ export OS="xUbuntu_22.04"
$ curl -L https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/$OS/Release.key
```

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# paste output here
```

```console
$ kubectl version --output=json
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="38 (Workstation Edition)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-21
VARIANT="Workstation Edition"
VARIANT_ID=workstation

$ uname -a
Linux <name> 6.8.9-100.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu May  2 18:50:49 UTC 2024 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
executed locally
</details>

**Comment by SimonBaeumer** [comment]
I found this issue https://github.com/cri-o/cri-o/issues/5721 as a duplicate of mine but less descriptive.

**Comment by saschagrunert** [comment]
I think we should update the docs and make this more prominent: https://github.com/cri-o/cri-o/blob/main/install.md#installation-instructions

We now ship as part of the new https://github.com/cri-o/packaging repo, not the devel:kubic ones.

**Comment by SimonBaeumer** [comment]
Thanks @saschagrunert for the quick fix, I got it working now!

**Comment by saschagrunert** [comment]
Closing this one in favor of https://github.com/cri-o/cri-o/issues/8353
