### ISSUE TITLE
Possible problem with go 1.23 (rc1)

### ISSUE THREAD

**Issue by buckaroogeek** [cri-o/cri-o#8373]
I did test builds of cri-o 1.30.3, 1.30.2, 1.30.1, and 1.29.6 on Fedora rawhide (to be Fedora 41) with go 1.23 (rc1). I am using a slightly modified version of the spec file for cri-o as used in Fedora. All builds failed at the same point. Using the same spec file, all builds succeed under Fedora 40 (current release). 

Has anyone else tried go 1.23 rc1 to build cri-o? I do not have enough data to say if this is due to the version of go or something else in Fedora rawhide.

The builds fail at the transition from building github.com/cri-o/cri-o/server/otel-collector to building github.com/cri-o/cri-o/internal/oci but I am not sure which is actually failing.

I find this in the build log when using go 1.23: ```_build/src/github.com/cri-o/cri-o/vendor/capnproto.org/go/capnp/v3/list.go:1087:10: invalid composite literal type T```, but not in the go 1.22 build logs.

**Comment by buckaroogeek** [comment]
I found https://github.com/capnproto/go-capnp/issues/575 opened by @saschagrunert 4 days ago. Will close.

**Comment by kwilczynski** [comment]
Related:

- https://github.com/cri-o/cri-o/pull/8354#issuecomment-2216960687

**Comment by dvzrv** [comment]
Hi! :wave: 

I'm packaging cri-o for Arch Linux.

This issue currently prevents me from upgrading to 1.30.5 (or rebuilding 1.30.4), as I am unable to build the project with go 1.23.0.

Why was the update not backported to the 1.30 branch to make it available in 1.30.5?

**Comment by buckaroogeek** [comment]
> Why was the update not backported to the 1.30 branch to make it available in 1.30.5?

I was kind of expecting this also as Fedora 41 (out in Oct) will supply go 1.23. Fortunately in Fedora, one of our go package maintainers built a set of rpm macros called go_vendor_tools which allows me to update a vendor module when building a golang binary package. I have been able to use this feature to create cri-o v1.29 and v1.30  rpms for Fedora 41 and newer.
