### ISSUE TITLE
Updated from PRERELEASE and now k8s node does not start any containers due to error Error: fork/exec /usr/bin/crio-conmon: no such file or directory

### ISSUE THREAD

**Issue by unixbird** [cri-o/cri-o#8385]
### What happened?

Updated via APT repos and now receive the error Error: fork/exec /usr/bin/crio-conmon: no such file or directory

### What did you expect to happen?

A typical update and a working node

### How can we reproduce it (as minimally and precisely as possible)?

update to latest PRERELEASE under kubeadm 1.29 and use the nvidia container runtime. 

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# crio version Version:        1.31.0
   GitCommit:      503d183a7168676bf4de55339e36a4d5e34be234
   GitCommitDate:  2024-07-15T08:35:30Z
   GitTreeState:   clean
   BuildDate:      1970-01-01T00:00:00Z
   GoVersion:      go1.22.3
   Compiler:       gc
   Platform:       linux/amd64
   Linkmode:       static
   BuildTags:      
     static
     netgo
     osusergo
     exclude_graphdriver_btrfs
     exclude_graphdriver_devicemapper
     seccomp
     apparmor
     selinux
     exclude_graphdriver_devicemapper
   LDFlags:          unknown
   SeccompEnabled:   true
   AppArmorEnabled:  true
```

```console
$ kubectl version --output=json
# {
  "clientVersion": {
    "major": "1",
    "minor": "29",
    "gitVersion": "v1.29.4",
    "gitCommit": "55019c83b0fd51ef4ced8c29eec2c4847f896e74",
    "gitTreeState": "clean",
    "buildDate": "2024-04-16T15:07:16Z",
    "goVersion": "go1.21.9",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v5.0.4-0.20230601165947-6ce0bf390ce3",
  "serverVersion": {
    "major": "1",
    "minor": "29",
    "gitVersion": "v1.29.4",
    "gitCommit": "55019c83b0fd51ef4ced8c29eec2c4847f896e74",
    "gitTreeState": "clean",
    "buildDate": "2024-04-16T15:00:26Z",
    "goVersion": "go1.21.9",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
# Linux yotsugi 6.8.8-2-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.8-2 (2024-06-24T09:00Z) x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by unixbird** [comment]
I'm seeing that at one point I installed the PRERELEASE instead of STABLE. I changed the repos to STABLE v1.30 as I intend to update kubeadm to 1.30 soon and it seems I cannot downgrade 

```cri-o is already the newest version (1.31.0~dev-95.1).```

**Comment by unixbird** [comment]
Alright I was able to resolve this by downgrading from that release to the latest STABLE 1.30 and then fully rebooting the node. I'll leave this up just in case however. I'm not sure if there is a big change happening in the newer versions of CRI-O/kubernetes but I could not find any resources in regards to the package crio-conmon that it mentioned.

**Comment by saschagrunert** [comment]
@unixbird I think you have to update the configuration to point to `/usr/libexec/crun` instead of the `crio-` prefixed ones. The same would apply to conmon, conmon-rs as well as runc.

**Comment by unixbird** [comment]
@saschagrunert currently my CRI-O is using runc if that matters. I had a similar issue when i was attempting to switch to crun earlier this year however. 

Currently the crio.conf points to /usr/bin/conmon which does exist

**Comment by saschagrunert** [comment]
@unixbird does `/usr/libexec/runc` exist? If so, please change the config so that it aligns with the packages.

**Comment by unixbird** [comment]
> @unixbird does `/usr/libexec/runc` exist? If so, please change the config so that it aligns with the packages.

It does not exist

**Comment by unixbird** [comment]
so I looked into this further and for some reason crio-conmon exists now. The crio.conf that I thought was pointed to /usr/bin/conmon it is actually the nvidia-container-runtime configs but is referenced in a config it made in /etc/crio/crio.conf.d/10-crio.conf

any suggestions for changing this for the future?
@saschagrunert

**Comment by saschagrunert** [comment]
@unixbird we're trying to stabilize our packages in the future and not do such breaking changes again. We need some migration strategy, I'm just sorry for the trouble! Do you need anything else or do you think we can close out this issue?

**Comment by unixbird** [comment]
Alright just wanted to make sure. We can close this out
