### ISSUE TITLE
cri-tools (`critest`) case "runtime should output OOMKilled reason" flakes when being fixed

### ISSUE THREAD

**Issue by saschagrunert** [cri-o/cri-o#8411]
Right now, the exit code and reason is not checked correctly in cri-tools: https://github.com/kubernetes-sigs/cri-tools/blob/71d27b1f93a87ff9462479a4c5f3fc8572d4715a/pkg/validate/container_linux.go#L161-L165

```go
Expect(state.ExitCode, int32(137))
```

should be 

```go
Expect(state.ExitCode).To(Equal(int32(137)))
```

This shadows the actual test result. We should check with the following combinations if everything works as expected:

- runc and conmon
- runc and conmon-rs
- crun and conmon
- crun and conmon-rs

Reason for this issue is that I fixed this behavior in https://github.com/kubernetes-sigs/cri-tools/pull/1496 which introduced failing CI tests within this repository.

**Comment by roman-kiselenko** [comment]
/unassign

Don't have enough capacity right now.

**Comment by saschagrunert** [comment]
Relevant are those lines which exists in one log but not the other:

```
 DEBUG backend:create_container{container_id="e49144605a1369bd940019747012000d02b8753a41dfa27bd8d033cb4e222568" uuid="3b9879d7-5ef0-4605-8fec-37821dc2afd6"}:promise:watch{pid=757948}:cgroup_handling: conmonrs::oom_watcher: 304: Updating OOM counter to 1
 DEBUG backend:create_container{container_id="e49144605a1369bd940019747012000d02b8753a41dfa27bd8d033cb4e222568" uuid="3b9879d7-5ef0-4605-8fec-37821dc2afd6"}:promise:watch{pid=757948}:cgroup_handling: conmonrs::oom_watcher: 244: Found OOM event counter=1
```

**Comment by saschagrunert** [comment]
Working on a fix in https://github.com/containers/conmon-rs/pull/2353

**Comment by saschagrunert** [comment]
This should be fixed with https://github.com/containers/conmon-rs/releases/tag/v0.6.4
