### ISSUE TITLE
Crio profiling Endpoint Use ListenAndServe Instead of ListenAndServeTLS

### ISSUE THREAD

**Issue by obin-tran** [cri-o/cri-o#8469]
### What happened?

Crio profiling endpoint uses ListenAndServe instead of ListenAndServeTLS, which could lead to potential security vulnerabilities
https://github.com/cri-o/cri-o/blob/main/cmd/crio/main.go#L246C20-L246C34

### What did you expect to happen?

We should use ListenAndServeTLS to ensure that the communication is encrypted and secure, rather than using ListenAndServe.

### How can we reproduce it (as minimally and precisely as possible)?

NA

### CRI-O and Kubernetes version

Any

### OS version

Any

### Additional environment details (AWS, VirtualBox, physical, etc.)

Using ListenAndServe causes security vulnerabilities.

**Comment by saschagrunert** [comment]
Thank you for opening this issue @obin-tran, I assume that's related to https://github.com/cri-o/cri-o/issues/8469.

cc @kwilczynski

**Comment by kwilczynski** [comment]
@obin-tran, what vulnerabilities specifically do you have in mind?

**Comment by kwilczynski** [comment]
To add more colour here: this specific endpoint is turned off by default and used for profiling to aid troubleshooting, so it's not turned on all the time, hopefully. Also, it should only listen on `localhost` (which is hardcoded) at the moment (something that probably should be changed to `127.0.0.1`). Thus, the surface area for attack is limited, so there isn't any immediate need for concern here.

To add, tools like Google's pprof tool support `https+insecure`, which would be fine if used directly against.

We have an issue tracking this sort of effort, per:

- https://github.com/cri-o/cri-o/issues/7513

**Comment by obin-tran** [comment]
There could be other process sniffing the loopback interface. It could be a service running in you PC, sniffing and sending data outside to a remote server.

**Comment by kwilczynski** [comment]
I will close this as a duplicate of https://github.com/cri-o/cri-o/issues/7513.
