### ISSUE TITLE
cant install latest version on ubuntu 20.04

### ISSUE THREAD

**Issue by medyagh** [cri-o/cri-o#8471]
### What happened?

here at minikube project we are stuck with v1.24 and it would be nice to upgrade [minikube crio](https://github.com/kubernetes/minikube/blob/8e81f8de25324c7bf6d9e9dbbbc301022610f1f3/deploy/kicbase/Dockerfile#L209) to latest version

following this instructions https://github.com/cri-o/cri-o/blob/release-1.24/README.md#installing-cri-o

```
$  curl https://raw.githubusercontent.com/cri-o/cri-o/main/scripts/get | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     56      0 --:--:-- --:--:-- --:--:--    56
bash: line 1: 404:: command not found

```
first the above file doesnt exist I manually changed it to ``https://raw.githubusercontent.com/cri-o/cri-o/release-1.24/scripts/get ` however I get the following error

curl https://raw.githubusercontent.com/cri-o/cri-o/release-1.24/scripts/get | bash -s -- -t v1.30.4
```
root@minikube:/home/docker# curl https://raw.githubusercontent.com/cri-o/cri-o/release-1.24/scripts/get | bash -s -- -t v1.30.4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7324  100  7324    0     0  53358      0 --:--:-- --:--:-- --:--:-- 53459
Welcome to the CRI-O install script!
Using version: v1.30.4
No architecture provided, using: arm64
Checking if all commands are available: curl jq tar
Downloading https://storage.googleapis.com/cri-o/artifacts/cri-o.arm64.v1.30.4.tar.gz to /tmp/tmp.hwHeJKbbDy
Installing CRI-O
/tmp/tmp.hwHeJKbbDy /home/docker
+ install -d -m 755 /etc/cni/net.d
+ install -D -m 755 -t /opt/cni/bin cni-plugins/LICENSE cni-plugins/README.md cni-plugins/bandwidth cni-plugins/bridge cni-plugins/dhcp cni-plugins/dummy cni-plugins/firewall cni-plugins/host-device cni-plugins/host-local cni-plugins/ipvlan cni-plugins/loopback cni-plugins/macvlan cni-plugins/portmap cni-plugins/ptp cni-plugins/sbr cni-plugins/static cni-plugins/tap cni-plugins/tuning cni-plugins/vlan cni-plugins/vrf
+ install -D -m 644 -t /etc/cni/net.d contrib/10-crio-bridge.conf
install: cannot stat 'contrib/10-crio-bridge.conf': No such file or directory
+ rm -rf -- /tmp/tmp.hwHeJKbbDy
```

### What did you expect to happen?

be able to install latest crio version on ubuntu jammy 

### How can we reproduce it (as minimally and precisely as possible)?

try installing it on latest ubuntu:jammy image

```
 docker run -it ubuntu:jammy-20240627.1 /bin/bash
```

### Anything else we need to know?
please feel free to ping me in minikube slack channel if anyone interested to fix this for the users

**Comment by afbjorklund** [comment]
I think the instructions on how install has moved to here: https://github.com/cri-o/packaging/blob/main/README.md

And the script moved from cri-o/cri-o to cri-o/packaging: https://raw.githubusercontent.com/cri-o/packaging/main/get

**Comment by afbjorklund** [comment]
But I think the problem will be to pick **one** version of CRI-O, that would work with any old version of Kubernetes?

There is an issue to move the CRI and CRI installation to the bootstrapper, but it is also needed for the provisioning...

* https://github.com/kubernetes/minikube/issues/15460

* https://github.com/kubernetes/minikube/issues/10883

**Comment by saschagrunert** [comment]
Assuming that this one is resolved now, feel free to reopen if I've missed anything.
