### ISSUE TITLE
CRI-O and Kind

### ISSUE THREAD

**Issue by kannon92** [cri-o/cri-o#8486]
We should have some way to support Kind and CRIO as a tool.

There exists a [Gist](https://gist.github.com/aojea/bd1fb766302779b77b8f68fa0a81c0f2) to help with this but it is not clear to me if this actually works.

**Comment by sohankunkerkar** [comment]
I guess you are looking for https://github.com/cri-o/cri-o/blob/main/tutorials/crio-in-kind.md

**Comment by kannon92** [comment]
Oh. I did not see that.

/close

**Comment by kannon92** [comment]
Opened up https://github.com/kubernetes-sigs/kind/pull/3718 to add this tutorial to the kind user docs.
