### ISSUE TITLE
REQUEST: New org member status for bitoku

### ISSUE THREAD

**Issue by bitoku** [cri-o/cri-o#8496]
### GitHub Username

@bitoku

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have one sponsor from the list of approvers in at least one OWNERS file within the CRI-O repository
- [X] I have spoken to my sponsor ahead of this application, and they have agreed to sponsor my application

### Sponsor

@kwilczynski

### List of contributions to the CRI-O project

- https://github.com/cri-o/cri-o/pull/8203
- https://github.com/cri-o/cri-o/pull/8418
- https://github.com/cri-o/cri-o/pull/8195
- https://github.com/cri-o/cri-o/pull/8057
- https://github.com/cri-o/cri-o/pull/8124

**Comment by kwilczynski** [comment]
@bitoku has been making excellent contributions and is a joy to work with.

I am delighted to welcome him as an official contributor to the project. :tada:

**Comment by haircommander** [comment]
+1 from me! Welcome :) lazy consensus deadline is one week away, please poke me if I forget to add you after that

**Comment by haircommander** [comment]
I sent the invite! thanks for your work so far and keep up the good work :tada:

**Comment by bitoku** [comment]
thank you!
