### ISSUE TITLE
CI Feature: Run K8s node-e2e tests in CRI-O CI

### ISSUE THREAD

**Issue by kannon92** [cri-o/cri-o#8503]
We would like to be able to run main cri-o against latest master k8s to discover any regressions.

We want to be able to test different components with cri-o and k8s that upstream is not as interested in testing.

**Comment by sohankunkerkar** [comment]
>We would like to be able to run main cri-o against latest master k8s to discover any regressions.

We are already using the [master](https://github.com/cri-o/cri-o/blob/20c06a19cb395445620c31730c0f1a0a1922eaae/contrib/test/ci/setup.yml#L47) branch for CI.
We have two periodic [jobs](https://github.com/cri-o/cri-o?tab=readme-ov-file#ci-images-and-jobs) that run every day at 8:30 PM EST to build images with the latest Kubernetes codebase.

**Comment by haircommander** [comment]
point of clarification: are we running `node_e2e` or `e2e` tests

**Comment by kannon92** [comment]
I want to run `make test-e2e-node` with the crio master and custom ignition.

**Comment by sohankunkerkar** [comment]
>point of clarification: are we running node_e2e or e2e tests

I guess we are running e2e tests

**Comment by sohankunkerkar** [comment]
>I want to run make test-e2e-node with the crio master and custom ignition.

Are you thinking of adding a periodic job, or will it run on every PR? Our CI uses the PR content, not the master branch content, for running tests against changes.

**Comment by kannon92** [comment]
I was thinking a periodic is useful and a PR.

**Comment by kannon92** [comment]
Maybe we start with a periodic and we monitor that to catch potential issues with k8s and crio.

**Comment by sohankunkerkar** [comment]
See [this](https://github.com/openshift/release/pull/39629) PR. I think you need to do something similar, but you should add a separate workflow under `step-registry/cri-o`.

**Comment by sohankunkerkar** [comment]
We have added some [coverage](https://prow.ci.openshift.org/?job=rehearse-55802-periodic-ci-cri-o-cri-o-main-periodics-crio-node-e2e-*-periodic) for e2e-node-test in CRI-O CI, and while we still need to follow up on it, it's a good start toward improved coverage.

**Comment by sohankunkerkar** [comment]
Follow up work tracked here: https://github.com/cri-o/cri-o/issues/8668
