### ISSUE TITLE
Apt Release.key file doesn't exist for version 1.31

### ISSUE THREAD

**Issue by chkp-barelelbaz** [cri-o/cri-o#8544]
### What happened?

Can't download

### What did you expect to happen?

The Release.key file to be exist

### How can we reproduce it (as minimally and precisely as possible)?

go to:
https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/addons:/cri-o:/stable:/v1.31/deb/Release.key

### CRI-O and Kubernetes version

<details>

https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/addons:/cri-o:/stable:/v1.31/deb/Release.key
Not found but:
https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/addons:/cri-o:/stable:/v1.30/deb/Release.key
works

</details>

### OS version

linux

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by saschagrunert** [comment]
Hey @chkp-barelelbaz, thank you for the request! CRI-O v1.31 has not been released yet. The key will be available once that's done.

**Comment by chkp-barelelbaz** [comment]
Thanks!
