### ISSUE TITLE
Crictl inspect reports images aren't pinned which are

### ISSUE THREAD

**Issue by MaryJulian17** [cri-o/cri-o#8555]
### What happened?

I have set pinned images using the pinned_images key in the crio config file:

> [crio.image]
> pause_image = "registry.k8s.io/pause:3.9"
> pinned_images = ["docker.io/*", "registry.k8s.io/*", "zoscp.io/*", "zoscontainers.io/*"]

When I run crictl images --pinned, they show up as pinned:
> ((root@host))>crictl images --pinned
> IMAGE                                                                    TAG                 IMAGE ID            SIZE                PINNED
> docker.io/flannel/flannel-cni-plugin                                     v1.4.1              1cd14561240a0       11MB                true
> docker.io/flannel/flannel-cni-plugin                                     v1.5.1-flannel1     1cd14561240a0       11MB                true
> docker.io/flannel/flannel                                                v0.25.1-s390x       34fa354ba8223       75.5MB              true
> docker.io/flannel/flannel                                                v0.25.5-s390x       34fa354ba8223       75.5MB              true
> registry.k8s.io/coredns/coredns                                          v1.11.1             eb48c5b93df57       64.4MB              true
> registry.k8s.io/etcd                                                     3.5.12-0            1268a6ea276ad       151MB               true

However, if I run 'crictl inspecti' on a particular image, it reports pinned as false. 
> ((root@host))>crictl inspecti 1cd14561240a0 -o json
> {
>   "status": {
>     "id": "1cd14561240a090333110875596549b2b4d10da4fd9784a318f86e0b3073c562",
>     "repoTags": [
>       "docker.io/flannel/flannel-cni-plugin:v1.4.1",
>       "docker.io/flannel/flannel-cni-plugin:v1.5.1-flannel1"
>     ],
>     "repoDigests": [
>       "docker.io/flannel/flannel-cni-plugin@sha256:8004b14a3e0985e2df3d3fc6604c40823c574c83929c829b7eb8473f7cec535b"
>     ],
>     "size": "11032762",
>     "uid": null,
>     "username": "",
>     "spec": {
>       "image": "",
>       "annotations": {},
>       "userSpecifiedImage": "",
>       "runtimeHandler": ""
>     },
>     "pinned": false
> ....

### What did you expect to happen?

I expect the pinned state to be the same between the 'crictl images' and 'crictl inspecti' commands.

### How can we reproduce it (as minimally and precisely as possible)?

Set images as pinned using the config file. Run the 'crictl images --pinned' and 'crictl inspecti <> -o json' commands.

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# paste output here
crio version 1.30.5
Version:        1.30.5
GitCommit:      df27b8f8eb49a13c522aca56ee4ec27bc7482fad
GitCommitDate:  2024-09-02T07:15:35Z
GitTreeState:   clean
BuildDate:      1970-01-01T00:00:00Z
GoVersion:      go1.22.0
Compiler:       gc
Platform:       linux/s390x
Linkmode:       static
BuildTags:
  static
  netgo
  osusergo
  exclude_graphdriver_btrfs
  exclude_graphdriver_devicemapper
  seccomp
  apparmor
  selinux
LDFlags:          unknown
SeccompEnabled:   true
AppArmorEnabled:  false
```

```console
$ kubectl version --output=json
# paste output here
{
  "clientVersion": {
    "major": "1",
    "minor": "30",
    "gitVersion": "v1.30.4",
    "gitCommit": "a51b3b711150f57ffc1f526a640ec058514ed596",
    "gitTreeState": "clean",
    "buildDate": "2024-08-14T19:04:15Z",
    "goVersion": "go1.22.5",
    "compiler": "gc",
    "platform": "linux/s390x"
  },
  "kustomizeVersion": "v5.0.4-0.20230601165947-6ce0bf390ce3",
  "serverVersion": {
    "major": "1",
    "minor": "30",
    "gitVersion": "v1.30.4",
    "gitCommit": "a51b3b711150f57ffc1f526a640ec058514ed596",
    "gitTreeState": "clean",
    "buildDate": "2024-08-14T18:57:35Z",
    "goVersion": "go1.22.5",
    "compiler": "gc",
    "platform": "linux/s390x"
  }
}
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
RHEL 9.3
$ uname -a
# paste output here
Linux host 5.14.0-362.24.1.el9.zfpc10.6.s390x #1 SMP Mon Jul 1 09:04:29 CDT 2024 s390x s390x s390x GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
n/a
</details>

**Comment by sohankunkerkar** [comment]
https://github.com/cri-o/cri-o/pull/8556 should fix the issue.
