### ISSUE TITLE
The PodSandboxStatus interface should return the Timestamp in nanoseconds.

### ISSUE THREAD

**Issue by HirazawaUi** [cri-o/cri-o#8580]
### What happened?

The kubelet determines whether the container status has changed by comparing the update times of container status. However, CRI-O currently returns the Timestamp in seconds, while kubelet expects this timestamp in nanoseconds for comparison. 
https://github.com/cri-o/cri-o/blob/11934304d11256189df8e316e195af6650a472aa/server/sandbox_status.go#L43-L48

To allow kubelet to perform more granular control over pod updates and status changes, we should return the timestamp in nanoseconds.

### What did you expect to happen?

The PodSandboxStatus interface should return the Timestamp in nanoseconds.

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# paste output here
```
N/A
```console
$ kubectl version --output=json
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>
N/A

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by kwilczynski** [comment]
@HirazawaUi, thank you for reaching out!

Nice catch! This indeed appears to be a requirement per:

_(taken from https://github.com/kubernetes/cri-api/blob/090e333fde2f9614fdec0489c4bfac3a97090f9a/pkg/apis/runtime/v1/api.pb.go#L2210-L2224)_

```go
type PodSandboxStatusResponse struct {
	// Status of the PodSandbox.
	Status *PodSandboxStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Info is extra information of the PodSandbox. The key could be arbitrary string, and
	// value should be in json format. The information could include anything useful for
	// debug, e.g. network namespace for linux container based container runtime.
	// It should only be returned non-empty when Verbose is true.
	Info map[string]string `protobuf:"bytes,2,rep,name=info,proto3" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Container statuses
	ContainersStatuses []*ContainerStatus `protobuf:"bytes,3,rep,name=containers_statuses,json=containersStatuses,proto3" json:"containers_statuses,omitempty"`
	// Timestamp in nanoseconds at which container and pod statuses were recorded
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}
```

See the above `Timestamp` struct member comment.

**Comment by saschagrunert** [comment]
Good catch @HirazawaUi, a fix is proposed in https://github.com/cri-o/cri-o/pull/8582
