### ISSUE TITLE
Looks like default runtime was changed from runc to crun without announcement

### ISSUE THREAD

**Issue by mlkishkel** [cri-o/cri-o#8626]
### What happened?

When I used cri-o on my nodes for K8s from 1.23 to 1.27 default runtime always was **runc**.
But when I downloaded new cri-o for 1.28 and 1.29 default runtime was changed to **crun**.
This may be a problem (for example https://github.com/containers/crun/issues/1566) cause I steel didn't test my cluster's behaviour on **crun** and I'm not ready to migrate from **runc** to **crun** at the moment.

Default runtime is changed cause of after installation of cri-o new default config was added etc/crio/crio.conf.d/10-crio.conf which say that crun is now default.

```bash
[crio.image]
signature_policy = "/etc/crio/policy.json"

[crio.runtime]
default_runtime = "crun"

[crio.runtime.runtimes.crun]
runtime_path = "/usr/libexec/crio/crun"
runtime_root = "/run/crun"
monitor_path = "/usr/libexec/crio/conmon"
allowed_annotations = [
    "io.containers.trace-syscall",
]

[crio.runtime.runtimes.runc]
runtime_path = "/usr/libexec/crio/runc"
runtime_root = "/run/runc"
monitor_path = "/usr/libexec/crio/conmon"
```

### What did you expect to happen?

Use **runc** as default as it should be for versions 1.28 and 1.29.  Or maybe get some release note which tells me that cri-o package from 1.28 now sets **crun** as default.

### How can we reproduce it (as minimally and precisely as possible)?

export K8S_VERSION="1.28"
export PROJECT_PATH=stable:/v${K8S_VERSION}
cat <<EOF | tee /etc/yum.repos.d/cri-o.repo
[cri-o]
name=CRI-O
baseurl=https://pkgs.k8s.io/addons:/cri-o:/$PROJECT_PATH/rpm/
enabled=1
gpgcheck=1
gpgkey=https://pkgs.k8s.io/addons:/cri-o:/$PROJECT_PATH/rpm/repodata/repomd.xml.key
EOF
dnf -y install cri-o
cat /etc/crio/crio.conf.d/10-crio.conf

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.28.10
Version:        1.28.10
GitCommit:      368cd231d174002cf25db59a2baba43e81bb2eba
GitCommitDate:  2024-09-02T09:06:37Z
GitTreeState:   clean
BuildDate:      1970-01-01T00:00:00Z
GoVersion:      go1.20.14
Compiler:       gc
Platform:       linux/arm64
Linkmode:       static
BuildTags:      
  static
  netgo
  osusergo
  exclude_graphdriver_btrfs
  exclude_graphdriver_devicemapper
  seccomp
  apparmor
  selinux
LDFlags:          unknown
SeccompEnabled:   true
AppArmorEnabled:  false
```

```console
$ kubectl version --output=json
none
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="AlmaLinux"
VERSION="9.4 (Seafoam Ocelot)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="AlmaLinux 9.4 (Seafoam Ocelot)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.4"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"
SUPPORT_END=2032-06-01
$ uname -a
Linux 5fdfb0aa58f0 6.6.22-linuxkit #1 SMP Fri Mar 29 12:21:27 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
Not important 
</details>

**Comment by sohankunkerkar** [comment]
We conducted a poll here: https://github.com/cri-o/cri-o/discussions/8507 to gather consensus around making crun the default runtime for CRI-O. The poll was around for a few days before reaching a lazy consensus, but I agree that we never made a formal announcement about it.

**Comment by haircommander** [comment]
this was done as part of the packaging migration. the cri-o binary itself doesn't default to crun until 1.31 (which did come with an announcement) but when we migrated from OBS to our current packaging solution we moved to crun without an announcement.

**Comment by haircommander** [comment]
Sorry you experienced difficulty with that! It wasn't intended. For now you can delete the drop-in file setting crun as default, or override it with a higher priority one, until you're ready to migrate.

**Comment by mlkishkel** [comment]
@haircommander  @sohankunkerkar well, sometimes that happens.

Added an override config for default runtime and everything works fine. Thanks for help!
