### ISSUE TITLE
Policy Signature Verification Fails

### ISSUE THREAD

**Issue by MaryJulian17** [cri-o/cri-o#8666]
### What happened?

Using a policy define like this, when crio starts a container, the signature verification fails with:
```
Oct 09 15:39:26 HOST crio[2094]: time="2024-10-09 15:39:26.904125667Z" level=debug msg="Response: &RunPodSandboxResponse{PodSandboxId:327f5ecea3068153344a14a569c254875c05e64daf45769fced1503f9a99066f,}" file="otel-collector/interceptors.go:75" id=a403abc5-f746-4ace-a453-9d6244b2329c name=/runtime.v1.RuntimeService/RunPodSandbox
Oct 09 15:39:26 HOST crio[2094]: time="2024-10-09 15:39:26.905114611Z" level=debug msg="Response error: checking signature of \"registry.k8s.io/kube-controller-manager:v1.31.1\": verifying signatures: Invalid crypto engine" file="otel-collector/interceptors.go:72" id=86731c11-5ad3-442b-bca6-cb2ab551cfa5 name=/runtime.v1.RuntimeService/CreateContainer
Oct 09 15:39:26 HOST crio[2094]: time="2024-10-09 15:39:26.907250611Z" level=debug msg="Request: &PodSandboxStatusRequest{PodSandboxId:327f5ecea3068153344a14a569c254875c05e64daf45769fced1503f9a99066f,Verbose:false,}" file="otel-collector/interceptors.go:63" id=0d2927fa-4a43-4607-b164-9576e13e21f6 name=/runtime.v1.RuntimeService/PodSandboxStatus
Oct 09 15:39:26 HOST crio[2094]: time="2024-10-09 15:39:26.907396114Z" level=debug msg="Response: &PodSandboxStatusResponse{Status:&PodSandboxStatus{Id:327f5ecea3068153344a14a569c254875c05e64daf45769fced1503f9a99066f,Metadata:&PodSandboxMetadata{Name:kube-scheduler-HOST,Uid:d1b799f8aa6f6a039bd87cb5c290988a,Namespace:kube-system,Attempt:0,},State:SANDBOX_READY,CreatedAt:1728488366884356609,Network:&PodSandboxNetworkStatus{Ip:,AdditionalIps:[]*PodIP{},},Linux:&LinuxPodSandboxStatus{Namespaces:&Namespace{Options:&NamespaceOption{Network:NODE,Pid:CONTAINER,Ipc:POD,TargetId:,UsernsOptions:nil,},},},Labels:map[string]string{component: kube-scheduler,io.kubernetes.container.name: POD,io.kubernetes.pod.name: kube-scheduler-HOST,io.kubernetes.pod.namespace: kube-system,io.kubernetes.pod.uid: d1b799f8aa6f6a039bd87cb5c290988a,tier: control-plane,},Annotations:map[string]string{kubernetes.io/config.hash: d1b799f8aa6f6a039bd87cb5c290988a,kubernetes.io/config.seen: 2024-10-09T15:39:25.956572130Z,kubernetes.io/config.source: file,},RuntimeHandler:,},Info:map[string]string{},ContainersStatuses:[]*ContainerStatus{},Timestamp:0,}" file="otel-collector/interceptors.go:75" id=0d2927fa-4a43-4607-b164-9576e13e21f6 name=/runtime.v1.RuntimeService/PodSandboxStatus
```

```json
 "docker": {
             "registry.k8s.io": [{
                 "type": "signedBy",
                 "keyType": "GPGKeys",
                 "keyPath": "/home/image_signing/key.gpg"
              }],
            "docker.io": [{
                "type": "signedBy",
                "keyType": "GPGKeys",
                "keyPath": "/home/image_signing/key.gpg"
              }]
        }
```

### What did you expect to happen?

The image signatures to be verified.

### How can we reproduce it (as minimally and precisely as possible)?

Run image signature verification on pod start. This is on a s390x machine.

### Anything else we need to know?

gpg version is 2.3.3

((root@ZCPA1))>gpgconf
gpg:OpenPGP:/usr/bin/gpg
gpgsm:S/MIME:/usr/bin/gpgsm
keyboxd:Public Keys:/usr/libexec/keyboxd
gpg-agent:Private Keys:/usr/bin/gpg-agent
scdaemon:Smartcards:/usr/libexec/scdaemon
dirmngr:Network:/usr/bin/dirmngr
pinentry:Passphrase Entry:/usr/bin/pinentry

/usr/lib64/libgpgme.so.11.24.1

I'm able to create a test program in both C and go that makes a new context, sets the engine info, and imports the keys. This is dynamically linked to the shared object, so that might be a difference from crio.

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.31.1
   GitCommit:      1328c762815533fb201b0c4362741bc9ab2ce2e6
   GitCommitDate:  2024-10-01T19:38:55Z
   GitTreeState:   dirty
   BuildDate:      1970-01-01T00:00:00Z
   GoVersion:      go1.22.5
   Compiler:       gc
   Platform:       linux/s390x
   Linkmode:       static
   BuildTags:
     static
     netgo
     osusergo
     exclude_graphdriver_btrfs
     seccomp
     apparmor
     selinux
     exclude_graphdriver_devicemapper
   LDFlags:          unknown
   SeccompEnabled:   true
   AppArmorEnabled:  false

```

```console
$ kubectl version --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "31",
    "gitVersion": "v1.31.1",
    "gitCommit": "948afe5ca072329a73c8e79ed5938717a5cb3d21",
    "gitTreeState": "clean",
    "buildDate": "2024-09-11T21:28:00Z",
    "goVersion": "go1.22.6",
    "compiler": "gc",
    "platform": "linux/s390x"
  },
  "kustomizeVersion": "v5.4.2"
}

```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# RHEL 9
$ uname -a
Linux HOST 5.14.0-362.24.1.el9.s390x #1 SMP Mon Jul 1 09:04:29 CDT 2024 s390x s390x s390x GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by sj98ta** [comment]
> @MaryJulian17 thank you for the report. Do you have gnupg and/or gnupg2 installed?

@saschagrunert I have worked a little bit with @MaryJulian17 on this problem.  What is installed is gnupg2.  gpupg is not installed.

**Comment by sj98ta** [comment]
@saschagrunert  It seems that crio statically links the libraries it needs?  Is that correct?

**Comment by saschagrunert** [comment]
@sj98ta yes that’s correct, libraries may have runtime dependencies, though

**Comment by sj98ta** [comment]
@saschagrunert  yes, ok... I was just wondering what versions of the libraries it was using was all.   But, thanks for looking into this.

**Comment by MaryJulian17** [comment]
@saschagrunert, what version of gnupg is cri-o using? I'm wondering if there's a version discrepancy.

**Comment by MaryJulian17** [comment]
I rebuilt cri-o with gpg 2.3.3, and signature verification worked fine

**Comment by saschagrunert** [comment]
@MaryJulian17 for `master` we use right now:
```
> nix-store -q --references $(nix-instantiate nix/default.nix)
/nix/store/v6x3cs394jgqfbi0a42pam708flxaphh-default-builder.sh
/nix/store/0fj9hk6x5yprg4v9l2b0g4fp1bnchalz-glibc-2.39-52.drv
/nix/store/s7hvxiy7934f539xy4df5mm6bsigvns0-bash-5.2p32.drv
/nix/store/sbxnap725qcfsjgp21vjd1h6qpgi6gwj-stdenv-linux.drv
/nix/store/12ffr8s5zywap9gic87cbm47badjdlgj-go-md2man-2.0.4.drv
/nix/store/5gln22m0dipgswmrbnwnd65bl2bdbbfh-install-shell-files.drv
/nix/store/5rn0693rbx2bl8ba33blifv4fqbwvbcr-go-1.23.1.drv
/nix/store/7rpzsplw6amzhrxbipx7yf6yhqays7an-which-2.21.drv
/nix/store/c0rigscly298h5jbx5g7kg1ia0zz4bmv-libgpg-error-1.50.drv
/nix/store/dgjl7qrkgina2mdqyhm7n8kyp27hjj98-make-shell-wrapper-hook.drv
/nix/store/fknxwn52fs8f96hcgqv15ql0mq4aly2k-pkg-config-wrapper-0.29.2.drv
/nix/store/hdy6jq41v9kfly5cnp3f281ag7vpnnpq-cri-o
/nix/store/ja92xhmcka2p2sbpv1s6jm0p46fhf1py-libassuan-2.5.7.drv
/nix/store/k2psy8y7mgknxc1lrlxdb7mqpwwfzjg4-libapparmor-4.0.1.drv
/nix/store/r54g078lf4iph0xp140cbcfyggi1ik0s-git-minimal-2.46.0.drv
/nix/store/s7c91avs969c3rncnlxz5y32zaaaw0fl-gpgme-1.23.2.drv
/nix/store/vh8n4lkszbr2p62z3qhwmlq6zm81gb99-libseccomp-2.5.5.drv
/nix/store/xmj2z9kss3cmvqavcls934gkby4969sc-libselinux-3.6.drv
```

**Comment by MaryJulian17** [comment]
When I increase the level of debugging for gpgme, I see this:
>2024-10-22 19:27:09 gpgme[42715.a6f5] gpgme_new: enter: r_ctx=0x000000c0009f4028
>2024-10-22 19:27:09 gpgme[42715.a6f5] gpgme-walk_path: 'gpgconf' not found in >'/nix/store/9dk5pmvkw7k02kswb7l2dihfg9jpki1g-gnupg-s390x-unknown-linux-musl-2.4.5/bin'
>2024-10-22 19:27:09 gpgme[42715.a6f5] gpgme-dinfo: gpgconf='[null]'
>2024-10-22 19:27:09 gpgme[42715.a6f5] gpgme-walk_path: 'gpg' not found in '/nix/store/9dk5pmvkw7k02kswb7l2dihfg9jpki1g->gnupg-s390x-unknown-linux-musl-2.4.5/bin'
>2024-10-22 19:27:09 gpgme[42715.a6f5] gpgme_new: leave: ctx=0x000003ffa137a830
>2024-10-22 19:27:09 gpgme[42715.a6f4] gpgme_set_protocol: enter: ctx=0x000003ffa137a830 protocol=0 (OpenPGP)

It makes me think that this could be an issue with the musl libc? It might also explain why we didn't see this when dynamically linking these libraries.

**Comment by saschagrunert** [comment]
> could be an issue with the musl libc?

Yes this could be problem. We probably have to find out where `gpgme-walk_path` searches for `gpgconf'`, but the search path (`/nix/store/9dk5pmvkw7k02kswb7l2dihfg9jpki1g-gnupg-s390x-unknown-linux-musl-2.4.5/bin`) seems incorrect.

```
> strings ./result/bin/crio | rg gnupg
/nix/store/cf3z9hdvk3y9rs1i330jzsrgms2w6fgx-gnupg-s390x-unknown-linux-musl-2.4.5/bin
```

**Comment by sj98ta** [comment]
@saschagrunert it seems it is not just gpgconf,  but gpg also cannot be found.    Of course, it is using the same search path. 

```
2024-10-22 19:27:09 gpgme[42715.a6f5] gpgme-walk_path: 'gpg' not found in '/nix/store/9dk5pmvkw7k02kswb7l2dihfg9jpki1g->gnupg-s390x-unknown-linux-musl-2.4.5/bin'

Looking at  gpgme  src/posix-util.c,  this is how the search path is derived:

```
#ifdef FIXED_SEARCH_PATH
  orig_path = FIXED_SEARCH_PATH;
#else
  orig_path = getenv ("PATH");
  if (!orig_path)
    orig_path = "/bin:/usr/bin";
#endif
  ret = walk_path_str (orig_path, pgm);

```
I am only guess at this point, but I suspect `FIXED_SEARCH_PATH` is possibly defined?   However, I suppose it could me that `getenv("PATH")` returned the path of interest as well.

**Comment by MaryJulian17** [comment]
Small update: I did create the `/nix/store/9dk5pmvkw7k02kswb7l2dihfg9jpki1g-gnupg-s390x-unknown-linux-musl-2.4.5/bin` directory on the system and added a symlink to gpg there. This allowed cri-o to continue. However, I don't think I should need to do that. 

It looks like if gpgme is compiled with the --enable-fixed-path option, FIXED_SEARCH_PATH is set and that defines the directory gpgme looks for gpg in. That option is set in the default.nix file of gpgme in nixpkgs (https://github.com/nixos/nixpkgs/blob/9a79bc998d0207268c8e00b737e896e2e717ccd2/pkgs/development/libraries/gpgme/default.nix#L94). 

Is there any way for the nix files that cri-o defines to unset that option? I'm surprised that this is an issue just for s390x, but is this working on other architectures?

**Comment by sj98ta** [comment]
I don't know much at all about nix, and the build process for this.   From what little I have read, it seems that the packages were intended to run on NixOS.   However, it seems that nix packages can run on other distros, if they are statically linked, which cri-o should be.   I guess 'under the covers',  I am sure how the /nix/store directories are package within the executable, such that it `gpgme` can find `gpg`.  Or, is it not withing the binary, and that is the problem?

**Comment by saschagrunert** [comment]
@MaryJulian17 @sj98ta let's give it a shot: https://github.com/cri-o/cri-o/pull/8708

**Comment by sj98ta** [comment]
@saschagrunert  Thank you.... You updated this, just as I was about to ask you if we could override or remove the `--enable-fixed-path` in the `gpgme` `configureFlags`.    

I am sure @MaryJulian17  will try this change as soon as she gets in this morning.  

Thank you!

**Comment by MaryJulian17** [comment]
Thank you @saschagrunert! I think that fixed the gpgme issue. I'm running into an error starting pods, but I suspect that's just running k8s 1.31 while these binaries were built for 1.32.

**Comment by RedHead17** [comment]
Can this be put in the next 1.31 release? I noticed it wasn't in 1.31.2
