### ISSUE TITLE
Problem with the repository's GPG key for some CRI-O versions (at least 1.31.3 and 1.29) Works for 1.24 

### ISSUE THREAD

**Issue by AlexHeiphetz** [cri-o/cri-o#8841]
### What happened?

$ curl -L https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$CRIO_VERSION/$OS/Release.key | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
100   370  100   370    0     0    621      0 --:--:-- --:--:-- --:--:--   621
100   371  100   371    0     0    486      0 --:--:-- --:--:-- --:--:--   486
100   372  100   372    0     0    399      0 --:--:-- --:--:-- --:--:--   399
100   373  100   373    0     0    339      0  0:00:01  0:00:01 --:--:--   339
100   374  100   374    0     0    295      0  0:00:01  0:00:01 --:--:--     0
100  1083    0  1083    0     0    753      0 --:--:--  0:00:01 --:--:--   753
gpg: no valid OpenPGP data found.

### What did you expect to happen?

Receive "OK"

### How can we reproduce it (as minimally and precisely as possible)?

# Set OS and CRI-O version variables
OS="xUbuntu_22.04"
CRIO_VERSION="1.33.1"  

# Add the CRI-O repository to sources.list.d
echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$CRIO_VERSION/$OS/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$CRIO_VERSION.list

# Download the GPG keys and store them in the trusted.gpg.d directory
sudo mkdir -p /etc/apt/keyrings
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/libcontainers-stable.gpg
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$CRIO_VERSION/$OS/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/libcontainers-stable-cri-o.gpg

# Use the [signed-by] option in the sources.list.d files to specify the key for each repository
sudo sed -i "s|deb https://download\.opensuse\.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /|deb [signed-by=/etc/apt/keyrings/libcontainers-stable.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /|" /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
sudo sed -i "s|deb https://download\.opensuse\.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$CRIO_VERSION/$OS/ /|deb [signed-by=/etc/apt/keyrings/libcontainers-stable-cri-o.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$CRIO_VERSION/$OS/ /|" /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$CRIO_VERSION.list

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
$ crio --version
crio version 1.24.6
Version:          1.24.6
GitCommit:        4bfe15a9feb74ffc95e66a21c04b15fa7bbc2b90
GitTreeState:     clean
BuildDate:        2023-06-14T14:44:50Z
GoVersion:        go1.18.2
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        apparmor, exclude_graphdriver_devicemapper, containers_image_ostree_stub, seccomp
SeccompEnabled:   true
AppArmorEnabled:  false

```

```console
$ kubectl version --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "31",
    "gitVersion": "v1.31.4",
    "gitCommit": "a78aa47129b8539636eb86a9d00e31b2720fe06b",
    "gitTreeState": "clean",
    "buildDate": "2024-12-10T11:43:21Z",
    "goVersion": "go1.22.9",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v5.4.2"
}

```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

$ uname -a
Linux thinkpad 6.8.0-49-generic #49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov  4 02:06:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux


</details>


### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by saschagrunert** [comment]
That's an issue with the kubic packages, we mainly maintain them nowadays in https://github.com/cri-o/packaging
